### ISSUE TITLE
Thank you for using GitHub for issue-tracking.

### ISSUE THREAD

**Issue by koderian** [Yesssssman/epicfightmod#1]

**Comment by Yesssssman** [comment]
yeah, this looks better. I'm getting used to this.

**Comment by koderian** [comment]
@Yesssssman Question, for version 2.0.0, I see you fixed the shader issue. It says though that AimHelper & CollisionBox Disabled temporararily. What will this impact?

**Comment by Yesssssman** [comment]
It's actually because I didn't completed it. It wouldn't have any problems with the mod after I complete it.
