### ISSUE TITLE
[BUG] Wither dashes don't hit targets, including Wither Ghost Attacks.

### ISSUE THREAD

**Issue by Fillybodyknow** [Yesssssman/epicfightmod#1000]
Epic Fight  18.1.13-beta
Forge 1.18.2 - 40.1.19

[https://youtu.be/UTSGGj9zARo](url)

**Comment by Yesssssman** [comment]
I can't see your link

**Comment by Fillybodyknow** [comment]
https://youtu.be/UTSGGj9zARo

**Comment by Yesssssman** [comment]
ok, I found the problem. thanks for your report

**Comment by Yesssssman** [comment]
Fixed in 18.1.16
