### ISSUE TITLE
entity models not rendering

### ISSUE THREAD

**Issue by LordAzarael** [Yesssssman/epicfightmod#1001]
when i disabled epic fight entities began rendering again

here is the mod list:
Twigs
Alex's Delight
Alex's Mobs
AppleSkin
Architectury API (Fabric/Forge)
AutoRegLib
Better Animals Plus
BetterF3
BlockUI
Builder's Delight (Forge)
Building Gadgets
Butcher's Delight
Catalogue
Citadel
Cloth Config API (Fabric/Forge)
Configured
Construction Wand
Corn Delight
Create
Create Confectionery
Create Crafts & Additions
Create: Steam Powered
Cultural Delights
Decorative Blocks
Eccentric Tome
Epic Fight
Epic Knights: Shields, Armor and Weapons
FallingTree (Forge&Fabric)
Farmer's Delight
Farmer's Respite
Feature NBT Deadlock Be Gone
Flywheel
FTB Library (Forge)
Geolosys
Honey Expansion (Add-on for Farmer's Delight)
Iceberg
Immersive Engineering
Immersive Weathering [FORGE]
Integrated Dungeons and Structures
Inventory HUD+
Just Enough Items (JEI)
Just Enough Resources (JER)
Legendary Tooltips
Magnesium/Rubidium Extras
Mysterious Mountain Lib
Neat
Oculus
Patchouli
Quark
Radium Reforged
Radon
Replanter
Repurposed Structures (Forge)
Rubidium
ShetiPhianCore
Sophisticated Backpacks
Sophisticated Core
Structurize
Terralith
Terraqueous
Thatched
The One Probe
Untamed Wilds
Valhelsia Core
Valhelsia Structures
Verdure
Xaero's Minimap
Xaero's World Map
YUNG's API (Forge)
YUNG's Better Dungeons (Forge)
YUNG's Better Mineshafts (Forge)
YUNG's Better Strongholds (Forge)
YUNG's Bridges (Forge)
YUNG's Extras (Forge)

**Comment by MetalKnight56** [comment]
Please provide your MC version, forge version and current efms version

**Comment by Yesssssman** [comment]
I can't check all mods one by one since it will make me fatigued seriously. And please attach the screen capture or something when you report the visual bugs.

**Comment by pikasalt** [comment]
Try removing fallingtrees
