### ISSUE TITLE
Cant dodge

### ISSUE THREAD

**Issue by Andzhay** [Yesssssman/epicfightmod#1002]
I have been trying to get the doge to work. I have done all I could think of and nothing is working. I changed key binds and everything. Could I get any help with this?

**Comment by MetalKnight56** [comment]
What version are you on?

**Comment by DragonFireEFX** [comment]
You cannot use dodge until you have learned the skill and if you have learned the skill and still not working then there might be an issue

**Comment by Andzhay** [comment]
ah ok its working now thank you.
