### ISSUE TITLE
[Bug] Armor stand recognized like a living entity

### ISSUE THREAD

**Issue by Zano1999** [Yesssssman/epicfightmod#1003]
I don't know if is it intentional, but the armor stand have the same indicator on the head of the other living entities

**Comment by MetalKnight56** [comment]
Please provide your MC version, forge version and current mod version

**Comment by Zano1999** [comment]
MC versione: 1.18.2
Forge version: 40.1.16
Mod versione: 18.1.13-beta

**Comment by MetalKnight56** [comment]
> 

Have you tried downgrading your forge version to see if the issue persists ?

**Comment by Zano1999** [comment]
No, because other mods required updated forge

**Comment by MetalKnight56** [comment]
> No, because other mods required updated forge

Do you have any mods that change something in armor stands ?

**Comment by Zano1999** [comment]
Quark, do the arms on the armors stands

**Comment by MetalKnight56** [comment]
> I don't know if is it intentional, but the armor stand have the same indicator on the head of the other living entities

Just tested, yes i believe this is indeed a bug, will pass on to the mod's developer so it can be fixxed in the upcomming update. Thanks for reporting !

**Comment by Zano1999** [comment]
Alright, thanks to you :)

**Comment by Yesssssman** [comment]
Fixed in 18.1.15
