### ISSUE TITLE
Crash Report: Rendering entity in world

### ISSUE THREAD

**Issue by aedreu** [Yesssssman/epicfightmod#1005]
**Versions**
minecraft: 1.18.2
epicfightmod: 18.1.16
forge: 40.1.16
java: 18

**Description**
CTD whenever I use minecolonies build tool. It seemed to be working ok with 18.1.15.

crash log:
https://pastebin.com/LJqSLVcS

**Comment by Yesssssman** [comment]
https://github.com/ldtteam/Structurize/issues/504#issuecomment-1120669693

Please update your Minecolonies version.
