### ISSUE TITLE
Ender Dragon crash [18.1.16]

### ISSUE THREAD

**Issue by MetalKnight56** [Yesssssman/epicfightmod#1007]
(https://mclo.gs/rTuUsyM) - Latest.log

Tried summoning an Ender Dragon and started following it. It immediatly crashed when i switched to survival mode. 

Forge: 40.1.0
Minecraft: 1.18.2

**Comment by Yesssssman** [comment]
#999

**Comment by Yesssssman** [comment]
Yes, but both crash reports have the same contents. I guess he misunderstood something.

**Comment by Yesssssman** [comment]
Fixed in 18.1.18
