### ISSUE TITLE
Game freezing when evoker/vex are summoned/spawned [18.1.16]

### ISSUE THREAD

**Issue by MetalKnight56** [Yesssssman/epicfightmod#1008]
So after leaving vex/evokers in some random spot and letting them fight for a while causes the game to freeze and bassically makes it so i can't do anything, like drop items, spawn mobs, get items from the ground. All entities stop mid air and i can't deal any damage. Video showing it:

https://www.youtube.com/watch?v=sM_3wTCwIXA (you may need to copy the link and open a new tab for it to show)

(https://mclo.gs/VFSn7q8) - Latest.log

Forge: 40.1.0
Minecraft: 1.18.2

**Comment by Woodgoldtwo** [comment]
I had this problem to

**Comment by Woodgoldtwo** [comment]
You can't switch gamemodes, use the chat or interact with anything. 
And if you try to leave the world, the game will freeze.

**Comment by Yesssssman** [comment]
Fixed in 18.1.18
