### ISSUE TITLE
[BUG] Ender dragon can't damage players by hitting.

### ISSUE THREAD

**Issue by Fillybodyknow** [Yesssssman/epicfightmod#1010]
Epic Fight 18.1.16

Forge 1.18.2 - 40.1.19

**Comment by Fillybodyknow** [comment]
https://youtu.be/mrCyWGRsUVA

**Comment by Yesssssman** [comment]
Have you set up any data pack?

**Comment by Fillybodyknow** [comment]
I tried Forge each Version. 40.1.10 and up. Ender dragon bugs. 40.1.9 and down. Ender dragon is normal.

**Comment by Yesssssman** [comment]
Then the version above 40.1.9 is incompatible. I'll update the forge version when they say the latest version "recommended"

**Comment by Fillybodyknow** [comment]
OK.
