### ISSUE TITLE
[BUG] Optifine's emissive texture/Combat mode

### ISSUE THREAD

**Issue by noxyaberry** [Yesssssman/epicfightmod#1011]
Hi, i did some tests recently with emissives textures on weapons and i noticed when on combat mode the player model shines. Sharing two screenshots when off/on combat mode.
![2022-05-16_17 24 59](https://user-images.githubusercontent.com/7552359/168632351-bffeddb4-9f2a-4b8b-8ee2-274125045c1a.png)
![2022-05-16_17 25 06](https://user-images.githubusercontent.com/7552359/168632374-e2718dcd-97f1-423f-bbc1-8fd1d6e433ae.png)

**Comment by Yesssssman** [comment]
Ahh, this was Optifine. Optifine issues are hard to fix for now. Since it's not an open source.
