### ISSUE TITLE
Bug with armor from beyond earth

### ISSUE THREAD

**Issue by janerikk** [Yesssssman/epicfightmod#1012]
Space suit armor looks weird in combat stance (from Beyond Earth mod) https://www.curseforge.com/minecraft/mc-mods/beyond-earth
![arm1](https://user-images.githubusercontent.com/105665484/168652396-86025385-8dd9-4666-bba4-b942ba23490e.JPG)
![arm2](https://user-images.githubusercontent.com/105665484/168652394-dc5f2abd-e1c3-4725-807e-a554105cd058.JPG)
As well as semitransparent textures not working but that's less important.
![armnoh1](https://user-images.githubusercontent.com/105665484/168652392-97bd1536-056e-40a0-9b42-517179512531.JPG)
![armnoh2](https://user-images.githubusercontent.com/105665484/168652388-bdb82959-edb8-4fd8-a426-247fd9129b70.JPG)

I do not have OptiFine installed.

**Comment by Yesssssman** [comment]
https://github.com/Yesssssman/epicfightmod/wiki/Creating-custom-armor-resource-pack
Here's a guideline on how to make custom armors compatible.

**Comment by VanilaBOI** [comment]
In the Epic Fight Discord, there is a Resourcepack for Beyoned Earth.
https://discordapp.com/channels/955784714264932362/964701095056257034/972629452167200859

**Comment by MetalKnight56** [comment]
#536 - Duplicate
