### ISSUE TITLE
Optifine Conflict: 1.18.2

### ISSUE THREAD

**Issue by FlamingLlama** [Yesssssman/epicfightmod#1017]
![Base Profile Screenshot 2022 05 18 - 10 09 55 35](https://user-images.githubusercontent.com/105822509/169153941-e0c9c133-c79c-4eef-9939-7e69f7f11456.png)
Using Optifine HD U7 (As of writing, the most updated version) and Epic Fight 18.1.16 (Also newest as of writing) results in the above issue where all blocks have extreme texture breakage.

**Comment by MetalKnight56** [comment]
Delete optifine config and it will fix this issue, this won't be fixxed now since optifine is not open source

**Comment by Yesssssman** [comment]
Is this even involved with epicfight? I've never done anything with block textures.
