### ISSUE TITLE
Crash Report: Rendering entity in world

### ISSUE THREAD

**Issue by Bohemiangrove666** [Yesssssman/epicfightmod#1018]
Hi,

I host a Minecraft server (1.18.2 Better Minecraft Plus) and recently I have been experiencing a Minecraft Crash, it says "Description: Rendering entity in the world", but it doesn't crash the server, just the client-side. I was told by my hosting company that the problem was Epic Fight mod and that I should try reaching you. 

https://pastebin.com/gGCZQ0da
https://pastebin.com/DDbg3WDX

The Mod List is included in the crash log.

https://crashy.net/mJptY90xmkH0M8orZh8D

"NullPointerException: Cannot invoke "yesman.epicfight.api.client.model.ClientModel.getProperties()" because "model" is null"

**Comment by Yesssssman** [comment]
#1013

**Comment by Yesssssman** [comment]
Fixed in 18.1.18
