### ISSUE TITLE
[Suggestion]Some QoL suggestion for MC1.12

### ISSUE THREAD

**Issue by HuangAdam** [Yesssssman/epicfightmod#1019]
In MC1.12, The content of the mod is almost enough.
Compare with higher version (above 1.16), it focuses on overhaul vanilla attack instead of skill.
Epic fight enhance vanilla attack system. Each attack type is distinctive, and usage scenarios are different.

However, in MC1.12, it is difficult to get started, since it cannot work with other mods well.
My friend kill me with a gun (Vic's Modern Warfare) in game. But I can't see any detail about he aimed his gun at me. For the reason that, he aimed at me in battle mode.

Aimed at you in mine mode:
![2022-05-19_16 57 51](https://user-images.githubusercontent.com/46439030/169255224-771e0e09-094e-49dd-a379-2d121dc06e42.png)
Aimed at you in battle mode:
![2022-05-19_16 58 05](https://user-images.githubusercontent.com/46439030/169255326-5edabbec-b565-4f73-bf9b-696006f53a01.png)

Please add a config, that is battle mode blacklist and whitelist, similar with auto preparation of the higher version.
Sorry to waste your time, and thanks for your reading.

**Comment by VanilaBOI** [comment]
Well first of 1.12 is discontinued, so it won't get any updates any more.
For a work around I would recommend you turn on Filter animations so you have the normal model in mine mode

**Comment by HuangAdam** [comment]
> Well first of 1.12 is discontinued, so it won't get any updates any more. For a work around I would recommend you turn on Filter animations so you have the normal model in mine mode

Yeah, I know. I just hope developers discover the mod in 1.12 is not completed. Even the workaround have been used in higher version. Maybe it would be fixed?

> For a work around I would recommend you turn on Filter animations so you have the normal model in mine mode

I have turned on it. But it needs to choose weapon and toggle on the battle mode step by step. For a fight system, It is not smart, isn't it?

**Comment by Yesssssman** [comment]
1.12.2 is not supported anymore. Its source code is old and incompatible with recent versions so it's like I have to develop from zero.
