### ISSUE TITLE
Request: Separate option to turn off target indicator

### ISSUE THREAD

**Issue by Alaberti** [Yesssssman/epicfightmod#102]
Hello!

I appreciate the option to turn off health indicators, but I was hoping to have a different option to turn off the target indicator so that I can keep the health indicator on. 

I have a pack with mobs that hide, but if the player gets close enough the target indicator will reveal the hidden mob right before they jump out. 

Please and thank you!

**Comment by Yesssssman** [comment]
Ooh, I haven't considered that. I'd make it invisible when entities are affected by the invisible potion at the same time as I add an option to turn off them. Thank you.

**Comment by Alaberti** [comment]
I see the update, thank you so much!
