### ISSUE TITLE
Epic Fight Mod(Custom Entities for a different mod)

### ISSUE THREAD

**Issue by antended** [Yesssssman/epicfightmod#1021]
hi, im trying to add animations for the custom entities from a different mod, to specify, the Demon Slayer Mod. and when i tried it the textures are glitched wherein the head is invisible and the skin is just messed up. also, the entities attack each other, even tho they're not supposed to. can someone help me fix this? (tbh i just want to add animations for the efm mod to the demon slayer mod)

**Comment by NeoIGuess** [comment]
The entity's from the demon slayer mod's textures are not the same as a normal mob's textures, so you're going to have to make a texture pack to make them match. This video explains it better https://youtu.be/QdzbaOZae8U

**Comment by antended** [comment]
> The entity's from the demon slayer mod's textures are not the same as a normal mob's textures, so you're going to have to make a texture pack to make them match. This video explains it better https://youtu.be/QdzbaOZae8U

i watched this video already but idk if i have to extract the JAR file into a zip and edit the config, or just read it as a zip file once and leave it be as a JAR file. idk if im making sense tho

**Comment by antended** [comment]
> The entity's from the demon slayer mod's textures are not the same as a normal mob's textures, so you're going to have to make a texture pack to make them match. This video explains it better https://youtu.be/QdzbaOZae8U

btw if u have a discord i can show u what the problem is so that i can explain it better

**Comment by Yesssssman** [comment]
Recommend using the data pack for advanced settings:

https://github.com/Yesssssman/epicfightmod/wiki/Custom-entity-datapack
