### ISSUE TITLE
regarding custom entity behaviors

### ISSUE THREAD

**Issue by antended** [Yesssssman/epicfightmod#1022]
same problem for demon slayer mod. i tried to add efm animations to the entities and it works, only problem now is that the mobs attack anything , even for the same entity type. i need help with this.

**Comment by Yesssssman** [comment]
Datapack entity in 1.18.2 supports the more advanced functionality that you mentioned but seems like demon slayer doesn't port the 1.18.2 version yet.

**Comment by antended** [comment]
is there a workaround for this issue?

**Comment by Yesssssman** [comment]
As far as now, no.

**Comment by antended** [comment]
oh ok, thanks for the info. i hope you can fix it soon.
