### ISSUE TITLE
Server crashes when you are fighting a witch or a drowned.

### ISSUE THREAD

**Issue by logicallydimp23** [Yesssssman/epicfightmod#1024]
[crash-2022-05-21_05.56.25-server.txt](https://github.com/Yesssssman/epicfightmod/files/8747098/crash-2022-05-21_05.56.25-server.txt)

When the witch do a range attack the server crashes.

Minecraft v. 1.18.2 btw

**Comment by Yesssssman** [comment]
Have you installed any other mods?

**Comment by Yesssssman** [comment]
Could you check if this problem still remains after you remove all other mods?
