### ISSUE TITLE
Conflict with Kingdom Keys

### ISSUE THREAD

**Issue by Abelatox** [Yesssssman/epicfightmod#1025]
Hello, so it seems in a recent Epic Fight Mod update it conflicts with Kingdom Keys mod, 
Didn't have a conflict in: EpicFight-18.0.3-beta (Probably later ones too but I don't have any proof)
Has a conflict in: EpicFight-18.1.18-beta
The conflict happens when in Kingdom Keys you enable an ability (Synch Blade) which allows you to summon one weapon in each hand, without the ability it has no issues.

https://pastebin.com/23D7haTk

Thanks ^^

**Comment by Yesssssman** [comment]
Could you post the source code of how that skill works?

**Comment by Abelatox** [comment]
Sure, essentially to summon a weapon it spawns it in your mainhand, but if the skill is enabled it does that in the offhand too (slot 40).
https://github.com/Wehavecookies56/Kingdom-Keys/blob/master/src/main/java/online/kingdomkeys/kingdomkeys/network/cts/CSSummonKeyblade.java

**Comment by Yesssssman** [comment]
Fixed in 18.1.19
