### ISSUE TITLE
[Suggestion & Bug] Texture pack

### ISSUE THREAD

**Issue by iLazy7** [Yesssssman/epicfightmod#1027]
Please a compatibility with Tissou's Zombie Texturepack. 
There's a bug when using Tissou's Zombie Texturepack I've noticed that when using that texture pack the zombie mob skin won't randomize and only one skin will spawn for all zombie even though i'm using optifine and i figured that the epic fight mod and that pack is not compatible, i'm hoping that you guys might fix this for more immersive gameplay in the game.

**Comment by VanilaBOI** [comment]
Sorry but optifine is just not compatible and probably will never be.

**Comment by VanilaBOI** [comment]
https://github.com/Yesssssman/epicfightmod/issues/1016

**Comment by Yesssssman** [comment]
yeah, that's what I want to say. sorry.
