### ISSUE TITLE
GAMERULE KEEPSKILL FAILED 1.16.5 IN SERVER COMMAND

### ISSUE THREAD

**Issue by WerelWolf** [Yesssssman/epicfightmod#1030]
Server 1.16.5 is not working keepSkill, when the player comes back from death all skills are gone

**Comment by WerelWolf** [comment]
@Yesssssman hi ?

**Comment by Yesssssman** [comment]
You should provide detailed information. It does not happen in regular forge servers. so I won't give any support to this.

**Comment by Yesssssman** [comment]
If the Mohist's code blew up all epicfight skills, accidently or intended whatever, I can't fix this issue cause it totally depends on Mohist developers.
