### ISSUE TITLE
[1.16.5] no pvp protection  against efm

### ISSUE THREAD

**Issue by Zoraior** [Yesssssman/epicfightmod#1037]
I have tried protect my world spawn server against efm but nothing works, World Guard Plugins, pvp off on server.properties
nothing works

**Comment by Zoraior** [comment]
https://user-images.githubusercontent.com/76544300/170545017-b68069c4-cab9-4687-bbc6-90b9bde044e3.mp4

**Comment by Yesssssman** [comment]
oh... please use the team system as a temporary solution.

**Comment by Zoraior** [comment]
Any update about that?

**Comment by Yesssssman** [comment]
I'm working on 1.18.2 for now. Once I done it, I'll work on 1.16.5 at once.

**Comment by Yesssssman** [comment]
Fixed in 16.6.0
