### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by DragonAstemirN** [Yesssssman/epicfightmod#1040]
Hello greetings.
I think it would be a good idea to be able to have the katana unsheathed with the right click, and that it be sheathed again only with the same right click.

**Comment by VanilaBOI** [comment]
While it would be nice to be able to manually sheeth it for visual effects, it sheeths itself after 5 seconds because it makes the next attack a lot quicker. Also the right click would interf with the guard ability.

**Comment by DragonAstemirN** [comment]
It is true that there is that interaction with guard ability, but it could be solved by doing a fast press for holster and draw, and a constant press for the skill as it does now.
A custom key could also be used.
Of course this is all visual, thanks for the time I love the mod
![2022-05-30_03 46 14](https://user-images.githubusercontent.com/94336869/170968482-2941506d-29ca-475d-9d7f-ebdc14e8934d.png)
![2022-05-30_03 46 22](https://user-images.githubusercontent.com/94336869/170968503-50bab207-36a4-4895-b677-15b76cb813d4.png)
![2022-05-30_03 46 35](https://user-images.githubusercontent.com/94336869/170968529-7b3a156f-02b9-4d3f-a682-dfdd74c2d106.png)
This is also the reason for my request, thanks again

**Comment by VanilaBOI** [comment]
Whoa, wait I don't remember colt's armor looking like that?

**Comment by DragonAstemirN** [comment]
Sorry, it's a mix with the armor of (Dawn Of Time - Builder Edition) In its update for 1.16.5
