### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Aromiya-AR15** [Yesssssman/epicfightmod#1042]
I want to use a 3D model for a rapier, using dagger animation and fight style. I noticed that it has 1 block, or lower than 1 block hit reach, so I'd like to ask that does the "reach" attribute affact to epic fight? And how to increase reach distance of the dagger animation. Thank you for reading this and hope the mod will have more successful future
Note: I'm using 1.16.5 version of the mod

**Comment by Woodgoldtwo** [comment]
All weapon types have already have a set hitbox

So if you set a modded weapon as a dagger, it will use the normal dagger hitbox

**Comment by Woodgoldtwo** [comment]
But yes. A way to customize the hitbox would be very nice

**Comment by Aromiya-AR15** [comment]
> But yes. A way to customize the hitbox would be very nice

I really hope that the "reach" attribute can work with epic fight so that I can extend the tip of the dagger a little bit

**Comment by Yesssssman** [comment]
his function was added after 18.2.6. Sorry for the late notification.
