### ISSUE TITLE
Mod dosnt work with optifine

### ISSUE THREAD

**Issue by Ainster345** [Yesssssman/epicfightmod#1043]
I've tried multiple versions of forge/optifine and the mod itself in 1.18.2 and it breaks every texture into a mess every time and I have no idea how to fix it or why I've seen literally no one else having this issue
(screenshot below)

![2022-05-31_23 17 30](https://user-images.githubusercontent.com/106642517/171320987-7e538d6d-489b-4954-bc27-d8793f48952e.png)

**Comment by Aromiya-AR15** [comment]
do you have any resource pack enabled? I think it is from resource pack problem

**Comment by Ainster345** [comment]
> 

nope, not a shader or resource pack. I'm using a different optimization mod now and it fine
