### ISSUE TITLE
Custom Resource pack

### ISSUE THREAD

**Issue by WoidRIPER** [Yesssssman/epicfightmod#1044]
I want to know how to create my own resource pack for Epic Fight with custom animations.
I found the character models and mobs in the game files, but I do not know what program they can be edited. I tried Blender.

**Comment by MetalKnight56** [comment]
Please note that all blender versions are 2.79.
Json exporter for Epic Fight version over the 17.0.5 
- From the official discord thread made by yesman

**Comment by WoidRIPER** [comment]
Where can I find the Json exporter plugin?

**Comment by WoidRIPER** [comment]
Thank you.

**Comment by WoidRIPER** [comment]
Thank you.
