### ISSUE TITLE
1.16.5 Crashing

### ISSUE THREAD

**Issue by FryFritters** [Yesssssman/epicfightmod#1045]
1.16.5 Crashes for a unknown reason, not even a in game issue, when I go to load up the world, thats when it crashes, and Im unsure of what to do at the moment. I try to run this with a MHA mod.

**Comment by zargogo** [comment]
You should provide a crash log

**Comment by FryFritters** [comment]
[Crash report.txt](https://github.com/Yesssssman/epicfightmod/files/8825720/Crash.report.txt)

**Comment by FryFritters** [comment]
> Try installing the latest epic fight and recommended forge version. it's written in changelog

Latest epic fight? Wdym by that.

**Comment by Yesssssman** [comment]
Curseforge.

![image](https://user-images.githubusercontent.com/79469058/172393269-b7f38dc4-9d7e-4077-9476-10310948b007.png)
