### ISSUE TITLE
Can't see the map

### ISSUE THREAD

**Issue by non141514** [Yesssssman/epicfightmod#1048]
Game Version 1.18.2
Mod Version 18.1.20-beta

**Comment by VanilaBOI** [comment]
What map?
Could give a bit more information?

**Comment by non141514** [comment]
> What map? Could give a bit more information?
treasure map

**Comment by VanilaBOI** [comment]
![2022-06-05_21 02 52](https://user-images.githubusercontent.com/86358160/172066349-83de4921-e782-4101-9cb6-b7e8bda77f1f.png)
Sorry but I don't know what you mean?

**Comment by Yesssssman** [comment]
If you meant you can't see the maps when you're in first person, Use the "filter animation" option. It would disable the animated model during mining mode.
