### ISSUE TITLE
Support/Optimization for High resolution skins

### ISSUE THREAD

**Issue by Red-TF2-Sniper** [Yesssssman/epicfightmod#1050]
EFM already does "somewhat"  supports 1024 x 512 and other HD skins in fight mode but tanks the performance heavily and cause the integral server to have long ticks. This can sometimes go long enough that the server watchdog kicks in.

Mod to achieve the HD Skins: OfflineSkins / Link: https://www.curseforge.com/minecraft/mc-mods/offlineskins

**Comment by Yesssssman** [comment]
Sorry but the incompatibility with optifine features would not be supported since it is not open sourced and very hard to work at same time.
