### ISSUE TITLE
Can't hit Ender Dragon [1.16.5]

### ISSUE THREAD

**Issue by Sazuzaki** [Yesssssman/epicfightmod#1051]
Heyo, Epic Fight battle mode can't hit the Ender Dragon. I tested it with a modpack with only Epic Fight installed. 

https://youtu.be/zBy0wDWNvCs

Thanks!

**Comment by Sazuzaki** [comment]
More info:
All just kinda happened out of no where. I physically cannot hit the Ender Dragon in Epic Fight mode. Vanilla attacks work fine, but I can't attack him in melee combat with Epic Fight. I've tried changing my forge versions, didn't work. I tried going back to a previous Epic Fight version (16.5.12) and it just crashed immediately upon loading the world.
I'm hot out of ideas on what the issue might be. I've tested this on a completely different PC, a modpack with only Epic Fight installed, and it still occurs. It all works fine in 1.18.2

It just confuses me as to what really could've caused it? It's on a version that has been practically untouched by Mojang for years, as well as a version of the mod that hasn't been touched either. I'm not sure if bugs just randomly generate like that, but Minecraft do be wonky sometimes.

https://youtu.be/ioJl6nshvho
https://youtu.be/zBy0wDWNvCs

**Comment by Yesssssman** [comment]
Well, the most important thing is it had worked. If the epicfight version is not changed, the problem would be the version of forge, for both internal and dedicated server. Try the recommended forge version that is written in changelog.

**Comment by Sazuzaki** [comment]
Hey, thanks for the reply.
Just tried the recommended forge version, it still doesn't register the hits. I had my GF test it as well, she still can't hit the dragon. Perhaps when you get free time, you can see if it happens to you?

It really just baffles me. I'm not programmer or coder, but it's super strange this started happening out of no where with 0 changes to the game, mod, and mod loader. The only thing I remember before this happened was a couple of mods in my main modpack had to be updated. I only remember one of those mods, that being Geckolib. Everything else I can't recall, but this still happens with only EpicFight, even on an entirely different HDD or PC.

**Comment by Sazuzaki** [comment]
Update 2: So, it works now? Collective just updated, but I don't believe that has any ties to Epic Fight. I'm going to close this issue, but I'm not sure if it will come up again in the future. Thank you for your time.
