### ISSUE TITLE
[Crash, common, 1.16.5] Random crash from Zombie, Husk: Ticking entity - ChasingGoal

### ISSUE THREAD

**Issue by AlexLeeroy** [Yesssssman/epicfightmod#1054]
**Versions:**
16.5.13 for Minecraft 1.16.5

­
**Description:**
Only tested on dedicated server, heavily modded. The server randomly crashes, instantly. The crash log so far has always shown a Zombie or Husk as the errored entity. Reason: Ticking entity (LookController, ChasingGoal)

Cannot find specific activity that causes the crash to happen. There seems to simply be a chance for each mob and player alive.

­
I can provide a list of active mods if requested. These crashes make the experience unstable - EFM is just too good to play without, but a crash every hour causes frustration. especially since they almost always happen on intense fights.

I have seen that EFM v.18.1.5 had this issue, or a smilar one, fixed. I am reporting this regardless hoping it helps the mod's development, and would appreciate any tips on how to stop it from happening.

­
**­Crash Reports:**
[crash-2022-06-07_16.46.32-server.txt](https://github.com/Yesssssman/epicfightmod/files/8884205/crash-2022-06-07_16.46.32-server.txt)
[crash-2022-06-09_01.14.46-server.txt](https://github.com/Yesssssman/epicfightmod/files/8884206/crash-2022-06-09_01.14.46-server.txt)
[crash-2022-06-10_17.33.32-server.txt](https://github.com/Yesssssman/epicfightmod/files/8884207/crash-2022-06-10_17.33.32-server.txt)
[crash-2022-06-10_18.46.54-server.txt](https://github.com/Yesssssman/epicfightmod/files/8884208/crash-2022-06-10_18.46.54-server.txt)

**Comment by Yesssssman** [comment]
Fixed in 16.6.0
