### ISSUE TITLE
Aim Helper

### ISSUE THREAD

**Issue by Dargorix** [Yesssssman/epicfightmod#1055]
The aim helper doesn't show up.
I have tried the mod alone, without any other mod or datapack and without the graphic on fabulous or any shaders. 
And even now the aim helper doesn't show up when i use a bow or a crossbow whereas the config is "on".
I have some sreenshot :
![image](https://user-images.githubusercontent.com/89711165/173608463-9900e991-192e-4894-bd69-a49371523c74.png)
![image](https://user-images.githubusercontent.com/89711165/173608535-20cd13d5-3ea5-4051-9a24-86d805bab4d8.png)
![image](https://user-images.githubusercontent.com/89711165/173608569-8482b134-31c5-4ee2-a09c-0f03b95caca3.png)
![image](https://user-images.githubusercontent.com/89711165/173608609-f65ea14c-8e53-4283-9c47-e5bc2f638ad9.png)
Thank for all ^^

**Comment by Yesssssman** [comment]
Is the graphic setting fabulous?

**Comment by Yesssssman** [comment]
It is incompatible with some shaders and optifine mod. Did you use any of them?

**Comment by Dargorix** [comment]
I haven't any of them, I juste use the mod alone for the test. I have here other screen shot if that can help. And overall thank for all ^^
![image](https://user-images.githubusercontent.com/89711165/177628602-dcdb61c5-2a76-4449-8895-59cfa864b963.png)
![image](https://user-images.githubusercontent.com/89711165/177628638-4f691b2e-99d8-46c7-b115-5b246212daa0.png)
![image](https://user-images.githubusercontent.com/89711165/177628654-55ebc0d2-4dd9-4555-8544-78fdae2ec4de.png)
![image](https://user-images.githubusercontent.com/89711165/177628666-b6beb683-36c5-40f6-aba1-030c0606a6c3.png)
![image](https://user-images.githubusercontent.com/89711165/177628691-04b341fb-5f3a-4a44-aa57-768f1b4961fc.png)
![image](https://user-images.githubusercontent.com/89711165/177628722-240c1a4e-f902-4f86-9ef7-186375a29a26.png)
