### ISSUE TITLE
Suggestion: sort skill books

### ISSUE THREAD

**Issue by kazume** [Yesssssman/epicfightmod#1059]
I would find it helpful when skill books would be sorted into 3 categories: classes (or talents), guards and dodges.
It would be helpful too if they were sorted in the creative inventory.

Keep up the good work, I LOVE this mod!

**Comment by VanilaBOI** [comment]
Well they already have their own catagories: dodge, guard and passive. As for the creative tab, that be nice but it would have been better if you'd just suggested this in the development chat in the discord. Github is for issues you know.

**Comment by kazume** [comment]
Ok, good point, I'll do that!

> Github is for issues you know.

That actually really depends on how you use it. Most issue trackers include a "suggestions" category as well and I just saw that some other people were posting suggestions, so I assumed this repo was as well. I'll close and post in discord though :)
