### ISSUE TITLE
Ender dragon crash

### ISSUE THREAD

**Issue by Judiax** [Yesssssman/epicfightmod#1060]
When you spawn in a ender dragon, after a while mc crashes and it says 

Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.dimension.end.EndDragonFight.m_64098_()" because the return value of "net.minecraft.world.entity.boss.enderdragon.EnderDragon.m_31158_()" is null

what does this mean and how do you fix it?
version: epicfight-18.1.18 beta jar

**Comment by VanilaBOI** [comment]
The ender dragon is programmed for the end. If he gets spawned some where else the game will crash and there's nothing we can do about it.

**Comment by Yesssssman** [comment]
Full crash report please
