### ISSUE TITLE
A Strange crash in a single player game

### ISSUE THREAD

**Issue by MagicGuo123** [Yesssssman/epicfightmod#1064]
**Minecraft Version:** 1.16.5
**Forge Version:** 36.2.35
**Mod Version:** EpicFightMod-16.5.13
**Crash Discription:** After I entered the game, before I could do anything, the game got stuck and then crashed. But when I switched to a superflat world test, no matter what I did, it didn't cause a crash.
**Crash report(part):**
![图片](https://user-images.githubusercontent.com/108066433/175285606-f1e31ecb-f565-49a6-b2a3-f96fef64bb6a.png)
**Changes to the data file:** By following https://github.com/Yesssssman/epicfightmod/wiki/Custom-Weapon-Armor-datapack, I add capabilities of weapons from: spartanweaponry, spartantwilight, mahoutsukai and iceandfire. All weapon been tested in a superflat world and there's no problem when I tested them.

I hope there is enough information. Please help me. Your mod is really fun and I eagerly want to play it!

**Appendix：List of installed modules:**
alexsmobs-1.11.1
citadel-1.8.1-1.16.5
Atum-1.16.5-2.2.5
appleskin-forge-mc1.16.x-2.0.0
carryon-1.16.5-1.15.5.15
iceandfire-2.1.9-1.16.5
citadel-1.8.1-1.16.5
BiomesOPlenty-1.16.5-13.1.0.477-universal
ImmersiveEngineering-1.16.5-5.0.7-143
ImmersivePetroleum-1.16.5-3.3.0-11
Waystones_1.16.5-7.6.2
polymorph-forge-1.16.5-0.39
majobroom1.3.1
JRFTL+[1.16.5]-1.2
WaterStrainer-1.16.3-10.0.0
musketmod-1.16.5-forge-1.2.1
create-mc1.16.5_v0.3.2g
flywheel-1.16-0.2.5
cfm-7.0.0pre22-1.16.3
compactstorage-1.16.5-5.1b17
Clumps-6.0.0.25
sisser-1.7
Quark-r2.4-316
AutoRegLib-1.6-49
CookingForBlockheads_1.16.5-9.3.3
TravelersBackpack-1.16.5-5.4.2
mahoutsukai-1.16.5-v1.31.32
twilightforest-1.16.5-4.0.870-universal
Patchouli-1.16.4-53.2
pandoras_creatures-1.16.3-2.0.1
pamhc2foodcore-1.16.3-1.0.2
pamhc2foodextended-1.16.3-1.0.2
pamhc2trees-1.16.3-1.0.1
pamhc2crops-1.16.3-1.0.2
champions-forge-1.16.5-2.0.1.7
corpse-1.16.5-1.0.5
EpicFightMod-16.5.13
XaerosWorldMap_1.23.3_Forge_1.16.5
guardvillagers-1.16.5.1.2.4
FastLeafDecay-v25
Aquaculture-1.16.5-2.1.19
SpartanWeaponry-1.16.4-2.1.0-beta-4
spartantwilight-1.16.5-2.1.1
SpartanShields-1.16.5-2.1.2
Mekanism-1.16.5-10.0.21.448
MekanismTools-1.16.5-10.0.21.448
Mining dimension(cave  version)-1.16.5-forge-1.0
ensorcellation-1.16.4-1.2.0
cofh_core-1.16.4-1.2.1
Xaeros_Minimap_22.9.3_Forge_1.16.5
DoggyTalents-1.16.5-2.0.1.9
ars_nouveau-1.16.5-1.20.1
geckolib-forge-1.16.5-3.0.42
astralsorcery-1.16-1.16.5-1.13.12
observerlib-1.16.5-1.5.3
enhancedcelestials-1.0.4-1.16.4
firstaid-1.9.6
ToughAsNails-1.16.5-4.0.1.23-universal
fishtraps-0.1.3
ShoulderSurfing-1.16.5-2.2.2
ChinjufuMod[1.16.5]6.0.1
Botania-1.16.5-420.2
curios-forge-1.16.5-4.0.5.2
forgeautofish-2.1.3-1.16.x
i18nupdatemod-1.16.5-2.0.2-hotfix-4
NaturesCompass-1.16.5-1.9.1-forge
jei-1.16.5-7.7.1.110

**Comment by Yesssssman** [comment]
Fixed in 16.6.0
