### ISSUE TITLE
entity：Witch

### ISSUE THREAD

**Issue by FanRenLa** [Yesssssman/epicfightmod#1065]
[crash-2022-06-24_20.06.02-server.txt](https://github.com/Yesssssman/epicfightmod/files/8976016/crash-2022-06-24_20.06.02-server.txt)

**Comment by FanRenLa** [comment]
EpicFight-18.2.2-beta

**Comment by Yesssssman** [comment]
Crash with ecologics mod.

**Comment by FanRenLa** [comment]
> 与生态学 mod 崩溃。
It's Improved Mobs, I experimented in the village (I don't know if there is a connection to the village, or Iron Golem; Villager; but it did crash), and let the witches go.
[crash-2022-06-26_14.47.19-server.txt](https://github.com/Yesssssman/epicfightmod/files/8986099/crash-2022-06-26_14.47.19-server.txt)

**Comment by Deathawaits4** [comment]
Disable the vehicle module in improved mobs and the guardian module. This should fix the issue. It did for me.
