### ISSUE TITLE
Random Crashes, 'Look Controller' 

### ISSUE THREAD

**Issue by mohaneddz** [Yesssssman/epicfightmod#1068]
I think the Crashy link Can tell better than i do ;
https://crashy.net/ehTWKDINZ0RmLHSmeOXM
will the problem be fixed for the 1.16.5 version? if so I will be greatful ♥

**Comment by Yesssssman** [comment]
duplicte #1064

**Comment by mohaneddz** [comment]
what does that mean? sorry i didn't get it .

**Comment by VanilaBOI** [comment]
It means that this issue has already been reported and solved.

**Comment by Yesssssman** [comment]
Actually, it's not solved yet, but it'll be solved when I backport to 1.16.5

**Comment by Yesssssman** [comment]
Fixed in 16.6.0
