### ISSUE TITLE
Broken Textures with Optifine

### ISSUE THREAD

**Issue by RazorTheSavage** [Yesssssman/epicfightmod#1071]
All the mods I have installed are Forge Optifine and the epic fight mod,
I have no resource packs enabled and no shaders. 

This is what I see when in game.
![Minecraft_ 1 18 2 - Singleplayer 6_30_2022 10_48_51 AM](https://user-images.githubusercontent.com/95834160/176712435-0d758559-125e-43f0-8d24-37cac1fbc870.png)

 I've tried variouse different versions of Forge and Optifine, 
 The problem happens when I have both Optifine and the Epic Fight Mod enabled together.
 
 Does anyone know of a fix?

**Comment by MetalKnight56** [comment]
uninstall Optifine, won't fix since OF is not open source nor it uses forge api.
