### ISSUE TITLE
Show entity error, let me delete entity?

### ISSUE THREAD

**Issue by mzmoc** [Yesssssman/epicfightmod#1074]
I have attached my error file.
[实体错误报告.zip](https://github.com/Yesssssman/epicfightmod/files/9055008/default.zip)
Because I'm Chinese, soThe document is in Chinese, sorry.

**Comment by Yesssssman** [comment]
Please use the recommended forge version. If it still happens, report it again.

**Comment by mzmoc** [comment]
Thank you very much. The problem has been solved.
