### ISSUE TITLE
Spartan Weaponry, Ice and Fire addon

### ISSUE THREAD

**Issue by Rydjinn** [Yesssssman/epicfightmod#1076]
Apparently I did something wrong here, but I don't know what. I copy and pasted a working config made adjustments so it should have worked. Can anyone help me?

	[custom_weaponry.spartan_scythe_wood]
		armor_ignorance = 0.0
		hit_at_once = 2
		impact = 1.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SPEAR"
		registry_name = "spartanweaponry:scythe_wood"

There's nearly 100 of these, supposedly all with the same problem, for the Ice and Fire addon to Spartan Weaponry in 1.16.5

[Epic Fight Spartan.txt](https://github.com/Yesssssman/epicfightmod/files/9074354/Epic.Fight.Spartan.txt)

**Comment by MetalKnight56** [comment]
empty file, i suggest you go onto the discord server and download a pre-made config file for spartan weapondry, all public configs are on creation-sharing channel.

**Comment by Yesssssman** [comment]
Config file is completely replaced by the datapack. it is much more convenient to use and bug-free. I highly recommend you using datapack. Here's the guide: https://github.com/Yesssssman/epicfightmod/wiki/Custom-Weapon-Armor-datapack

**Comment by Rydjinn** [comment]
Yes, but I'm trying to configure for a Spartan Weaponry addon not the mod itself
