### ISSUE TITLE
tinkers and epic fight - trait incompatibility

### ISSUE THREAD

**Issue by Deathawaits4** [Yesssssman/epicfightmod#1077]
Hei,

so tinkers constructs traits are not working with epic fight mod.
This is propably due to the fact that epic fight uses a completely different hit registering mechanic
Tinkers provides an api for that and it would be really really great if you could add tinkers construct compatibility

specifically this: 
https://github.com/SlimeKnights/TinkersConstruct/blob/5dfa77d74fa8b1e36fc9d6c7b548aa0928a939b1/src/main/java/slimeknights/tconstruct/library/modifiers/Modifier.java#L820

this library has all the modificators attached and i think, since tinkers provides an api, it should be possible without hacky stuff.

**Comment by Yesssssman** [comment]
Fixed in recent versions (1.18.2, 1.19.2, 1.20.1)
