### ISSUE TITLE
animations dont show in multiplayer

### ISSUE THREAD

**Issue by ViktorArzano** [Yesssssman/epicfightmod#1079]
me and my friends can't see eachother animations :(

**Comment by ViktorArzano** [comment]
i also need to mention that we have rubidium installed, but the animations work just fine for yourself, we just can't see each other animations

**Comment by Ape21** [comment]
Having same issue, I've read players relogging could fix this issue but I am yet to test this myself.

**Comment by ViktorArzano** [comment]
> Having same issue, I've read players relogging could fix this issue but I am yet to test this myself.

that's wxactly what happened to me. I relogged and and for some 30irsh seconds i could indeed see the animation, pretty weird.

**Comment by Terekyy** [comment]
Me and a friend had the same problem, so we downgraded to EpicFight-18.1.20-beta.jar which is the previous version, and now it works. Just a temporary fix :)

**Comment by Yesssssman** [comment]
Thanks for reporting, I'll fix this as soon as possible.
