### ISSUE TITLE
Dodging into vines makes you lose control of your character. [1.16.5 Latest]

### ISSUE THREAD

**Issue by Sazuzaki** [Yesssssman/epicfightmod#1082]
Heyo, I recently discovered a bug in Epic Fight 16.5.13 where if you dodge into vines against a wall, you'll lose all control of your character. I mean like, EVERYTHING. I can't scroll through my items, open my inventory, attack, or anything else. 

Only two ways I know to fix it: 
1.  Teleport out of the vines and dodge again.
2. Re-log into the server.

Steps to reproduce:
1. Log into Minecraft with Epic Fight 16.5.13
2. Dodge into some vines with a wall behind them.

Thanks for your time!

**Comment by MetalKnight56** [comment]
Could you please provide some kind of footage it would help a lot

**Comment by Yesssssman** [comment]
Does this issue only happen in 1.16.5? or it also happens at the latest?

**Comment by Sazuzaki** [comment]
> Does this issue only happen in 1.16.5? or it also happens at the latest?

Sorry I've been busy, I'll get a video soon. And it only happens in 1.16.5.

**Comment by Yesssssman** [comment]
There was no specific change for this problem in 16.6.0, but I'm pretty sure that this issue has been fixed since it completely same as last 1.18.2 version.
