### ISSUE TITLE
Configured mod causes crash with some other mods when trying to edit the auto switch items config

### ISSUE THREAD

**Issue by Voidner** [Yesssssman/epicfightmod#1083]
Here's a list of mods i know will cause a crash when you scroll through the items in the config 

ice and fire
alex mobs
geckolib
ars nouveau
waystones
quark
serene seasons
optifine

**Comment by MetalKnight56** [comment]
first of all which version of epic fight and minecraft are you on? Secondly delete optifine as it causes various issues and its not supported.

**Comment by Yesssssman** [comment]
Crash report... please?
