### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by luigi052005** [Yesssssman/epicfightmod#1084]
Forge is bad and has no future 
pls port the mod to fabric.

**Comment by Yesssssman** [comment]
![image](https://user-images.githubusercontent.com/79469058/179496957-5b666dc4-cedf-48c2-83d3-365670ac676f.png)

**Comment by MetalKnight56** [comment]
bruh the mod is already going to receive a port, ask in the discord server before talking bullshit in github, this is only meant for actual issues
