### ISSUE TITLE
EpicFightMod configuration tac-r-0.2.1.1-1.16.5MOD firearms crash

### ISSUE THREAD

**Issue by ainlzj** [Yesssssman/epicfightmod#1087]
I used EpicFightMod to add tac-r-0.2.1.1-1.16.5MOD, and it suddenly crashed when I opened the EPIC add tool interface and looked down for the firear
[crash-2022-07-21_18.18.00-client.txt](https://github.com/Yesssssman/epicfightmod/files/9158486/crash-2022-07-21_18.18.00-client.txt)
m

**Comment by MetalKnight56** [comment]
Denied issue, 1.16.5 no longer will be supported.
