### ISSUE TITLE
EpicFight Animation

### ISSUE THREAD

**Issue by DellYTTY** [Yesssssman/epicfightmod#1088]
Good afternoon, evening, I want to remove the spider animation from Epic Fight, because I simply don't need it (I want to use it from another mod/resource pack, namely the spider animation). However, I don't understand how to do this =(

P.s: version 1.16.5 (because there is an assembly of mods on it and there is no way to switch to another version)

**Comment by Yesssssman** [comment]
Those features are only possible in 1.18.2 for now.

**Comment by DellYTTY** [comment]
It's a pity, of course, but thanks for the answer =)
