### ISSUE TITLE
Crash to desktop when attacking an entity using vanilla attack

### ISSUE THREAD

**Issue by PatriamStudios** [Yesssssman/epicfightmod#1089]
Pretty straightforward explanation as per the title. When entering Epic Fight Mod's combat mode there is no issue attacking entities, it is only when out of combat mode and attacking with the normal vanilla punch.

Has been tested by multiple players both on multiplayer and singleplayer, going through the crash log ourselves we can't seem to find anything wrong.

We are using the latest 1.16 version downloaded from the Curseforge

Thanks in advance! :D

Crashlog example: https://pastebin.com/42G585kD

**Comment by Yesssssman** [comment]
You've come to the wrong place! Please report this issue to Ambience mod.
