### ISSUE TITLE
Still being able to attack when downed with PlayerRevive mod

### ISSUE THREAD

**Issue by ricchix** [Yesssssman/epicfightmod#1090]
https://user-images.githubusercontent.com/89796563/180392992-684ca118-6413-44a4-b12f-f408a2fac6d2.mp4

This is on 1.18.2 and Forge 40.1.68
EpicFight version: 18.2.6-beta
PlayerRevive version: 2.0.1

**Comment by CreativeMD** [comment]
PlayerRevive cancels the `ClickInputEvent` when a player is downed ([source](https://github.com/CreativeMD/PlayerRevive/blob/1.18/src/main/java/team/creative/playerrevive/client/ReviveEventClient.java#L62)). So somehow this is being ignored.

**Comment by adoetho** [comment]
Any updates to this?

**Comment by Jetpack-Cat** [comment]
Any update on this? I really need player revive for my modpack.

**Comment by Walrus98** [comment]
Can you maybe inject some of your code using mixin? Maybe we can handle that, disabling the damage event overriding attack entity method of this class https://github.com/Yesssssman/epicfightmod/blob/a55c570a9675c25bc1eaf5f97146c91e36c2c161/src/main/java/yesman/epicfight/events/PlayerEvents.java#L33

**Comment by CreativeMD** [comment]
@Walrus98 sorry but I will not mixin into other peoples code just to get the compatibility solved. Already provided a suggestion for the solution.

**Comment by guivnf** [comment]
Issue has been solved on our side and will be made available in a future update.
