### ISSUE TITLE
mod doesnt want to work

### ISSUE THREAD

**Issue by Lildemon187** [Yesssssman/epicfightmod#1093]
Man me and my friends where making a server for us to play and i added all these mods to the server and The epic fight mod just didnt want to work i even took all the mods out and just tried it by itself and it still didnt work if you can respond to me and try to help me i would love it.

**Comment by MetalKnight56** [comment]
Need minecraft version, epic fight version, forge version, mod list, possible crash log, and footage of the mod "not working"

**Comment by Lildemon187** [comment]
https://medal.tv/games/minecraft/clips/tzIH9jIlFrvLJ/d13371V2LwKE?invite=cr-MSxERk4sMTU2NDk2NTcs clip of the mod not working and my mods list is gonna be in the next comment

**Comment by Lildemon187** [comment]
![image](https://user-images.githubusercontent.com/109875226/180621809-f59128bf-52ca-4cd5-894b-4427ac37bccc.png)

**Comment by Yesssssman** [comment]
Press "R"

**Comment by MetalKnight56** [comment]
> https://medal.tv/games/minecraft/clips/tzIH9jIlFrvLJ/d13371V2LwKE?invite=cr-MSxERk4sMTU2NDk2NTcs clip of the mod not working and my mods list is gonna be in the next comment

link doesn't seem to work please fix if issue persists

**Comment by Yesssssman** [comment]
I found he didn't switch to the battle mode in his video.

![image](https://user-images.githubusercontent.com/79469058/180630001-438c1eca-4992-465b-b0fd-ecae600f19fb.png)

The special attack icon is shown in the battle mode. And all animated attacks only work in battle mode.

![image](https://user-images.githubusercontent.com/79469058/180630055-6a81d73e-fc22-4a1b-9a08-04c5edfe3fa5.png)

**Comment by MetalKnight56** [comment]
oh ok
