### ISSUE TITLE
When you exit combat mode, you can still use the weapon's special skill - Ver.18.2.6-beta | Forge: 40.1.68

### ISSUE THREAD

**Issue by IsNEI13** [Yesssssman/epicfightmod#1095]
https://user-images.githubusercontent.com/60393163/180718965-9af35727-56d2-4205-a7c7-4486d033c610.mp4

**Comment by Yesssssman** [comment]
Have you installed other mods?

**Comment by IsNEI13** [comment]
Yes, I have installed several

**Comment by Yesssssman** [comment]
Could you check if this problem still happens after removing all other mods?

**Comment by IsNEI13** [comment]
I'm going to test the mod by installing it alone.

**Comment by IsNEI13** [comment]
https://user-images.githubusercontent.com/60393163/181329671-7871a225-2c57-4fca-befd-c231ff1c1a73.mp4

**Comment by IsNEI13** [comment]
![image](https://user-images.githubusercontent.com/60393163/181333805-fd3dcff1-f1dc-47f8-8e9e-ba1614d043b2.png)

**Comment by Yesssssman** [comment]
Are you using a custom key settings?

**Comment by IsNEI13** [comment]
I have on the side click of the mouse to change the combat mode
In another side click for the special ability of the weapon
In the right click, it is default to cover me with the weapon
And the roll is also by default (Shift)

**Comment by Yesssssman** [comment]
Ok thanks, will be fixed in the next update

**Comment by Yesssssman** [comment]
Fixed in 18.3.0

**Comment by IsNEI13** [comment]
Yeaaah!!
