### ISSUE TITLE
Sometimes you can't see the player/mobs/chest - Ver.18.2.6-beta | Forge: 40.1.68

### ISSUE THREAD

**Issue by IsNEI13** [Yesssssman/epicfightmod#1096]
https://user-images.githubusercontent.com/60393163/180753307-3cd269f8-1150-41e1-8831-5b139cc6984c.mp4

**Comment by Yesssssman** [comment]
It seems like you can't see the vanilla model also. Is this problem solved if you remove epicfight?

**Comment by IsNEI13** [comment]
Yes, although this problem happens sometimes, restarting minecraft works fine (sometimes), but other times it fails.

**Comment by Yesssssman** [comment]
Well... if the animated model is only invisible, I'd inspect this problem. But since the vanilla model is also invisible, I can't find any clue that this problem comes from my side.

**Comment by IsNEI13** [comment]
I will do more tests, don't worry

**Comment by IsNEI13** [comment]
Do you know if there is incompatibility with mods like Optifine, Rubidium...etc.

**Comment by IsNEI13** [comment]
I entered the world again and the game closed.
Here is the last log: https://mclo.gs/MOkZY4g
It's the first time it happens to me, now I start without problem.
