### ISSUE TITLE
Animations don't work in 3rd person camera [1.12.2]

### ISSUE THREAD

**Issue by Spews** [Yesssssman/epicfightmod#1097]
Hi there just want to report that if u have Emoticons by McHorseYT u will get an animation bug.
btw I just find your mod and looks very good i will try some extra things and will report any error i get. 

Keep doing a good job bro.

**Comment by Yesssssman** [comment]
Can't solve this problem since both mods have different models to animate each model.

**Comment by Spews** [comment]
lmao that was fast
