### ISSUE TITLE
Config Option to always use the animated player model

### ISSUE THREAD

**Issue by FireTamer81** [Yesssssman/epicfightmod#1098]
At the moment, Epic Fight is the only mod that adds an animated player model (that I know of at least). So, being able to always use the animated player model for actions like running and such without having to be in combat mode would be awesome. 

Might allow players to avoid the disconnect between switching between the normal player model and Epic fight one too (like the height change).

**Comment by Woodgoldtwo** [comment]
Turn off filter animation in the config
It makes players use EFM's custom animations even when they are not in combat mode

**Comment by Yesssssman** [comment]
Already existing option.
