### ISSUE TITLE
[1.18.2] Latest version of Epic Fight Mod missing Weight and Stun Armor attributes

### ISSUE THREAD

**Issue by mr-poyo** [Yesssssman/epicfightmod#1099]
**Forge:** 40.1.60
**Version:** 1.18.2
**jar:** EpicFight-18.2.6-beta.jar

The latest version of Epic Fight Mod is missing some attributes to include Weight and Stun Armor.

Hope this helps

Steps to reproduce:
1) Load a new world with EpicFight-18.2.6-beta.jar
2) Look at tooltip for netherite armor (missing weight and stun armor)
3) Learn the Roll skill
4) Perform max rolls without armor and full stamina = 3
5) Perform max rolls with netherite armor and full stamina = 3

Thank you for a great mod. I've been spending many many hours with it.

**Comment by Yesssssman** [comment]
Thanks! It will be fixed in the next update.

**Comment by Yesssssman** [comment]
Fixed in 18.3.0
