### ISSUE TITLE
Trying to configure new mobs/items/armor from other mods via config

### ISSUE THREAD

**Issue by ShadeKage** [Yesssssman/epicfightmod#1101]
So I cant tell if im dumb, but the "epicfight.toml" config file doesnt contain any info for adding new stuff to the mod, only stuff for skill book spawn/drop rates, and default gamerules.
This means that i cant add any new mobs, like some from a wither storm mod (it adds zombie, skeleton, creeper, and spider variants)
Ive tried writing in the code lines manually in the file from watching year old tutorials on how to do it, but the game crashes un surprisingly

I assume a newer update changed this file for the new skill books, etc. But you removed the custom stuff, maybe could you add that back? please? 
Or if im just doing this wrong in some manner and got the wrong file, comment back and tell me what im missing, or at least update the tutorial vids that were made on the forge page, Thanks

**Comment by ShadeKage** [comment]
P.S.
Is the custom mob thing a 1.16 exclusive feature? The vid posted on the forge page mentions when it was 
https://www.youtube.com/watch?v=vEs1SXiLDVI
this vid ^  If so, then consider this a suggestion to add this to the newer version (im running on 1.18.2 for reference)

**Comment by Woodgoldtwo** [comment]
In the latest versions you use datapacks instead of the config

**Comment by Woodgoldtwo** [comment]
it's more stable and has more features

**Comment by Woodgoldtwo** [comment]
(also there is a datapack for crackers wither storm mod mobs in the epic fight discord server that you can download)

**Comment by Yesssssman** [comment]
First, the configuration by .toml file is deprecated since it's too buggy and has terrible readability. But you can still configure the custom weapon and entities by setting up the datapack. Here's how to do it: https://github.com/Yesssssman/epicfightmod/wiki

By the way, I'm going to add the description notifying people that these features are deprecated in my video. Thanks for reminding me it!

**Comment by ShadeKage** [comment]
> (also there is a datapack for crackers wither storm mod mobs in the epic fight discord server that you can download)

Yo, can i get the link tho? I actually wanna download that instead of writing it myself lol
