### ISSUE TITLE
Animations are bugged. [1.16.5]

### ISSUE THREAD

**Issue by Ctakep** [Yesssssman/epicfightmod#1102]
When I want to use the fight mod the weapones are smaller and between my legs. On the first time it was working just fine. Idk what to do please help.

Also here's a screenshot
![2022-07-29_13 01 18](https://user-images.githubusercontent.com/110233422/181746026-e108b19c-0e35-4510-a6d1-181633915766.png)
![2022-07-29_12 59 57](https://user-images.githubusercontent.com/110233422/181746057-f64a7ece-7662-4447-85ea-e6d17585dea1.png)
.

**Comment by Yesssssman** [comment]
Incompatibility with wizard staff mod. Remove one of them.
