### ISSUE TITLE
Suggestion : New types of weapons

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#1104]
I have new weapon type ideas.

1- Mace
2- Lance
3- Club/Bat (Something like a baseball bat but made out of wood)
4- Throwing axe
5- Javelin
6- The oldest rifle of the world history.
7- The oldest pistol of the world history.
8- Blowgun
9- Maybe you can make the stick useable for fight.

**Comment by MarioSMB** [comment]
Two handed hammer support would be great (e.g. TConstruct's sledge hammer), with a powerful slam attack.
