### ISSUE TITLE
Suggestion : Some system changes

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#1105]
I suggest you to do some small changes.

1 - Add it in config menu so we can choose will keepskillsafterdeath be defaultly set false or true.
2 - When a player creates a world without cheats before installing the mod, let them toggle keepskillsafterdeath for one time.
3 - Let the player have 2 skills at once, force some skills to be primary and some of them to be secondary. 
A warrior in real life could know both dodge and guard skills.
4 - You may make a different type of animation filter so it would also filter the mob animations too.
5 - Add animation to snowball and fireball.

**Comment by Yesssssman** [comment]
1: It already exists.
2: It can be done with a LAN server allowing cheats.
3: Maybe in the future updates.
4: It already exists.
5: Nope, the RPM of the snowball is too fast to animate it. And fireball is not shootable by the player.

**Comment by TurkishAhmet4545** [comment]
> 1: It already exists. 2: It can be done with a LAN server allowing cheats. 3: Maybe in the future updates. 4: It already exists. 5: Nope, the RPM of the snowball is too fast to animate it. And fireball is not shootable by the player.

Okay. But how does mob animation filter work ?
I meant when we turn off battle mode, mobs also would to that.

**Comment by Yesssssman** [comment]
That's impossible. Imagine what will happen if players are switching their mode in the multiplay.

**Comment by TurkishAhmet4545** [comment]
> That's impossible. Imagine what will happen if players switch their mode in the multiplay.

You could simply make it exclusive for singleplay.
But in short, i don't want to get attacked by mobs with battle mode on while im not in battle mode, atleast in singleplay.

**Comment by Yesssssman** [comment]
Let me explain. There are two types of servers in Minecraft. One is the "Internal Server" which you call "singleplay" and the other is "Dedicated Server" which is normally called multiplay. Of course, your suggestion is unable to apply to Dedicated server. But Internal Server also can be worked as a multiplay, by opening the LAN server. So there's no perfect singleplay in Minecraft. And you can simply use the creative mode if you don't want to be attacked by mobs.

**Comment by TurkishAhmet4545** [comment]
> Let me explain. There are two types of servers in Minecraft. One is the "Internal Server" which you call "singleplay" and the other is "Dedicated Server" which is normally called multiplay. Of course, your suggestion is unable to apply to Dedicated server. But Internal Server also can be worked as a multiplay, by opening the LAN server. So there's no perfect singleplay in Minecraft. And you can simply use the creative mode if you don't want to be attacked by mobs.

I am playing Survival. I want to always fight in equal conditions but it sucks when im not in battle mode but they are.
