### ISSUE TITLE
Is this a bug or just miss-described? 

### ISSUE THREAD

**Issue by BlueLightner** [Yesssssman/epicfightmod#1106]
The Guard skill reads you will able to "block all melee attacks from the front." (It does not mention blocking ranged attacks.)
The Active Guard skill reads "you will be able to block ranged attacks."

From my experience you do not need the Active Guard skill to block arrows.
Either I am misunderstanding/not reading it correctly, Active Guard is just for its stamina perk and something is miss-described, or Guard is not meant to block ranged attacks (such as arrows), and is therefore a bug. My guess is something being miss-described.

Does anyone know the answers?

**Comment by Yesssssman** [comment]
You pointed it out precisely! Yes, This is the bug I didn't expect. Thanks for reporting and I'll fix that in the next update.

**Comment by TurkishAhmet4545** [comment]
> You pointed it out precisely! Yes, This is the bug I didn't expect. Thanks for reporting and I'll fix that in the next update.

Does that mean we will be able to block ranged attacks with the simple guard skill ?

**Comment by Yesssssman** [comment]
It's even possible for now. Originally, the projectile damage types were only blockable by the advanced guard skills (Energizing guard, Active guard) but it's able to block the projectiles with normal guard skill in the latest.

**Comment by Yesssssman** [comment]
Fixed in 18.3.0
