### ISSUE TITLE
About item tooltips

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#1107]
I see that this mod prevents the game from showing items durabilities with held item tooltips on.
Is this a simple thing i can solve or should you fix somethings ?

**Comment by Yesssssman** [comment]
![image](https://user-images.githubusercontent.com/79469058/182373497-852ead4a-4d0d-4cd4-b1b4-a15c506deb18.png)

Something must be wrong in your environment.

**Comment by TurkishAhmet4545** [comment]
> ![image](https://user-images.githubusercontent.com/79469058/182373497-852ead4a-4d0d-4cd4-b1b4-a15c506deb18.png)
> 
> Something must be wrong in your environment.

I don't know maybe a 1.16.5 bug.
I will check it.
