### ISSUE TITLE
Certain shields from Epic Knights & MobZ mods floating in off-hand (1.18.2)

### ISSUE THREAD

**Issue by bassistracer** [Yesssssman/epicfightmod#1108]
![2022-08-01_16 34 14](https://user-images.githubusercontent.com/108098942/182250744-21cfe42f-6d4b-4367-b44c-bf0e7f59f5e9.png)
![2022-08-01_16 35 00](https://user-images.githubusercontent.com/108098942/182250750-b602686d-04b6-4c40-b2c5-0a3555da9743.png)
![2022-08-01_16 35 14](https://user-images.githubusercontent.com/108098942/182250751-efdf7f56-47f5-450d-8715-03b013dc661f.png)

was told to make it a github issue here -- the first two images are of the Targe and Buckler from Epic Knights (applies to all material variations) (listed as [material]_target and [material]_buckler)
and the third is from MobZ called the Metal Shield (simply listed as shield).
I registered all of these as shields, and they still float. Any solutions?

**Comment by Yesssssman** [comment]
Fixed in 1.20.1
