### ISSUE TITLE
Questions about 1.16.5

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#1109]
I have about version 1.16.5.

1 - How long are you planning to continue doing backports for 1.16.5 ?
2 - Even though new versions go too far, would you continue doing backports for 1.16.5 ?

As the new versions over 1.16.5 filtered players that use potato pc, i recommend you to show some special interest for 1.16.5 version.

**Comment by Yesssssman** [comment]
Most of the bugs that exist in 1.16.5 are solved in 1.18.2 so I'll backport it once. But I'll stop supporting 1.16.5 as the Minecraft version goes up.
