### ISSUE TITLE
Sever crash issue

### ISSUE THREAD

**Issue by ReedJr** [Yesssssman/epicfightmod#1110]
Here is the sever crash report. Idk what is the issue with this mod crashing. If it is another mod that is incompatible with this mod I would like to know please.
[crash-2022-08-04_02.12.49-server.txt](https://github.com/Yesssssman/epicfightmod/files/9256448/crash-2022-08-04_02.12.49-server.txt)

**Comment by ReedJr** [comment]
btw this is v1.16.5 java and vEpicFightMod-16.5.13.jar.

**Comment by Yesssssman** [comment]
Guess it doesn't work with some mods but I can't find since there are too many mods installed
