### ISSUE TITLE
Is the pure guard skill too rare ?

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#1111]
I fighted alot in my survival world.
It seems i got almost any other skill book except pure "Guard".
I got Active Guard, Energizing Guard, Step, Roll, Swordmaster, Berserker etc. but still couldn't find or get guard.
Is it scripted as the rarest one ?
Version : 1.16.5
Forge : 36.2.20
Mod version : https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/3534866

**Comment by Yesssssman** [comment]
No, they're all random.

**Comment by TurkishAhmet4545** [comment]
> No, they're all random.

But shouldn't there be something different if every other skill book comes repeating but still no guard ?

**Comment by Yesssssman** [comment]
Hm, Since the number of skills is not quite big for now, I just made them drop randomly. But I'm considering making a drop table for skill books for each mob as the number of the skills grows.

**Comment by TurkishAhmet4545** [comment]
> Hm, Since the number of skills is not quite big for now, I just made them drop randomly. But I'm considering making a drop table for skill books for each mob as the number of the skills grows.

Does that mean we will get something like a box and we will choose one of the skills in it ?
