### ISSUE TITLE
Enderdragon doesn't do any damage (and 1 game crash issue)

### ISSUE THREAD

**Issue by Judobeast** [Yesssssman/epicfightmod#1117]
He only keeps hitting me but no damage, the only thing that has damage is the dragon breath... 
The game crashed one time when i entered the end and the log says "Ticking entity" and below says this as the main problem 

java.lang.NullPointerException: Cannot invoke "yesman.epicfight.api.animation.TransformSheet.readFrom(yesman.epicfight.api.animation.TransformSheet)" because "transformSheet" is null

**Comment by AllenOW** [comment]
minecraft1.18.2/mod18.2.6beta
Melee attacks do not deal any damage to the player when Enderdragon lands on the ground.

**Comment by Yesssssman** [comment]
I'm already working on this bug

**Comment by Yesssssman** [comment]
Fixed in 18.3.0

**Comment by CatastropheChou** [comment]
1.16.5, epicfight:16.6.4 also has this crash
https://pastebin.ubuntu.com/p/DfSBKbTsMh/
> Fixed in 18.3.0
