### ISSUE TITLE
[Suggestion] Successfully blocking melee attacks stuns enemies

### ISSUE THREAD

**Issue by MarioSMB** [Yesssssman/epicfightmod#1118]
It seems very difficult to parry with the greatswords since blocking with the appropriate skill doesn't stop enemies from attacking you for any amount of time. It would be cool if a successful parry caused enemies to be stunned for a second so that you would have an opening to attack.

**Comment by Yesssssman** [comment]
Greatsword is not designed to be used as parrying. And I'm making a new battle system. Tho it won't stop the enemy's attack animation, it will also benefit if you succeed in parrying.
