### ISSUE TITLE
Some skill selector issues

### ISSUE THREAD

**Issue by MarioSMB** [Yesssssman/epicfightmod#1119]
When clicking on a skill in the skill selector, you are immediately charged 5 levels without confirmation or any description for the skill. This is counter-intuitive to those who are not completely familiar with all the skills, as it is not clear what you're selecting or that you will be charged in levels for switching to it.  
It would be nice if clicking on a skill displayed the same description as the initial skill book, with an apply button that asks the player to confirm the swap.  

When selecting a skill, the menu closes and whatever weapon you're holding performs an attack action.

When you have no skills yet, the skill selector should display some text such as "No skills collected, use Skill Books to unlock them", as currently it is difficult to tell if the empty skill menu is a bug without having found one of these books.

An option to control the cost of applying skills would be nice if this doesn't already exist!

**Comment by Yesssssman** [comment]
Love your ideas but you missed one thing,

![image](https://user-images.githubusercontent.com/79469058/183919506-b2a9c6f7-160a-4015-97bd-f5ddddc8a139.png)

the level requirement is already indicated like this. 

Well, the skill UI is currently so messy. I'll consider your opinion when I remake it

**Comment by MarioSMB** [comment]
There is indeed an indicator of the cost but there is no indication that simply clicking on the skill has made you pay that cost; the experience bar is not visible, there's no experience-like sound or confirmation etc. The only indication that I was being charged experience levels was running out of levels!
