### ISSUE TITLE
[Suggestion] Maintain sprinting after actions (rolling, attacking etc)

### ISSUE THREAD

**Issue by MarioSMB** [Yesssssman/epicfightmod#1120]
Performing a dodge roll while sprinting cancels out the sprint, so you end up holding the button without sprinting! It would be nice if the player continued to sprint after the roll and after attacking, as it is strange to be not sprinting while holding the sprint button.

**Comment by MarioSMB** [comment]
This also appears to be a bit of an issue with any action besides the Guard skill, which correctly allows you to continue sprinting after using it.

**Comment by Yesssssman** [comment]
If you press the sprint button again at the right time, you have the same effect of this tho it's a high-level technique

**Comment by MarioSMB** [comment]
The technique seems a little inconsistent though; some actions will allow you to continue sprinting, such as blocking with the guard skill. It's just a bit unintuitive to be holding the sprint button and not be sprinting, a game I play has a bug causing a similar behaviour and it's more a source of frustration than skill. I hope an option or a "second wind" skill or something can be considered to allow this to work.

**Comment by Yesssssman** [comment]
Guard skill doesn't interrupt you from moving. It only slows down your movement speed. All actions that prohibit you from moving will
