### ISSUE TITLE
[Suggestion] Immunity to stuns while swinging a greatsword

### ISSUE THREAD

**Issue by MarioSMB** [Yesssssman/epicfightmod#1121]
It might just be the 1.18.2 bug where armors have no stun resistance, but it seems incredibly punishing to use a greatsword when compared to any other weapon, for one simple reason: your attacks are cancelled by any hits!  
The player will already be taking a lot of damage thanks to the slow speed of the weapon, it doesn't seem too unbalanced to allow swinging the heavy weapon around without getting interrupted so easily.

**Comment by Yesssssman** [comment]
Will be added as a passive skill :) great idea tho.
