### ISSUE TITLE
[Suggestion] Crosshair while aiming with bows

### ISSUE THREAD

**Issue by MarioSMB** [Yesssssman/epicfightmod#1123]
Aiming with the bow seems incredibly janky currently, as it's impossible to tell where you're aiming or how far the shot will go.  
Some kind of indicator (such as a crosshair at the target or a visual display of the arrow's arc) would be nice, possibly along with some target locking on the enemy with a marker over its head.

**Comment by Yesssssman** [comment]
It's already possible with the shoulder surfing mod.

**Comment by MarioSMB** [comment]
With just Epic Fight installed it seems like one would be better off switching to build mode to use the bow than trying to use it in combat mode, I hope some improvements to the bow combat can be considered in the future as there's so much potential for it.
