### ISSUE TITLE
Katana sheath sound playing in build mode

### ISSUE THREAD

**Issue by MarioSMB** [Yesssssman/epicfightmod#1124]
When you switch to the katana while in build mode, after a few seconds it will play a sheathing sound despite not having any visible sheath.

**Comment by Yesssssman** [comment]
That's because the "Filter Animation" option doesn't mean removing all epic fight logic from the player. It just disables animations so that other mods using animations could be compatible.

**Comment by MarioSMB** [comment]
That is fair, but perhaps the sound for sheathing should be muted while in build mode, since there's no sheath?
