### ISSUE TITLE
Rolling tied to stamina which is not displayed in build mode

### ISSUE THREAD

**Issue by MarioSMB** [Yesssssman/epicfightmod#1126]
In build mode it is still possible to dodge roll, but there is no visible stamina display making it difficult to see when you're able to roll again or that you've actually rolled (besides being thrown in a direction jarringly).

**Comment by Yesssssman** [comment]
Could you provide more information like version, key settings, video capture?

**Comment by MarioSMB** [comment]
Default settings, though I changed the Roll key to Z so that I could actually roll, by default it overlaps with sprinting and does not work.  

Minecraft version: 1.18  
Mod version: 18.2.6  
Forge version: 40.1.68  
No other mods installed.  

When dodge rolling in build mode there is no stamina bar, I can record a video if needed but this was tested with a completely clean environment.  
The problem with not displaying it is, rolling still takes stamina so it's unclear that you need it or that it's being consumed.

**Comment by Yesssssman** [comment]
Fixed in 18.3.1
