### ISSUE TITLE
Energizing Guard - Unintentional Weapon/Odd Ranged Blocking

### ISSUE THREAD

**Issue by BlueLightner** [Yesssssman/epicfightmod#1130]
I've encountered a few potential bugs while using the Energizing Guard skill.

-The Greatsword does not use this skill, despite being listed in the skill books description.
-Ranged attacks set stamina multiplier to 3.4x and drains stamina completely. Edit: Also blocks 100% damage rather than 80%.
-Explosions are still properly blocked. (I'm unsure if magic attacks are blocked correctly.) 

It's possible the Greatsword was not properly added to the list of weapons effected by Energizing Guard, or the skill book accidently includes it in the description. I'm unsure what could cause the odd interaction with ranged attacks and Energizing Guard.

I also wanted to thank you for fixing the last bug I reported! It's awesome that you are actively improving your mod.

**Comment by Yesssssman** [comment]
Fixed in 18.3.1
