### ISSUE TITLE
Roll/Sidestep without combat mode enabled

### ISSUE THREAD

**Issue by BlueLightner** [Yesssssman/epicfightmod#1132]
It gives a small boost of speed without any animation. 
Edit: I figured I should explain why this bug is problematic; It's very anti-synergetic with sneaking.

If I remember correctly, holding shift (with default controls) would sneak, while tapping it would use a movement skill in the last update. Right now the skills are used whether the button is held or not, so this may be two bugs relating to movement skills.

**Comment by Yesssssman** [comment]
Fixed in 18.3.1
