### ISSUE TITLE
Aim Assist Bug

### ISSUE THREAD

**Issue by BlueLightner** [Yesssssman/epicfightmod#1133]
![Screenshot_5](https://user-images.githubusercontent.com/110366759/184511772-e8503b77-6a02-4f30-b295-691413ed6148.png)
Bow and Crossbow have an offset aim assist which doesn't seem to follow the players sight. I marked a red line next to the aim assist green line so it's easier to see.

I would also like to mention my three bug reports were posted while using the latest version of Epic Fight (18.3.0 beta)

**Comment by Yesssssman** [comment]
Fixed in 18.3.1
