### ISSUE TITLE
HI bro.Can't create new worlds, can't enter existing worlds

### ISSUE THREAD

**Issue by AllenOW** [Yesssssman/epicfightmod#1135]
https://paste.fastmirror.net/?212605fc0271d68c#DFWriLB9AsUh4Y9bgUk2Fo4NBeK8gWxJHmjxshd4BUeo
This is a crash report, suspected to be a problem with this mod
I can't play after I update to 18.3.0,
EpicFight-18.3.0/fight nbt integration-1.18.2-1.0.2
minecraft1.18.2
forge40.1.69

**Comment by Yesssssman** [comment]
EpicFight NBT integration is incompatible with the latest EpicFight version.

**Comment by AllenOW** [comment]
Thank you, you are a really good developer
