### ISSUE TITLE
[Suggestion] Early Game Balancing

### ISSUE THREAD

**Issue by BlueLightner** [Yesssssman/epicfightmod#1136]
I want to thank you for the extremely quick hotfix! There still seems to be a rendering issue with aim assist for me, but that's okay.
 
Suggestion:                                                                                               
   I find it difficult to avoid damage from armed foes (Zombies, Vindicators ect) without skills. They appear to have the same attack range as players, which works great in PvP, but can feel unfair in raids/dungeon mods where these enemies appear often.
This is easily fixed once skills such as Guard, Step, and Roll are unlocked, but I figured it was worth pointing out.
 
   A valid argument could be made that this balances the early game of the mod, so no pressure from me to change anything.
   
   The idea is turning the 'Step' skill into an upgrade; adding the invulnerability. The invulnerability on both 'Step' and 'Roll' are essential for staying within attack reach of your opponent while dodging, so I think the upgrade would be worth using for both PvP and PvE scenarios. The base Step skill would be a useful skill to back away from incoming damage. It's not as efficient as side stepping with invulnerability, but it allows any player to have a consistent method of dodging attacks, regardless of progression.
   
  If it is possible to change the attack reach of armed AI, that also works. I appreciate you reading this suggestion!

**Comment by Yesssssman** [comment]
There is already an invincible frame in both Step and Roll. This is involved with how Technician (Returns the stamina if you successfully dodge the attack) works. When you're attacked during the invincible frame, the stamina is returned.
