### ISSUE TITLE
Incompatibility with OptiFine [1.18.2]

### ISSUE THREAD

**Issue by AlexLeeroy** [Yesssssman/epicfightmod#1140]
Epic Fight v18.3.1 and Epic Fight v18.3.0 both require the latest version of Forge (40.1.73). They seem to crash on any earlier version.

Optifine HD U H7 works on Forge versions 40.1.57 and below.

As far as my knowlede goes, this means that the two mods cannot run at the same time.

EF v18.2.6 (the latest release apart from the two mentioned) seems to be fully compatible.

**Comment by MetalKnight56** [comment]
won't fix, OF is not open source, nor does it use forge modding API. If you want it to be fixed, go report OF's devs this issue, and also make sure to ask them to make it open source
