### ISSUE TITLE
Potential Mod Incompatibility with Biome Makeover

### ISSUE THREAD

**Issue by Gelox1209** [Yesssssman/epicfightmod#1142]
I'm assuming this is caused by Epic Fight, but I'm unsure.

Halfway through the Adjudicator boss fight(from biome makeover), the server crashes with the following server log:
[biomemakeoverepicfightcrash.log](https://github.com/Yesssssman/epicfightmod/files/9386211/biomemakeoverepicfightcrash.log)

**Comment by Yesssssman** [comment]
Fixed in 18.3.3
