### ISSUE TITLE
Attacking with Greatsword while player moving backwards creates glitchy animation

### ISSUE THREAD

**Issue by uoissvd** [Yesssssman/epicfightmod#1145]
Attacking with Greatsword while player is moving backwards seems to create glitchy animation where the player appears to reset the sword position in the wrong direction.

Not sure whether this issue is related the bug where attack animation was playing twice while moving backwards (fixed in version 18.3.2).

**Comment by Yesssssman** [comment]
Fixed in 18.3.3
