### ISSUE TITLE
Some modded items have registry names containing illegal characters

### ISSUE THREAD

**Issue by Cirion-Spellbinder** [Yesssssman/epicfightmod#1146]
On the Wiki, there is a page titled ["Custom Weapon Armor datapack."](https://github.com/Yesssssman/epicfightmod/wiki/Custom-Weapon-Armor-datapack) This page presents a guide on making a datapack to add Epic Fight compatibility to modded weapons and armor, involving creating a series of folders and a json file with the following names:

> data -> "modid" -> capabilities -> "type" -> "registrynames".json

where `registrynames` refers to the registry name of the item which one wants to add compatibility for. However, some modded items have registry names which include illegal characters which cannot be included in file names, for example, "/" occurs in practically _all_ TerraFirmaCraft item names. See, for example, [this file from the TerraFirmaCraft source code tagging all the knives added by TerraFirmaCraft as knives.](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/8a88d088b115a14afbe5c2ad8fe6fe6f2c70e176/src/main/resources/data/tfc/tags/items/knives.json)

This means items such as "tfc:metal/knife/steel" cannot be given Epic Fight compatibility through a data pack because "tfc:metal/knife/steel.json" is not a valid file name on account of including two instances of the illegal character "/" in its registry name.

**Comment by MetalKnight56** [comment]
This is latest version issue, with the recommended forge version. This is terrafirmacraft devs comentary about this 
![image](https://user-images.githubusercontent.com/77132244/186051937-7a9a7ec1-db2f-4135-9d73-d78f08e00eba.png)

**Comment by Yesssssman** [comment]
It is abnormal to contain a slash character in item registry name. There are many other ways to express the item variation like NBT tag or capability. I don't understand why they used that inconvenient way.

**Comment by MetalKnight56** [comment]
![image](https://user-images.githubusercontent.com/77132244/186781445-8e2d25b6-ad68-4980-9367-26199103b038.png)

**Comment by MetalKnight56** [comment]
Fixed on 18.3.7 (1.18.2) and 16.6.3 (1.16.5), Check updates channel in our discord to see how to arrange the folders in order for this to work
