### ISSUE TITLE
Constant non-defined armor stun armor/weight value

### ISSUE THREAD

**Issue by DarkScorn** [Yesssssman/epicfightmod#1147]
Instead of having stun armor and weight related to armor points in previous versions, mod version 18.3.2 on minecraft forge 1.18.2- 40.1.73, all armor that are not defined via datapacks have the same (15/15) stun armor and weight value.

Edit: Vanilla armors stun armor values and weight values are same
Netherite helmet had 2.25 stun armor 9 weight before,
now it has 9 stun armor and 9 weight. I don't know if this is intentional.

Example screenshots

![2022-08-23_14 27 52](https://user-images.githubusercontent.com/24631889/186148509-85986f0f-45fd-425c-95c2-4055e452f374.png)
![2022-08-23_14 27 54](https://user-images.githubusercontent.com/24631889/186148522-1790b883-8ff9-4934-858d-45bc2a1012a6.png)

**Comment by Yesssssman** [comment]
Fixed in 18.3.3
