### ISSUE TITLE
Crashing and not explaning why (old forge versions)

### ISSUE THREAD

**Issue by gaesyeah** [Yesssssman/epicfightmod#1148]
Just crashes with old forge versions which is just normal, but without a "message" saying why or which forge version is needed

[crash-2022-08-24_14.22.43-fml.txt](https://github.com/Yesssssman/epicfightmod/files/9418248/crash-2022-08-24_14.22.43-fml.txt)
.

**Comment by MetalKnight56** [comment]
Which version of efm, minecraft and forge you on

**Comment by gaesyeah** [comment]
minecraft 1.18.2
forge 40.1.51
epic fight 18.3.3

**Comment by Yesssssman** [comment]
Update your forge version

**Comment by gaesyeah** [comment]
yeah, i know, thanks.

I openned this issue because it was the first time i saw this happening, normally minecraft leaves a "message" saying which forge version is needed, and in this case some inexperienced users could get confused.

And i actually want some help, please.

My minecraft just closes when i enter in any world if one of the latest versions of forge is installed, because of this im using forge 40.1.51 with Epic Fight 18.2.6 (isnt a crash, it really just closes before 1% world loading)

**Comment by Yesssssman** [comment]
Please attach a crash report so I can help you

**Comment by gaesyeah** [comment]
there's actually no crash report, but I discovered what's is causing this issue: optfine, it doesn't work with later forge versions.

anyway, thanks.

**Comment by Yesssssman** [comment]
Well most optifine issues are unable to fix cause it's not an API for forge. I recommend you using Rubidium to enhance the graphic performance.
