### ISSUE TITLE
Battle mode ignores skin transparency

### ISSUE THREAD

**Issue by ConnixTV** [Yesssssman/epicfightmod#1149]
See title. This bug gives an interesting effect if the transparency is only used for glasses like my skin, but I can see it being an issue for other skins.

Building mode:
![2022-08-24_13 28 20](https://user-images.githubusercontent.com/97262402/186517294-6453742c-afb3-4e49-8016-0a032918a3e2.png)

Battle mode:
![2022-08-24_13 28 33](https://user-images.githubusercontent.com/97262402/186517367-ae851fcd-95a8-4b3d-81e7-939f72dcb304.png)

**Comment by Yesssssman** [comment]
Fixed at 18.3.6
