### ISSUE TITLE
[1.18.2 Forge 40.1.73] Dying in battle mode causes hotbar number keys to stop working

### ISSUE THREAD

**Issue by DeadlyAccurate** [Yesssssman/epicfightmod#1153]
EpicFight-18.3.3-beta.jar

This is an odd issue, but it does have a bit of a workaround. Whenever I die while still in battle mode, I can no longer use the top row of number keys on my laptop. Other keys still work fine, but I can't switch hotbar slots with the number keys. 

If I die again while not in battle mode, the keys return to normal, so I can work around the issue, but I wanted to go ahead and report it.

**Comment by Yesssssman** [comment]
https://user-images.githubusercontent.com/79469058/186848725-00932e0b-02fe-4173-a9a2-60c0fa4dc2dc.mp4

Can you try it again

**Comment by DeadlyAccurate** [comment]
OK, I tried again with the same world save and it's not happening, so I'll assume it was a fluke. If it happens again, I'll try to narrow down the exact issue.
