### ISSUE TITLE
Crash with rendering epic fight skill books

### ISSUE THREAD

**Issue by InteJason** [Yesssssman/epicfightmod#1154]
Version: 1.18.2-18.3.2

https://paste.gg/p/anonymous/f2a967fbb0544674b71caddf874c4ba2

**Comment by MetalKnight56** [comment]
update to latest

**Comment by InteJason** [comment]
Alright just did, same issue in 18.3.3: https://paste.gg/p/anonymous/51b1db5b5475430b98f59dc79c035bb1

**Comment by Yesssssman** [comment]
What skill book did you try to render?

**Comment by MetalKnight56** [comment]
Try deleting rubidium and oculus, both of them seem to have caused an unexpected crash

**Comment by InteJason** [comment]
the skill book was 'dodge'

**Comment by Yesssssman** [comment]
Well, all I can know from the the crash report is it doesn't have a skill stored in item NBT but tried to render skill description UI.

What did you do?

**Comment by Yesssssman** [comment]
I tweaked some code to check if the skill NBT is valid. But please check what exactly went wrong to avoid potential problems.
