### ISSUE TITLE
Incorrect "Stun Armor" and "Weight" attributes of Armors.

### ISSUE THREAD

**Issue by uoissvd** [Yesssssman/epicfightmod#1155]
Epic Fight Version: 18.3.3 (latest)
Forge Version: 1.18.2-40.1.73

Vanilla Armor pieces have correct Stun Time and Weight attributes but any armor from custom mods all have +0.75 Stun Time and +5 Weight regardless of their defense points.

Tested with Twilight Forest and Epic Knight mods.

In previous version of Epic Fight (18.2.5 and before), armors from custom mods had correct Stun Time and Weights applied depending on their defense points by default so no datapack is required to configure them individually (unless you want to make explicit changes).

Not sure whether this is an expected change in the latest version or a bug..

**Comment by Yesssssman** [comment]
Fixed in 18.3.4
