### ISSUE TITLE
Incompatibility with Skin Layers 3D

### ISSUE THREAD

**Issue by Neposis** [Yesssssman/epicfightmod#1156]
Hiya,
Due to the nature of the mod, the skin layers mod doesn't work with epic fight.

![image](https://user-images.githubusercontent.com/53699708/186925535-e1ba4f67-21e1-4fa2-a215-e6240027d5ed.png)

**Comment by MetalKnight56** [comment]
This nis a known issue, we'll be working with tr7zw to fix several issues between his mods and epic fight, as of now this has been denied several times
