### ISSUE TITLE
How to configure items with "/" slashes in their ids?

### ISSUE THREAD

**Issue by Dyshonored** [Yesssssman/epicfightmod#1157]
Tried to create a weapon armor datapack for stun armour attributes for the mod "TerraFirmaCraft". However, the item ids for equipment from that mod contained "/" slashes. This prevented me from creating .json files with the exact ids of the items I wanted to edit (which is required according to the wiki of this site)

**Comment by Dyshonored** [comment]
May be changing how datapack is read by the mod so that the item id is taken from a parameter within the .json file itself instead of from the file name?

**Comment by Dyshonored** [comment]
Same issue as #1146, actually

**Comment by MetalKnight56** [comment]
Fixed on 18.3.7 (1.18.2) and 16.6.3 (1.16.5), Check updates channel in our discord to see how to arrange the folders in order for this to work
