### ISSUE TITLE
no animations

### ISSUE THREAD

**Issue by whenisthedoor** [Yesssssman/epicfightmod#1159]
why are the epic fight animation not working?

**Comment by MetalKnight56** [comment]
No mod version, mod loader version, mc version, if on server or multiplayer, modlist, crash log, log, i'm not omniscent to know whats happening

**Comment by Woodgoldtwo** [comment]
have you tried pressing r

**Comment by whenisthedoor** [comment]
how do i enter combat mode

**Comment by Woodgoldtwo** [comment]
press r

**Comment by Woodgoldtwo** [comment]
there is also a config option that makes the animations play even when you are not in combat mode

**Comment by whenisthedoor** [comment]
what

**Comment by Yesssssman** [comment]
Read the description on Curseforge page. If the problem still exists, then report again here with more specific information.
