### ISSUE TITLE
[1.18.2 Forge 40.1.74] "this.weaponAttackMotions" is null (sorta fixed but then new error); possible incompat with Pokecube AIO

### ISSUE THREAD

**Issue by DeadlyAccurate** [Yesssssman/epicfightmod#1162]
I would really love to salvage both mods in my modpack, so I'm giving this one a shot, as crazy as it may be. 

OK, so I mentioned this on Discord, but yesterday during testing, I would randomly get a freeze then CTD, even though I wasn't in combat mode and wasn't even looking at anything but the ground. Here's the crash report.

https://pastebin.com/Qj9GAeCp

My husband is a programmer, though not in Java, so he took a look at the source code and figured a possible fix would be to add on line 97 (the line above the error)

if (this.weaponAttackMotions == null) { return null;}

We rebuilt the mod, put it in the pack, removed the Curseforge one, and I started testing again. All seemed great for quite a while. I was fighting zombies and spiders and skeletons without issues. Then I started walking toward a Pokecube village, and it froze and crashed again. With a new error.

https://pastebin.com/SKqwqrz4

Of course, I don't know for sure that Pokecube AIO is the incompatible mod, but I ran a test by making a fighting pit and spawning in zombies with various mods' weapons and objects in hand in an attempt to get a crash, and it never did.

These are the versions of the two mods I'm using.

pokecube-aio-1.18.2-3.17.3.jar
EpicFight-18.3.3-beta.jar

What other information would help in debugging this? I've pulled Pokecube for now, but I *really* want to add it to my pack if possible.

**Comment by MetalKnight56** [comment]
downgrade forge version to 40.1.73

**Comment by MetalKnight56** [comment]
Hey there, so afaik you are using 40.1.74 forge version, could you try and downgrade the forge version to recommended one (40.1.73)

**Comment by DeadlyAccurate** [comment]
Sure, I can try that. I think I started getting this problem on 40.1.73 and upgraded to see if that would fix it, but at this point I honestly don't remember.

**Comment by DeadlyAccurate** [comment]
Still the same crash. Unfortunately, I can't figure out which mod it's happening with. I no longer think it's Pokecube. It *might* be Apotheosis's Adventure Module (the named special mobs that spawn), but the only reason I can say that is during one of my pack tests, I started adding in mods one at a time and it happened shortly after adding Apotheosis. But I couldn't recreate it even after hours of running around. (Also, I've tried both with and without the Apotheosis datapack).

I can go hours without any issues and then it'll suddenly happen when I step outside of my base with nothing around. I've tried mods like Not Enough Crashes to see if it would report the mods it suspects is the issue, but I've had no luck. If I get any more information, I'll let you know.

**Comment by Yesssssman** [comment]
Could you provide the datapack? Well, the solution you've suggested was kinda first-aid. I'll take a look at the logic that can cause the crash by comparing your datapack.

**Comment by Yesssssman** [comment]
Haven't you set any datapack regarding custom entity? The last log you put on the pastebin tells that you're using entity datapack. (The Null pointer exception at CustomHumanoidMobPatchProvider). Or has pokecube-aio made their own datapack to make compatible their entities with epicfight?

**Comment by DeadlyAccurate** [comment]
I had a couple of datapacks for Epic Fight. One for Guard Villagers and one for Tinker's Construct. The others were for mob heads, player heads, and multiplayer sleep, and armor statues.

Would the Armor Statues datapack be considered an entity pack? 
https://vanillatweaks.net/share#GN7Bfj

**Comment by Yesssssman** [comment]
I mean this one: https://github.com/Yesssssman/epicfightmod/wiki/Custom-entity-datapack

Isn't there any datapack folder name starts with epicfight_mobpatch?

**Comment by DeadlyAccurate** [comment]
I used the datapacks I got off your Discord (Epic_Construct for the Tinker's integration; guardepic for Guard Villagers; and Epic_Apotheosis for Apotheosis integration).

https://discord.com/channels/955784714264932362/964701095056257034/1013500158077575318
https://discord.com/channels/955784714264932362/964701095056257034/996768180972290108
https://discord.com/channels/955784714264932362/964701095056257034/1010259026531057745

But no other Epic Fight datapacks.

**Comment by Yesssssman** [comment]
Ok, the crash report says your data pack tried to make custom AI for zombies but loaded incorrectly somewhat reason. Can you still reproduce this crash?

**Comment by DeadlyAccurate** [comment]
Sure, I'll do that tonight and post the next crash report to pastebin once it's happened.

**Comment by DeadlyAccurate** [comment]
It took hours before it finally crashed, but it eventually did. I walked into a building in the overworld, and the game froze, then crashed to desktop. I wasn't in combat, and I think it was daylight. I was in creative mode (other times I've been in survival).

https://pastebin.com/RPeEd3eE

Does the error message mean that a creature is spawning with something in its hand that the mod is struggling to recognize? I've tested spawning in zombies with all of Epic Fight's weapons, with Tinker's weapons, and with vanilla's. I've summoned Apotheosis bosses and set them to fight Guard Villagers. I've done that for hours and never had a problem. Zombies even handle dual-wielding daggers without a problem.

**Comment by Yesssssman** [comment]
Sorry, but could you post the full log file? It's under /.minecraft/logs folder named debug.log

**Comment by DeadlyAccurate** [comment]
My more recent modpack tests were without Epic Fight, and I don't have a debug.log file in that folder, so I'll have to re-add the mod and retest. It may be a while before I can provide the file, though; house purchase + AirBnb move is taking up a lot of time.

**Comment by MetalKnight56** [comment]
Fixed in 18.3.5

**Comment by Yesssssman** [comment]
Ok I simply fixed it with first proposal. But still please provide me a debug.log file if you like, to enhance the wiki page by specifying misused example.
