### ISSUE TITLE
Enderdragon will not land outside of the End

### ISSUE THREAD

**Issue by Cirion-Spellbinder** [Yesssssman/epicfightmod#1165]
Outside the End, the enderdragon will not land on the ground so you can attack it. The enderdragon will just keep flying upwards, even if you damage it.

https://user-images.githubusercontent.com/51251479/187832290-61472808-c4c1-4a9a-8286-051df28d36c5.mp4

**Comment by Yesssssman** [comment]
This is not a bug but it's how her AI is designed. She keeps searching for a landing point nearby an ender podium, which does not exist in the overworld.
