### ISSUE TITLE
Epic Fight (epicfight) has failed to load correctly 

### ISSUE THREAD

**Issue by DankMemesLife** [Yesssssman/epicfightmod#1168]
java.lang.NoClassDefFoundError:
![Screenshot 2022-09-01 072434](https://user-images.githubusercontent.com/90221878/187902972-c325f3ec-7d1b-49eb-9053-70a8a6c34821.png)

**Comment by Yesssssman** [comment]
Update the forge.

**Comment by DankMemesLife** [comment]
oh

**Comment by DankMemesLife** [comment]
Thank you
