### ISSUE TITLE
[Bug]: Config File does not work

### ISSUE THREAD

**Issue by Adzeiros** [Yesssssman/epicfightmod#1169]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

So I wanted to change the config so I don't lose learned skills on death.

I exited the game and opened the epicfight.toml file inside the root config folder (there is no config file in individual game saves, I checked) I changed the settings in there to what I wanted and saved it.

I then re-launched the game and joined my world, where I tested Vanilla attacks (as I had disabled that inside the config). I was able to use vanilla attacks which means it did not load from the config...

I then used the in-game command to disable vanilla attacks, which worked fine. However, upon leaving my save and reloading back in the setting reverted back to the default, and vanilla attacks were enabled again...

I have tested with the latest version of EpicFight 18.3.3 and older versions (18.3.2 and 18.3.1) they didn't work either.

**Comment by Yesssssman** [comment]
You misunderstood the concept of "default_gamerule". It means the game rule value that is set when you create a new world, doesn't mean that it'll be applied when you join the existing world.

And so I assume that you did something wrong with your last attempt, which does not happen on my side when I tested it. Could you try it again?

**Comment by Adzeiros** [comment]
> 

I attempted to update my forge version to the one recommended which did not work...

I did, in fact, misunderstand that it was an initial setting. I have since just used NBT Explorer to manually change the game rules of my save, since then they have stuck and everything is fine. Thanks!
