### ISSUE TITLE
Support For Spartan Shields Mod

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#117]
I dont like vanilla shield too much.
I liked spartan shields mod but it has problems with this mod.

Can you add compatibility for them please ?
Version Of Spartan Shields is 1.12.2

**Comment by Yesssssman** [comment]
What's the problem?

**Comment by TurkishAhmet4545** [comment]
> What's the problem?

Shields are looking in bad rotation.

**Comment by TurkishAhmet4545** [comment]
I've Checked the new version of mod and i seen that this bug is fixed. 👍
