### ISSUE TITLE
[Bug]: Climbing up a ladder does not play the climbing animation.

### ISSUE THREAD

**Issue by uoissvd** [Yesssssman/epicfightmod#1170]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

If you are in Battle Mode (with 3rd person view) and try to climb up a ladder using 'W' key (i.e. without any side movements), the climbing animation plays for a little bit and then no longer gets played.

It is more noticeable with ladders that are high (e.g. more than 6~7 blocks high).

It seems the issue is caused by some calculation performed in the _getPlaySpeed_() method of the **MovementAnimation** class. If I rebuild the mod to ignore the calculations in that method (so that it always return 1.0F), I do not notice the issue.

**Comment by Yesssssman** [comment]
Fixed in 18.3.4
