### ISSUE TITLE
Resource Pack Texture Issues [Bug]

### ISSUE THREAD

**Issue by FaintApricity** [Yesssssman/epicfightmod#1171]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

![Screenshot_6](https://user-images.githubusercontent.com/112509182/188288767-444a816e-5e07-4060-9284-80eadb5778ed.png)
While in combat mode, some of the textures from resource packs (In this case; Faithless 1.18.2) have a visual glitch in the inventory. 

The game does not crash, that was a mislabel. I apologize.

**Comment by Yesssssman** [comment]
Is this caused by epicfight?
