### ISSUE TITLE
[Crash]: Randomly crashed when changing off-hand weapon

### ISSUE THREAD

**Issue by INooBTooMuch** [Yesssssman/epicfightmod#1172]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

I'm not sure how to search about the problem in the already reported issues and it didn't happen again but, I originally crashed when I tried to move a Sword from off-hand and change it with another sword ([Forbidden and Arcanus](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus) sword and another with [Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis) affix loot).

So as I said I tried to replicate it and couldn't but here is the [Log](https://gist.github.com/INooBTooMuch/0a91d732c2733501306365ef3ec419eb).

**Comment by Yesssssman** [comment]
Crash with majruszsdifficulty mod. I'm not sure why this is happening so recommend you remove it temporarily.
