### ISSUE TITLE
[Bug]: Mobs from The Graveyard (FORGE)

### ISSUE THREAD

**Issue by INooBTooMuch** [Yesssssman/epicfightmod#1173]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

[The Graveyard (FORGE)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)

### Minecraft Version

1.18.2

### What happened?

Mobs don't have health indicators. (only 3 do)
They also don't have the animations and attacks balanced for Epic Fight, but it is what it is.

**Comment by Yesssssman** [comment]
You have to set the datapack to make them compatible.

https://github.com/Yesssssman/epicfightmod/wiki/Custom-entity-datapack

**Comment by INooBTooMuch** [comment]
Its a little bit overwhelming. 
I change this to the mob I want to add "renderer": "minecraft:zombie"
This "isHumanoid" if they have a weapon or not
This "faction": "neutral" for agro to each other (undead and illagers)
I don't feel like I should mess with "attributes"
I can't find other values for "default_livingmotions" in the exaple all are "living" or is it if the mob is not killed? (I thought it was undead/living)
Infront of the animations I should put "epicfight:" and the path (epicfight:illager/idle_aggressive)
Also there is BIPED and mob specific animations, in the exaple of the zombie there are "idle": "epicfight:biped/living/idle", should I use this for the rest or (since the mob is a corrupted vindicator) the vindicator "illager/idle_aggressive" one?

**Comment by INooBTooMuch** [comment]
So I made [this](https://gist.github.com/INooBTooMuch/ed2b11eea5628187df79522a2ea76ae6) for one of the mobs that seems similar to a vindicator is everything normal and would it work?
