### ISSUE TITLE
my wolf does not attack

### ISSUE THREAD

**Issue by Bem20** [Yesssssman/epicfightmod#1174]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

when I hit with epic fight, my wolf doesn't fight, but with the vanilla hit, my wolf does attack. Im using the last version of epic fight mod and the recommended version of forge for that version of the mod

[https://imgur.com/a/OIY6twn](url)

Thanks for your support.

**Comment by MetalKnight56** [comment]
Fixed in 18.3.5
