### ISSUE TITLE
[Bug] Epic Fight weapons ignoring invulnerable tag

### ISSUE THREAD

**Issue by Catomax262** [Yesssssman/epicfightmod#1175]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

For some reason when i attack an invulnerable enemy it just surpasses the tag and deals normal damage to it. I am specifically stating this due to Flash's NPCs mod's NPCs taking damage if i hit them with e.g. a tachi. This is not a mod incompatibility between Epic Fight and Flash's NPCs because i tested it with an invulnerable zombie and it took damage.

**Comment by Yesssssman** [comment]
Were you a creative mode? It ignores the invulnerable tag if you're in creative mode both normal and epicfight attacks.
