### ISSUE TITLE
[Bug]: Small Animation Bug

### ISSUE THREAD

**Issue by FaintApricity** [Yesssssman/epicfightmod#1176]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

The Katana is not put back in the scabbard
![Screenshot_11](https://user-images.githubusercontent.com/112509182/188979227-e808b210-e334-41a7-87a9-73c2995a2325.png)
Edit: I'm unsure how to prevent to "crash" tag from appearing, this doesn't crash the game either

**Comment by Yesssssman** [comment]
Is it latest version?
