### ISSUE TITLE
[Bug]: Apotheosis Affixes

### ISSUE THREAD

**Issue by INooBTooMuch** [Yesssssman/epicfightmod#1177]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

[Apotheosis](https://www.curseforge.com/minecraft/mc-mods/apotheosis)

### Minecraft Version

1.18.2

### What happened?

Apotheosis has some Affixes that are applied to loot, mainly I think Attack Range, Critical Chance (& Critical Damage) affixes don't apply when attacking with "Battle Mode" on. Range is understandable but since you cant crit with normal attacks when in "Battle Mode" I think that affixes should still let you (since you cant change affixes on a weapon).

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users

**Comment by Shadowyjp** [comment]
When this update gonna come?

**Comment by MetalKnight56** [comment]
> When this update gonna come?

We'll be running a closed beta pretty soon. If you want to participate in it, make sure to sign up in here: https://forms.gle/MZaFs56opiXhLhb2A
