### ISSUE TITLE
Support for FirstPersonModel mod

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#118]
I liked first person model mod too much,but it is some buggy with this mod.
Can you make compatibility with it please :(

**Comment by Yesssssman** [comment]
Turn on the "filter animation" option. It will solve the problem by disabling the mod animation in mining mode.

**Comment by TurkishAhmet4545** [comment]
> Turn on the "filter animation" option. It will solve the problem by disabling the mod animation in mining mode.

Is this feature available for 1.12.2 ?

**Comment by Yesssssman** [comment]
Yes

**Comment by TurkishAhmet4545** [comment]
> Yes

I want to be able to use first person model mod with animations turned on.

**Comment by TurkishAhmet4545** [comment]
I can't believe it ! 
I didnt know you fixed this already.
:)

**Comment by HeroRyker** [comment]
Wait how did he fix it?

**Comment by HeroRyker** [comment]
It is still broken for me
