### ISSUE TITLE
Crash on hiting entity [Crash]: 

### ISSUE THREAD

**Issue by Reavez5** [Yesssssman/epicfightmod#1180]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Game crashes every time im trying to hit someone in battle mod
[tl-logger3404938069644705333.txt](https://github.com/Yesssssman/epicfightmod/files/9560465/tl-logger3404938069644705333.txt)

**Comment by MetalKnight56** [comment]
Please make sure to remove every single mod then add one by one to find which mod is causing this issue.

**Comment by Yesssssman** [comment]
@MetalKnight56 Well after taking a look at the log this crash is fully responsible for Epic Fight.

**Comment by Yesssssman** [comment]
Wait, you're not using the latest forge version. Please update the forge and if this happens again, report again.
