### ISSUE TITLE
All the armor is broken [Bug]

### ISSUE THREAD

**Issue by Reavez5** [Yesssssman/epicfightmod#1181]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Every armor, even vanilla, is broken in battle mode. 
![image](https://user-images.githubusercontent.com/93596875/190000701-f2c3389d-1872-4cef-8379-f61d428772a5.png)
[latest.log](https://github.com/Yesssssman/epicfightmod/files/9560483/latest.log)

**Comment by MetalKnight56** [comment]
Looks like you have loads of mods installed, make sure to remove one by one and see which one is causing this issue, if you have any ResourcePacks, alsomake sure to remove those for now so we can track down this issue

**Comment by maximogta** [comment]
Same bug here, happens even when Epic Fight is the only mod installed, without resourcepacks or datapacks loaded, 1.16.5, EpicFight-16.6.0-ALPHA. Forge 36.2.29

**Comment by MetalKnight56** [comment]
Did you have optifine ?

**Comment by maximogta** [comment]
No, tried it in a new instance with fresh forge install trough curseforge launcher.

**Comment by MetalKnight56** [comment]
Weird... What forge version are you using? the recommended is 40.1.80

**Comment by maximogta** [comment]
In curseforge launcher for mc 1.16.5 the latest forge version is Forge 36.2.29, is what I used,same bug wit Forge 36.2.34.

**Comment by MetalKnight56** [comment]
ok, i'll report this to the lead developer so he can take an in depth look at it

**Comment by maximogta** [comment]
in 1.18.2 this bug does not exist, tested right now with latest Epic Fight version.

**Comment by Yesssssman** [comment]
Fixed in 16.6.1.
