### ISSUE TITLE
[Bug]: Flying animation with elytra. EpicFight-16.6.0-ALPHA 1.16.5

### ISSUE THREAD

**Issue by maximogta** [Yesssssman/epicfightmod#1182]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Forge version 36.2.39
Epic fight is the only mod loaded and no resourcepack or datapack are loaded. 
Combat mode activated.
When flying with elytra the player does not fly straight, it tilts from left to right and becomes invisible temporarily, the flying animation isn't working.
Visual bug.

**Comment by Yesssssman** [comment]
Fixed in 16.6.1
