### ISSUE TITLE
Addon making [need help]: 

### ISSUE THREAD

**Issue by Reavez5** [Yesssssman/epicfightmod#1184]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

We Can do our mod on 1.18.2. Version is not significant for us. But we still need help.

**Comment by Yesssssman** [comment]
https://discord.com/invite/NbAJwj8RHg
Can you open a new forum regarding this issue? It's pretty hard to understand what you like to do.

**Comment by Yesssssman** [comment]
Let me share the sample code since Weapons of Minecraft is private now.

```
@Mod.EventBusSubscriber(modid = YourModId.YOUR_MOD_ID , bus = EventBusSubscriber.Bus.MOD)
public class YourSkills {
	
	public static Skill YOUR_SKILL;
	
	@SubscribeEvent
	public static void registerSkills(SkillRegistryEvent event) {
		
		YOUR_SKILL = event.registerSkill(
				
				new YourSkill(
						YourSkill.createYourBuilder(
							new ResourceLocation(YourMod.YOUR_MOD_ID, "yourskillname")
						);
				)
		);
	}
}```

**Comment by Reavez5** [comment]
> Let me share the sample code since Weapons of Minecraft is private now.
> 
> ```
> @Mod.EventBusSubscriber(modid = YourModId.YOUR_MOD_ID , bus = EventBusSubscriber.Bus.MOD)
> public class YourSkills {
> 	
> 	public static Skill YOUR_SKILL;
> 	
> 	@SubscribeEvent
> 	public static void registerSkills(SkillRegistryEvent event) {
> 		
> 		YOUR_SKILL = event.registerSkill(
> 				
> 				new YourSkill(
> 						YourSkill.createYourBuilder(
> 							new ResourceLocation(YourMod.YOUR_MOD_ID, "yourskillname")
> 						);
> 				)
> 		);
> 	}
> }```
> ```

Thank you so much!
