### ISSUE TITLE
Connection lost, Server closed [Crash]

### ISSUE THREAD

**Issue by Reavez5** [Yesssssman/epicfightmod#1186]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Connection lost, Server closed after hiting enemy with greatsword.

**Comment by Yesssssman** [comment]
Crash repo?

**Comment by Reavez5** [comment]
[latest.log](https://github.com/Yesssssman/epicfightmod/files/9587159/latest.log)

**Comment by Yesssssman** [comment]
Do you still get this crash? I guess it's temporal or something went wrong just once.

**Comment by Yesssssman** [comment]
Nah, this was because the lower forge version. I think you already solved this so I'll just close this issue.
