### ISSUE TITLE
Latest Code Update

### ISSUE THREAD

**Issue by uoissvd** [Yesssssman/epicfightmod#1187]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Hi,

Would it be possible to update the codes in the github to the latest version (18.3.6)?
I'm trying to make some custom patch to work with another mod and it would be great if I can use the latest code.

Sorry for putting this in the issues page but I can't find a suitable place to make such a request to.

Thanks

**Comment by Yesssssman** [comment]
Sure, I just needed to keep the changed codes cause I'm working on both version now.
