### ISSUE TITLE
[Bug]: mobs animation dont work

### ISSUE THREAD

**Issue by LouisDkat** [Yesssssman/epicfightmod#1188]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

all their animations are broken they just walk with their base stand pose and dont show the moving animation

**Comment by Yesssssman** [comment]
Have you read the guideline for reporting any bugs? I can't help you without the information that what is causing this issue.

**Comment by MetalKnight56** [comment]
Footage too, we need footage
