### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Leg4res** [Yesssssman/epicfightmod#1189]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight Mod

### Minecraft Version

1.16.5

### What happened?

I wanted to play my modpack with friends, so i created a server, but every time we hit any entity in battle mod, game crashes. I tried same in singleplayer, but it works fine. Here crash reports:
[crash-2022-09-16_04.26.14-client.txt](https://github.com/Yesssssman/epicfightmod/files/9580250/crash-2022-09-16_04.26.14-client.txt)
[crash-2022-09-16_04.43.37-client.txt](https://github.com/Yesssssman/epicfightmod/files/9580251/crash-2022-09-16_04.43.37-client.txt)

**Comment by Yesssssman** [comment]
Could you check this on 16.6.1?

**Comment by Leg4res** [comment]
I tried, everything same, but instead of crashing, i just got kicked off the server with an "internal server error".

**Comment by Leg4res** [comment]
> Could you check this on 16.6.1?

I tried, everything same, but instead of crashing, i just got kicked off the server with an "internal server error".

**Comment by MetalKnight56** [comment]
> > Could you check this on 16.6.1?
> 
> I tried, everything same, but instead of crashing, i just got kicked off the server with an "internal server error".

Please try attaching the server log and the client log so we can take a look at whats happening

**Comment by ItzXPurpleX** [comment]
I am experiencing the same thing
[crash-2022-09-17_02.49.44-server.txt](https://github.com/Yesssssman/epicfightmod/files/9590810/crash-2022-09-17_02.49.44-server.txt)
I believe this is the crash report for this issue if it would be of any help

**Comment by infinite990** [comment]
Me too.
Running a modified config.
[crash-2022-09-17_20.35.07-server.txt](https://github.com/Yesssssman/epicfightmod/files/9592515/crash-2022-09-17_20.35.07-server.txt)

**Comment by Yesssssman** [comment]
@infinite990 your forge version is not latest version. Please update the forge version and test it again.

**Comment by Yesssssman** [comment]
> 

If you're using dedicated server, Check both client and server have same forge and epicfight version.
