### ISSUE TITLE
[Bug]: Pillager and Piglins with Crossbow frequently shows animation glitch when attacking.

### ISSUE THREAD

**Issue by uoissvd** [Yesssssman/epicfightmod#1190]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

You frequently notice Pillagers/Piglins (with Crossbow) twist their body until its very thin.

To replicate: Spawn some Pillagers (or Piglins with Crossbow) then move around a bit and wait until they charge the crossbow and attack you.

![2022-09-17_02 42 32](https://user-images.githubusercontent.com/2747729/190667194-b55b59c5-8479-4cdc-926c-afe8375b89fd.png)

**Comment by Woodgoldtwo** [comment]
This is because they are coded to always look at you

**Comment by Woodgoldtwo** [comment]
But the game decides to rotate it 361 degrees insead of 1

**Comment by MetalKnight56** [comment]
Could you send your modlist if you have any

**Comment by uoissvd** [comment]
Hi,

I have tested without any mods other than Epic Fight Mod.

Epic Fight Mod version 18.3.6
Forge Version 40.1.80

Thanks

**Comment by uoissvd** [comment]
Just adding some notes ..

If I disable the 2nd/3rd person logic for non-player entities in getPoseByTime(..) and modifyPose(..) methods in AimAnimation.java, the glitch seems to disappear.

Both methods are currently using a single condition !entitypatch.isFirstPerson() which makes the logic applicable to both Player and Mobs.

While it appears to fix the glitch, I'm not exactly sure whether it is okay to disable the logic for non-player entities..

**Comment by DragonAstemirN** [comment]
I have the same problem
minecraft version 1.16.5
private only with epicfightmod, without any other mod
same problem

Spawn some Pillagers (or Piglins with Crossbow) then move around a bit and wait until they charge the crossbow and attack you.

**Comment by MetalKnight56** [comment]
This issue has been fixxed on the latest commit, you don't need to worry about this anymore as the next update will cover this.

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users

**Comment by FoxeLocklear** [comment]
It's doing this in the most recent version too
