### ISSUE TITLE
[Bug|Crash]: Ender Dragon landing causes a crash

### ISSUE THREAD

**Issue by Sazuzaki** [Yesssssman/epicfightmod#1192]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 16.6.1

### Minecraft Version

1.16.5

### What happened?

Just testing out the backports for 1.16.5, and found out the Ender Dragon crashes when landing. 

Crash log: https://pastebin.com/r1Lnuf88

**Comment by Yesssssman** [comment]
Fixed in 16.6.2
