### ISSUE TITLE
[Bug|Crash]: Hitting or Receiving Damage Crashes the Game

### ISSUE THREAD

**Issue by Zexecraftian** [Yesssssman/epicfightmod#1193]
### Have you checked if a similar issue is already reported by someone else?

- [ ] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

If I go into battle mode and hit a mob, it crashes the game. Along with this, if a mob such as a zombie hits me, it also crashes the game. Creeper explosions and arrows don't cause crashes.

Here is the crash report for further info:
[crash-2022-09-18_10.34.10-server.txt](https://github.com/Yesssssman/epicfightmod/files/9593008/crash-2022-09-18_10.34.10-server.txt)

**Comment by Yesssssman** [comment]
Update the forge
