### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by PlatinumOx** [Yesssssman/epicfightmod#1196]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

whenever i attack anything while in combat mode it crashes, the error on launcher says: The game crashed whilst ticking player
Error: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;)Lnet/minecraft/entity/EntitySize;
the exit code says: -1
it is the only mod installed, i downloaded the recommended version of forge 1.16.5 but it still crashes, i dont know how to fix this, i play on single player

**Comment by MetalKnight56** [comment]
Upload the crash log

**Comment by PlatinumOx** [comment]
how do i upload it, i just punch something then it gives me the error that i stated after it crashes

**Comment by MetalKnight56** [comment]
> how do i upload it, i just punch something then it gives me the error that i stated after it crashes

Well that is useless, you need to get the log drag and drop it here, thats how you upload it, simple

**Comment by PlatinumOx** [comment]
where do i find the crash log, im new to java, i purchased the pc version 3 days ago

**Comment by MetalKnight56** [comment]
> where do i find the crash log, im new to java, i purchased the pc version 3 days ago

It has nothing to do with java, its on your .minecraft folder, its literally a folder called "LOGS"

**Comment by PlatinumOx** [comment]
oh alr give me a sec

**Comment by PlatinumOx** [comment]
[2022-09-18-4.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602559/2022-09-18-4.log.gz)
[2022-09-18-5.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602560/2022-09-18-5.log.gz)
[2022-09-18-6.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602561/2022-09-18-6.log.gz)
[latest.log](https://github.com/Yesssssman/epicfightmod/files/9602562/latest.log)
[2022-09-15-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602563/2022-09-15-1.log.gz)
[2022-09-16-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602564/2022-09-16-1.log.gz)
[2022-09-16-2.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602565/2022-09-16-2.log.gz)
[2022-09-16-3.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602566/2022-09-16-3.log.gz)
[2022-09-16-4.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602567/2022-09-16-4.log.gz)
[2022-09-16-5.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602568/2022-09-16-5.log.gz)
[2022-09-17-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602569/2022-09-17-1.log.gz)
[2022-09-17-2.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602570/2022-09-17-2.log.gz)
[2022-09-17-3.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602571/2022-09-17-3.log.gz)
[2022-09-17-4.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602572/2022-09-17-4.log.gz)
[2022-09-17-5.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602573/2022-09-17-5.log.gz)
[2022-09-17-6.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602574/2022-09-17-6.log.gz)
[2022-09-17-7.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602575/2022-09-17-7.log.gz)
[2022-09-18-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602576/2022-09-18-1.log.gz)
[2022-09-18-2.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602577/2022-09-18-2.log.gz)
[2022-09-18-3.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602578/2022-09-18-3.log.gz)

**Comment by PlatinumOx** [comment]
there are the logs i found inside
\

**Comment by PlatinumOx** [comment]
it said folder isnt supported so i had to send them like that, sorry

**Comment by MetalKnight56** [comment]
> [2022-09-18-4.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602559/2022-09-18-4.log.gz) [2022-09-18-5.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602560/2022-09-18-5.log.gz) [2022-09-18-6.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602561/2022-09-18-6.log.gz) [latest.log](https://github.com/Yesssssman/epicfightmod/files/9602562/latest.log) [2022-09-15-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602563/2022-09-15-1.log.gz) [2022-09-16-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602564/2022-09-16-1.log.gz) [2022-09-16-2.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602565/2022-09-16-2.log.gz) [2022-09-16-3.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602566/2022-09-16-3.log.gz) [2022-09-16-4.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602567/2022-09-16-4.log.gz) [2022-09-16-5.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602568/2022-09-16-5.log.gz) [2022-09-17-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602569/2022-09-17-1.log.gz) [2022-09-17-2.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602570/2022-09-17-2.log.gz) [2022-09-17-3.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602571/2022-09-17-3.log.gz) [2022-09-17-4.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602572/2022-09-17-4.log.gz) [2022-09-17-5.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602573/2022-09-17-5.log.gz) [2022-09-17-6.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602574/2022-09-17-6.log.gz) [2022-09-17-7.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602575/2022-09-17-7.log.gz) [2022-09-18-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602576/2022-09-18-1.log.gz) [2022-09-18-2.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602577/2022-09-18-2.log.gz) [2022-09-18-3.log.gz](https://github.com/Yesssssman/epicfightmod/files/9602578/2022-09-18-3.log.gz)

You are kidding me right? Dude you just uploaded the whole folder without the debug one, i don't need any of these, just latest and debug

**Comment by PlatinumOx** [comment]
bro im new to this kind of stuff so im a lil confused

**Comment by PlatinumOx** [comment]
ima look for latest

**Comment by PlatinumOx** [comment]
[latest.log](https://github.com/Yesssssman/epicfightmod/files/9602594/latest.log)
i cant find one called debug ill keep looking

**Comment by PlatinumOx** [comment]
cant find it in logs and i cant find it in search, is there a specific folder?

**Comment by MetalKnight56** [comment]
> cant find it in logs and i cant find it in search, is there a specific folder?

Logs

**Comment by PlatinumOx** [comment]
> > cant find it in logs and i cant find it in search, is there a specific folder?
> 
> Logs

there is nothing called debug or has debug in its name in log

**Comment by PlatinumOx** [comment]
there is only logs with dates on em, they are the ones i sent above

**Comment by MetalKnight56** [comment]
This is a vanilla issue, when joining the world click on f3 + S that should reload your sound manager, and thus fix the issue, afaik this is not an issue with epic fight

**Comment by PlatinumOx** [comment]
> This is a vanilla issue, when joining the world click on f3 + S that should reload your sound manager, and thus fix the issue, afaik this is not an issue with epic fight

ill try it then punch something

**Comment by PlatinumOx** [comment]
i clicked f3 and s and didnt do anything, clicked it multiple times again and it still crashed when i hit something, is there a specific setting that should be on or off?

**Comment by PlatinumOx** [comment]
ill probably go to sleep and try to fix this tommorow, i have been trying for a few hours now, thank you for your patience, ill check this again when i wake up

**Comment by MetalKnight56** [comment]
Closing this current issue, as the user violated the support policy by not updating the forge version to the recommended trhus causing the issue.

**Comment by PlatinumOx** [comment]
im back
