### ISSUE TITLE
[Bug|Crash]: crashes each time i hit something

### ISSUE THREAD

**Issue by PlatinumOx** [Yesssssman/epicfightmod#1197]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [x] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

whenever i attack anything while in combat mode it crashes, the error on launcher says: The game crashed whilst ticking player
Error: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;)Lnet/minecraft/entity/EntitySize;
the exit code says: -1
it is the only mod installed, i downloaded the recommended version of forge 1.16.5 but it still crashes, i dont know how to fix this, i play on single player
yes i installed the recommended version of forge 1.16.5
i tried another patch didnt work, i use curse forge to play it
i submitted this issue yesterday as well but it was closed because the person who was helping me thought i didnt have the recommended forge version

**Comment by PlatinumOx** [comment]
if anyone knows how to fix this issue please let me know

**Comment by PlatinumOx** [comment]
and if i need another forge version how do i change it, what version do i need, i want to enjoy the mod but i dont know how to fix the crash

**Comment by PlatinumOx** [comment]
i just tried playing the 1.18.2 version using forge 40.1.0 and it says the mod has failed to load

**Comment by PlatinumOx** [comment]
i appologize but im new to this kind of stuff, im trying to figure things out, every time i try to fix it crashes or doesnt load, m trying to get help not annoy people :(

**Comment by Yesssssman** [comment]
Check the recommended forge version and download it. That's all

**Comment by PlatinumOx** [comment]
> Check the recommended forge version and download it. That's all

i did but it still crashes, i just tried to insert the mod into the folder instead of using curse forge but it still crashed, can you tell me a version that is recommended? i use 36.2.34 because it said its recommended but still didnt work

**Comment by Yesssssman** [comment]
Recommended forge version for the latest is 36.2.39

**Comment by PlatinumOx** [comment]
> Recommended forge version for the latest is 36.2.39

ill try using it give me a moment

**Comment by PlatinumOx** [comment]
it works! now i dont crash after 1 attack, thank bro, if i have any other problems(which hopefully doesnt happen lol) ill post it here, hopefully that wont annoy you, thanks again!

**Comment by PlatinumOx** [comment]
with here i mean the support page not this page lol
