### ISSUE TITLE
[Bug|Crash]: Minecolonies house schematic crash

### ISSUE THREAD

**Issue by lcollazo57** [Yesssssman/epicfightmod#1198]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Mine Colonies

### Minecraft Version

1.16.5

### What happened?

Client crash when placing down house schematic in Mine Colonies. Seems to not like rendering something inside the schematic, possibly the vanilla armor stand? Crash report is attached. Minecraft version 1.16.5, Forge version 36.2.39, Epic fight version 1.6.6.2

[crash-2022-09-19_09.12.25-client.txt](https://github.com/Yesssssman/epicfightmod/files/9610808/crash-2022-09-19_09.12.25-client.txt)

**Comment by Yesssssman** [comment]
This issue had already been fixed in 1.18.2 version by Minecolonies team but I don't have no idea if they still support 1.16.5.

**Comment by MetalKnight56** [comment]
1.16.5 is no longer supported by minecolonies, and this issue can't be fixed on our end
