### ISSUE TITLE
[Bug|Crash]: Shield in the wrong position with Silent Gear

### ISSUE THREAD

**Issue by SsjGabe360** [Yesssssman/epicfightmod#1199]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/silent-gear

### Minecraft Version

1.16.5

### What happened?

The shields in Silent Gear would be in a wrong position above the offhand making the shield look like it's floating above the offhand

**Comment by MetalKnight56** [comment]
You can fix this issue by importing the model in blockbench and fixing the pivot point, if you want, take the https://www.curseforge.com/minecraft/texture-packs/spartan-shields-fix-for-epic-fight as an example resourcepack
