### ISSUE TITLE
[Bug]: infused crystal sword's on-hit explosion doesn't work

### ISSUE THREAD

**Issue by Lindry** [Yesssssman/epicfightmod#1200]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/astral-sorcery

### Minecraft Version

1.16.5

### What happened?

when on battle mode, the chaining lightning bolts from the lightning arc perk added by astral sorcery works properly

but the on-hit explosion from the infused crystal sword (also from astral sorcery) just don't work

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
