### ISSUE TITLE
[Bug|: Sophisticated Backpacks

### ISSUE THREAD

**Issue by INooBTooMuch** [Yesssssman/epicfightmod#1202]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

[Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)

### Minecraft Version

1.18.2

### What happened?

Endermen that spawn with the backpack from [Sophisticated Backpacks](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks) , the backpack is not in the correct place.

![2022-09-24_16 25 23](https://user-images.githubusercontent.com/107572028/192100607-c28058ea-11f3-4e77-a88e-8135a040eeb7.png)
![2022-09-24_16 25 29](https://user-images.githubusercontent.com/107572028/192100633-e1408e45-e743-4423-8436-ca98544759e1.png)
![2022-09-24_16 25 41](https://user-images.githubusercontent.com/107572028/192100646-5c6925db-622f-4f7d-8a4b-5e414e225881.png)

**Comment by MetalKnight56** [comment]
Bruh why do they spawn with a backpack

**Comment by INooBTooMuch** [comment]
All mobs have a possibility to spawn with one, and they play jukebox music.

**Comment by MetalKnight56** [comment]
> All mobs have a possibility to spawn with one, and they play jukebox music.

Yeah tbh its not usual for a mod like an enderman to spawn with a backpack, if you can try disabling mob spawns with backpacks

**Comment by INooBTooMuch** [comment]
I mean I turned it off for endermen, but it was nice because they don't drop it always and they get buffed when they have one since it has loot from the mob's dimension/structure. If the model is able to get fixed that would be good.
