### ISSUE TITLE
[Bug|Enhancement]: Budschie's Morph Mod- entities don't have animations, and instead are just shown like the models are

### ISSUE THREAD

**Issue by Globalfirestorm10** [Yesssssman/epicfightmod#1203]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/budschies-morph-mod

### Minecraft Version

1.18.2

### What happened?

most entities with epicfight don't show animations when morphed into (i.e, the ender dragon is displayed how it would be when you view the model).

**Comment by MetalKnight56** [comment]
Please explain what you mean by, are just shown as the models are...

**Comment by Globalfirestorm10** [comment]
![image](https://user-images.githubusercontent.com/102924027/194890801-87e31b87-ecd7-46cb-9995-dd9c578e143d.png)

**Comment by Globalfirestorm10** [comment]
I will try to upload the video, but I'm facing difficulties because of file sharing limits

**Comment by Globalfirestorm10** [comment]
basically, the mobs have zero animations, they just stay in one position (similar to the skeleton in the photo). this happens with epic fight's fight mode and without as well

**Comment by Globalfirestorm10** [comment]
so, is this issue just abandoned?

**Comment by MetalKnight56** [comment]
> so, is this issue just abandoned?

No, i need footage to see whats happening, and also the mod list, forge version and epic fight version. If you have issues with file limit, try uploading it to youtube then sharing the linkn here

**Comment by Globalfirestorm10** [comment]
Hi there, would it be possible for me to dm you with the clip on discord? I cannot, no matter what, seem to upload the clip here

**Comment by MetalKnight56** [comment]
> Hi there, would it be possible for me to dm you with the clip on discord? I cannot, no matter what, seem to upload the clip here

YouTube then put the link here

**Comment by Globalfirestorm10** [comment]
> > Hi there, would it be possible for me to dm you with the clip on discord? I cannot, no matter what, seem to upload the clip here
> 
> 
> 
> YouTube then put the link here
> 
> 

I cannot do this due to reasons i'd like to keep private
