### ISSUE TITLE
[Bug]: Incompatibility between Epic Fight and Better Third Person

### ISSUE THREAD

**Issue by Mecnavio** [Yesssssman/epicfightmod#1204]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Better Third Person

### Minecraft Version

1.16.5

### What happened?

When both Epic Fight Mod and Better Third Person was both launched, the camra in third person can't be moved horizontally

Forge 36.2.39
EpicFight-16.6.2.jar
BetterThirdPerson-Forge-1.16.4-1.7.2.jar

**Comment by MetalKnight56** [comment]
We are ware of this issue, better third person mod is closed source, if you want us to have compatbility ask them to share their code so we can see what is even causing the issue.
