### ISSUE TITLE
[Enhancement]: First person view like 1.16.5 in 1.18.2?

### ISSUE THREAD

**Issue by Pfr19** [Yesssssman/epicfightmod#1205]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

I only want yo know how i can hace the vanilla animation in first person but allí the animations ON, like the versión 1.16.5, no only dessactivate the animation when i' m in minning mode, it's no immersive. Simeone know how i can do this in the 1.18 .2 versión?

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
