### ISSUE TITLE
[Bug|Crash]: The offhand_max_strikes attribute is not asigned to modded mobs that are "patched" with datapacks, causing the game to crash if one hits you with it's off-hand

### ISSUE THREAD

**Issue by Woodgoldtwo** [Yesssssman/epicfightmod#1206]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

The attribute "epicfight:offhand_max_strikes" is not automaticly asigned to modded mobs that have been patched by datapacks, causing the game to crash when the mob attacks another entity with it's off-hand (without a weapon as using one would give the mob the "offhand_max_strikes" attribute of that weapon)

**Comment by Woodgoldtwo** [comment]
This bug has made the development of my EFM player mobs compatibility datapack an absolute nightmare so i hope it gets fixed soon

**Comment by Yesssssman** [comment]
Did you use the latest version? This issue should never happen because I made an attribute supplier always returning epicfight attributes even tho they were not registered. 

https://github.com/Yesssssman/epicfightmod/blob/1.18.2/src/main/java/yesman/epicfight/world/entity/ai/attribute/EpicFightAttributeSupplier.java

**Comment by Woodgoldtwo** [comment]
I am using the latest version of both epic fight and forge on 1.18.2

**Comment by Woodgoldtwo** [comment]
[crash-2022-09-22_18.48.34-server.txt](https://github.com/Yesssssman/epicfightmod/files/9741303/crash-2022-09-22_18.48.34-server.txt)

**Comment by Woodgoldtwo** [comment]
This is the latest crashlog for it that i could find

**Comment by Woodgoldtwo** [comment]
If you want to reproduce the issue then download the Player Mobs mod and my EpicPlayerMobs datapack (and of course Epic Fight), start up minecraft with these mods installed, create a world, add the datapack, summon a player mob and wait for it to damage you using it's off-hand

**Comment by Woodgoldtwo** [comment]
[crash-2022-10-09_12.42.06-server.txt](https://github.com/Yesssssman/epicfightmod/files/9741359/crash-2022-10-09_12.42.06-server.txt)
Here is the **actual** crashlog

**Comment by Woodgoldtwo** [comment]
Is this still active?

**Comment by Woodgoldtwo** [comment]
Because it's still unresolved

**Comment by Woodgoldtwo** [comment]
The issue isn't closed nor has the bug been fixed, and not a single person is acknowledging it's existence

>:(

**Comment by MetalKnight56** [comment]
> This issue isn't closed nor has the bug been fixed, and not a single person is acknowledging it's existence
> 
> **_great_**

We are working on it, but its not considered main priority since it seems to be only happening on 1.16.5, i myself couldn't replicate the issue on 1.18.2. We'll let you know when we solve this issue don't worry

**Comment by Woodgoldtwo** [comment]
It does happen on 1.18.2 as well

**Comment by MetalKnight56** [comment]
> It does happen on 1.18.2 as well

Can you attach your datapack with the offhand max strike issue?

**Comment by Yesssssman** [comment]
It's gonna be fixed in the next update

**Comment by 9ghtX** [comment]
Is that fixed? On 1.18.2? I have just zombie presets in patched entities, but my server crashes cause of this property

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
