### ISSUE TITLE
[Bug] Ender dragon behaviour seems broken, spinning issue

### ISSUE THREAD

**Issue by bdubsub** [Yesssssman/epicfightmod#1207]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

When fighting the Ender Dragon in survival mode the battle starts off okay without any issues at first however once the dragon does it's healing ability and gets full health the dragon will fly away and start spinning in an area while it's in place. I did use Optifine at first and immediately once I hit it the dragon begun to spin out of control in one area. However after upon learning Optifine is not the most compatible mod I delete it and it's config and that's when the fight lasted longer than before but like mentioned earlier in this message the dragon begun to spin and I was able to easily defeat it since it was stuck in place just spinning. To be clear this is without ANY other mods, including Optifine, this is Epic Fight mod by itself in singleplayer whilst fighting the dragon in survival. 

![2022-09-28_15 43 36_2](https://user-images.githubusercontent.com/114626830/192906752-b0f06592-d04d-49d4-984f-6092ce34469f.png)

**Comment by MetalKnight56** [comment]
Could you please use the latest version on a fresh instalation of minecraft just to make sure optifine didn't make some kind of irreversible behaviour changes to the ender dragon?

**Comment by MetalKnight56** [comment]
Denied issue, 1.16.5 no longer will be supported.
