### ISSUE TITLE
[Bug] Gamerule keepSkills not applying its effect

### ISSUE THREAD

**Issue by Somepersonontheinternet1** [Yesssssman/epicfightmod#1210]
### Have you checked if a similar issue is already reported by someone else?

- [x] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Hello,

I am currently trying to set up a server with your mod (version: 1.16.5 forge version: 1.16.5-forge-36.2.39) and for some reason /keepskills doesnt work even after setting it to true multiple times(even after trying to use a command block on repeat).The game just continues as if /keepskills was set to false wich on a server where pvp is obviously happening often is unfortunate

**Comment by Somepersonontheinternet1** [comment]
> I can't figure out the "some reason" because I'm not in your situation. Please specify the reason causing this issue.

I wrote some reason because i dont know for what reason it doesnt work

**Comment by Yesssssman** [comment]
I can't help you if you don't have any information on what is causing the issue in your case.

**Comment by MetalKnight56** [comment]
Use the config option instead of the gamerule, for now gamerule seems to be deprecated

**Comment by MetalKnight56** [comment]
@Yesssssman I've relabeled this issue as other users have reported some malfunctioning when using the gamerule

**Comment by Yesssssman** [comment]
No, gamerules are not deprecated at all and the config options are just the default value of gamerules when you create the world. Please check if it's fixed when you remove all other mods and if so, find which mod is causing this issue.

**Comment by mathi0101** [comment]
> No, gamerules are not deprecated at all and the config options are just the default value of gamerules when you create the world. Please check if it's fixed when you remove all other mods and if so, find which mod is causing this issue.

I have installed epic fight, vampirism and tombstone and the same is happening to me and my friends.
I think it has to be one of these two mods

**Comment by mathi0101** [comment]
INFO • minecraft mohist-1.16.5-1078-server.jar : minecraft (1.16.5) - 1
24.10 00:04:34 [Server] INFO • mods_folder mcw-bridges-2.0.3-mc1.16.5.jar : mcwbridges (2.0.3) - 1
24.10 00:04:34 [Server] INFO • mods_folder voicechat-forge-1.16.5-2.3.10.jar : voicechat (1.16.5-2.3.10) - 1
24.10 00:04:34 [Server] INFO • mods_folder mowziesmobs-1.5.16.jar : mowziesmobs (1.5.16) - 1
24.10 00:04:34 [Server] INFO • mods_folder AmbientSounds_v3.1.11_mc1.16.5.jar : ambientsounds (3.0.3) - 1
24.10 00:04:34 [Server] INFO • mods_folder spiders-2.0-1.16.4-1.0.4.jar : spiderstpo (1.0.4) - 1
24.10 00:04:34 [Server] INFO • mods_folder dungeons_plus-1.16.5-1.1.5.jar : dungeons_plus (1.1.5) - 1
24.10 00:04:34 [Server] INFO • mods_folder CreativeCore_v2.2.1_mc1.16.5.jar : creativecore (2.0.0) - 1
24.10 00:04:34 [Server] INFO • mods_folder jei-1.16.5-7.7.1.152.jar : jei (7.7.1.152) - 1
24.10 00:04:34 [Server] INFO • mods_folder VisualWorkbench-v1.1.0-1.16.5.jar : visualworkbench (1.1.0) - 1
24.10 00:04:34 [Server] INFO • mods_folder Guide-API-VP-1.16.5-2.2.2.jar : guideapi-vp (2.2.2) - 1
24.10 00:04:34 [Server] INFO • mods_folder Neat+1.7-27.jar : neat (1.7-27) - 1
24.10 00:04:34 [Server] INFO • mods_folder TerraForged-1.16.5-0.2.15.jar : terraforged (0.2.15) - 1
24.10 00:04:34 [Server] INFO • mods_folder EpicFightMod-16.5.13.jar : epicfight (16.5.13) - 1
24.10 00:04:34 [Server] INFO • mods_folder Croptopia-1.16.5-FORGE-2.0.5.jar : croptopia (2.0.5) - 1
24.10 00:04:34 [Server] INFO • mods_folder WeaponThrow-1.16.4-5.7.jar : weaponthrow (1.16.4-5.7) - 1
24.10 00:04:34 [Server] INFO • mods_folder camera-1.16.5-1.0.14.jar : camera (1.16.5-1.0.14) - 1
24.10 00:04:34 [Server] INFO • mods_folder journeymap-1.16.5-5.8.5p5.jar : journeymap (5.8.5p5) - 1
24.10 00:04:34 [Server] INFO • mods_folder citadel-1.8.1-1.16.5.jar : citadel (1.8.1) - 1
24.10 00:04:34 [Server] INFO • mods_folder [1.16.5]+SecurityCraft+v1.9.3.1.jar : securitycraft (v1.9.3.1) - 1
24.10 00:04:34 [Server] INFO • mods_folder TravelersBackpack-1.16.5-5.4.15.jar : travelersbackpack (5.4.15) - 1
24.10 00:04:34 [Server] INFO • mods_folder StorageDrawers-1.16.3-8.5.2.jar : storagedrawers (8.5.2) - 1
24.10 00:04:34 [Server] INFO • mods_folder tombstone-6.8.0-1.16.5.jar : tombstone (6.8.0) - 1
24.10 00:04:34 [Server] INFO • mods_folder OPF-1.16.x-v2.jar : opf (0) - 1
24.10 00:04:34 [Server] INFO • mods_folder mcw-doors-1.0.6-mc1.16.5.jar : mcwdoors (1.0.6) - 1
24.10 00:04:34 [Server] INFO • mods_folder cfm-7.0.0pre22-1.16.3.jar : cfm (7.0.0-pre22) - 1
24.10 00:04:34 [Server] INFO • mods_folder Vampirism-1.16.5-1.8.11.jar : vampirism (1.8.11) - 2
24.10 00:04:34 [Server] INFO • mods_folder Werewolves-1.16.5-1.8-0.6.5.jar : werewolves (0.6.5) - 1
24.10 00:04:34 [Server] INFO • mods_folder iceandfire-2.1.11-1.16.5.jar : iceandfire (2.1.11-1.16.5) - 1

**Comment by MetalKnight56** [comment]
> This is my entire list of mods running on mohist 1.16.5:
> 
> INFO • minecraft mohist-1.16.5-1078-server.jar : minecraft (1.16.5) - 1 24.10 00:04:34 [Server] INFO • mods_folder mcw-bridges-2.0.3-mc1.16.5.jar : mcwbridges (2.0.3) - 1 24.10 00:04:34 [Server] INFO • mods_folder voicechat-forge-1.16.5-2.3.10.jar : voicechat (1.16.5-2.3.10) - 1 24.10 00:04:34 [Server] INFO • mods_folder mowziesmobs-1.5.16.jar : mowziesmobs (1.5.16) - 1 24.10 00:04:34 [Server] INFO • mods_folder AmbientSounds_v3.1.11_mc1.16.5.jar : ambientsounds (3.0.3) - 1 24.10 00:04:34 [Server] INFO • mods_folder spiders-2.0-1.16.4-1.0.4.jar : spiderstpo (1.0.4) - 1 24.10 00:04:34 [Server] INFO • mods_folder dungeons_plus-1.16.5-1.1.5.jar : dungeons_plus (1.1.5) - 1 24.10 00:04:34 [Server] INFO • mods_folder CreativeCore_v2.2.1_mc1.16.5.jar : creativecore (2.0.0) - 1 24.10 00:04:34 [Server] INFO • mods_folder jei-1.16.5-7.7.1.152.jar : jei (7.7.1.152) - 1 24.10 00:04:34 [Server] INFO • mods_folder VisualWorkbench-v1.1.0-1.16.5.jar : visualworkbench (1.1.0) - 1 24.10 00:04:34 [Server] INFO • mods_folder Guide-API-VP-1.16.5-2.2.2.jar : guideapi-vp (2.2.2) - 1 24.10 00:04:34 [Server] INFO • mods_folder Neat+1.7-27.jar : neat (1.7-27) - 1 24.10 00:04:34 [Server] INFO • mods_folder TerraForged-1.16.5-0.2.15.jar : terraforged (0.2.15) - 1 24.10 00:04:34 [Server] INFO • mods_folder EpicFightMod-16.5.13.jar : epicfight (16.5.13) - 1 24.10 00:04:34 [Server] INFO • mods_folder Croptopia-1.16.5-FORGE-2.0.5.jar : croptopia (2.0.5) - 1 24.10 00:04:34 [Server] INFO • mods_folder WeaponThrow-1.16.4-5.7.jar : weaponthrow (1.16.4-5.7) - 1 24.10 00:04:34 [Server] INFO • mods_folder camera-1.16.5-1.0.14.jar : camera (1.16.5-1.0.14) - 1 24.10 00:04:34 [Server] INFO • mods_folder journeymap-1.16.5-5.8.5p5.jar : journeymap (5.8.5p5) - 1 24.10 00:04:34 [Server] INFO • mods_folder citadel-1.8.1-1.16.5.jar : citadel (1.8.1) - 1 24.10 00:04:34 [Server] INFO • mods_folder [1.16.5]+SecurityCraft+v1.9.3.1.jar : securitycraft (v1.9.3.1) - 1 24.10 00:04:34 [Server] INFO • mods_folder TravelersBackpack-1.16.5-5.4.15.jar : travelersbackpack (5.4.15) - 1 24.10 00:04:34 [Server] INFO • mods_folder StorageDrawers-1.16.3-8.5.2.jar : storagedrawers (8.5.2) - 1 24.10 00:04:34 [Server] INFO • mods_folder tombstone-6.8.0-1.16.5.jar : tombstone (6.8.0) - 1 24.10 00:04:34 [Server] INFO • mods_folder OPF-1.16.x-v2.jar : opf (0) - 1 24.10 00:04:34 [Server] INFO • mods_folder mcw-doors-1.0.6-mc1.16.5.jar : mcwdoors (1.0.6) - 1 24.10 00:04:34 [Server] INFO • mods_folder cfm-7.0.0pre22-1.16.3.jar : cfm (7.0.0-pre22) - 1 24.10 00:04:34 [Server] INFO • mods_folder Vampirism-1.16.5-1.8.11.jar : vampirism (1.8.11) - 2 24.10 00:04:34 [Server] INFO • mods_folder Werewolves-1.16.5-1.8-0.6.5.jar : werewolves (0.6.5) - 1 24.10 00:04:34 [Server] INFO • mods_folder iceandfire-2.1.11-1.16.5.jar : iceandfire (2.1.11-1.16.5) - 1

Mohist is a custom server loader, although we recommend the usage of mohist-magma we can't 100% be sure it'll work, so if i were you i would either change server loader or just use forge's default server jar.
