### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Shunpo1** [Yesssssman/epicfightmod#1211]
### Have you checked if a similar issue is already reported by someone else?

- [x] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

The game crashes when attacking mobs
[crash-2022-10-03_09.36.00-server.txt](https://github.com/Yesssssman/epicfightmod/files/9696544/crash-2022-10-03_09.36.00-server.txt)

**Comment by Yesssssman** [comment]
Update forge
