### ISSUE TITLE
[Bug|compatible with optifine]: 

### ISSUE THREAD

**Issue by EVGENmr** [Yesssssman/epicfightmod#1212]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Glow texture does not work on armor and cit does not work when the armor from optifine is animated. Is it possible to implement it at all? and on 1.12.2?

**Comment by MetalKnight56** [comment]
Optifine is not open source which means, we are unable to fix any issue, not only that but it doesn't use forge api it only has some things that make it poorly run on forge. If you want shaders use oculus/rubidium and maybe in the future we'll be able to support shader mods. As of now we won't try to patch or do anything with this.
