### ISSUE TITLE
[Bug|Crash]: Crash server when weapon or armor breaks with Epic Fight Mod and Bonfire Mod.

### ISSUE THREAD

**Issue by 5stigma** [Yesssssman/epicfightmod#1213]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Bonfire Mod by Wehavecookies56

### Minecraft Version

1.18.2

### What happened?

Crash server when weapon or armor breaks with Epic Fight Mod and Bonfire Mod. sometimes it just kicks you out of the server.

Sometimes the server freezes and has to be restarted. the client does not have to be restarted.

**Comment by 5stigma** [comment]
I have already reported this to Bonfire's author

**Comment by Yesssssman** [comment]
Could you post the crash repo?

**Comment by 5stigma** [comment]
it does not give me a crash log, since it freezes and does not allow me to enter commands or it just kicks me out of the server. But, I noticed that it happens when the entity is on fire (for what it's worth (I don't know English (Goggle T.))).

**Comment by Yesssssman** [comment]
Could you provide me the last log under /.minecraft/logs?

**Comment by 5stigma** [comment]
The problem is already solved by Bonfire's Author.
