### ISSUE TITLE
[Bug|Crash]: Reopen: End Dragon Still Crashing When Attacking 16.5

### ISSUE THREAD

**Issue by freddwardo** [Yesssssman/epicfightmod#1214]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

I reported this issue https://github.com/Yesssssman/epicfightmod/issues/1208. I updated the mod and The End Dragon is still crashing once it registers a player and tries to attack, and now there are weird texture issues. I started disabling a bunch of mods but at that point it makes more sense to disable epic fight which would really hurt a lot of players in my modpack. If there's an easy fix for this I would really appreciate it! Really love this mod and everything you do for us players. Here's the new crash log 

[crash-2022-10-14_09.10.37-server.txt](https://github.com/Yesssssman/epicfightmod/files/9787180/crash-2022-10-14_09.10.37-server.txt)

**Comment by Yesssssman** [comment]
Thanks for reporting. I'll check if there're other potential problems.

**Comment by freddwardo** [comment]
Thank you so much! I absolutely love this mod, thank you for being so
active and supportive!
