### ISSUE TITLE
[Bug|Crash]: Attacking mob in Life In the Village 2 crashes game

### ISSUE THREAD

**Issue by Safierninja** [Yesssssman/epicfightmod#1217]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

So I am currently playing a Life In The Village 2 modpack and I decided that I wanted to use the epic fight mod. I added it and everything was going well until I hit a mob as soon as that happened my game crashed. I was a bit confused and I hit some mobs a few more times and the same thing over and over again, so I went to Discord for the modpack and they said that It is a ticking issue with the particles that show up when you hit someone, and it might be conflicting with other mods but currently we don't know what mods.
[crash-2022-10-16_21.30.00-server.txt](https://github.com/Yesssssman/epicfightmod/files/9796609/crash-2022-10-16_21.30.00-server.txt)
[crash-2022-10-16_21.53.43-server.txt](https://github.com/Yesssssman/epicfightmod/files/9796610/crash-2022-10-16_21.53.43-server.txt)
[crash-2022-10-16_21.38.42-server.txt](https://github.com/Yesssssman/epicfightmod/files/9796596/crash-2022-10-16_21.38.42-server.txt)
https://github.com/Yesssssman/epicfightmod/files/9796594/crash-2022-10-16_21.44.57-server.txt)

**Comment by Yesssssman** [comment]
We don't support for the old forge version. Please update your forge.
