### ISSUE TITLE
[Bug|Crash]: 1.16.5 16.6.4

### ISSUE THREAD

**Issue by TelurXS** [Yesssssman/epicfightmod#1218]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Weird crash when attacking an entity
[crash-2022-10-17_20.46.55-server.txt](https://github.com/Yesssssman/epicfightmod/files/9803253/crash-2022-10-17_20.46.55-server.txt)

**Comment by SlendyMcTendies** [comment]
I have the same or very similar problem

[crash-2022-10-20_19.42.37-server.txt](https://github.com/Yesssssman/epicfightmod/files/9834607/crash-2022-10-20_19.42.37-server.txt)

**Comment by TelurXS** [comment]
> I have the same or very similar problem
> 
> [crash-2022-10-20_19.42.37-server.txt](https://github.com/Yesssssman/epicfightmod/files/9834607/crash-2022-10-20_19.42.37-server.txt)

If you are using CurseForge, update your forge to the latest version. It helped me.
![image](https://user-images.githubusercontent.com/107636729/197187338-f0a33d5d-261f-4bc1-ac78-8507dcd52f6b.png)
