### ISSUE TITLE
VariedCommodities helmets issue

### ISSUE THREAD

**Issue by Tennik** [Yesssssman/epicfightmod#122]
Hello there again! Found some problems with rendering of helmets from VariedCommodities Mod (Custom NPC`s addon) in third person.
Helmets with broken render are:
- Full Iron Helmet;
![Full Iron Helmet](https://user-images.githubusercontent.com/12845200/112900762-9025a580-90ec-11eb-8a5b-0244a79a642f.png)
![Full Iron Helmet(1)](https://user-images.githubusercontent.com/12845200/112900772-93209600-90ec-11eb-9832-5a43752bd2b6.png)
![Full Iron Helmet(2)](https://user-images.githubusercontent.com/12845200/112900773-93b92c80-90ec-11eb-88eb-0450926f4143.png)
- Full Gold Helmet;
- Full Diamond Helmet;
![Full Diamond Helmet](https://user-images.githubusercontent.com/12845200/112900666-771cf480-90ec-11eb-9cd5-ba0fafc8af67.png)
![Full Diamond Helmet(1)](https://user-images.githubusercontent.com/12845200/112900727-869c3d80-90ec-11eb-8392-3d7e472604ce.png)
![Full Diamond Helmet(2)](https://user-images.githubusercontent.com/12845200/112900748-8a2fc480-90ec-11eb-949e-0a1f50033752.png)
- Full Emerald Helmet;
- Knight's Helmet;
- X407 Prototype Helmet;
![X407 Prototype Helmet](https://user-images.githubusercontent.com/12845200/112900791-9ae03a80-90ec-11eb-8475-3b1da4e4797e.png)
![X407 Prototype Helmet(1)](https://user-images.githubusercontent.com/12845200/112900796-9c116780-90ec-11eb-9bf2-f1e9e3673ac4.png)
![X407 Prototype Helmet(2)](https://user-images.githubusercontent.com/12845200/112900797-9c116780-90ec-11eb-8846-b03b275be13c.png)
- Demonic Helmet
The same issue is with all types of skirts
![Skirt](https://user-images.githubusercontent.com/12845200/112900822-a5023900-90ec-11eb-9e28-5644fbde84cd.png)
![Skirt(1)](https://user-images.githubusercontent.com/12845200/112900827-a6336600-90ec-11eb-93e0-6aa049a236e4.png)

I use the latest version of mod for 1.12.2

**Comment by Yesssssman** [comment]
Automatic model generation is not perfect. Try this way and if it doesn't work, I can't support it anymore.
Turn on the "filter animation" option in mod configuration GUI, then, equip the armor in none-battle mod(to show the armor in the vanilla model.) then, go to the battle mod. This solved the problem with custom armors from botania mod, but they don't work with the dungeons gear mod.

**Comment by Tennik** [comment]
Yes, that solve the problem, but model without your animation looks much worse, so I prefer to not use these items
