### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by AlienTaco** [Yesssssman/epicfightmod#1222]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

EpicFightMod

### Minecraft Version

1.16.5

### What happened?

Game crashed when I hit a mob.
The mod was working completely fine until I hit a mob, causing the game to then immidetly crash, then this message appeared in the launcher.
Error: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;)Lnet/minecraft/entity/EntitySize;

**Comment by Woodgoldtwo** [comment]
Update forge to the recommended version: 36.2.39

**Comment by MetalKnight56** [comment]
Closed the issue as it
