### ISSUE TITLE
Enderman Eyes in Latest Version Above Head?

### ISSUE THREAD

**Issue by SaltyOnigiri** [Yesssssman/epicfightmod#1224]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

So I kept getting a weird visual glitch we’re enderman eyes float above the head. I removed every mod but the epic fight mod so I know it’s not a compatibility issue.

![image](https://user-images.githubusercontent.com/63155601/200098557-a1dd242b-fbcb-4302-b904-60e040bc9f8b.jpg)

**Comment by MetalKnight56** [comment]
Seems to be an issue with shaders

**Comment by DitaSalander** [comment]
actually, I tried removing shader mods like oculus and the glitch is still there...
