### ISSUE TITLE
[Bug|Crash]: Server crashes uppon damage and player gets kicked out of the server when using epic fight mode and doing damage

### ISSUE THREAD

**Issue by BestInfinity** [Yesssssman/epicfightmod#1225]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/download/4029362

### Minecraft Version

1.16.5

### What happened?

https://mclo.gs/niQptkF  when someone deals damage they get kicked out of the server or when they take damage the server crashes

**Comment by Woodgoldtwo** [comment]
"Are you using the latest Epic Fight and recommended Forge version?"

-"I checked I'm using latest Epic Fight and recommended Forge version."


_**bruh**_

**Comment by MetalKnight56** [comment]
> Update the forge version to 36.2.39

@Woodgoldtwo no need to answer these in github they'll be labeled as violated support policy and will be blocked from sending any further issue reports

**Comment by MetalKnight56** [comment]
Closed this issue as it violates the terms and support policy.
