### ISSUE TITLE
[Bug|Crash]: ender dragon causes crash when spawned in the overworld via commands

### ISSUE THREAD

**Issue by oliverrook** [Yesssssman/epicfightmod#1227]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Attempted to spawn the ender dragon in a creative flat world on the tunneler's dream preset in the overworld, using commands in the chat.
Upon spawning the game crashed instantly and the world can no longer be loaded into without crashing immediately upon exiting pause.

From the log file:

Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.dimension.end.EndDragonFight.m_64098_()" because the return value of "net.minecraft.world.entity.boss.enderdragon.EnderDragon.m_31158_()" is null
	at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.DragonFlyingPhase.findNewTarget(DragonFlyingPhase.java:60) ~[EpicFight-18.3.7.jar%23201!/:18.3.7] {re:classloading}
	at yesman.epicfight.world.capabilities.entitypatch.boss.enderdragon.DragonFlyingPhase.m_6989_(DragonFlyingPhase.java:35) ~[EpicFight-18.3.7.jar%23201!/:18.3.7] {re:classloading}
	at net.minecraft.world.entity.boss.enderdragon.EnderDragon.m_8107_(EnderDragon.java:227) ~[client-1.18.2-20220404.173914-srg.jar%23462!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2253)

**Comment by Woodgoldtwo** [comment]
this is a common issue

**Comment by Woodgoldtwo** [comment]
epicfight revamps the enderdragon which causes the A.I. to break when spawned outside of the main island

**Comment by MetalKnight56** [comment]
Go on the end in survival

**Comment by oliverrook** [comment]
Wasn't in survival, I was on a creative world. Was just testing stuff.

**Comment by oliverrook** [comment]
> epicfight revamps the enderdragon which causes the A.I. to break when spawned outside of the main island

Alright. Well I didn't see any known issues about it so I couldn't have known could I?

**Comment by MetalKnight56** [comment]
> Wasn't in survival, I was on a creative world. Was just testing stuff.

i know, thats whyb i'm telling you, if you want to go in the end, hop on the portal on survival mode

**Comment by Woodgoldtwo** [comment]
> > epicfight revamps the enderdragon which causes the A.I. to break when spawned outside of the main island
> 
> Alright. Well I didn't see any known issues about it so I couldn't have known could I?

Well now you know and can avoid it in the future

**Comment by oliverrook** [comment]
It's 1.18.2 not 1.16.5

**Comment by MetalKnight56** [comment]
Closed the issue, as it's a known issue that should be avoided by the user

**Comment by MetalKnight56** [comment]
> It's 1.18.2 not 1.16.5

my bad

**Comment by Woodgoldtwo** [comment]
Summary:

_Don't encounter the ender dragon in any other way than **entering the end in survival**_

**Comment by oliverrook** [comment]
I will say, not knowing how the code works but having a general understanding of programming, it might be possible to trick the game into thinking a dimension is the end when spawning in the ender dragon by having it so the ender dragon's ai references the dimension it's in via an reference variable rather than the one it's actually supposed to be in.

**Comment by Woodgoldtwo** [comment]
> I will say, not knowing how the code works but having a general understanding of programming, it might be possible to trick the game into thinking a dimension is the end when spawning in the ender dragon by having it so the ender dragon's ai references the dimension it's in via an reference variable rather than the one it's actually supposed to be in.

The main end island and it's structures are integrated into th ender dragon's A.I. so just making it think that it is in the end simply won't work
