### ISSUE TITLE
Crash: Ticking player

### ISSUE THREAD

**Issue by jojofire12** [Yesssssman/epicfightmod#1228]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

The game crashes upon hitting entities
[crash-2022-11-10_16.54.35-server.txt](https://github.com/Yesssssman/epicfightmod/files/9984932/crash-2022-11-10_16.54.35-server.txt)

**Comment by MetalKnight56** [comment]
Closed this issue as it violates the terms and support policy
