### ISSUE TITLE
[Bug|Crash]:  animations wont work

### ISSUE THREAD

**Issue by Jaquise23124412** [Yesssssman/epicfightmod#1231]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.16.5

### What happened?

Animations wont work

**Comment by tacoman11** [comment]
same

**Comment by MetalKnight56** [comment]
> ### Have you checked if a similar issue is already reported by someone else?
> * [x]  I checked there are no similar issues have been reported.
> 
> ### Have you read the support policy?
> * [x]  I read it and I accept the policy.
> 
> ### Are you using the latest Epic Fight and recommended Forge version?
> * [x]  I checked I'm using latest Epic Fight and recommended Forge version.
> 
> ### Is this issue related to mod incompatibility?
> * [x]  This is a mod compatibility issue and I'm aware of the problem.
> 
> ### The mod
> Epic Fight
> 
> ### Minecraft Version
> 1.16.5
> 
> ### What happened?
> Animations wont work

Ok, so you want me to fix you issue, yet you don't provide any details in what is happening, like fr if you are going to come here to report random stuff like animation wont work, don't even take you time to do that, just don't even install the mod, this is not of any help, and i'm just going to close this issue cuz policy is violated
