### ISSUE TITLE
[Bug|Crash]: i'm having problems with the version (16.6.4.jar) even without other mod or with other mod.

### ISSUE THREAD

**Issue by Jubilenios** [Yesssssman/epicfightmod#1233]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files

### Minecraft Version

1.16.5

### What happened?

The red triangle on top of the mob health bar is left with a black square. And also the motion animation only activates when I press the "r" but soon after when I hit any mob the game closes and says that i try compatibility problem with "other mods" even also just while it's in the folder "mods".

**Comment by MetalKnight56** [comment]
Closed this issue as user violated the support policy
