### ISSUE TITLE
[Bug|Crash]: Crash while fighting skeleton

### ISSUE THREAD

**Issue by Dking44** [Yesssssman/epicfightmod#1234]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

### Minecraft Version

1.16.5

### What happened?

Game crashed when fighting a skeleton
[crash-2022-11-17_03.30.08-client.txt](https://github.com/Yesssssman/epicfightmod/files/10029459/crash-2022-11-17_03.30.08-client.txt)

**Comment by mrdragonblack** [comment]
helloDking44 the problem is you not update the mod to latest version  or update your forge

**Comment by MetalKnight56** [comment]
Closed the issue as this violates the support policy
