### ISSUE TITLE
[Bug|Crash]: Ender Dragon crashes the game if you attempt to fight it in the overworld

### ISSUE THREAD

**Issue by mhwang668** [Yesssssman/epicfightmod#1235]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Spawning in the Ender Dragon in the overworld and trying to fight it in survival mode causes the game to just crash.
[crash-2022-11-18_21.39.30-server.txt](https://github.com/Yesssssman/epicfightmod/files/10045882/crash-2022-11-18_21.39.30-server.txt)

**Comment by MetalKnight56** [comment]
This is an intended feature to prevent issue when fighting the ender dragon and spoiling the experience
