### ISSUE TITLE
Crash upon attacking entities.

### ISSUE THREAD

**Issue by ILikeDogs34** [Yesssssman/epicfightmod#1237]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.16.5

### What happened?

Game breaking bug for the mod version, EpicFight-16.6.4.jar, on forge version 36.2.32. When dealing damage to any entity using the "attack mode" of this mod, the game will crash. I have isolated the mod and am still running into the issue. I have not checked if this issue persist in other versions of forge.
Thanks for the help!

**Comment by MetalKnight56** [comment]
Closed the issue as it violates the support policy
