### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by LordGriefington** [Yesssssman/epicfightmod#1239]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Optifine

### Minecraft Version

1.16.5

### What happened?

while holding a custom item in battle mode wich has emissive texture. the player is glowing as well.
I am using OptiFine_1.16.5_HD_U_G8
![2022-11-29_01 53 08](https://user-images.githubusercontent.com/83673600/204411865-681c40ae-eab8-439e-8c94-68603b021c04.png)
![2022-11-29_01 53 18](https://user-images.githubusercontent.com/83673600/204411870-c02dd88d-a831-4cb4-9cea-6560b4849f40.png)

**Comment by LordGriefington** [comment]
it also happens when something emissive is rendered on the player. but only while in battle mode. (means the epic fight model, I have filter_animation = true)

**Comment by MetalKnight56** [comment]
Closed the issue as its a mod incompatbility with optifine which is a closed source mod which doesn't use forge API
