### ISSUE TITLE
Issues with Custom Weapons with "KATANA"

### ISSUE THREAD

**Issue by AshesUponAshes** [Yesssssman/epicfightmod#124]
They use the Held Moves of the SWORD weapons(Only the Held Moves, Standard Attacks are fine) and are labeled as "Main-Hand Only", furthermore due to the beforementioned Issue, They can be used with Shields, when attacking with these, the game will crash

**Comment by Yesssssman** [comment]
Ok this will be fixed.

**Comment by AshesUponAshes** [comment]
ty
