### ISSUE TITLE
[Bug|Crash]: "The game crashed whilst ticking player"

### ISSUE THREAD

**Issue by Salut08** [Yesssssman/epicfightmod#1241]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight Mod

### Minecraft Version

1.16.5

### What happened?

When I type any entity with the mod "Epic Fight" my game crashes and displays this :
![Minecraft Launcher 30_11_2022 13_32_40](https://user-images.githubusercontent.com/119502195/204797854-37301287-3306-46c2-9e69-1d753da05c69.png)

**Comment by Salut08** [comment]
sorry; but how can I fix it

**Comment by MetalKnight56** [comment]
Closed this issue as user violated the support policy

**Comment by Salut08** [comment]
that is to say??
