### ISSUE TITLE
[Bug|Crash]: Crashing Upon Something Taking Damage

### ISSUE THREAD

**Issue by NeytFox** [Yesssssman/epicfightmod#1242]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

I crash when i damage anything, for no reason

**Comment by MetalKnight56** [comment]
Closing the issue as user violated the support policy
