### ISSUE TITLE
[Crash]: Crash when entering combat mode

### ISSUE THREAD

**Issue by LvsrsRedDragon** [Yesssssman/epicfightmod#1245]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

As soon as I switch to combat mode, the game crashes. All seems to indicate that Epic Fight is to blame, since the error I had was similar to a previous issue (though the cause is not the same), That being "Pose stack not empty".

[crash-2022-12-08_17.48.05-client.txt](https://github.com/Yesssssman/epicfightmod/files/10189357/crash-2022-12-08_17.48.05-client.txt)

Above is the full crash log. Thank you in advance!

**Comment by LvsrsRedDragon** [comment]
Ah, sorry. I did mark this as an 1.18.2 issue, but accidentally refreshed the page. This must have reverted some of my changes. Also, I'm using less than 120 mods, which is not a lot by today's standards. But ok, I'll try to solve the issue, and I'll get back once I did, so I can tell what mod is incompatible.

**Comment by LvsrsRedDragon** [comment]
Okay, I have re-read the log. There is no mention of an entity with that name. The only time the log mentions that is when it prints the users in the server.

**Comment by LvsrsRedDragon** [comment]
Okay, now  that I've re-read the log, there is no mention of an entity with that name.  The only time that nickname is mentioned was as a player in the server.

**Comment by MetalKnight56** [comment]
> Okay, now that I've re-read the log, there is no mention of an entity with that name. The only time that nickname is mentioned was as a player in the server.
> 
> EDIT: I just realized, the only time it actually crashes is in third person while in battle mode. Doing it in first person or being in third person in mining mode does not crash the game.

Did you remove all mods before testing this? I've never seen epic fight crash on its own
