### ISSUE TITLE
[Bug]: Skin texture bug

### ISSUE THREAD

**Issue by AlokenMaloken** [Yesssssman/epicfightmod#1247]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

I added custom armor from the Conquest. It works fine in both mining and combat modes. But when switching to combat, the skin "breaks" regardless of whether I'm wearing this armor or not.

![image](https://user-images.githubusercontent.com/120446620/207246083-fc48bb50-1a95-450e-89e5-c67a422c4ecd.png)
![image](https://user-images.githubusercontent.com/120446620/207246160-fac2e7f1-50af-4fe5-a8d6-eb9fbe991cab.png)

**Comment by MetalKnight56** [comment]
Ok, so it seems that you've not marked this as a mod incompatbility, yet this is 100% some kind of incompatbility issue. Please correct your issue report first and make sure you are using the recommended configurations to allow the mod to run properly
