### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Jynxz121** [Yesssssman/epicfightmod#1248]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.16.5

### What happened?

![image_2022-12-14_155342074](https://user-images.githubusercontent.com/120584856/207643801-dcd23d0b-d424-4348-895a-b02ecd85303c.png)

these are the mods i use everytime i switch pressing "R" and hit something it crashes my game.

**Comment by MetalKnight56** [comment]
Closed the issue as user broke the terms of the support policy
