### ISSUE TITLE
[Bug]: Hopefully a simple fix

### ISSUE THREAD

**Issue by Fall4573** [Yesssssman/epicfightmod#1249]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Heyy ik it says to make sure I'm using the most up-to-date version, but basically. I'm working with 1.12.2 and that's what's compatible with other mods I have but the issue I'm hoping is an easy fix that you can probably figure out and tell me what to do faster than doing constant trial and error.

I looked at other rpts and it's not a crash but a bug, also not something discussed I'm hoping this will help others too

basically, I'm able to go into combat mode and perform the animations, but when I actually go to attack any entity it defaults back to the regular Minecraft attack. This is a conflict I've dealt with before when installing conflicting mods like smart moving, surprisingly in some instances I've managed to accidentally make other movement mods compatible for ex: smart moving will work as long as you're not in combat mode and vice versa. Pretty cool, in exhausting efforts to recreate this I ended up just removing any mods not compatible with epic fight "the OG"

however, I feel like there's something I may be missing because even after removing them the issue above still occurs

tried deleting certain config files so they reset and about 50 other things

figured its a problem you'd found a fix for before working with @bstylia14 on the mod pack he spent 9 months on so far
full disclosure I've been working on something similar for about 5 years and only recently stumbled into just enough steady income to buy jeff Besos a hairline replacement and start really putting it all together
[latest.log](https://github.com/Yesssssman/epicfightmod/files/10244624/latest.log)
,so if money is what it takes to get a response I gotchu lol
ik this has been less active and I appreciate all you've done so far, really hoping for a response

**Comment by MetalKnight56** [comment]
1.12.2 is no longer supported
