### ISSUE TITLE
[Bug] We can't hit the end dragon

### ISSUE THREAD

**Issue by hitmanssilent** [Yesssssman/epicfightmod#125]
Do you remember when I told you a few days ago that you could not fight the end dragon with the combat mode activated? Well, it keeps happening but not for the reasons I thought at the beginning, before I thought it was because the attacks did not hit the end dragon because there was no upward angle to hit, but now I have discovered that for some reason, the end dragon It can not be hit even being a few inches from it (or even being inside the end dragon model) even having a spear or great sword, only in combat mode, when we are in normal mode we can hit the end dragon, I tried with all the weapons and tools that the mod allows, even hitting clean hand and none of them seem to have an effect on the end dragon if we are in combat mode.

By the way, I'm on 1.16.5, I don't know what will happen if we try it on 1.12.2

**Comment by Yesssssman** [comment]
I'm starting to inspect. thank you for reporting.
