### ISSUE TITLE
[Bug]: Left Hand having weapon offset issue

### ISSUE THREAD

**Issue by freddwardo** [Yesssssman/epicfightmod#1250]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Minecraft has an option to switch your main hand to left for left handed people but epic fight keeps the items in the right hand oriented slots within the animations. Is this a simple fix?
![2022-12-16_10 53 50](https://user-images.githubusercontent.com/114755659/208137781-4330182e-e3f6-4b38-9e71-ad6543ed7104.png)
![2022-12-16_10 54 15](https://user-images.githubusercontent.com/114755659/208137782-0a92bc99-10f8-44a2-be24-4d6804b89d43.png)
![2022-12-16_10 53 36](https://user-images.githubusercontent.com/114755659/208137783-7ed86794-1726-4fb8-99d1-b82500f3b059.png)
![2022-12-16_10 53 39](https://user-images.githubusercontent.com/114755659/208137784-41f2e74f-fadf-4d19-930e-fe1568e03d23.png)

**Comment by MetalKnight56** [comment]
Yeah so the only way to fix this issue would be to redo all the animations for the left hand. I've started work on it but its really tiring and takes a lot of time do redo it all
