### ISSUE TITLE
[1.18.2]: Ticking Player crash

### ISSUE THREAD

**Issue by LunafeyLazuli** [Yesssssman/epicfightmod#1251]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

So sometimes, when some of my peeps randomly join the server, they'll get a rendering crash saying that it's a "ticking player" but they can join back right after, and it's just fine.
[crash-2022-12-16_16.15.28-client.txt](https://github.com/Yesssssman/epicfightmod/files/10249532/crash-2022-12-16_16.15.28-client.txt)

**Comment by LunafeyLazuli** [comment]
I didn't check the mod incompatibility just because I'm not sure if it is conflicting with another mod or not

**Comment by MetalKnight56** [comment]
Downgrade forge and try again, if it continues tell me

**Comment by LunafeyLazuli** [comment]
Sweet I'll try it out!

**Comment by LunafeyLazuli** [comment]
Tried to go back a version (Forge 40.1.85 to 40.1.84) and it was just crashing on launch afterward, but the weird part is that since it's not a constant crash, it's random on when it happens so it will probably be a bit hard to reproduce x.x

**Comment by MetalKnight56** [comment]
> Tried to go back a version (Forge 40.1.85 to 40.1.84) and it was just crashing on launch afterward, but the weird part is that since it's not a constant crash, it's random on when it happens so it will probably be a bit hard to reproduce x.x

No, go back to the recommended one, 40.1.80

**Comment by LunafeyLazuli** [comment]
Sweet I'll test it again

**Comment by LunafeyLazuli** [comment]
So when I tried to back to that version, my game started crashing pretty hard because of all the other mods needing forge to be a higher version

**Comment by MetalKnight56** [comment]
> So when I tried to back to that version, my game started crashing pretty hard because of all the other mods needing forge to be a higher version

move these mods to older versions or remove them. Nothing we can do for now until next update which'll take some time

**Comment by LunafeyLazuli** [comment]
Ah dang, fair enough

**Comment by MetalKnight56** [comment]
Closing issue as fixed in 18.5.0.1, which is currently available for Beta Testers only.
 New forge version: 40.2.9
