### ISSUE TITLE
[Bug|Crash]: Whenever I attack anything in the combat mode the game crashes. 

### ISSUE THREAD

**Issue by GoldNickel007** [Yesssssman/epicfightmod#1252]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Everything was running smoothly until I attacked a spider with the combat mode on, then the game crashed. I tried again on different mobs and it does the same thing.

**Comment by MetalKnight56** [comment]
Closed the issuenas user did not follow the support policy
