### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by GoofinAround** [Yesssssman/epicfightmod#1254]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Whenever I hit an entity in combat mode, be it first or third person, the game crashes. It doesn't crash whenever I hit it in mining mode, and I not only the only other mod I had, but deleted it from my computer. I'm no computer scientist and I don't know much (if anything at all) about javascript, but it says something about hit particles, attack animation ticks, events and other stuff. Here's the full crash report, and if it has any importance, the only other mod I originally had was the vampirism mod, though I did remove it after loading the world.

[crash-2022-12-23_13.01.24-server.txt](https://github.com/Yesssssman/epicfightmod/files/10296999/crash-2022-12-23_13.01.24-server.txt)

If for whatever reason you are unable to view the file attached, here is a link to a google document of it. https://docs.google.com/document/d/1bo-vJy7b_SYJ96ecGexHoPRbJ_fjaLCJ20l5_VVbJWA/edit?usp=sharing

If you see this, thank you for your time, have a wonderful day and hopefully, there is an easy explanation and solution to this.

**Comment by MetalKnight56** [comment]
Closed this issue as user did not follow the support policy
