### ISSUE TITLE
[Bug]: Invisible Nether Star when killing wither

### ISSUE THREAD

**Issue by SsjGabe360** [Yesssssman/epicfightmod#1255]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Every time I kill the wither, the floating nether star is invisible and it's annoying to find. I also made a video demonstrating how the nether star is invisible.

https://user-images.githubusercontent.com/69879319/209452824-afdef232-0952-43f9-87a2-6ee1471537c8.mp4

**Comment by MetalKnight56** [comment]
Is it invisible as it does not drop? If you can, please kill him with a sword instead a command

**Comment by SsjGabe360** [comment]
https://user-images.githubusercontent.com/69879319/209506702-c7b2915a-39ab-4cc2-a0a4-77c95fad8969.mp4

**Comment by MetalKnight56** [comment]
> It does drop, it's just hard to find, and also I'm using this mod by itself.
> 
>  Minecraft_.1.16.5.-.Singleplayer.2022-12-25.23-16-27.1.1.mp4

Thank you, i'm guessing yesman overlooked this while porting wither. Is this consistent on both versions ? 1.16.5 and 1.18.2? If so, please tell me.

**Comment by SsjGabe360** [comment]
It only happens in 1.16.5



https://user-images.githubusercontent.com/69879319/209576864-0a7820dd-9e56-428d-a950-2aafb50da958.mp4

**Comment by MetalKnight56** [comment]
Thank you, we'll look into this in the next update

**Comment by MetalKnight56** [comment]
Denied issue, 1.16.5 no longer will be supported.
