### ISSUE TITLE
[Bug]: Combat not working at all

### ISSUE THREAD

**Issue by Kaiokengodx1000** [Yesssssman/epicfightmod#1257]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://essential.gg/download

### Minecraft Version

1.16.5

### What happened?

When trying to play a modpack I made with my friend using essential for forge, it simply doesn't work in multiplayer, In-fact we enter the combat mod and simply cannot attack, we can see each others animations for walking and running, but attacking was an impossibility and it made it so the mod is completely useless in an online world. If at all possible please fix this ungodly bug. thanks.

**Comment by AltonyPegas** [comment]
It seems to me that your bug report has low information: there are no logs and the bug is hard to reproduce.

**Comment by Kaiokengodx1000** [comment]
Since it doesnt actually crash the game its hard to get the logs, and its not hard at all to reproduce, It seems using the mod at all with essential on an online world makes the combat not work, we can see one another's animations when in combat mode yet we cant see ourselves in third person using them, The only way I found a work around (that has the same bug half the time mind you) was to turn off vanilla fighting completely when creating the world, even then half the time the game will simply stop letting you attack again even if your in the attack mode, making you completely unable to defend yourself.

**Comment by MetalKnight56** [comment]
Ok, so essential is a closed source mod, probably does some weird things to connection and i can't even think how. If you figure out how to solve this issue then sure yeah, but mostly its a compatbility issue which we can't properly solve without having someone that actually understands the code to guide us. Feel free to learn java and make a pull request to patch this issue. If i were you, i'd just host a server like usual...
