### ISSUE TITLE
[Bug|Crash]: incompatible with Arclight server(bukkit-based)

### ISSUE THREAD

**Issue by 3104NEIL** [Yesssssman/epicfightmod#1258]
### Have you checked if a similar issue is already reported by someone else?

- [x] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Arclight

### Minecraft Version

1.18.2

### What happened?

When we wanted to fight with Ender Dragon, the server crashed.
The log says it was caused by Epicfight,EnderDragon.
It has confused me for a few months.
Arclight version is 1.0.7, using Forge 40.1.92
Epic Fight version 18.3.7
Log will upload later

**Comment by MetalKnight56** [comment]
i think arclight needs to be on forge 40.1.80
But afaik, it doesn't properly work with epic fight, i'd use magma instead

**Comment by 3104NEIL** [comment]
i modified its installer so it could download Forge 40.1.92
and is magma a hybrid server?

**Comment by MetalKnight56** [comment]
yes

**Comment by 3104NEIL** [comment]
i have searched magma, but it only have 1.12.2
is there any good 1.18.2 hybrid server?

**Comment by MetalKnight56** [comment]
> > i have searched magma, but it only have 1.12.2 is there any good 1.18.2 hybrid server?
> 
> they have 1.12.2, 1.16.5 and 1.18.2

**Comment by 3104NEIL** [comment]
ok i got the server, i'm living in China right now and it seems that the magma foundation blocked Chinese IP, i have to use VPN. Thank you for your help.

**Comment by MetalKnight56** [comment]
> ok i got the server, i'm living in China right now and it seems that the magma foundation blocked Chinese IP, i have to use VPN. Thank you for your help.

Oof, yeah, so is it working?

**Comment by FunHB** [comment]
[crash-2023-04-11_15.30.13-server.txt](https://github.com/Yesssssman/epicfightmod/files/11201152/crash-2023-04-11_15.30.13-server.txt)
I tried on Magma, but still same error.

**Comment by MetalKnight56** [comment]
> [crash-2023-04-11_15.30.13-server.txt](https://github.com/Yesssssman/epicfightmod/files/11201152/crash-2023-04-11_15.30.13-server.txt) I tried on Magma, but still same error.

Disable all other mods and only launch magma server with epic fight enabled. If the issue persists let me know.

**Comment by FunHB** [comment]
https://pastebin.com/fazmj2aP

Nothing really changed.

**Comment by MetalKnight56** [comment]
> [pastebin.com/fazmj2aP](https://pastebin.com/fazmj2aP)
> 
> Nothing really changed.

It looks like an issue with one of the enabled plugins. I'd try disabling luckperms, but if it doesn't work disable them all and slowly add them back so we can see which one is causing the crash.

**Comment by FunHB** [comment]
disabling plugins didn't help

https://pastebin.com/8t29cBbw

**Comment by MetalKnight56** [comment]
> disabling plugins didn't help
> 
> [pastebin.com/8t29cBbw](https://pastebin.com/8t29cBbw)

There seems to be some plugins still enabled. 

Plugins: { ClearLag v3.2.2 me.minebuilders.clearlag.Clearlag [bob7l], Essentials v2.20.0-dev+44-43d84de com.earth2me.essentials.Essentials [Zenexer, ementalo, Aelux, Brettflan, KimKandor, snowleo, ceulemans, Xeology, KHobbits, md_5, Iaccidentally, drtshock, vemacs, SupaHam, mdcfe, JRoy, pop4959],}

**Comment by FunHB** [comment]
https://pastebin.com/HatJkQPw

from the same day, because I noticed that I still had some plugins, but forgot to resend the log. As you can see, the error persists.

**Comment by Shybella** [comment]
This is fixed now, https://github.com/IzzelAliz/Arclight/issues/1059

Next time please report the issue to the hybrid, this didn't have to take 6+ months to get fixed.
