### ISSUE TITLE
[Enhancement]: Way to force player into battle mode or mining mode for x duration?

### ISSUE THREAD

**Issue by jdspeyer** [Yesssssman/epicfightmod#1259]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Not an issue, just a suggestion I had thought of while creating a map/modpack. I understand that it is somewhat niche, but I was thinking there could be quite a few use cases in adventure maps/ modpacks where the creator might want to lock the player out of mining or battle mode for some duration. 

Thought this could be done with either a potion effect that could be applied, or a command (I know there is a command to put the player into the mode currently, but from my knowledge, there is nothing stopping them from immediately toggling back).

**Comment by MetalKnight56** [comment]
I mean, we could make it so you are able to change the mode, being able to set duration is too specific and can be done without us having to add it yk, could use repeaters or some kind of loop with redstone and a command block that locks the player with a command into a certain mode, what do you think?

**Comment by jdspeyer** [comment]
Totally understand. In the case of map-making, you're totally right, the command blocks would work. I do think, like you said, an ability to toggle the mode in some manner that doesn't allow the player to change it back could have more widespread use (but totally understand there are features that are far more important than this haha).

Thanks for the reply! Love this mod and looking forward to the first-person enhancements that I see you guys working on based on your replies/tags on the other issues 👀

**Comment by MetalKnight56** [comment]
> Totally understand. In the case of map-making, you're totally right, the command blocks would work. I do think, like you said, an ability to toggle the mode in some manner that doesn't allow the player to change it back could have more widespread use (but totally understand there are features that are far more important than this haha).
> 
> Thanks for the reply! Love this mod and looking forward to the first-person enhancements that I see you guys working on based on your replies/tags on the other issues 👀

Ok so theres a command that allows you to switch players mode between mining and battle, like this:
/epicfight mode [battle|mining] [@a|@e|@r|@p]
We'll be adding a new gamerule to stop players from switching between modes.
/gamerule canSwitchCombat [true|false] 
What do youn think?

**Comment by jdspeyer** [comment]
I think that is a great way to handle it!

**Comment by DynastyKarma** [comment]
> > Totally understand. In the case of map-making, you're totally right, the command blocks would work. I do think, like you said, an ability to toggle the mode in some manner that doesn't allow the player to change it back could have more widespread use (but totally understand there are features that are far more important than this haha).
> > Thanks for the reply! Love this mod and looking forward to the first-person enhancements that I see you guys working on based on your replies/tags on the other issues 👀
> 
> Ok so theres **already** a command that allows you to switch players mode between mining and battle, like this: _/epicfight mode [battle|mining] [@A|@e|@r|@p]_
> 
> We'll be adding a **new** gamerule to stop players from switching between modes. _/gamerule canSwitchCombat [true|false]_ What do you think?

That's a cool gamerule, but then how would people do stuff such as mining? As you can't break blocks in Fight Mode.

**Comment by MetalKnight56** [comment]
> > > Totally understand. In the case of map-making, you're totally right, the command blocks would work. I do think, like you said, an ability to toggle the mode in some manner that doesn't allow the player to change it back could have more widespread use (but totally understand there are features that are far more important than this haha).
> > > Thanks for the reply! Love this mod and looking forward to the first-person enhancements that I see you guys working on based on your replies/tags on the other issues 👀
> > 
> > 
> > Ok so theres **already** a command that allows you to switch players mode between mining and battle, like this: _/epicfight mode [battle|mining] [@A|@e|@r|@p]_
> > We'll be adding a **new** gamerule to stop players from switching between modes. _/gamerule canSwitchCombat [true|false]_ What do you think?
> 
> That's a cool gamerule, but then how would people do stuff such as mining? As you can't break blocks in Fight Mode. As there are some parts of some adventure maps and stuff that give you certain items that allow you to break certain blocks.

Thats up to the map creator to decide when he wants players to be able to mine or when he wants them to go to combat yk.
So like, they'd just change player's modes with the commands above and they can configure stuff to their liking

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
