### ISSUE TITLE
client crash.

### ISSUE THREAD

**Issue by cursinorock** [Yesssssman/epicfightmod#126]
I just created a new world and it crashed while I was exploring.

Forge 36.1.3
with many mods but work just fine with the old version of the mod.

[crash-2021-03-30_11.31.30-server.txt](https://github.com/Yesssssman/epicfightmod/files/6229802/crash-2021-03-30_11.31.30-server.txt)

**Comment by Fooshcookie** [comment]
Go back into the world, if you can, to where you crashed with the Epic Fight Mod disabled. Check around for a Husk Spawner. Those spawners for some unknown reason are causing crashes; I checked this with a random spawner of my own placing and a husk spawn egg in the dark. It appears it's when the entity attempts to spawn that the crash occurs, as if unable to spawn, the spawner will not cause a crash (IE: in sunlight or peaceful mode). I'm unsure if a fix is in the works, or not, however this has been reported multiple times, I believe, including by myself. It's a really unfortunate and annoying bug, so hopefully it's being looked into.

**Comment by cursinorock** [comment]
Thks but i try it and works fine now, in this new version, idk why xD

**Comment by Fooshcookie** [comment]
Odd, I'm still having the issue. Perhaps it's two separate issues entirely, despite having a strikingly similar crash log. I'm keeping an eye out regardless.
