### ISSUE TITLE
[Bug]: My 1.18.2 config files arent able to add custom weapons

### ISSUE THREAD

**Issue by bean2xd** [Yesssssman/epicfightmod#1261]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

In the config files, i searched for "epicfight.toml" for adding animations to modded weapons, but my config file are like this:
![imagem_2023-01-01_120509609](https://user-images.githubusercontent.com/121759312/210175306-96afac69-eba1-4b81-b72c-b52984dbd747.png)
Is it because of the game version?

**Comment by MetalKnight56** [comment]
Closing issue as user violated support policy and din't check updates.
