### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by GOOFYAHHFARDNITEPRANKSTER1465872016** [Yesssssman/epicfightmod#1262]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.16.5

### What happened?

hello. a year ago i started to use Epic fight mod but recently i started having my game crashed while i was punching mobs on my survival world, the version i was playing on was 1.16.5 i heard that LOOOOOTSSSSSSSSSSS of ppl have the same problem any solution? please?

**Comment by DynastyKarma** [comment]
Hehe, welp.
Just an fyi, this post is going to get closed, your message is most likely gonna be "Closed issue as user broke the support policy
"

**Comment by GOOFYAHHFARDNITEPRANKSTER1465872016** [comment]
if i broke the rules i have nothing against it

**Comment by GOOFYAHHFARDNITEPRANKSTER1465872016** [comment]
go ahead delete my issue im sorry

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy
