### ISSUE TITLE
[Bug|Crash]: Player Ticking Crash (1.16.5)

### ISSUE THREAD

**Issue by GreedBR123** [Yesssssman/epicfightmod#1263]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

 I put a bunch of mods together in curseforge and tried to play, I get a crash everytime I get damaged by a mob, maybe it's just the modded ones. In my case it was a Tremor from Lycanite mobs I received damage before I think the crash just applies to a entity damaging me.
[crash-2023-01-07_20.15.05-server.txt](https://github.com/Yesssssman/epicfightmod/files/10367331/crash-2023-01-07_20.15.05-server.txt)
I have seen other reports and I have spartan weaponry, lycanite mobs, rubidium, sophisticated backpacks, apotheosis, tinker's construct, oculus, shoulder surfing reloaded and ice and fire that may cause a incompatibility.

I tried to take damage from a vanilla mob (a spider) and I crashed immediatly the crash report: 
[crash-2023-01-07_20.55.03-server.txt](https://github.com/Yesssssman/epicfightmod/files/10367336/crash-2023-01-07_20.55.03-server.txt)

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy
