### ISSUE TITLE
[Bug|Crash]: PLEASE HELP MEEE

### ISSUE THREAD

**Issue by Na1wyoo** [Yesssssman/epicfightmod#1264]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

I am from Russia, my English may be broken. I fucked your epic fight all the time, I spent 6 days trying to add animations to objects from the Spartans mod, but it doesn't fucking work, because there are no fucking lines with custom entities and objects in the config. If you try to enter everything yourself, replace the config with the config from the site https://minecraftpatch.ru/epic-fight-spartan-weaponry-447367 the fucking game makes the config default!!!! I need version 1.16.5 and please, please tell me how to make other mods with weapons also have animation

[loot]
	skill_book_mob_loot = true
	skill_book_chest_loot = true

[default_gamerule]
	hasFallAnimation = true
	#Range: 0 ~ 100
	weightPenalty = 100
	disapleEntityUI = false
	keepSkills = false
	doVanillaAttack = true

**Comment by Na1wyoo** [comment]
and ye, in russia dont have information on this mod

**Comment by MetalKnight56** [comment]
User provided suspicious link and did not state their issue calmly. Closing this issue as user broke the support policy.
