### ISSUE TITLE
[Suggestion]: Will you add animation of eating and drinking? 

### ISSUE THREAD

**Issue by GalaxyZEROX** [Yesssssman/epicfightmod#1265]
### Have you checked if a similar issue is already reported by someone else?

- [ ] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Excuse me, will you add the animation of eating food and drinking medicine in a later update?

**Comment by MetalKnight56** [comment]
Yes, drinking and eating animations are already finished. We'll be releasing it along side the next update.

**Comment by GalaxyZEROX** [comment]
> 没错，喝酒吃饭动画早就完成了。我们将在下一次更新时发布它。

This is really great! Will it be updated from 1.16.5?

**Comment by MetalKnight56** [comment]
> > 没错，喝酒吃饭动画早就完成了。我们将在下一次更新时发布它。
> 
> This is really great! Will it be updated from 1.16.5?

Not planned for 1.16.5, but we might, don't want to confirm nor deny.

**Comment by GalaxyZEROX** [comment]
> > > 没错,喝酒吃饭动画早就完成了。我们将在下一次更新时发布它。
> > 
> > 
> > 这真的太棒了！会从1.16.5更新吗？
> 
> 1.16.5没有计划，但我们可能会，不想确认也不想否认。

All right. . . . Looking forward to future updates.

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
