### ISSUE TITLE
[Crash]: Catserver-1.16.5 can't commonly use this mod

### ISSUE THREAD

**Issue by Y-Yuw** [Yesssssman/epicfightmod#1266]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [ ] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

16.6.4

### Minecraft Version

1.16.5

### What happened?

Any time if I use the fight way in this mod,the server becomes crashed.
[crash.txt](https://github.com/Yesssssman/epicfightmod/files/10420358/crash.txt)
Can you tell me how to fix this problem?
thank you very much

**Comment by Y-Yuw** [comment]
catserver use forge:36.2.39

**Comment by MetalKnight56** [comment]
> catserver use forge:36.2.39

This is a mod incompatbility issue, doesn't seem to be a direct issue with epicfight, try removing mods one by one and then launching the server to narrow down the possible trouble makers. If you'd like to report issues within epic fight, then use the github, everything else, please refer to the discord server.

**Comment by Y-Yuw** [comment]
no，i tried that, i remove every mod without this mod, the crash still happens
![image](https://user-images.githubusercontent.com/89560808/212556983-c4e481d1-45d0-48bc-a845-1451bcda02c1.png)
![image](https://user-images.githubusercontent.com/89560808/212557004-6f79649f-8e33-4909-b7c8-6ce7367513e5.png)

**Comment by Y-Yuw** [comment]
![image](https://user-images.githubusercontent.com/89560808/212557041-dbcf57b2-4143-40f8-a898-f11882adad34.png)

**Comment by MetalKnight56** [comment]
> no，i tried that, i remove every mod without this mod, the crash still happens ![image](https://user-images.githubusercontent.com/89560808/212556983-c4e481d1-45d0-48bc-a845-1451bcda02c1.png) ![image](https://user-images.githubusercontent.com/89560808/212557004-6f79649f-8e33-4909-b7c8-6ce7367513e5.png)

The server also needs forge 36.2.39

**Comment by Y-Yuw** [comment]
Catserver's latest version has the forge
![7GW}Y59{4Z_PG5UD5H{JU%A](https://user-images.githubusercontent.com/89560808/212557189-d1541340-fa77-42c4-a5a7-187fc9692066.jpg)

**Comment by MetalKnight56** [comment]
> Catserver's latest version has the forge ![7GW}Y59{4Z_PG5UD5H{JU%A](https://user-images.githubusercontent.com/89560808/212557189-d1541340-fa77-42c4-a5a7-187fc9692066.jpg)

what is catserver goddamnit, and what version of forge, i need the whole log, crashlog everything

**Comment by Y-Yuw** [comment]
[crash-2023-01-16_01.28.51-server.txt](https://github.com/Yesssssman/epicfightmod/files/10420798/crash-2023-01-16_01.28.51-server.txt)

**Comment by MetalKnight56** [comment]
> [crash-2023-01-16_01.28.51-server.txt](https://github.com/Yesssssman/epicfightmod/files/10420798/crash-2023-01-16_01.28.51-server.txt)

Bro, use forge's server not this catloader or whatever

**Comment by Y-Yuw** [comment]
hmmmmmm,so this problem is just the incompatbility between the Catserver and EpicFight?

**Comment by MetalKnight56** [comment]
> hmmmmmm,so this problem is just the incompatbility between the Catserver and EpicFight?

No its an issue with catserver only, epicfight runs fine, you are using a garbage bukkit implementation to run alongisde with forge, if i were you i'd use magma for this, and even then its not recommended. I'd just use forge server.

**Comment by Y-Yuw** [comment]
OK, I know about that,thank you very much for answering the question for me.
![%9UO2071D6Z MNY}TDRZ(T7](https://user-images.githubusercontent.com/89560808/212557622-3f6d40a4-ee4c-4c7e-8eed-f6d1b2c6ea10.jpg)
