### ISSUE TITLE
[Bug]: Mine and slash mod bar in Epic Fight mod

### ISSUE THREAD

**Issue by dylan-jara** [Yesssssman/epicfightmod#1267]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Mine and Slash 

### Minecraft Version

1.16.5

### What happened?

The Mine and slash mod, generates a life bar + the level of the mob, but when using the Epic Fight Mod, it disables and the epic fight mod bar is placed, is there a way to place the mod bar mine and slash on top of the mob, keeping the animation on?, or is there a way to remove the animation and thus enable the life and level bar of the other mod?.

**Comment by MetalKnight56** [comment]
Closed issue as this is not a real issue. Support Policy Violation.
