### ISSUE TITLE
[Bug|Crash]: Whenever I attack NPCs my game crashes

### ISSUE THREAD

**Issue by Iamverycoolvery** [Yesssssman/epicfightmod#1269]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Whenever I try attacking any mobs, the game freezes and crashes. It doesn't matter if it's a normal attack or the special attack, my game will crash when I attack mobs. I have checked the mod alone and it still crashed whenever I attacked. This is only for the combat mode, not normally fighting. Please fix this I cannot use the mod.

**Comment by MetalKnight56** [comment]
Closed issue as user did not follow the support policy.
