### ISSUE TITLE
Spear incompatibility issues with the dungeons gear mod. This extends to staffs as well

### ISSUE THREAD

**Issue by Ragnaorok** [Yesssssman/epicfightmod#127]
[custom_weaponry.battlestaff]
		armor_ignorance = 0.0
		hit_at_once = 3
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:battlestaff"
the weapon attack animations are defaulted to fist

**Comment by Yesssssman** [comment]
What is the version?
