### ISSUE TITLE
[Bug|Crash]: Custom Weaponry from DungeonGears Do Vanilla Animation

### ISSUE THREAD

**Issue by MNxqvi** [Yesssssman/epicfightmod#1272]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Hey guys,
I can't seem to get animations working for weapons in the DungeonGears modpack, not sure what i'm doing wrong haha
Here's what i've got in the config file:

[default_gamerule]
	doVanillaAttack = true
	keepSkills = false
	hasFallAnimation = true
	disapleEntityUI = false
	#Range: 0 ~ 100
	weightPenalty = 100

[loot]
	skill_book_mob_loot = true
	skill_book_chest_loot = true

[custom_weaponry]

[custom_weaponry.Venom_Glaive]
armor_ignorance = 10.0
hit_at_once = 4
impact = 2.9
#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
weapon_type = "SPEAR"
registry_name = "dungeons_gear:venom_glaive"

**Comment by MetalKnight56** [comment]
Support policy violated, do not ask for help in github, we have a discord server for this kind of support.
