### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Leavesandbeans** [Yesssssman/epicfightmod#1274]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Im able to get into battle mode and use vanilla attacks, but hitting a mob with a battle mode attack will cause the game to automatically crash.

**Comment by MetalKnight56** [comment]
Closed issue as user did not follow the support policy.
