### ISSUE TITLE
[Bug|Crash]: whenever i attack a mob my game crashes

### ISSUE THREAD

**Issue by M0NKEYGR1NDER** [Yesssssman/epicfightmod#1276]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

epic fight mod

### Minecraft Version

1.16.5

### What happened?

whever i attack a mob with the epic fight mod activated my game crashes

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy.

**Comment by M0NKEYGR1NDER** [comment]
how do i fix it?

**Comment by M0NKEYGR1NDER** [comment]
???
