### ISSUE TITLE
[Bug|Crash]: whenever i attack a mob i crash

### ISSUE THREAD

**Issue by M0NKEYGR1NDER** [Yesssssman/epicfightmod#1277]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.16.5

### What happened?

whenever i attack a mob while in combat mode my game crashes, i have no other mods installed only epic fight. i dont know why it keeps on crashing. ive read a other issue like this, they said to use the most recent forge but i am. this is what i get, The game crashed whilst ticking player
Error: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;)Lnet/minecraft/entity/EntitySize;

**Comment by MetalKnight56** [comment]
Closed issue as user did not follow the support policy. **STOP REPORTING THIS HERE OR YOU WILL BE BLOCKED FROM THIS PROJECT**

**Comment by M0NKEYGR1NDER** [comment]
how do i fix it???

**Comment by M0NKEYGR1NDER** [comment]
whats the point of posting a bug or crash if yall aint gonna help

**Comment by M0NKEYGR1NDER** [comment]
makes no sense

**Comment by MetalKnight56** [comment]
> whats the point of posting a bug or crash if yall aint gonna help

Because its not a fucking issue, you are just dumb. If you need help use the **DISCORD SERVER**
https://discord.gg/wpaVPMCB, first do some research before quote "reporting an issue"

**Comment by M0NKEYGR1NDER** [comment]
i did

**Comment by M0NKEYGR1NDER** [comment]
i looked up other issues like this and it said to use the most recent version of forge

**Comment by M0NKEYGR1NDER** [comment]
and i am

**Comment by MetalKnight56** [comment]
> and i am

Log

**Comment by M0NKEYGR1NDER** [comment]
?

**Comment by MetalKnight56** [comment]
> ?
How do you expect me to help you if you didn't even send a log report?

**Comment by M0NKEYGR1NDER** [comment]
i did

**Comment by M0NKEYGR1NDER** [comment]
The game crashed whilst ticking player
Error: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;)Lnet/minecraft/entity/EntitySize;

**Comment by MetalKnight56** [comment]
> The game crashed whilst ticking player Error: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;)Lnet/minecraft/entity/EntitySize;

This is not a fucking log report

**Comment by M0NKEYGR1NDER** [comment]
its not?

**Comment by MetalKnight56** [comment]
> its not?

You see, thats why you shouldn't be here, now if you want help use the discord server. Its better for both of us if you keep the project clean with actual issues

**Comment by M0NKEYGR1NDER** [comment]
how do i get the log report

**Comment by MetalKnight56** [comment]
> how do i get the log report

Figure it out yourself, i won't be replying to this anymore.
