### ISSUE TITLE
[Bug|Crash]: Game Crashes to launcher everytime I hit something in battle mode

### ISSUE THREAD

**Issue by Kcplayz07** [Yesssssman/epicfightmod#1278]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Everytime I hit something in combat mode it crashes to the launcher, if I hit something outside of combat mode its fine, but as soon as I hit something it crashes

**Comment by Kcplayz07** [comment]
just double checked, and anytime a mob hits me, even if im not in combat mode it still crashes me

**Comment by MetalKnight56** [comment]
Closed issue as user did not follow the support policy. Please refer to the discord server for this kind of issue.
