### ISSUE TITLE
[Bug]: You can't add items that automatically switch between digging and fighting in MOD (1.16.5).

### ISSUE THREAD

**Issue by GalaxyZEROX** [Yesssssman/epicfightmod#1282]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

In the game MOD, it is impossible to add the item ID that automatically switches mining/fighting.

**Comment by GalaxyZEROX** [comment]
![2023_02_13_18_04 08](https://user-images.githubusercontent.com/73332842/218429125-085d143b-867c-4c92-991c-37d10ed778bc.png)
![2023_02_13_18_01 49](https://user-images.githubusercontent.com/73332842/218429132-7edd9b68-d4d6-4c7d-aacf-f6a3063c3af5.png)

**Comment by MetalKnight56** [comment]
> ![2023_02_13_18_04 08](https://user-images.githubusercontent.com/73332842/218429125-085d143b-867c-4c92-991c-37d10ed778bc.png) ![2023_02_13_18_01 49](https://user-images.githubusercontent.com/73332842/218429132-7edd9b68-d4d6-4c7d-aacf-f6a3063c3af5.png)

Use the in-game UI. You can do that by going onto mods, and adding in the weapons you want from there.

**Comment by GalaxyZEROX** [comment]
https://user-images.githubusercontent.com/73332842/219036201-5229c10a-d2e9-4833-87f4-13b05c4e7ce1.mp4

**Comment by MetalKnight56** [comment]
Denied issue, 1.16.5 no longer will be supported.
