### ISSUE TITLE
[BUG] Invisibility potion shows player model in first person1.16.5/1.18.2

### ISSUE THREAD

**Issue by GalaxyZEROX** [Yesssssman/epicfightmod#1283]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Armourer's Workshop

### Minecraft Version

1.16.5

### What happened?

When Armourer's Workshop and Epic Fight are used simultaneously in 1.16.5 and 1.18.2, Epic Fight in the first person can't make the player's body invisible, which leads to serious body model interleaving.

**Comment by MetalKnight56** [comment]
Footage please, it'll help us a lot

**Comment by GalaxyZEROX** [comment]
![2023-02-15_20 56 05](https://user-images.githubusercontent.com/73332842/219033761-32265402-8786-4337-83a1-ac3baa0d5374.png)
![2023-02-15_20 55 52](https://user-images.githubusercontent.com/73332842/219033771-a9cb819b-cf60-47fc-a121-dc6e0c16ce30.png)

**Comment by MetalKnight56** [comment]
> ![2023-02-15_20 56 05](https://user-images.githubusercontent.com/73332842/219033761-32265402-8786-4337-83a1-ac3baa0d5374.png) ![2023-02-15_20 55 52](https://user-images.githubusercontent.com/73332842/219033771-a9cb819b-cf60-47fc-a121-dc6e0c16ce30.png)

You may want to try reporting that to the armorer's workshop github page. I'll look into this more later

**Comment by GalaxyZEROX** [comment]
In this regard, I have contacted the author of Armourer's Workshop, and the author said that he could not replace the model that could not be invisible in the first person. . . Unless you can make the first person invisible by stealth potion.

**Comment by MetalKnight56** [comment]
> In this regard, I have contacted the author of Armourer's Workshop, and the author said that he could not replace the model that could not be invisible in the first person. . . Unless you can make the first person invisible by stealth potion.

Can you check this issue in vanilla, only with epic fight?

**Comment by GalaxyZEROX** [comment]
https://user-images.githubusercontent.com/73332842/219871667-7a65c816-003f-42af-832c-2c3a43214a8e.mp4

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
