### ISSUE TITLE
[Bug|Crash]: A question about Mermaid Tail's visual compatibility with epic fight

### ISSUE THREAD

**Issue by DSTJohnXie** [Yesssssman/epicfightmod#1285]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/mermod-forge

### Minecraft Version

1.18.2

### What happened?

Excuse me, I just noticed some conflict between epic fight and the mermaid tail mod, when player is in battle mode, the player's legs will come out of the mermaid tail mod's fish tail model, do you know how to fix this?

https://user-images.githubusercontent.com/102445656/219680395-891d3a63-8099-4feb-99e0-7a4d6caf6eb0.mp4

List of mods involved:
epic fight
Origins (Forge):https://www.curseforge.com/minecraft/mc-mods/origins-forge              
require: Caelus API (Forge)  https://www.curseforge.com/minecraft/mc-mods/caelus

Mermod [FORGE]:https://www.curseforge.com/minecraft/mc-mods/mermod-forge
(Major conflicting mods)

Origins: Accessibilities:https://www.curseforge.com/minecraft/mc-mods/origins-accessibilities

thats all,thanks for your hard work, I'm looking forward to your update, my savior.plzzzzzzzzzzzzzzzzzzzzzzzzz!

**Comment by DSTJohnXie** [comment]
Some information you might want to know as you go along (just in case I'm not clear). Mermaid Tail mod is an Origin mod that gives Merpeople a tail when underwater, not pants or shoes to attach to the kit bar, it does have a trigger called sea necklace, but it require the

curios api:https://www.curseforge.com/minecraft/mc-mods/curios
（I'm sorry that I missed this prefix when uploading，please forgive me for my foolishness）

**Comment by MetalKnight56** [comment]
@Yesssssman I think this may be nice for us to patch as it'll allow other mods to disable body parts and ovveride them with whatever they want.

**Comment by Yesssssman** [comment]
Fixed in recent 1.20.1
