### ISSUE TITLE
[Bug|Crash]: Crash fighting a ravager

### ISSUE THREAD

**Issue by maximogta** [Yesssssman/epicfightmod#1287]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Crash:
https://pastebin.com/yC7KjWbz

Full log:
https://drive.google.com/file/d/1qcpVx6vXd8Hh4pwyYIeS8YqndC4s2BIU/view?usp=share_link

**Comment by mrdragonblack** [comment]
try to upgrade your forge or remove your optifine or remove conflict mod  
because I've experienced anything like this i remove the conflict mod and its clear no crash or update your latest epic fight mod

**Comment by MetalKnight56** [comment]
Please remove all mods and slowly add them back to see what is causing this issue.
