### ISSUE TITLE
[Crash]: Crash when use "Build Tool" in mod Minecolonies

### ISSUE THREAD

**Issue by Edemstreij** [Yesssssman/epicfightmod#1288]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/minecolonies

### Minecraft Version

1.16.5

### What happened?

When I use the latest version of the EPM mod, along with the Minecolonies mod, or more specifically with the Structurize mod. My game is crashing when I try to install a building with Эarmor_stand".The mod creates a projection of the future building, and if there is "Armor_stand" in the projection, the game crashes. Everything worked for me with version EPM 16.5.13. 
[crash-2023-02-21_20.35.01-client.txt](https://github.com/Yesssssman/epicfightmod/files/10796221/crash-2023-02-21_20.35.01-client.txt)

**Comment by MetalKnight56** [comment]
Epic Fight doesn't work with mine colonies on 1.16.5. Upgrade your minecraft version or uninstall minecolonies. Nothing we can do as this is an issue on their side and they've decided to discontinue 1.16.5.

**Comment by BraveCaperCat2** [comment]
You cannot use minecraft versions higher than 1.16.5 with epic fight mod - it is only available for 1.16.x (all minor versions of 1.16)
