### ISSUE TITLE
[Bug|Crash]: Incompatibility with Weapon Leveling

### ISSUE THREAD

**Issue by Dolphos** [Yesssssman/epicfightmod#1289]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/weapon-leveling

### Minecraft Version

1.18.2

### What happened?

I am running forge with a couple of mods including weapon leveling and epic fight.
When hitting/killing enemies with any weapon normally I get some XP for this weapon.
However, when in combat mode of Epic Fight I do in fact not gain any weapon experience for the used weapon.

Minecraft Version: 1.18.2
Mod Version: weaponleveling-1.18.2-1.4.3

1. Download Epic Fight and weapon leveling
2. use any weapon in combat mode
3. gain no experience on this weapon...

Expected: gain experience

So, it would for now be nice to know, what could possibly cause this issue. Does the Combat Mode maybe change the hit detection? Please do enlighten me :)

**Comment by Dolphos** [comment]
PS.: I also reported the bug on Weapon Leveling's side, in hopes for them to respond. Maybe they can provide some intel as well.

**Comment by MetalKnight56** [comment]
This issue should be fixed on the latest branch, tho we haven't yet pushed the update to CurseForge as we want to fix more stuff first.

**Comment by Dolphos** [comment]
Alright, then I will gladly wait for the patch. Thank You :)
