### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by TDraNix** [Yesssssman/epicfightmod#1290]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

EpicFight-16.6.4

### Minecraft Version

1.16.5

### What happened?

The game crashed when I just hit a Drowned with an Iron Pickaxe in the Deep Ocean biome. Here's my crash report
[crash-2023-02-25_10.45.59-server.txt](https://github.com/Yesssssman/epicfightmod/files/10830185/crash-2023-02-25_10.45.59-server.txt)

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy. Please refer to the discord for issues like this.
