### ISSUE TITLE
[Bug|Crash]:

### ISSUE THREAD

**Issue by Horhaywastaken** [Yesssssman/epicfightmod#1291]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://beta.curseforge.com/minecraft/mc-mods/epic-fight-mod

### Minecraft Version

1.16.5

### What happened?

As soon as I attack anything from another mod in the most recent version, 1.16.5, the game crashes, bosses especially. I know this hasn't always happened, is it just something in the newest release? (16.6.4.jar)

**Comment by Kasualix** [comment]
any crash report?

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy.  Please refer to the discord server for this kind of issue.
