### ISSUE TITLE
[Bug|Crash]: Forge - 40.2.1 EFM 18.3.7 "this.weaponAttackMotions" is null error

### ISSUE THREAD

**Issue by epicthejet** [Yesssssman/epicfightmod#1293]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

[crash-2023-03-20_03.32.13-server.txt](https://github.com/Yesssssman/epicfightmod/files/11022834/crash-2023-03-20_03.32.13-server.txt)

Ok, so I was testing modpack stability and the world I was on locked up. Had to kill the game in task manager to close it as the world wouldn't save or anything. I have a suspicion that it has something to do with the mod im currently working on, called Jet and Elias Armors. This was a recent expansion I did where I set up humanoid mobs with native support for EFM using datapacks contained in the mod itself. It worked just fine for the first 2 days of testing but after I gave one of the mobs the option to use either a katana or dual swords these crashes began to happen. So I removed that capability and those weapons entirely yet it still happend. I can give more info if needed as well as the mod I'm working on itself since that version of it isn't on curseforge yet. Also so its known, the mod I'm referring to was made using Mcreator.

P.S. the crashlog can be reproduced instantly by doing the /reload command

**Comment by epicthejet** [comment]
Quick note, did some more digging and it turns out it was integrated dungeons and structures that was causing most of the issues. Regardless that crash after doing the reload command is still 100% on EFM.

**Comment by MetalKnight56** [comment]
Can you confirm for me if this issue still persists?

**Comment by DeshiDesu** [comment]
Can confirm this crash still persists on 1.20.1
the only true solution is to never do /reload ig...
[crash-2024-05-01_22.14.29-server.txt](https://github.com/Yesssssman/epicfightmod/files/15183102/crash-2024-05-01_22.14.29-server.txt)

**Comment by guivnf** [comment]
Crash was fixed way back in 20.6.5
