### ISSUE TITLE
[Bug]: epicfight.toml Config does not contain Custom weapon in 1.16.4 (mod version 16.6.4?

### ISSUE THREAD

**Issue by Riper67** [Yesssssman/epicfightmod#1294]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

So i Donwloaded Some weaponry mods (dont remember names) and i wanted to add animations to it via the config. so i watched some tutorials n stuff but after i found the config there was no [custom_weaponry] in there. is it because its not inside anymore or was it for older versions?

YT video: https://www.youtube.com/watch?v=qOJpCXR8L_w
Screenshots:
![Screenshot 2023-03-24 151424](https://user-images.githubusercontent.com/128292643/227548074-ca5864ab-8765-47c7-a943-92f5a48d73ce.JPEG)

**Comment by MetalKnight56** [comment]
Weapon configs are no longer supported. Use datapacks instead and check the wiki to learn how.
