### ISSUE TITLE
[Crash]: The game crashes whenever I attack a mob (Ticking player)

### ISSUE THREAD

**Issue by ManuApplejuice** [Yesssssman/epicfightmod#1295]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Hi, I started playing a modpack recently called Shattered Ring, a souls-like modpack created by AsianHalfSquat, the game runned fine at first, after a few days i did something that may have caused the crash, there were multiple crashes, i tried fixing it but I gave up after the third day. How I wrote in the title the crash happens when I attack any mob, not atacking, just when a mob is hit by me. I added more mods to the modpack, so I don't know if it's a mod incompatibility problem, or a problem with the Epic Fight  mod itself, I also tried to use other versions of the Epic Fight mod. Here is the crash report from the last crash called "Ticking player" , there are more crashes just like this one, and others like one about something called "Loading entity NBT" , one called "Unexpected error", as well as one similar to the first but called  "Ticking entity". I will add those too (The reports are in mention order as well as ordered form lastest to oldest) Thank you for your time.

[crash-2023-03-24_21.19.03-server.txt](https://github.com/Yesssssman/epicfightmod/files/11067921/crash-2023-03-24_21.19.03-server.txt)

[crash-2023-03-23_00.35.56-server.txt](https://github.com/Yesssssman/epicfightmod/files/11067922/crash-2023-03-23_00.35.56-server.txt)

[crash-2023-03-07_04.02.42-client.txt](https://github.com/Yesssssman/epicfightmod/files/11067925/crash-2023-03-07_04.02.42-client.txt)

[crash-2023-03-07_01.34.55-client.txt](https://github.com/Yesssssman/epicfightmod/files/11067926/crash-2023-03-07_01.34.55-client.txt)

**Comment by DynastyKarma** [comment]
Check the forge version, try updating it to the latest. Just an FYI this issue will probably get closed, so try this before it does.

**Comment by ManuApplejuice** [comment]
> Check the forge version, try updating it to the latest. Just an FYI this issue will probably get closed, so try this before it does.

Closed why? Too similar to another report?

**Comment by Kasualix** [comment]
Epic Fight can't work on Forge 36.2.34.
You MUST use 36.2.39

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy. Please refer to the discord server for this kind of issue.
