### ISSUE TITLE
[Bug|Crash]: The config file don't load correctly

### ISSUE THREAD

**Issue by ChaoticPhamton** [Yesssssman/epicfightmod#1296]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/4029362

### Minecraft Version

1.16.5

### What happened?

I was making a few tests of mods, and when i wanted to make a clear version to test a PVP with the Epic Fight mod by itself, i try adding wepons, then i noticed that the config file wasn't correctly loaded showing the "custom weaponry" section, i tried adding it from another file, but still being not usefull to work, how can i fix this or how i can get the old epicfight.toml, this is the only thing i can see on the current toml archive:

"[loot]
	skill_book_mob_loot = true
	skill_book_chest_loot = true

[default_gamerule]
	hasFallAnimation = true
	#Range: 0 ~ 100
	weightPenalty = 100
	disapleEntityUI = false
	keepSkills = false
	doVanillaAttack = true"
	
if someone have fixed this, how you did it?

**Comment by Woodgoldtwo** [comment]
The config is no longer used for mod compatibility

**Comment by ChaoticPhamton** [comment]
What datapack it would be? And if we use an older forge version it work?? It happens with the newer forge version then, since i just updated the forge

**Comment by ChaoticPhamton** [comment]
> ![image](https://user-images.githubusercontent.com/129194219/228286906-19494a9c-d91b-45ff-83c0-5ce8a1046e50.png) Data is overwritten by Forge on every launch

Now that i read it right, it seems that forge think the epicfight.toml is wrong configured, cna you give me a copy of your epicfight.toml?? I would like to try something

**Comment by TrollSom** [comment]
> > ![image](https://user-images.githubusercontent.com/129194219/228286906-19494a9c-d91b-45ff-83c0-5ce8a1046e50.png) Data is overwritten by Forge on every launch
> 
> Now that i read it right, it seems that forge think the epicfight.toml is wrong configured, can you give me a copy of your epicfight.toml?? I would like to try something

[custom_entity]

	[custom_entity.sample]
		type_name = "modid:type_name"
		impact = 0.5
		max_strikes = 1
		armor_negation = 0.0
		#Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
		ai_type = "ZOMBIE"
		texture_location = "modid:texture_location"

[custom_weaponry]

	[custom_weaponry.iceandfire_dragonsteel_fire_sword]
		armor_ignorance = 10.0
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "LONGSWORD"
		registry_name = "iceandfire:dragonsteel_fire_sword"

	[custom_weaponry.iceandfire_dragonsteel_lightning_sword]
		armor_ignorance = 10.0
		hit_at_once = 2
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "LONGSWORD"
		registry_name = "iceandfire:dragonsteel_lightning_sword"

	[custom_weaponry.iceandfire_dragonsteel_ice_sword]
		armor_ignorance = 10.0
		hit_at_once = 2
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "LONGSWORD"
		registry_name = "iceandfire:dragonsteel_ice_sword"

	[custom_weaponry.iceandfire_dread_queen_sword]
		armor_ignorance = 15.0
		hit_at_once = 2
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "LONGSWORD"
		registry_name = "iceandfire:dread_queen_sword"

	[custom_weaponry.iceandfire_stymphalian_bird_dagger]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 0.3
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "DAGGER"
		registry_name = "iceandfire:stymphalian_bird_dagger"

	[custom_weaponry.iceandfire_tide_trident]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "TRIDENT"
		registry_name = "iceandfire:tide_trident"

	[custom_weaponry.iceandfire_troll_weapon_trunk]
		armor_ignorance = 10.0
		hit_at_once = 3
		impact = 3.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "GREATSWORD"
		registry_name = "iceandfire:troll_weapon_trunk"

	[custom_weaponry.iceandfire_troll_weapon_trunk_frost]
		armor_ignorance = 10.0
		hit_at_once = 3
		impact = 3.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "GREATSWORD"
		registry_name = "iceandfire:troll_weapon_trunk_frost"

	[custom_weaponry.iceandfire_troll_weapon_hammer]
		armor_ignorance = 10.0
		hit_at_once = 3
		impact = 3.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "GREATSWORD"
		registry_name = "iceandfire:troll_weapon_hammer"

	[custom_weaponry.iceandfire_troll_weapon_column_frost]
		armor_ignorance = 10.0
		hit_at_once = 3
		impact = 3.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "GREATSWORD"
		registry_name = "iceandfire:troll_weapon_column_frost"

	[custom_weaponry.iceandfire_troll_weapon_column_forest]
		armor_ignorance = 10.0
		hit_at_once = 3
		impact = 3.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "GREATSWORD"
		registry_name = "iceandfire:troll_weapon_column_forest"

	[custom_weaponry.iceandfire_troll_weapon_column]
		armor_ignorance = 10.0
		hit_at_once = 3
		impact = 3.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "GREATSWORD"
		registry_name = "iceandfire:troll_weapon_column"

	[custom_weaponry.iceandfire_troll_weapon_axe]
		armor_ignorance = 10.0
		hit_at_once = 3
		impact = 3.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "GREATSWORD"
		registry_name = "iceandfire:troll_weapon_axe"

	[custom_weaponry.iceandfire_hippocampus_slapper]
		armor_ignorance = 0.0
		hit_at_once = 2
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "AXE"
		registry_name = "iceandfire:hippocampus_slapper"

	[custom_weaponry.sample]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		registry_name = "modid:registryname"

[custom_armor]

	[custom_armor.sample]
		stun_armor = 0.0
		weight = 0.0
		registry_name = "modid:registryname"

**Comment by ChaoticPhamton** [comment]
thx

**Comment by ChaoticPhamton** [comment]
> The config is no longer used for mod compatibility, you have to use a datapack

I'm trying to use different forge versions but seems to don't work with any version, how i do to make the different weapons compatible with EPF? Since i can't find the datapacks yet, i'm making an aternos server and need this working as soon as possible :(

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy. Please refer to the discord sever for this kind of issue
