### ISSUE TITLE
[Bug]: Controllable support

### ISSUE THREAD

**Issue by 911653534** [Yesssssman/epicfightmod#1297]
### Have you checked if a similar issue is already reported by someone else?

- [ ] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

i'd like to replace the left mouse button with some other key, so that i can use my gamepad conveniently. the main problem is that i can't attack in fight mode when i also use the mod named Controllable

**Comment by ChaoticPhamton** [comment]
it's the main button on mc, like the vanilla attack, the button that appears in controls are for the skill, have you tried it that way yet?

**Comment by 911653534** [comment]
Thank you very much for seeing my message, but when I use the Controllable mod and use the corresponding attack button, the behavior produced is the original attack behavior, not the special style attack in the Epic Fight mod. Maybe my description is not very clear, but I have seen other players suffer from the same problem. Can you try the Controllable mod？

**Comment by 911653534** [comment]
If the attack key in attack mode of Epic Fight mod can be displayed and modified in the key settings interface, I think it would be a great modification solution. I'm afraid my explanation is not clear, and here is the result picture after the change. Thank you for your reply again.
![1](https://user-images.githubusercontent.com/75149084/228583129-d1fb9957-08ec-4e74-9f1f-0d828c39f751.png)

**Comment by MetalKnight56** [comment]
> 

Controllable compatibility is not available yet, make sure to remove that mod for now and follow our progress as our next update should cover these bugs.

**Comment by MetalKnight56** [comment]
I'll be closing this issue when the update is released. Lets leave this open to help me remember to inclusde this on the update note.

**Comment by Blues7a** [comment]
I hope this is fixed soon

**Comment by MetalKnight56** [comment]
Issue has been fixed as of the latest commits
https://github.com/Yesssssman/epicfightmod/compare/e963d283e2ec...35e8aa9ea4ba

**Comment by EchoEllet** [comment]
> Issue has been fixed as of the latest commits [e963d28...35e8aa9](https://github.com/Epic-Fight/epicfight/compare/e963d283e2ec...35e8aa9ea4ba)

The PR #2112 fixes a compatibility issue that can be reproduced when using any controller mod + Epic fight and Shoulder surfing reloaded. This fix is related to this commit.
