### ISSUE TITLE
[Bug|Crash]: The game crashed when using optifine

### ISSUE THREAD

**Issue by RevaldoVeryCool** [Yesssssman/epicfightmod#1298]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Optifine

### Minecraft Version

1.18.2

### What happened?

I want to play with this mod but it just crashed.
Im using the not enough crash mod for the log files:
https://bytebin.lucko.me/DlaVJTVG3I
If you need an actual log file tho feel free to ask for it

**Comment by MetalKnight56** [comment]
Denied issue as we do not support closed source mods.
