### ISSUE TITLE
[Bug|Crash]:Fighting Stance Breaks after prolonged building/mining1.18.3.8

### ISSUE THREAD

**Issue by TehSpoonMan** [Yesssssman/epicfightmod#1300]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

EpicFightMod

### Minecraft Version

1.18.2

### What happened?

I have to restart the world to fix the Fighting Stance attacks and abilities not working. At some point while building my base, the attacks from the fighting stance stop working as does my dodge roll as it disconnects from my abilities book.

**Comment by TehSpoonMan** [comment]
Also continues to work if I periodically go into fight stance and roll, nut this is also me trying to see if there is anything that particularly triggers the break.

**Comment by MetalKnight56** [comment]
If you are using dawncraft, please report this issue to them. If they find the culprit of this issue, we'll fix it on our side if needed.
https://github.com/SettingDust/dawncraft-fixes
