### ISSUE TITLE
Server Side Issue

### ISSUE THREAD

**Issue by Drinkerton** [Yesssssman/epicfightmod#1301]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Server side attack animations and learned abilities not working even when the mod itself is installed showing the fight mode can be activated and all the items are unlocked when gamemode is switched to creative. 
But in a single player world the mod works flawlessly (yes i have the right mods installed into my server folder it's an exact copy paste."
- The Server is self hosted running a 1.18.2 Server Jar File with the correct latest 1.18.2 forge installer.
- Deleted all mods with fresh 1.18.2 installs of forge and server files so that EFM is the only one i test with no conflicting mods.
- Tested the 1.16 mod and forge installer versions to see if it was my 1.18.2 messing up but it turned out to also face the same exact issues.
- Tried to do load up the mod then look at logs for an issue but honestly was confused admittedly i can usually fix an issue that way but no words/phrases stuck out to me to do research on it. 
- Spent hours looking at the EFM discord, curseforge EFM mod comments, and the EFM github issues tab with no clear answer or solution.

Clearly i must be doing something wrong since i assume other people had no trouble running the mod server side or something is having trouble which i'm not knowledgable enough to understand and fix.

I'm going to drop a spark file into here and hope maybe someone has the answer or could lead me to possible solutions but if not that is pefectly fine i've been at this for a few hours now and just need to step away lol.

[spark profile.txt](https://github.com/Yesssssman/epicfightmod/files/11129489/spark.profile.txt)

**Comment by MetalKnight56** [comment]
Please provide log, mc version, forge version, epic fight version, and some footage.
