### ISSUE TITLE
[Bug|Crash]:  Freeze/Hang While exploring the world 

### ISSUE THREAD

**Issue by TryingMyBestt** [Yesssssman/epicfightmod#1304]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Log and Debug

https://gist.github.com/TryingMyBestt/d13bc36f0712d69c43bbe416f7451e41

**Comment by MetalKnight56** [comment]
Closign issue as user did not follow the support policy. Please refer to the discord server for this kind of issue.
