### ISSUE TITLE
1.12.2 Wither Skeletons causing server and client crash

### ISSUE THREAD

**Issue by Dreamms41** [Yesssssman/epicfightmod#131]
When spawning a wither skeleton to fight with the newest version of the 1.12.2 EFM, my client and server crashed.

[crash-2021-03-31_00.14.59-server.txt](https://github.com/Yesssssman/epicfightmod/files/6233757/crash-2021-03-31_00.14.59-server.txt)

**Comment by Yesssssman** [comment]
Thanks for reporting this will be fixed as soon as possible.
