### ISSUE TITLE
[Bug|Crash]: Epic Fight potentially crashing players whenever they are attacked by pillagers

### ISSUE THREAD

**Issue by Killerbee47** [Yesssssman/epicfightmod#1310]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Upon fighting Pillagers specifically, whenever some of them shoot, the client being shot immediately crashes. Screen is frozen, game freezes and becomes unresponsive. However, the server still registers the player online and they most likely die. Issue is only occuring on my Minecraft Server. 

Attached is a crash report from a player who experienced this. 

[message (2).txt](https://github.com/Yesssssman/epicfightmod/files/11206983/message.2.txt)

**Comment by MetalKnight56** [comment]
Please remove all mods and only have epic fight enabled, if the issue persistis re upload your crash log. If it doesn't then its probably not our issue and rather a mod incompatbility.

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy (OPTIFINE INSTALLED). Please refer to the discord server for this kind of issue.
