### ISSUE TITLE
[Bug|Crash]: Crash Loop on Player Death in Dawncraft Modpack

### ISSUE THREAD

**Issue by Ferisia** [Yesssssman/epicfightmod#1311]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Steps to Reproduce:
1. Run Dawncraft Modpack
2. Die

[crash-2023-04-12_12.13.29-client(1).txt](https://github.com/Yesssssman/epicfightmod/files/11214996/crash-2023-04-12_12.13.29-client.1.txt)

**Comment by MetalKnight56** [comment]
This is an issue within dawncraft. If you want this to be fixed report it to them, and if it happens to be something on our side, dawncraft developers will ask us to fix it.
