### ISSUE TITLE
[Help]: Is it possible to use Epic Fight Mod Animations on citizens/guards in Minecolonies?

### ISSUE THREAD

**Issue by uoissvd** [Yesssssman/epicfightmod#1313]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/minecolonies

### Minecraft Version

1.18.2

### What happened?

Hi,

I'm not sure whether it is possible to use epic fight mod model/animations on citizens/guards and other mobs (e.g. barbarians) in Minecolonies mod.

Unlike other mods, Minecolonies seems to use a different character model and when I try to use a datapack to apply the epic fight biped model/animations, the citizens are rendered incorrectly (like super broken).

I would appreciate if you could guide me here for a possible solution.

Thanks,

**Comment by MetalKnight56** [comment]
You might need to change the textures to fit in the vanilla UV maps (which is what we use).
