### ISSUE TITLE
[Bug]: Essentials Stops combat mode

### ISSUE THREAD

**Issue by Solvern** [Yesssssman/epicfightmod#1314]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/essential-mod

### Minecraft Version

1.18.2

### What happened?

Everything works fine before trying to invite a friend, the combat mode works flawlessly, after joining essential servers to invite a friend combat mode stops receiving inputs other than movement and disabling combat mode. It has happened consistently on multiple worlds and without any other mods.

**Comment by MetalKnight56** [comment]
Essential is a closed source mod. We do not provide support for closed source mods, if you want this to be fixed report it to them!

**Comment by Solvern** [comment]
I will do that, thanks and sorry for wasting your time.
