### ISSUE TITLE
[Bug|Crash]: Exception Ticking World

### ISSUE THREAD

**Issue by DeshiDesu** [Yesssssman/epicfightmod#1316]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

 > Cannot invoke "java.util.Map.forEach(java.util.function.BiConsumer)" because the return value of "yesman.epicfight.world.capabilities.item.CapabilityItem.getLivingMotionModifier(yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch, net.minecraft.world.InteractionHand)" is null

Crash Report:

 >  [crash-2023-04-15_12.59.19-server.txt](https://github.com/Yesssssman/epicfightmod/files/11240880/crash-2023-04-15_12.59.19-server.txt)

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy, please refer to the discord server for this kind of issue.
