### ISSUE TITLE
[Bug|Crash]: Server crush.

### ISSUE THREAD

**Issue by CinosTheUberhedge** [Yesssssman/epicfightmod#1317]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Well, i started an Aternos server with this mod, when i appeared in the world, it was a zombie with a wooden sword in his hands next to me, then he hit me and my server crushed.
Crash log:
https://mclo.gs/he7OUJ9

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy. Please refer to the discord server for this kind of issue.
(Wrong forge version)
