### ISSUE TITLE
[Bug|Crash]: World crashing randomly when using epic fight

### ISSUE THREAD

**Issue by PlayerBosta** [Yesssssman/epicfightmod#1319]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

When using epic fight my world randomly crashes after like 5 minutes, as it says in the title.
[crash-2023-04-22_16.07.54-client.txt](https://github.com/Yesssssman/epicfightmod/files/11302140/crash-2023-04-22_16.07.54-client.txt)
[latest.log](https://github.com/Yesssssman/epicfightmod/files/11302141/latest.log)

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy. Please refer to the discord server for this kind of issue.
