### ISSUE TITLE
Crossbow animation for 1.12, perfect use for modded ranged weapons like crossbows or guns

### ISSUE THREAD

**Issue by barttraeger** [Yesssssman/epicfightmod#132]
Right now only the BOW animation is available in 1.12 for any ranged weapons.
When using a crossbow from e.g. Spartan Weaponry the mod uses the bow animation,
which looks very weird.
The crossbow animation from the newer versions of Epic Fight Mod would fit in perfectly.
Also for guns like the Immersive Engineering revolver this animation fits way better,
since the gun would be held in front of the player constantly.

I really enjoy this mod, you did a fantastic job, thank you very much!

**Comment by hitmanssilent** [comment]
With the guns theme I agree, the animation is perfect for some mods that add guns, other mods that could be perfect with that animation are also the mods of, Techguns mod, MrCrayfish's Gun Mod and Vic's Modern Warfare Mod.

**Comment by Yesssssman** [comment]
Since there is no crossbow in 1.12.2, It's very hard to make it compatible because there's no way to recognize that they're crossbow. I'll post it later if I find the solution.
