### ISSUE TITLE
[Bug|Crash]: Oculus Incompatibility

### ISSUE THREAD

**Issue by PPlayer31** [Yesssssman/epicfightmod#1320]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Oculus

### Minecraft Version

1.16.5

### What happened?

[crash-2023-04-23_13.23.04-client.txt](https://github.com/Yesssssman/epicfightmod/files/11304199/crash-2023-04-23_13.23.04-client.txt)
Epic Fight Incompatibility with Oculus. Crashes extremely randomly. Access to the world is permitted until it crashes...

**Comment by Kasualix** [comment]
https://github.com/Yesssssman/epicfightmod/issues/1161
duplicate
