### ISSUE TITLE
[Crash]: Game crashes when using Build Tool from Structurize

### ISSUE THREAD

**Issue by BraveCaperCat2** [Yesssssman/epicfightmod#1321]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/structurize

### Minecraft Version

1.16.5

### What happened?

When using the build tool from structurize, the game sometimes crashes - it is this mod definitely as of this line in the log (listed below the line):
java.lang.NullPointerException: Rendering entity in world
	at yesman.epicfight.client.events.engine.RenderEngine$Events.renderLivingEvent(RenderEngine.java:430) ~[?:16.6.4]
[latest.log](https://github.com/Yesssssman/epicfightmod/files/11325207/latest.log)
There is also no reason for "1.18.2" to be listed in the "Minecraft Version" property of the report, as 1.18.2 is not supported by the mod - see:
![Screenshot 2023-04-25 182653](https://user-images.githubusercontent.com/113925022/234355436-35bb639a-a36a-4fc8-89e7-5758756eca8a.png)
The game version (shown next to a controller icon) is 1.16.5, meaning that the latest version is for 1.16.5.

**Comment by MetalKnight56** [comment]
This is an issue with minecolonies, they've said they won't patch this as 1.16.5 is dicontinued on their side and so on ours. Either play on 1.18.2 or wait for new versions to be released. Also i don't get what you mean byt he mod being labeled as 1.16.5 Thats just weird labeling from CurseForge and we can't do anything about it as far as i know. Look at the FAQ on our page before doing these reports.
