### ISSUE TITLE
[Bug|]: Combat mode doesn't make me attack

### ISSUE THREAD

**Issue by Crida117** [Yesssssman/epicfightmod#1322]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

When I enter combat mode it doesn't make me attack anything, like it doesn't give the animation and the attack, sometimes it fixes but it almost alway doesn't work

**Comment by MetalKnight56** [comment]
Do you have any other mods enabled ? Can you provide me with your forge version, minecraft version and epic fight version please?

**Comment by EthanLightning** [comment]
Im having the same issue in 1.18,2. I narrowed it down to this mod https://www.curseforge.com/minecraft/mc-mods/primordialexpanseskills, Primordial Expanse Skills. While its installed, I can make the first attack normally after going into combat mode, but after that there is no animation, but the attack cooldown still shows up. That mod adds melee skills, so thats probably whats causing it.

**Comment by Crida117** [comment]
> Do you have any other mods enabled ? Can you provide me with your forge version, minecraft version and epic fight version please?

I'm using the latest version of both forge and the mod on 1.18.2 the problem begins when i press esc or start a lan world

**Comment by MetalKnight56** [comment]
> > Do you have any other mods enabled ? Can you provide me with your forge version, minecraft version and epic fight version please?
> 
> I'm using the latest version of both forge and the mod on 1.18.2 the problem begins when i press esc or start a lan world

Are you able to provide footage? And if possible a log?

**Comment by Chillayy** [comment]
I'm having the same issue, here's what's happening for me:

https://medal.tv/games/minecraft/clips/1rceesVfky8E7i/d13375gRw8qB?invite=cr-MSxJWjcsODgyNjc2NCw

log: 
https://hastebin.skyra.pw/oguxivanev.yaml

**Comment by ajioe1111** [comment]
same problem 1.19.2
