### ISSUE TITLE
[Bug|Crash]: Crash

### ISSUE THREAD

**Issue by Aabaddon** [Yesssssman/epicfightmod#1324]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

It crashed a bunch of times, i tried removing mods that i thought where causing the problem (because i actually want to keep using epic fight and is the reason im making the modpack for me and my friends) i dont know much about mods or programing so im sorry if this mentions some type of incompatibility im not aware of.
[crash-2023-05-06_20.28.23-server.txt](https://github.com/Yesssssman/epicfightmod/files/11413711/crash-2023-05-06_20.28.23-server.txt)
[crash-2023-05-06_20.00.54-server.txt](https://github.com/Yesssssman/epicfightmod/files/11413712/crash-2023-05-06_20.00.54-server.txt)

**Comment by MetalKnight56** [comment]
Sounds like an issue with dungeons lib, what version of forge is your server on again?
