### ISSUE TITLE
[HELP] Model Error

### ISSUE THREAD

**Issue by FirefliTheWitch** [Yesssssman/epicfightmod#1325]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Better Animal Models

### Minecraft Version

1.16.5

### What happened?

Im aware of the mod thats causing the problem, its an incompatibility between EFM and Better Animal Models. It completely breaks both spider and endermen models, which is deeply saddening. I've tried to backport for both mods because I know that fixed it before but I cant figure out what specific version of each mod combined fixes it, so I was wondering if there was an easier fix other than just getting rid of Epic Fight?
![image_2023-05-08_010154429](https://user-images.githubusercontent.com/132872011/236738096-a128a017-f881-41c7-8262-ecaa930fa304.png)

**Comment by FirefliTheWitch** [comment]
I got it to be a little better, no missing textures but the eyes are still floating above the head as well as having eyes on their normal fixed models lolol, much better let me know if you need this fix!

**Comment by Globalfirestorm10** [comment]
This may be late, but i'd recommend you find a resourcepack to delete mob animations on the epic fight discord server, delete all files except for spider and cave spider ones, and then load the game up with that, as epicfight doesn't work with mods that change the mob or play models
