### ISSUE TITLE
[Bug]: Skill render problems in the server

### ISSUE THREAD

**Issue by 1625926165** [Yesssssman/epicfightmod#1328]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

When I use weapon skills on the server and rotate the camera Angle, the screen shakes like crazy.
The reason for this trigger is that turning the cast Angle while casting a weapon skill causes the cast direction to change to the direction after the cast Angle is turned.
It won't trigger in single player mode because it won't do what I said above, it's the opposite of what I said above, turning the Angle doesn't change its direction.
It only appears when tachi and dagger second animation，This doesn't seem to be the case with other weapon types.
I don't know if this is caused by the Mod.

![1](https://github.com/Yesssssman/epicfightmod/assets/102323087/e132d2af-b6b0-49fb-95db-9f456bb95747)
![2](https://github.com/Yesssssman/epicfightmod/assets/102323087/c72f0e6c-6d1d-4d10-82b3-3b9f73063fc4)

**Comment by MetalKnight56** [comment]
Closing issue as its fixed on 18.5.0.1 which currently is only available to Beta Testers
