### ISSUE TITLE
[Bug]: Elytra wear on the body Render position error

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1329]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

 Elytra wear on the body Close the game Restart the game Enter the world appear Render position error
![2023-05-28_16 36 49](https://github.com/Yesssssman/epicfightmod/assets/130232431/e65f2de0-38a4-4e93-89ab-cf1a49719f8e)
![2023-05-28_16 36 26](https://github.com/Yesssssman/epicfightmod/assets/130232431/ded9f88b-f386-4d08-8181-ecb19783f280)
Minecraft 1.18.2 and Minecraft 1.16.5 Epic Fight latest version have the same problem

**Comment by fzrdwa123456** [comment]
My English is not very good and I use a translator so it might be a little strange to express

**Comment by Overlegened** [comment]
Do you have any other mods installed? Could be caused by a Mod incompatibility

**Comment by fzrdwa123456** [comment]
Nothing else

**Comment by fzrdwa123456** [comment]
> Do you have any other mods installed? Could be caused by a Mod incompatibility

No other mods are installed

**Comment by fzrdwa123456** [comment]
> Do you have any other mods installed? Could be caused by a Mod incompatibility

After I found this problem, you did not fix it in the subsequent updates and no one gave feedback

**Comment by fzrdwa123456** [comment]
> Do you have any other mods installed? Could be caused by a Mod incompatibility

This bug has been around for a long time

**Comment by MetalKnight56** [comment]
> > Do you have any other mods installed? Could be caused by a Mod incompatibility
> 
> No other mods are installed

Interesting response cuz i see modded plants on the desert on those pictures. This is probably caused by the magic staff/wand mod, we will not solve this issue, if they want they can contact us then we'll work this out, but without their contribution we won't bother fixing this.

**Comment by fzrdwa123456** [comment]
> > > 有没有安装其他的mod？可能是由Mod不兼容引起的
> > 
> > 
> > 没有安装其他模块
> 
> 有趣的回应，因为我在那些照片上看到了沙漠中的改良植物。这可能是由魔法杖/魔杖模式引起的，我们不会解决这个问题，如果他们想他们可以联系我们，我们会解决这个问题，但是没有他们的贡献，我们不会去解决这个问题。

No mod That's just a resource pack

**Comment by fzrdwa123456** [comment]
> > > 有没有安装其他的mod？可能是由Mod不兼容引起的
> > 
> > 
> > 没有安装其他模块
> 
> 有趣的回应，因为我在那些照片上看到了沙漠中的改良植物。这可能是由魔法杖/魔杖模式引起的，我们不会解决这个问题，如果他们想他们可以联系我们，我们会解决这个问题，但是没有他们的贡献，我们不会去解决这个问题。

I didn't lie to you

**Comment by MetalKnight56** [comment]
> I didn't lie to you

Have you recently installed optifine?

**Comment by fzrdwa123456** [comment]
> > 我没有骗你
> 
> 您最近安装了optifine吗？

no optifine

**Comment by fzrdwa123456** [comment]
> > 我没有骗你
> 
> 您最近安装了optifine吗？

You should fix this bug It's been around for a long time

**Comment by fzrdwa123456** [comment]
> > 我没有骗你
> 
> 您最近安装了optifine吗？

I didn't install optifine

**Comment by MetalKnight56** [comment]
> > > 我没有骗你
> > 
> > 
> > 您最近安装了optifine吗？
> 
> You should fix this bug It's been around for a long time

Yeah there is no way to know what is causing this, please, do a fresh installation of minecraft and try it again. Mind that you shouldn't use any other mods aside epic fight, if the issue persists let me know.

**Comment by fzrdwa123456** [comment]
> > > > 我没有骗你
> > > 
> > > 
> > > 您最近安装了optifine吗？
> > 
> > 
> > 你应该解决这个问题，它已经存在很长时间了
> 
> 是的，没有办法知道这是什么原因造成的，请重新安装minecraft，然后再试一次。请注意，除了史诗战斗，你不应该使用任何其他模式，如果问题仍然存在，请让我知道。

Your method I've tried the bug still triggers

**Comment by MetalKnight56** [comment]
> > > > > 我没有骗你
> > > > 
> > > > 
> > > > 您最近安装了optifine吗？
> > > 
> > > 
> > > 你应该解决这个问题，它已经存在很长时间了
> > 
> > 
> > 是的，没有办法知道这是什么原因造成的，请重新安装minecraft，然后再试一次。请注意，除了史诗战斗，你不应该使用任何其他模式，如果问题仍然存在，请让我知道。
> 
> Your method I've tried the bug still triggers

Then i have no idea whats causing it.

**Comment by fzrdwa123456** [comment]
> > > > > > 我没有骗你
> > > > > 
> > > > > 
> > > > > 您最近安装了optifine吗？
> > > > 
> > > > 
> > > > 你应该解决这个问题，它已经存在很长时间了
> > > 
> > > 
> > > 是的,没有办法知道这是什么原因造成的,请重新安装minecraft，然后再试一次。请注意,除了史诗战斗,你不应该使用任何其他模式,如果问题仍然存在,请让我知道。
> > 
> > 
> > 我试过了你的方法，但还是会触发bug
> 
> 我不知道是什么引起的。

Hey, when you press "E" to open the inventory, it seems to disappear, maybe because you modified the player model

**Comment by fzrdwa123456** [comment]
> > > > > > 我没有骗你
> > > > > 
> > > > > 
> > > > > 您最近安装了optifine吗？
> > > > 
> > > > 
> > > > 你应该解决这个问题，它已经存在很长时间了
> > > 
> > > 
> > > 是的，没有办法知道这是什么原因造成的，请重新安装minecraft，然后再试一次。请注意，除了史诗战斗，你不应该使用任何其他模式，如果问题仍然存在，请让我知道。
> > 
> > 
> > Your method I've tried the bug still triggers
> 
> Then i have no idea whats causing it.

It's possible that you modified the player model to cause problems and maybe you should try the method I described

**Comment by MetalKnight56** [comment]
> > > > > > > 我没有骗你
> > > > > > 
> > > > > > 
> > > > > > 您最近安装了optifine吗？
> > > > > 
> > > > > 
> > > > > 你应该解决这个问题，它已经存在很长时间了
> > > > 
> > > > 
> > > > 是的，没有办法知道这是什么原因造成的，请重新安装minecraft，然后再试一次。请注意，除了史诗战斗，你不应该使用任何其他模式，如果问题仍然存在，请让我知道。
> > > 
> > > 
> > > Your method I've tried the bug still triggers
> > 
> > 
> > Then i have no idea whats causing it.
> 
> It's possible that you modified the player model to cause problems and maybe you should try the method I described

You didn`t discribe any methods, 2 yeah we change the player model so what, if you dislike that, go play other mods instead. I`m locking this post, and do not report this issue again on this repo again, otherwise i`ll block your account from making new posts here.
