### ISSUE TITLE
[Bug]: can't see map in first person view when 'filter animation' option is on

### ISSUE THREAD

**Issue by Spo0on** [Yesssssman/epicfightmod#1330]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

I like to set the `filter animation` option to off in order to have epic fight animation always on, but it implies that i can't see the map when in first person view.
It would be great if there was an option to enable filter animation just for specific items, or for first person view only (since animation is useless in first person).

**Comment by MetalKnight56** [comment]
You can use the auto mining mode or auto combat mode to auto switch between the two depending on what item you are holding, but we plan on doing an animation for you to hold the map, so this should be fixed in the next update.

**Comment by Yesssssman** [comment]
Fixed in 18.5.12
