### ISSUE TITLE
[Bug]: First person render issue

### ISSUE THREAD

**Issue by lab3** [Yesssssman/epicfightmod#1331]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

I'm posting here as it looks like a compat issue with playeranimator and epicflight

Summary: In first person view when casting a spell the players head is rendered in a weird position.

Here is the original bug report posted to our issue tracker with screenshot..
https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/52

**Comment by MetalKnight56** [comment]
First person will be overhauled next update.

**Comment by MetalKnight56** [comment]
Actually, i'm not sure if we'll be able to fix this, this is an issue with playeranimator and epic fight and both mods use different bend implementations that are quite difficult to merge together so they work. I'll close this issue for now, and later resume this if i get an answer from the player animator devs.

**Comment by lab3** [comment]
Is there a way to disable any part of the animation that we could control through a compat?  This would allow us to detect this mod is installed and then disable that portion of the animation during a cast animation sequence.
