### ISSUE TITLE
[Bug]The incompatibiliry issue with mod based on geckolib

### ISSUE THREAD

**Issue by 1234DDDs** [Yesssssman/epicfightmod#1332]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

geckolib

### Minecraft Version

1.18.2

### What happened?

the mod i made based on geckolib has occurred an incompatibility issue(texture error) when i using epicfight mod, how can i solve it
![RDLX` _2}H}3{HL CDGKRZ6_tmb](https://github.com/Yesssssman/epicfightmod/assets/114791211/62aa999d-e752-4353-a602-c503e6e9a252)
![_0}R4UXOBKUK3VZN8K0S8U4_tmb](https://github.com/Yesssssman/epicfightmod/assets/114791211/eb4f845d-b11c-43b7-b205-ea8a9c31517f)

**Comment by MetalKnight56** [comment]
Known issue, we'll soon have docs explaining how you can fix this.
