### ISSUE TITLE
option to turn off blood and blood splatter on death

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [Yesssssman/epicfightmod#1333]
### Have you checked if a similar issue is already reported by someone else?

- [x] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

i don't want blood in my gameplay. on death, there is blood splatters on screen, which is very scary and violent, and when you hit mobs. there are blood particles, which indeed are too violent for me.

**Comment by MetalKnight56** [comment]
You can make a resourcepack that changes the textures of blood to transparent textures. It shouldn't be too hard, but we'll consider that. Btw, i'm pretty sure there's already an option for that, but you'll need to check for yourself.

**Comment by MetalKnight56** [comment]
Yep there is, its inside epic-fight-client.toml

**Comment by SonicTheHedgehog58987276** [comment]
in my config the offgore rule is set to true, but there is dark green blood particles still.

**Comment by MetalKnight56** [comment]
> in my config the offgore rule is set to true, but there is dark green blood particles still.

dark green blood? Can you show me with a print screen?

**Comment by SonicTheHedgehog58987276** [comment]
can you update it to 1.19.4 first?
