### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by dodododododdodo** [Yesssssman/epicfightmod#1334]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Medieval minecraft modpack (forge)

### Minecraft Version

1.16.5

### What happened?

After 1 minute the game crashes and it gets fixed when uninstalling the mod, but i´m used to playing with epic fight and i want to know if there is a way to fix it, the crash log i get is https://bytebin.lucko.me/M9mrgwE4do, sometimes the message is pose stack not empty

**Comment by MetalKnight56** [comment]
Way too many mods, there's no way i figure this out, remove them all and slowly add them back to find which one is causing the issue. If you want to play with epic fight make sure its enabled since the start.
