### ISSUE TITLE
[Bug|Crash]: CRASH TO PUNSH ENTITY

### ISSUE THREAD

**Issue by GGoldennn** [Yesssssman/epicfightmod#1336]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

EPIC FIGTH MOD

### Minecraft Version

1.16.5

### What happened?

Good morning, I wanted to report an error of the EPIC FIGTH MOD when I hit an entity with the fight mode, the game crashes. It should be noted that I use the latest version and I do not use more mods, only the epic figth mods

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy. Please refer to the discord server for this kind of issue.
