### ISSUE TITLE
Incompatibility with "Dungeons gear mod" and "Optifine Shaders"

### ISSUE THREAD

**Issue by disastercube** [Yesssssman/epicfightmod#134]
**Dungeons Gear Mod Issue / 1.16.5** 
------------------
When playing with Epic Fight Mod and Dungeons Gear Mod together some texture problems arise with Dungeons Gear armor and weapons in hand placement. While textures look fine inside the inventory, outside in F5 mode you can see that the textures are all messed up.

**_How it looks inside inventory: (looks fine even with the mod)_**
![1](https://user-images.githubusercontent.com/62697421/113132023-32917600-921e-11eb-9203-1d475ae7cd4b.png)

**_How it looks in F5 mode: (messed up armor texture and gauntlet wrongly placed)_**
![2](https://user-images.githubusercontent.com/62697421/113132091-489f3680-921e-11eb-8e31-40cc493eafde.png)

**_How it should look:_**
![3](https://user-images.githubusercontent.com/62697421/113132152-5c4a9d00-921e-11eb-92da-c1c5694f1df4.png)

**Optifine Shader Issue / 1.16.5_HD_U_G7** 
------------------
When using shaders with Epic Fight Mod the textures of added weapons are missing.

**_Example of Katana:_**
![k](https://user-images.githubusercontent.com/62697421/113132585-f1e62c80-921e-11eb-8f21-21ba34472353.png)

**_Example of inside the inventory:_**
![s](https://user-images.githubusercontent.com/62697421/113132659-0d513780-921f-11eb-9aa6-80752e44b9aa.png)

**Comment by disastercube** [comment]
As for the "bictures below" do you mean Optifine problems ? If so I did restart minecraft many times and didn't work.

**Comment by Quizer9O8** [comment]
Any idea what makes Dungeons gear mod's armor different from Ice & Fire's armor? I&E Used to have the same issue with armor rendering but recently it got fixed on their side somehow after a few updates. Maybe if you three guys get together I'm sure you'll find a solution.

**Comment by MetalKnight56** [comment]
Patched Dungeon Gear mod here: https://www.planetminecraft.com/data-pack/epic-fight-dungeon-gear-patch/
