### ISSUE TITLE
[Crash]: Epic Fight crashes with many mods on logging to modded server

### ISSUE THREAD

**Issue by 9ghtX** [Yesssssman/epicfightmod#1340]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Any additional mod, except (for this report) Unearthed.

### Minecraft Version

1.18.2

### What happened?

With any additional mod (except of Unearthed for this report; without it or any other client connects successfully) EF crashes when I try to connect to my modded server with this report:
[crash-2023-06-26_12.43.39-client.txt](https://github.com/Yesssssman/epicfightmod/files/11864204/crash-2023-06-26_12.43.39-client.txt)

It looks like EF can't get some player entity state. Maybe it's about timeout of loading entity or something like that?

In singleplayer everything works fine.

**Comment by 9ghtX** [comment]
For mention (maybe that's important) what mods I tried to add:
- Unearthed (with Hyla as dependency)
- Exotic Birds
- Advanced Chimneys (with Forge Endertech as dependency)

Also have a few waiting for adding to modpack:
- Custom Dungeon Loot
- Illuminations
- Jump Boat
- Missing Wilds
- Lootr
But I won't try, cause think it will crash as it did

**Comment by MetalKnight56** [comment]
Yeah you need to figure out which mod is causing this. Disable all mods, and slowly add them back, make sure you have epic fight enabled from the start, then when you find the one causing issues, you update me.

**Comment by 9ghtX** [comment]
It's not about specific mod. It's about count of mods. Cause I tried to put each of this mods from above one at a time. And them all crash client.
And it doesn't matter what kind of mod I install. It can be a client-only mod or mod that adds items, mobs or/and blocks. So I'm sure it's EFs' problem

**Comment by MetalKnight56** [comment]
> It's not about specific mod. It's about count of mods. Cause I tried to put each of this mods from above one at a time. And them all crash client. And it doesn't matter what kind of mod I install. It can be a client-only mod or mod that adds items, mobs or/and blocks. So I'm sure it's EFs' problem

Well its basically impossible to figure whats happening if you don't provide which set of mods is causing this. I'm not gonna do the testing for you, and i doubt you have made what i told you, so again, either do what i'm asking you to do so we can solve the issue or i'm closing this down as denied and won't solve.

**Comment by 9ghtX** [comment]
The list of mods is down below in crash report. If you need this in other format, so here it is - 
[modlist.txt](https://github.com/Yesssssman/epicfightmod/files/11897933/modlist.txt)
It's different for now, but still crashes on entering server with same error with EF.

**Comment by MetalKnight56** [comment]
> 

This is not what i asked, again, i don't care about your modpack or whatever you are trying to do, there may be one or two mods causing the issue, its not ALL of those that are causing the issue, so one last time i ask you, remove them all and slowly add them back.
