### ISSUE TITLE
[Bug|No textures]: 

### ISSUE THREAD

**Issue by starfox230** [Yesssssman/epicfightmod#1342]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

No other mods or shaders installed, game is completely broken, no top layer of dirt, I'm basically floating and looking at stone below my feet, the player hand is gone, 3rd person there is no me, no mobs are visible, my game just looks like a mess. I'm not using any resource packs besides the default and 3d armor.

**Comment by MetalKnight56** [comment]
> 

I need footage, can't guess whats happening, and also i need your forge version.
