### ISSUE TITLE
[Bug| Client and server has same file version but it says it doesn't

### ISSUE THREAD

**Issue by ghost** [Yesssssman/epicfightmod#1343]
### Have you checked if a similar issue is already reported by someone else?

- [x] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [x] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [x] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

### Minecraft Version

1.18.2

### What happened?

it says the following mod versions does not match with the server even though it does, version 18.3.7 are both installed in the client and the server but it keeps popping up and saying it does not match
![358090833_633459082176435_6646528744928589765_n](https://github.com/Yesssssman/epicfightmod/assets/138453963/a9c04623-0617-4819-8599-db64d1a12c51)
![358090833_633459082176435_6646528744928589765_n](https://github.com/Yesssssman/epicfightmod/assets/138453963/95be24de-1d9e-4de7-b2d1-4f6d53258335)

**Comment by MetalKnight56** [comment]
We need the server logs to actually see whats going on, this is useless.
