### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by cobaltlol** [Yesssssman/epicfightmod#1345]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [x] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

I created my own modpack and when i switch to combat mode and try to kill something (almost always its a pillager wielding a crossbow for some reason) the game's TPS freezes and i cant attack anymore, no other mobs move anymore, can't eat and no blocks drop when being mined. The game doesn't crash though only that the TPS freezes.

**Comment by cobaltlol** [comment]
Also it doesn't freeze every time, it seems to randomly pick what pillager with a crossbow will cause my tps to freeze

**Comment by cobaltlol** [comment]
Here's a video to show what happens
https://github.com/Yesssssman/epicfightmod/assets/109155765/bbabf7f8-bfc6-4124-9475-d4e39e34e163

**Comment by MetalKnight56** [comment]
Probably wrong forge version. Closing issue as 1.16.5 is no longer supported.
