### ISSUE TITLE
[Bug|ConnectionClosed]: When player attacks an entity no particle or sound files are found, thus kicking the player.

### ISSUE THREAD

**Issue by MosuRikuTenpi** [Yesssssman/epicfightmod#1346]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight Mod

### Minecraft Version

1.16.5

### What happened?

Pretty much (this was on a test server) upon the player entered battle mode and an entity such as a zombie was hit via left click or special attack, game would kick with message Internal Server Error.
Steps:
1. Get any weapon (ideally epicfight weapons)
2. find your mob of choice
3. left click and hit them
4. server should kick saying "Internal Server Error" (btw the console as far as I'm aware fails due to missing files, couldnt find where they were on the wiki)
5. Enjoy the bug! or dont... idk

**Comment by MetalKnight56** [comment]
Probably an issue with wrong forge version. Denied issue, 1.16.5 no longer will be supported.
