### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by CakeGooooo** [Yesssssman/epicfightmod#1347]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

This mod brings me the feeling of 《Sekiro:ShadowsDieTwice》, but there are big problems in the connection and fluency of the movements, or for example, the endurance consumption is relatively large when tumbling, and it is difficult to return the physical strength through learning the skill book, so I want to know. Can you change the size of the endurance value to make it smoother during combat, and if so, how?

**Comment by MetalKnight56** [comment]
What do you mean with endurance? You talking about the stamina bar?

**Comment by CakeGooooo** [comment]
It is the long bar shown in the lower right corner, I think it should be a stamina bar, when tumbling will consume a lot of stamina, is there any way to modify the value of stamina, or reduce the stamina consumption of tumbling？
