### ISSUE TITLE
[Bug|Crash]: I would like to know how to use Blender to expand more model animations

### ISSUE THREAD

**Issue by Jun-Craft** [Yesssssman/epicfightmod#1348]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

https://github.com/Yesssssman/epicfightmod/wiki/Blender-Basics-and-Tips-and-Tricks

The relevant page of WIKI is empty
How to use Blender to edit EpicFight model animations?

**Comment by MetalKnight56** [comment]
This page is still being worked on. For now search for youtube tutorials on how to do that.
