### ISSUE TITLE
[Bug]: incompatible with PlayerRevive

### ISSUE THREAD

**Issue by cpm9** [Yesssssman/epicfightmod#1351]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/playerrevive

### Minecraft Version

ANY

### What happened?

If you die while in fight mode with the player revive mod instead of being stuck and waiting for the counter to elapse or for another player to revive you, you have the ability to continue to move around and fight and kill other players and mobs. This is pretty game breaking as it makes you invincible for a period of time. I'd love to use your mod in combination with player revive. I saw an old closed issue about it but this is existing in the latest 1.16.5 versions of both mods and latest forge verison. Cheers!

**Comment by MetalKnight56** [comment]
You should ask the player revive developer to contact us so we can help him fix any potential issues.

**Comment by nitpum** [comment]
Any update? they are replied here https://github.com/Yesssssman/epicfightmod/issues/1090#issuecomment-1193801238

**Comment by Yesssssman** [comment]
Fixed in 20.8.3
