### ISSUE TITLE
[Crash]: incompatible with MineColonies

### ISSUE THREAD

**Issue by cpm9** [Yesssssman/epicfightmod#1352]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/minecolonies

### Minecraft Version

1.16.5

### What happened?

Description:
It appears to be related to rending an armor stands in the MineColonies ghost/preview structure. Placing a Armor Stand normally does not cause the crash.

Replication:
1. The quickiest way to replicate is create a new creative singleplayer world
2. Spawn two MineColonies items from the creative menu (Build Tool & Town Hall)
3. Right click the Build Tool on the ground and switch from Decoration to Town Hall & switch to "medieval oak"
4. The crash will occur when switching from town hall level 3 to level 4

Image:
![epicfightminecolonies](https://github.com/Yesssssman/epicfightmod/assets/82549089/8f22fab7-ffd6-4342-bd84-4e189a76970f)

Latest log:
[latest.log](https://github.com/Yesssssman/epicfightmod/files/12076709/latest.log)

Crash report:
[crash-2023-07-17_23.51.00-client.txt](https://github.com/Yesssssman/epicfightmod/files/12076712/crash-2023-07-17_23.51.00-client.txt)

Mod List:
- forge-1.16.5-36.2.39
- EpicFight-16.6.4
- minecolonies-1.16.5-1.0.978-RELEASE
- structurize-1.16.5-1.0.418-ALPHA

**Comment by MetalKnight56** [comment]
Closing issue as user did not read the support policy.

**Comment by RagexPrince683** [comment]
LOL bro this is an actual issue

**Comment by sentwayfarer** [comment]
> LOL bro this is an actual issue

This post is from mid 2023, and was an issue in 1.16.5. If it was still an issue, you would report it again. We do not support any version below 1.20.1 anymore.

**Comment by RagexPrince683** [comment]
I'm not reading the entire bible to report an issue. Sorry. Your mod is not that important.

**Comment by guivnf** [comment]
> I'm not reading the entire bible to report an issue. Sorry. Your mod is not that important.

So is your issue. We won't commit to fixing something if you won't commit to reading a 5 line guide on how not to mess our github issue report hub.

**Comment by RagexPrince683** [comment]
> > I'm not reading the entire bible to report an issue. Sorry. Your mod is not that important.
> 
> So is your issue. We won't commit to fixing something if you won't commit to reading a 5 line guide on how not to mess our github issue report hub.

Let's settle down okay? Why does epic fight need a render override or mixin or whatever for an armor stand in the first place? 

Moreover why does the armor stand not consider whether or not it may or may not exist? I'm not filling out your webmd form tier github issue report just to make a issue for you to inevitably close it because you're clearly a control freak. I already do enough modding to know I don't need a entire medical support form to let people report issues over a minecraft mod.

**Comment by Forixaim** [comment]
Hi, I just want to let you know that.

1. We do not have a mixin with Armor Stands and we don't even touch it.

2. If you still have complaints please open a new issue and send as much info as possible.

3. The form is meant for organization purposes and if you think that we will inevitably close it you may have to think about your issue again.

Thank you for your time.
This Issue will be locked.

**Comment by guivnf** [comment]
> Moreover why does the armor stand not consider whether or not it may or may not exist? I'm not filling out your webmd form tier github issue report just to make a issue for you to inevitably close it because you're clearly a control freak. I already do enough modding to know I don't need a entire medical support form to let people report issues over a minecraft mod.

It's not that deep, just don't use the mod... We're not fixing a 1.16.5 issue that's already been fixed on newer versions just cuz some rando like you decided to revive an old issue thread lmao. Go outside for a bit, breath some fresh air and come back, this is just a cool mod for a block game, we don't owe you anything and we don't work for you, you should be glad we're even answering to this.
