### ISSUE TITLE
[Bug|Crash]:  EpicFight attributes are resetting after leaving and returning to the world

### ISSUE THREAD

**Issue by qVoidreaver** [Yesssssman/epicfightmod#1354]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

So... I'm creating a kind of "classes" within the game using FTB Quests, and when completing a certain quest, a command will be executed changing the player's attributes (which in this case I would change the attributes that epicfight makes available). But whenever I change the attributes and exit and then enter the game, the attributes go back to the default value and not the way I left it.

I believe there is a bug that causes the game attributes to return to default when the player enters and exits the game because no other mod that provides other attributes does the same.

I honestly don't know what to do (i looked in the files and in the configs), it kind of made my modpack stop in time. If there is any way to resolve this, please let me know. And no, datapacks are not the solution, as each player must have their own attribute and not something fixed for everyone

**Comment by MetalKnight56** [comment]
Remove all mods except epic fight and ftb quests and its dependencies and try again, if it continues, i`ll need some footage of it.

**Comment by qVoidreaver** [comment]
> Collaborator

It still goes on, and apparently it's only when the "stamina" attribute is modified 

I made a video that shows what happens

 https://youtu.be/6_fk8JZLsW0

**Comment by Yesssssman** [comment]
Well, it's been a very long time ago and I don't know if you would see this message but the bug will be fixed in the next epic fight update but only in 1.20.1. Sorry for the late reply.
