### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by faerheart** [Yesssssman/epicfightmod#1355]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/brass-armory

### Minecraft Version

1.18.2

### What happened?

attempting to use the Golden Spear's throwing feature after assigning it EFM values through datapacks causes the game to visually glitch and become unplayable

**Comment by MetalKnight56** [comment]
Closing issue as 1.16.5 is no longer supported.
