### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Smoker120900** [Yesssssman/epicfightmod#1356]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/weapon-leveling

### Minecraft Version

1.18.2

### What happened?

when i enter combat mode weapons stop gaining experience, i don't know if this is an issue with the coding of both mods or if it is something else

**Comment by MetalKnight56** [comment]
Check if it has been fixed on the beta

**Comment by MetalKnight56** [comment]
Fixed in beta 18.5.0.16. Available for now only to beta testers.
