### ISSUE TITLE
[Bug|Crash]: Crash with JEA

### ISSUE THREAD

**Issue by ghost** [Yesssssman/epicfightmod#1360]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Just Enough Advancements

### Minecraft Version

1.16.5

### What happened?

https://github.com/MelanX/JustEnoughAdvancements/issues/9

**Comment by MetalKnight56** [comment]
I'm pretty sure this has been fixed, but i'll check it as soon as i can
