### ISSUE TITLE
[Bug|Crash]: Crash due to attack

### ISSUE THREAD

**Issue by TsuneZebra** [Yesssssman/epicfightmod#1361]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Forge version 36.2.34, mod version 16.6.4, directly crashes when attacking MOBS, no other mod, single epic fight, error message: java.lang.NoSuchMethodError: net.minecraft.entity.Entity.getDimensionsForge(Lnet/minecraft/entity/Pose;) Lnet/minecraft/entity/EntitySize;

**Comment by MetalKnight56** [comment]
Closing issue as user violated the support policy. Please refer to the discord server for these kinds of issues.
