### ISSUE TITLE
the healthbar and pointer does not show for certain mobs

### ISSUE THREAD

**Issue by malikcuh** [Yesssssman/epicfightmod#1362]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

epic fight mod

### Minecraft Version

1.18.2

### What happened?

the healthbar and marker

**Comment by LGamingOfficial** [comment]
what about the healthbar and marker? you want to turn them on? off? 

you can do so in the configuration settings via either game or files.

**Comment by MetalKnight56** [comment]
Footage needed
