### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by NightmareWRLD** [Yesssssman/epicfightmod#1364]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Incompatibility with vampirism, when vampires are out of combat they return to vanilla animations. Advanced vampires and etc have distorted skins.

**Comment by MetalKnight56** [comment]
footage missing

**Comment by MetalKnight56** [comment]
Closing issue as ticket expired.
