### ISSUE TITLE
[Bug|Crash]: game crash with error code 1 with nothing else.

### ISSUE THREAD

**Issue by someguyfromoverthere** [Yesssssman/epicfightmod#1365]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Using the MultiMC launcher, I created an instance with the epic fight mod 18.3.7 and optifine (1.18.2 HU U H9) (disabled). I used forge 40.1.80, but when launching the game instantly crashed without opening a window. Attached is the log file. There were no other mods, resource packs, data packs, or anything.
[epic fight optifine fail log.txt](https://github.com/Yesssssman/epicfightmod/files/12489905/epic.fight.optifine.fail.log.txt)

**Comment by Yesssssman** [comment]
I can't get any clue to fix this problem in your log file. Try removing Optifine because they also cause the problem with Forge

**Comment by someguyfromoverthere** [comment]
Ok
