### ISSUE TITLE
[Bug|Crash]: weapon attributes and its name are upside down

### ISSUE THREAD

**Issue by StarryNightNue** [Yesssssman/epicfightmod#1368]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

there is a small bug in the beta version 18.5.1
i use the IBE editor mod to modify attributes, but the weapon name and impact attribute are upside down
![BUG](https://github.com/Yesssssman/epicfightmod/assets/105207066/51ee507b-4d41-493b-be2a-63a00e510bd0)

**Comment by Yesssssman** [comment]
Fixed in 18.5.4
