### ISSUE TITLE
[Bug|Crash]:EpicFight-18.5.3-beta Minor issue

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1369]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

bug trigger procedure

https://github.com/Yesssssman/epicfightmod/assets/130232431/f5d23c1e-9f20-4ff7-b0ee-c614ec1390a6

1，filter Animation: ON is set to filter Animation: OFF
2，Then quit the game
3，Then restart the game

https://github.com/Yesssssman/epicfightmod/assets/130232431/b9ac59f2-83d7-493d-ba52-73357c81ccb9

4，Create New World
5，This problem occurs when you wear Elytra
6，This issue can also cause compatibility issues with individual mods like Elytra for example, Quark mod Backpack
7，Minecraft 1.18.2 
      Forge 40.2.10

**Comment by fzrdwa123456** [comment]
I have posted similar issues before but I did not describe the detailed triggering process of the bug. Sorry

**Comment by fzrdwa123456** [comment]
EpicFight-18.5.3-beta

**Comment by Yesssssman** [comment]
Will be fixed in 18.5.4

**Comment by fzrdwa123456** [comment]
> 将在 18.5.4 中修复

Thank you

**Comment by fzrdwa123456** [comment]
> Will be fixed in 18.5.4

May I make a suggestion? Whether future releases will add a new configuration to The data pack, i.e. the ability to set the block of the weapon, will be obvious in the L_Ender's Cataclysm This problem occurs with the Incinerator weapon as well as some other mod weapons where the right button of a weapon has a special ability but modifying them with the Epic Battle packet will cause the right button to appear only leaving the block animation unable to use the original weapon's ability even without learning the Skill In the case of the Book, I think it would be a compatibility issue if you could add the ability to change the weapon to block or not in the data pack of epic battles even after learning the Skill Book

**Comment by Yesssssman** [comment]
> > Will be fixed in 18.5.4
> 
> May I make a suggestion? Whether future releases will add a new configuration to The data pack, i.e. the ability to set the block of the weapon, will be obvious in the L_Ender's Cataclysm This problem occurs with the Incinerator weapon as well as some other mod weapons where the right button of a weapon has a special ability but modifying them with the Epic Battle packet will cause the right button to appear only leaving the block animation unable to use the original weapon's ability even without learning the Skill In the case of the Book, I think it would be a compatibility issue if you could add the ability to change the weapon to block or not in the data pack of epic battles even after learning the Skill Book

Can you open a new issue tab describing this issue with any videos or pictures?
