### ISSUE TITLE
[Bug|Crash]: Ground damage swallow blocks

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1372]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

1，Ground placement blocks destroyed by weapons are swallowed and disappear without being returned

https://github.com/Yesssssman/epicfightmod/assets/130232431/31a7f16f-6de7-4d91-80b3-84a61a9248ba

2，Learning Meteor Slam will also swallow blocks

https://github.com/Yesssssman/epicfightmod/assets/130232431/31b7e7ae-d0dd-45cd-b2ba-cb476ea59cca

3，Maybe you should set the damaged ground so that you can't place blocks until the damaged ground is restored
4，Minecraft 1.18.2
      Forge 40.2.10
      Epic Fight 18.5.5 beta

**Comment by fzrdwa123456** [comment]
Although the missing blocks will return temporarily, there will still be several missing blocks

**Comment by Yesssssman** [comment]
Fixed in 20.9.2
