### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by AngeloStyles** [Yesssssman/epicfightmod#1373]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Oculus

### Minecraft Version

1.16.5

### What happened?

Minecraft crashes as I try to join server, says mods with issues are Epic Fight, Oculus.
Link of report here:
https://bytebin.lucko.me/stSAoGiG06

**Comment by MetalKnight56** [comment]
1.16.5 is discontinued
