### ISSUE TITLE
issue; server keeps saying missing the following mods

### ISSUE THREAD

**Issue by furrydemon1** [Yesssssman/epicfightmod#1374]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

epic fight

### Minecraft Version

1.18.2

### What happened?

it is installed but keeps saying mismatched mod channel list server is missing the folllowing mods and epic fight is the only one installed ![Screenshot 2023-09-24 211528](https://github.com/Yesssssman/epicfightmod/assets/33299492/67158bca-f5c5-4f2f-afb2-bc03c9a6af40)

**Comment by MetalKnight56** [comment]
Attach logs
