### ISSUE TITLE
[Bug|Crash]: Load crash

### ISSUE THREAD

**Issue by al-wei** [Yesssssman/epicfightmod#1375]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

modernfix-forge-5.7.4+mc1.16.5, ColdSweat-2.2

### Minecraft Version

1.16.5

### What happened?

EpicFight-16.6.4
modernfix-forge-5.7.4+mc1.16.5
ColdSweat-2.2
The above three mods crashed the loading game.

https://gist.github.com/al-wei/5a2a5a1c91bc71a286627acd40046c5c

**Comment by MetalKnight56** [comment]
Closing issue as discontinued version is being used.
