### ISSUE TITLE
[Bug]: Blade Trail invisible in specific location

### ISSUE THREAD

**Issue by dfdyz** [Yesssssman/epicfightmod#1376]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

please override method "shouldCull" in class “esman.epicfight.client.particle.TrailParticle”

```
public class TrailParticle extends TextureSheetParticle {
...
	@Override
	public boolean shouldCull() {
		return false;
	}
...
}
```

**Comment by Yesssssman** [comment]
Thanks. I'll fix it in the next version.
