### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by gechoph** [Yesssssman/epicfightmod#1378]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

### Minecraft Version

1.18.2

### What happened?

when im using demolition leap and meteor slam at max charge minecraft

**Comment by MetalKnight56** [comment]
Attach your log
