### ISSUE TITLE
[Bug|Crash]: custom entity datapack doesn't work

### ISSUE THREAD

**Issue by Cyber2049** [Yesssssman/epicfightmod#1379]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

[crash-2023-10-02_16.00.01-server.txt](https://github.com/Yesssssman/epicfightmod/files/12788165/crash-2023-10-02_16.00.01-server.txt)
It seems that 'present' cannot be used to setup custom entity in datapack

**Comment by Yesssssman** [comment]
You now have to define "armature" keyword for custom entities, which is made to ensure the compatibility between different animation and armature forms. See more information in here: https://epicfight-docs.readthedocs.io/en/latest/Guides/page1/

**Comment by MetalKnight56** [comment]
> I use the zombie present. Still doesn't work after I define "armature" for it.

Attach your datapack here so we can take a look at it.
