### ISSUE TITLE
[Suggestion] Hitting from behind of the shield

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#138]
I suggest you to add penetrating while blocking with the shield.
This Feature can mostly be cool while using spear.

**Comment by Yesssssman** [comment]
It seems to little bit strong feature but I also consider implementing them with some penalty.

**Comment by TurkishAhmet4545** [comment]
> It seems to little bit strong feature but I also consider implementing them with some penalty.

I also recommend you to add blockhit feature with Shield + Sword/Spear
