### ISSUE TITLE
[Bug|Suggestion]: map cannot be viewed while sitting on a boat or riding an animal

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1380]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

https://github.com/Yesssssman/epicfightmod/assets/130232431/c7223fac-c13d-45fc-a84a-76c53141495e

Can you view the map while riding an animal or sitting down?

**Comment by fzrdwa123456** [comment]
Minecraft 1.18.2
Forge 40.2.10
Epic Fight 18.5.11 release

**Comment by Yesssssman** [comment]
Fixed in 18.5.12

**Comment by fzrdwa123456** [comment]
> Fixed in 18.5.12

The great Yesssman thank you
