### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by LucasLeels** [Yesssssman/epicfightmod#1381]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

The game crashes and an error occurs when using the longsword and crack attack, the jump skill also crashes the game when used.

**Comment by Yesssssman** [comment]
please post the crash report

**Comment by fzrdwa123456** [comment]
> 请发布崩溃报告

His meltdown could have been caused by installing optifine

**Comment by LucasLeels** [comment]
> por favor poste o relatório do acidente

Desculpe a demora já foi resolvido obrigado.

**Comment by LucasLeels** [comment]
> > 请发布崩溃报告
> 
> His meltdown could have been caused by installing optifine

It was so easy, thanks for the help.

**Comment by fzrdwa123456** [comment]
> > por favor poste o relatório do acidente
> 
> Desculpe a demora já foi resolvido obrigado.

The use of optifine is not recommended for your next trip. You're welcome.
