### ISSUE TITLE
[Bug]: Particle map is lost when a leaf block is suspended in the air and destroyed with Meteor Slam Skill

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1382]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

https://github.com/Yesssssman/epicfightmod/assets/130232431/7fd29d13-67ca-4e06-825e-1c22acae41e7

https://github.com/Yesssssman/epicfightmod/assets/130232431/674b3c47-cb4c-419a-b278-a61d7bfaf33e

A bug I accidentally found
Minecraft 1.18.2
Forge 40.2.10
Epic Fight 18.5.12 release

**Comment by fzrdwa123456** [comment]
The second video is more obvious

**Comment by fzrdwa123456** [comment]
In the new test, it was found that whenever the block is suspended and destroyed, the particle map will be lost

**Comment by fzrdwa123456** [comment]
https://github.com/Yesssssman/epicfightmod/assets/130232431/dcccc58b-e1b2-456b-906c-f53e9e7f771f

**Comment by Yesssssman** [comment]
Fixed in 20.9.2
