### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by AngeloStyles** [Yesssssman/epicfightmod#1383]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

It crashes on startup. I am using a modpack I put together. I'm very sure its a mod compatibility issue, just not sure which mod(s) are the issue. Wondering if anyone can help me figure this out ! I'm not sure if theres other information I could give, but please do let me know!

Crash Report:
[crash-2023-10-04_14.16.58-fml.txt](https://github.com/Yesssssman/epicfightmod/files/12806890/crash-2023-10-04_14.16.58-fml.txt)
Latest Log:
[latest log.txt](https://github.com/Yesssssman/epicfightmod/files/12806895/latest.log.txt)

**Comment by MetalKnight56** [comment]
Closing issue as user did not follow the support policy. Please refer to the discord server for this kind of issue.
