### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by DonutIV** [Yesssssman/epicfightmod#1384]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm

### Minecraft Version

1.18.2

### What happened?

Dodging boss attacks from L_Ender's Cataclysm by mcl_ender (a common mod used with epic fight for a dark souls experience) sometimes crashes the game, don't know why. This was not a problem in previous versions of epic fight.

**Comment by Yesssssman** [comment]
Fixed in 18.5.13
