### ISSUE TITLE
[Bug|Crash]: Optifine Incompatability

### ISSUE THREAD

**Issue by Walking-Wake** [Yesssssman/epicfightmod#1386]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.optifine.net/home

### Minecraft Version

1.18.2

### What happened?

Anything that causes the ground break effect (such as demolition leap) causes the game to crash. A possible solution would be a config option to disable said effect for Optifine users. The crash can be caused by activating Optifine and using demolition leap or any similar ground breaking effect. I can provide a crash log if requested.

**Comment by xLasttDev** [comment]
yep i got the same crash 
details 

MC ver 1.18.2
Optifine ver OptiFine HDU_H9 
Epic Fight ver epicfight - 18.5.13

i tried to use neruina-1.2.5-forge+1.18.2-1.20.1 but same result

**Comment by MetalKnight56** [comment]
Closing issue as optifine is trash, closed source and doesn't use forge's modding api so we can't do anything about it.
