### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by game822snake** [Yesssssman/epicfightmod#1387]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/nyfs-quivers

### Minecraft Version

1.16.5

### What happened?

The latest version of Nyf's Quiver doesn't support the latest version of 1.16.5 epic fight, I'm unsure where the issue is arising from so I'm just wandering if there is anything I can do. Thanks!

Here's the crash report:

https://pastebin.com/7gAFUdy9

**Comment by game822snake** [comment]
I'm so sorry I forgot to add a title

**Comment by Yesssssman** [comment]
Looks like you have to downgrade the epic fight version

```
Details:
	Mod File: NyfsQuiver-1.16.5-0.6.3.jar
	Failure message: Mod nyfsquiver only supports epicfight 16.5.13
		Currently, epicfight is 16.6.4
	Mod Version: 1.16.5-0.6.3
```

**Comment by MetalKnight56** [comment]
Closing issue as 1.16.5 is no longer supported.
