### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Mark-123456** [Yesssssman/epicfightmod#1388]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Dawncraft

### Minecraft Version

1.18.2

### What happened?

Running Dawncraft, died while battling an epic boss 'Nine Tails'. 
DawnCraft uses EpicFight-18.3.8.jar.
Client crashed after death.  When reconnecting to server, MC crashes immediately with error:  "yesman.epicfight.api.animation.TransformSheet.getInterpolatedTransform(float)" because "rootCoord" is null
Reloaded DawnCraft Mod - same issue.

Looking for suggestion on how to fix so character can join server

**Comment by MetalKnight56** [comment]
Report it to them.
