### ISSUE TITLE
[Bug|Crash]: java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by rebarnerd** [Yesssssman/epicfightmod#1389]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight, Epic Fright Pirates, Dual Greatsword, yamato moveset

### Minecraft Version

1.18.2

### What happened?

I have a modpack, not sure if this is an issue with mod compatibility but it probably is, not sure which mod, I mightve missed if someone had this problem, but I havent seen this issue. Here are some images of the error message and my mod list
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/64d45ce5-13a5-41e8-9bf9-a796480a87f9)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/80dce9c3-8b1b-4198-a7f9-bee157bb2bee)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/ea8fd93b-12fd-4b57-b367-92af57863e59)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/9bb3fefc-ecf6-4fdc-b710-c3229e2eff0e)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/6d0f05b3-5515-49e0-ab58-651bff309add)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/819fd652-7e76-4f08-92f0-3cf171baa96a)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/14a9300a-7e3e-4eec-9bfe-c6b6dab54997)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/783fa563-29a0-4961-9376-058e97623217)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/b9f31001-b209-4b4e-8142-4f1dd8686813)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/b3b4d65d-d07d-4138-96d6-b3ca6a4b3cd1)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/d570caa7-0bb9-4a3e-b5cf-bef66fa00c6c)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/5e5919bc-f221-4855-8604-a99ffc60454b)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/1cf4aa18-3e86-4442-afe3-a7e5dc4e7b31)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/a62e2d1d-7f4f-4a83-8dfe-005a07bc4669)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/3e12e679-f8a7-4297-9793-83ab16b576f1)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/a6af0a74-07b9-4493-a6aa-704020eeff52)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/c21ecd43-55c2-4fcb-9c72-2d14b414f2db)
![image](https://github.com/Yesssssman/epicfightmod/assets/63887384/93378f01-04aa-4cd7-8335-4d88c6a43c6d)

**Comment by rebarnerd** [comment]
UPDATE: I EVEN RAN ALL THE EPIC FIGHT MODS I HAD ALONE TOGETHER AND THEY DIDNT RUN

**Comment by rebarnerd** [comment]
The problem seems to stem from dual swords,pirates, and the yamato

**Comment by MetalKnight56** [comment]
yes remove the addons you have and only keep epic fight. They are yet to update to the newer versions of ef.
