### ISSUE TITLE
a problem where blocks cannot be broken

### ISSUE THREAD

**Issue by HongMint88** [Yesssssman/epicfightmod#139]
I want to use it on the RPG server, but there is housing content on the server. If a user tries to break a block, it won't break because of motion, can you solve it?

Client is use Forge 1.12.2.

**Comment by TurkishAhmet4545** [comment]
> I want to use it on the RPG server, but there is housing content on the server. If a user tries to break a block, it won't break because of motion, can you solve it?
> 
> Client is use Forge 1.12.2.

Did you download new version of the mod ?
And does this problem happen in build mode ?

**Comment by Yesssssman** [comment]
You can't break any block in the battle mode. Get out and you can break blocks.

**Comment by HongMint88** [comment]
I received the latest version of Epic Fight mod and applied it. It was not in combat, it was in survival mode, and the block was not broken due to combat motion.

**Comment by HongMint88** [comment]
I'm sorry! I received the latest version and it's settled. I thought it was the latest version, but it was posted the day before.
