### ISSUE TITLE
3D skin layer incompat 

### ISSUE THREAD

**Issue by Acat1234** [Yesssssman/epicfightmod#1390]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

1. im useing 1.19.2 not 1.18.2 soooo anyways 2 modles overlap witch is the problem any way to fix?

**Comment by robit4** [comment]
![2023-10-10_13 50 24](https://github.com/Yesssssman/epicfightmod/assets/126712560/584559b8-87ac-470b-a035-cdf7db96b0da)

**Comment by robit4** [comment]
![2023-10-11_12 09 22](https://github.com/Yesssssman/epicfightmod/assets/126712560/4f9df0ca-043b-4eff-880f-34fb209f9e2a)

**Comment by robit4** [comment]
The combat and mining overlap

**Comment by MetalKnight56** [comment]
Remove 3D skin layers. We are still yet to fix this issue.

**Comment by SomehowSurviving** [comment]
I don't have 3D skin layers, but am still having this issue.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. We weren't able to fix all the changes to the older versions. Thank you for your consideration.
