### ISSUE TITLE
[Bug|Crash]: Dedicated Servers not showing custom entity datapack animations

### ISSUE THREAD

**Issue by SC-Merk** [Yesssssman/epicfightmod#1391]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.18.2

### What happened?

whenever using datapacks on a dedicated server the datapack would work except for the animations of the entity
I made a video for comparison when using the datapack in a dedicated server and in a singleplayer world.
[video](https://streamable.com/2xq1k5)

**Comment by Yesssssman** [comment]
Fixed in X.5.14. Thank you for reporting
