### ISSUE TITLE
[Bug|Crash]: Flashback after the Final Shadow Dragon lands

### ISSUE THREAD

**Issue by Oguri-Chen** [Yesssssman/epicfightmod#1396]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://modrinth.com/datapack/stellarity/version/2.0e

### Minecraft Version

1.18.2

### What happened?

I apologize for using translation software due to my poor English

forge1.20.1，47.1.3，The game version 47.2.1 has also been tested and will have the same issue
Mod latest version

The Ender Dragon flies without any issues, but when it descends and prepares to switch to its epic combat attack mode, the game crashes. This issue seems to be conflicting with the 'stellarity' mod.

**Comment by MetalKnight56** [comment]
We do not support datapacks or mods that change entity ai heavily, as we also make changes to it and thus it can cause crashes.
