### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Darianstark3** [Yesssssman/epicfightmod#1397]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

I do not know if it is a mod compatibility issue or not and I am playing on version 1.20.1 but it was not an option. The game appears to work completely fine and I can kill mobs like cows, iron golems, and even a modded animal, but if I kill a hostile mob like a witch or skeleton, the game completely crashes. 
[latest.log](https://github.com/Yesssssman/epicfightmod/files/12889892/latest.log)

**Comment by MetalKnight56** [comment]
Remove all mods and try again, if the game continues to crash with only epic fight and minecraft then attach that new log here
