### ISSUE TITLE
Demolition Leap Crashs My Minecraft

### ISSUE THREAD

**Issue by IWS231** [Yesssssman/epicfightmod#1398]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [x] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

idk when i use it at power level 2 its ok but when it get to 3 or higher the game crashs
**Versions** 
- Minecraft version 1.20.1 
- Forge version 47.0.45 
- Mod version - 20.5.13
- and here is the log file i cant copy past all the code so here it is 
[New.Text.Dssocument.txt](https://github.com/Yesssssman/epicfightmod/files/12893401/New.Text.Dssocument.txt)

**Comment by SAGESSE-CN** [comment]
retry with 20.5.15

**Comment by IWS231** [comment]
Thx So Much It Works
