### ISSUE TITLE
[Suggestion]: config file adds either the default mining mode when the player enters the world or the battle mode enabled

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1399]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Can you add configuration options to the config file to automatically default mining mode or battle mode when the player enters the world?
![Screenshot 2023-10-13 235717](https://github.com/Yesssssman/epicfightmod/assets/130232431/12b27549-ef8f-472a-9fa6-bfbb56941752)
Otherwise, this option is meaningless because the default mode when you change it to OFF is mining mode instead of combat mode.

**Comment by DonorKrovi** [comment]
Good idea

**Comment by Yesssssman** [comment]
This feature was just added in 20.8.9
