### ISSUE TITLE
[Suggestion] Double Sword

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#140]
This idea looks best,can you add attacking with dual swords please

**Comment by lLeohartl** [comment]
> This idea looks best,can you add attacking with dual swords please

**A Dual Wielding Mechanic already works in the current versions of the mod,** you only need to equip a sword in **both hands.** This will unlock a new chain of Standard Attacks and a new Special Attack called Dancing Edge, both using the two equipped swords. But of course, **this only works with swords and no other type of weapon.**

**Comment by TurkishAhmet4545** [comment]
> > This idea looks best,can you add attacking with dual swords please
> 
> **A Dual Wielding Mechanic already works in the current versions of the mod,** you only need to equip a sword in **both hands.** This will unlock a new chain of Standard Attacks and a new Special Attack called Dancing Edge, both using the two equipped swords. But of course, **this only works with swords and no other type of weapon.**

Ok,thx. :)
