### ISSUE TITLE
[Bug|Crash]: The ground damage caused an anomaly in the Monster Spawner

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1400]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

https://github.com/Yesssssman/epicfightmod/assets/130232431/c6ff323a-8dbd-40ad-ae4d-eddc44e175d1

What creature is inside the Monster Spawner block that doesn't show when it's destroyed but seems to spawn normally but can't be seen.
1.18.2 and 1.19.2 May have the same problem.
Minecraft 1.20.1
Forge 47.2.1
Epic Fight 20.5.15

**Comment by Yesssssman** [comment]
Fixed in 20.9.2
