### ISSUE TITLE
[Help|1.20.1]:  Armor model issue

### ISSUE THREAD

**Issue by JellyCreeperOfficial** [Yesssssman/epicfightmod#1402]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks

### Minecraft Version

1.18.2

### What happened?

This issue is actually with 1.20.1

I have been following your 3d armor and texturing guide and managed to export the json file and got it into a datapack with the folder structure path as detailed in the guide.

I am using the Pyromancer hat from Iron's Spells 'n Spellbooks as an example:
![image](https://github.com/Yesssssman/epicfightmod/assets/23292973/6fa7aa29-13ec-4b11-b3bd-1506266e153e)
This image is how it looks before I exported it in blender. Everything seemed to be working in pose mode and I could rotate it without issue.
I made a resource pack with the structure:
"Pyro Armor Set" -> assets -> irons_spellbooks -> animmodels -> armor -> pyromancer_helmet.json
"Pyro Armor Set" -> pack.mcmeta

with the following lines:
{
    "pack":{
        "pack_format":15,
        "description":"Pyromancer Set"
        }
}

When playing the game there is no difference from enabling the resource pack or not. This is what I see:
![image](https://github.com/Yesssssman/epicfightmod/assets/23292973/323cffa2-3c57-4641-9244-ad18a6a16356)
![image](https://github.com/Yesssssman/epicfightmod/assets/23292973/ae36a73a-7753-4d19-b92c-c185c2b2ecbc)
![image](https://github.com/Yesssssman/epicfightmod/assets/23292973/e895f366-2b9e-401d-9ac9-d3764bccf208)
The first image is with epic fight turned off. This issue occurs with all armor sets from this mod across the board.
![image](https://github.com/Yesssssman/epicfightmod/assets/23292973/d7b49df2-d2f7-4ac6-9b48-0575b20e9d29)

 What have I done wrong?

**Comment by fzrdwa123456** [comment]
> ### Have you checked if a similar issue is already reported by someone else?
> * [x]  I checked there are no similar issues have been reported.
> 
> ### Have you read the support policy?
> * [x]  I read it and I accept the policy.
> 
> ### Are you using the latest Epic Fight and recommended Forge version?
> * [x]  I checked I'm using latest Epic Fight and recommended Forge version.
> 
> ### Is this issue related to mod incompatibility?
> * [x]  This is a mod compatibility issue and I'm aware of the problem.
> 
> ### The mod
> https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks
> 
> ### Minecraft Version
> 1.18.2
> 
> ### What happened?
> This issue is actually with 1.20.1
> 
> I have been following your 3d armor and texturing guide and managed to export the json file and got it into a datapack with the folder structure path as detailed in the guide.
> 
> I am using the Pyromancer hat from Iron's Spells 'n Spellbooks as an example: ![image](https://user-images.githubusercontent.com/23292973/275543054-6fa7aa29-13ec-4b11-b3bd-1506266e153e.png) This image is how it looks before I exported it in blender. Everything seemed to be working in pose mode and I could rotate it without issue. I made a resource pack with the structure: "Pyro Armor Set" -> assets -> irons_spellbooks -> animmodels -> armor -> pyromancer_helmet.json "Pyro Armor Set" -> pack.mcmeta
> 
> with the following lines: { "pack":{ "pack_format":15, "description":"Pyromancer Set" } }
> 
> When playing the game there is no difference from enabling the resource pack or not. This is what I see: ![image](https://user-images.githubusercontent.com/23292973/275545540-323cffa2-3c57-4641-9244-ad18a6a16356.png) ![image](https://user-images.githubusercontent.com/23292973/275545617-ae36a73a-7753-4d19-b92c-c185c2b2ecbc.png) ![image](https://user-images.githubusercontent.com/23292973/275545755-e895f366-2b9e-401d-9ac9-d3764bccf208.png) The first image is with epic fight turned off. This issue occurs with all armor sets from this mod across the board. ![image](https://user-images.githubusercontent.com/23292973/275547158-d7b49df2-d2f7-4ac6-9b48-0575b20e9d29.png)
> 
> What have I done wrong?

That's epic fight's problem

**Comment by fzrdwa123456** [comment]
epic fight 1.20.1 will cause incompatible armor to look like this

**Comment by guivnf** [comment]
fixed in 18.5.16, 19.5.16, 20.5.16

**Comment by Zhejunfung** [comment]
the bug seems to have a comeback in the newest version any fix?

**Comment by L3653** [comment]
the bug is still present
