### ISSUE TITLE
Crash when joining server

### ISSUE THREAD

**Issue by knoxhack** [Yesssssman/epicfightmod#1403]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Version: EpicFight-20.5.15
Minecraft: 1.20.1

"Tacoɔɐ⊥: 
im unable to figure out the cause, but i constantly have issues connecting to my server. if im able to connect, i get around 15 minutes before i crash. thats if i dont have a server timeout or failure to connect. it was crashing upon joining, but i found a workaround by joining the official server before attempting to connect to my server (maybe im getting a missing asset?)."

[crash-2023-10-16_14.33.16-client.txt](https://github.com/Yesssssman/epicfightmod/files/12923385/crash-2023-10-16_14.33.16-client.txt)

**Comment by Yesssssman** [comment]
There are tons of mods in there and it's caused by one of them but I can't get a clue which mod is causing this issue. Sorry but I can't solve this problem because it's so tiring
