### ISSUE TITLE
[Suggestion]: default mode for server

### ISSUE THREAD

**Issue by DonorKrovi** [Yesssssman/epicfightmod#1407]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Players who don't understand how the mod works can't change the battle mode, which is why they constantly complain that they can't beat mobs, I suggest making it possible to automatically activate the battle mode or set it by default on the servers, which will be extremely convenient!

**Comment by TheCatLord0** [comment]
You can just perma set them to battle mode with a repeating command block. And honestly they could also just learn?

**Comment by DonorKrovi** [comment]
> You can just perma set them to battle mode with a repeating command block. And honestly they could also just learn?

Some stupid alternatives

**Comment by fzrdwa123456** [comment]
"/epicfight mode battl@s "This allows you to adjust the player's current mode. This command is to enable battle mode because it is currently in config and does not allow this command to be set. If you want to keep the command on, you can use" Global" GameRules "mod or" FTB Task "mod setup instructions ask you to give it a try

**Comment by fzrdwa123456** [comment]
Although I provided advice here https://github.com/Yesssssman/epicfightmod/issues/1399 but I don't know will be adopted

**Comment by Yesssssman** [comment]
This feature was just added in 20.8.9
