### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by TheHallowGent** [Yesssssman/epicfightmod#1408]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.16.5

### What happened?

The animations are not working with other mods

**Comment by MetalKnight56** [comment]
Closing issue as 1.16.5 is no longer supported (discontinued).
