### ISSUE TITLE
Attacking too fast will cause no damage 

### ISSUE THREAD

**Issue by Dr-WeiAL** [Yesssssman/epicfightmod#141]
Attacking too fast will cause no damage

I tested that the attack has no damage when the attack speed is 4, and only a heavy hit will cause damage, but when the attack speed is 3.5, it can cause damage.

**Comment by AKreedz** [comment]
Me too.Weapon with attckSpeed AttributeModifiers seems too fast to attack the enemy,such as diamond spear with +10% speed,can not touch any enemy.


by the way Dash Attack and Weapon Special Attack doesn't effected by attackSpeed or potion effect,that's weird

**Comment by Yesssssman** [comment]
Sorry, this will be fixed as soon as possible.
