### ISSUE TITLE
[Bug|Crash]: wither skeleton crash using WOM weapon

### ISSUE THREAD

**Issue by kaairu** [Yesssssman/epicfightmod#1412]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

WOM weapons of miracles

### Minecraft Version

1.20.1

### What happened?

gave a few wither skeletons some of the weapons from WOM and my game crashed 

https://paste.modularity.gg/paste?content=https://cdn.discordapp.com/attachments/1101396706861531157/1165734243956162601/crash-2023-10-22_12.30.38-client.txt?ex=6547ed9e&is=6535789e&hm=f5289fdda193800ff7356258477a969374943342784b32ffdbf172ba68ac9d8a&&raw=false

https://paste.modularity.gg/paste?content=https://cdn.discordapp.com/attachments/1101396706861531157/1165734244358824006/latest.log?ex=6547ed9e&is=6535789e&hm=60057e6adbfe129bce3fefbe49481d4385a5c4faf057d872e55378b82edfcc93&&raw=false

**Comment by MetalKnight56** [comment]
*Regarding WOM issues/crashes please redirect them to the newly opened Weapons Of Minecraft's Issue tracker Linked Below*

[**WOM Issue Tracker**](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/issues)
