### ISSUE TITLE
[Bug]: On the server, the energy for a special attack does not accumulate on most weapons

### ISSUE THREAD

**Issue by fanfanoverlord** [Yesssssman/epicfightmod#1413]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Epic Battle-16.6.4
In the single world, the mod works without problems. But I put the mod on the server, and there most of the weapons do not accumulate energy for a special attack.

Example in the video:
https://github.com/Yesssssman/epicfightmod/assets/148730929/29314ed6-8ead-4550-b7c1-b88751d762ac

energy storage works for:
![image](https://github.com/Yesssssman/epicfightmod/assets/148730929/c5f90c14-d383-48df-9a28-5ab827a11636)

energy storage not works for:
![image](https://github.com/Yesssssman/epicfightmod/assets/148730929/52a788b6-cc0e-4d44-a599-a018de0c1037)

Those spears that do not accumulate energy, but can accumulate in combination with a shield:
![image](https://github.com/Yesssssman/epicfightmod/assets/148730929/5a4a05d4-208c-4419-9c6e-35fdaa5f11a3)

Katana accumulates energy only with a strong swing:
https://github.com/Yesssssman/epicfightmod/assets/148730929/915cd87c-0504-4ad2-8452-ebf9acb1985e

**Comment by fzrdwa123456** [comment]
You should probably test this on 1.18.2 because they don't support Epic Fight 1.16.5 anymore

**Comment by fanfanoverlord** [comment]
> You should probably test this on 1.18.2 because they don't support Epic Fight 1.16.5 anymore

Unfortunately, I need version 1.16.5. In addition, I saw 1 server on 1.16.5 where this mod worked correctly.
The mod on my server, as I said, does not work completely.
If anyone knows a solution to this problem, then I will be grateful.

**Comment by fzrdwa123456** [comment]
> > You should probably test this on 1.18.2 because they don't support Epic Fight 1.16.5 anymore
> 
> Unfortunately, I need version 1.16.5. In addition, I saw 1 server on 1.16.5 where this mod worked correctly. The mod on my server, as I said, does not work completely. If anyone knows a solution to this problem, then I will be grateful.

Maybe you should ask them

**Comment by fanfanoverlord** [comment]
> > > You should probably test this on 1.18.2 because they don't support Epic Fight 1.16.5 anymore
> > 
> > 
> > Unfortunately, I need version 1.16.5. In addition, I saw 1 server on 1.16.5 where this mod worked correctly. The mod on my server, as I said, does not work completely. If anyone knows a solution to this problem, then I will be grateful.
> 
> Maybe you should ask them

I tried, but they refused me in a rude way

**Comment by MetalKnight56** [comment]
Closing issue as 1.16.5 is no longer suported. If you want this issue to be fixed, feel free to make a pull request with the fix inside of it, we'll gladly rebuild the mod with that fix and make it available in CF, if you don't know how to code, unfortunately there's nothing we can do.
