### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Arlequuin** [Yesssssman/epicfightmod#1414]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

epic fights

### Minecraft Version

1.18.2

### What happened?

minecraft fails to load. im using the dawncraft modpack so i understand it may be a compatibility issue... the conflicts in the report were simple_mobs,  and dawncraft_tweaks... i already know about the other addons needing an update.. any update on if a patch or updated version of epic fights  will resolve this issue? if not would removing said mods fix the issue? would love to try the amazing new movesets and skills but in a modpack resembling an rpg world thanks for your time and effort 
![DawnCraft 10_24_2023 7_46_50 AM](https://github.com/Yesssssman/epicfightmod/assets/148873860/09a5c416-825d-4482-bbf0-a307cf6aeafc)

**Comment by fzrdwa123456** [comment]
This has nothing to do with epic fight. You should ask the makers of dawncraft to update the epic fight affiliate

**Comment by MetalKnight56** [comment]
The addons being used are yet to be updated, please contact each author and show this issue to them so they can support our latest versions.
