### ISSUE TITLE
cant use any left click attacks

### ISSUE THREAD

**Issue by mariohany534** [Yesssssman/epicfightmod#1417]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

im in a multipliayer server with the mod i got weapons of miracles mod insalled and these two are the only mods (weapons of miracles and epic fight) i cant use any left click attack

**Comment by MetalKnight56** [comment]
Provide, footage and logs.

**Comment by karaagedesu1** [comment]
Are you using the Saturn mod?
The latest version breaks epic fight.
