### ISSUE TITLE
[translate]: zh_tw

### ISSUE THREAD

**Issue by andy3559167** [Yesssssman/epicfightmod#1418]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/4796372

### Minecraft Version

1.20.1

### What happened?

{
	"attribute.name.epicfight.impact": "%s 影響",
	"attribute.name.epicfight.armor_negation": "%s 護甲忽視",
	"attribute.name.epicfight.max_strikes": "每擊中 %s 個敵人",
	"attribute.name.epicfight.mainhand_only": "僅主手",
	"attribute.name.epicfight.twohanded": "雙手持",
	"attribute.name.epicfight.stun_armor": "擊暈護甲",
	"attribute.name.epicfight.weight": "重量",
	"attribute.name.epicfight.staminar": "耐力",
	"attribute.name.epicfight.stamina_regen": "耐力回復",
	"attribute.name.epicfight.max_execution_resistance": "處決抵抗度",

	"commands.epicfight.skill.add.success.single": "已將技能 %s 添加至 %s",
	"commands.epicfight.skill.add.success.multiple": "已將技能 %s 添加至 %s 目標",
	"commands.epicfight.skill.add.failed": "無法添加此技能（技能已應用）",

	"commands.epicfight.skill.remove.success.single": "已從 %s 中移除 %s",
	"commands.epicfight.skill.remove.success.multiple": "已從 %s 目標中移除 %s",
	"commands.epicfight.skill.remove.failed": "無法移除此技能（技能不存在）",

	"commands.epicfight.skill.clear.success.single": "已從 %s 中移除所有技能",
	"commands.epicfight.skill.clear.success.multiple": "已從 %s 目標中移除所有技能",
	"commands.epicfight.skill.clear.failed": "目標上沒有可移除的技能",

	"death.attack.wither_beam": "%1$s 被凋零光束蒸發",
	"death.attack.shockwave": "%1$s 被震波撕裂",

	"debug.armor_model_debugging.on": "護甲模型調試：開啟",
	"debug.armor_model_debugging.off": "護甲模型調試：關閉",

	"damage_source.epicfight.damage": "%s 傷害",
	"damage_source.epicfight.target_lost_health": " + %s 目標失去的生命值",
	"damage_source.epicfight.sweeping_edge_enchant_level": " + %s（橫掃邊緣 %s 級）",
	"damage_source.epicfight.stun_none": "§7無",
	"damage_source.epicfight.stun_short": "§8施加 §a短 §8擊暈",
	"damage_source.epicfight.stun_long": "§8施加 §6長 §8擊暈",
	"damage_source.epicfight.stun_hold": "§c持續 §8擊暈目標",
	"damage_source.epicfight.stun_knockdown": "§c擊倒 §8目標",
	"damage_source.epicfight.stun_neutralize": "",

	"effect.epicfight.stun_immunity": "擊暈免疫",
	"effect.epicfight.blooming": "綻放",
	"effect.epicfight.stun_instability": "不穩定",

	"entity.epicfight.wither_skeleton_minion": "凋零骷髏的爪牙",

	"epicfight.gui.configuration.autoswitching": "自動切換物品",
	"epicfight.gui.to_battle_mode": "切換至戰鬥模式",
	"epicfight.gui.to_mining_mode": "切換至採礦模式",
	"epicfight.gui.warn_already_registered": "%s 警告：此物品已在對立類別中註冊！",
	"epicfight.gui.tooltip_battle": "自動註冊所有具有 epicfight 屬性的物品。",
	"epicfight.gui.tooltip_mining": "自動註冊所有不包含在戰鬥模式中的物品。",
	"epicfight.gui.delete_all": "刪除全部",
	"epicfight.gui.auto_add": "自動添加",
	"epicfight.gui.attribute": "Epic Fight 屬性：",

	"epicfight.skillNotFound": "未知技能：%s",

	"epicfight.weapon_category.not_weapon": "非武器",
	"epicfight.weapon_category.axe": "斧頭",
	"epicfight.weapon_category.fist": "拳頭",
	"epicfight.weapon_category.greatsword": "大劍",
	"epicfight.weapon_category.hoe": "鋤頭",
	"epicfight.weapon_category.pickaxe": "鎬",
	"epicfight.weapon_category.shovel": "鏟",
	"epicfight.weapon_category.sword": "劍",
	"epicfight.weapon_category.uchigatana": "打刀",
	"epicfight.weapon_category.spear": "矛",
	"epicfight.weapon_category.tachi": "太刀",
	"epicfight.weapon_category.trident": "三叉戟",
	"epicfight.weapon_category.longsword": "長劍",
	"epicfight.weapon_category.dagger": "匕首",
	"epicfight.weapon_category.shield": "盾牌",
	"epicfight.weapon_category.ranged": "遠程",

	"epicfight.skill_category.dodge": "閃避",
	"epicfight.skill_category.passive": "被動",
	"epicfight.skill_category.guard": "防護",

	"epicfight.skill_slot.dodge": "閃避",
	"epicfight.skill_slot.passive1": "被動 1",
	"epicfight.skill_slot.passive2": "被動 2",
	"epicfight.skill_slot.passive3": "被動 3",
	"epicfight.skill_slot.guard": "防護",
	"epicfight.skill_slot.identity": "身份",
	"epicfight.skill_slot.mover": "移動技能",

	"gameMode.epicfight.mining": "採礦",
	"gameMode.epicfight.battle": "戰鬥",

	"gamerule.doVanillaAttack": "啟用基礎攻擊",
	"gamerule.hasFallAnimation": "啟用著陸動畫",
	"gamerule.keepSkills": "死亡後保留技能",
	"gamerule.weightPenalty": "對攻擊速度懲罰的重量影響。",
	"gamerule.disableEntityUI": "關閉所有玩家的生命條和目標指示器",
	"gamerule.globalStun": "啟用全局擊暈",
	"gamerule.canSwitchCombat": "啟用戰鬥/採礦模式切換",

	"gui.epicfight.skill_edit": "技能",
	"gui.epicfight.filter_animation.on": "過濾動畫：開啟",
	"gui.epicfight.filter_animation.off": "過濾動畫：關閉",

	"gui.epicfight.health_bar_show_option.none": "生命條顯示選項：無",
	"gui.epicfight.health_bar_show_option.hurt": "生命條顯示選項：受傷",
	"gui.epicfight.health_bar_show_option.target": "生命條顯示選項：目標",
	"gui.epicfight.target_indicator.on": "顯示目標指示器：開啟",
	"gui.epicfight.target_indicator.off": "顯示目標指示器：關閉",

	"gui.epicfight.ui_setup": "遊戲內界面設置",
	"gui.epicfight.ui_setup.tooltip": "打開界面設置屏幕",
	"gui.epicfight.aim_helper.on": "顯示瞄準助手：開啟",
	"gui.epicfight.aim_helper.off": "顯示瞄準助手：關閉",
	"gui.epicfight.aim_helper_color": "瞄準助手顏色",
	"gui.epicfight.long_press_counter": "長按計數器：%s",
	"gui.epicfight.camera_auto_switch.on": "自動切換相機：開啟",
	"gui.epicfight.camera_auto_switch.off": "自動切換相機：關閉",
	"gui.epicfight.auto_preparation.on": "自動準備：開啟",
	"gui.epicfight.auto_preparation.off": "自動準備：關閉",
	"gui.epicfight.off_blood_effects.on": "血液效果：開啟",
	"gui.epicfight.off_blood_effects.off": "血液效果：關閉",
	"gui.epicfight.no_mining_in_combat.on": "戰鬥中禁止採礦：開啟",
	"gui.epicfight.no_mining_in_combat.off": "戰鬥中禁止採礦：關閉",
	"gui.epicfight.auto_switching_items": "自動切換物品",
	"gui.epicfight.export_custom_armor": "匯出護甲模型",
	"gui.epicfight.filter_animation.tooltip": "在採礦模式中啟用/禁用 Epic Fight 模型",
	"gui.epicfight.health_bar_show_option.tooltip": "哪些實體應該顯示生命條？\n\n受傷：生命值不滿的實體。\n目標：玩家當前的目標。\n無：禁用生命條。",
	"gui.epicfight.target_indicator.tooltip": "啟用/禁用目標指示器",
	"gui.epicfight.long_press_counter.tooltip": "確定多少遊戲刻內按住按鍵才被視為長按。用於武器固有技能和閃避技能",
	"gui.epicfight.aim_helper.tooltip": "在瞄準弓或十字弓時渲染瞄準助手，不兼容極佳的圖形設置和某些著色器",
	"gui.epicfight.camera_auto_switch.tooltip": "切換戰鬥/採礦模式時自動切換到第一人稱/第三人稱",
	"gui.epicfight.auto_preparation.tooltip": "當玩家受到傷害時自動切換到戰鬥模式",
	"gui.epicfight.off_blood_effects.tooltip": "啟用/禁用血液效果",
	"gui.epicfight.no_mining_in_combat.tooltip": "啟用/禁用戰鬥模式下的挖掘能力",
	"gui.epicfight.auto_switching_items.tooltip": "編輯自動在戰鬥和挖掘模式之間切換的物品列表",
	"gui.epicfight.export_custom_armor.tooltip": "匯出所有自定義護甲模型作為資源包",
	"gui.epicfight.replace": "以下技能將被移除：%s",
	"gui.epicfight.require_learning": "您必須首先學習“%s”技能！",
	"gui.epicfight.learn": "學習",
	"gui.epicfight.applied": "已應用",
	"gui.epicfight.unusable": "無法使用",
	"gui.epicfight.changing_cost": "花費：%d",
	"gui.epicfight.no_skills": "您尚未學到任何技能！您可以通過從擊殺生物和打開寶箱中獲取技能書來學習技能",
	"gui.epicfight.select_slot_tooltip": "選擇應用技能的槽",
	"gui.epicfight.save": "保存",
	"item.epicfight.uchigatana": "打刀",
	"item.epicfight.stray_hat": "流浪者之帽",
	"item.epicfight.stray_robe": "流浪者之袍",
	"item.epicfight.stray_pants": "流浪者之褲",
	"item.epicfight.iron_tachi": "鐵太刀",
	"item.epicfight.golden_tachi": "金太刀",
	"item.epicfight.diamond_tachi": "鑽石太刀",
	"item.epicfight.netherite_tachi": "下界合金太刀",
	"item.epicfight.iron_longsword": "鐵長劍",
	"item.epicfight.golden_longsword": "金長劍",
	"item.epicfight.diamond_longsword": "鑽石長劍",
	"item.epicfight.netherite_longsword": "下界合金長劍",
	"item.epicfight.stone_spear": "石矛",
	"item.epicfight.iron_spear": "鐵矛",
	"item.epicfight.golden_spear": "金矛",
	"item.epicfight.diamond_spear": "鑽石矛",
	"item.epicfight.netherite_spear": "下界合金矛",
	"item.epicfight.stone_greatsword": "石巨劍",
	"item.epicfight.golden_greatsword": "金巨劍",
	"item.epicfight.iron_greatsword": "鐵巨劍",
	"item.epicfight.diamond_greatsword": "鑽石巨劍",
	"item.epicfight.netherite_greatsword": "下界合金巨劍",
	"item.epicfight.stone_dagger": "石匕首",
	"item.epicfight.golden_dagger": "金匕首",
	"item.epicfight.iron_dagger": "鐵匕首",
	"item.epicfight.diamond_dagger": "鑽石匕首",
	"item.epicfight.netherite_dagger": "下界合金匕首",
	"item.epicfight.skillbook": "技能書",
	"item.epicfight.knuckle": "手套",
	"item.minecraft.potion.effect.blooming": "盛開",
	"item.minecraft.splash_potion.effect.blooming": "盛開的飛濺藥水",
	"item.minecraft.lingering_potion.effect.blooming": "盛開的殘留藥水",
	"item.epicfight.uchigatana.tooltip": "在5秒閒置後收起“Uchigatana”，您的下一次攻擊將被強化",
	"itemGroup.epicfight.items": "EpicFight 物品",
	"key.epicfight.gui": "Epic Fight 介面",
	"key.epicfight.combat": "Epic Fight 戰鬥",
	"key.epicfight.show_tooltip": "顯示武器固有技能提示",
	"key.epicfight.switch_mode": "切換戰鬥/挖掘模式",
	"key.epicfight.weapon_innate_skill": "武器固有技能",
	"key.epicfight.skill_gui": "打開技能編輯器",
	"key.epicfight.dodge": "閃躲技能",
	"key.epicfight.lock_on": "鎖定目標",
	"key.epicfight.mover_skill": "移動技能",
	"key.epicfight.config": "打開配置屏幕",
	"skill.epicfight.dancing_edge": "舞刃",
	"skill.epicfight.dancing_edge.tooltip": "用致命的飾品砍倒敵人！",
	"skill.epicfight.battojutsu": "抜刀術",
	"skill.epicfight.battojutsu.tooltip": "以盲目的速度釋放您的劍！如果在奔跑時施放，您會向前劃動，切割前方的敵人。",
	"skill.epicfight.steel_whirlwind": "鋼鐵旋風",
	"skill.epicfight.steel_whirlwind.tooltip": "向前砍，殲滅您的敵人！此技能可充能，增加攻擊範圍和速度。",
	"skill.epicfight.the_guillotine": "斬首",
	"skill.epicfight.the_guillotine.tooltip": "用一記沉重的打擊處決您的目標。如果目標的血量低於%s，則會處決。",
	"skill.epicfight.heartpiercer": "穿心",
	"skill.epicfight.heartpiercer.tooltip": "迅速刺擊您的槍3次。",
	"skill.epicfight.grasping_spire": "纏繞之尖",
	"skill.epicfight.grasping_spire.tooltip": "刺穿敵人以將其拉近。成功擊中敵人將進行第二次打擊，擊退敵人的距離取決於擊中的敵人數量。",
	"skill.epicfight.sweeping_edge.level": "橫掃利刃",
	"skill.epicfight.sweeping_edge.tooltip": "用強大的橫掃打擊附近的敵人。",
	"skill.epicfight.rushing_tempo": "疾風節拍",
	"skill.epicfight.rushing_tempo.tooltip": "您可以在每次基本攻擊結束時執行額外的打擊。此技能可以堆疊%s次。",
	"skill.epicfight.relentless_combo": "無情連擊",
	"skill.epicfight.relentless_combo.tooltip": "釋放毀滅性的連續打擊！",
	"skill.epicfight.liechtenauer": "利希腾豪爾",
	"skill.epicfight.liechtenauer.tooltip": "保持%s秒的防禦姿勢。您可以在攻擊時阻擋所有攻擊。殺死敵人將增加防禦姿勢的持續時間%s秒。此效果激活時，您無法奔跑。",
	"skill.epicfight.sharp_stab": "快速刺擊",
	"skill.epicfight.sharp_stab.tooltip": "在攻擊之後以迅速和精確的刺擊繼續進攻，忽略敵人的防禦。",
	"skill.epicfight.eviscerate": "剖腹",
	"skill.epicfight.eviscerate.tooltip": "用野蠻的刺擊撕裂敵人。成功擊中敵人將拔出匕首，造成致命傷害。",
	"skill.epicfight.blade_rush": "刀刃衝刺",
	"skill.epicfight.blade_rush.tooltip": "切割穿過敵人，施加5秒的不穩定效果。達到3層不穩定將處決目標。",
	"skill.epicfight.wrathful_lighting": "憤怒閃電",
	"skill.epicfight.wrathful_lighting.tooltip": "召喚閃電擊打附近的敵人！有機會改變天氣。",
	"skill.epicfight.tsunami": "海嘯",
	"skill.epicfight.tsunami.tooltip": "喚起潮汐的力量，向前衝刺！下雨或在水下時，提高衝刺距離。",
	"skill.epicfight.everlasting_allegiance": "永恆忠誠",
	"skill.epicfight.everlasting_allegiance.tooltip": "召回您丟出的三叉戟，傷害其路徑上的所有敵人。",
	"skill.epicfight.roll": "翻滾",
	"skill.epicfight.roll.tooltip": "以您的移動方向翻滾。閃避所有入侵的攻擊。\n\n（體力：%d）",
	"skill.epicfight.step": "步行",
	"skill.epicfight.step.tooltip": "在您的移動方向短距離滑動。閃避所有入侵的攻擊。\n\n（體力：%d）",
	"skill.epicfight.guard": "防禦",
	"skill.epicfight.guard.tooltip": "右擊以抵擋前方的攻擊。持續防禦將消耗更多體力。\n\n（體力：根據您當前的防禦懲罰）\n\n可用的武器類型：%s",
	"skill.epicfight.parrying": "拆招",
	"skill.epicfight.parrying.tooltip": "允許您根據需要計時您的防禦，以防止體力使用。您現在可以防禦遠程攻擊。\n\n可用的武器類型：%s",
	"skill.epicfight.impact_guard": "衝擊防護",
	"skill.epicfight.impact_guard.tooltip": "減少防禦時的體力消耗。您現在可以使用%d%%效率防禦爆炸、火焰、魔法和射擊。\n\n可用的武器類型：%s",
	"skill.epicfight.berserker": "狂戰士",
	"skill.epicfight.berserker.tooltip": "每缺少1%%生命值，增加%s%%額外攻擊傷害和%s%%額外攻擊速度。\n\n額外攻擊速度不得超過5.0",
	"skill.epicfight.stamina_pillager": "體力劫掠者",
	"skill.epicfight.stamina_pillager.tooltip": "在殺死目標時恢復%s%%缺失的體力。",
	"skill.epicfight.swordmaster": "劍術大師",
	"skill.epicfight.swordmaster.tooltip": "增加%s%%額外攻擊速度。\n\n可用的武器類型：%s",
	"skill.epicfight.technician": "技師",
	"skill.epicfight.technician.tooltip": "在敵人攻擊擊中您之前，躲閃以恢復體力。",
	"skill.epicfight.hypervitality": "超級活力",
	"skill.epicfight.hypervitality.tooltip": "允許使用固Allows stamina use for innate weapon skills.\n\n(Cooldown: 20% of weapon innate power)",
	"skill.epicfight.forbidden_strength": "禁斷之力",
	"skill.epicfight.forbidden_strength.tooltip": "允許在耐力耗盡時消耗生命值。",
	"skill.epicfight.endurance": "忍耐",
	"skill.epicfight.endurance.tooltip": "當你在準備攻擊時被擊中，獲得 %s 秒的暈眩抵抗，持續時間取決於被消耗的耐力值。\n\n（冷卻時間：%ss）\n\n（耐力：%s%% 當前耐力）",
	"skill.epicfight.emergency_escape": "緊急逃脫",
	"skill.epicfight.emergency_escape.tooltip": "現在你可以通過閃避來取消你的攻擊。允許在耐力耗盡時閃避。\n\n（冷卻時間：%ss）\n\n可用武器類型：%s",
	"skill.epicfight.death_harvest": "死亡收穫",
	"skill.epicfight.death_harvest.tooltip": "使用內在武器技能殺死敵人時，恢復內在武器充能。充能量基於你的武器傷害和殺死的敵人數量。",
	"skill.epicfight.meteor_slam": "流星猛擊",
	"skill.epicfight.meteor_slam.tooltip": "§o從天而降的啟示。§r\n\n以強大的猛擊撞向地面。高度增加傷害並消耗耐力。如果墜落傷害超過耐力上限，將受到傷害。\n\n（耐力：墜落傷害）\n\n可用武器類型：%s",
	"skill.epicfight.revelation": "啟示",
	"skill.epicfight.revelation.tooltip": "§o鷹眼捕捉敵人的弱點。§r\n\n格擋、拆解和閃避會獲得啟示堆疊。達到指定的堆疊數量將允許你釋放令人驚嘆的反擊。",
	"skill.epicfight.demolition_leap": "爆裂跳躍",
	"skill.epicfight.demolition_leap.tooltip": "收集能量，以指定方向發射自己，減少下一次的墜落傷害50%。",
	"skill.epicfight.passive.category": "被動技能",
	"skill.epicfight.dodge.category": "閃避技能",
	"skill.epicfight.guard.category": "防禦技能",
	"skill.epicfight.identity.category": "身份技能",
	"skill.epicfight.mover.category": "移動技能",
	
	"beta_warning": "Epic Fight 的當前版本是封閉測試版，包含一些實驗性功能，可能無法正常運作或導致遊戲停止。如果您不想使用此模組，請從模組列表中刪除它。"
}

**Comment by MetalKnight56** [comment]
If you wish to help us translate, make sure to join us in our discord server and ask an admin for the translator role. Please ensure you provide this github issue page so i know who you are and so i can add you in our translation project.
