### ISSUE TITLE
[Bug|Crash]: Bug when using Epic Fight-related modes other than Epic Fight

### ISSUE THREAD

**Issue by Sunnsj** [Yesssssman/epicfightmod#1419]
### Have you checked if a similar issue is already reported by someone else?

- [x] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Paragliders Mod, Epic Fight - Yamato Moveset, Epic Fight ACG AddonPack

### Minecraft Version

1.18.2

### What happened?

If you only use Epic Fight, the mode will work fine, but if you use Epic Fight-related mode in curseforge, you get a "have failed to load correct" error.
![epic fight](https://github.com/Yesssssman/epicfightmod/assets/129259380/747aeccb-1fe2-4292-8042-1fcee2c190d0)

**Comment by MetalKnight56** [comment]
Epic Fight paragliders is yet to be updated. Please contact said mod's developer and report this to them.
