### ISSUE TITLE
[Incompatibility]: Marbled's Arsenal armor in fight mode

### ISSUE THREAD

**Issue by Celks** [Yesssssman/epicfightmod#1422]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Marbled's Arsenal

### Minecraft Version

1.20.1

### What happened?

When i turn to fight mode while using Marble's Arsenal armor my skin just turn pink and black

**Comment by MetalKnight56** [comment]
Update epic fight, this issue should be fixed as of the latest version of epic fight
