### ISSUE TITLE
[Bug|Crash]: 1.20.1 Crashing when equiping geckolib armors in combat mode

### ISSUE THREAD

**Issue by Alexsmobsenyojer** [Yesssssman/epicfightmod#1425]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [x] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

[crash-2023-10-29_15.54.05-client.txt](https://github.com/Yesssssman/epicfightmod/files/13198400/crash-2023-10-29_15.54.05-client.txt)

**Comment by MetalKnight56** [comment]
try removing rei_plugin_compatibilities and or anything related to REI, we don't support that mod, use JEI instead

**Comment by Alexsmobsenyojer** [comment]
> try removing rei_plugin_compatibilities and or anything related to REI, we don't support that mod, use JEI instead

How could it be connected to it ? I will try it though

**Comment by Alexsmobsenyojer** [comment]
> try removing rei_plugin_compatibilities and or anything related to REI, we don't support that mod, use JEI instead

Yep it works well now without rei. Thanks
