### ISSUE TITLE
[Bug|Crash]: Crash on hitting "Create world" in world selection

### ISSUE THREAD

**Issue by ShadowsFang** [Yesssssman/epicfightmod#1427]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.19.2

### What happened?

Attempting to create a new world in my new 1.19.2 pack, but everytime I hit "Create World" the game crashes.
Full Crash Report here:
https://bytebin.lucko.me/8pBsGeOfzO

**Comment by ShadowsFang** [comment]
And before anyone asks, I have tried all 4 versions for 1.19.2, same results every time

**Comment by MetalKnight56** [comment]
> And before anyone asks, I have tried all 4 versions for 1.19.2, same results every time

Then attach logs with the latest available version instead

**Comment by ShadowsFang** [comment]
Edited the link, it now has a crash report from the latest version

**Comment by MetalKnight56** [comment]
> Edited the link, it now has a crash report from the latest version

Bruh look at the ammount of mods in there, remove them all and show me the logs with only epic fight and minecraft so i can make sure this issue is indeed on our side.

**Comment by ShadowsFang** [comment]
Ok, Epic Fight doesn't crash like this by itself. However, it is the only one mentioned as a problem causer by Not Enough Crashes

**Comment by ShadowsFang** [comment]
Ok, after taking a few hours to go through the whole list I've learned that MedievalCraft (a mod intended to be used with epic fight, but ok) is the conflicting mod. Which is an issue the author of that mod has been told about in the comments of the Curse page, but they have yet to address it.
