### ISSUE TITLE
[Bug|Crash]: Mounted weapon guard animation error

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1428]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

https://github.com/Yesssssman/epicfightmod/assets/130232431/d851f7d1-a08a-43f3-8253-d97c940384a4

Can you optimize the two weapon types "longsword" and "greatsword" why can the weapon guard when it is behind the back?

It would be nice to change the weapon attack animation while riding on an animal because some weapons don't work with vertical thrusting like the "dagger" type they're supposed to stab forward

Minecraft 1.18.2
Forge 40.2.10
Epic Fight 18.5.16

**Comment by MetalKnight56** [comment]
Thats already a planned feature, but will take some time to do. Will close this for now since i'm already working on it
