### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Azterio** [Yesssssman/epicfightmod#1429]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

guard skill crashes when stopping blocking

**Comment by MetalKnight56** [comment]
Please attach logs
