### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by RealOdinshi** [Yesssssman/epicfightmod#1430]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

i may be dumb or somthing but importing the zip file into intellij and doing the command " gradlew genIntellijRuns " i am met with a error and i dont really know what im messing up since i imported the file and did the command and thats kinda all the instructions say but i really cant figure it out
![Screenshot 2023-11-01 224846](https://github.com/Yesssssman/epicfightmod/assets/147666176/34c7b957-9525-4167-aede-91646e6a178a)

**Comment by Yesssssman** [comment]
We don't support IntelliJ

**Comment by M6FGR** [comment]
Its the same as vscode tho

**Comment by M6FGR** [comment]
Try to run **build** or **build dependencies**
