### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Shadowzombie115** [Yesssssman/epicfightmod#1432]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

I was making a survival vanilla server for a friend and I (jei, epicfight, weapons of miracles, and journeymap), when I launched it and was only one on everything was fine, once he joined I haven't been able to use weapon abilities and suddenly get disconnected whenever he makes a weapon (great axe or greatsword for instance) but he doesn't get disconnected when I have one

**Comment by MetalKnight56** [comment]
attach your logs here. Both server and clients.

**Comment by Shadowzombie115** [comment]
[debug-2.log](https://github.com/Yesssssman/epicfightmod/files/13257769/debug-2.log)
(Server log)

[debug-2.log.gz](https://github.com/Yesssssman/epicfightmod/files/13257772/debug-2.log.gz)
(client log)

These are the closest logs to when the issue happened as I got off after that and only was on a bit today while he hasn't been on
