### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by kaairu** [Yesssssman/epicfightmod#1434]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/vmh

### Minecraft Version

1.20.1

### What happened?

game randomly crashes in game. logs mention its VMH (variable mod height). it also mentions its ticking a guard villager and a lot of epic fight which I assume is caused by the epic fight datapack compat by nameed

crash-report:
https://mclo.gs/ad7yxAO

log:
https://mclo.gs/epoLomy

**Comment by Yesssssman** [comment]
Crash from rikurob
