### ISSUE TITLE
[Suggestion]: Skill descriptions in the skill editor.

### ISSUE THREAD

**Issue by NekoLeila** [Yesssssman/epicfightmod#1436]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

It's really annoying having to find a book to remember exactly what a skill does. It'd be really nice to have it in the skill editor screen.

**Comment by FuryJack07** [comment]
Commenting on this instead of making a duplicate.

I REALLY want this to happen, especially for trikier skills like critical knowledge (???) - Like, I don't want to remember exactly how much each level of fire res boosts the chance, or how much each level of blast prot ups the damage!

**Comment by Yesssssman** [comment]
Added on the latest version. Thanks.
