### ISSUE TITLE
[Bug|Crash]: Crashing game with abilitys and other for performance mods

### ISSUE THREAD

**Issue by natSuky01** [Yesssssman/epicfightmod#1438]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.20.1

### What happened?

It should be noted that I am using performance mods, but looking at the codes I get errors with chunk names and the Epic Fight mod. Could someone teach me how to solve this?
[crash-2023-11-05_22.59.16-client.txt](https://github.com/Yesssssman/epicfightmod/files/13262363/crash-2023-11-05_22.59.16-client.txt)

**Comment by MetalKnight56** [comment]
Remove rei plugin compatbilities and rei, use JEI instead.
