### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by ilvro** [Yesssssman/epicfightmod#1440]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

when toggling the battle mode, i cant attack. thats it, its just that nothing happens. i can still press right click to block, but left click doesnt do anything - https://medal.tv/games/minecraft/clips/1rceesVfky8E7i/HmtczlYt5OlZ?invite=cr-MSxJWjcsODgyNjc2NCw (not my footage, but its the same thing, nothing happens when you attack)

same thing is happening to a friend who's playing in the same server as me (its only the two of us). i think 2 other people reported the same thing but nobody said anything else
here's a log, although i dont think theres anything interesting on it since there werent any crashes https://pastebin.com/GE7Z7utt

**Comment by ilvro** [comment]
fixed itself for a while and started happening again after i crashed using "satsujin" from weapons of minecraft, not sure what triggered it to get fixed (first time i use a weapon from WoM, probably will fix itself again, its the 3rd time it happens)

**Comment by Yesssssman** [comment]
the issue was from respawning after the player model is completely disappeared.

Please see if you still have the same problem in the latest.
