### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by sorakes** [Yesssssman/epicfightmod#1442]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

EpicFigth

### Minecraft Version

1.16.5

### What happened?

How can I disable just the ender dragon animation? It's crashing every time we start combat.

**Comment by MetalKnight56** [comment]
Check our entity datapack wiki.
