### ISSUE TITLE
[Bug|Crash]: Crash for join in the server

### ISSUE THREAD

**Issue by DonorKrovi** [Yesssssman/epicfightmod#1445]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.20.1

### What happened?

Join server = crash client
https://mclo.gs/nOtAs1G

**Comment by DonorKrovi** [comment]
Lates log

https://mcpaste.io/04b19da18977bd58

**Comment by DonorKrovi** [comment]
I'm use https://www.curseforge.com/minecraft/mc-mods/re-skin

**Comment by sekwah41** [comment]
Nothing in the logs indicates it's an incompatibility with my mod. You fail to load a skin but that will just set the data back to your skin or a Steve.

**Comment by Yesssssman** [comment]
Crash with ModernFix
It has been fixed in the latest 1.20.1
