### ISSUE TITLE
[Suggestion]: Instead of (T/F) for using default damage, would it be doable to add a reduced damage option?

### ISSUE THREAD

**Issue by bob6784558** [Yesssssman/epicfightmod#1446]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

I played with this in Dawn Craft and I was trying to implement this for my pack. Instead of switching to no damage with the default attacks (not using Epicfight) you'd do reduced damage. This would allow me to attack grappling enemies or target dummies while not relying on the cheese of the default damage.

"/gamerule doVanillaAttack true/false (default true)"
Instead 
/gamerule doVanillaAttack Default/Epicfight/reduced

**Comment by MetalKnight56** [comment]
https://github.com/SmileycorpMC/DawnCraft-Tweaks/issues
