### ISSUE TITLE
[Bug|Crash]: crash when learning a new skill

### ISSUE THREAD

**Issue by ilvro** [Yesssssman/epicfightmod#1447]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

used a Roll skill book and i crashed
crash report: https://pastebin.com/tSGC4w8k
latest log: https://pastebin.com/jG2mrAHP

**Comment by MetalKnight56** [comment]
remove all mods and try again, if it stops then its a mod incompatbility, Find the culprit and let me know;
