### ISSUE TITLE
[Bug]: Combat mode simply not working

### ISSUE THREAD

**Issue by Freakout04** [Yesssssman/epicfightmod#1448]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

I'm really not sure how to report this as there are no crash logs, but whenever I switch to combat mode, I can't attack. It's not that the animations just don't play, as I've tested this against targets. Skills that rely on input such as pain anticipation activate when I click, but still, nothing happens. I have fixed this issue in the past by installing performance mods, however it has now stopped working, despite FPS and TPS being at completely normal levels (TPS having issues was most likely what caused it before). I really don't know what to do about this, and I'm not sure what information I could give to help understand what the problem is, but for now, here's the list of mods I'm currently using, in case you know of any incompatibilities or causes:

[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Twilight Decor (by jodlodi)](https://www.curseforge.com/minecraft/mc-mods/twilightdecor)
[Magical Jewelry (by Andi_Erfurt)](https://www.curseforge.com/minecraft/mc-mods/magical-jewelry)
[Adaptive Performance Tweaks: Spawn (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-spawn)
[Dimensional Threading Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/dimensional-threading-reforged)
[Tetranomicon (by syrikalis)](https://www.curseforge.com/minecraft/mc-mods/tetranomicon)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[FPS Reducer (by bre2el)](https://www.curseforge.com/minecraft/mc-mods/fps-reducer)
[Realm RPG: Fallen Adventurers (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-fallen-adventurers)
[Enhanced Block Entities Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities-reforged-unofficial)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[Loot Beams: Relooted! (by shiroroku)](https://www.curseforge.com/minecraft/mc-mods/loot-beams)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[mutil (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/mutil)
[Just Another Rotten Flesh to Leather Mod (by alexdaum1)](https://www.curseforge.com/minecraft/mc-mods/just-another-rotten-flesh-to-leather-mod)
[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[YDM's Weapon Master (by YourDailyModderx)](https://www.curseforge.com/minecraft/mc-mods/ydms-weapon-master)
[FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
[Radium Reforged (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radium-reforged)
[Reforgium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/reforgium)
[Sildur's Vibrant shaders (by SildurFX)](https://www.curseforge.com/minecraft/shaders/sildurs-vibrant-shaders)
[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Memory Settings[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/memory-settings)
[Just Enough Golems (by zKryle)](https://www.curseforge.com/minecraft/mc-mods/just-enough-golems)
[AI Improvements (by QueenOfMissiles)](https://www.curseforge.com/minecraft/mc-mods/ai-improvements)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[Shiny Horses Forge - Enchantable Horse Armor (by tinytransfem)](https://www.curseforge.com/minecraft/mc-mods/shiny-horses-forge-enchantable-horse-armor)
[Multi Mine (by atomicstrykergrumpy)](https://www.curseforge.com/minecraft/mc-mods/multi-mine)
[Pluto (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/pluto)
[Enhanced Boss Bars (by Nakuring)](https://www.curseforge.com/minecraft/texture-packs/enhanced-boss-bars)
[GraveStone Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)
[Spells & Shields: Magicians' Tinkering (by CAS_ual_TY)](https://www.curseforge.com/minecraft/mc-mods/spells-shields-x-tinkers-construct)
[Better chunk loading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-chunk-loading-forge-fabric)
[Divine Weaponry - Better Combat (by WoroxIV)](https://www.curseforge.com/minecraft/mc-mods/divine-weaponry)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Macaw's Bridges - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-biome-o-plenty)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Villager Names (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/villager-names)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Better Arrow Recipe (by pendulumpower)](https://www.curseforge.com/minecraft/mc-mods/better-arrow-recipe)
[Rotten Creatures (by fusionstudiomc)](https://www.curseforge.com/minecraft/mc-mods/rotten-creatures)
[Spells & Shields (by CAS_ual_TY)](https://www.curseforge.com/minecraft/mc-mods/spells-shields)
[Armor Stand Shift Swap (by alan72104)](https://www.curseforge.com/minecraft/mc-mods/armor-stand-shift-swap)
[Arrow Collector (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/arrowcollector)
[Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
[Epic Fight Knuckles Extended(Datapack) (by Edemstreij)](https://www.curseforge.com/minecraft/texture-packs/epic-fight-knuckles-extended-datapack)
[Mimic Mod (by RedrixTTV)](https://www.curseforge.com/minecraft/mc-mods/mimic-mod)
[Prism [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/prism-lib)
[Macaw's Fences - Biomes O' Plenty (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-biomes-o-plenty)
[Aquamirae (Forge) (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/ob-aquamirae)
[Tax Free Levels (Fabric/Forge) (by Fourmisain)](https://www.curseforge.com/minecraft/mc-mods/tax-free-levels)
[Better Leveling (by Darkorg69)](https://www.curseforge.com/minecraft/mc-mods/better-leveling)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Let Sleeping Dogs Lie (Forge) (by ohaiiChun)](https://www.curseforge.com/minecraft/mc-mods/let-sleeping-dogs-lie)
[Inventory Essentials (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/inventory-essentials)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[Mantle (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/mantle)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Ice and Fire: Dragons (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Inventory Totem (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/inventory-totem)
[Castle in the Sky (by songxia23)](https://www.curseforge.com/minecraft/mc-mods/castle-in-the-sky-the-fairytale-of-laputa)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[ExpandAbility (by florensie)](https://www.curseforge.com/minecraft/mc-mods/expandability)
[Embellished Stone (Advancement Plaques) (by Grend_G)](https://www.curseforge.com/minecraft/texture-packs/embellished-stone-advancement-plaques)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[The Bumblezone (Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-forge)
[Tinkers Reforged (by Mrthomas20121)](https://www.curseforge.com/minecraft/mc-mods/tinkers-reforged)
[Blue Skies Tinkers Compat (by Mrthomas20121)](https://www.curseforge.com/minecraft/mc-mods/blue_skies_tcon)
[Adaptive Performance Tweaks: Items (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-items)
[simply swords with epicfight (by sunwoolove777)](https://www.curseforge.com/minecraft/mc-mods/simply-swords-with-epicfight)
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Enchanted Wolves (by Javisel)](https://www.curseforge.com/minecraft/mc-mods/enchanted-wolves)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Caelus API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Weather, Storms & Tornadoes (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/weather-storms-tornadoes)
[Stupid Horse Stand Still (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/stupid-horse-stand-still)
[Cataclysm: Heaven Burner (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/cataclysm-heaven-burner)
[Magnesium/Rubidium Extras (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Mandala's - Brewing Guide On (by cesar_zorak)](https://www.curseforge.com/minecraft/texture-packs/mandalas-brewing-guide-on)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Shoulder Surfing Reloaded (by _ForgeUser21552638)](https://www.curseforge.com/minecraft/mc-mods/shoulder-surfing-reloaded)
[Savage Ender Dragon[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/savage-ender-dragon)
[Adaptive Performance Tweaks: Gamerules (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-gamerules)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Log Begone (by AzureDoomC)](https://www.curseforge.com/minecraft/mc-mods/log-begone)
[U Team Core (by HyCraftHD)](https://www.curseforge.com/minecraft/mc-mods/u-team-core)
[Music Player (by HyCraftHD)](https://www.curseforge.com/minecraft/mc-mods/music-player)
[Entity Collision FPS Fix (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix)
[Ksyxis (by VidTu)](https://www.curseforge.com/minecraft/mc-mods/ksyxis)
[Arcane Additions (by nivthefox)](https://www.curseforge.com/minecraft/mc-mods/arcane-additions)
[Rotten Piglins Mod(Forge) (by abukkezsaruj)](https://www.curseforge.com/minecraft/mc-mods/rotten-piglins-mod)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Immersive Weathering [FORGE] (by OrdanaryMods)](https://www.curseforge.com/minecraft/mc-mods/immersive-weathering-forge)
[Twilight Forest: The Lost Blocks (by Kitteh6660)](https://www.curseforge.com/minecraft/mc-mods/twilight-forest-the-lost-blocks)
[Sword Displays (by sokratis12GR)](https://www.curseforge.com/minecraft/mc-mods/sword-displays)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Let Me Despawn (by frikinjay)](https://www.curseforge.com/minecraft/mc-mods/let-me-despawn)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[Ylf : your flying pet (by sunshinelay02)](https://www.curseforge.com/minecraft/mc-mods/ylf-your-flying-pet)
[Ice and Fire: Dragonseeker (by syrikalis)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragonseeker)
[Pet your cat (by lightsunboy)](https://www.curseforge.com/minecraft/mc-mods/pet-your-cat)
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[The legendary excalibur (by Dr4gon31)](https://www.curseforge.com/minecraft/mc-mods/the-legendary-excalibur)
[Towns & Kingdoms // Epic Fight Compat (by mikaaahh)](https://www.curseforge.com/minecraft/texture-packs/epic-fight-modded-compat)
[Chunk Sending[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Traveler's Backpack (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack)
[TerraForged (by won_ton_)](https://www.curseforge.com/minecraft/mc-mods/terraforged)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[More Bows and Arrows (by lupiiin_)](https://www.curseforge.com/minecraft/mc-mods/more-bows-and-arrows)
[Adaptive Performance Tweaks: Mods (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-mods)
[Tetra (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/tetra)
[Public Gui Announcement (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/public-gui-announcement)
[Epic Sanji (by reascer)](https://www.curseforge.com/minecraft/mc-mods/epic-sanji)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[GUI Scale[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/guiscale)
[Level Text Fix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/level-text-fix)
[Castle And Hustle (by tankist_razrab1337)](https://www.curseforge.com/minecraft/mc-mods/castle-and-hustle)
[Difficult Raids [FORGE] (by CalculusMaster)](https://www.curseforge.com/minecraft/mc-mods/difficult-raids)
[Mana and Artifice (by AWildCanadianEh)](https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice)
[Dungeon Crawl (by xiroc_)](https://www.curseforge.com/minecraft/mc-mods/dungeon-crawl)
[A New Range of Weaponry (by Taredok)](https://www.curseforge.com/minecraft/mc-mods/a-new-range-of-weaponry)
[Dimensional Dungeons (by Catastrophe573)](https://www.curseforge.com/minecraft/mc-mods/dimensional-dungeons)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[End Remastered (by jack_bagel)](https://www.curseforge.com/minecraft/mc-mods/endremastered)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Mowzie's Mobs (by bobmowzie)](https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs)
[Cataclysm Weaponery (by eyezlevrai)](https://www.curseforge.com/minecraft/mc-mods/cataclysmweaponery)
[Arch Bows (by Melvinbur)](https://www.curseforge.com/minecraft/mc-mods/arch-bows)
[Waystone Towers (by ner07ca)](https://www.curseforge.com/minecraft/mc-mods/waystone-towers)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Better Ender Dragon (by Ricy41)](https://www.curseforge.com/minecraft/texture-packs/better-ender-dragon)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Curious Armor Stands (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/curious-armor-stands)
[FastSuite (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastsuite)
[Mandala's GUI - Dark mode (by cesar_zorak)](https://www.curseforge.com/minecraft/texture-packs/mandalas-gui-dark-mode)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[Sword in the Stone (by bonker)](https://www.curseforge.com/minecraft/mc-mods/swordinthestone)
[Human Companions (by jus10wontons)](https://www.curseforge.com/minecraft/mc-mods/human-companions)
[Tinker's Planner (by tiffit_)](https://www.curseforge.com/minecraft/mc-mods/tinkers-planner)
[Epic Fight Knuckles Extended (by Edemstreij)](https://www.curseforge.com/minecraft/mc-mods/epic-fight-knuckles-extended)
[Ender Dragon Loot (by zarophh)](https://www.curseforge.com/minecraft/mc-mods/ender-dragon-loot)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Dragon Pets (by primal_zerg_)](https://www.curseforge.com/minecraft/mc-mods/dragon-pets)
[Parties (by EtherealOnyx)](https://www.curseforge.com/minecraft/mc-mods/parties)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Legendary Tooltips [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips)
[CullLessLeaves Reforged (Unofficial) (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/culllessleaves-reforged)
[Cyclops Core (by kroeser)](https://www.curseforge.com/minecraft/mc-mods/cyclops-core)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[Female Villagers (by Daripher)](https://www.curseforge.com/minecraft/mc-mods/female-villagers)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Radiant Gear (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/radiant-gear)
[Tinkers Construct (by mDiyo)](https://www.curseforge.com/minecraft/mc-mods/tinkers-construct)
[Simply Swords [Fabric & Forge] (by sweenuss)](https://www.curseforge.com/minecraft/mc-mods/simply-swords)
[fix GPU memory leak[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/fix-gpu-memory-leak)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Realm RPG: Pots & Mimics (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/pots-and-mimics-rpg)
[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[FixMySpawnR (by AbsolemJackdaw)](https://www.curseforge.com/minecraft/mc-mods/fixmyspawnr)
[Better Golems (by bagu_chan500)](https://www.curseforge.com/minecraft/mc-mods/bettergolem)
[Zombie Awareness (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/zombie-awareness)
[Adaptive Performance Tweaks (Bundle) (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks)
[Horse Combat Controls (by pitbox46)](https://www.curseforge.com/minecraft/mc-mods/horse-combat-controls)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[The End Expansion Mod 4 (by Molten546)](https://www.curseforge.com/minecraft/mc-mods/the-end-expansion-mod-4)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Starlight (Forge) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight-forge)
[When Dungeons Arise - No Flying Structures (by Aureljz)](https://www.curseforge.com/minecraft/texture-packs/when-dungeons-arise-no-flying-structures)
[Authentic Shadows (by liahim85)](https://www.curseforge.com/minecraft/texture-packs/authentic-shadows)
[Torch Slabs Mod (by EndlesNights)](https://www.curseforge.com/minecraft/mc-mods/torchslabs-mod)
[Repurposed Structures (Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
[ImmediatelyFast Reforged (Unofficial) - DISCONTINUED (by ccr4ft3r)](https://www.curseforge.com/minecraft/mc-mods/immediatelyfast-reforged)
[YUNG's Bridges (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges)
[Curious Lanterns (by Psilock1)](https://www.curseforge.com/minecraft/mc-mods/curious-lanterns)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[The Wild Backport (by blackgear27)](https://www.curseforge.com/minecraft/mc-mods/the-wild-backport)
[Xtra Arrows (by Jackbusters)](https://www.curseforge.com/minecraft/mc-mods/xtra-arrows)
[Callable Horses (by Tschipp)](https://www.curseforge.com/minecraft/mc-mods/callable-horses)
[Better Biome Blend (by FionaTheMortal)](https://www.curseforge.com/minecraft/mc-mods/better-biome-blend)
[Complementary Shaders - Unbound (by EminGTR)](https://www.curseforge.com/minecraft/shaders/complementary-unbound)
[MakeUp - Ultra Fast | Shaders (by XavierFST)](https://www.curseforge.com/minecraft/shaders/makeup-ultra-fast-shader)
[Upgrade Aquatic (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/upgrade-aquatic)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[AutoRegLib (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/autoreglib)
[Feature NBT Deadlock Be Gone (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/feature-nbt-deadlock-be-gone)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[Golems Are Friends Not Fodder (by LobsterJonn)](https://www.curseforge.com/minecraft/mc-mods/golemsarefriends)
[Better Advancements (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/better-advancements)
[♬ Aquamirae Mod EXTRA Music ♬ (by theexiiedfeiiow_)](https://www.curseforge.com/minecraft/mc-mods/aquamirae-mod-music)
[Antique Atlas (by Hunternif)](https://www.curseforge.com/minecraft/mc-mods/antique-atlas)
[YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Obscure API (Forge) (by Obscuria)](https://www.curseforge.com/minecraft/mc-mods/obscure-api)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Traveler's Titles (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/travelers-titles)
[ForgetMeChunk (Forge) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/forgetmechunk-forge)
[Better Animals Plus (by cybercat5555)](https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus)
[Adaptive Performance Tweaks: Core (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-core)
[Blue Skies (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/blue-skies)
[Epicfight - Dual GreatSword (by reascer)](https://www.curseforge.com/minecraft/mc-mods/epicfight-dual-greatsword)
[Better Invisibility (by Purplicious_Cow_)](https://www.curseforge.com/minecraft/mc-mods/better-invisibility)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Adaptive Performance Tweaks: Player Login Optimization and Protection (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-player)
[CoroUtil (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/coroutil)
[It Shall Not Tick (ISNT) (by Gaz_)](https://www.curseforge.com/minecraft/mc-mods/it-shall-not-tick)
[Modern Dynamic Surroundings (by 000_shadowake_AMP)](https://www.curseforge.com/minecraft/mc-mods/modern-dynamic-surroundings)
[Tinkers' Integrations and Tweaks (by wendall911)](https://www.curseforge.com/minecraft/mc-mods/tcintegrations)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[RPG-Hud [Forge] (by Raelzaryn)](https://www.curseforge.com/minecraft/mc-mods/rpg-hud)
[Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
[Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
[Just Enough Resources (JER) (by way2muchnoise)](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer)
[Dragon Magic And Relics (by xShadow0210x)](https://www.curseforge.com/minecraft/mc-mods/dragon-magic-and-relics)
[Lootr (Forge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Weapons of Miracles - epic fight (by reascer)](https://www.curseforge.com/minecraft/mc-mods/weapons-of-miracles-epicfight)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Epic Fight (by maninthe_home)](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod) 

Thank you for your time :)

**Comment by Atarphriel** [comment]
It's probably the freecam mods. Every time I entered freecam I couldn't attack and forgot every single skill until restart. So I stopped using freecam mods because it breaks the fight mode

**Comment by MetalKnight56** [comment]
Mod incompatbility, find the culprit and let us know about it.

**Comment by lodest114** [comment]
[Weather, Storms & Tornadoes (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/weather-storms-tornadoes)
I'm running it on a server
Sometimes this will cause the joining server to switch combat attitude and not be able to attack
At least after I saw this problem this morning, after checking my module list, I deleted it and can attack normally
Sorry, this answer may not be correct, I need your feedback to confirm
This is translated by the translation software, my English is not good, I'm sorry
