### ISSUE TITLE
[Bug| incompatible issue

### ISSUE THREAD

**Issue by Alpred122** [Yesssssman/epicfightmod#1449]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/dreadsteel

### Minecraft Version

1.18.2

### What happened?

I've tried to make the custom armor data pack but it still not work and the armor cant load into the game. Perhaps could u make EFM compatible with dreadsteel mod? since it compatible with ice and fire: dragons

**Comment by MetalKnight56** [comment]
Follow the guide below:
https://epicfight-docs.readthedocs.io/en/latest/Armor/3Darmor_page1/
