### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by ThatGamingcoconut** [Yesssssman/epicfightmod#1454]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.18.2

### What happened?

Game crashes whenever its launched. 

Error: java.lang.NoClassDefFoundError: yesman/epicfight/api/animation/property/AnimationProperty$PlaySpeedModifier

**Comment by HeyKillah** [comment]
I'm also having the same issue.

**Comment by MetalKnight56** [comment]
Attach the whole log.
