### ISSUE TITLE
[Crash]: Budschie's Morph Mod incompatibility ( java.lang.ArithmeticException: / by zero)

### ISSUE THREAD

**Issue by Sx-e** [Yesssssman/epicfightmod#1456]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/budschies-morph-mod

### Minecraft Version

1.18.2

### What happened?

Game crashes during loading a world.
Forge:forge-1.18.2-40.2.10
Mod version:
bmorph-1.18.2-2.0.1.jar
EpicFight-18.5.17.jar
[crash-2023-11-13_21.47.57-server.txt](https://github.com/Yesssssman/epicfightmod/files/13338304/crash-2023-11-13_21.47.57-server.txt)

**Comment by MetalKnight56** [comment]
Ask Budschie's Morph mod dev to contact us to fix this issue. (will close this issue if we don't get a reply)

**Comment by Sx-e** [comment]
I created an issue and asked the mod developer to contact you.
Link to issue:
https://github.com/Budschie/BudschieMorphMod/issues/129

**Comment by MetalKnight56** [comment]
> I created an issue and asked the mod developer to contact you. Link to issue: [Budschie/BudschieMorphMod#129](https://github.com/Budschie/BudschieMorphMod/issues/129)

I'm pretty sure his repository is abandoned. Most likely his mod is also abandoned, so i'll close this down as i don't see him replying.

**Comment by Budschie** [comment]
@MetalKnight56 I had indeed paused the development for a longer time, but now I have found said time again, so I'd be eager to fix this issue.

**Comment by Budschie** [comment]
Alright, by quickly taking a glance at the error I think that this has to do with the fact that my mod copies Attributes from the morph into which you are morphing (eg a cow) to the player. This presumably causes the stamina attribute to be set to `0`, which then causes this exception.

In other words: This would be a rather quick fix on my end, I'd just have to create some sort of blacklist for this attribute copy process and add this stamina ability to that list.

**Comment by Budschie** [comment]
The issue has been fixed :+1:

**Comment by MetalKnight56** [comment]
> The issue has been fixed 👍

Hey thanks for the work dude, really appreciatte the efforts you put into this :) (Sorry for not seeing this issue had updated before)
