### ISSUE TITLE
Armors overlapping while moving[Bug]: 

### ISSUE THREAD

**Issue by SubtilizerGGO** [Yesssssman/epicfightmod#1457]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Unknown-tried to remove potential suspected mods that may be known to cause this

### Minecraft Version

1.19.2

### What happened?

Hi there, everyone. Dunno if it's a bug for real, but when I use Epic Fight in my personal mash-up of mods, it seems that the armors, vanilla included, clip over in-between vanilla and epicfight movements.

![2023-11-17_16 17 50](https://github.com/Yesssssman/epicfightmod/assets/151190643/49477b1e-18ea-4b47-a9ec-7ab35fa1c1a3)
![2023-11-17_16 23 29](https://github.com/Yesssssman/epicfightmod/assets/151190643/675ab73a-7065-4a12-a20c-6bd8618eabf0)

Mod List:
![modlist1](https://github.com/Yesssssman/epicfightmod/assets/151190643/eb01037a-8045-4b4c-bda6-b3dd174472c2)
![modlist2](https://github.com/Yesssssman/epicfightmod/assets/151190643/d8be378b-ecaa-4ad2-ac6f-619984a27935)

**Comment by MetalKnight56** [comment]
100% a mod incompatibility. Find the culprit and tell us about it.

**Comment by SubtilizerGGO** [comment]
I can try, but as you can see, I have over 200 mods in there. That's gonna make it a pain to find lol.

**Comment by MetalKnight56** [comment]
> I can try, but as you can see, I have over 200 mods in there. That's gonna make it a pain to find lol.

Yea but it's your issue isn't it? It's not my problem it's yours, I'll just see if it's possible to fix the issue and that's it. If you don't want to find the culprit then that's on you, just let me know so I can close this report

**Comment by YunKo2** [comment]
> I can try, but as you can see, I have over 200 mods in there. That's gonna make it a pain to find lol.

It's probably Pehkui, you're character seems smaller than most minecraft character

**Comment by SubtilizerGGO** [comment]
> > I can try, but as you can see, I have over 200 mods in there. That's gonna make it a pain to find lol.
> 
> It's probably Pehkui, you're character seems smaller than most minecraft character

I've already tested that, pehkui is not the culprit. And took my damn time to sort out my mash-up and found out that the coremod of modular powersuits, numina, doesn't seem too fond of epic fight, lol. Dunno why it's still there, Closin'..
