### ISSUE TITLE
[Bug|Crash]: server only crash when loading,  (ClassMetadataNotFoundException LDLMetadataSection)

### ISSUE THREAD

**Issue by degoz16** [Yesssssman/epicfightmod#1458]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/4861795
https://www.curseforge.com/minecraft/mc-mods/gregtechceu-modern/files
### Minecraft Version

1.20.1

### What happened?

Crash, while trying to start dedicated server. Probably compatibility issue with **GTCEu modern** of latest version, because version before (1.0.13e) is working fine. The strange thing for me is that epic fight is trying to load client rendering code on the server and crashes. **Client is working fine.**

Latest log:
https://mclo.gs/hlTyNoW
Crash report:
https://mclo.gs/DpEXAB5

**Comment by Yesssssman** [comment]
Fixed in recent 1.20.1
