### ISSUE TITLE
[Suggestion]: opportunity to disabe first person rendering (except for the sword) and more configuration to mob animations

### ISSUE THREAD

**Issue by zireaelqqq** [Yesssssman/epicfightmod#1459]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

add the ability to disable character rendering in first person, add the ability to leave only the sword. This will give a big performance boost. It would also be nice to add the ability to configure which mobs will have their animation changed, for example pillarers (they don’t need them since there is no melee attack animation)

**Comment by MetalKnight56** [comment]
We'll overhaul first person animations as to add new options for ppl to enable or disable the rendering

**Comment by Yesssssman** [comment]
We added the option to 20.8.2. Thanks for your suggestion.
