### ISSUE TITLE
[Bug|Crash]:Crash from DivineRPG weapons

### ISSUE THREAD

**Issue by FortTundra** [Yesssssman/epicfightmod#1461]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

DivineRPG

### Minecraft Version

1.20.1

### What happened?

while using this mod and the mod DivineRPG the game crashes apon recieving a DivineRPG weapon/tool in hot bar or inventory, aswell as opening a container with said items inside. Armor does not seem to cause issue or crashes.After reloading after crash you can use the weapon or tool and open inventory until you obtain another weapon or open a chest containing one

**Comment by MetalKnight56** [comment]
Provide logs

**Comment by FortTundra** [comment]
Crash report: https://pastebin.com/eJG7Jcy6
Latest log: https://pastebin.com/eMTqzdMM
