### ISSUE TITLE
Please allow the mod entity to be patched.

### ISSUE THREAD

**Issue by karaagedesu1** [Yesssssman/epicfightmod#1463]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.19.2

### What's your suggestion?

This is also a bug report. When I try to use the datapack for 1.18.2 in version 1.19.2, it puts me into safe mode, I can use the datapack for mod weapons with no problem, but I cannot use the datapack for mod mobs.

**Comment by Yesssssman** [comment]
In 1.20.1, I added datapack editor screen that can add attributes & movesets for modded mobs
