### ISSUE TITLE
[Bug|Crash]: Reload Resource Pack tachi type weapons cannot use special abilities

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1464]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

https://github.com/Yesssssman/epicfightmod/assets/130232431/1aab9cf6-15f1-4244-aa01-67475c8b30f8

tachi type weapon overload resource packs are not working properly and special abilities cannot be released

**Comment by fzrdwa123456** [comment]
Forge 40.2.14
Epic Fight 18.5.18

**Comment by Yesssssman** [comment]
Fixed in 1.20.1
