### ISSUE TITLE
[Suggestion]: Config option for stamina

### ISSUE THREAD

**Issue by flarestone1** [Yesssssman/epicfightmod#1465]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.18.2

### What's your suggestion?

I think it would be good to have a config option for stamina, so we can customize its levels according to our preferences

**Comment by MetalKnight56** [comment]
What levels are you reffering to, gotta be a bit more specific on what options you want to see being added

**Comment by zKoffee** [comment]
> What levels are you reffering to, gotta be a bit more specific on what options you want to see being added

An option to set the base stamina at the level we want, without having to reconfigure it in chat every time the character dies, or restart the game.

**Comment by Yesssssman** [comment]
You can already do this with Minecraft commands

**Comment by Entys** [comment]
it's limited to 20, no more
