### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by undeadmartin** [Yesssssman/epicfightmod#1466]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Help, I am using the latest versions of efm and wom with not enough crashes and when I do it looks like this I will also leave you a report
[message.txt](https://github.com/Yesssssman/epicfightmod/files/13481923/message.txt)

**Comment by undeadmartin** [comment]
![WhatsApp Image 2023-11-27 at 21 13 56](https://github.com/Yesssssman/epicfightmod/assets/147748044/d07bcd3b-7dcc-4d90-8847-471aad231ff0)

**Comment by karaagedesu1** [comment]
Check the configuration carefully. The bug may be caused by a missing configuration.

**Comment by MetalKnight56** [comment]
As stated by @karaagedesu1, this issue can be caused by multiple wrong instances. I'd make sure to carefully check your configs, your game options and maybe try and remove faulty mods such as optifine, or possibly this notenough crashes.
