### ISSUE TITLE
[Bug|Crash]: Server crash with the wither and the dragon.

### ISSUE THREAD

**Issue by dalindarosa** [Yesssssman/epicfightmod#1467]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Hello! Excellent work with the mod. The bug that crashes the server is when the wither is summoned and one of his bombs hits one of the skeletons that he summons. We also tried going to the end and when the dragon bar appears, the server crashed.

**Comment by MetalKnight56** [comment]
attach logs

**Comment by dalindarosa** [comment]
[crash-2023-11-27_21.12.34-server.txt](https://github.com/Yesssssman/epicfightmod/files/13835338/crash-2023-11-27_21.12.34-server.txt)

**Comment by dalindarosa** [comment]
[crash-2023-11-27_20.39.38-server.txt](https://github.com/Yesssssman/epicfightmod/files/13835377/crash-2023-11-27_20.39.38-server.txt)

**Comment by MetalKnight56** [comment]
Issue is caused by Archlight a hybrid server enviroment that "supports" both the forge and bukkit api
