### ISSUE TITLE
[Bug|Crash]: Startup Crash

### ISSUE THREAD

**Issue by nnyxies** [Yesssssman/epicfightmod#1469]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight and/or Weapons of Miracles

### Minecraft Version

1.20.1

### What happened?

After I installed The new version of Epic Fight (20.6.1) and Weapons of Miracles (20.1.7.35),
when I start Minecraft, the game will always crash at startup unless I go back to the previous versions of both mods.

.
[crash-2023-11-29_20.31.36-client.txt](https://github.com/Yesssssman/epicfightmod/files/13501099/crash-2023-11-29_20.31.36-client.txt)

**Comment by cikovladimka** [comment]
I confirm this crash. It's really like that. Pls fix

**Comment by nnyxies** [comment]
In case someone's wandering through here, I'm just gonna say that it is fixed on the newest versions of both mods. Cheers!

**Comment by nnyxies** [comment]
In case someone's wandering through here, I'm just gonna say that it is fixed on the newest versions of both mods. Cheers!
