### ISSUE TITLE
Dash Attack and Weapon Special Attack doesn't effected by attackSpeed or potion

### ISSUE THREAD

**Issue by AKreedz** [Yesssssman/epicfightmod#147]
version 1.12.2-2.1.2

Dash Attack and Weapon Special Attack doesn't effected by attackSpeed or potion effect,that's weird

**Comment by Yesssssman** [comment]
Originally, that was what I intended, but now it seems a bit irrational. I'll fix it in the next update.

**Comment by AKreedz** [comment]
Thanks.By the way ,can you provide  the source code of 1.12.2?

**Comment by Yesssssman** [comment]
Yes, I'll do it soon.
