### ISSUE TITLE
[Bug| tlauncher tl skin cape doesn't render my account's skin

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [Yesssssman/epicfightmod#1476]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

tlauncher (not a mod)

### Minecraft Version

1.20.1

### What happened?

darn it, i don't like using the regular skin

**Comment by mrdragonblack** [comment]
check your tl account is support skin or try to remove mods or update your mods outdated mods may cause the bug

sorry for the language

**Comment by MetalKnight56** [comment]
We do not support TLauncher or other cracked launchers...

**Comment by EeryGlue493975** [comment]
tlauncher suck's at all
