### ISSUE TITLE
[Bug|Crash]: Weapons of miracles(?)

### ISSUE THREAD

**Issue by Acromo** [Yesssssman/epicfightmod#1477]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

We are using a few mods to play in a server, everyone has the same mod folder, however, there's one person who seems to have problems with a few of the weapons from the Weapons Of Miracles add-on, and these are (at least so far): When equipping the Antitheus weapon, after switching to a different slot on the hotbar the particles stay in motion, after that, switching items again crashes the game, also, when using Torment, his skill counter constantly changes from 1 to 0 to 1 and can't use it on command, at random times it activates during combat, torment also causes that he cannot control the charge (The special skill to run charging an attack and switching between 3 types of hits) as once he starts using it it won't let him stop until his stamina has run out, alternatively, there was one instance when it apparently worked, although for it to work the charge had to be cancelled with a normal attack and the next one would be the charge finisher.

Mods in alphabetical order (All for Minecraft Java 1.20.1 and using Forge 47.2.6):

Air Hop
Alex Caves
Alex Mobs
Arcane Lanterns
Architectury
Artifacts
Balm
Barterin Station
Biomes O Plenty
BOMD
Born in Chaos
Caelus
Citadel
Cloth Config
Collective
Colytra
Comforts
Cosmetic Armor Reworked
Curios
Diagonal Fences
Diagonal Windows
Double Doors
Easy Anvils
Easy Magic
Echo Chest
Enchanting Infuser
Epic Fight
Falling Tree
Farmers Delight
Fruits Delight
Geckolib
Jei
Journeymap
JRFTL (Just Another Rotten Flesh to Leather Mod)
Just Leveling
L_Enders Cataclysm
LeavesBeGone
Legendary Monsters
All of Macaws mods + their compats for Biomes o Plenty
Medieval Buildings
Moonlight
Nether Chested
Nethers Delight
Nyfs Spiders
Permanent Sponges
Practical Plushies
PuzzlesLib
Rainbowreef
Reusable Rockets
Revamped Wolf
Sophisticated Backpacks
Sophisticated Core
Structure Gel
Supplementaries
Suppsquared (Supplementaries Squared)
Terra Blender
The Conjurer
Trading Post
Trial Chambers Decorations
Twilight Forest
Universal Bonemeal
Universal Enchants
Visual Workbench
Waystones
Wendigo Mod
Witherstorm
Wood Enjoyer

Thanks in advance for any possible help and apologies for any inconvenience.

**Comment by mrdragonblack** [comment]
try  to remove all mods and try to add 1 by 1 by maybe it fix this maybe because mod conflict

**Comment by MetalKnight56** [comment]
Add the crashlogs perhaps?

**Comment by Alvareto136** [comment]
Try doing a backup and then update your modloader (Forge) to version 47.2.17 or newer. You might need to update many mods client and server side, but I think it's better to keep those up to date. Months ago I also had some problems with WoM and Epic Fight which disappeared after updating.
