### ISSUE TITLE
[Bug|Crash]: java.lang.ClassNotFoundException: yesman.epicfight.world.damagesource.SourceTag

### ISSUE THREAD

**Issue by SpiiWise** [Yesssssman/epicfightmod#1479]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Weapons of Miracles

### Minecraft Version

1.20.1

### What happened?

java.lang.ClassNotFoundException: yesman.epicfight.world.damagesource.SourceTag
Quando tento iniciar o jogo ele me entrega essa mensagem, sabe como resolver?

**Comment by TeddyBear-YT** [comment]
Update the mod.
