### ISSUE TITLE
Aim Indicator not showing up, unknown cause.

### ISSUE THREAD

**Issue by Portergoth** [Yesssssman/epicfightmod#148]
Hello!

I'm just writing to inform you that for some reason, the aim indicator isn't showing up when I use the mod in the modpack I am assembling for my own personal use.  I'm using forge version 36.1.1, with the latest version of optifine installed.  In addition, I am using Macaw's Roofs, Macaw's Furniture, Dungeons Plus, Move Plus, LevelHearts, Structure Gel API, and also Xaero's Minimap.

No expectations to magically fix this, I'm just providing information 👯‍♀️ 

Update:  Tried a few things out, shaderpacks seem to disable the aim indicator

**Comment by Yesssssman** [comment]
The aim helper doesn't show up if you were set the graphic option to fabulous. and as you said, shaders also turn off the aim helper. I'm not good at graphics so... I recommend using the Shoulder Surfing mod which points to the position where you look if you still want to use shader or fabulous graphic.

![2021-04-05_17 38 06](https://user-images.githubusercontent.com/79469058/113555330-bb9d1880-9635-11eb-98cd-b78eb17474fc.png)
