### ISSUE TITLE
[Bug|Crash]: crash when attack 1.20.1

### ISSUE THREAD

**Issue by matigol48** [Yesssssman/epicfightmod#1480]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.20.1

### What happened?

when i attack or a recieve an attack from a mob the game crash
error:
Internal Exception: java.lang.IndexOutOfBoundsException: reader Index(13) + length(4) exceeds writerIndex(14): UnpooledSlicedByteBuf(ridx: 13, widx: 14, cap: 14/14, unwrapped:
PooledUnsafeDirectByteBuf(ridx: 0, widx: 14, cap: 14))

**Comment by LisMorozniy** [comment]
Had same problem, it was caused by Dodge Master skill. Check if you have this skill on.

**Comment by MetalKnight56** [comment]
install spit it out and try to get the error again please
https://www.curseforge.com/minecraft/mc-mods/spit-it-out
