### ISSUE TITLE
[Bug|Crash]: Startup error in 1.20.1

### ISSUE THREAD

**Issue by NecroPraimer** [Yesssssman/epicfightmod#1481]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

_EpicFight - 20.6.3_

### Minecraft Version

1.20.1

### What happened?

[crash-2023-12-13_22.36.03-fml.txt](https://github.com/Yesssssman/epicfightmod/files/13668110/crash-2023-12-13_22.36.03-fml.txt)
It won't let me start the game i always get an error
![image](https://github.com/Yesssssman/epicfightmod/assets/36804792/5269a900-607f-4804-b4a8-c0478f0dfbdd)

**Comment by Yesssssman** [comment]
The old Epic Paragliders is not compatible with recent Epic Fight builds. Please remove the mod or use old Epic Fight version
