### ISSUE TITLE
[Suggestion]: Improve Mining in Combat.

### ISSUE THREAD

**Issue by XM666-Dev** [Yesssssman/epicfightmod#1482]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

When I combat with small mobs, such as small zombies, I can't use weapon skill because of targeting at ground blocks. Using weapon skill need long press, so the player starts to mine. That's very awful when you combat with small mobs. Please make player prefer using weapon skill than mining when he is targeting at blocks but prefer mining when shift key is pressed.
Sorry my English isn't well.

**Comment by Yesssssman** [comment]
We already have a similar system where you can categorize your items for battle & mining mode. it automatically switches the player mode based on the held item in the player's main hand. That feature is too much detailed.
