### ISSUE TITLE
[Suggestion]: Support with First Person render mod

### ISSUE THREAD

**Issue by LORDMUu** [Yesssssman/epicfightmod#1484]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

https://www.curseforge.com/minecraft/mc-mods/first-person-model/files

### Minecraft Version

1.19.2

### What's your suggestion?

Please support with first person mod for more realistic animations

**Comment by MetalKnight56** [comment]
It's on our plans...

**Comment by XSwiftxX** [comment]
> It's on our plans...
when will you fix the head model of the epic fight mod covering the screen when using the first person mod , and also when i try to break a block the frames extremely drop

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Sorry but please consider we weren't able to reflect all the changes to older versions.

**Comment by Striker5034** [comment]
i don't understand what the "fix" was. Seems to me that you made it so whenever i go into battle mode,the rendering of the 'first person mod' just disables.How is this a fix? the first person mod just stops working while in battle mode.I could have done this myself by tweaking some keybinds.

**Comment by anuscat69420-arch** [comment]
shit sucks

**Comment by guivnf** [comment]
> i don't understand what the "fix" was. Seems to me that you made it so whenever i go into battle mode,the rendering of the 'first person mod' just disables.How is this a fix? the first person mod just stops working while in battle mode.I could have done this myself by tweaking some keybinds.

The fix was that we've completely remade the first person system. You're now able to create first person specific animations, essentially making it more immersive and realistic. You also have other options for customization that are a bit more intricate to get into, but now there isn't really a need to use the first person model mod with epic fight anymore.
