### ISSUE TITLE
[Suggestion]: Custom waving sound compatible with other mod weapons

### ISSUE THREAD

**Issue by GalaxyZEROX** [Yesssssman/epicfightmod#1489]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

SurvivalPlus-Lightsabers

### Minecraft Version

1.18.2

### What's your suggestion?

https://github.com/Yesssssman/epicfightmod/assets/73332842/eedfdf28-287f-4f4e-8973-9cc5ce6e5a9f

Hello, can you add a custom waving sound compatible with other mod weapons? The lightsaber sounds like an iron sword, which is very strange.

**Comment by fzrdwa123456** [comment]
The issue you mentioned was already available in 1.20.1 using packet custom sound, but not in 1.18.2
![屏幕截图 2023-12-24 003229](https://github.com/Yesssssman/epicfightmod/assets/130232431/3465f311-b7c4-452d-afbe-cc04ad46a3e7)

**Comment by GalaxyZEROX** [comment]
Then, is it possible to transplant the function of custom waving sound to version 1.18.2 in the future? Version 1.20.1 does not have lightsaber mod.

**Comment by fzrdwa123456** [comment]
> Then, is it possible to transplant the function of custom waving sound to version 1.18.2 in the future? Version 1.20.1 does not have lightsaber mod.

No, new features only exist in the latest version and will not be backported, which is what they said before porting past may cause some problems

**Comment by fzrdwa123456** [comment]
> Then, is it possible to transplant the function of custom waving sound to version 1.18.2 in the future? Version 1.20.1 does not have lightsaber mod.

Try to use the latest version they support because some issues may not have been fixed in older versions
