### ISSUE TITLE
[Bug|Crash]: neoforge causes crash due to version number

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [Yesssssman/epicfightmod#1491]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://modrinth.com/mod/epic-fight/version/20.6.3

### Minecraft Version

1.20.1

### What happened?

neoforge crashes immediately, most likely because the forge version is a different number. in case you are unaware: forge only has a singular maintainer, not a whole team. neoforge consists of the entire old forge team. https://neoforged.net/ i am labeling this as an issue as forge is entirely too unstable in the current version.

**Comment by OrdinaryCloverOC** [comment]
https://modrinth.com/mod/epic-fight/version/20.5.13 this version of the mod appears to work entirely fine for those wondering.

**Comment by MetalKnight56** [comment]
NeoForged is not yet supported. Once we update the mod to 1.20.2+ we'll move the mod to NeoForged...

**Comment by deadspidervenom** [comment]
> NeoForged is not yet supported. Once we update the mod to 1.20.2+ we'll move the mod to NeoForged...

while i understand this is still underway, it seems most of the modding community is settling on 1.20.1 as the "modding version". Would it be possible to get a adjustment for it? From my understanding neoforge is just forge, so you should just have to remove or adjust the force required forge version to the request version.

**Comment by MetalKnight56** [comment]
> while i understand this is still underway, it seems most of the modding community is settling on 1.20.1 as the "modding version". Would it be possible to get a adjustment for it? From my understanding neoforge is just forge, so you should just have to remove or adjust the force required forge version to the request version.

Neoforged is not just forge it has a bunch of changes we will not deal with right now. Neoforged support will arrive after 1.20.1

**Comment by deadspidervenom** [comment]
so you are not gonna support neoforge till the next major modding version. Aight.

**Comment by Joshua-The-Tall** [comment]
Going to ask if anyone has found a workaround, as the modding community is still largely focused on 1.20.1, and we'd love to use the mod. Version20.6.3 seems to throw an incompatibility error as well :(

**Comment by deadspidervenom** [comment]
If you read the post, you would know the devs do not consider "1.20.1" to be the next major modding version, as they did not plan to  add in neoforge compatibility till after their 1.20.2 release. So there will be no update unless someone else makes the update or a compatibility patch. Dont expect this mod on neoforge for another 3-5 years at best. If this mod is even still relevant at that time, which it likely wont be, since other mods have taken its place due to the forced lack of compatibility.
