### ISSUE TITLE
[Suggestion]: Spartan Weaponry Compatibility

### ISSUE THREAD

**Issue by TheEffortFighter** [Yesssssman/epicfightmod#1492]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

Spartan Weaponry/Shields

### Minecraft Version

1.18.2

### What's your suggestion?

Just the title, asking for built-in compatibility with spartan weaponry's weapons.

**Comment by MetalKnight56** [comment]
This is not something we can do on our side, it all depends on the spartan weapondry developers...
