### ISSUE TITLE
[Bug|Crash]:   Error when attacking enemy Possibly caused by apotheosis

### ISSUE THREAD

**Issue by nefertus** [Yesssssman/epicfightmod#1493]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

apotheosis

### Minecraft Version

1.20.1

### What happened?

I'm not familiar with this so please check the error log

[crash-2023-12-28_18.56.06-server.txt](https://github.com/Yesssssman/epicfightmod/files/13785510/crash-2023-12-28_18.56.06-server.txt)

**Comment by MetalKnight56** [comment]
Closing issue as user has multiple fabric mods + closed source mods... 

* Remove all mods and slowly add them back until you find the culprit. Once you find it, send it here.
