### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by FrostbearDeluxe** [Yesssssman/epicfightmod#1494]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.19.2

### What happened?

when i try to attack, or a mobs/player attacks the game kicks me of the server, the error it appears is this
![imagen_2023-12-29_180849410](https://github.com/Yesssssman/epicfightmod/assets/80645869/3aa84e3b-96c9-4383-8395-503efa62777e)

**Comment by MetalKnight56** [comment]
install spit it out and try to get the error again please
https://www.curseforge.com/minecraft/mc-mods/spit-it-out
