### ISSUE TITLE
[Bug|visual] Visual bug with Jet and Elia's Armors

### ISSUE THREAD

**Issue by epicthejet** [Yesssssman/epicfightmod#1496]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/jet-and-elias-armors

### Minecraft Version

1.18.2

### What happened?

As of EF version 18.5.16, 19.5.16, and 20.5.16 the arms on this armor set as well as a few others in this mod dont bend at the elbows properly. They used to do so in every version prior. Is there anything you can do about this or is it something I need to do? If you need more details I can give whatever you need.

Here are some examples of the armor model not properly bending with the animations
https://medal.tv/games/minecraft/clips/1Nd2Fgt0AnwMuz/o6urPyTR9z6q?invite=cr-MSxkUHEsMzQxNzY0Mjgs?mobilebypass=true
https://medal.tv/games/minecraft/clips/1Nd2Fgt0AnwMuz/o6urPyTR9z6q?invite=cr-MSxkUHEsMzQxNzY0Mjgs?mobilebypass=true
https://medal.tv/games/minecraft/clips/1Nd2jUhKWmzVqs/d1337qhxzbnJ?invite=cr-MSxUMFgsMzQxNzY0Mjgs
https://medal.tv/games/minecraft/clips/1Nd1J5J0so4GAg/oKvNTSRl0mDV?invite=cr-MSxyWDMsMzQxNzY0Mjgs?mobilebypass=true
https://medal.tv/games/minecraft/clips/1Nd1tfuh37F_qc/grUr6ysHIamw?invite=cr-MSxobGUsMzQxNzY0Mjgs?mobilebypass=true

This was recorded on the the latest version of EF for 1.18.2, however you can easily reproduce this on any other version of minecraft

EDIT: its 18.5.17, 19.5.17, and 20.5.17 when the visual issues in the arms begin to show up, I was mistaken

**Comment by MetalKnight56** [comment]
> ### Have you checked if a similar issue is already reported by someone else?
> * [x]  I checked there are no similar issues have been reported.
> 
> ### Have you read the support policy?
> * [x]  I read it and I accept the policy.
> 
> ### Are you using the latest Epic Fight and recommended Forge version?
> * [x]  I checked I'm using latest Epic Fight and recommended Forge version.
> 
> ### Is this issue related to mod incompatibility?
> * [ ]  This is a mod compatibility issue and I'm aware of the problem.
> 
> ### The mod
> [curseforge.com/minecraft/mc-mods/jet-and-elias-armors](https://www.curseforge.com/minecraft/mc-mods/jet-and-elias-armors)
> 
> ### Minecraft Version
> 1.18.2
> 
> ### What happened?
> As of EF version 18.5.16, 19.5.16, and 20.5.16 the arms on this armor set as well as a few others in this mod dont bend at the elbows properly. They used to do so in every version prior. Is there anything you can do about this or is it something I need to do? If you need more details I can give whatever you need.
> 
> Here are some examples of the armor model not properly bending with the animations [medal.tv/games/minecraft/clips/1Nd2Fgt0AnwMuz/o6urPyTR9z6q?invite=cr-MSxkUHEsMzQxNzY0Mjgs?mobilebypass=true](https://medal.tv/games/minecraft/clips/1Nd2Fgt0AnwMuz/o6urPyTR9z6q?invite=cr-MSxkUHEsMzQxNzY0Mjgs?mobilebypass=true) [medal.tv/games/minecraft/clips/1Nd2Fgt0AnwMuz/o6urPyTR9z6q?invite=cr-MSxkUHEsMzQxNzY0Mjgs?mobilebypass=true](https://medal.tv/games/minecraft/clips/1Nd2Fgt0AnwMuz/o6urPyTR9z6q?invite=cr-MSxkUHEsMzQxNzY0Mjgs?mobilebypass=true) [medal.tv/games/minecraft/clips/1Nd2jUhKWmzVqs/d1337qhxzbnJ?invite=cr-MSxUMFgsMzQxNzY0Mjgs](https://medal.tv/games/minecraft/clips/1Nd2jUhKWmzVqs/d1337qhxzbnJ?invite=cr-MSxUMFgsMzQxNzY0Mjgs) [medal.tv/games/minecraft/clips/1Nd1J5J0so4GAg/oKvNTSRl0mDV?invite=cr-MSxyWDMsMzQxNzY0Mjgs?mobilebypass=true](https://medal.tv/games/minecraft/clips/1Nd1J5J0so4GAg/oKvNTSRl0mDV?invite=cr-MSxyWDMsMzQxNzY0Mjgs?mobilebypass=true) [medal.tv/games/minecraft/clips/1Nd1tfuh37F_qc/grUr6ysHIamw?invite=cr-MSxobGUsMzQxNzY0Mjgs?mobilebypass=true](https://medal.tv/games/minecraft/clips/1Nd1tfuh37F_qc/grUr6ysHIamw?invite=cr-MSxobGUsMzQxNzY0Mjgs?mobilebypass=true)
> 
> This was recorded on the the latest version of EF for 1.18.2, however you can easily reproduce this on any other version of minecraft

Can you please open source your mod because its very hard for us to figure the issue with just this ammount of info.

**Comment by epicthejet** [comment]
Id be happy to. This is an mcreator mod so would I just send a sharable zip of the workspace?

**Comment by MetalKnight56** [comment]
> Id be happy to. This is an mcreator mod so would I just send a sharable zip of the workspace?

Could you try putting it on github?

**Comment by MetalKnight56** [comment]
> > Id be happy to. This is an mcreator mod so would I just send a sharable zip of the workspace?
> 
> Could you try putting it on github?
(But i guess a zip with all the files of the mod should also be fine)

**Comment by epicthejet** [comment]
I dont know github all that well so I'll send the zip of the mod 
[JetAndEliasArmors1.4-1.18.2.zip](https://github.com/Yesssssman/epicfightmod/files/13854396/JetAndEliasArmors1.4-1.18.2.zip)

**Comment by epicthejet** [comment]
Interestingly enough, in the 1.20.1 version of the mod, the elbow bends are fine, however now theres something wrong with how the back of the armor moves. It used to bend with the model but now it doesnt bend at all. Theres also another visual issue when walking that I showed off here but I dont know how to describe it. Youll know it when you see it.

Here's the video showing the visual bugs in the latest version of EF 1.20.1 
https://youtu.be/mkyASwhLiBM

**Comment by MetalKnight56** [comment]
![image](https://github.com/Yesssssman/epicfightmod/assets/77132244/8a862704-d0d9-415b-be3e-23570374a9e2)

Issue was fixed in local space, and will be launched for use in the upcoming update.

Model regards each attached cube as "Arm" part (leftArm, rightArm) which is a part of vanilla model, so in the old versions, it was baked by vanilla transformation algorithm which doesn't calculates the center position of cube and just makes all cubes contain the bending parts

(If this issue persists after the next update, please post a comment here and ping @MetalKnight56 ok? )

**Comment by epicthejet** [comment]
Will do. Do you plan on looking into the issue with 1.20.1 as well? I posted a video and can provide whatever you need in regards to that

**Comment by MetalKnight56** [comment]
> Will do. Do you plan on looking into the issue with 1.20.1 as well? I posted a video and can provide whatever you need in regards to that

Most likely will be fixed across all versions, from 1.18.2 - 1.20.1

**Comment by Yesssssman** [comment]
Fixed
