### ISSUE TITLE
[Bug|Crash]: incompatibility with Timeless and classics mod, crashes during start up 

### ISSUE THREAD

**Issue by Kalkoen31** [Yesssssman/epicfightmod#1499]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns-tac

### Minecraft Version

1.18.2

### What happened?

I launch the game with the Epic fight mod and the Timeless and Classics mod and it crashes during start up.

The game crashed whilst initializing game Error: java.util.ConcurrentModificationException: null

Forge 1.18.2-40.2.17
Epic Fight 18.5.19
Timeless and Classics 0.3.10.1

I added the crash report, latest log, and launcher log:

[crash-2024-01-11_19.39.00-client.txt](https://github.com/Yesssssman/epicfightmod/files/13907168/crash-2024-01-11_19.39.00-client.txt)
[latest.log](https://github.com/Yesssssman/epicfightmod/files/13907170/latest.log)
[launcher_log.txt](https://github.com/Yesssssman/epicfightmod/files/13907173/launcher_log.txt)

**Comment by Yesssssman** [comment]
As you can see on the log, it doesn't suggest the clue that this crash was caused by Epic Fight and Timeless and Classics incompatibility.

![image](https://github.com/Yesssssman/epicfightmod/assets/79469058/9ee9bfc1-0f3e-4736-a188-ee3b42ca6df3)

Could you at least try removing all other mods and leaving only those two mods then see if the same crash occurs?

**Comment by Kalkoen31** [comment]
Ok, here it still crashes. This time I only used the timeless and classics mod (+ its dependency, which is framework 0.4.3), and the epic fight mod (18.5.19). Here are the files:

[crash-2024-01-27_11.12.51-client.txt](https://github.com/Yesssssman/epicfightmod/files/14071924/crash-2024-01-27_11.12.51-client.txt)
[latest.log](https://github.com/Yesssssman/epicfightmod/files/14071925/latest.log)
[launcher_log.txt](https://github.com/Yesssssman/epicfightmod/files/14071928/launcher_log.txt)

btw last time I figured out it were these 2 mods it was because I did a binary search to find out which mods were conflicting

**Comment by Kalkoen31** [comment]
I also just tested it a 3rd time, but with the 18.5.20 version of epic fight. That also still gives the ConcurrentModificationException error.

**Comment by 286799714** [comment]
Hello, I am a programmer of tac mod. I'll try to investigate this bug as well. My guess is that our gun model loading triggered this bug. We use ForgeModelBakery.addSpecialModel() to load the model. Anyway, I hope we can exchange our findings in this issue in the future.

**Comment by Kalkoen31** [comment]
Issue has been resolved with the new Timeless and Classics Zero version of the mod. ( https://github.com/MCModderAnchor/TACZ )
