### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by thedeerirty** [Yesssssman/epicfightmod#150]
[latest.log](https://github.com/Yesssssman/epicfightmod/files/6255602/latest.log)
[crash-2021-04-04_19.11.57-fml.txt](https://github.com/Yesssssman/epicfightmod/files/6255604/crash-2021-04-04_19.11.57-fml.txt)

Here's the report and log, getting this crash booting on latest version.

**Comment by Yesssssman** [comment]
Your Forge version is too old to run the latest version of EPM. Please update the forge first.
