### ISSUE TITLE
[Bug|Crash]: Epic Fights not on 47.2.0 For Curseforge! PLS HELP! 🙏

### ISSUE THREAD

**Issue by giggachad824** [Yesssssman/epicfightmod#1501]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

when I start my mod pack it wouldn't allow me to run the mod with it, because my curse forge mod pack is in 47.2.0. I have checked everything I could, and it all leads to the curse forge not being 47.2.0. 

Is there any way for me to get epic fight on curse forge 47.2.0. Thank!

**Comment by Yesssssman** [comment]
Since the Forge version keeps advancing, we don't support the older version of Forge or specific version of it. Please update your forge or use a proper version of Epic fight.
