### ISSUE TITLE
[Bug|Crash]: Some issues when playing with friend using LAN

### ISSUE THREAD

**Issue by HayaseYuuka777** [Yesssssman/epicfightmod#1503]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Weapons of Miracles

### Minecraft Version

1.18.2

### What happened?

I only know a little English, so don't blame grammar problems.
Anyway ,when I play with friends ,They can only use jump attack,but cannot use common attacks. I don't know what the problem is. Maybe is Epicfight bugs? or Weapons of Miracles bugs?  But I don't have any problems, Singleplayer is no problems too.
By the way, I am the host LAN.
I hope you can provide a solution,Thanks!

**Comment by Yesssssman** [comment]
There was a bug that every skill was messed up if you installed Epic Fight and Weapons of Miracles in the older version. Check if you're still using an old version and report it here again if the same problem persists in the latest version.

**Comment by TheDGhost** [comment]
I have same problem. 1.20.1. 
On the 30.6.3, or .4 EF version is definitly not working with WoM. 
On 30.6.2 my friend have jump-attack bug.  I try fix it, but... I'm to bad in it. 
How fix it?

**Comment by MetalKnight56** [comment]
> I have same problem. 1.20.1. On the 30.6.3, or .4 EF version is definitly not working with WoM. On 30.6.2 my friend have jump-attack bug. I try fix it, but... I'm to bad in it. How fix it?

attach all of your logs, including the sever's logs (if on dedicated), specially attach debug. If you can also attach some footage and your modlist...
