### ISSUE TITLE
[Suggestion]: Request to add gun animations, and not automatically adapt, but as an option. 

### ISSUE THREAD

**Issue by LSDGQ** [Yesssssman/epicfightmod#1504]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

Timeless and Classics Guns

### Minecraft Version

1.18.2

### What's your suggestion?

I hope to add animated models for guns, but not automatically adapt, and like you give other regular weapon mods [swords and so on], let players configure by themselves. I don’t have much coding experience and I don’t know if this is easy. I just hope you can give a gun animation option, because the third-person animations of gun mods are usually very bad.

I converted English through translation software There may be some errors, please forgive me

**Comment by fzrdwa123456** [comment]
I remember they said that 1.18.2 and 1.19.2 would no longer be updated
