### ISSUE TITLE
[Bug|Crash]: Right-clicking causes a crash

### ISSUE THREAD

**Issue by d39052** [Yesssssman/epicfightmod#1507]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

geckolib

### Minecraft Version

1.20.1

### What happened?

I run a server with mohist-1.20.1-517-server. I have both geckolib-forge-1.20.1-4.4 and EpicFight-20.6.3 on the client and server. when I right click with the weapon, everything works fine on the server, but the client pops up with the following prompt and can no longer access the server. The server doesn't have any error messages either.

![DB22CE1CC25063E8E3AAB722DF3FD09A](https://github.com/Yesssssman/epicfightmod/assets/157216847/e5e945c4-0a1a-4b04-99f6-5f7c4310f718)

**Comment by WahahaOnly** [comment]
The same problem happens with the katana (uchigatana)

**Comment by MetalKnight56** [comment]
1. Update the mod
2. Stop using a hybrid server loader
3. If you have Weapons Of miracles and have this issue, read their mod page, and install "Spit It Out" as is stated there
4. Missing logs
