### ISSUE TITLE
Special attack for type "AXE" doesn't work for modded weapons

### ISSUE THREAD

**Issue by Tennik** [Yesssssman/epicfightmod#151]
Hi! I have tried the latest version of mod for 1.12.2 and tried to add modded items in config file using your video guide. Everything works fine, but i found that special attack for weapon type "AXE" doen't work in battle mod. Here are some screenshots with my problem and my config file:
![2021-04-05_09 31 28](https://user-images.githubusercontent.com/12845200/113564151-867ecf00-9611-11eb-8247-920b15da6a78.png)
![2021-04-05_09 34 11](https://user-images.githubusercontent.com/12845200/113564156-87176580-9611-11eb-831b-2ae07c3ebf1b.png)

[epicfight.txt](https://github.com/Yesssssman/epicfightmod/files/6257662/epicfight.txt)

**Comment by Yesssssman** [comment]
Um.... this is my mistake. I always want to be perfect, but It's so hard. 😅 Anyway, thanks for reporting this and this will be fixed soon!

**Comment by Tennik** [comment]
> Um.... this is my mistake. I always want to be perfect, but It's so hard. 😅 Anyway, thanks for reporting this and this will be fixed soon!

Ok, thanks, will wait for it! :)
