### ISSUE TITLE
[Bug|Crash]: Impact block fully drains with arrows

### ISSUE THREAD

**Issue by Storm-930** [Yesssssman/epicfightmod#1513]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

With the skill Impact Block is learnt, using a compatible weapon, if an enemy (skeletons and pillagers were tested) shoots you while you're blocking, all of your stamina gets drained and a guard multiplier of 3.8 appears. Only happens with arrows as far as I'm aware. Melee attacks and explosions are blocked normally. Do note that you do not falter from getting attacked on full stamina drain.

**Comment by Yesssssman** [comment]
Thank you for reporting. This bug has been fixed in the latest version.
