### ISSUE TITLE
[Bug|Crash]: EpicFight-19.5.20 CRASH ON STARTUP

### ISSUE THREAD

**Issue by Minebrah** [Yesssssman/epicfightmod#1514]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

EpicFight-19.5.20

### Minecraft Version

1.19.2

### What happened?

https://gist.github.com/Minebrah/9565aadebce9feb4de6c57d9b0c0c47a

**Comment by Yesssssman** [comment]
You have an invalid weapon type name in your datapack. Check if any other values are types except this: https://epicfight-docs.readthedocs.io/Guides/page2/#onetwo-handed-weapon-file

![image](https://github.com/Yesssssman/epicfightmod/assets/79469058/d577b42d-383a-47db-b8b0-8467f2010cda)

**Comment by TerraShiii** [comment]
I've been consistently facing the same issue, how am I meant to change the values within the datapack if world creation fails and therefore there is no datapack to edit?
