### ISSUE TITLE
[Bug|Crash]: The current module conflicts with "Callable Horses."

### ISSUE THREAD

**Issue by chunye-shanhui** [Yesssssman/epicfightmod#1518]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/callable-horses

### Minecraft Version

1.20.1

### What happened?

When both "Callable Horses" and "Epic Fight" are loaded simultaneously, it causes the module functionality of "Callable Horses" to become disabled. This manifests as an inability to set it as a personal mount.

**Comment by MetalKnight56** [comment]
attach some logs and footage

**Comment by chunye-shanhui** [comment]
Sure, here are the logs and screenshots.
https://mclo.gs/rpspEZa
![01](https://github.com/Yesssssman/epicfightmod/assets/123534818/1b04efe4-373c-4b3c-ac8a-ff4abec689cb)

**Comment by chunye-shanhui** [comment]
It only causes another module to be unusable, but this module functions perfectly fine. So, I'm not sure if these log files can provide any assistance for you.

**Comment by MetalKnight56** [comment]
> Sure, here are the logs and screenshots. https://mclo.gs/rpspEZa ![01](https://private-user-images.githubusercontent.com/123534818/300240202-1b04efe4-373c-4b3c-ac8a-ff4abec689cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0Njc5NDksIm5iZiI6MTcwNjQ2NzY0OSwicGF0aCI6Ii8xMjM1MzQ4MTgvMzAwMjQwMjAyLTFiMDRlZmU0LTM3M2MtNGIzYy1hYzhhLWZmNGFiZWM2ODljYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOFQxODQ3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmUwYmE3MGZjZTQ4MzhlMTZiODA0Y2MzYmE2NjIxZjk2NTNlM2UwZWQ2YjFiZmE2Y2I0NDU4YjU2ZjcxZjU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5tQ_LIoVhJbh6xmGenD9JMc_f8ouOty6s32I0z4Gvas)

remove all other mods except epic fight and callable horses and try again. Also need the new logs and some new footage.

**Comment by chunye-shanhui** [comment]
If only these two mods are added, there are no issues with functionality. Therefore, is this situation caused by the indirect impact of other mods?
（https://mclo.gs/57Emh6e）
Moreover, if I later add other mods back in, there won't be any issues. However, if I recreate the world, the functionality becomes abnormal again.

**Comment by MetalKnight56** [comment]
> If only these two mods are added, there are no issues with functionality. Therefore, is this situation caused by the indirect impact of other mods? （[https://mclo.gs/57Emh6e）](https://mclo.gs/57Emh6e%EF%BC%89) Moreover, if I later add other mods back in, there won't be any issues. However, if I recreate the world, the functionality becomes abnormal again.

If only the two are added, and no issue arises, then it's most likely a third mod interfeering.

**Comment by chunye-shanhui** [comment]
"May I ask what should I do? Currently, it does seem that the issue is caused by the third module. However, if I temporarily disable the 'Epic Fight' module, the functionality works fine."

**Comment by chunye-shanhui** [comment]
> > If only these two mods are added, there are no issues with functionality. Therefore, is this situation caused by the indirect impact of other mods? （[https://mclo.gs/57Emh6e）](https://mclo.gs/57Emh6e%EF%BC%89) Moreover, if I later add other mods back in, there won't be any issues. However, if I recreate the world, the functionality becomes abnormal again.
> 
> If only the two are added, and no issue arises, then it's most likely a third mod interfeering.

"May I ask what should I do? Currently, it does seem that the issue is caused by the third module. However, if I temporarily disable the 'Epic Fight' module, the functionality works fine."

**Comment by Meidde** [comment]
@chunye-shanhui Did you find any solution? I used these mods together last year, but they were old versions in this case, I think maybe there is a version that works, because from what I saw no one cares about this error

**Comment by Yesssssman** [comment]
> Sure, here are the logs and screenshots. https://mclo.gs/rpspEZa ![01](https://private-user-images.githubusercontent.com/123534818/300240202-1b04efe4-373c-4b3c-ac8a-ff4abec689cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNTgyMjUsIm5iZiI6MTcyMzM1NzkyNSwicGF0aCI6Ii8xMjM1MzQ4MTgvMzAwMjQwMjAyLTFiMDRlZmU0LTM3M2MtNGIzYy1hYzhhLWZmNGFiZWM2ODljYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQwNjMyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjA4ZmZhMmQxYmI0NjlhNjEzNGUwZDk2MWM0NmEzYzJhYTQ3MTdjNTQ4NjU3NzM5NjE3OTQ5ZGJmMTQ5MGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i9aJkAm5pYE94x9UyDctB2Emh0iQ5jm_Xl6PB4l_JKk)

I only can see the physics mod spit out some error messages in your log. Please try removing it
