### ISSUE TITLE
Problems with config files

### ISSUE THREAD

**Issue by StLankowski** [Yesssssman/epicfightmod#152]
I tried to change the cofig file of an armor (custom model) but it did not work, and I don"t know why?
![2021-04-05_19 31 01](https://user-images.githubusercontent.com/80618694/113604821-1474ad00-9646-11eb-8acc-3f0e52cb2e80.png)

The config for the helmet:

[custom_armor.Griefer_Helmet]
		stun_armor = 0.75
		weight = 5
		registry_name = "savageandravage:griefer_helmet"

**Comment by Yesssssman** [comment]
Version?

**Comment by StLankowski** [comment]
> Version?

Minecraft version: 1.16.5
Mod Version: 3.1.3

**Comment by Yesssssman** [comment]
Which doesn't work? Are the values ​​you set not being applied properly?

**Comment by StLankowski** [comment]
Sorry for not answearing for so long.
It seems that the mod doesn't see a cofig file at all. I tried changing armors- Still the same bug with textures.
Tried changing weapones- weird staff happened. I downloaded a cofig file version compatible with spartan Weaponery, and there was nothing missing in config file. but The game crashed instantly. On launch.
