### ISSUE TITLE
[Bug|Crash]: Internal Exception: java.langNullPointerException: Cannot invoke "yesman.epicfight.skill.SkillDataManager$SkillDataKey.getValueType()" because the return value of "yesman.epicfight.skill.SkillDataManager$SkillDataManager$SkillDataKey.findById(Int)" is null

### ISSUE THREAD

**Issue by Lepommejamez** [Yesssssman/epicfightmod#1520]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

I am hosting a server with my friends, and the server has epic fights. After playing for some time, I started getting this error, not letting me join in the client side. My friends however have no issue.

Internal Exception: java.langNullPointerException: Cannot invoke "yesman.epicfight.skill.SkillDataManager$SkillDataKey.getValueType()" because the return value of "yesman.epicfight.skill.SkillDataManager$SkillDataManager$SkillDataKey.findById(Int)" is null

Attached below is the log:
[2024-01-25-1.log](https://github.com/Yesssssman/epicfightmod/files/14059861/2024-01-25-1.log)

**Comment by Yesssssman** [comment]
Fixed

**Comment by Piterochka** [comment]
how

**Comment by MetalKnight56** [comment]
> how

just update the mod?

**Comment by Shybella** [comment]
This is not fixed on `18.5.24` 1.18.2
