### ISSUE TITLE
[Bug|Crash]: Getting kicked while holding the uchigatana.

### ISSUE THREAD

**Issue by UnsexSituation** [Yesssssman/epicfightmod#1523]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

After about five seconds of holding the item, the game kicks me for the attached error.
![javaw_qJefSQBNe2](https://github.com/Yesssssman/epicfightmod/assets/142322498/cfb14cbd-8352-45ee-bd90-d11a03788a30)
Crash log: https://mclo.gs/eqrw7KD

**Comment by MetalKnight56** [comment]
Download the mod [Spit it out](https://www.curseforge.com/minecraft/mc-mods/spit-it-out) and send me the log.
Spit it out is a mod, you have to download it on your client and on your server.


You can also add this to your Server jvm_args : 
-Dsun.rmi.dgc.server.gcInterval=2147483646

**Comment by UnsexSituation** [comment]
Setting the jvm arg fixed it.
