### ISSUE TITLE
[Bug|Crash]: Sophisticated Backpacks model fit problems

### ISSUE THREAD

**Issue by fzrdwa123456** [Yesssssman/epicfightmod#1524]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

### Minecraft Version

1.20.1

### What happened?

Squatting causes some mod models to separate from certain parts of the body, e.g. YDM's Weapon Master
epic fight 20.6.5
forge 47.2.20

**Comment by fzrdwa123456** [comment]
![2024-01-29_02 28 02](https://github.com/Yesssssman/epicfightmod/assets/130232431/c76c5404-673a-479c-a27a-14a4b3094382)

**Comment by fzrdwa123456** [comment]
https://github.com/Yesssssman/epicfightmod/assets/130232431/1d3d7b07-1cb2-4141-9f11-4adc02fc79ce

**Comment by MetalKnight56** [comment]
They need to fix this. we're unable to patch every mod that does this...
