### ISSUE TITLE
[Bug|Crash]: Can't attack on server

### ISSUE THREAD

**Issue by Aabaddon** [Yesssssman/epicfightmod#1525]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

i dont know, in single player i can do everything as normal but in the server i have with friends players cant attack with left click

**Comment by Aabaddon** [comment]
i still can use innate attack skills, but when i try to do a normal hit with any weapon or without a weapon the character simply does nothing, error only on server

**Comment by Aabaddon** [comment]
using any skill book allows a player to attack again, but when using some skills the server kicks the player with 

Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(13) + length(4) exceeds writer index(14): PooledUnsafeDirectByteBuf(ride: 13, wide: 14, cap:

**Comment by Aabaddon** [comment]
i have 2 addons

-Epic Fight Impactful

- Weapons of Miracles

**Comment by Aabaddon** [comment]
solved by removing weapons of miracles xd this is like therapy

**Comment by Lucybruv** [comment]
Having the same problem. Was trying to use my own server but upon joining I couldn't attack at all. I was in combat mode and I made sure my keybinds were right too, hadn't had the issue at all in single player. Rejoining fixed it for me but idk what the cause was

**Comment by MetalKnight56** [comment]
Remove sinytra connector, and check your mods to make sure you don't have a mismatched mod list.

**Comment by Aabaddon** [comment]
i dont use sinytra connector in my modpack, and every mod in the server was uploaded directly from my mods folder

**Comment by MetalKnight56** [comment]
> i dont use sinytra connector in my modpack, and every mod in the server was uploaded directly from my mods folder

Attach your logs.

**Comment by Aabaddon** [comment]
[latest (2).log](https://github.com/Yesssssman/epicfightmod/files/14115153/latest.2.log)

**Comment by Aabaddon** [comment]
it says nothing about any epic fight problem in the logs

**Comment by MetalKnight56** [comment]
> [latest (2).log](https://github.com/Yesssssman/epicfightmod/files/14115153/latest.2.log)

Incomplete log... Attach the whole thing (both from client and server)

**Comment by Aabaddon** [comment]
[server.log](https://github.com/Yesssssman/epicfightmod/files/14117330/server.log)
[client.log](https://github.com/Yesssssman/epicfightmod/files/14117332/client.log)

here

**Comment by MrAdisson** [comment]
I had the same issue, found the responsible : it was the "Epic Fight Battle Styles" mod, it seems to have a server side issue making the player not able to attack / only do jump attack. Remove it and every thing will work again !

**Comment by Nariod14** [comment]
I'm experiencing the same issue! I'm using the same version of Minecraft and the latest version of Epic Fight (20.14.4-1.20.1). All of my other mods are also updated to their latest versions as of writing. While the hits sometimes register, the animations don't play, except for a few simply swords animations. I have a lot of mods installed, but they all work perfectly together in singleplayer mode. Any help would be greatly appreciated! I've tried to provide as much information as possible, using Crash Assistant and Exaroton for reference.

If any more info is needed I'd be happy to provide!

Server logs:
https://mclo.gs/5KYaysO

Client logs:
The logs have been uploaded to `gnomebot.dev`:
### [latest.log head](<https://gnomebot.dev/paste/mclogs/I7XvmSy>) / [tail](<https://gnomebot.dev/paste/mclogs/AHv3DZm>) (~15MB & ~135k lines)   |   [crash-2025-12-27_15.05.27-client.txt](<https://gnomebot.dev/paste/mclogs/asNLC48>)   |   [crash_assistant_app.log](<https://gnomebot.dev/paste/mclogs/XMoxHdY>)   |   [modlist.txt](<https://gnomebot.dev/paste/mclogs/fa5t193>)   |   CurseForge: skip launcher
