### ISSUE TITLE
[Bug|Crash]: EpicFight repeats the same attack over and over.

### ISSUE THREAD

**Issue by UnsexSituation** [Yesssssman/epicfightmod#1529]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

https://github.com/Yesssssman/epicfightmod/assets/142322498/d5e70de2-306a-4739-a613-71266ac81c72

**Comment by MetalKnight56** [comment]
If you have sinytra connector or you are running this on a dedicated server, you should check your modlist because this is most likely a mismatched mod list problem or just sinytra being weird (which i would recommend removing it)

**Comment by UnsexSituation** [comment]
I don't have sinytra, but I'll check the mod list.
