### ISSUE TITLE
[1.16.5] Mounted combat animations not compatible with non-vanilla mobs

### ISSUE THREAD

**Issue by Dyshonored** [Yesssssman/epicfightmod#153]
I tested mounted combat with Ice and Fire's Hippogryphs and it seems that I cannot attack at all when in fight mode.
But thank you for all the tireless bugfixing so far:)

**Comment by ghiltonT** [comment]
tengo el mismo problema pero uso la jabalina de spartan weapon para lanzarlas quisiera saber si hay una forma de agregar a las monturas no vanila
