### ISSUE TITLE
[Bug|Crash]: Unable to launch because of "Error loading class: yesman/epicfight/config/ConfigurationIngame"

### ISSUE THREAD

**Issue by BakaBunny** [Yesssssman/epicfightmod#1531]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Server Mode

SinglePlayer

### Minecraft Version

1.20.1

### What happened?

I tried to do some trouble shooting on what could be the potential cause but i came out empty handed. i have tried repairing the profile then the installation through the cursed forge launcher but the problem still persist. i also did a test just having the epic fight mod in another instance and it worked just fine, so I'm assuming its another mod causing it but i am not sure which one. I installed several mods before the problem happened (it worked fine before i installed the new mods). i cant remember all the mods which i installed and tried disabling the ones i do remember (most are just performance booster mods) but i had no luck.

Here is the log of when the problem first occurred: 
https://mclo.gs/FVAHty5

If you need my mod list then i will provide when requested.

**Comment by MetalKnight56** [comment]
Outdated addons
