### ISSUE TITLE
[Bug]: Incompatibility with TerraFirmaCraft

### ISSUE THREAD

**Issue by Proxwian** [Yesssssman/epicfightmod#1534]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

TerraFirmaCraft

### Server Mode

SinglePlayer

### Minecraft Version

1.20.1

### What happened?

Can't throw Spear from TFC in any mode (build/fight) with EpicFight installed

**Comment by Proxwian** [comment]
Firstly reported to TerraFirmaCraft author, but he closed the issue https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/2628

**Comment by MetalKnight56** [comment]
Considering how game changing terrafirma craft is, and how their mod weirdly registers trindet like weapons, we'll also be closing this. If they aren't really up to fixing issues between the two mods so are we. Best you can do is choose between the two...
