### ISSUE TITLE
[|Crash]: BSL shaders cause the game to crash.

### ISSUE THREAD

**Issue by DesolateIntention** [Yesssssman/epicfightmod#1535]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Server Mode

Dedicated Server

### Minecraft Version

1.16.5

### What happened?

Game crashed when using BSL Shaders. Crash report seemed to blame this mod. I've attached the crash report and logs. Nothing in particular happens before a crash. I have a 1060 Mobile 3 GB + i7-7700HQ + 16 GB RAM. RAM was okay when the game crashed, as well as committed RAM.
[crash-2024-02-02_23.19.29-client.txt](https://github.com/Yesssssman/epicfightmod/files/14149384/crash-2024-02-02_23.19.29-client.txt)
[2024-02-02-7.log](https://github.com/Yesssssman/epicfightmod/files/14149391/2024-02-02-7.log)

**Comment by MetalKnight56** [comment]
Closing issue as 1.16.5 is no longer supported.
