### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by CloneDropper** [Yesssssman/epicfightmod#1538]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Thx for checking Well... the issue is I get stuck on loading screen at 100% I couldn't find the culprit I have the required dependencies. Thats what crash says java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage 
and that's the crash log;
[crash-2024-02-06_15.38.20-server.txt](https://github.com/Yesssssman/epicfightmod/files/14179793/crash-2024-02-06_15.38.20-server.txt)
I appreciate any help Thanks in advance!

**Comment by MetalKnight56** [comment]
> ### Have you checked if a similar issue is already reported by someone else?
> 
>     * [x]  I checked there are no similar issues have been reported.
> 
> 
> ### Have you read the support policy?
> 
>     * [x]  I read it and I accept the policy.
> 
> 
> ### Are you using the latest Epic Fight and recommended Forge version?
> 
>     * [x]  I checked I'm using latest Epic Fight and recommended Forge version.
> 
> 
> ### Is this issue related to mod incompatibility?
> 
>     * [ ]  This is a mod compatibility issue and I'm aware of the problem.
> 
> 
> ### The mod
> 
> _No response_
> ### Minecraft Version
> 
> 1.20.1
> ### What happened?
> 
> Thx for checking Well... the issue is I get stuck on loading screen at 100% I couldn't find the culprit I have the required dependencies. Thats what crash says java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage and that's the crash log; [crash-2024-02-06_15.38.20-server.txt](https://github.com/Yesssssman/epicfightmod/files/14179793/crash-2024-02-06_15.38.20-server.txt) I appreciate any help Thanks in advance!

remove a mod called "The dawn era"

**Comment by CloneDropper** [comment]
> > ### Have you checked if a similar issue is already reported by someone else?
> > ```
> > * [x]  I checked there are no similar issues have been reported.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Have you read the support policy?
> > ```
> > * [x]  I read it and I accept the policy.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Are you using the latest Epic Fight and recommended Forge version?
> > ```
> > * [x]  I checked I'm using latest Epic Fight and recommended Forge version.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Is this issue related to mod incompatibility?
> > ```
> > * [ ]  This is a mod compatibility issue and I'm aware of the problem.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### The mod
> > _No response_
> > ### Minecraft Version
> > 1.20.1
> > ### What happened?
> > Thx for checking Well... the issue is I get stuck on loading screen at 100% I couldn't find the culprit I have the required dependencies. Thats what crash says java.lang.IllegalArgumentException: Can't find attribute minecraft:generic.attack_damage and that's the crash log; [crash-2024-02-06_15.38.20-server.txt](https://github.com/Yesssssman/epicfightmod/files/14179793/crash-2024-02-06_15.38.20-server.txt) I appreciate any help Thanks in advance!
> 
> remove a mod called "The dawn era"

♥ ♥ ♥ Thank You So Much ♥ ♥ ♥

**Comment by agro2309** [comment]
anyone figure out fix
