### ISSUE TITLE
[Bug|Crash]: "Epic Fight Mod (and 3 of it's addons) has failed to load correctly"

### ISSUE THREAD

**Issue by Tsukiszzz** [Yesssssman/epicfightmod#1539]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

So I'm making a modpack to play with friends around EFM but this is what happens when i try to play it.
![Screenshot_23](https://github.com/Yesssssman/epicfightmod/assets/159476863/dbfbd8f1-2117-42b4-826d-84b9af78ff87)

**Comment by Yesssssman** [comment]
Attach the crash log

**Comment by MetalKnight56** [comment]
Just remove outdated addons.
