### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by WSKJDKASJD** [Yesssssman/epicfightmod#1540]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

i dont know, thats why i asking about this

### Minecraft Version

1.18.2

### What happened?

After deleting the old version of Epic fight and replacing it with the latest version 5.2.1, the game cannot be opened. This is my crash log and  screenshot
[crash-2024-02-09_02.51.32-fml.txt](https://github.com/Yesssssman/epicfightmod/files/14213545/crash-2024-02-09_02.51.32-fml.txt)
![N9JGN4MPTT$FX Q12YRRITQ](https://github.com/Yesssssman/epicfightmod/assets/159148975/f493a403-5f54-45c3-899c-396211b411b3)

**Comment by Yesssssman** [comment]
Issue is from outdated addon
