### ISSUE TITLE
[Bug]: can't attack while in a server.

### ISSUE THREAD

**Issue by notrealmasi** [Yesssssman/epicfightmod#1542]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight.

### Minecraft Version

1.19.2

### What happened?

Epic fight 19.5.21
Simply swords with epic fight v3
Epic Fight battle styles 1.0.1
also using /gamerule weightpenalty 20 and /gamerule doVanillaAttack false.
Also using WoM 19.1.7.37
The issue occurs when i load into my server, since when i do, i'm unable to attack. the only way i'm able to attack is if i hold "spacebar" and "attack" at the same time, causing the jump-attack to proc, also none of the skills are usable, would appreciate an answer, fix or suggestion, thanks in advance.

**Comment by MrAdisson** [comment]
I can confirm that, I have the same setup, it happens only when I host a forge server running with Epic Fight mod, I have no issue on my local solo game.

**Comment by MrAdisson** [comment]
Yo, I had the same issue, found the responsible : it was "Epic Fight Battle Styles", it seems to have a server side issue making the player not able to attack / only do jump attack. Remove it and every thing will work again !
