### ISSUE TITLE
[Bug|Crash]: Custom skins incompatibility  (MCA reborn)

### ISSUE THREAD

**Issue by crixtard** [Yesssssman/epicfightmod#1546]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn

### Minecraft Version

1.20.1

### What happened?

The problem arises from the fact that Epic Fight Mod modifies animations in the game, causing conflicts with MCA Reborn. Specifically, when Epic Fight Mod is active, it prevents MCA Reborn from utilizing custom skins as intended. Instead it shows the vanilla skin.

**Comment by MetalKnight56** [comment]
MCA handles tgheir entities in a weird way, most likely making it render in the vanilla layer and so its basically impossible for us to disable their entity model and you get 2 models at once. can't do anything go report it to them

**Comment by HunterHTTP** [comment]
i have same problem :(
