### ISSUE TITLE
[BUG]: When I was making a dataset, I stumbled upon a critical problem with the giant sword collision box determination!!

### ISSUE THREAD

**Issue by hyqzaa** [Yesssssman/epicfightmod#1550]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### The mod

Epic Fight

### Minecraft Version

1.16.5

### What's your suggestion?

When I was making a dataset, I stumbled upon a critical problem with the giant sword collision box determination, which was fatal to the integrated dataset authors![My English is not good, so I can only use translation software to talk——I am an integration package author]1.19.2~1.18.2Only the latest versions of the above two game versions were tested

If the "damage_bonus" value is set to negative for a weapon of the Great Sword type when crafting the packet, then all of your Great Sword type weapons will have a judgment error on part of the attack, while you attack forward the attack animation is correct, but can only attack behind! This is very deadly!! I have tried many cases, and it still exists even after deleting the relevant packets!!! I want to make it disappear, but this is very random, Even if I remove the other irrelevant mods, there are still bugs.

I don't know how to express the qwq order, please do help me, This is my favorite mod...

https://github.com/Yesssssman/epicfightmod/assets/159793001/b4ef1225-efe3-4a27-b7b4-a231a2c50ffd

**Comment by MetalKnight56** [comment]
> Only the latest versions of the above two game versions were tested

Can you make sure to check if this also happens on 1.19.2 & most importantly in 1.20.1?

**Comment by hyqzaa** [comment]
> > 仅测试了上述两个游戏版本的最新版本
> 
> 你能确保检查这是否也发生在 1.19.2 上，最重要的是在 1.20.1 中吗？

I tested it all afternoon and found that the bug was firing erratically, and to be honest I'm not sure if it's the result of what I said above. However, by repeatedly comparing the collision box, I found that after the bug triggered, the damage determination of some attacks was similar to slow. For example, when I attacked, the animation showed that I raised the sword behind me, and the impact box of the sword turned red, which should have triggered the damage judgment. However, after testing the sword for a whole afternoon, I found that the bug trigger was very unstable. To be honest, I am not sure whether it was caused by my above reasons. However, by repeatedly comparing the collision box, I found that after the bug triggered, the damage determination of some attacks was similar to slow. For example, when I attack, the animation shows that I hold the sword behind me, the sword's impact box turns red, which should trigger the damage determination, but when the sword is thrown in the middle, the sword's impact box turns back white and cannot cause damage, and when the sword is swung, it turns red again, and this moment the monster hits the red box and causes damage. So far, I have not tested how the bug was triggered. Is there any way to fix the bug manually by modifying the packet? This is really important to me! Thanks for help

**Comment by MetalKnight56** [comment]
> > > 仅测试了上述两个游戏版本的最新版本
> > 
> > 
> > 你能确保检查这是否也发生在 1.19.2 上，最重要的是在 1.20.1 中吗？
> 
> I tested it all afternoon and found that the bug was firing erratically, and to be honest I'm not sure if it's the result of what I said above. However, by repeatedly comparing the collision box, I found that after the bug triggered, the damage determination of some attacks was similar to slow. For example, when I attack, the animation shows that I hold the sword behind me, the sword's impact box turns red, which should trigger the damage determination, but when the sword is thrown in the middle, the sword's impact box turns back white and cannot cause damage, and when the sword is swung, it turns red again, and this moment the monster hits the red box and causes damage. So far, I have not tested how the bug was triggered. Is there any way to fix the bug manually by modifying the packet? This is really important to me! Thanks for help

Well i'm not even sure what you are doing to begin with, Why did you want to set the damage bonus to a negative value to begin with? I'm not getting the issue properly nor what's causing it, because i can't really give you a solution without actually knowing the cause of the issue too...

**Comment by metziupz** [comment]
Exactly the same thing is happening to me and I'm on 1.19.2

**Comment by metziupz** [comment]
I just fixed it, it is a temporary solution but it can work until someone fixes it, you simply have to delete the epic fight files in the config folder

**Comment by MetalKnight56** [comment]
> I just fixed it, it is a temporary solution but it can work until someone fixes it, you simply have to delete the epic fight files in the config folder

what files.... and what config folder are you even talking abt?

**Comment by hyqzaa** [comment]
> > > > 仅测试了上述两个游戏版本的最新版本
> > > 
> > > 
> > > 你能确保检查这是否也发生在 1.19.2 上，最重要的是在 1.20.1 中吗？
> > 
> > 
> > I tested it all afternoon and found that the bug was firing erratically, and to be honest I'm not sure if it's the result of what I said above. However, by repeatedly comparing the collision box, I found that after the bug triggered, the damage determination of some attacks was similar to slow. For example, when I attack, the animation shows that I hold the sword behind me, the sword's impact box turns red, which should trigger the damage determination, but when the sword is thrown in the middle, the sword's impact box turns back white and cannot cause damage, and when the sword is swung, it turns red again, and this moment the monster hits the red box and causes damage. So far, I have not tested how the bug was triggered. Is there any way to fix the bug manually by modifying the packet? This is really important to me! Thanks for help
> 
> Well i'm not even sure what you are doing to begin with, Why did you want to set the damage bonus to a negative value to begin with? I'm not getting the issue properly nor what's causing it, because i can't really give you a solution without actually knowing the cause of the issue too...

The negative value is set to reduce the damage of some weapons

**Comment by hyqzaa** [comment]
> I just fixed it, it is a temporary solution but it can work until someone fixes it, you simply have to delete the epic fight files in the config folder

I am an integration package author, how did you fix this bug, my integration package can not continue to produce because of this bug

**Comment by hyqzaa** [comment]
> > > > 仅测试了上述两个游戏版本的最新版本
> > > 
> > > 
> > > 你能确保检查这是否也发生在 1.19.2 上，最重要的是在 1.20.1 中吗？
> > 
> > 
> > I tested it all afternoon and found that the bug was firing erratically, and to be honest I'm not sure if it's the result of what I said above. However, by repeatedly comparing the collision box, I found that after the bug triggered, the damage determination of some attacks was similar to slow. For example, when I attack, the animation shows that I hold the sword behind me, the sword's impact box turns red, which should trigger the damage determination, but when the sword is thrown in the middle, the sword's impact box turns back white and cannot cause damage, and when the sword is swung, it turns red again, and this moment the monster hits the red box and causes damage. So far, I have not tested how the bug was triggered. Is there any way to fix the bug manually by modifying the packet? This is really important to me! Thanks for help
> 
> Well i'm not even sure what you are doing to begin with, Why did you want to set the damage bonus to a negative value to begin with? I'm not getting the issue properly nor what's causing it, because i can't really give you a solution without actually knowing the cause of the issue too...

Through the form of packets, such as the Great Sword weapon that comes with the module, I think they are unbalanced, so I lowered the damage in the configuration file, the original damage is 13, then I set the "damage_bonus" value to -6, and the final weapon damage will be 7. I don't know if you understand my approach, but I will try to express it

**Comment by hyqzaa** [comment]
> > > > 仅测试了上述两个游戏版本的最新版本
> > > 
> > > 
> > > 你能确保检查这是否也发生在 1.19.2 上，最重要的是在 1.20.1 中吗？
> > 
> > 
> > I tested it all afternoon and found that the bug was firing erratically, and to be honest I'm not sure if it's the result of what I said above. However, by repeatedly comparing the collision box, I found that after the bug triggered, the damage determination of some attacks was similar to slow. For example, when I attack, the animation shows that I hold the sword behind me, the sword's impact box turns red, which should trigger the damage determination, but when the sword is thrown in the middle, the sword's impact box turns back white and cannot cause damage, and when the sword is swung, it turns red again, and this moment the monster hits the red box and causes damage. So far, I have not tested how the bug was triggered. Is there any way to fix the bug manually by modifying the packet? This is really important to me! Thanks for help
> 
> Well i'm not even sure what you are doing to begin with, Why did you want to set the damage bonus to a negative value to begin with? I'm not getting the issue properly nor what's causing it, because i can't really give you a solution without actually knowing the cause of the issue too...

However, if you use unzip software to open the module file and modify some of the files inside, you can do a similar thing

**Comment by MetalKnight56** [comment]
> > > > > 仅测试了上述两个游戏版本的最新版本
> > > > 
> > > > 
> > > > 你能确保检查这是否也发生在 1.19.2 上，最重要的是在 1.20.1 中吗？
> > > 
> > > 
> > > I tested it all afternoon and found that the bug was firing erratically, and to be honest I'm not sure if it's the result of what I said above. However, by repeatedly comparing the collision box, I found that after the bug triggered, the damage determination of some attacks was similar to slow. For example, when I attack, the animation shows that I hold the sword behind me, the sword's impact box turns red, which should trigger the damage determination, but when the sword is thrown in the middle, the sword's impact box turns back white and cannot cause damage, and when the sword is swung, it turns red again, and this moment the monster hits the red box and causes damage. So far, I have not tested how the bug was triggered. Is there any way to fix the bug manually by modifying the packet? This is really important to me! Thanks for help
> > 
> > 
> > Well i'm not even sure what you are doing to begin with, Why did you want to set the damage bonus to a negative value to begin with? I'm not getting the issue properly nor what's causing it, because i can't really give you a solution without actually knowing the cause of the issue too...
> 
> Through the form of packets, such as the Great Sword weapon that comes with the module, I think they are unbalanced, so I lowered the damage in the configuration file, the original damage is 13, then I set the "damage_bonus" value to -6, and the final weapon damage will be 7. I don't know if you understand my approach, but I will try to express it

Yeah and thats exactly what happens right? If you are looking at the tooltip, make sure to update epic fight as in the latest update we fixed an issue with tooltips being unresponsive and not properly displaying the values they should...

**Comment by hyqzaa** [comment]
> > > > > > 仅测试了上述两个游戏版本的最新版本
> > > > > 
> > > > > 
> > > > > 你能确保检查这是否也发生在 1.19.2 上，最重要的是在 1.20.1 中吗？
> > > > 
> > > > 
> > > > I tested it all afternoon and found that the bug was firing erratically, and to be honest I'm not sure if it's the result of what I said above. However, by repeatedly comparing the collision box, I found that after the bug triggered, the damage determination of some attacks was similar to slow. For example, when I attack, the animation shows that I hold the sword behind me, the sword's impact box turns red, which should trigger the damage determination, but when the sword is thrown in the middle, the sword's impact box turns back white and cannot cause damage, and when the sword is swung, it turns red again, and this moment the monster hits the red box and causes damage. So far, I have not tested how the bug was triggered. Is there any way to fix the bug manually by modifying the packet? This is really important to me! Thanks for help
> > > 
> > > 
> > > Well i'm not even sure what you are doing to begin with, Why did you want to set the damage bonus to a negative value to begin with? I'm not getting the issue properly nor what's causing it, because i can't really give you a solution without actually knowing the cause of the issue too...
> > 
> > 
> > Through the form of packets, such as the Great Sword weapon that comes with the module, I think they are unbalanced, so I lowered the damage in the configuration file, the original damage is 13, then I set the "damage_bonus" value to -6, and the final weapon damage will be 7. I don't know if you understand my approach, but I will try to express it
> 
> Yeah and thats exactly what happens right? If you are looking at the tooltip, make sure to update epic fight as in the latest update we fixed an issue with tooltips being unresponsive and not properly displaying the values they should...

After updating the module, although the Great Sword type weapon is solved, the "uchigatana" type that was not bug-free before seems to have a similar bug. However, the good news is that this type of weapon is relatively small, which does not particularly affect the production of integrated packages.

**Comment by hyqzaa** [comment]
> > > > > > 仅测试了上述两个游戏版本的最新版本
> > > > > 
> > > > > 
> > > > > 你能确保检查这是否也发生在 1.19.2 上，最重要的是在 1.20.1 中吗？
> > > > 
> > > > 
> > > > I tested it all afternoon and found that the bug was firing erratically, and to be honest I'm not sure if it's the result of what I said above. However, by repeatedly comparing the collision box, I found that after the bug triggered, the damage determination of some attacks was similar to slow. For example, when I attack, the animation shows that I hold the sword behind me, the sword's impact box turns red, which should trigger the damage determination, but when the sword is thrown in the middle, the sword's impact box turns back white and cannot cause damage, and when the sword is swung, it turns red again, and this moment the monster hits the red box and causes damage. So far, I have not tested how the bug was triggered. Is there any way to fix the bug manually by modifying the packet? This is really important to me! Thanks for help
> > > 
> > > 
> > > Well i'm not even sure what you are doing to begin with, Why did you want to set the damage bonus to a negative value to begin with? I'm not getting the issue properly nor what's causing it, because i can't really give you a solution without actually knowing the cause of the issue too...
> > 
> > 
> > Through the form of packets, such as the Great Sword weapon that comes with the module, I think they are unbalanced, so I lowered the damage in the configuration file, the original damage is 13, then I set the "damage_bonus" value to -6, and the final weapon damage will be 7. I don't know if you understand my approach, but I will try to express it
> 
> Yeah and thats exactly what happens right? If you are looking at the tooltip, make sure to update epic fight as in the latest update we fixed an issue with tooltips being unresponsive and not properly displaying the values they should...

After testing other weapons, the "spear" weapon type began to show some similar conditions
