### ISSUE TITLE
[bug] 2 similar bugs

### ISSUE THREAD

**Issue by ParaLumic** [Yesssssman/epicfightmod#1551]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Perfect bulwark gains stacks from any form of damage, and while standing on a magma block you can gain 100 stacks in less than 5 seconds making you able to 1 hit anything

Both offensive bulwark and vengeful parry can gain stacks very quickly if attacked by anything that hits quick. I suggest giving them both a very short cooldown

**Comment by MetalKnight56** [comment]
> Perfect bulwark gains stacks from any form of damage, and while standing on a magma block you can gain 100 stacks in less than 5 seconds making you able to 1 hit anything
What even is bulwark gains 

> Both offensive bulwark and vengeful parry can gain stacks very quickly if attacked by anything that hits quick. I suggest giving them both a very short cooldown
still have 0 idea what a bulwark is

**Comment by ParaLumic** [comment]
> > Perfect bulwark gains stacks from any form of damage, and while standing on a magma block you can gain 100 stacks in less than 5 seconds making you able to 1 hit anything
> 
> What even is bulwark gains
> 
> > Both offensive bulwark and vengeful parry can gain stacks very quickly if attacked by anything that hits quick. I suggest giving them both a very short cooldown
> 
> still have 0 idea what a bulwark is

Is this the wrong mod? They might be from WOM, the mod doesn't say what skills belong to it
