### ISSUE TITLE
[Bug|Crash]: yesman/epic fight/skill/skilldatamanager$valuetype

### ISSUE THREAD

**Issue by charliez0** [Yesssssman/epicfightmod#1553]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

[minecraft-exported-crash-info-2024-02-25T21-47-22.zip](https://github.com/Yesssssman/epicfightmod/files/14396691/minecraft-exported-crash-info-2024-02-25T21-47-22.zip)
I don't know which mod does hurt the compatibility issue with this one

**Comment by thutagsgrfgegdfgergtdgwt** [comment]
same with me here I made a lil modpack nothing big started it and it had an error and it said "yesman/epic fight/skill/skilldatamanager$valuetype" js like the same with one of your errors when i looked into your crash file.

**Comment by Yesssssman** [comment]
Please update your WoM version. It's not compatible with Epic Fight 20.7.x versions.

**Comment by charliez0** [comment]
wom?

**Comment by Yesssssman** [comment]
> wom?

Weapons of Miracles addon

**Comment by charliez0** [comment]
My fault, sorry
closing issue as resolved.
