### ISSUE TITLE
[Bug|Crash]: Incompatible with DivineRPG weapon items

### ISSUE THREAD

**Issue by yuankun1** [Yesssssman/epicfightmod#1555]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/official-divinerpg

### Minecraft Version

1.20.1

### What happened?

I opened the weapon inventory of DivineRPG module and dragged it down to crash
https://pastebin.com/fQYEppk2

**Comment by yuankun1** [comment]
21/5000
Do you need to add a language key to solve this problem

**Comment by MetalKnight56** [comment]
Please remove all mods except epic fight and divine RPG and try again, if it continues to crash, re-post your logs here so we can take a look at it.

**Comment by yuankun1** [comment]
[c

> 请删除除史诗战斗和神圣RPG之外的所有mod并重试，如果它继续崩溃，请在此重新发布您的日志，以便我们可以查看它。

[crash-2024-03-02_21.40.19-client.txt](https://github.com/Yesssssman/epicfightmod/files/14469517/crash-2024-03-02_21.40.19-client.txt)
This is a new diary.

**Comment by Omegarte** [comment]
I have a similar issue and similar crash report as the OP (i.e. using divine RPG weapons in epic fight mode)

**Comment by Yesssssman** [comment]
Fixed in latest 1.20.1
