### ISSUE TITLE
[Bug|Crash]: game crashes when i go into combat mode while wearing any armor

### ISSUE THREAD

**Issue by cptPakzad** [Yesssssman/epicfightmod#1556]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

I was playing with my modpack like normal until i got my first piece of iron armor and when i enabled combat mode my game crashed and i could not rejoin the world again i tried it with several world same issue i even removed every other mods exept epic fight but still crashed.
The weird part is when i wore any armor from the mod "born in chaos" it didn't crash my game but with vanilla armor and armors from other mods it crashes.
 
[crash-2024-02-27_15.14.48-client.txt](https://github.com/Yesssssman/epicfightmod/files/14420054/crash-2024-02-27_15.14.48-client.txt)

Please help me solve this

**Comment by MetalKnight56** [comment]
Attach logs

**Comment by cptPakzad** [comment]
> Attach logs

[crash-2024-02-27_11.49.28-client.txt](https://github.com/Yesssssman/epicfightmod/files/14416487/crash-2024-02-27_11.49.28-client.txt)

**Comment by Yesssssman** [comment]
When did you get this error? Which armor were you wearing when game crashed?

Basically, this error comes from the broken unicode containing inside the armor texture path.

`net.minecraft.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:textures/models/armor/epicfight/iron_layer_۱.png`

**Comment by MetalKnight56** [comment]
> > Attach logs
> 
> [crash-2024-02-27_11.49.28-client.txt](https://github.com/Yesssssman/epicfightmod/files/14416487/crash-2024-02-27_11.49.28-client.txt)

Remove Entity Texture features & Entity model features, make sure to also disable fresh animations as it's not supported cuz it changes entity models.
