### ISSUE TITLE
[Bug]: Can't attack on combat mode 

### ISSUE THREAD

**Issue by EnyelBTW** [Yesssssman/epicfightmod#1558]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

(first sorry if my english is not perfect) I just can't attack in combat mode on a multiplayer server (working correctly on singleplayer) the only thing that happened before that is that i updated alex caves to the newest version AND ADDED THE MOD Epic Sanji (im suspecting in that one) the console on server doesn't show something wrong but the cliente shows this warnings:

[EpicFightMod] Can't find the joint HeelIK_R in the animation file, DashAttackAnimation epic_fight_battle_styles:animmodels/animations/chakram/chakram_dash
12:25:45.773
epicfight
Render thread
[EpicFightMod] Can't find the joint ElbowIK_R in the animation file, DashAttackAnimation epic_fight_battle_styles:animmodels/animations/chakram/chakram_dash
12:25:45.773
epicfight
Render thread
[EpicFightMod] Can't find the joint ElbowIK_L in the animation file, DashAttackAnimation epic_fight_battle_styles:animmodels/animations/chakram/chakram_dash

(they are more)
And in the info is spaming:
com.mojang.blaze3d.platform.GlDebug
Render thread
OpenGL debug message: id=1000, source=API, type=ERROR, severity=HIGH, message='glBindTextureUnit has generated an error (GL_INVALID_OPERATION)'

I have the mod Spit it out to solve the animation render bug that kicks you from the server but this is quite different

**Comment by MetalKnight56** [comment]
Are you using epic fight battel styles?
(also attach your whole log, thatever you posted is really useless)

**Comment by EnyelBTW** [comment]
![image](https://github.com/Yesssssman/epicfightmod/assets/161638332/a80d3a67-cebc-4b3d-8879-6905ee9d4a41)

Yes im using the the battle styles mod server side and client

**Comment by EnyelBTW** [comment]
It used to work normally until i instaled and updated those 2 mods

**Comment by MetalKnight56** [comment]
> Yes im using the the battle styles mod server side and client
Then remove it, as it's been reported to cause issues like this.
