### ISSUE TITLE
[Bug|Crash]: Weapon type damage collision box decision bug

### ISSUE THREAD

**Issue by hyqzaa** [Yesssssman/epicfightmod#1561]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.19.2

### What happened?

Module authors Hello, before I submitted a similar to the weapon damage collision box to determine the bug, where another player said he also found a similar bug and through some methods to fix, but I do not know what method he used, although the bug disappeared after the update of the module. After some time I modified the packet again, the attack speed of a weapon of the "longsword" type was originally 1.6, I wanted to reduce the attack speed, set the "speed_bonus" value to -0.6, and the attack speed became 1. After entering the game, the attack speed was indeed reduced, but the data was not correctly displayed, it still showed 1.6. And the damage bump box bug I submitted earlier for the Great Sword weapons reappeared. In fact, the last time I found that other weapon types seem to have similar bugs, but the impact is not as big as the great sword type, I did not care - in fact, other weapon types are also somewhat of this decision bug[mod for the latest version of the module authors Hello, before I submitted a similar to the weapon damage collision box decision bug, Although the bug disappeared after the mod update. After some time I modified the packet again, the attack speed of a weapon of the "longsword" type was originally 1.6, I wanted to reduce the attack speed, set the "speed_bonus" value to -0.6, and the attack speed became 1. After entering the game, the attack speed was indeed reduced, but the data was not correctly displayed, it still showed 1.6. And the damage bump box bug I submitted earlier for the Great Sword weapons reappeared. In fact, I last found that other weapon types seem to have similar bugs, but the impact is not as big as the great sword type, so I did not care - in fact, other weapon types also have some of this judgment bug[mod is the latest version, my English is not good, I can only use software translation for dialogue][The following picture is the relevant dialogue submitted last bug].
![QQ截图20240229165445](https://github.com/Yesssssman/epicfightmod/assets/159793001/55ac5d9d-d566-4da1-8f96-1b6f3e9d0de0)
![QQ截图20240229165512](https://github.com/Yesssssman/epicfightmod/assets/159793001/15955284-c447-4472-812c-d33c629e197a)
![QQ截图20240229165637](https://github.com/Yesssssman/epicfightmod/assets/159793001/6e778122-652f-4e79-867e-7bfba61ef1a7)

**Comment by MetalKnight56** [comment]
Ok so it does indeed change the tooltip value to 1, but when you reload your game it goes back to 1.6, even if you haven't made any changes to the datapack?

**Comment by hyqzaa** [comment]
> Ok so it does indeed change the tooltip value to 1, but when you reload your game it goes back to 1.6, even if you haven't made any changes to the datapack?

A little sorry, I did not understand the translation software after translation

**Comment by MetalKnight56** [comment]
> > Ok so it does indeed change the tooltip value to 1, but when you reload your game it goes back to 1.6, even if you haven't made any changes to the datapack?
> 
> A little sorry, I did not understand the translation software after translation

If you  don't understand english, it's basically impossible for me to guess what you are trying to say, or for you to undertsnad what i'm saying. So please try your best to read it again or something...
