### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by BeastMaster6989** [Yesssssman/epicfightmod#1563]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.20.1

### What happened?

When I enter the world, I open the inventory of the creative menu, flipping through the pages. The game crashes after a while. CrashLog is attached.

[crash-2024-02-29_16.11.12-client.txt](https://github.com/Yesssssman/epicfightmod/files/14449146/crash-2024-02-29_16.11.12-client.txt)

**Comment by BeastMaster6989** [comment]
entering the world, opening the creative menu and scrolling through the pages the game freezes and crashes, unfortunately there is nothing more to add.

**Comment by BeastMaster6989** [comment]
the world just won't load after updating to the latest version)

**Comment by MetalKnight56** [comment]
> the world just won't load after updating to the latest version) ok, the world is irretrievably lost, it doesn’t want to load anymore)

I still need the logs after you updated. If you are using WoM, remove it
