### ISSUE TITLE
[Bug]: invisible projectiles

### ISSUE THREAD

**Issue by malikcuh** [Yesssssman/epicfightmod#1564]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

epic fight mod

### Minecraft Version

1.20.1

### What happened?

[latest.log](https://github.com/Yesssssman/epicfightmod/files/14452098/latest.log)

**Comment by MetalKnight56** [comment]
Footage, and information missing. Will be closed if not answered

**Comment by malikcuh** [comment]
Uploading MedalTVMinecraftJava20240229225009.mp4…

**Comment by malikcuh** [comment]
https://github.com/Yesssssman/epicfightmod/assets/142112224/3e99ed24-907f-4ff0-9290-70a4d9c6dae9

**Comment by MetalKnight56** [comment]
> MedalTVMinecraftJava20240229225012.mp4

You do seem to have quite a lot of mods... Please re move them all, see if the issue persists and if it doesn't, then slowly add mods back until you find the culprit.
