### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by tlafurkan** [Yesssssman/epicfightmod#1565]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

In version 20.7.1 and 20.7.2 when i use uchigatana game recognises it as a sword. it only happens when entering a world 2. time.

**Comment by MetalKnight56** [comment]
Try updating to the newest version

**Comment by MetalKnight56** [comment]
> its still happening

Then attach your logs.

**Comment by tlafurkan** [comment]
where can i find my logs?

**Comment by MetalKnight56** [comment]
> where can i find my logs?

search

**Comment by wujekbobixon** [comment]
@tlafurkan  do you using a WOM?

**Comment by tlafurkan** [comment]
@wujekbobixon yes, but i think 20.7.3 solved it if i run it without WOM.
