### ISSUE TITLE
[Bug|Crash]: Crash when creating new world

### ISSUE THREAD

**Issue by lartts** [Yesssssman/epicfightmod#1567]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.20.1

### What happened?

Something wrong with the "yesman.epicfight.api.utils.ExtendableEnumManager.get(ExtendableEnumManager.java:91)"
https://pastebin.com/Rru1k2qb

**Comment by Yesssssman** [comment]
Your datapack has an invalid weapon category name "katana", the old name of "uchigatana". You have to fix it.
