### ISSUE TITLE
[Bug|Crash]:nvalid player data is displayed online

### ISSUE THREAD

**Issue by hyqzaa** [Yesssssman/epicfightmod#1568]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

epic fight

### Minecraft Version

1.19.2

### What happened?

I took the module out for testing alone, using the latest version, without any optimizations, including ModernFix
![QQ截图20240303170604](https://github.com/Yesssssman/epicfightmod/assets/159793001/c2590ab9-477c-416c-8412-8b80bf8c3cae)

**Comment by MetalKnight56** [comment]
> ### Have you checked if a similar issue is already reported by someone else?
> 
>     * [x]  I checked there are no similar issues have been reported.
> 
> 
> ### Have you read the support policy?
> 
>     * [x]  I read it and I accept the policy.
> 
> 
> ### Are you using the latest Epic Fight and recommended Forge version?
> 
>     * [x]  I checked I'm using latest Epic Fight and recommended Forge version.
> 
> 
> ### Is this issue related to mod incompatibility?
> 
>     * [ ]  This is a mod compatibility issue and I'm aware of the problem.
> 
> 
> ### The mod
> 
> epic fight
> ### Minecraft Version
> 
> 1.19.2
> ### What happened?
> 
> I took the module out for testing alone, using the latest version, without any optimizations, including ModernFix ![QQ截图20240303170604](https://private-user-images.githubusercontent.com/159793001/309538587-c2590ab9-477c-416c-8412-8b80bf8c3cae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0ODc4NDAsIm5iZiI6MTcwOTQ4NzU0MCwicGF0aCI6Ii8xNTk3OTMwMDEvMzA5NTM4NTg3LWMyNTkwYWI5LTQ3N2MtNDE2Yy04NDEyLThiODBiZjhjM2NhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxNzM5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDM0ZWY5YmRmMDljYTQ0ZWI4OGU3MGQ1NjY0MDI0YWI3ZmNmNmJiNjBiMjdjNjRjMDk3Y2FjZjJiYzM5YTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PlYqVF2isDby7AK9TiluiEYHq63orFIkgmCNy3A0RRQ)

Stop fucking creating duplicates, or i'll have to block you out of this repository.
