### ISSUE TITLE
Katana animations

### ISSUE THREAD

**Issue by thedeerirty** [Yesssssman/epicfightmod#157]
Hi, for all the weebs out there, will the katana special attack be fixed in configs soon? It still gives the standard sword attack

**Comment by Yesssssman** [comment]
It's not a bug but I intended it because most katanas from other mods don't have a sheath. But this is a temporary solution. I'll make new types of weapons in the future.

**Comment by thedeerirty** [comment]
While I can agree that makes sense, I do imagine most or the majority of players don't mind that feature/oversight. People wanna do the slash dash I feel.
