### ISSUE TITLE
[Bug]: FPS drop seriously when loading Epic Fight entitiy models.

### ISSUE THREAD

**Issue by Hakuyako** [Yesssssman/epicfightmod#1570]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [x] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Hi, I notice that the entity model of  EpicFight can causing serious FPS drop.

I tested on two computers with different hardware:
One computer with RTX4090 graphics card , and another one with GTX1060 graphics card. Two computers connect to one server, use the same video settings, same shader, and looking at the same scene.

When there are 10 Pillagers on the screen:
The computer with rtx4090 graphics cards, avg FPS  dropped from 300 to 150 (50% drop!).
The computer  with gtx1060 graphics cards, avg FPS  dropped from 60 to 50 (16% drop).

When there are 10 players on the screen:
On the rtx4090 device, when enabling "Animation Filtering", avg FPS remains at 300. 
When disabling "Animation Filter", avg FPS drops to 110 (63% drop).

My mod list:
   EpicFight-20.7.4
   oculus-mc1.20.1-1.6.13
   embeddium-0.2.18 mc1.20.1
   rubidium-extra-0.5.3.1 mc1.20.1-build.110
Forge version:
   1.20.1-Forge_47.2.20
Shaderpack:
   ComplementaryUnbound_r5.1.1

I tested in a clean environment. I guess this issue can be related to refresh rate of the animation, since it  only occurs when the base frame rate is high.

I would like to donate to this improvement If you can provide a solution.

**Comment by MetalKnight56** [comment]
Entities won't usually drop that much FPS, most likely caused by rubidium, in any case just remove that and its dependets and use embeddium instead, no one uses rubidium anymore and it's poorly supported...

If you'd like to donate, you can simply go to our sponsor page, github displays it below each page so it should be pretty easy to find :)

**Comment by Hakuyako** [comment]
> Entities won't usually drop that much FPS, most likely caused by rubidium, in any case just remove that and its dependets and use embeddium instead, no one uses rubidium anymore and it's poorly supported...
> 
> If you'd like to donate, you can simply go to our sponsor page, github displays it below each page so it should be pretty easy to find :)

Thanks for replying this issue.

In fact, I have installed embeddium and not using rubidium. 
The rubidium-extra in my modlist is only an extra-option mod for Embedium, similar to sodium-extra.

I further tried deleting rubidium-extra and only using EF+oculus+embeddium. 
The problem of entity models causing FPS drop still exists, which player model has the most significant impact.

Any help would be appreciated.

**Comment by MetalKnight56** [comment]
> In fact, I have installed embeddium and not using rubidium. The rubidium-extra in my modlist is only an extra-option mod for Embedium, similar to sodium-extra.
> 
> I further tried deleting rubidium-extra and only using EF+oculus+embeddium. The problem of entity models causing FPS drop still exists, which player model has the most significant impact.
> 
> Any help would be appreciated.

Could you please try and record that frame drop with spark? 
Simply install spark, launch a singleplayer or multiplayer world and do the following commands - 
**/sparkc profiler start**
Then proceed to look at an entity and see if frames drop
when they do drop, you can then stop the profiler with 
**/sparkc profiler stop**

After that, just link the profiler here so we can see the results.
Make sure to also attach some footage and maybe some logs too to help us out.

**Comment by Razor235T** [comment]
That's the only reason I don't use the mod. It seems to be heavy on the CPU, when there are lots of mobs around, my FPS drops from 140 to 80, without the mod only to maybe 130-135. Your case seems to be caused by the cpu bottleneck too.

**Comment by MetalKnight56** [comment]
> That's the only reason I don't use the mod. It seems to be heavy on the CPU, when there are lots of mobs around, my FPS drops from 140 to 80, without the mod only to maybe 130-135. Your case seems to be caused by the cpu bottleneck too.

We are looking into solutions on this issue, dw we'll eventually come up with something

**Comment by Yesssssman** [comment]
In 20.8.2, There is an option to use Animation shader which enhances the frame rate when there are many entities nearby you. I'm not sure if your issue is the same case but I saw it was definitely effective for enhance the fps. (See the clue here: https://discord.com/channels/955784714264932362/995760057214050326/1267960715474505808)

Please check this on your environment and give me feedback because I truly want to know if Epic fight is optimized in the best way lol

**Comment by Riyuukii** [comment]
> In 20.8.2, There is an option to use Animation shader which enhances the frame rate when there are many entities nearby you. I'm not sure if your issue is the same case but I saw it was definitely effective for enhance the fps. (See the clue here: https://discord.com/channels/955784714264932362/995760057214050326/1267960715474505808)
> 
> Please check this on your environment and give me feedback because I truly want to know if Epic fight is optimized in the best way lol

hey, I experienced the same problem in DawnCraft, the problem is that the version 20.8.2 is not available for 1.18.2 forge,which is the version dawncraft is using. Will there be any chance of 20.8.2 be ported to 1.18.2? ty in advance!

additional infos (just in case if they can be helpful):
- RTX 4080 Super
- Ryzen 7 7800X3D
- 32GB of RAM with 10GB allocated
- my fps dropped from 200fps with 0 entity all the way down to 40fps with tons of entities around

**Comment by Yesssssman** [comment]
> > In 20.8.2, There is an option to use Animation shader which enhances the frame rate when there are many entities nearby you. I'm not sure if your issue is the same case but I saw it was definitely effective for enhance the fps. (See the clue here: https://discord.com/channels/955784714264932362/995760057214050326/1267960715474505808)
> > Please check this on your environment and give me feedback because I truly want to know if Epic fight is optimized in the best way lol
> 
> hey, I experienced the same problem in DawnCraft, the problem is that the version 20.8.2 is not available for 1.18.2 forge,which is the version dawncraft is using. Will there be any chance of 20.8.2 be ported to 1.18.2? ty in advance!
> 
> additional infos (just in case if they can be helpful):
> 
> * RTX 4080 Super
> * Ryzen 7 7800X3D
> * 32GB of RAM with 10GB allocated
> * my fps dropped from 200fps with 0 entity all the way down to 40fps with tons of entities around

Sorry but we won't backport epic fight to the previous versions. And Dawncraft won't be compatible even if we backport the latest 1.20.1.

**Comment by Razor235T** [comment]
> In 20.8.2, There is an option to use Animation shader which enhances the frame rate when there are many entities nearby you. I'm not sure if your issue is the same case but I saw it was definitely effective for enhance the fps. (See the clue here: https://discord.com/channels/955784714264932362/995760057214050326/1267960715474505808)
> 
> Please check this on your environment and give me feedback because I truly want to know if Epic fight is optimized in the best way lol

Animation shader seems to be good in terms of optimization. But I'm constantly seeing the feature disabling itself, saying: "Failed to create shader glint". A developer of the shaderpack (Bliss shaders), that I use, said about the incompatibility, "Custom shaders from a mod often don't play nice with iris shaders."
