### ISSUE TITLE
[BUG] Uchigatana doesn't respon to attack

### ISSUE THREAD

**Issue by FirdausCraft10** [Yesssssman/epicfightmod#1573]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

EpicFight-20.7.4.jar

### Minecraft Version

1.20.1

### What happened?

While in combat mode the Uchigatana don't respon to attack and it doesn't show any single attack.

**Comment by alexdlcr** [comment]
I happen to have the same issue. In the image you can see what it says after the game crashes
![Captura de pantalla 2024-03-08 121921](https://github.com/Yesssssman/epicfightmod/assets/161983047/1b06cbe9-faf0-4202-ace2-6dad9c16b4ac)

**Comment by FirdausCraft10** [comment]
boss fight also makes the game crash while parrying with weapons. idk if this is becouse the mod compatibilities or maybe the bug is already exist inside the mod. i felt like not enjoying the mod for alot becouse there is many bug about crash that i accidently doing it inside the mod. but about optifine maybe its the problem ig???

**Comment by alexdlcr** [comment]
I'm using oculus instead of optifine so i don't think that's the actual problem. I've considered incompatibility with a mod my first option, probably a performance mod that breaks the animation of epic fight. The problem is I don't know which one is it

**Comment by alexdlcr** [comment]
These are all the mods I'm using
![Captura de pantalla 2024-03-08 151432](https://github.com/Yesssssman/epicfightmod/assets/161983047/4ed10cbd-6748-4a7a-9678-2506c0d102ec)
![Captura de pantalla 2024-03-08 151624](https://github.com/Yesssssman/epicfightmod/assets/161983047/f632e56c-bc68-46ef-b888-ed0a6b2dd092)

**Comment by FirdausCraft10** [comment]
seems like everything is fine when using all those mods, but i think the dev mod needs to fix the mod soon becouse these bugs is already inside the mod. its not just boss fight that make the game crash. parrying skills is also makes the game crash while fight with mobs such as Wither Skeleton and Wither. i tried both and its the same thing happend. but thanks for those mods file i really intrested to try that :D

**Comment by FirdausCraft10** [comment]
but the good part is when using a server the weapons of miracles is no longer makes the player disconnect immediently so thats the good part
