### ISSUE TITLE
[Suggestion]: Difficulty in using rolling related skills when using Leawind's Third Person

### ISSUE THREAD

**Issue by whidte** [Yesssssman/epicfightmod#1575]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

Leawind's Third Person

### Minecraft Version

1.20.1

### What's your suggestion?

When using Leawind's Third Person, using tumbling related skills will tumble in the opposite direction of the model, rather than the opposite direction of the camera.I feel that the cause of the problem is a bit like # 807, which shows that it has been fixed, but the problem still exists on Leawind's Third Person.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
