### ISSUE TITLE
NoClassDefFoundError for InfernalGainer and EpicSanji mods based on Epic Fight. all this from attempting to start Minecraft 1.20.1

### ISSUE THREAD

**Issue by Epicnemesis142** [Yesssssman/epicfightmod#1579]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

InfernalGainers and EpicSanji

### Minecraft Version

1.20.1

### What happened?

Whenever I try to start either the server (1.20.1 Arclight) or the client (1.20.1 Forge version 47.2.20), I get the same error message: NoClassDefFoundError for epicfight's "SkillDataManager$ValueType"

Here is the crash file in its completion, for I have many mods, yet the problem really began with InfernalGainers and EpicSanji (I really like the Epic Fight mod as you can see):

[crash-2024-03-11_13.45.48-fml.txt](https://github.com/Yesssssman/epicfightmod/files/14563499/crash-2024-03-11_13.45.48-fml.txt)

**Comment by Yesssssman** [comment]
Those are outdated
