### ISSUE TITLE
[Issue/Improvement] Can't attack while using elytra

### ISSUE THREAD

**Issue by Spynathan** [Yesssssman/epicfightmod#158]
Currently you can't attack while flying with an elytra while in combat mode, same applies to swimming but with swimming you just revert back to the normal standing combat. I'd imagine it'd take a bit of work, but unique attacks for elytra flight would be amazing. Combos for each weapon might be a pain, but in principal you could use the elytra as the weapon for flight attacks. Or just have a standard elytra combo for melee weapons. The character Zephyr from warframe comes to mind, could serve as some good inspiration. But I'm sure you'll come up with a great idea yourself.

PS, I didn't want to make a whole post for this, so I'll just add it here, a discord server to discuss the mod would be nice. Especially to discuss balance in regards to things like PvP but it's just a suggestion. 

PPS, Love your work so I tipped 5$ to your paypal, it's not much but at least you can get a coffee kek

**Comment by Yesssssman** [comment]
I don't know people can hit their foe while flying at such high speed. You know, Elytra is not designed for the battle but for the movements. But the real matter is the size of the mod file could be doubled or tripled. The size of the animation file accounts for almost 70~80% of the total size of the mod file, so adding the new attack animation while swimming or flying for each weapon can be hugely increased the size of the mod file.

Anyway, thanks for your support. That was such a great help to me!

**Comment by Spynathan** [comment]
Yeah I'm probably one of the few people who ever fight with elytra kek. Good to know though, thanks for the explanation. Optimization is pretty important, so I'm glad you're keeping it in mind. Keep up the good stuff m8
