### ISSUE TITLE
[BUG] Animations working but not?

### ISSUE THREAD

**Issue by kayrovrs** [Yesssssman/epicfightmod#1580]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

the running animations work fine, but when trying to do the skills from epic fight it's just the og Minecraft's animation. Is something not compatible or a bug?

![Screenshot_14](https://github.com/Yesssssman/epicfightmod/assets/163220233/19d15fe4-c89f-4620-a19d-104874b617e1)

**Comment by kayrovrs** [comment]
Normal attacking is also animations from og minecraft

**Comment by StormCharLux** [comment]
Well, I have compatible mods and I have been testing the weapons and the only one that has problems is the animation of the uchigatana, there is no attack animation and shortly after it closes if you insist, with the weapons of miracle mod the satsujin sword has another animation therefore is not causing the error, please review the uchigatana/Katana animation
