### ISSUE TITLE
[Bug|Crash]: 1.18.2 forge server does not start properly

### ISSUE THREAD

**Issue by ReverieAurora** [Yesssssman/epicfightmod#1581]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

information:
forge:40.2.17
mod version:18.5.24

Problem description:
I've added an epic fight mod to my server,it launched normally at first.but it stop suddenly.
what's more,when I use epic fight in version 18.5.21,the server will start up normally.
So I additionally tested other versions of epic fight and found that versions from 18.5.21 onwards would cause the above issues.
(By trying the above, I'm almost certain that the error was caused by the epic fight. but idk the specifics of it)

console output：
[latest.log](https://github.com/Yesssssman/epicfightmod/files/14614986/latest.log)

**Comment by Yesssssman** [comment]
Crash from epic_fight_battle_styles
