### ISSUE TITLE
[Bug|Crash]: 1.20.1 - Can't attack on dedicated server

### ISSUE THREAD

**Issue by nwadekoko** [Yesssssman/epicfightmod#1582]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Better combat?

### Minecraft Version

1.20.1

### What happened?

Hello, I have no idea how I managed to do this but currently I'm able to play with Better Combat when in first person and I can also switch to battle mode of Epic Fight whenever I want, and both mods works together. I have been searching all over because I can't find if they're supposed to be compatible, from my understanding people put one or the other. 

So yeah it works in solo worlds but once on my dedicated server with my friends, they can't seem to be able to use Epic Fight attacks (LMB) unless while jumping for some reason. I was wondering if all of this is normal ? Is it just a pure incompatibility with Better combat ? If so I wonder how I got both to work, and if there is a way to keep both working as I don't see why it couldn't be compatible, one being majorly used in first person and the other in third.

I tried not hosting the server and went on my friend's server, again on her solo world she can use Epic fight and better combat just like me, but once on the multiplayer server, she could still do both types of attacks (EF when in 3rd person and BC when in 1st) but I could only attack with BC in first person, once in third person, weirdly enough I COULD attack with LMB but it only did the animation of the Swords jump attack, whereas I was not jumping.

All of this is pretty weird, but it doesn't cause any crash, so I don't know what more to put to help you. Here's a list of all the mods in the modpack :
![2024-03-17 22_23_05-mods](https://github.com/Yesssssman/epicfightmod/assets/57798775/a0beae18-d44c-4d3d-904d-ac55bbc40675)

Also just to clarify, I use Essential Mod to host my singleplayer world as a server for my friends to join, Idk if that makes any difference in the way the game handles the "server" and if maybe that could be a cause. In the picture above Essential is disabled because I was doing some tests.

**Comment by nwadekoko** [comment]
Quick update : We tried to find some solutions and I saw Player Revive wasn't making things easy with Epic fight apparently. I replaced the mod with Hardcore revival and idk if thats the reason, but all of us three can use Epic fight now ! 
Only thing that changed is that Better combat still works in first person but the attacks doesn't do damage.
So I'm also seeing on Better combat side, but ultimately it would be awesome if both Epic Fight and Better combat could work complementary.

**Comment by nwadekoko** [comment]
I also have tried to make a regular server with the same mods, I can't join the world even...
Here's the crash log in case someone can try to help me there as I don't understand most of it
https://pastebin.com/hmM0gC2B

**Comment by MakkuSaiko** [comment]
(Disclaimer, I'm not the mod developer)

Hi there. 
I checked your logs, and it seems like there is an error involving better combat. Idk, if the mods are not compatible. 
Does it crash if you attack in normal mode or battle mode or both?

**Comment by Yesssssman** [comment]
> I also have tried to make a regular server with the same mods, I can't join the world even... Here's the crash log in case someone can try to help me there as I don't understand most of it https://pastebin.com/hmM0gC2B

Crash in better combat mod
