### ISSUE TITLE
[Bug]:  Vanilla Attacks Occur In Battle Mode (In Base Epic Fight)

### ISSUE THREAD

**Issue by Saithe6** [Yesssssman/epicfightmod#1583]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

When doVanillaAttack is on vanilla attacks will occur in battle mode. There is a similar issue relating to this happening with weapons from a different mod but this is happening in base Epic Fight and leads to problems such as being able to attack mid roll and hitting enemies before you swing at them. I noticed this in version 20.7.4 but it seems to have been introduced in 20.6.5. I'm on forge version 47.2.21 which is the current forge version at this time.

**Comment by Yesssssman** [comment]
Please check if the same bug exists in the latest version

**Comment by Saithe6** [comment]
seems to be fixed!!!!
