### ISSUE TITLE
[Bug|Crash]: Ticking player

### ISSUE THREAD

**Issue by PorpleMoi** [Yesssssman/epicfightmod#1584]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

When I using dual-wielding of swords and paired weapons against any mobs, including vanilla ones, the game crashes with a ticking issue message. I'm unsure how to address this problem; I've tried removing various modifications and installing them in different combinations, but I still can't identify the root cause. This occurs with weapons from both the Epic Fight and others weapons from L'Ender Cataclysm, RPG Weapons, and Born in Chaos.

I've also installed the latest version of Forge, removed optimization mods, Gekolib, and L'Ender Cataclysm, etc., but I still can't figure out what's causing it.

[crash-2024-03-18_20.06.17-server.txt](https://github.com/Yesssssman/epicfightmod/files/14639244/crash-2024-03-18_20.06.17-server.txt)

**Comment by Yesssssman** [comment]
This is known issue in weapons-of-miracle 20.1.7.39. Please update the wom version.
