### ISSUE TITLE
[Suggestion]: [1.20.1] I hope the mod can suppon Skin Layers 3D

### ISSUE THREAD

**Issue by NicholasWong-3069** [Yesssssman/epicfightmod#1586]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d

### Minecraft Version

1.20.1

### What's your suggestion?

I hope the mod can suppon Skin Layers 3D
![image](https://github.com/Yesssssman/epicfightmod/assets/121357783/62854c47-b058-4882-9d68-ec7904d6111c)
![image](https://github.com/Yesssssman/epicfightmod/assets/121357783/4cb0b5ed-9b8d-4508-b158-1b0ecf850950)

**Comment by guivnf** [comment]
Fixed in 20.8.2. We weren't able to fix all the changes to the older versions. Thank you for your consideration.
