### ISSUE TITLE
[Bug|Crash]: Whenever I kill hostile mobs, server crashes

### ISSUE THREAD

**Issue by HenryMin13** [Yesssssman/epicfightmod#1588]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

EpicFight-19.5.24.

### Minecraft Version

1.19.2

### What happened?

I'm hosting a modded server using Aternos consisting of the mods "Origins" (with Origins++), "Xaeros Minimap", "Ars Nouvaeu", and Epic Fight (with Weapons of Miracle). I'm playing on the version 1.19.2 and the latest forge which is 43.3.9

All the mods work properly as well as Epic Fight except when I kill mobs, specifically hostile mobs, the server crashes and says "connection lost: Internal Server Error". I've tested on passive mobs and I dont crash when I kill them, only hostile mobs like zombies, creepers, skellys, spiders etc. I also tested to kill the mobs outside of combat mode and I dont crash so its clearly the Epic Fight crashing me, how to fix?

**Comment by HenryMin13** [comment]
I tried also killing hostile mob in a single player mob, mc crashed and this was the error code, if it helps:

The game crashed whilst ticking player
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "this.lootTableId" is null

**Comment by Yesssssman** [comment]
Crash in apoli mod
