### ISSUE TITLE
[Feature/Quality of Life] Blocking

### ISSUE THREAD

**Issue by thedeerirty** [Yesssssman/epicfightmod#159]
The idea itself is simple;

Weapons have a blocking animation they can use. It won't fully stop damage, but reduce it, like old sword combat.
Different weapon types (or even configurable per weapon) have more damage reduction, but maybe slower windup speed into blocking.

Additionally, if timed within a certain window, you can parry an attack to avoid damage completely, stun/knock back enemies, deflect projectiles, and maybe gain a small amount of special energy.

**Comment by StLankowski** [comment]
That is SO cool Idea! That would be perfect!

**Comment by thedeerirty** [comment]
Thanks!

In addition, I think each weapon type should have a different parry window, making some types easier to parry with than others.

Greatswords being the hardest (because they're likely heavier and harder to move to parry quickly) while Katana class weapons having a really fast and easier parry window

**Comment by TurkishAhmet4545** [comment]
Hmm will sword blocking be like mount and blade or 1.7x
