### ISSUE TITLE
[Bug|Crash]: Incompatible with Leawind's Third Person

### ISSUE THREAD

**Issue by iekiekkeikei** [Yesssssman/epicfightmod#1590]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://modrinth.com/mod/leawind-third-person

### Minecraft Version

1.20.1

### What happened?

The camera is forced to be centred on the player when attacking.

- put the player in combat mode.
- put the player in third person view.
- attack.
- force the camera to centre on the player.

Expected behavior
When attacking during combat mode, the third-person camera is momentarily centred on the player.

**Comment by Tapacywka** [comment]
Exactly the same problem happens with the [Shoulder Surfing Reloaded](https://modrinth.com/mod/shoulder-surfing-reloaded).

**Comment by LAPEORRA** [comment]
Is there any update on this bug?

**Comment by LAPEORRA** [comment]
Is there any update on this bug?

**Comment by Yesssssman** [comment]
it's been fixed and will be reflected in the next update. Thanks for reporting

**Comment by Tapacywka** [comment]
> it's been fixed and will be reflected in the next update. Thanks for reporting
Is this fixed for Shoulder Surfing Reloaded too? Or only for LTP?

**Comment by MetalKnight56** [comment]
https://github.com/LEAWIND/Third-Person/discussions/84
Issues regarding lock-on will be moved to this discussion as it's not specifically on our side to fix this.
