### ISSUE TITLE
[Bug]:  The Uchigatana has the standard sword moveset

### ISSUE THREAD

**Issue by LordM4x** [Yesssssman/epicfightmod#1591]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

I joined the world, found a Uchigatana and it just has the standard Sword moveset
[latest.log](https://github.com/Yesssssman/epicfightmod/files/14747044/latest.log)
If I press Ctrl F in this log and search uchigatana it seems to register all animations so idk whats up

**Comment by Yesssssman** [comment]
You should check the epic fight version. This is known issue that I fixed 20.7.3 (Check the changelog also here: https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/5148983)

**Comment by LordM4x** [comment]
> You should check the epic fight version. This is known issue that I fixed 20.7.3 (Check the changelog also here: https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/5148983)

I'm using 20.7.4

**Comment by MetalKnight56** [comment]
> > You should check the epic fight version. This is known issue that I fixed 20.7.3 (Check the changelog also here: https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/5148983)
> 
> 
> 
> I'm using 20.7.4

According to your logs you are not
