### ISSUE TITLE
[Bug|Crash]: 1.16.5 Register items. Cannot save.

### ISSUE THREAD

**Issue by al-wei** [Yesssssman/epicfightmod#1592]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.16.5

### What happened?

Register items. Cannot save.
No save button.
The esc will exit and cannot be saved.
The enter key doesn't have any effect.

Epic Fight 16.6.5, Forge 36.2.39
![image](https://github.com/Yesssssman/epicfightmod/assets/145486869/17b3b21c-53d7-4926-ac36-50a4d79f9e4b)

**Comment by al-wei** [comment]
+1
![image](https://github.com/Yesssssman/epicfightmod/assets/145486869/ab445c79-8e6c-43a5-8c6e-fdf519656e03)

**Comment by Yesssssman** [comment]
Sorry but we don't support 1.16.5 anymore rn
