### ISSUE TITLE
[Bug|Crash]: 1.18.2 Can't attack in battle mode at all. Dedicated server Dawncraft 2.0.5

### ISSUE THREAD

**Issue by Balzakito** [Yesssssman/epicfightmod#1593]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

Can't attack while in battle mode, in build mode I can but I can't shoot a (cross)bow in either mode. Problem persists after relogging. This problem just randomly started appearing, it's been fine since we started the server but today for some reason it stopped working. I believe it started after the server crashed once because I completed a villager quest in dawncraft and was awarded a map. 
[latest.log](https://github.com/Yesssssman/epicfightmod/files/14826003/latest.log)

**Comment by Raiiiden** [comment]
I recommend asking in their discord as for one it's their modpack, and two you said it started after you completed a quest which is a mod made by their team

**Comment by Yesssssman** [comment]
We fixed the skill data key issue in 1.20.1 Please update to that version
