### ISSUE TITLE
[Bug|Crash]: Epic Fight has failed to load correctly (and three others)

### ISSUE THREAD

**Issue by Nova-Ozuka** [Yesssssman/epicfightmod#1595]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

_https://www.curseforge.com/minecraft/mc-mods/epic-sanji https://www.curseforge.com/minecraft/mc-mods/epic-paragliders_

### Minecraft Version

1.20.1

### What happened?

So ButterJaffa built a modpack, and I wanted to try it myself. I've tried several times to get pass the issue of four mods not loading correctly. Besides Epic Fight, I'm also having the same issue with three add-ons: WoM, Epic Sanji, and Epic Fight - Zelda, Legend of the Master Sword, with the latter two being something I added for personal preference. I've tried removing the extra two add-ons, removing Epic Fight NBT integration, and even using an older version of Epic Fight, but at this point, it feels like I'm banging my head against the wall.

Edit: Before I was using the latest version of Forge, but I tried the recommended version just now

Edit 2: I tried removing mods in bulk and then pulling out different add-ons to find the problem, and now I can confirm that there is 2 compatibility issues. Epic Sanji has one, and Epic Paraglider is another. I don't know if it has to do with the current version of Epic Fight or any other specifics though.

[crash-2024-04-03_10.11.35-fml.txt](https://github.com/Yesssssman/epicfightmod/files/14854594/crash-2024-04-03_10.11.35-fml.txt)
[crash-2024-04-03_00.36.06-fml.txt](https://github.com/Yesssssman/epicfightmod/files/14854692/crash-2024-04-03_00.36.06-fml.txt)
[crash-2024-04-03_00.11.08-fml.txt](https://github.com/Yesssssman/epicfightmod/files/14854743/crash-2024-04-03_00.11.08-fml.txt)
[crash-2024-04-03_12.12.10-fml.txt](https://github.com/Yesssssman/epicfightmod/files/14855955/crash-2024-04-03_12.12.10-fml.txt)

[crash-2024-04-03_17.18.03-fml.txt](https://github.com/Yesssssman/epicfightmod/files/14859167/crash-2024-04-03_17.18.03-fml.txt)

**Comment by Raiiiden** [comment]
First question: Are you/did you update any mods in the modpack after installing it like Epic Fight?
Second Question: Did you remove any addons after installing the modpack.

You shouldn't have to do anything after installing the modpack, if you want to edit the modpack do not update any mod as it will probably crash.

**Comment by Raiiiden** [comment]
My guess is you updated Epic Fight in their modpack and now it's crashing because the addons don't support the newer version of epic fight

**Comment by Yesssssman** [comment]
You're using an outdated addon that is not supported for epic fight (20.7.4).
