### ISSUE TITLE
[Bug|Crash]: Launcher/Server doesn't start

### ISSUE THREAD

**Issue by JCabreraS7244** [Yesssssman/epicfightmod#1596]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

When I try to launch my server or client it crashes immediately. The original Minecraft client just prompted me with the "1 error" message. However, the server sent me these logs --> https://mclo.gs/RnSLqGn

I'm using the recommended Forge 47.2.0 and Minecraft 1.20.1. I tried with various Epic fight versions, but it is the same

**Comment by AugustMen** [comment]
Hello, try forge version 43.3.8 and higher.
