### ISSUE TITLE
[Suggestion]: Optional integration with Feathers

### ISSUE THREAD

**Issue by ClockworkCorvus** [Yesssssman/epicfightmod#1598]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

https://www.curseforge.com/minecraft/mc-mods/feathers

### Minecraft Version

1.20.1

### What's your suggestion?

Given that Epic Fight is a souls-like combat mod with a stamina system, it might make sense to incorporate a mod like Feathers, if at least as an optional dependency/compatibility.

Armor weight (that as far as I can tell works for all mods), a built in stamina system that is effected by said armor weight, etc. might make a good match with the rest of Epic Fight's mechanics. Limiting one's stamina capability by their armor weight would make a ton of sense.

**Comment by MetalKnight56** [comment]
> ### Have you checked if there's any similar suggestions ?
> 
>     * [x]  I checked, there are no similar suggestions that have been reported.
> 
> 
> ### Are you using the latest Epic Fight ?
> 
>     * [x]  I checked I'm using latest Epic Fight version.
> 
> 
> ### Is this suggestion related to another mod? (i.e: add animations for X mod)
> 
>     * [x]  This is related to other mods.
> 
> 
> ### The mod
> 
> https://www.curseforge.com/minecraft/mc-mods/feathers
> ### Minecraft Version
> 
> 1.20.1
> ### What's your suggestion?
> 
> Given that Epic Fight is a souls-like combat mod with a stamina system, it might make sense to incorporate a mod like Feathers, if at least as an optional dependency/compatibility.
> 
> Armor weight (that as far as I can tell works for all mods), a built in stamina system that is effected by said armor weight, etc. might make a good match with the rest of Epic Fight's mechanics. Limiting one's stamina capability by their armor weight would make a ton of sense.

I don't think feathers or any elenai mod is still being worked on still... It's last update was in on Oct 24, 2023
