### ISSUE TITLE
[Bug|Crash]: End portal

### ISSUE THREAD

**Issue by murhi** [Yesssssman/epicfightmod#1599]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

After we killed the ender dragon, no portal spawned for us to go home, and no portal to the end city spawned. the only way for us to get home was to jump in the void.

**Comment by Yesssssman** [comment]
Not an epic fight issue.
