### ISSUE TITLE
Hi, a few questions I have

### ISSUE THREAD

**Issue by desmandias** [Yesssssman/epicfightmod#16]
Heyo! Sorry if this is _only_ for issues, but I wasn't quite sure if there was a better place to ask

I'm curious at the compatiblity with other mods, say stuff like Ice and Fire, Mahoutsuki, etc. Would they be causing some issues, crashes, rendering errors, etc.? Or, something like vampirism, which I think changes the player model every so slightly.

Furthermore, was going to suggest maybe a compact with Tetra? Having a modular weapon system combined with this great combat idea seems like a good combination. At the very least, if its not an option already, maybe a config where you could classify items as swords, katanas, greatswords, etc.?

**Comment by Yesssssman** [comment]
The every custom armor has rendering issue cause I made a new model that only works with vanilla armor models. I can't remake all of custom armors, so It can't be fixed in short period.
And you can setup the config file to make compatible with weapons of other mod. Here is good example so refer to this.

https://www.curseforge.com/minecraft/customization/epic-fight-spartan-weaponry

**Comment by desmandias** [comment]
the armor does make sense; but I was thinking more of mobs from those mods, and the like; how that sort of effect gets calculated

also, what has to be done for the armor, coding wise? Or does it simply just have to be modelled to fit the new player models being used?

and sweet! that'll be useful, thanks so much!

**Comment by Yesssssman** [comment]
Yes. the remaked model includes the data of which part this vertex is so the model can transformed matching to player's pose. custom armor doesn't have this information so it's impossible to matching to animation's pose. Just think of mo'bends mod.

**Comment by desmandias** [comment]
ah... so you'd have to redesign the models themselves to flow with the player's model, if I'm understanding correctly

**Comment by desmandias** [comment]
Also, question; can i classify other weapons as trident weapons? doesn't seem to be an option in the config.

**Comment by Yesssssman** [comment]
the trident follows the spear attack motion without two handed attack motion. if you want it, I'll add trident option.

**Comment by desmandias** [comment]
Sorry for the late reply, but yes! I think many besides me would enjoy it; plus, it has a throwing-weapon animation if i remember right.
