### ISSUE TITLE
Bug|Crash]: 1.20 herrsche sword and shield combo bugged

### ISSUE THREAD

**Issue by AlucardWolf** [Yesssssman/epicfightmod#1602]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Weapon of mircle 

### Minecraft Version

1.20.1

### What happened?

Im not really sure what may have happend but the current issue im having is when i try to use the herrsche and the shield combo thats primary compatibility is with epic fight. I am unable to actually use the full combo or the charge hit with out my player character freezing in mid charge combo only to crash specifically if i don't scroll of the weapon in main hand, and me taking the shield manually out of my off-hand otherwise if move the shield while frozen i'll crash.

**Comment by Yesssssman** [comment]
Not epic fight issue
