### ISSUE TITLE
[Bug|Serverside Kick]: Weapons of Miracles Serverside error

### ISSUE THREAD

**Issue by Ryuco** [Yesssssman/epicfightmod#1604]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

Forge 1.19.2

### What happened?

_**Main issue**_
When swinging or holding certain weapons inside a server you get error message attached as an image below. The weapons that cause this problem as well as steps to recreate this that i have found are:

Antitheis (any swing and certain idle animations)
Enderblaster (Duel wielding sprint jumpshot and attack animations)
Torment (Simply holding it causes you to repeatedly crash like this until inventory is reset)
Herrscher & Gesetz (any attack when wielding both)
Agony (weapon innate skill)
Satsujin (Weapon innate skill and many idle animations)

_**List of Currently used mods**_
[Cultural Delights (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/cultural-delights)
[End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)
[Miner's Delight + (by soytutta)](https://www.curseforge.com/minecraft/mc-mods/miners-delight-plus)
[Tetra: Hammered (by krabby7_plays)](https://www.curseforge.com/minecraft/mc-mods/tetra-hammered)
[mutil (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/mutil)
[Epic Fight NBT Integration (by pitbox46)](https://www.curseforge.com/minecraft/mc-mods/epic-fight-nbt-integration)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Decoration Delight: Refurbished (by InfernoSakai)](https://www.curseforge.com/minecraft/mc-mods/decoration-delight)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[Crabber's Delight (by AlabasterLeking)](https://www.curseforge.com/minecraft/mc-mods/crabbers-delight)
[Tetra (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/tetra)
[Brewin' And Chewin' (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/brewin-and-chewin)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Alex's Delight (by NCP_Bails)](https://www.curseforge.com/minecraft/mc-mods/alexs-delight)
[Epicfight - Dual GreatSword (by reascer)](https://www.curseforge.com/minecraft/mc-mods/epicfight-dual-greatsword)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[Tetranomicon (by syrikalis)](https://www.curseforge.com/minecraft/mc-mods/tetranomicon)
[Epic Fight (by maninthe_home)](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Weapons of Miracles - epic fight (by reascer)](https://www.curseforge.com/minecraft/mc-mods/weapons-of-miracles-epicfight)

_**Latest Serverside Log**_
[latest.log](https://github.com/Yesssssman/epicfightmod/files/14938662/latest.log)

![Screenshot 2024-04-10 185928](https://github.com/Yesssssman/epicfightmod/assets/106418818/b1c52059-08e2-477e-9121-c7401ab3439f)

**Comment by Ryuco** [comment]
if anyone has any sort of fix please let me know, Ive had this problem a lot in the past and haven't personally seen it talked about

**Comment by Mint060821** [comment]
Same issue here MC 1.19.2 , a friend kept getting that error whenever they swing any weapon while R is active (epic fight animations) 

I haven't really found a solution yet.

**Comment by Yesssssman** [comment]
This is a known issue and we already fixed it in 1.20.1 in both Weapons of Mircale and Epic Fight. But we can't afford the amount of work which becomes twice as we have to port 1.19.2 and 1.18.2 at the same time. If you don't want to get this problem please update your Minecraft version. Thanks.
