### ISSUE TITLE
Incompatibility with Eidolon weapons

### ISSUE THREAD

**Issue by Spynathan** [Yesssssman/epicfightmod#161]
Eidolon has a couple weapons that have unique effects, such the Sword of Sapping that heals you as you deal damage and the Reaper's Scythe which causes mobs to drop specific items when you kill them using it. When using them in combat mode however the effects don't occur. I wasn't sure whether to report it here or on Eidolons git, but since epic fight is the more complex mod of the two I figured I'd report here.

**Comment by BadGhost92** [comment]
please add this mods too (spartan weaponry)

**Comment by Spynathan** [comment]
Fixed in the latest update woo! I'll go ahead and close this
