### ISSUE TITLE
[Bug|Crash]: Server related problem

### ISSUE THREAD

**Issue by AugustMen** [Yesssssman/epicfightmod#1613]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [x] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

Good evening.
I encountered a problem that the mod does not work correctly on the server.
There is only one mod - Epic Fight
The problem is that it sometimes works, sometimes it doesn't.
Sometimes it happens that you cannot hit, the LMB simply does not react.
At other times you can hit, but only with one attack.
What could be the problem?
Every time you turn it off and on there are different problems.

**Comment by guivnf** [comment]
Provide logs and footage.
