### ISSUE TITLE
[Bug|Crash]: Epic Fight break / Slash Blade Mod holding right click attack.

### ISSUE THREAD

**Issue by Cookie-0319** [Yesssssman/epicfightmod#1614]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Slash Blade

### Minecraft Version

1.20.1

### What happened?

This report used translation.
Slash Blade Mod's sword has an attack that activates Judgment Cut by holding and release right click. If you introduce Epic Fight, that attack will no longer be able to be activated. I suspect that the cause is that Epic Fight is overriding the right click, and I have reported it.

Epic Fight - 20.7.4
[Slash Blade](https://www.curseforge.com/minecraft/mc-mods/slashblade) - 0.1.2
Forge 1.20.1 47.2.20

**Comment by Yesssssman** [comment]
Could you check if the same problem exists in latest epic fight versions?
