### ISSUE TITLE
[Bug|Crash]:  Medieval entity datapack not doing chase animation when seeing a target, will just walk towards enemy

### ISSUE THREAD

**Issue by AzureAxi** [Yesssssman/epicfightmod#1615]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Medieval entity, and a datapack for medieval entities to be compatible with efm

### Minecraft Version

1.18.2

### What happened?

So i'm using medieval entity mod and a datapack made by MPsantos20 that makes the entities in that mod compatible with efm. But the chase animation doesn't work properly because when it sees the player, it will walk but have the same amount of speed as the running. I do not like the fact that the animation it uses for running is "walking". Could anyone explain how would i fix this issue? as of i know, medieval entity is not made for efm but it can be via. Datapacks.

![image](https://github.com/Yesssssman/epicfightmod/assets/167629761/fc0e090c-b079-4527-99f1-6bf85ec26179)

**Comment by AzureAxi** [comment]
Oh, and also the datapack uses Indestructible mod for EFM

**Comment by AzureAxi** [comment]
Problem fixed, Medieval entity mod wasn't compatible with efm. I tried copying a json file from a efm mod that has entities that can run with efm animation. It did not run, it simply just walked. You may try the mod "medieval entity" and the datapack from "Mpsantos20". It is in curseforge.

**Comment by Cyber2049** [comment]
that's not the problem from EFM.
