### ISSUE TITLE
[BugCrash]: The game crash when using parry skill while fighting mobs

### ISSUE THREAD

**Issue by FirdausCraft10** [Yesssssman/epicfightmod#1617]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

EpicFight-20.7.4.jar

### Minecraft Version

1.20.1

### What happened?

When i was fighting with mobs and using parry skill the game crash immidently. idk whats wrong..

**Comment by Raiiiden** [comment]
Gonna need a log. Does this happen in Singleplayer or Multiplayer or both

**Comment by FirdausCraft10** [comment]
It happens both of them

Pada Rab, 24 Apr 2024 03.30, Raiden ***@***.***> menulis:

**Comment by FirdausCraft10** [comment]
> Gonna need a log. Does this happen in Singleplayer or Multiplayer or both

This thing happend both idk but if i use parry skill in multiplayer when fighting, the game doesnt crash but unexpected disconnect
