### ISSUE TITLE
Is patching addon's fightstyle to mobs truly possible?

### ISSUE THREAD

**Issue by 5A93** [Yesssssman/epicfightmod#1618]
Sorry to ask here, I'm poor on coding so not exactly how it works. Went through all my test it seems to me that maybe all that addon authors had missing something, datapack either cannot be loaded or weapon type automatically be misidentified to one of those in origin mod

**Comment by Yesssssman** [comment]
We know the problem datapack is not very intuitive and understandable for both users and developers. We're currently developing a new system that enables users to create a custom datapack in the game. It'll have enhanced usability and trace the issues that your pack currently has. Thanks.

![image](https://github.com/Yesssssman/epicfightmod/assets/79469058/cbeb0cb1-83de-45da-b0e9-4d593bd631d9)

**Comment by 5A93** [comment]
> We know the problem datapack is not very intuitive and understandable for both users and developers. We're currently developing a new system that enables users to create a custom datapack in the game. It'll have enhanced usability and trace the issues that your pack currently has. Thanks.
> 
> ![image](https://private-user-images.githubusercontent.com/79469058/325147129-cbeb0cb1-83de-45da-b0e9-4d593bd631d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNDI1ODUsIm5iZiI6MTcxNDM0MjI4NSwicGF0aCI6Ii83OTQ2OTA1OC8zMjUxNDcxMjktY2JlYjBjYjEtODNkZS00NWRhLWIwZTktNGQ1OTNiZDYzMWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDIyMTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZTBhYTE3OWU4ZmJjOWFlNTBlN2M2M2YyNDZkOGE1MjMyNTdiOTlhY2I4OGU3YzM0MWM0ZDgxYTJmYWVhZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._YgyMa9Y_5wD0YEX12gLUKB4dbY7JvHyxJTZaZnDfXE)

Thank you for your excellent effort! Hope problems is gonna solved by the upated is releasing. I've been further test addon mods these days, and found that an addon called Epic Fight - Infernal Gainer could easily make mobs adapted to its own movesets without adding

**Comment by guivnf** [comment]
added editor on 20.8.2+

**Comment by 5A93** [comment]
> 在 20.8.2+ 上添加了编辑器

I think there is some misunderstanding. I mean, weapons from the mod itself works perfectly fine with mobs, the problem came from addon weapons' ultilizing failure and I didn't know why. I shall test the newest version with WOM to find out if it's still happening.

**Comment by guivnf** [comment]
> > 在 20.8.2+ 上添加了编辑器
> 
> I think there is some misunderstanding. I mean, weapons from the mod itself works perfectly fine with mobs, the problem came from addon weapons' ultilizing failure and I didn't know why. I shall test the newest version with WOM to find out if it's still happening.

addon weapons are not handled by us but by those addon authors
