### ISSUE TITLE
[Bug|Crash]: Battle mode doesn't work properly when Freecam mod is installed.

### ISSUE THREAD

**Issue by Vutka1** [Yesssssman/epicfightmod#1619]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Freecam (Modrinth legit version) 1.2.1 : https://modrinth.com/mod/freecam/version/1.2.1-forge-mc1.20

### Minecraft Version

1.20.1

### What happened?

Whenever you have Freecam installed, entering battle mode doesn't do anything. Weapon icon in bottom right corner **does** appear, meaning that battle mode is active, however no player animations work, all weapon hits are performed as vanilla hits (though hostile mobs still successfully perform their attack animations). Skills menu also shows that you have no skills, even if you do have some skills learned.
Deleting Freecam reverts everything to working state.

**Comment by Yesssssman** [comment]
Will be fixed in the next update. Thank you.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
