### ISSUE TITLE
[Bug|Crash]: Incompatibility with an Alex's Caves item: Galena Gauntlet

### ISSUE THREAD

**Issue by Greg727** [Yesssssman/epicfightmod#1622]
### Have you checked if a similar issue is already reported by someone else?

- [ ] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/alexs-caves/files/all?page=1&pageSize=20&showAlphaFiles=show

### Minecraft Version

1.20.1

### What happened?

I was using Epic Fight with the mod Alex's Caves. In Alex's Caves, there is an item called Galena Gauntlet, but it doesn't work properly when used along side Epic Fight.

**Comment by guivnf** [comment]
Provide footaged of the issue.

**Comment by survival888** [comment]
I also have this bug i will post a video of it here a little bit later

**Comment by survival888** [comment]
with the epic mod with alex caves installed does the gelene gountlet  not work correctly with items vanish or become invisable when with the gelena gountlet with this video you see how the item is suppost to work
https://drive.google.com/file/d/1S4-pHmDfB_NdXDbzvkRUwZR76jJ6d8lW/view?usp=sharing
