### ISSUE TITLE
[Bug|Crash]: No endermen while fighting ender dragon and after that

### ISSUE THREAD

**Issue by Xyz01847910** [Yesssssman/epicfightmod#1626]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

I turned gamerule "nomobsinbossfights" to false. But endermen aren't spawning(well, they are but they are invisible) on the main island in end. Even after killing the dragon there are no endermen on the main island

**Comment by Yesssssman** [comment]
Thanks, it will be fixed in the next update.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
