### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by FuryJack07** [Yesssssman/epicfightmod#1628]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/icarus

### Minecraft Version

1.20.1

### What happened?

Any time i try to use both the icarus and the epic fight mods, the game crashes during mod loading with exit code -1 and [This](https://pastebin.com/exA67nwF) crash report

**Comment by Yesssssman** [comment]
I just removed the mixin file in the newer version(20.8.2). Thanks for reporting!
