### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Queens21s** [Yesssssman/epicfightmod#1629]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.planetminecraft.com/texture-pack/glamrock-freddy-fazbear-optifine-1-18/

### Minecraft Version

1.18.2

### What happened?

I have a texture pack that changes the textures of the iron golem and the spiders (and endermen but i havent seen one after i added this mod so i dont know if they have the same problem, but probably since their animations also changed with this mod) after adding this mod their textures are completely ruined. they are see through and the textures are at the wrong part of their body n stuff. Can this be fixed?

and also when trying to open the game it gave me an error sayin Epic Fight ran into an error, this is the log:
[latest.log](https://github.com/Yesssssman/epicfightmod/files/15202716/latest.log)

at the end of it, it says stuff about the Fazbear n friends texture pack and epic fight mod.

Forge version: 40.2.17
Epic fight: 18.5.24

**Comment by guivnf** [comment]
Optifine dependant and resourcepacks like it are not supported as we also temper with model changes to the vanilla mobs. If you want to change entity models and animations please do so in blender, the wiki should help you a bit.
