### ISSUE TITLE
[Bug|Crash]: mod incompatibility with the "first person" mod 

### ISSUE THREAD

**Issue by XSwiftxX** [Yesssssman/epicfightmod#1630]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/first-person-model

### Minecraft Version

1.18.2

### What happened?

well , when playing the game using epic fight mod with the first person mod the player model overlaps the original model , the first person mod tries to show the player's full body but the epic fight mod's player model covers the player's view , and make it unplayable , i want to play your mod with the ability to actually see me waving the weapon with my hand on the target , not just a weapon floating around 
![image_2024-05-03_211305433](https://github.com/Yesssssman/epicfightmod/assets/168859544/31250504-fc6c-4cdd-977d-e34db67e2e94)

**Comment by AugustMen** [comment]
I'm a Russian speaker, so use Google translator

Приветствую тебя, возможно уже поздно, но я решил эту проблему и хочу поделиться с теми, кто до сих пор сталкивается с ней.

- Почему так происходит?

Проблема в том, что эти два мода имеют свою камеру и они конфликтуют друг с другом, из-за чего и происходит нечто подобное.

- Как это решить?

Всё довольно просто, даже не нужно выходить из Майнкрафта. Для того, чтобы это исправить, нужно в самом майнкрафте зайти в "Настройки" - "Управление". Далее нужно найти там мод Firstperson "Переключение вида от первого лица" и Epic Fight Combat "Toggle Battle/Mining Mode". Меняем эти два пункта на одну кнопку и всё работает.

- Пояснение для тех, кто вдруг не понял.

Скажем Firstperson "Переключение вида от первого лица" стоит на F6, а Epic Fight Combat "Toggle Battle/Mining Mode" на R. Нужно, чтобы они активировались вместе на одну клавишу, скажем R и тогда Firstperson "Переключение вида от первого лица" будет стоять на R вместе с Epic Fight Combat "Toggle Battle/Mining Mode".

**Comment by Yesssssman** [comment]
The issue has been fixed but in 1.20.1. Sorry but I wasn't able to reflect all the changes to the older versions.
