### ISSUE TITLE
[Bug]: Missing gamerule title strings in "Edit Game Rules" screen.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1632]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

Mod is missing some gamerule title strings in "Edit Game Rules" screen.

### Steps to reproduce

1. Start Minecraft 1.20.1 with the latest version of Epic Fight and with recommended Forge version;
2. Make sure that your game is in "English (US)" locale. If not, change language by pressing dedicated button on the main screen and choosing specified locale;
3. Press "Singleplayer", "Create New World", "More" tab, "Game Rules";
4. In the "Player" and "Spawning" sections you'll see `gamerule.stiffComboAttacks` and `gamerule.noMobsInBossfight` strings respectively.

### Expected behavior

Mod game rules are showing readable, non-technical title.

### Observed behavior

Mod game rules are showing technical title/string.

### Notes

"Edit Game Rules" screen exists only in Minecraft 1.19.4 and higher. Because of that, all versions, excluding 1.20.1, are unaffected by this bug.

### Screenshots

![gamerule stiffComboAttacks](https://github.com/Yesssssman/epicfightmod/assets/165374321/5f7f2e2c-38e0-46d7-be28-71285f45d075)
![gamerule noMobsInBossfight](https://github.com/Yesssssman/epicfightmod/assets/165374321/484210b8-9b1e-4afa-b11c-c8d6376af9c9)

**Comment by Yesssssman** [comment]
Thank you. Will be fixed in the next update.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
