### ISSUE TITLE
[Crash]: Every 1.20.1 Version past version 20.5.17 Requires NeoForge for 1.20.2 (47.2.20 for example) and not the version it's tagged as

### ISSUE THREAD

**Issue by whiteglovian** [Yesssssman/epicfightmod#1636]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

This is more of a simple labeling issue than a mod issue. However, it should probably be corrected with the CurseForge page. Sorry if this isn't the correct category
[crash-2024-05-06_17.20.46-fml.txt](https://github.com/Yesssssman/epicfightmod/files/15227770/crash-2024-05-06_17.20.46-fml.txt)

**Comment by Peterwannabe** [comment]
Im using 1.20.1 featured version in course forge but uts not working on my 1.20.1 forge.

**Comment by guivnf** [comment]
A neoforged port of the mod will arrive after we port it to 1.21, as of now, NeoForged is not recommended to be used along-side Epic Fight
