### ISSUE TITLE
[Bug]: epicfight_mobpatch does not work on the server

### ISSUE THREAD

**Issue by Kiuju79** [Yesssssman/epicfightmod#1637]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

datapack, Added ai for zombie_villager.
The single player game works, However, being in the server will cause you to be unable to enter the game.
This is the case in both ArcLight and Mohist tests.

mc 1.19.2
EpicFight-19.5.24

![log](https://github.com/Yesssssman/epicfightmod/assets/122474664/4ac5e812-6504-49fd-93eb-67ec93000b3d)
*server log

datapack

**Comment by Kiuju79** [comment]
[test_datapacks.zip](https://github.com/Yesssssman/epicfightmod/files/15246658/test_datapacks.zip)
datapack

**Comment by guivnf** [comment]
We do not support the usage of hybrid server loaders such as mohist and arclight. Closing issue as user broke the support policy.
