### ISSUE TITLE
[Suggestion]: Adding new features from Epik Fignt 1.20.x to Minecraft 1.12.2

### ISSUE THREAD

**Issue by Epik0rangutan** [Yesssssman/epicfightmod#1638]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

### Minecraft Version

1.16.5

### What's your suggestion?

So one time I was playing with my friend on some old modpack. We wanted to add epic fight, and so we did. To be honest epic fight on 1.12.2 is kinda raw, it doesn't have all of the features that 1.20.x versions include. I know that maybe it's hard to implement because of the diffrence of forge 1.20.x and 1.12.2 but I know that it is possible, and it would be great if people with old hardware could still enjoy this mod even on 1.12.2 and maybe lower.

**Comment by fzrdwa123456** [comment]
It's impossible because they've already abandoned even 1.16.5, let alone updating 1.12.2. Moreover, new features are all implemented through data packs, which are not available in 1.12.2. Currently, almost all new features can only be experienced in versions above 1.20.1. There are only bug fixes in 1.18.2 and 1.19.2, not new features.

**Comment by Epik0rangutan** [comment]
> It's impossible because they've already abandoned even 1.16.5, let alone updating 1.12.2. Moreover, new features are all implemented through data packs, which are not available in 1.12.2. Currently, almost all new features can only be experienced in versions above 1.20.1. There are only bug fixes in 1.18.2 and 1.19.2, not new features.

Well that's unfortunate.
