### ISSUE TITLE
[Bug|Crash]: I can't attack enemies on a slab in my xp farm ? What ?

### ISSUE THREAD

**Issue by duynh1134** [Yesssssman/epicfightmod#1639]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

### Minecraft Version

1.20.1

### What happened?

I can't attack enemies on a slab in my xp farm . Same with trap door or cappet.

**Comment by Yesssssman** [comment]
I guess you struck entities behind a wall or somewhere. Epic Fight doesn't allow striking the enemies behind a wall or out of the player's sight. Just recommend you use vanilla attacks.
