### ISSUE TITLE
Please compatible with Armourer's Workshop Mod.

### ISSUE THREAD

**Issue by HongMint88** [Yesssssman/epicfightmod#164]
Please compatible with Armourer's Workshop Mod. I can't see it even if you wear an item made of armourer's workshop.

**Comment by LuizRicardoHesse** [comment]
I was thinking, could have compatibility with Tinkers Construct, and Construct's Armory.

"I'm Brazilian I have difficulty with English, but this mod is very good, I had to use google translator, for this suggestion, kkkk"

**Comment by hitmanssilent** [comment]
I like this idea, please make it real :D

**Comment by GalaxyZEROX** [comment]
It also hopes to be compatible, because as long as it can be compatible with Armourer's Workshop Mod, basically the problem of the number of types of weapons and armor will be solved at once!
