### ISSUE TITLE
[Suggestion]: The compatibility between the first person and firearms

### ISSUE THREAD

**Issue by GalaxyZEROX** [Yesssssman/epicfightmod#1640]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

“Epic Compat: MrCrayfish's Gun Mod”，“MrCrayfish's Gun Mod”

### Minecraft Version

1.18.2

### What's your suggestion?

When I use "Epic Fight" and "Epic Compat: MrCrayfish's Gun Mod" and "MrCrayfish's Gun Mod", I can't use filtered animation when aiming in the first person, which leads to my inability to aim normally. Could you add a white list and a black list so that some weapons can only use epic animation in the third person instead of epic animation in the first person?
![2024-05-13_21 42 16](https://github.com/Yesssssman/epicfightmod/assets/73332842/c1cb5905-9eb2-4cc1-9893-d98d95be6441)
![2024-05-13_21 42 33](https://github.com/Yesssssman/epicfightmod/assets/73332842/12dfabf1-8f7c-42ea-9829-eb535b38a067)
![2024-05-13_21 46 07](https://github.com/Yesssssman/epicfightmod/assets/73332842/8b33974d-49f1-4ca7-99a2-aedf176db69b)
![2024-05-13_21 46 20](https://github.com/Yesssssman/epicfightmod/assets/73332842/d5249cdd-8c01-4b01-a144-72c1c7c9ccad)

**Comment by GalaxyZEROX** [comment]
In the case of aiming with the right mouse button, the first person of "MrCrayfish's Gun Mod" will automatically close the sight and enlarge the sight of the gun. In this case, there will be some incongruities with the first person of "Epic Fight".

**Comment by GalaxyZEROX** [comment]
It is suggested to add a configuration option. In mining mode, only the third person animation is displayed, and the first person is still displayed in the original version.

**Comment by Yesssssman** [comment]
You can disable First person model in latest 1.20.1 update
