### ISSUE TITLE
[Bug|Crash]: Alternate Mining/Combat Mode.

### ISSUE THREAD

**Issue by 4d4m0r** [Yesssssman/epicfightmod#1641]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

I don't know if it's necessarily a bug.

From the videos I saw on YouTube, when the switch between mining and combat mode occurs, there is a change in Steve.

In a way, my doll is always in combat mode. So when I switch to mining mode, I don't see my right hand with the tool in question (pickaxe or axe), but I mine and collect wood normally. I'm not used to it, I'd like to know if there's a way to use mining mode with vanilla minecraft vision.

**Comment by guivnf** [comment]
Closing issue as the reported "bug" is not actually bug and may be fixed by switching filteranimation: false ---> true in the mod's config file.
