### ISSUE TITLE
[Crash]:Game Crash when any dual wielding weapon breaks in offhand

### ISSUE THREAD

**Issue by ghost** [Yesssssman/epicfightmod#1642]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Every time a dual wielding weapon such as glove(s), sword etc. breaks while in offhand minecraft crashes. Same goes for other versions including the Minecraft version 1.18.2 (tested on multiple forge versions). I tested it without other mods except for epic fight mod.  
[crash-2024-05-14_19.37.39-server.txt](https://github.com/Yesssssman/epicfightmod/files/15312129/crash-2024-05-14_19.37.39-server.txt)

https://github.com/Yesssssman/epicfightmod/assets/140316764/d1e8355c-a237-4c51-80ca-7208f51863e3

**Comment by guivnf** [comment]
Thanks, issue should be solved before the next release. I'll close this and mark it as solved once we reach it

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
