### ISSUE TITLE
[Bug|Crash]: Epic Fight has failed to load correctly (and others)

### ISSUE THREAD

**Issue by Vergil1235** [Yesssssman/epicfightmod#1643]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic fight, yamato moveset, dual Greatsword, infernal gainer, miracle of mincraft, falshion moveset

### Minecraft Version

1.18.2

### What happened?

[crash-2024-05-16_16.21.27-fml.txt](https://github.com/Yesssssman/epicfightmod/files/15335911/crash-2024-05-16_16.21.27-fml.txt)
So mods just dont load and i dont know why. And btw i using epic fight datapack mod

**Comment by guivnf** [comment]
yamato moveset, dual Greatsword, infernal gainer, falchion moveset are all outdated addons, please remove them and report this issue to the correct authors.
