### ISSUE TITLE
[Bug]: Damage Attribute (in the datapacks, maybe)

### ISSUE THREAD

**Issue by qVoidreaver** [Yesssssman/epicfightmod#1645]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [x] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

  There's a problem with weapon attributes. 

 If I have a weapon of a certain material in my hands, it will modify the damage attributes of another weapon. This problem only occurs with daggers, gloves and greatswords (in the case of greatswords, this can have a SERIOUS impact when using the double greatsword mod). The problem boils down to the fact that if I take a netherite dagger and in the other hand a gold dagger (this happens with all materials, it's an example, not something specific), the damage of the gold dagger is COMPLETELY zeroed out and maybe the damage of the netherite dagger is increased by 1 (for no reason). 

 “Ah, but that could be a problem with your data package, modify the damage using ‘two_hands’”... no, I've tested it, it's not. 

 This is very bad because it forces me to use another mod and configure it so that when daggers or swords of different materials are wielded, the damage is completely zeroed out, because at the same time as it can increase the damage, it can also decrease it and that... well, it's a very annoying bug.

Apparently the bug/feature happens when I modify the weapon's damage as shown in the video. The damage of the glove was 3 and the damage of my punch was 1, so when I changed the damage of the glove to 1.5, the damage of the punch was canceled.

video: https://www.youtube.com/watch?v=9Jpd-dGRosE

 I looked to see if anyone had already reported this, but I couldn't find it, so if you have, let me know plss
 
 NOTE: The video shows various mods that I'm using, but I can assure you that without mods this bug also occurs, I had already tested it a long time ago in previous versions and so far it hasn't been resolved... I think

**Comment by guivnf** [comment]
Issue is known and will be fixed in an upcoming release of the mod.
