### ISSUE TITLE
[Bug|Crash]: The slash of Satsujin can cause a CRASH

### ISSUE THREAD

**Issue by moranchu** [Yesssssman/epicfightmod#1646]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

When the slash attack of satsujin that can be stacked triggers on the target, if you happen to die at that moment, it will cause the game to crash. It is speculated from the crash report that this might be due to a null issue caused by the loss of the "damagesource" player at this time. This crash occurs both in single-player mode and on servers, and it can lead to the server crashing as well.

**Comment by guivnf** [comment]
Closing issue as user broke the support policy. Reffered weapon type is not from Epic Fight.
