### ISSUE TITLE
[Bug]: Armor partial rendering errors

### ISSUE THREAD

**Issue by JEDIGD** [Yesssssman/epicfightmod#1648]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Protection Pixel

### Minecraft Version

1.20.1

### What happened?

![94276869063186f14129b603fa1cedcc1865707619](https://github.com/Yesssssman/epicfightmod/assets/157476350/f28a517a-0582-44a1-b64c-ade588269638)
render mistake
mod files,armor files here
[pp.zip](https://github.com/Yesssssman/epicfightmod/files/15465457/pp.zip)

**Comment by guivnf** [comment]
Is this mod made in MCreator? Is the armor animated or made in geckolib ? And have you tried patching it in blender like shown in the referred wiki articles ?:

https://epicfight-docs.readthedocs.io/Guides/page3/
https://epicfight-docs.readthedocs.io/Armor/3Darmor_page1/
https://epicfight-docs.readthedocs.io/Armor/3Darmor_page2/

**Comment by JEDIGD** [comment]
yes，no, no. Even if I haven't done this before, the compatibility with other parts is still very good, which makes me doubt if there is a bug here. If it's not a bug, then this problem will be solved.tks.

**Comment by guivnf** [comment]
Are you the mod author?

**Comment by JEDIGD** [comment]
Yeah

**Comment by guivnf** [comment]
> Yeah

K, if you want to, join our discord server some time later and you can then remind me so i fix this issue of the armor on your mod. It'll take some time before i can find some spare time to properly fix your armor model but it shouldn't take that long

**Comment by JEDIGD** [comment]
Tks，I would be appreciate for this
