### ISSUE TITLE
[Suggestion]: Add a config option to turn on/off vanilla nether star dropping

### ISSUE THREAD

**Issue by Kouchya** [Yesssssman/epicfightmod#1651]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

The wither killed by player leaves a DroppedNetherStar entity where it dies instead of dropping a nether star item. This is cool in some ways, but it makes automatic wither farming impossible - the wither just won't drop any stars when auto-killed. It would be nice if a serverside config option is provided to toggle the vanilla-style nether star dropping.

**Comment by Yesssssman** [comment]
Added in 20.9.2
