### ISSUE TITLE
[Bug|Crash]: error

### ISSUE THREAD

**Issue by lengzu** [Yesssssman/epicfightmod#1655]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

[crash-2024-06-03_13.55.06-server.txt](https://github.com/user-attachments/files/15529439/crash-2024-06-03_13.55.06-server.txt)

**Comment by guivnf** [comment]
Closing issue as user did not provide any information on the reffered issue and it seems that the aquired version of the mod has been tempered with.
