### ISSUE TITLE
[Bug|Crash]: Can't find attribute epicfight:offhand_max_strikes

### ISSUE THREAD

**Issue by Ak1m0** [Yesssssman/epicfightmod#1656]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/mine-mine-no-mi

### Minecraft Version

1.16.5

### What happened?

Hello, I'm trying to make animated attacks for the Mine Mine no Mi mod, I've read the guides and did everything according to them. The situation is as follows, I add animated attacks to the mob, for swords, axes (one-handed, two-handed) everything works fine, and when I try to change the unarmed attack from ''epicfight:zombie/attack1'' to ''epicfight:biped/combat/fist_auto1'', everything works until the moment of the attack by this mob, and the crash report says Can't find attribute epicfight:offhand_max_strikes.
What should I do, please tell me?
[crash-2024-06-03_09.50.30-server.txt](https://github.com/user-attachments/files/15536153/crash-2024-06-03_09.50.30-server.txt)

**Comment by Ak1m0** [comment]
I'll also show you the files where I change this:
1) Zombie-like attack(works)
[brawler_trainer.json](https://github.com/user-attachments/files/15536330/brawler_trainer.json)
2) Attack like a player (does not work)
[brawler_trainer(1).json](https://github.com/user-attachments/files/15536331/brawler_trainer.1.json)

**Comment by guivnf** [comment]
1.16.5 is no longer supported. Closing issue
