### ISSUE TITLE
[Bug|Crash]: Weird weapons collision box

### ISSUE THREAD

**Issue by KuuroNull** [Yesssssman/epicfightmod#1657]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

The collision box for the first attack of greatsword didn't seem to hit anything in the front but do damage thing beside and in the back of the user. Sprint attack, unless the target have a large hitbox, like big slime and ravenger, it's still not guarantee to hit.
 A similar issue is happen to the first attack of the spear, tho you can still hit thing in the front, it's seem like you have to be very close to the target.

**Comment by guivnf** [comment]
Remove epic fight animations resourcepack. It's an old resourcepack using old animation data files and it'll break the mod if used.
