### ISSUE TITLE
[Bug|Crash]:  Crash upon clicking create new world

### ISSUE THREAD

**Issue by JustRad123** [Yesssssman/epicfightmod#1659]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

This issue is very similar : https://github.com/Yesssssman/epicfightmod/issues/1487 however its a bit old and even tho says its fixed its back.
Im using ver 20.7.4 of the mod and forge version 47.3.1

Essentially it crashes upon world creation with some missing/unknown weapon anims but also cries abt mouse handler or smt

[Log.txt](https://github.com/user-attachments/files/15744910/Log.txt)   log (im using MultiMC)

[Crash.txt](https://github.com/user-attachments/files/15744914/Crash.txt) Crash report just in case

**Comment by Negark2** [comment]
This exact same issue is also present in the latest version of 1.19.2. More so, my crash is talking about "Katana" not being able to be identified
[crash-2024-06-10_02.29.53-client.txt](https://github.com/user-attachments/files/15755256/crash-2024-06-10_02.29.53-client.txt)

**Comment by Yesssssman** [comment]
The reason for the first crash is you haven't installed WoM tho the data pack you installed requires it.

The reason for the second crash is your datapack depends on the old EpicFight version. So I recommend downgrading EpicFight or you can manually fix the the type names in your datapack like this.

```
{
	"attributes":
	{
		...
	},
	"type":"epicfight:katana"
}
```
to
```
{
	"attributes":
	{
		...
	},
	"type":"epicfight:uchigatana"
}
```
