### ISSUE TITLE
[Bug|Crash]: 1.20.1 Crashing on World Creation [Culprit Found]

### ISSUE THREAD

**Issue by P4YN-Ki** [Yesssssman/epicfightmod#1661]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/roughly-enough-professions-rep & https://www.curseforge.com/minecraft/mc-mods/roughly-enough-resources

### Minecraft Version

1.20.1

### What happened?

Starting the game and creating a new world with either of the two mods enable will result in the player being kicked out of the world at creation with an error about being removed from the World. There is no crash log, just a latest.log which I will provide a link too here: https://pastebin.com/UibRtMpC or I will add it here for download. Removing both these mods will allow the game to load as normal. I am using the latest version of Epic Fight and it's corrosponding verion of forge, currently EF=20.7.3 & Forge=47.2.20. The versions of REI Professions & REI Resources are REI_Pro=1.20.1-2.0.2 & REI_RE=1.20(1)-2.9.0
[latest.log](https://github.com/user-attachments/files/15794181/latest.log)

I'm aware this might not get fixed, but there may also be others who have this issue and hopefully they see this.

**Comment by Yesssssman** [comment]
Fixed in 20.8.10
