### ISSUE TITLE
[Bug|Crash]: Entities in a custom entity datapack don't stun other targets with melee attacks

### ISSUE THREAD

**Issue by aVindicator** [Yesssssman/epicfightmod#1662]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

The entities can get stunned by other Epic Fight attacks, but they can't stun other Epic Fight mobs with their melee attacks.
Example: https://medal.tv/games/minecraft/clips/i3cfsCBhJn5JQ4cZE/d1337PiU7wID?invite=cr-MSxxRHcsMjMwMTM2MTMs

I don't think this is supposed to happen, I copy-pasted the examples from the custom entity datapack guide aswell, and they still couldn't stun. I also attached my edited json file - 
[summoned_zombie.json](https://github.com/user-attachments/files/15796443/summoned_zombie.json)

**Comment by Yesssssman** [comment]
What is Summoned zombie? This problem is not from datapack but it seems like your entity doesn't have an attribute for stun or the player has a resistance to it.
