### ISSUE TITLE
[Bug|Crash]: epic fight+addons are crashing and I do not know why

### ISSUE THREAD

**Issue by deadend06** [Yesssssman/epicfightmod#1666]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

[crash-2024-06-19_17.33.35-fml.txt](https://github.com/user-attachments/files/15906114/crash-2024-06-19_17.33.35-fml.txt)

**Comment by Yesssssman** [comment]
Infernal Gainer requires Epic Fight version less than 20.6.4
