### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by KB2285** [Yesssssman/epicfightmod#1667]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

When I customized weapon animation,I found all mob animations in biped animation folder could not added into combos.Animations would be stopped if the first mobs animation finished.But bipeds can play mob animations freely with Indestructible.

**Comment by Yesssssman** [comment]
Please send you datapack.

**Comment by KB2285** [comment]
I am sorry because I had made compromiseshad and placed all the mob animation at the end of the combos,so my databack may not offer help.The folder named wa has my customized weapons.
[epicfight.zip](https://github.com/user-attachments/files/16507699/epicfight.zip)

**Comment by Yesssssman** [comment]
Well could you narrow down example weapon type and entity? I need to install all the mods to run your datapack but I don't have a time to do that.

**Comment by KB2285** [comment]
I am sorry and it is my mistake.Now I only left the hunter axe and hunter entity in the vampirism mod as examples.
[epicfight2.zip](https://github.com/user-attachments/files/16508067/epicfight2.zip)

**Comment by Yesssssman** [comment]
Please see if the issue has solved in 20.8.6

**Comment by KB2285** [comment]
It worked normally!Thank you very much!!!❤❤❤
