### ISSUE TITLE
Unable to use Eye of the End[Bug|Crash]: 

### ISSUE THREAD

**Issue by OAO87** [Yesssssman/epicfightmod#1670]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

I can't use the Eye of the End properly in the game

**Comment by Yesssssman** [comment]
Please provide more details to reproduce the issue. I didn't get any problems when I tested on my side.

https://github.com/Yesssssman/epicfightmod/assets/79469058/2aefb88f-d2f6-422a-943f-1ba43cca26bb

**Comment by OAO87** [comment]
I'm very sorry. It may be due to other modules that I can't use it.
