### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by MWArctic** [Yesssssman/epicfightmod#1671]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

[latest.log](https://github.com/user-attachments/files/15943317/latest.log)

I am getting an odd crash consistently. I am setting up a modpack and it works perfectly fine on single player. However, when I start my server and try to connect as the client, I get a client crash with the error at the bottom of the log. 

This crash did not occur with an install of only Epic Fight, so I'm currently searching for a possible mod incompatibility. I've also done fresh server installs, including world and player data wipe, with no luck.

**Comment by Yesssssman** [comment]
This crash has the same issue as #1624.

**Comment by Yesssssman** [comment]
Fixed in 20.8.7
