### ISSUE TITLE
[Bug|Crash]: Ender Blaster

### ISSUE THREAD

**Issue by AvocadoLouko** [Yesssssman/epicfightmod#1673]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.19.2

### What happened?

My friend got the ender blasters and when on use or jumping w/ then on hand he got disconnected

**Comment by Yesssssman** [comment]
Ender Blaster is from Weapons of Miracles. Please report this to their issue tracker.
https://github.com/Reascer/WeaponsOfMinecraft/issues
