### ISSUE TITLE
[Bug|Crash]: Looking up while performing "Demolition Leap" causes visual extreme player's head Y rotation.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1674]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

Performing "Demolition Leap" skill while looking up causes visual extreme player's head Y rotation change.

### Steps to reproduce

1. Start Minecraft 1.20.1 with the latest version of Epic Fight and with recommended Forge version;
2. Press "Singleplayer", then select or create a new world with cheats enabled;
3. Make sure that you don't have any skills. If there are any, then execute skill clearing command: `/epicfight skill clear @s`;
4. Learn "Demolition Leap" using a skill book or using following command: `/epicfight skill add @s mover epicfight:demolition_leap`;
5. Change your camera perspective to third person front view and perform learned skill.

### Expected behavior

Player's head is not going through body.

### Observed behavior

Player's head is going through body.

### Video

https://github.com/Yesssssman/epicfightmod/assets/165374321/0c6c8168-bc6c-4b7c-b2a8-3b8640ab1795

#### Tested Minecraft versions

- 1.20.1 (Epic Fight 20.7.4, Singleplayer & Multiplayer [LAN])
- 1.19.2 (Epic Fight 19.5.24, Singleplayer & Multiplayer [Dedicated Forge server])

**Comment by Yesssssman** [comment]
Thanks for reporting. This will be fixed in the next update.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
