### ISSUE TITLE
[Bug|Crash]: Ender Dragon's breath causes damage to the player in creative game mode.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1675]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

Ender Dragon's breath causes damage to the player in creative game mode.

### Steps to reproduce

In order to reproduce this bug, you need two instances of Minecraft running with **different nicknames.** If you don't have the ability to launch the game using offline mode or using two online accounts, then you can [use this mod.](https://modrinth.com/mod/in-game-account-switcher)

**Make sure, that your instances are running from the different folders. If not, then this could cause your settings and your world(s) to corrupt.**

1. Start two instances of Minecraft 1.20.1 with the latest version of Epic Fight and with recommended Forge version;
2. On the first instance press "Singleplayer", then select or create a new world with cheats enabled;
3. After world load, bring "Game Menu" screen, press "Open to LAN", enable cheats and click "Start LAN world";
4. Bring the second instance to the world of the first one;
5. Make sure, that first instance is in creative mode and the second one is in survival or adventure;
6. Also make sure, that characters are staying close to each other;
7. Give high level resistance effect to the second instance in order to avoid manual respawning: `/effect give @s resistance infinite 127` or `/effect give @s resistance 3600 127` for older versions;
8. Summon the Ender Dragon using `/summon ender_dragon` command. Entity should fly towards the second player;
9. Select your first instance and fly right in the Ender Dragon's breath. If the player takes damage while in creative mode, then the bug is successfully recreated.

### Expected behavior

Player in creative mode is **not** taking damage from the Ender Dragon's breath.

### Observed behavior

Player in creative mode is taking damage from the Ender Dragon's breath.

### Video

https://github.com/Yesssssman/epicfightmod/assets/165374321/395f3e19-e9ac-4d4e-b815-2c38026dc046

**Comment by Yesssssman** [comment]
Thanks for reporting. This will be fixed in the next update.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
