### ISSUE TITLE
[Bug]: "Demolition Leap" skill fails if there's a wall behind.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1676]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

Trying to perform "Demolition Leap" while touching the wall behind causes the player to fly up.

### Steps to reproduce

1. Start Minecraft 1.20.1 with the latest version of Epic Fight and with recommended Forge version;
2. Open "Singleplayer", then select or create a new world;
3. Build a wall using any solid blocks or find a ready one;
4. Make sure that you don't have any skills. If there are any, then clear them: `/epicfight skill clear @s`;
5. Learn "Demolition Leap" using a skill book or by performing this command: `/epicfight skill add @s mover epicfight:demolition_leap`;
6. Make your player to touch the wall behind;
7. Try to perform "Demolition Leap". If your character doesn't jump forwards, then the bug is successfully recreated.

### Expected behavior

Player should perform "Demolition Leap" regardless of blocks behind.

### Observed behavior

Player jumps high.

### Video

https://github.com/Yesssssman/epicfightmod/assets/165374321/15f2b042-8869-4845-a3a4-301ed8317ef6

**Comment by Yesssssman** [comment]
It will be fixed in the new version. Thank you for reporting!

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
