### ISSUE TITLE
[Bug]: Ender Dragon's breath ignores respawn immunity.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1677]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

Ender Dragon's breath ignores [respawn immunity.](https://minecraft.wiki/w/Player#Respawn_immunity)

### Steps to reproduce

**Recreating this bug might cause your world to softlock. Proceed with caution.**

1. Start Minecraft 1.20.1 with the latest version of Epic Fight and with recommended Forge version;
2. Open "Singleplayer", then select or create a new world;
3. Switch your gamemode to survival or adventure;
4. Set your spawnpoint. `/spawnpoint @s`;
5. Summon Ender Dragon in Overworld. `/summon ender_dragon`;
6. If after death your character is taking damage during three-second respawn immunity, then the bug is successfully recreated.

### Expected behavior

Player **doesn't** take damage during respawn immunity.

### Observed behavior

Player does take damage during respawn immunity.

### Video

Provided video shows different bug setup for clarity.

https://github.com/Yesssssman/epicfightmod/assets/165374321/e656f392-9725-438b-9a44-75c4b4881f46

**Comment by Yesssssman** [comment]
Same cause as #1675

**Comment by Raccffy** [comment]
> Same cause as #1675

Closing the issue as duplicate.
