### ISSUE TITLE
[Bug]: More missing translation strings!

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1678]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

This issue is continuation of #1632. There's more strings in the mod that hasn't been translated yet.

### List of untranslated strings.

- This list is not exaustive. Some strings might not be covered here;
- If you're going to reproduce anything below, make sure that you're using "English (US)" game locale.

#### Displayed in subtitles

Subtitles can be enabled via `Game Menu --> Options... --> Music & Sounds... --> Show Subtitles: ON`.

- `entity.weapon.whoosh`. Player performs punch;
- `entity.weapon.whoosh_small`. Player swings small or lightweight weapons;
- `entity.weapon.whoosh_hard`. Player swings big or weighty weapons;
- `entity.weapon.whoosh_sharp`. Player used "Battojutsu" skill;
- `entity.weapon.sword_in`. Player hides blades in an Uchigatana or performs "Battojutsu" skill;
- `entity.hit.blunt`. Player successfully dealts damage to an other entity;
- `entity.hit.blade`. Player successfully dealts damage to an other entity using a weapon;
- `entity.hit.eviscerate`. Player successfully used dagger's eviscerate skill;
- `entity.enderdragon.dragon_breath`. Ender Dragon's breath;
- `entity.enderdragon.dragon_breath_finale`. Same as previous;
- `sfx.nether_star_glitter`. Nether Star shine sound effect after beating Wither;
- `sfx.ground_slam_small`. Player used greatsword while sprinting to slam the ground;
- `sfx.ground_slam`. Player used "Meteor Slam" skill to slam the ground;
- `skill.roll`. Roll sound effect;
- `sfx.entity_move`. Skill entity move;
- `sfx.no_sound`.

#### Effects

- `effect.epicfight.instability`. "Instability" effect. (For example, executing `/effect give @s epicfight:instability` will display "Applied effect *effect.epicfight.instability* to *PlayerName*")

#### Commands

- `epicfight.skillNotFound`. If you try to add or remove a non-existent skill, then this message will be displayed (For example, `/epicfight skill add @p dodge epicfight:some_insane_stuff`).

**Comment by Yesssssman** [comment]
Thank you so much for your attribution.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
