### ISSUE TITLE
[Bug]: Toggle R key not working 

### ISSUE THREAD

**Issue by CoffeeADIK** [Yesssssman/epicfightmod#1679]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

The toggle R key is not working and im stuck in combat mode everytime I have checked the other versions and the mod seems to be working fine except for 1.20.1

**Comment by OneWorldStudio** [comment]
just change the buttons, you have a conflict of clicks

**Comment by Yesssssman** [comment]
Could you provide information about when it happens? It doesn't happen in a normal environment. Also, check key conflicts just as the answer above.

**Comment by xShadowTR** [comment]
> Could you provide information about when it happens? It doesn't happen in a normal environment. Also, check key conflicts just as the answer above.

I have the same issue too I dont know if its a update feature I cant use vanilla animations when I press R if its a feature please remove or make a config about it, it brokes my other mods

**Comment by Yesssssman** [comment]
> I have the same issue too I dont know if its a update feature I cant use vanilla animations when I press R if its a feature please remove or make a config about it, it brokes my other mods

I can't fix anything if you only say like "I have the same problem". Please provide me detailed information like steps to reproduce the bug you have or the name of the mod causing the issue.

**Comment by xShadowTR** [comment]
Sorry it was just epic fight graphics were on

23 Tem 2024 Sal 10:34 tarihinde Yesman ***@***.***> şunu
yazdı:
