### ISSUE TITLE
[Bug|Crash]: Error load server

### ISSUE THREAD

**Issue by OneWorldStudio** [Yesssssman/epicfightmod#1680]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Hello, your mod does not work on the server, namely the Build version from the GitHub site, I have compiled the epicfight-20 versions.8.1 [0,1,2] all these versions work on the server, but they stop working on the client

https://mclo.gs/

I know that these are only test versions, but I would like to test the new introduction on the server and help you with the tests)))

**Comment by Yesssssman** [comment]
the link is invalid.

**Comment by OneWorldStudio** [comment]
> the link is invalid.
sorry https://mclo.gs/UjiLhkz

**Comment by OneWorldStudio** [comment]
?

**Comment by Yesssssman** [comment]
Thank you! This will be fixed in the next update.

**Comment by OneWorldStudio** [comment]
> Thank you! This will be fixed in the next update.

Thank so much

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
