### ISSUE TITLE
[Bug]: Using /attribute reveals attributes' name issues.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1681]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

When using `/attribute` command, some of the attribute names from the mod are either untranslated or display unassigned variables or don't comply with Minecraft's attribute name style.

### Steps to reproduce

1. Start Minecraft 1.20.1 with the latest version of Epic Fight and with recommended Forge version;
2. Open "Singleplayer", then select or create a new world;
3. Execute `/attribute @s epicfight:[name_of_affected_attribute] get`. Where "name_of_affected_attribute" is the name of attribute in one of the three lists below.

### List of broken attribute names.

- `epicfight:execution_resistance`: "attribute.name.epicfight.execution_resistance";
- `epicfight:offhand_armor_negation`: "attribute.name.epicfight.offhand_armor_negation";
- `epicfight:offhand_impact`: "attribute.name.epicfight.offhand_impact";
- `epicfight:offhand_max_strikes`: "attribute.name.epicfight.offhand_max_strikes".

### List of variable attribute names.

- `epicfight:armor_negation`: "%s Armor Negation" instead of "Armor Negation";
- `epicfight:impact`: "%s Impact" instead of "Impact";
- `epicfight:max_strikes`: "Hit %s Enemies per Swing". This can be rephrased to "Maximum amount of affected enemies per swing". Pretty long, I know.

### List of attributes with non-compliant style.

- `epicfight:offhand_attack_speed`: "offhand attack speed". This should be "**O**ffhand **A**ttack **S**peed".

### Screenshot

![Epic Fight's attributes displayed.](https://github.com/Yesssssman/epicfightmod/assets/165374321/5cee040a-b7b3-49df-9457-a1d95087bc2c)

**Comment by Yesssssman** [comment]
It will be fixed in the next update. Thanks!

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
