### ISSUE TITLE
[Bug]: Blooming effect strings issues.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1682]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

Blooming effect is using Minecraft namespace and has untranslated string for tipped arrow.

### Steps to reproduce

1. Start Minecraft 1.20.1 with the latest version of Epic Fight and with recommended Forge version;
2. Open "Singleplayer", then select or create a new world;
3. Open creative inventory, go to "Combat" tab, scroll down and hover your cursor to the last tipped arrow, colored red. This should reveal untranslated string with Minecraft namespace.

### Notes

All mod-related stuff **should** be in mod namespace to avoid confusion.

### Screenshot

![Blooming tipped arrow is missing translation string.](https://github.com/Yesssssman/epicfightmod/assets/165374321/98f37cc3-bb9c-4135-8986-1f3856471b1f)

**Comment by Yesssssman** [comment]
Blooming is a dummy effect for now. I'm going to disable it until I add an effect for it. Thanks for reporting.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
