### ISSUE TITLE
[Bug]: Player can hit entity behind using fists if they're too close.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1685]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

Player can hit entity behind using fists if they're too close, but not so close to hit with vanilla attack.

### Steps to reproduce

In order to reproduce this bug, you need two instances of Minecraft running with different nicknames. If you don't have the ability to launch the game using offline mode or using two online accounts, then you can [use this mod.](https://modrinth.com/mod/in-game-account-switcher)

**Make sure, that your instances are running from the different folders. If not, then this could cause your settings and your world(s) to corrupt.**

1. Start two instances of Minecraft 1.20.1 with the latest version of Epic Fight and with recommended Forge version;
2. On the first instance press "Singleplayer", then select or create a new world with cheats enabled;
3. After world load, bring "Game Menu" screen, press "Open to LAN", enable cheats and click "Start LAN world";
4. Bring the second instance to the world of the first one;
5. Make sure, that the second player is in survival or adventure game mode;
6. Create a team using `/team add [Team Name]` command, where "Team Name" is any valid team name;
7. Disable team collision by executing `/team modify [Team Name] collisionRule never`;
8. Add all instances to your new team: `/team join @a`;
9. Select your first instance, stand in front of the second one and move backwards slowly until you reach the player behind;
10. Switch your fight mode to "Mining" by pressing hotkey or by using `/epicfight mode mining` and make sure, that you're not hitting the second instance with vanilla attacks;
11. Switch back to "Battle" fight mode (hotkey or `/epicfight mode battle`) and try to perform a punch. If player behind takes damage, then the bug was successfully recreated.

### Expected behavior

Player behind does not take damage while other one is performing a punch in front of him.

### Observed behavior

Player behind takes damage.

### Video

https://github.com/Yesssssman/epicfightmod/assets/165374321/70a9e889-9fc6-4711-b95d-2e1fd4681c3c

**Comment by Yesssssman** [comment]
Technically this issue is impossible to fix completely, but I pushed back the attack timing of the fist attack animations one frame later so it relieved. Thank you for reporting.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
