### ISSUE TITLE
Armour trims issue

### ISSUE THREAD

**Issue by EiikUu** [Yesssssman/epicfightmod#1689]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Trimmed armour looks weird with the epic fight animation

![IMG-20240703-WA0000](https://github.com/Yesssssman/epicfightmod/assets/166088440/b684f024-95f8-4c55-83a0-dce8a7262e99)
![IMG-20240703-WA0001](https://github.com/Yesssssman/epicfightmod/assets/166088440/d8cde394-90fb-4f52-9312-ede2b272d00b)

**Comment by guivnf** [comment]
> ### Have you checked if a similar issue is already reported by someone else?
> 
> - [X] I checked there are no similar issues have been reported.
> 
> ### Have you read the support policy?
> 
> - [X] I read it and I accept the policy.
> 
> ### Are you using the latest Epic Fight and recommended Forge version?
> 
> - [X] I checked I'm using latest Epic Fight and recommended Forge version.
> 
> ### Is this issue related to mod incompatibility?
> 
> - [ ] This is a mod compatibility issue and I'm aware of the problem.
> 
> ### The mod
> 
> _No response_
> 
> ### Minecraft Version
> 
> 1.20.1
> 
> ### What happened?
> 
> Trimmed armour looks weird with the epic fight animation
> 
> 
> 
> ![IMG-20240703-WA0000](https://github.com/Yesssssman/epicfightmod/assets/166088440/b684f024-95f8-4c55-83a0-dce8a7262e99)
> 
> ![IMG-20240703-WA0001](https://github.com/Yesssssman/epicfightmod/assets/166088440/d8cde394-90fb-4f52-9312-ede2b272d00b)
> 
> 

What trim is that ?

**Comment by EiikUu** [comment]
Coast trim, I'm not sure but I believe every trim has this issue

**Comment by Yesssssman** [comment]
Fixed in development environment. no worries

**Comment by EiikUu** [comment]
Thank you, is it available on 1.20.1?

**Comment by Yesssssman** [comment]
Sadly we're on beta testing now. I'll let you know if we officially upload the new version in Curseforge.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
