### ISSUE TITLE
[Crash]: Epic Fight Crash While in game

### ISSUE THREAD

**Issue by Ohminecraft** [Yesssssman/epicfightmod#1690]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

I have a modpack I created, but when I create a new world, after 10 - 30 minutes of playing, it crashes, then when I enter the world again, it crashes again.

Here is crash report

https://pastebin.com/xzaxLwFP

**Comment by Yesssssman** [comment]
Same crash as #1688

**Comment by Yesssssman** [comment]
This issue will be fixed in the next release of Epic Fight Battle System (Maybe 1.2.4)

**Comment by Yesssssman** [comment]
I checked this issue no longer occurs in the latest epic fight battle styles.
