### ISSUE TITLE
[Bug|Crash]: Server not booting with epic fight installed

### ISSUE THREAD

**Issue by HypnoticChris** [Yesssssman/epicfightmod#1692]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

I am currently in the middle of developing a RPG modpack that utilizes Epic Fight in it. All of my testing has been in singleplayer prior to today, and I have had no issues with Epic Fight. However, upon my friend running a server on their computer to test out something in a multiplayer context, the server would not boot if Epic Fight was in the server mods. We also tested without using any Epic Fight addons as well. The issue only seems to be a server issue, as booting the same modpack on a client doesn't have any issues. We have checked that they are running the same forge version for the server as the client, and checked that it is the same epic fight version as the client.
latest.log : https://pastebin.com/M5NYZ26G
mods list (for the server) : 
adorabuild-structures-2.7.0-forge-1.20.1.jar
AdvancementPlaques-1.20.1-forge-1.5.1.jar
aeroblender-1.20.1-1.0.1-neoforge.jar
aether-1.20.1-1.4.2-neoforge.jar
aether-redux-2.0.16c-1.20.1-neoforge.jar
aether_delight_1.0.0_forge_1.20.1.jar
alembic-1.0.9.jar
alexscaves-1.1.4.jar
alexsmobs-1.22.8.jar
almostunified-forge-1.20.1-0.9.4.jar
AmbientEnvironment-forge-1.20.1-11.0.0.1.jar
Apotheosis-1.20.1-7.4.0.jar
ApotheoticAdditionsV2.0.2.jar
ApothicAttributes-1.20.1-1.3.5.jar
Aquaculture-1.20.1-2.5.1.jar
aquamirae-6.API15.jar
architectury-9.2.14-forge.jar
ars_creo-1.20.1-4.1.0.jar
ars_nouveau-1.20.1-4.12.1-all.jar
art_of_forging-1.8.1-1.20.1.jar
AttributeFix-Forge-1.20.1-21.0.4.jar
azurelib-neo-1.20.1-2.0.30.jar
badpackets-forge-0.4.3.jar
balm-forge-1.20.1-7.3.6-all.jar
better fishing.jar
bettervillage-forge-1.20.1-3.2.0.jar
blockui-1.20.1-1.0.156-RELEASE.jar
bloodmagic-1.20.1-3.3.3-45.jar
blossom.jar
blueprint-1.20.1-7.1.0.jar
bobby-1.20.1_v5.0.1.jar
BOMD-Forge-1.20.1-1.1.1.jar
Bookshelf-Forge-1.20.1-20.2.13.jar
born_in_chaos_[Forge]1.20.1_1.3.1.jar
Bountiful-6.0.3+1.20.1-forge.jar
bygonenether-1.3.2-1.20.x.jar
caelus-forge-3.2.0+1.20.1.jar
call_of_yucatan-1.0.10-forge-1.20.1.jar
Cataclysmic Illagers-1.0.0.jar
celestisynth-1.20.1-1.2.2.jar
CerbonsApi-Forge-1.20.1-1.0.0.jar
citadel-2.5.4-1.20.1.jar
cloth-config-11.1.118-forge.jar
Clumps-forge-1.20.1-12.0.0.4.jar
ColossalChests-1.20.1-1.8.4.jar
common-networking-forge-1.0.5-1.20.1.jar
Controlling-forge-1.20.1-12.0.2.jar
coroutil-forge-1.20.1-1.3.7.jar
corpse-forge-1.20.1-1.0.12.jar
cosmeticarmorreworked-1.20.1-v1a.jar
CraftTweaker-forge-1.20.1-14.0.40.jar
CraterLib-Forge-1.20-2.0.0.jar
create-1.20.1-0.5.1.f.jar
create-stuff-additions1.20.1_v2.0.4a.jar
createaddition-1.20.1-1.2.4c.jar
cupboard-1.20.1-2.7.jar
curios-forge-5.9.1+1.20.1.jar
curseofpandora-2.4.15.jar
CyclopsCore-1.20.1-1.19.2.jar
DarkPaintings-Forge-1.20.1-17.0.4.jar
deeperdarker-forge-1.20.1-1.2.1.jar
delightfulburgers-1.20.1.jar
domum_ornamentum-1.20.1-1.0.186-RELEASE-universal.jar
drippyloadingscreen_forge_3.0.1_MC_1.20.1.jar
dummmmmmy-1.20-1.8.17b.jar
Dungeon Crawl-1.20.1-2.3.14.jar
DungeonsArise-1.20.x-2.1.58-release.jar
dungeonsweaponry-1.16.2-1.20.1.jar
dungeons_enhanced-1.20.1-5.2.2.jar
dungeons_plus-1.20.1-1.5.0.jar
eeeabsmobs-1.20.1-0.92.jar
EFMCompat 2.0.jar.DISABLED
eidolon_repraised-1.20.1-0.3.8.11.jar
embersrekindled-1.20.1-1.3.7.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.16.jar
endersdelight-1.20.1-1.0.3.jar
endrem_forge-5.2.3-R-1.20.X.jar
EnigmaticLegacy-2.29.0.jar
entityculling-forge-1.6.6-mc1.20.1.jar
entityjs-0.2.1-1.20.1.jar
EpicFight-20.7.4.jar
epicpaladins-0.1.1-1.20.1-forge.jar
epicsamurai-0.0.44-1.20.1-neo.jar
ExplorersCompass-1.20.1-1.3.3-forge.jar
fabledweaponry-1.20.1-1.0.7.5.jar
fancymenu_forge_3.2.3_MC_1.20.1.jar
fantasyfurniture-1.20.1-9.0.0.jar
FarmersDelight-1.20.1-1.2.4.jar
FastFurnace-1.20.1-8.0.2.jar
Fastload-Reforged-mc1.20.1-3.4.0.jar
ferritecore-6.0.1-forge.jar
Fishingreal-1.20.1-1.7.2.jar
forbidden_arcanus-1.20.1-2.2.6.jar
FpsReducer2-forge-1.20-2.5.jar
framework-forge-1.20.1-0.7.6.jar
ftb-library-forge-2001.2.2.jar
ftb-quests-forge-2001.4.6.jar
ftb-teams-forge-2001.3.0.jar
fusion-1.1.1-forge-mc1.20.1.jar
Galosphere-1.20.1-1.4.1-Forge.jar
GameStages-Forge-1.20.1-15.0.1.jar
geckolib-forge-1.20.1-4.4.7.jar
goblintraders-forge-1.20.1-1.9.3.jar
Icarus-NeoForge-2.9.1.jar
iceandfire-2.1.13-1.20.1-beta-4.jar
Iceberg-1.20.1-forge-1.1.21.jar
ice_and_fire_spellbooks-2.2.0-1.20.1.jar
idas_forge-1.10.0+1.20.1.jar
ImmersiveEngineering-1.20.1-10.1.0-171.jar
impactful-20.6.7.jar.DISABLED
Incendium_1.20.x_v5.3.5.jar
InsaneLib-1.13.5-mc1.20.1.jar
integrated_api-1.5.1+1.20.1-forge.jar
integrated_stronghold-1.1.1+1.20.1-forge.jar
ironchests-5.0.2-forge.jar
ironfurnaces-1.20.1-4.1.6.jar
irons_spellbooks-1.20.1-3.2.1.jar
irons_spells_js-1.20.1-2.1.2-release.jar
ItemStages-Forge-1.20.1-8.0.3.jar
Jade-1.20.1-forge-11.9.4.jar
jei-1.20.1-forge-15.3.0.8.jar
JustEnoughResources-1.20.1-1.4.0.247.jar
justzoom_forge_1.0.2_MC_1.20.1.jar
Kambrik-6.1.1+1.20.1-forge.jar
konkrete_forge_1.8.0_MC_1.20-1.20.1.jar
kotlinforforge-4.11.0-all.jar
kubejs-forge-2001.6.5-build.14.jar
l2artifacts-2.4.24.jar
l2complements-2.4.39.jar
l2hostility-2.4.27.jar
l2library-2.4.28.jar
l2weaponry-2.4.30.jar
libraryferret-forge-1.20.1-4.0.0.jar
limitedchunks-1.20.1-4.1.jar
lionfishapi-1.9.jar
lios_overhauled_villages-1.18.2-1.21-v0.0.4.jar
lmft-1.0.4+1.20.1-forge.jar
lootintegrations-1.20.1-3.7.jar
lootr-forge-1.20-0.7.34.86.jar
L_Enders_Cataclysm-1.99.6-1.20.1.jar
MaxHealthFix-Forge-1.20.1-12.0.3.jar
melody_forge_1.0.3_MC_1.20.1-1.20.4.jar
minecolonies-1.20.1-1.1.601-BETA.jar
miners_delight-1.20.1-1.2.3.jar
mixininheaven-mc1.17.1-1.20-v0.0.1-hotfix.jar
mobgamestages-1.20.1-0.1.jar
modernfix-forge-5.18.6+mc1.20.1.jar
modlist.txt
MonsterPlus-Forge1.20.1-v1.1.6.1.jar
moonlight-1.20-2.12.6-forge.jar
multipiston-1.20-1.2.43-RELEASE.jar
mutil-1.20.1-6.1.1.jar
mvs-4.1.2-1.20-forge.jar
Necronomicon-Forge-1.4.2.jar
netherdepthsupgrade-3.1.5-1.20.jar
nethersdelight-1.20.1-4.0.jar
NightConfigFixes-v8.0.0-1.20.1-Forge.jar
noisium-forge-2.0.3+mc1.20-1.20.1.jar
notenoughanimations-forge-1.7.4-mc1.20.1.jar
Nullscape_1.20.x_v1.2.6.jar
obscure_api-15.jar
octolib-1.20.1-0.3.jar
OpenLoader-Forge-1.20.1-19.0.4.jar
Paraglider-forge-20.1.3.jar
part 2.zip
part1.zip
Patchouli-1.20.1-84-FORGE.jar
phantasmic-1.20.1-0.2.5.jar
Philips-Ruins1.20.1-4.1.jar
photon-forge-1.20.1-1.0.7.a.jar
Placebo-1.20.1-8.6.2.jar
player-animation-lib-forge-1.0.2-rc1+1.20.jar
plushies-1.4.0-forge.jar
polymorph-forge-0.49.5+1.20.1.jar
probejs-7.0.1-forge.jar
ProgressiveBosses-3.9.7-mc1.20.1.jar
puffish_attributes-0.4.0-1.20-forge.jar
puffish_skills-0.12.2-1.20-forge.jar
PuzzlesLib-v8.1.21-1.20.1-Forge.jar
Quark-4.0-458.jar
questsadditions-1.4.3a.jar
raccompat-1.20.1-0.1.2.1.jar
radium-mc1.20.1-0.12.3+git.50c5c33.jar
ramcompat-1.20.1-0.1.3.jar
RegionsUnexploredForge-0.5.5+1.20.1.jar
relics-1.20.1-0.6.5.2.jar
resourcefulconfig-forge-1.20.1-2.1.2.jar
rhino-forge-2001.2.2-build.18.jar
right-click-harvest-3.2.3+1.20.1-forge.jar
saturn-mc1.20.1-0.1.3.jar
Searchables-forge-1.20.1-1.0.3.jar
SimpleRPC-Universal-3.3.1.jar
simplyswords-forge-1.55.0-1.20.1.jar
smoothchunk-1.20.1-3.6.jar
solapplepie-1.20.1-2.3.0.jar
sophisticatedbackpacks-1.20.1-3.20.5.1044.jar
sophisticatedcore-1.20.1-0.6.22.611.jar
sound-physics-remastered-forge-1.20.1-1.4.2.jar
spark-1.10.53-forge.jar
starlight-1.1.2+forge.1cda73c.jar
Steam_Rails-1.6.4+forge-mc1.20.1.jar
Stoneworks-v8.0.0-1.20.1-Forge.jar
storagedrawers-1.20.1-12.0.3.jar
structure_gel-1.20.1-2.16.2.jar
structurize-1.20.1-1.0.740-BETA.jar
supplementaries-1.20-2.8.17.jar
sworddisplay-1.20.1-1.0.0.jar
takesapillage-1.0.3-1.20.1.jar
tectonic-forge-1.19.3-2.3.5a.jar
TerraBlender-forge-1.20.1-3.0.1.7.jar
Terralith_1.20_v2.5.1.jar
tetra-1.20.1-6.3.0.jar
tetraextras-0.1.4-1.20.1.jar
tetranomicon-1.5.3-1.20.1.jar
The_Graveyard_3.1_(FORGE)_for_1.20.1.jar
thitemstages-1.20.1-0.2.1.jar
tlc_forge-1.0.3-R-1.20.X.jar
TonsOfEnchants-1.20.1-1.0.jar
toofast-1.20-0.4.3.5.jar
totw_modded-forge-1.20.1-1.0.5.jar
towntalk-1.20.1-1.1.0.jar
TravelersTitles-1.20-Forge-4.0.2.jar
TreeChop-1.20.1-forge-0.19.0.jar
Twigs-1.20.1-3.1.0.jar
twilightforest-1.20.1-4.3.2508-universal.jar
valhelsia_core-forge-1.20.1-1.1.2.jar
VisualWorkbench-v8.0.0-1.20.1-Forge.jar
Voidscape-1.20.1-1.5.389.jar
watut-forge-1.20.1-1.1.1.jar
waystones-forge-1.20-14.1.4.jar
WeaponsOfMiracles-20.1.7.40.jar.DISABLED
witheringboon-1.8.3.jar
XaerosWorldMap_1.38.8_Forge_1.20.jar
Xaeros_Minimap_24.2.0_Forge_1.20.jar
YungsApi-1.20-Forge-4.0.5.jar
YungsBetterEndIsland-1.20-Forge-2.0.6.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar
YungsBridges-1.20-Forge-4.0.3.jar
Zeta-1.0-19.jar

**Comment by Yesssssman** [comment]
Please launch the server without epicfight and its addons. What I found from your crash log is some mod is trying to access LDLib on the server side which is a client side mod.

**Comment by HypnoticChris** [comment]
oh wow thank you so much, I had heard before that photon (a mod that uses LDLib despite the mod itself not being installed) didn't need to be ran on the server, but I didn't think it would cause issues, as I said, removing epic fight and the addons the server would boot just fine even with photon installed.. mods are weird. But thank you, time to continue debugging.
