### ISSUE TITLE
[Bug|Crash]: Crash while in-game

### ISSUE THREAD

**Issue by lartts** [Yesssssman/epicfightmod#1693]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.7.4

### Minecraft Version

1.20.1

### What happened?

[latest.log](https://github.com/user-attachments/files/16177942/latest.log)
[crash-2024-07-11_20.34.45-server.txt](https://github.com/user-attachments/files/16177948/crash-2024-07-11_20.34.45-server.txt)

**Comment by Yesssssman** [comment]
Caused by Epic Fight Battle Styles. The developer is aware of this issue and fixing it now.  I recommend removing the mod before the new version is uploaded.

**Comment by Yesssssman** [comment]
I checked this issue no longer occurs in the latest epic fight battle styles.
