### ISSUE TITLE
Crash: : Game Crash When Dual Wielding Great Swords Against Lord of Sorcery in Dawncraft Echoes of Legend

### ISSUE THREAD

**Issue by Talionius** [Yesssssman/epicfightmod#1695]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Dawncraft Echos of Legend

### Minecraft Version

1.18.2

### What happened?

Game Crash When Dual Wielding Great Swords Against Lord of Sorcery in Dawncraft Echoes of Legend

Description:
The game crashes specifically when fighting the Lord of Sorcery in the Dawncraft Echoes of Legend mod while dual-wielding great swords. The crash occurs upon successfully hitting the enemy with the offhand weapon. After the initial crash, the game continuously crashes immediately upon logging in until the save file is edited to change the difficulty to peaceful. This issue may be related to the combination of mods in the Dawncraft mod pack rather than Epic Fights alone. However, I am reporting this for documentation purposes and hoping to find a fix.

Steps to Reproduce:

Install Dawncraft through Forge.
Learn the skill to dual-wield Great Swords.
Progress the main quest until you reach the Lord of Sorcery (Note: This issue may occur with other bosses, but I only had the skill to dual-wield great swords at this point).
Upon a successful hit with the offhand weapon, the game will freeze and eventually crash with the error: The Game Crashed whilst ticking enemy.
Expected Behavior:
The game should not crash when dual-wielding great swords against the Lord of Sorcery or any other boss.

Actual Behavior:
The game crashes upon a successful hit with the offhand weapon while dual-wielding great swords against the Lord of Sorcery.

Error Message:
The Game Crashed whilst ticking enemy

Additional Information:

Minecraft Version: [Your Minecraft Version]
Forge Version: [Your Forge Version]
Dawncraft Mod Version: [Your Dawncraft Mod Version]
Epic Fights Mod Version: [Your Epic Fights Mod Version]
Other Installed Mods: [List other mods in the mod pack]
Temporary Workaround:
Editing the save file with NBTExplorer to change the difficulty to peaceful allows logging in without crashing, but this is not a viable long-term solution.

Attachments:
[crash-2024-07-11_21.55.59-server.txt](https://github.com/user-attachments/files/16198110/crash-2024-07-11_21.55.59-server.txt)
![game-crash-error](https://github.com/user-attachments/assets/f71bd66e-2a0e-4438-9f5c-3692f668dc9d)

This issue is likely due to the interaction between multiple mods in the Dawncraft mod pack. Any insight or potential fixes would be greatly appreciated. Thank you so much for your help.

**Comment by Yesssssman** [comment]
Could you check how many folders are under `.minecraft\libraries\org\apache\logging\log4j\log4j-api` ?

**Comment by Talionius** [comment]
![image](https://github.com/user-attachments/assets/7e8f6f3a-f96b-41ba-9208-18b961de8016)
I have two folders. One of them is `2.17.0`, the other is `2.22.1`.

**Comment by Yesssssman** [comment]
I installed dawncraft and didn't get the same crash... Well the only fact that I can see from the log is those libraries are conflicting in your game. Sorry but this issue is just out of my boundary...

**Comment by Talionius** [comment]
Thank you for looking into it! I appreciate it! <3
