### ISSUE TITLE
Entity Scaling Issue

### ISSUE THREAD

**Issue by JonasL0430** [Yesssssman/epicfightmod#1696]
Just wanted to put in a formal bug report for this. Basically, anytime an entity (including the player) is scaled up using the scale value in Epic Fight, the Y rotation of said entity starts to not work properly. Best way I can describe it is that, when facing certain directions (for me it was often East with the player) the rotation of the entity gets offset by about -30 degrees from what it should be. This leads to the entity facing the wrong direction compared to the direction they're traveling in. 

This is a bit annoying when scaling up the player, but is especially problematic when scaling up entities (the more common use case) as it makes them quite difficult and janky to fight.

**Comment by JonasL0430** [comment]
I can see this says it's been solved, thanks for fixing it so quick! I don't see any commits listed that relate to this fix though. Is it possible you could share what changes were made to fix it (if the changes were simple enough)? I need to back port the fixes to 20.7.4 (if possible) in order to maintain compatibility with a few epic fight addons.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
