### ISSUE TITLE
Skin rendering error

### ISSUE THREAD

**Issue by Opareds** [Yesssssman/epicfightmod#17]
I noticed that on my skin there's a few pixels that isn't supposted to be there. Like black pixels on spots I circled red. You may look closely to see them. That's all errors I have noticed for now, i'll write more if i found more of them.
![image](https://user-images.githubusercontent.com/63459953/108876746-9917e880-760f-11eb-983f-39fe07166d40.png)

**Comment by Yesssssman** [comment]
Ok, I'll modify the model file.

**Comment by Yesssssman** [comment]
Wait, can I know which version you are using?

**Comment by Opareds** [comment]
now i use 2.0.3, still same problem, and it's not with optifine, i tested it before
