### ISSUE TITLE
[Bug|Crash]: Game crashed! 

### ISSUE THREAD

**Issue by Starlux531** [Yesssssman/epicfightmod#1701]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

When I made a serious error while entering the game, I didn't even enter the game loading interface. Strangely enough, it still runs on my other device. The crash is just a probability issue. After ruling it out, I have preliminarily concluded that removing Epicfight can make the game run smoothly, but I need this mod. Please help me determine the problem.

this is crash info: https://github.com/AudioHackerZ/crash-track/blob/main/crash20240716.log

**Comment by Rxnzo** [comment]
Remove / Disable flywheel and test that

**Comment by AudioHackerZ** [comment]
“Flywheel is now intended to be bundled within the mods that need it. You do not need to download Flywheel directly for versions >= 0.6.9.”  So flywheel not in my mod list.If I put it in, it will fail 100% of the time.

**Comment by Starlux531** [comment]
> Remove / Disable flywheel and test that

“Flywheel is now intended to be bundled within the mods that need it. You do not need to download Flywheel directly for versions >= 0.6.9.” So flywheel not in my mod list.If I put it in, it will fail 100% of the time.

**Comment by Rxnzo** [comment]
According to your crashlog you do have flywheel installed

**Comment by Starlux531** [comment]
> According to your crashlog you do have flywheel installed

I will not repeat these very basic common sense.
If the flywheel is to blame, I'd love to find a way to fix it！

The explanation of flywheel is in this link.：https://createmod.net/whywheel/

**Comment by Yesssssman** [comment]
Well I can't get any useful information in the crash log. Could you please narrow down which mod is causing this error?

**Comment by Yesssssman** [comment]
Same as #1700 tho

**Comment by Starlux531** [comment]
> Same as #1700 tho

After several days and nights of debug, I found that tac conflicts with your mod. tac is a gun mod that improves many actions and control-related content. Although I don't know where the specific conflict is, the solution is to replace the latest version of tacz, aka Tac-Zero.

**Comment by Starlux531** [comment]
> Same as #1700 tho

I have posted the solution in various forums. In fact, many people have reported this problem. However, I understand that this is a complicated job. If possible, please add labels.

**Comment by Yesssssman** [comment]
They have fixed the issue, but it's only 1.20.1...
[![image](https://github.com/user-attachments/assets/78df7e14-f788-4523-a319-95578df9d3da)
](https://github.com/MCModderAnchor/TACZ/commit/90d327f133aeeb838379e649d9726f8172e45b66)
