### ISSUE TITLE
Epic fight mod and addons failing to load

### ISSUE THREAD

**Issue by Guram0n** [Yesssssman/epicfightmod#1702]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight+Epic Fight addons

### Minecraft Version

1.18.2

### What happened?

It says Epic Fight mod has failed to load correctly along with all the epic fight addons

**Comment by Yesssssman** [comment]
Attach the log
