### ISSUE TITLE
[Bug|Crash]:  Vanilla attack and I don't do damage

### ISSUE THREAD

**Issue by JustYourGithubUser** [Yesssssman/epicfightmod#1704]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.20.1

### What happened?

Ok, so i saw this video on youtube that was: "turning minecraft into a combat game". I always wanted a minecraft like that, so i watched. it talked about epic fight so i went onto forge, downloaded epic fight and some other epic fight compatible mods. I summoned a piglin, and attacked it, and not only did it not play a animated attack, but it DIDN'T DO DAMAGE!!! like, AT ALL!!! so i reloaded, and it still didnt work... Help PLS!

**Comment by Yesssssman** [comment]
Press R to get into battle mode
