### ISSUE TITLE
[Bug|Crash]: Steel Whirlwind Crashing other nearby clients

### ISSUE THREAD

**Issue by Rxnzo** [Yesssssman/epicfightmod#1705]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.18.2

### What happened?

When users use Steel Whirlwind in my server, it crashes anyone nearby, I did see this get updated for 1.19.2 but I'm assuming I'm having the same issue on 1.18.2
[crash-2024-07-18_13.14.41-client.txt](https://github.com/user-attachments/files/16288765/crash-2024-07-18_13.14.41-client.txt)

**Comment by Yesssssman** [comment]
#1705

**Comment by Yesssssman** [comment]
We will publish everything at once since we're on a big update. Thanks for reporting anyway

**Comment by Yesssssman** [comment]
Fixed in 18.5.16. Enjoy it!
