### ISSUE TITLE
[Bug|Crash]: Epic Fight acting up? Need help

### ISSUE THREAD

**Issue by Axisiser** [Yesssssman/epicfightmod#1708]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight

### Minecraft Version

1.20,1

### What happened?

While playing custom modpack, running into crashing problems. World would start and start playing and suddenyly black screen and then crashes.
[crash-2024-07-20_21.06.15-server.txt](https://github.com/user-attachments/files/16323067/crash-2024-07-20_21.06.15-server.txt)

**Comment by Yesssssman** [comment]
Crash from Epic Fight Battle Styles

**Comment by Yesssssman** [comment]
I checked this issue no longer occurs in the latest epic fight battle styles.
