### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by StratCube2** [Yesssssman/epicfightmod#1709]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Weapons of miracles failing to load

### Minecraft Version

1.20.1

### What happened?

I am making a modpack for me and my friend to play on a server but when I tried testing to see if all the mods work there seems to be a problem which said that weapons of miracles failed to load. I checked config and I found a file called wom.toml but it has nothing in it. I have attached a files.
[latestlog.txt](https://github.com/user-attachments/files/16324075/latestlog.txt)
[crash-2024-07-21_15.42.00-fml.txt](https://github.com/user-attachments/files/16324078/crash-2024-07-21_15.42.00-fml.txt)
[crash-2024-07-21_15.40.16-fml.txt](https://github.com/user-attachments/files/16324079/crash-2024-07-21_15.40.16-fml.txt)
[crash-2024-07-21_15.36.55-fml.txt](https://github.com/user-attachments/files/16324080/crash-2024-07-21_15.36.55-fml.txt)
[crash-2024-07-21_15.35.50-fml.txt](https://github.com/user-attachments/files/16324081/crash-2024-07-21_15.35.50-fml.txt)
Forge version:47.3.5

**Comment by M6FGR** [comment]
Wom version is too old. Try upgrading it

**Comment by StratCube2** [comment]
Ok

**Comment by StratCube2** [comment]
It worked. Thanks
