### ISSUE TITLE
[Bug|Crash]: The game crashed whilst ticking entity Error: java.lang.NullPointerException: Cannot invoke "yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.getEntityState()" because "playerpatch" is null

### ISSUE THREAD

**Issue by B-Mesia** [Yesssssman/epicfightmod#1710]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

happened right after a gorgon of ice and fire mod killed me while playing with my ow modpack. There is the log
[message.txt](https://github.com/user-attachments/files/16325348/message.txt)
.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!
