### ISSUE TITLE
[Bug|Crash]: Epic Fight (epicfight) has failed to load correctly

### ISSUE THREAD

**Issue by HoyoshiShounen** [Yesssssman/epicfightmod#1711]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [x] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

[crash-2024-07-22_20.00.05-fml.txt](https://github.com/user-attachments/files/16337458/crash-2024-07-22_20.00.05-fml.txt)
[latest.log](https://github.com/user-attachments/files/16337459/latest.log)

Can anyone help?

**Comment by M6FGR** [comment]
Is secure jar handler a mod in the modlist?

**Comment by M6FGR** [comment]
If yes then try removing it

**Comment by Yesssssman** [comment]
Some epic fight addons are outdated. Please remove them from your modlist.

**Comment by HoyoshiShounen** [comment]
if I download the old version of epic fight, will I be able to install these addons?

**Comment by Yesssssman** [comment]
Maybe, but I'm not sure which version is it.

**Comment by HoyoshiShounen** [comment]
minecraft version 1.20.1, mod version 20.7.4

**Comment by HoyoshiShounen** [comment]
or are you talking about the addon version?

**Comment by Yesssssman** [comment]
I mean, If you downgrade Epic Fight version, you can use the addon causing this crash. but I don't know which epic fight version is compatible with it.

**Comment by M6FGR** [comment]
try versions between 20.6.3-20.7.2
