### ISSUE TITLE
[Suggestion|Bug|Mod Support]: Custom Maps do not Preview Maps despite Map Animation being Active

### ISSUE THREAD

**Issue by AriaElidove** [Yesssssman/epicfightmod#1714]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

The Twilight Forest

### Minecraft Version

1.20.1

### What happened?

When holding a vanilla Minecraft Map, there is a custom animation for holding and viewing the map properly. However, when modded maps do this, in this case Twilight Forest's Magic Map, Maze Map, and Ore Map, the map is not previewed as it would without the Epic Fight animations being enabled, as shown below. This can be "fixed" by just hitting `R`, but I feel adding support for this, and potentially other modded map types would be benefitial.

----
With Epic Fight Animations:
![image](https://github.com/user-attachments/assets/80aeb516-0f3d-4d33-a912-7ea3627be0ef)

Without Epic FIght Animations:
![image](https://github.com/user-attachments/assets/ef847387-555c-4f34-a9e9-015706b9d685)

----
The initial thought I had for this would be to support anything under `forge:maps` or an appropriate equivalent, but I don't believe this exists as a tag... Also, I have no idea how the map previewing system works between Epic Fight and vanilla/modded (ie Supplimentaries) maps work, as well as how Twilight Forest map previewing work, so this may not work as an idea at all.

See Also: https://github.com/TeamTwilight/twilightforest/issues/2171

**Comment by Yesssssman** [comment]
Fixed in the latest efm

![image](https://github.com/user-attachments/assets/0d68c15e-276f-4a8c-b3e7-f39c1b0eabda)
![image](https://github.com/user-attachments/assets/3d11050c-a010-4065-95ef-9749b533df6a)
