### ISSUE TITLE
Friendly fire not deactivated

### ISSUE THREAD

**Issue by yaboua** [Yesssssman/epicfightmod#1715]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

When players are on the same team, they can't damage each other with vanilla attacks.
However the epic fight attacks still damage allies

**Comment by guivnf** [comment]
Attach footage, mod version, game version and if needed logs.

**Comment by Yesssssman** [comment]
https://github.com/user-attachments/assets/80cbbec0-2cd7-4ec2-9137-f92aec02cec2

We can't reproduce the bug
