### ISSUE TITLE
[Bug|Crash]: Datapack of Ender dragon cause game issue

### ISSUE THREAD

**Issue by ShenxPresent** [Yesssssman/epicfightmod#1716]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

error while use datapack to edit ender dragon.
related log: https://mclo.gs/d3YfxJk
possible fix: yesman.epicfight.world.capabilities.entitypatch.LivingEntityPatch.onConstructed may should check if it is a living entity

**Comment by Yesssssman** [comment]
Oof... Ender dragon doesn't meet the condition that can be customizable. I will just exclude Ender dragon from the options to patch.

**Comment by Yesssssman** [comment]
Fixed in 20.8.4
