### ISSUE TITLE
[Bug]: Datapacks showing incorrect values

### ISSUE THREAD

**Issue by faerheart** [Yesssssman/epicfightmod#1717]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Minecraft Version

1.20.1

### What happened?

Changing weapon values with datapacks is causing other weapons to inherit the same changes of the item in the main hand.

![image](https://github.com/user-attachments/assets/5257b0f3-b057-4307-9d8a-30fb30de27fc)

The image shows that the Iron Sword has it's attack damage reduced by **1**, making it **5**. However every other weapon is also showing the same value adjustment, all showing their attack damage being reduced even when not equipped.

This bug also occurs when dual-wielding, where in this case every weapon is getting their attack damage reduced by **3** instead.

Datapack is also being applied to the world via the Paxi mod

**Comment by Yesssssman** [comment]
Gouki the god

**Comment by Yesssssman** [comment]
Fixed in 20.8.3
