### ISSUE TITLE
[Bug|Crash]: Ticking entity

### ISSUE THREAD

**Issue by KinoaKizuto** [Yesssssman/epicfightmod#1718]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic fight

### Minecraft Version

1.20.1

### What happened?

Game crashes right after creating a new world, here's the log:
[crash-2024-08-03_21.29.36-server.txt](https://github.com/user-attachments/files/16484465/crash-2024-08-03_21.29.36-server.txt)

**Comment by Yesssssman** [comment]
Update epic fight battle styles

**Comment by KinoaKizuto** [comment]
> Update epic fight battle styles

Solved with that, tysm for the response and your work!
