### ISSUE TITLE
[Crash]: Trying to render player model in Datapack Editor after loading from previous save causes game crash.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1719]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.8.2

### Minecraft Version

1.20.1

### What happened?

Trying to render player model in Datapack Editor after loading from previous save causes game crash.

## Steps to reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Press "Mods", then select Epic Fight mod, click "Config";
3. Select "Datapack Editor";
4. Add new weapon by pressing "+", call it and choose a category for it;
5. Exit datapack editor by pressing "Cancel";
6. Invoke "Datapack Editor" once again;
7. Dialog box should say about loading previous pack. Press "Ok";
8. Game should crash at this point, but if you're playing in low resolution, then scroll down using mouse wheel.

## Expected behavior

Datapack Editor doesn't crash when approaching rendered player model.

## Observed behavior

Datapack Editor crashes the game when approaching rendered player model.

## Video

https://github.com/user-attachments/assets/bbf703c9-a09a-4db1-acf8-37b0d20bde1d

## Crash Log

[crash-2024-08-04_12.18.19-client.txt](https://github.com/user-attachments/files/16486681/crash-2024-08-04_12.18.19-client.txt)

**Comment by Yesssssman** [comment]
Fixed in 20.8.3

**Comment by Raccffy** [comment]
> Fixed in 20.8.3

It works like clockwork. Thanks, [Yesssssman](https://github.com/Yesssssman)!
