### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by goldrichman9Modded** [Yesssssman/epicfightmod#1720]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [X] This is a mod compatibility issue and I'm aware of the problem.

### The mod

https://www.curseforge.com/minecraft/mc-mods/changed-minecraft-mod

### Minecraft Version

1.18.2

### What happened?

So, i was _froced_ to play to mod with epic fight and i realize the other models that mod has don't have epic fight animations the just have still moment without the model moving, but it works fine it just that these no animaions with the other mobs the mod adds.

**Comment by Yesssssman** [comment]
1.18.2 is not supported anymore.
