### ISSUE TITLE
[Crash]: Exporting datapack with invalid Windows filename causes game crash.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1721]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.8.3

### Minecraft Version

1.20.1

### What happened?

Exporting datapack with invalid Windows filename causes game crash.

## Steps to reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Press "Mods", then select Epic Fight mod, click "Config";
3. Select "Datapack Editor";
4. Make a simple datapack;
5. When all mandatory parameters are set, press "Export" button;
6. Write any invalid or reserved Windows filename and press "Ok".

## Expected behavior

Datapack Editor warns the player about invalid filename.

## Observed behavior

Datapack Editor crashes the game due to Windows restrictions.

## Video

https://github.com/user-attachments/assets/667e4623-f9b2-4f58-881c-14a10e110530

## Notes

Here's [complete list of forbidden filenames for Windows.](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file)

**Comment by Yesssssman** [comment]
Fixed in 20.8.4
