### ISSUE TITLE
[Bug]: Cannot vertically move datapack menus by dragging scroll bars.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1722]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.8.3

### Minecraft Version

1.20.1

### What happened?

Cannot vertically move datapack main menus by dragging scroll bars.

## Steps to reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Press "Mods", then select Epic Fight mod, click "Config";
3. Select "Datapack Editor";
4. Try to move scroll bar.

## Expected behavior

Menu moves vertically by dragging the scroll bar.

## Observed behavior

Menu is stuck.

## Video

https://github.com/user-attachments/assets/4fb70383-8458-419e-be5f-f7c8a7601583

## Notes

Submenus (such as "Hit Particle", "Hit Sound", "Swing Sound" and etc.) are not affected.

**Comment by Yesssssman** [comment]
Fixed in 20.8.4
