### ISSUE TITLE
[Bug]: Save warning appears, even if nothing was changed.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1723]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.8.3

### Minecraft Version

1.20.1

### What happened?

Save warning appears, even if nothing was changed.

## Steps to reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Press "Mods", then select Epic Fight mod, click "Config";
3. Select "Datapack Editor";
4. Choose any option from the list below and press "Cancel".

#### Weapon Type

- Styles;
- Offhand Validator;
- Combos;
- Living Animations.

#### Item Capability

- Attributes (requires any item type).

#### Mob Capability

- Combat Behavior (requires any selected armature and model).

## Expected behavior

Datapack Editor returns to previous main menu.

## Observed behavior

Datapack Editor warns the user about saving changes.

## Video

https://github.com/user-attachments/assets/cb64feb9-97c0-4cee-aa71-0d49e447de97

**Comment by Yesssssman** [comment]
There is a hidden function for it. If you press ok, the default values will be set up for the tag the screen is handling, If you press cancel, it doesn't create default values.

**Comment by Raccffy** [comment]
> There is a hidden function for it. If you press ok, the default values will be set up for the tag the screen is handling, If you press cancel, it doesn't create default values.

Ah, okay. Got it.
