### ISSUE TITLE
[Bug]: Ender Dragon's area effect breath is untranslated.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1724]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### The mod

Epic Fight 20.8.3

### Minecraft Version

1.20.1

### What happened?

Ender Dragon's area effect breath is untranslated.

## Steps to reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Press "Singleplayer", select existing world or create a new one;
3. Switch your gamemode to survival or adventure;
4. Summon Ender Dragon(s) and wait for your fate.

## Expected behavior

Game prints "[Player] was killed by Ender Dragon using magic".

## Observed behavior

Game prints "[Player] was killed by `entity.epicfight.area_effect_breath` using magic".

## Video

https://github.com/user-attachments/assets/abb1c8fa-a072-428e-a061-e7ccba16bf81

**Comment by Yesssssman** [comment]
Fixed in 20.8.4
