### ISSUE TITLE
[Bug]: OpenGL debug message spam in console when use_animation_shader is true

### ISSUE THREAD

**Issue by DeshiDesu** [Yesssssman/epicfightmod#1725]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

![image](https://github.com/user-attachments/assets/7234bd08-7217-4e81-8ad0-e8aa3e43d7cd)
My logs are being spammed with this message. When I turn off use_animation_shader it goes away.

I'm not really sure why this is happening. If it helps with narrowing the culprit I'll provide any other info on this bug.

**Comment by DeshiDesu** [comment]
https://github.com/user-attachments/assets/aa51d27c-7d74-4706-bde8-d51935ef809a

May be unrelated but I also have error messages about travelers backpack and wavey capes. Im assuming its because i dont have the mods installed.
![image](https://github.com/user-attachments/assets/bd6f1fe3-8fdc-4517-9da7-89e2acd25214)

**Comment by Yesssssman** [comment]
Turn off the animation shader. It's not 100% compatible with all OS and graphic cards.

You can ignore those warning messages. It's just checking for the develops.
