### ISSUE TITLE
[Bug|Crash]: The new weapon types created are not changing their attributes

### ISSUE THREAD

**Issue by qVoidreaver** [Yesssssman/epicfightmod#1726]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

  [ New Version ] 
  
  Creating new weapon types and applying attributes means that ALL weapons linked to the weapon type are based ONLY on the attribute of one of the weapons linked to the weapon type created.

 For example: I created a certain type of weapon, applied that type of weapon using "Item Capabilities" to 3 different weapons, which means that it will only take 1 of those weapons and apply its attribute to ALL the others (it may not be just 1, that was my speculation, it may be that it takes 2 and makes a mix).
 
  And delving deeper into "Item Capabilities", using the minus sign "-" when giving attributes (whether for armor or weapons) causes the game to crash
  
  
  The new update is fantastic, I can't wait to see what the community creates with it! Thanks for your attention and have a nice day.

**Comment by qVoidreaver** [comment]
bytebin.lucko.me/pgdMi75E2U -> Crashlog with " - " string

**Comment by Yesssssman** [comment]
I still don't get what you mean. Weapon type doesn't have any data about attributes and you have to give attributes to all item capabilities. It doesn't copy or paste attributes from specific Item Capability.

I solved the second issue. Thanks for reporting!

**Comment by qVoidreaver** [comment]
> I still don't get what you mean. Weapon type doesn't have any data about attributes and you have to give attributes to all item capabilities. It doesn't copy or paste attributes from specific Item Capability.
> 
> I solved the second issue. Thanks for reporting!

 I'll even try to explain with examples.
 
 I created a weapon type. This type of weapon, when applied to "Item Capabilities" (where attributes are applied), is limited to 1 weapon out of several that have been applied to this type of weapon, for example:

{
  "collider": {
    "number": 3,
    "size": [
      0.1,
      0.2,
      1.0
    ],
    "center": [
      0.0,
      0.0,
      -1.0
    ]
  },
  "attributes": {
    "two_hand": {
      "impact": 2.5,
      "max_strikes": 4,
      "armor_negation": 0.0,
      "damage_bonus": -9.0,
      "speed_bonus": -0.60
    }
  },
  "type": "epicfight:newgreatsword"
}

* "epicfight:newgreatsword" is the type of weapon created, and in this file it is a modification of the Stone Greatsword.

This one:

{
  "collider": {
    "number": 3,
    "size": [
      0.1,
      0.2,
      1.0
    ],
    "center": [
      0.0,
      0.0,
      -1.0
    ]
  },
  "attributes": {
    "two_hand": {
      "impact": 1.5,
      "max_strikes": 2,
      "armor_negation": 0.0,
      "damage_bonus": -3.0,
      "speed_bonus": -0.55
    }
  },
  "type": "epicfight:newgreatsword"
}

 This is what is applied to an Iron Greatsword.

What I've been trying to explain is that ONLY the modification made to the Stone Greatsword will be applied to the TWO Greatswords, COMPLETELY ignoring the attributes of the Iron Greatsword's .json file.

**Comment by qVoidreaver** [comment]
If I'm not mistaken, this attribute error doesn't occur if the weapon type exists, only if it is created.
 And yes, I think I could make several types of weapons with the same movement but different names to get around this bug, but it would be more work, I think.
