### ISSUE TITLE
[Bug|Crash]: The game crashed whilst unexpected error. Error: java.lang.IllegalStateException: Mesh destroyed

### ISSUE THREAD

**Issue by zank8151** [Yesssssman/epicfightmod#1727]
### Have you checked if a similar issue is already reported by someone else?

- [X] I checked there are no similar issues have been reported.

### Have you read the support policy?

- [X] I read it and I accept the policy.

### Are you using the latest Epic Fight and recommended Forge version?

- [X] I checked I'm using latest Epic Fight and recommended Forge version.

### Is this issue related to mod incompatibility?

- [ ] This is a mod compatibility issue and I'm aware of the problem.

### Minecraft Version

1.20.1

### What happened?

Game ONLY crashes in a server i own, cannot load a specific mesh, error message talks about first person camera, deleting the mod and reinstalling both server and client-side did not fix, game runs perfectly fine in singleplayer may be a conflicting mod error however it has ran fine for the past couple days with what i had and nothing new has been added.
mods: jujutsu craft, jujutsu craft compatability, weapons of miracles

error message: [https://mclo.gs/U24oHk4](https://mclo.gs/U24oHk4)

**Comment by Yesssssman** [comment]
Fixed in 20.8.5

**Comment by zank8151** [comment]
ty ❤️❤️ awesome mod
