### ISSUE TITLE
[Bug|Crash]: WoM: Failed to register automatic subscribers. ModID: wom, class reascer.wom.main.WeaponsOfMinecraft org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

### ISSUE THREAD

**Issue by P-Michalski** [Yesssssman/epicfightmod#1729]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Weapons of Miracles

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I am playing on my modded server. Upgrading Epic Fight and WoM throws an error on the client (WoM doesn't load properly)
Tested both on forge 47.3.0 and 47.3.5 with different versions of new Epic Fight and WoM releases. It worked fine server-side and server seemed to load properly (no console info regarding some errors). Both server and client work fine with 1.20.1 versions that were "newest" before 03.08 (date when the new releases came out). I have no idea what causes this problem, I tried looking for a simillar issue on GitHub and Epic Fight discord, but the issues there were mostly related to some Epic Fight addons beeing outdated.

My modlist is visible in the latest.log file that I attach. I would be grateful for any ideas on how to resolve the issue.

[latest.log](https://github.com/user-attachments/files/16508139/latest.log)

### Steps to Reproduce

Launch forge 47.3.X with my modlist.

**Comment by Yesssssman** [comment]
Armourers workshop is not compatible with the latest Epic fight. Please remove the mod until it releases newer version.
