### ISSUE TITLE
[Bug]: Selecting certain colliders in Weapon Type causes error message to appear.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1730]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.5

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Selecting certain colliders in Weapon Type causes "Cannot read field "f_82479_" because "this.modelCenter" is null" error.

#### Affected colliders

- `epicfight:battojutsu_dash`
- `epicfight:biped_body_collider`

### Steps to Reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Enter "Mods" menu, select Epic Fight and click "Config";
3. Invoke Datapack Editor;
4. Press "+" to add a new weapon;
5. Find collider option and click search button;
6. Choose one of the affected colliders from the list.

### Screenshot

![modelCenter](https://github.com/user-attachments/assets/f80d4087-97b8-449b-aa0b-0843ac23dd2b)

**Comment by Yesssssman** [comment]
Fixed in 20.8.6
