### ISSUE TITLE
[Bug]: Dialog box does not make things in the background inactive.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1731]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.5

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

If dialog box is displayed, things in the background (such as button hovering, tooltips appearing) are still active.

### Steps to Reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Enter "Mods" menu, select Epic Fight and click "Config";
3. Invoke Datapack Editor;
4. Press "+" to add new weapon;
5. Exit Datapack Editor and invoke it once again;
6. Hover on buttons, options and Datapack Editor's pages.

### Expected behavior

Buttons and pages are **not** active. Tooltips are **not** appearing.

### Observed behavior

Buttons and pages are active. Tooltips are appearing and may overlay dialog box.

### Notes

Trying to click on the buttons at the background doesn't do anything.

### Video

https://github.com/user-attachments/assets/0279ae75-4e4b-4fc1-9750-5139f449496e

*Note: This video was recorded before 20.8.5 was released. Latest version is still affected by the bug.*

**Comment by Yesssssman** [comment]
Fixed in 20.8.6
