### ISSUE TITLE
[Bug]: Dragging scroll bar in dropdown menus is broken.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1732]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.5

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Trying to move scroll bar in dropdown menus yields in nothing. It just disappears.

This is continuation of #1722.

### Steps to Reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Enter "Mods" menu, select Epic Fight and click "Config";
3. Invoke Datapack Editor;
4. Press "+" to add new weapon;
5. Click category dropdown menu and try to move the scroll bar.

### Video

https://github.com/user-attachments/assets/a1bc8d32-d216-44e0-828f-8f28b4b6d618

*Note: This video was recorded before 20.8.5 was released. Latest version of Epic Fight is still affected by the bug.*

**Comment by Yesssssman** [comment]
Fixed in 20.8.6
