### ISSUE TITLE
[Bug]: Reloading resources in the middle of moving skill performance disables skill movement.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1733]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.5

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Reloading resources in the middle of moving skill performance disables skill movement.

### Steps to Reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Create a new world or select a new one with cheats enabled;
3. Switch your gamemode to creative.
4. Learn moving skills or grab weapons to perform move attacks;
5. In the middle of skill performance, press <kbd>F3</kbd>+<kbd>T</kbd>;
6. Try to use moving skills or move attacks once again.

### Affected skills

*These skills were broken during testing. There might be more.*

- Steel Whirlwind;
- Meteor Slam;
- Double dagger attack (every 3rd attack is flawed).

### Expected Behavior

Moving skills and move attacks are still working, regardless of resource pack reloading.

### Observed Behavior

Moving skills and move attacks are broken after resource pack reloading.

### Notes

- Pressing resource pack reloading button combination in singleplayer doesn't stop the current skill from moving, although trying to perform them again fails;
- Reloading resource pack while **not** performing any moving skill fixes the bug.

### Videos

https://github.com/user-attachments/assets/264f29f0-c433-4e78-836f-a91d2cb45205

https://github.com/user-attachments/assets/888833b2-c4cd-4c3c-af53-69a1b3c03303

**Comment by Yesssssman** [comment]
Fixed in 20.8.6
