### ISSUE TITLE
[error] intellij client problem

### ISSUE THREAD

**Issue by M6FGR** [Yesssssman/epicfightmod#1734]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.5

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

In intellij the RunClient is broken.

I cant switch to mining mode and in battle mode i cant eve hit

i could post a video if it helps

### Steps to Reproduce

well the video is 5 seconds long and i cant upload it because its too big
but just what i did is use the runclient in intellij and epic fight is broken and it spams this message:
[19:26:27] [Render thread/INFO] [mojang/GlDebug]: OpenGL debug message: id=1005, source=API, type=ERROR, severity=HIGH, message='No detailed debug message due to a non-debug context'

**Comment by silverxd3** [comment]
I have the same problem. I want to play with my friends on my server, but for some reason some of us our Minecraft crash because of Epic Fight

**Comment by M6FGR** [comment]
> I have the same problem. I want to play with my friends on my server, but for some reason some of us our Minecraft crash because of Epic Fight

its either 2 of these reasons
1 mod incompatibilty
2 corrupted/broken datapack

**Comment by guivnf** [comment]
disable the animation shader

**Comment by silverxd3** [comment]
How?

**Comment by silverxd3** [comment]
But how?

**Comment by guivnf** [comment]
> How?

config

**Comment by silverxd3** [comment]
Let's see, I don't understand. I may be playing with shaders, but before this recent update my minecraft didn't crash with epic fight and shaders on. But now it's crashing just by having shaders on? My friends, some of them, don't even use shaders and their minecraft crashes because of the recent update or even before this new update of the mod.

**Comment by M6FGR** [comment]
what about the intellij client

**Comment by silverxd3** [comment]
Even disabling Shaders my game is still crashing

**Comment by silverxd3** [comment]
- Head --
Thread: Render thread
Suspected Mod: 
	Epic Fight (epicfight), Version: 20.8.5
		Issue tracker URL: https://github.com/Yesssssman/epicfightmod/issues
		at TRANSFORMER/epicfight@20.8.5/yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.getStamina(PlayerPatch.java:382)

**Comment by guivnf** [comment]
> Even disabling Shaders my game is still crashing

saying that doesn't rly help us, attach the logs & make sure to remove every other mod

**Comment by silverxd3** [comment]
I've found the problem. It seems that the Epic Fight mod is not compatible with ModernFix on the client side, but it is compatible on the server side.

**Comment by silverxd3** [comment]
Or well, it is compatible for both sides, but when I enter my server where I play with friends (having both mods activated) the game closes.

**Comment by Yesssssman** [comment]
> * Head --
>   Thread: Render thread
>   Suspected Mod:
>   Epic Fight (epicfight), Version: 20.8.5
>   Issue tracker URL: https://github.com/Yesssssman/epicfightmod/issues
>   at TRANSFORMER/epicfight@20.8.5/yesman.epicfight.world.capabilities.entitypatch.player.PlayerPatch.getStamina(PlayerPatch.java:382)

Please see if your issue has solved in 20.8.6
