### ISSUE TITLE
[Bug|Crash]: Guandao Moveset causing crash

### ISSUE THREAD

**Issue by Nathan2347u809789** [Yesssssman/epicfightmod#1735]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-guandao-moveset/files/4960987/additional-files

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

im trying to use this mod with theepic fight mod and it keeps doing this 
![image_2024-08-06_205600826](https://github.com/user-attachments/assets/01862381-75bd-48f2-8e63-40b20d052bcb)

### Steps to Reproduce

i dont know how to fix it

**Comment by FemBane** [comment]
Getting a similar issue with the guandao moveset, and a lot others, on a much larger scale
latest.log https://mclo.gs/Wn7Joxr
crashlog https://mclo.gs/R4xnVpc

**Comment by M6FGR** [comment]
its outdated
