### ISSUE TITLE
[Bug]: Auto right-click/interaction when looking at some Create Mod blocks after latest updates

### ISSUE THREAD

**Issue by ElectricLithuanian** [Yesssssman/epicfightmod#1739]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Versions after 20.8.2 (20.8.2 doesn't have this issue) introduced a bug where if you're within range of certain Create blocks (Moving chests, contraption controls, potentially others) and looking at them, the player starts auto-interacting/right-clicking on the object repeatedly. Causes a major disruption to gameplay with one of the most popular tech mods in Minecraft. Not listing as a Create mod issue since this was introduced with some of the latest Epic Fight code changes and wasn't a bug before. 

### Steps to Reproduce

Use a contraption with a chest on it in Create Mod and look at the chest when near. Place Contraption Controls on an elevator and look at it when within interaction range.

**Comment by guivnf** [comment]
Disable the animation shader in the config menu and see if it persists

**Comment by ElectricLithuanian** [comment]
Persists after disabling the animation shader. Just tested with 20.8.7, looked like it was already disabled by default

**Comment by TruePureGold** [comment]
Here to comment having the same issue, it also seems to probably be basicly any modded entity that can be interacted with, not just create ones, as i noticed this issue happening with the "backpacked" mod's backpacks

**Comment by ElectricLithuanian** [comment]
Can confirm fixed with 20.8.8. Thank you
