### ISSUE TITLE
[Crash]: Wom Time travel crash + curios items suddenly showing up when they previously did not

### ISSUE THREAD

**Issue by FuryJack07** [Yesssssman/epicfightmod#1741]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

https://pastebin.com/yXfyFJmH
the game just... crashed (well, not really, because I have Neurina which catches entity ticking exceptions so that the game doesn't get bricked)
I was using Wom's time travel dodge skill for fun, testing it out, and then, out of nowhere I was kicked out of my world (because that's what neurina does when it catches a player ticking error, it kicks the erroring player out)

### Steps to Reproduce

I don't know, it was working fine, then when it tried teleporting me back it just crashed and- 

ok, this is me after re-entering the world, and now I'm so confused. before this crash, no item in the curios slots was being rendered, like, none, across multiple game sessions. I thought it was intentional after an update because I remember some problem with curios or something... but after the crash, i entered the world and now all curios items are just... rendering like normal??? What is going on????????

I wish I could send the whole latest.log file but it's FAR too big, If you know somewhere I could send it, tell me, I'm gonna save it

**Comment by FuryJack07** [comment]
AND THEN I CLOSE THE GAME (To get latest.log), REOPEN IT AND ALL CURIOS ITEMS ARE INVISIBLE AGAIN WHAT IS GOING ON THIS MOD IS SO GLITCHY AHHHHHHHHHHHHHHHHHHHHH

**Comment by guivnf** [comment]
Do never report issues here again. We will not tolerate this kind of behavior, and if I see anything from you here again we will remove you indefinitely from here. 

Also, don't use epic fight, we don't care about your issue and we will not attempt to fix whatever is going on on your end, learn how to properly behave online.
