### ISSUE TITLE
[Bug|Crash]: The player's head disappears when they attack.

### ISSUE THREAD

**Issue by xfgj** [Yesssssman/epicfightmod#1742]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Leawind's Third Person

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

The player's head disappears when they attack.

### Steps to Reproduce

it always occurs from the third perspective.

**Comment by xfgj** [comment]
![image](https://github.com/user-attachments/assets/f0936eb7-025c-45b8-bfc1-978deff0674e)

**Comment by guivnf** [comment]
User did not attempt to find the culprit on his own, has clearly many other mods that are conflicting. Closing issue as done.
