### ISSUE TITLE
[Suggestion]: Control the animation during "use" method

### ISSUE THREAD

**Issue by mariumbacchus** [Yesssssman/epicfightmod#1744]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

https://www.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry

### Minecraft Version

1.18.2

### What's your suggestion?

I am currently trying to make my mod Soulslike Weaponry compatible with Epic Fight mod. What I have noticed is that after assigning weapon types to my weapons, such as Darkin Blade being a greatsword, their use animation changes to a block stance and their right click charge abilities break. This is because this mod changes the remaining ticks parameter to `Integer.MAX_VALUE`. This is the reason why other mods also break with this mod, since they often check if `maxUseTime - remainingUseTicks >= 10`, like in the trident class. Since the remaining use ticks value is so large, the result becomes a negative number which makes the ability not trigger.

This is not necessarily a problem for me, after realizing this I adjusted the if statement and the logic works fine. The problem is the default animation it uses for spears and greatswords. Since it defaults to a block animation, it covers the whole screen and looks really off in 3rd person when the real ability is used after a blocking stance, like with my Moonlight Greatsword shooting a beam after being in a block stance. It doesn't look nice.

Adding a way to either:
A: Blacklist items from having a custom "use" animation in the config, or
B: Customize the animation used during the "use" method, like using the swords guard stance (which looks better with some weapons) or using the trident one with large spears. This would help greatly.

I could always make the weapons use the sword type instead, but I'd like to have their moves vary instead of all being the same at varying attack speed. You could also make the weapons check for the vanilla UseAction/UseAnim enum and give a custom animation based on that, since a lot of my weapons use the `UseAction.SPEAR` for their vanilla animation when charging their abilities.

Also adding a variable in the datapack API whether the weapon can or cannot be in the offhand without it relying on the weapon type would be nice. One weapon I have uses the trident weapon type, but this makes it's ability (which can only be used in offhand) unusable. 

I am looking forward to your response.

**Comment by mariumbacchus** [comment]
Update: I recently updated my mod to 1.20.1, and now Epic Fight mod breaks right click abilities yet again. Adding a way to blacklist items from having their right click abilities/functionalities overwritten would be the best approach, especially for other mods too.

**Comment by guivnf** [comment]
> Update: I recently updated my mod to 1.20.1, and now Epic Fight mod breaks right click abilities yet again. Adding a way to blacklist items from having their right click abilities/functionalities overwritten would be the best approach, especially for other mods too.

Hey, sorry to hear about this issue. Changes were made there so me could accommodate a new change in how weapon types are handled. In our latest update we allow users to import animations and make their own move sets through a datapack and resourcepack. You could instead make your own moveset and prevent it from breaking in the future all together now, we have 3 videos in our Discord server and a 4th one incoming with all details about how to use the in game editor. Our wiki is currently outdated but we do expect a lot of changes in the future

**Comment by mariumbacchus** [comment]
Thanks for the reply, the videos were very eye-opening. I had no idea there was a builtin datapack editor like that until now, very well made at that. If you could add those videos to the wiki and/or update it, that would be great. I don't usually go looking in discords right away when I see there is a wiki for an api like yours, so updating it would be appreciated.
