### ISSUE TITLE
[Bug|Crash]: Import Animations "Phases" Bug

### ISSUE THREAD

**Issue by qVoidreaver** [Yesssssman/epicfightmod#1745]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [x] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

  Version 20.8.7
  
  The video shows what happened:
  
https://github.com/user-attachments/assets/2527615c-5943-433d-ad5e-05c6e9671b21

 When you save, one of the two will happen: What occurred during the video (crash); Save Failure (the other thing that can occur).
 
  If the game crashes, you will be forced to restart the game (if using Paxi) to reload the Resource Pack of the new movement or the old ones that have already been imported.
  You can make a small comparison of the movements in the video with those in this image after the Crash (Not Enough Crashes didn't let the game close):
  
  
![image](https://github.com/user-attachments/assets/3cdae796-5b10-4b18-8189-a75855745402)

Oh, I can't forget the log crash that occurred during the video: bytebin.lucko.me/9NjzbAEDA4

  

### Steps to Reproduce

 Watch the attached video

**Comment by qVoidreaver** [comment]
Ah, the "Phases" is by selecting "attack animation", I forgot to mention.

**Comment by Yesssssman** [comment]
First, you can't save attack animations without filling those elements under Phase.
Second, _Importing_ animations doesn't mean it actually reloaded in Minecraft's asset system. You always have to reload after creating a new pack.

And lastly, I didn't get the crash after I followed the video you sent me. Could you test it without any mods installed?

**Comment by qVoidreaver** [comment]
> First, you can't save attack animations without filling those elements under Phase. Second, _Importing_ animations doesn't mean it actually reloaded in Minecraft's asset system. You always have to reload after creating a new pack.
> 
> And lastly, I didn't get the crash after I followed the video you sent me. Could you test it without any mods installed?

You're right that the crashes are related to the mods. Now, there is a case in this video where the "phases" delete themselves and don't want to be saved:


https://github.com/user-attachments/assets/6301f193-c91b-462c-8814-62f03c68224f



ps: I know I need to provide information for them to be saved correctly, but even if I do, they still do the same thing as in the video. If you do the same procedure as in the video and enter the information correctly, they will be saved and if you go to "imported animations" again, the phases will be deleted and you can see the message (when trying to save again) in the image:

![image](https://github.com/user-attachments/assets/f8a5e64e-feae-4266-8ef6-142c100a55ca)

**Comment by Yesssssman** [comment]
Thanks, they're all fixed and I also enhanced the error message screen a bit
![image](https://github.com/user-attachments/assets/96c08464-1da0-43d3-aa82-4d543dea2fc8)
