### ISSUE TITLE
[Bug|Crash]: Stuttering on Ender Dragon walking animation

### ISSUE THREAD

**Issue by 29Raptors** [Yesssssman/epicfightmod#1747]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I have recently experienced several issues with the ender dragon on versions of EF above 20.7.4, namely the head seems to be crooked most of the time, as well as noticeable stuttering on the legs during it's walking animations.

### Steps to Reproduce

Comparison of ender dragon animations on versions 20.7.4(top), and 20.8.8(bottom)

https://github.com/user-attachments/assets/a83b14e0-d2db-43b4-9486-82028c4aee23

https://github.com/user-attachments/assets/c80c8c69-ae90-4c36-bb02-193bd0867a27

**Comment by Yesssssman** [comment]
Fixed in 20.8.9
