### ISSUE TITLE
[Bug|Crash]: Skill Editior glitched

### ISSUE THREAD

**Issue by Johndoe14185** [Yesssssman/epicfightmod#1749]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.7

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

When I tried to apply the skill I learned, the skill icon deviated from its position, this issue is found in the latest version.

### Steps to Reproduce

![2024-08-11_00 30 14](https://github.com/user-attachments/assets/d0ee3046-a0ee-43f0-a973-af3fa90fca43)

**Comment by Yesssssman** [comment]
You're using the old texture of skill book screen. Update your resource pack first

**Comment by Johndoe14185** [comment]
it worked! my thx.

**Comment by Johndoe14185** [comment]
> You're using the old texture of skill book screen. Update your resource pack first

it worked! my thanks.
