### ISSUE TITLE
[Bug|Crash]: camera problem when playing animation of hit on horse

### ISSUE THREAD

**Issue by zireaelqqq** [Yesssssman/epicfightmod#1750]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

camera problem when playing animation of hit on horse

### Steps to Reproduce

https://discord.com/channels/955784714264932362/988551886779088957/1269376898668957746 
[Архив ZIP - WinRAR.zip](https://github.com/user-attachments/files/16571890/ZIP.-.WinRAR.zip)

**Comment by Yesssssman** [comment]
I can't access the link

**Comment by zireaelqqq** [comment]
I dropped the video in the archive, just watch it

**Comment by zireaelqqq** [comment]
Or just sit on the horse and try to hit a couple of times while moving the camera from side to side

**Comment by Yesssssman** [comment]
Fixed in 20.8.9
