### ISSUE TITLE
[Suggestion]: Attack Correction and Impact/Knockback

### ISSUE THREAD

**Issue by qVoidreaver** [Yesssssman/epicfightmod#1752]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

 

https://github.com/user-attachments/assets/222e45da-102e-44df-a5b1-5af249af08fc

 
 I don't know if "attack correction" is the right term to use, but the video explains what I mean. I'm trying to make the hitboxes more realistic, but the jump is so big to give the attack range that the hit just doesn't hit. The suggestion itself? A way to disable this or an improvement to the mechanics.

https://github.com/user-attachments/assets/cfcafaaa-b0a0-495c-993a-84836b5a1b01

 As for that other video, it's related to the impact/repulsion the weapons are causing, isn't that a bit too strong? Maybe that's my point, but the video isn't just about that, it's also about the immense repulsion it's causing to a mob that doesn't have a small hit animation, which ends up becoming a safe attack at times, causing the dagger to push the target so that its hit doesn't hit (the dagger has 1 impact). I remember that this didn't happen in past versions (prior to this new one that has been receiving updates)

**Comment by Yesssssman** [comment]
It's quite hard to understand what's going on in your first video. And I also have no idea what you want to do by _make the hitboxes more realistic_. There are some options to solve the issue of the first video, such as correcting the contact time or widening your hitbox toward the front.

And yeah, I understand the knockback system is wonky for animated battle. I'll definitely change the mechanism in the future somehow.

**Comment by qVoidreaver** [comment]
> É muito difícil entender o que está acontecendo em seu primeiro vídeo. E também não tenho ideia do que você quer fazer _ao tornar as hitboxes mais realistas_. Existem algumas opções para resolver o problema do primeiro vídeo, como corrigir o tempo de contato ou ampliar sua hitbox para a frente.
> 
> E sim, eu entendo que o sistema de knockback é instável para batalhas animadas. Eu definitivamente vou mudar o mecanismo no futuro de alguma forma.

  "Making the hitboxes more realistic" would be in the sense of the weapon I'm using.

 For example, in the video, I'm using a scythe, so I made your hitbox related to the blade of a scythe. So, what happens in the video is that the advance to hit the attack was so great that the blade is passing behind the zombie, and that's why the attack isn't hitting (although the visual looks like the blade is passing in front of it). In this sense, "making the hitboxes more realistic" would mean not hitting the zombie with the handle of the scythe.

 But anyway, it's just an idea, if it doesn't bother you or anything, no problem. I think my main point would be the Knockback issue, which you yourself said you'd like to change in the future.

 Thanks for your support.
