### ISSUE TITLE
[Bug|Crash]:  The chest plate completely blocks the view with some weapons in hand

### ISSUE THREAD

**Issue by zireaelqqq** [Yesssssman/epicfightmod#1753]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

can you add an option to turn off armor/player display in first person? And leave only  animation of weapons and shields

### Steps to Reproduce

https://github.com/user-attachments/assets/ebdf6213-c48d-47a2-800b-37617d9e907c

**Comment by Yesssssman** [comment]
Fixed in 20.8.10
