### ISSUE TITLE
[Bug|Crash]: Crash with new version

### ISSUE THREAD

**Issue by lostopkk** [Yesssssman/epicfightmod#1754]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.9

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I have an old modpack that was with the old version of epic fight and it works normally, but when I update to the new version it doesn't work
Old version is 20.7.4

### Steps to Reproduce

1. Modpack works normally
2. Update new version
3. Crash when initialize

[crash-2024-08-12_08.49.30-fml.txt](https://github.com/user-attachments/files/16581140/crash-2024-08-12_08.49.30-fml.txt)
[latest.log](https://github.com/user-attachments/files/16581145/latest.log)

**Comment by Yesssssman** [comment]
Crash with epicfight parcool compat: https://www.curseforge.com/minecraft/mc-mods/epic-compat-parcool

Do not use the mod it needs to be updated
