### ISSUE TITLE
[Bug]: Barrier emits particles when slammed.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1755]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.9

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Barrier emits particles when slammed.

### Steps to Reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Create a new world or select one with cheats enabled;
3. Switch your gamemode to creative;
4. Give yourself a barrier. This can be done by using a command or by grabbing it from "Operator Utilities" creative tab;
5. Build something with barriers. Don't forget, you must be able to crush these blocks;
6. Grab Epic Fight weapons (e.g. Greatsword) or learn skills, that allow you to slam the ground (e.g. "Meteor Slam");
7. Slam the barrier!

### Expected Behavior

Barrier **does not** emit particles when slammed.

### Notes

This bug only affects Epic Fight for 1.20.1, because since 1.19.3 [22w42a] barriers [no longer emit block particles when broken](https://minecraft.wiki/w/Barrier#History).

### Video

https://github.com/user-attachments/assets/6e3784db-8d25-4aad-b428-9521d5486916

**Comment by guivnf** [comment]
I have no idea how you are able to keep finding these bugs, cuz they are all too specific, but thanks for reporting, will hopefully be fixed soon.

**Comment by Raccffy** [comment]
> I have no idea how you are able to keep finding these bugs, cuz they are all too specific, but thanks for reporting, will hopefully be fixed soon.

**Players are unpredictable. This is it!**

My goal is to make Epic Fight as stable as possible, even in very unexpected behaviors. The more stable it is, then it is less likely to break in the future.

**Comment by Yesssssman** [comment]
Fixed in 20.9.1
