### ISSUE TITLE
[Bug]: Some Epic Fight weapons have size deviation when dropped.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1756]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.9

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Some Epic Fight weapons have size deviation when dropped.

### Steps to Reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Create a new world or select one with cheats enabled;
3. Switch your gamemode to creative;
4. Give yourself some weapons from Minecraft and from Epic Fight;
5. Drop them on the ground.

### Expected Behavior

Epic Fight weapons are equal with Minecraft items in size.

### Observed Behavior

Some Epic Fight weapons are either too big or too small compared to Minecraft items.

### Video

https://github.com/user-attachments/assets/2c17d893-f949-493d-8fde-7656535fd2c6

**Comment by guivnf** [comment]
Same as #1757
