### ISSUE TITLE
[Bug]: Some Epic Fight weapons are mirrored inside an Item Frame.

### ISSUE THREAD

**Issue by Raccffy** [Yesssssman/epicfightmod#1757]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight 20.8.9

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Some Epic Fight weapons are mirrored inside an Item Frame.

### Steps to Reproduce

1. Launch Minecraft 1.20.1 with latest version of Epic Fight and with recommended Forge version;
2. Create a new world or select one with cheats enabled;
3. Switch your gamemode to creative;
4. Grab an item frame;
5. Choose affected Epic Fight weapon from the list below;
6. Place an item frame and put inside your weapon.

### Affected weapons

- Uchigatana;
- Tachi;
- Longsword.

### Expected Behavior

All weapons are directed to the right.

### Observed Behavior

Affected weapons are directed to the left.

### Video

https://github.com/user-attachments/assets/57b9932e-63bd-4e0f-a9fc-fee0458bbda6

**Comment by guivnf** [comment]
@Yesssssman you don't need to worry about this issue as all weapon GUI icons will later be replaced by their 16x16 texture variants, which i'm still working on. Don't even bother checking where exactly this rendering issue happens, most likely a forge inconsistency with higher res textures

**Comment by Yesssssman** [comment]
Fixed in 20.9.3
