### ISSUE TITLE
[Bug]: The second phase of the imported animations was not saved.

### ISSUE THREAD

**Issue by GLMaster19** [Yesssssman/epicfightmod#1758]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Hello, dear developers.
I and one other user of Epic Fight mod have encountered a problem that when importing an attack animation with two phases, the second phase is not saved.
For clarity, I would like to point out that the first phase is called "phase0" and the second phase is called "phase1". It is the second phase that is not saved.
I personally encountered this problem both on the old version of EF, from your Patreon, and after upgrading to the new one. 
I imported animations from the Dual Greatswords mod, namely animations dual_auto_1 and dual_auto_3 - just they have two phases of attack.
When exporting these two animations with fully prescribed two phases, in the .json file at the path datapack_name/data/animations_name/animmodels/animations/biped (and in both files) is not prescribed the second phase, only one:

"constructor": {
    "invocation_command": "(0.25#F,dualgreat:biped/greatsword_dual_auto_1#java.lang.String,epicfight:entity/biped#yesman.epicfight.api.model.Armature,[(0.0#F,0.0#F,0.2#F,0.4#F,0.45#F,0.45#F,OFF_HAND#net.minecraft.world.InteractionHand,epicfight:entity/biped.Tool_L#yesman.epicfight.api.animation.Joint,(3#I,0.5d#D,0.8d#D,1.0d#D,0.0d#D,0.0d#D,-1.0d#D)#yesman.epicfight.api.collider.MultiOBBCollider)]#yesman.epicfight.api.animation.types.AttackAnimation$Phase)#yesman.epicfight.api.animation.types.BasicAttackAnimation"

Up there is a string of only one imported animations.

When rewriting datapack and checking the imported animations for the presence of the second phase in the editor, it turned out that the second phase is missing, which is confirmed by the .json file, and more specifically - the line above.

![before_export_first_anim](https://github.com/user-attachments/assets/59abc189-f76e-4770-b3f4-52b671dcfc33)
![after_export_first_anim](https://github.com/user-attachments/assets/745bc89c-1432-4da4-acc5-e716d7c8f18c)
![before_export_second_anim](https://github.com/user-attachments/assets/e477d158-e82a-4336-9dd8-9d9c5aa69e15)
![after_export_second_anim](https://github.com/user-attachments/assets/f643b3db-e769-40aa-b0cb-ac0db75bd937)

Photos is "before-after exporting", for two of those animations.

Here is a datapack, that contains both of this animations +moveset + capability to a weapon from a Epic Knights.

[zwei_dual.zip](https://github.com/user-attachments/files/16606424/zwei_dual.zip)

Update from 15/08/2024:

Experimentally, it was found that when creating three phases, the animations can be exported once with the settings of two phases intact.
That is, you create the phases from phase0 to phase2, then prescribe each of the three phases (the settings of phase1 are the same as those of phase2, just so that the phase we need is saved), export and that's it - you have two working phases.
But, after re-exporting the datapack, the second phase of the animation disappears again, because of which it must be re-configured.
Conclusion: if you create more than one phase in the animation, one phase will not be saved.

### Steps to Reproduce

1. Import any animations, that have a two phases to deal damage.
2. Adjust it by setting all the necessary values at the two phases.
3. Export it and check the .json file for the second attack phase in the animations at the path datapack_name/data/animations_name/animmodels/animations/biped.
4. In the presence/absence of the second phase, to finally confirm the presence/absence of the problem, overwrite the same datapack and open it in the in-game editor.

**Comment by Yesssssman** [comment]
Fixed in 20.8.10
