### ISSUE TITLE
[Bug|Crash]: (MAYBE) Just Piglin Brute - Entity datapack bug.

### ISSUE THREAD

**Issue by qVoidreaver** [Yesssssman/epicfightmod#1760]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

  [New version] (28.8.9)

Here are 3 bugs related to the same entity (maybe this is happening with some other entities too)

 context: I'm making a modification to the brute piglins to improve their mechanics and make them more difficult to face, but I end up finding myself in these 3 situations:

 The first one:
 

https://github.com/user-attachments/assets/3d8a74cd-2bc8-44fe-8a09-6dec33821d01

This is related to the entity not respecting the cooldown, which in this entity is 300 (15 sec).

Now this second video:

https://github.com/user-attachments/assets/51d37a7b-70f2-4d34-b7ff-2c2b27368c58

This has to do with the fact that the entity simply doesn't want to move to attack me, it just stays put.

There's also this third video:

https://github.com/user-attachments/assets/e4bf160f-5981-4d09-b138-74c5ae2a62f4

 I'm using the old forms of data packets for entities (before this new version) and I haven't had ANY problems, except with the piglins, as you can see in the last two videos (which are the old data packets). In this third video, I tried using epicfight's own settings feature and the piglin simply didn't appear, but it's there.
 
 
  NOTE: There is NO other mod apart from epicfight. I have no idea if the same thing is happening with the other vanilla mobs that receive modifications, but I must add that I tried to modify the Zombie and the moment it noticed my presence the game crashed.

### Steps to Reproduce

 I just created a datapack of a piglin brute

**Comment by Yesssssman** [comment]
Please post your datapack

**Comment by qVoidreaver** [comment]
> Please post your datapack

[piglin.zip](https://github.com/user-attachments/files/16650002/piglin.zip)

**Comment by Yesssssman** [comment]
Fixed in 20.9.1
