### ISSUE TITLE
[Suggestion]: Compatibility with Amendments first person torch/lantern

### ISSUE THREAD

**Issue by polykatt** [Yesssssman/epicfightmod#1761]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

https://curseforge.com/minecraft/mc-mods/amendments

### Minecraft Version

1.20.1

### What's your suggestion?

The Amendments mod adds 3D holding animations for torches, lanterns and candles. These are visible in first person and third person. However, these animations do not work with epic fight. Would it be possible to make these compatible or maybe even replicate the animations for epic fight?

**Comment by guivnf** [comment]
You can already kinda do that, just create a weapon type and add your custom lantern holding animations to it. You don't even need amendments for that, only epic fight.

**Comment by Yesssssman** [comment]
Epic Fight doesn't support vanilla animation. You can configure options to display vanilla animations for specific items.
