### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by 5A93** [Yesssssman/epicfightmod#1763]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

AzureLib

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Version epicfight-forge-20.8.9-1.20.1 is incompatible with azurelib-neo-1.20.1-2.0.30, I know someone had already said the newest version of Epic Fight only compatible with the newest azurelib, but I checked this is the newest version
Maybe something else caused it.
[minecraft.log](https://github.com/user-attachments/files/16641804/minecraft.log)

### Steps to Reproduce

1.Use both version of mods
2.Open the game

**Comment by Yesssssman** [comment]
This is not a crash from epic fight. It's from crittersandcompanions

**Comment by 5A93** [comment]
> 这不是史诗战斗中的崩溃。这是来自crittersandcompanions

I'm so sorry, somehow I summit the wrong log, I was in the bad shape. This is the true log
[minecraft.log](https://github.com/user-attachments/files/16646473/minecraft.log)

**Comment by Yesssssman** [comment]
The crash is from MCDoom mod not from epic fight

**Comment by 5A93** [comment]
> 崩溃是由 MCDoom mod 引起的，而不是由 epic fight 引起的

Yes I figured it out. Thanks for your time
