### ISSUE TITLE
[Bug|Crash]: The game crashed whilst mouseclicked event handler Error: java.lang.IllegalArgumentException: Can't find animation named: wom:biped/combat/enderblaster_twohand_dash

### ISSUE THREAD

**Issue by Chance567789cmc** [Yesssssman/epicfightmod#1764]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I am unable to Load or create any worlds with create mod

### Steps to Reproduce

Install Weapons of Miracle Version 20.1.8.5.1 And Epic Fight version 20.8.9-1.20.1
Load A World
See if it works

**Comment by Chance567789cmc** [comment]
i made a mistake, the crash report For this complaint read "The game crashed whilst mouseclicked event handler
Error: java.util.NoSuchElementException: No animation with registry name wom:biped/combat/katana_dash"

**Comment by Yesssssman** [comment]
Not an epic fight side issue
