### ISSUE TITLE
[Bug]: Vindicators show their weapon even without being aggroed 

### ISSUE THREAD

**Issue by Thisplaysnames** [Yesssssman/epicfightmod#1765]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

just a small visual bug, ever since the 8.2 update vindicators show their main hand weapon even without being aggroed which causes and odd look for it, especially with texture packs or making a vindicator hold a custom weapon 

### Steps to Reproduce

![2024-08-17_14 27 05](https://github.com/user-attachments/assets/014076d0-8576-4948-8c94-416644630904)
![2024-08-17_14 27 39](https://github.com/user-attachments/assets/168de606-dc49-4b14-a01d-43c928f369c8)

**Comment by Yesssssman** [comment]
Fixed in 20.8.10
