### ISSUE TITLE
[Bug|Crash]:  incompatibility with Irons spellbooks necromancers

### ISSUE THREAD

**Issue by Archongaming** [Yesssssman/epicfightmod#1766]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Specifically irons spells and spellbooks

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

im sorry i cant pull the crash report right now but ive narrowed it down to an interaction between epic fight and irons spellbooks, they refuse to even consider the idea of fixing it but due to epic fight, irons spellbooks necromancer npcs CTD when trying to summon undead

### Steps to Reproduce

No others mods just irons spellbooks and epic fight.spaen a necromancer and engage them in combat. when the necromancer attempts to summon undead allies the game will crash

**Comment by Yesssssman** [comment]
Please attach the log when you can

**Comment by Archongaming** [comment]
[crash-2024-08-18_16.59.32-client.txt](https://github.com/user-attachments/files/16647237/crash-2024-08-18_16.59.32-client.txt)

**Comment by Archongaming** [comment]
Sorry I know im using alot of mods this is for a modpack, for now I've disabled necromancers from spawning using badmobs but let me know if this can be fixed :)

**Comment by Archongaming** [comment]
Oh i just fixed it, this occurred specifically when an epic fight mob patch is added to the entities summoned skeleton and summoned zombie

**Comment by Archongaming** [comment]
is there a way to have it fixed so modpack creators can use epic fight animations with the necromancer summoned undead

**Comment by Yesssssman** [comment]
yeah I will fix this in the next update, it's because geckolib entities are not compatible with mob capabilities

**Comment by Yesssssman** [comment]
Could you share your datapack? I want to check if it fixed in my side

**Comment by Yesssssman** [comment]
Well nvm, it has been fixed in 20.9.1
