### ISSUE TITLE
[Bug]: incompatibility with alexscaves 

### ISSUE THREAD

**Issue by latiaotiao** [Yesssssman/epicfightmod#1767]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

it break some particles like alexscaves galena gauntlet's magnetic effect 

### Steps to Reproduce

epicfight20.8.10    alex's caves1.1.4 ：use galena gauntlet control sword ，magnetic chain and sword model can't display

**Comment by latiaotiao** [comment]
I don't know if it's the same issue,  the skill effect of Ruine in WOM is not visible

**Comment by Yesssssman** [comment]
#1743

**Comment by survival888** [comment]
you mean the Weapons of Miracles addon right no that does not matter i tested it with and without that one installed still has the same glitch
