### ISSUE TITLE
[Suggestion]: Custom Weapon Type：Two hand weapon shouldn't be put in off-hand slot

### ISSUE THREAD

**Issue by latiaotiao** [Yesssssman/epicfightmod#1769]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

Weapons that use a custom weapon type, which is two-handed and can still be placed in the off-hand slot

**Comment by Yesssssman** [comment]
![image](https://github.com/user-attachments/assets/c3148396-bc4f-4a3c-9dbf-a170a5e597ce)
Added a new element in weapon type tab. I appreciate your suggestion.
