### ISSUE TITLE
[Bug|Crash]: broken armor_stand

### ISSUE THREAD

**Issue by NilsCoy** [Yesssssman/epicfightmod#1772]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

![image](https://github.com/user-attachments/assets/7fde4876-6908-4212-8b4a-fca038ffbebb)

In the new version of the mod, models have apparently been updated and armor_stand has also been affected. For some reason, they cause crashes and incorrect installation of items.

On my server, I use a plugin to add model creatures: Model Engine, which creates mobs based on armor_stand. Before that, I used the mod version 20.7.4 and no problems were observed, however, when updating to a new version of the mod, all the models began to overlap with armor_stand differently, and the object rotation function disappeared from them. Perhaps this is due to the new shader for models

In general, I would just suggest rolling them back, I don't think it affects anything in particular.

### Steps to Reproduce

I just changed the mod version and the forge version on my server. After that, the models created on armor_stand were broken.

**Comment by Yesssssman** [comment]
Please try this with the animation shader turned off.

**Comment by NilsCoy** [comment]
The animation shader is disabled by default. I also checked how it behaves with on and off, nothing changes. The latest version 20.8.10 also has this bug, but everything is fine on 20.7.4.

**Comment by guivnf** [comment]
> The animation shader is disabled by default. I also checked how it behaves with on and off, nothing changes. The latest version 20.8.10 also has this bug, but everything is fine on 20.7.4.

we still can't reproduce this issue.... You just said you are using a hybrid loader (which we don't support), with plugins, which we can't even access their source code it seems, and with 0 info on how they work or how they should be working. A picture, with 0 information will get you nowhere.
