### ISSUE TITLE
[Suggestion]: more options of show attributes 

### ISSUE THREAD

**Issue by latiaotiao** [Yesssssman/epicfightmod#1775]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

The current configuration can only hide weapon's attributes in tooltip，The armor's attributes  are still shown. Considering that some attributes are important.It's best to configure each attribute separately.

**Comment by Yesssssman** [comment]
Armor attributes are stored exactly in the same place where vanilla attributes are stored, unlike weapon attributes which are stored in item capability exclusive for epic fight. And I think that is too much
