### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Gastlyspear** [Yesssssman/epicfightmod#1776]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Epic Fight (epicfight) has failed to load correctly
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

### Steps to Reproduce

These message shows when Minecraft start
![error](https://github.com/user-attachments/assets/879c7594-7e58-47a0-9943-063cdd4f8cb4)

**Comment by M6FGR** [comment]
Might be a mod incompatibility,Try removing mod by mod until it runs correctly

**Comment by guivnf** [comment]
> Might be a mod incompatibility,Try removing mod by mod until it runs correctly 

Could you please not reply to issues in GitHub? I've seen you giving some weird recommendations and closed issues that are marked as policy violation shouldn't receive further replies.

**Comment by M6FGR** [comment]
My bad
