### ISSUE TITLE
[Bug|Crash]: Entering combat mode crashes my game

### ISSUE THREAD

**Issue by Weezow** [Yesssssman/epicfightmod#1777]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I'm testing a modpack which was working fine until I had to update every mod in it to the latest version. Now, when I start a new world, I can join and walk around no issues until I press "R" to enter combat mode and the game crashes. I'll provide both my modlist and the crash report.

Thank you very much for anything you can do.

[crash-2024-08-23_22.51.17-client.txt](https://github.com/user-attachments/files/16733920/crash-2024-08-23_22.51.17-client.txt)
[modlist.txt](https://github.com/user-attachments/files/16733921/modlist.txt)

### Steps to Reproduce

Pressing "R" will immediately crash my game.

**Comment by Yesssssman** [comment]
You have an outdated resource pack. Remove it to avoid the crash.
