### ISSUE TITLE
[Bug|Crash]: epic fight, weapons of miracle, epic fight -battle arts all critical errors appearing

### ISSUE THREAD

**Issue by death12092** [Yesssssman/epicfightmod#1778]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

may be embedium but idk at this point

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

![image](https://github.com/user-attachments/assets/e06490ea-c45e-4504-90ac-aae77baeb9da)
now i know i have alot of mods but if i enable the TexTrue's embedium options embediun complains so  disabling was the only option and then epic fights just wouldn't load and show the critical error every time

### Steps to Reproduce

[knights and magic-broke.zip](https://github.com/user-attachments/files/16737435/knights.and.magic-broke.zip)

**Comment by guivnf** [comment]
Don't fucking report issues that aren't from epic fight here.

**Comment by dieeeeeeeego** [comment]
People just wont read the support policy
