### ISSUE TITLE
[Bug]: Skin Layers 3D mod adds duplicate model when spawning/respawning when in 3rd person

### ISSUE THREAD

**Issue by Jetpack-Cat** [Yesssssman/epicfightmod#1779]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Skin Layers 3D (1.6.7-mc1.20.1)

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Epic Fight Forge 20.9.1-1.20.1

When first spawning or respawning and the camera is in 3rd person, a duplicate of your player model will be created next to your actual player model. The duplicate will disappear within a few seconds.

If I disable Epic Fight mod, this issue doesn't happen.

![2024-08-25_10 37 25](https://github.com/user-attachments/assets/2e1634dd-1730-49d3-8d4a-95574c8d1a75)

[latest.log](https://github.com/user-attachments/files/16741525/latest.log)

### Steps to Reproduce

Use both epic fight and Skin Layers 3D mod together, and make it so when you spawn or respawn you're in 3rd person perspective.

**Comment by Yesssssman** [comment]
This is not a bug but what I intended because player model has to be initialize once before bake 3d skin layer cubes
