### ISSUE TITLE
[Bug|Crash]: Epic Fight has Failed to Load Correctly

### ISSUE THREAD

**Issue by ExGingerino** [Yesssssman/epicfightmod#1785]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I'm currently running Epicfight alongside a few mods- I'll list all mods in the pack at the bottom of this section. 
The error log reads :
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An Unexpected Critical Error was encountered.
This happens as soon as I boot up Minecraft, before I even get a chance to see the main menu.

Mods in the modpack [A-Z]
-AppleSkin
-Architectury API [Fabric/Forge/NeoForge]
-Balm [Forge Edition
-Better Combat [Fabric + Forge]
-Cloth Config API [Fabric/Forge/NeoForge]
-Clumps
-Embeddium
-Epic Fight
-Epic Fight EX Capabilities
-Epic Fight Impactful
-Epic Fight Mod and Other Mods Weapons Compatibilities
-Epic Knights: Shields, Armor, and Weapons [Fabric/Forge/NeoForge]
-Essential Mod
-Gecko Lib
-Jujutsu Combat
-Jujutsu Craft [Sorcery Fight]
-Jujutsu Kaisen GT 2
-JEI
-Load My F***ing Tags
-Lootr [Forge + Neoforge]
-Mouse Tweaks
-Physics Mod
-Player Animator
-Realm RPG: Pots + Mimics
-RPG-hud [Forge]
-Simply Swords [Fabric + Forge]
-Sound Physics Remastered
-The Lost Cities
-Traveler's Backpack
-Waystones
-Waystones Teleport Pets
-Xaero's Minimap
-Xaero's Minimap + World Map Waystones Compatibility
-Xaero's World Map

### Steps to Reproduce

I just boot up the mod with this modpack, everything is fully up to date, and when I get to the main menu it just gives me this error message. I really don't know what to do from here.
![image](https://github.com/user-attachments/assets/9b2eb767-ec32-4531-9a47-0340c398c340)
A snip of the error message [The only error experienced]

[modproblem.txt](https://github.com/user-attachments/files/16793167/modproblem.txt)
This is the Log of the problem. I'm not a programmer, so 98% of this is gibberish to me. [The 2% is dyslexia beating my ass]

[crash-2024-08-29_02.38.12-fml.txt](https://github.com/user-attachments/files/16793319/crash-2024-08-29_02.38.12-fml.txt)
This is the Crash report. Report to the former comment on why I need help with this.

**Comment by Yesssssman** [comment]
Epic Fight addon is outdated
