### ISSUE TITLE
[Bug|Crash]: Crash when dying

### ISSUE THREAD

**Issue by Mqony** [Yesssssman/epicfightmod#1786]
### Please check if a similar issue has already been reported.

- [x] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Game crashes when dying
[crash-2024-08-29_01.24.56-client.txt](https://github.com/user-attachments/files/16796107/crash-2024-08-29_01.24.56-client.txt)
[latest.log](https://github.com/user-attachments/files/16796109/latest.log)

### Steps to Reproduce

Just Die

**Comment by Yesssssman** [comment]
Please provide more information on how to reproduce this crash. This ain't happen in pure epic fight environment.

**Comment by Mqony** [comment]
I did the /kill command and this crash happened

**Comment by Yesssssman** [comment]
I need any useful information, not a way to die.

**Comment by Yesssssman** [comment]
Specify the mod or resource pack causing this issue or even a piece of footage describing how I can reproduce this issue in my side

**Comment by Mqony** [comment]
I found that the crash only happens when holding a weapon from the Weapons of Miracles mod then doing the /kill command. I don't know if it's something you can fix or if it's an issue on WoM's side.

**Comment by Yesssssman** [comment]
What was the name of the weapon? And do you use any resource pack?

**Comment by Mqony** [comment]
The Antitheus, and I don't use any resource packs

**Comment by guivnf** [comment]
You have way too many mods, and you are using sinytra connector, which tries to load fabric mods, which we don't advise using along side epic fight.

**Comment by MistifyedOne** [comment]
Nice, so were avoiding valid issues and closing them down because you don't feel like fixing it. Great work dev team!

**Comment by guivnf** [comment]
> Nice, so were avoiding valid issues and closing them down because you don't feel like fixing it. Great work dev team!

More like you can't read our report policy. We explicitly say you need to narrow down the issue by yourself first, and i told you all the reasons as to why i'm not gonna continue further having this issue open. I'm sorry if you can't read or something, or you are simply too lazy and want everything to be fixed for you instead of actually learning how to handle them on your own, but that's simply not how modding works.
