### ISSUE TITLE
[Bug|Crash]: Player/entity's skin rendering error

### ISSUE THREAD

**Issue by abc123litianyu** [Yesssssman/epicfightmod#1789]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

When you install the "Epic Fight" mod, the skin will look like this
![屏幕截图 2024-08-30 141809](https://github.com/user-attachments/assets/5ee4be9b-3c75-4057-ac63-9c0e1cb314ca)
:

### Steps to Reproduce

1. Install Minecraft JE 1.20.1 and the corresponding latest forge in the launcher
2. Install the "Epic Fight" mod
3. Launch the game
4. Create a new world
5. Open up the world
6. Then you will be able to see the problem I described: Player/entity's skin rendering error

**Comment by guivnf** [comment]
What even is Minecraft JE
+you clearly have more than just epic fight there lol

**Comment by Mikaaah** [comment]
> What even is Minecraft JE +you clearly have more than just epic fight there lol

JE Is Java Edition lol

**Comment by guivnf** [comment]
> > What even is Minecraft JE +you clearly have more than just epic fight there lol
> 
> JE Is Java Edition lol

how was i supposed to know lmao, who tf goes by Minecraft JE

**Comment by PlayerRager** [comment]
I think I found the issue, it's due to shaders for me it was an option in the shaders I was using called "Parallax Occlusion Mapping" I turned it off and it fixed the skin
