### ISSUE TITLE
[Bug|Crash]: Any custom projectile entity when coming in contact with lupus (wolf wom) is crashing my server

### ISSUE THREAD

**Issue by Sidabyss** [Yesssssman/epicfightmod#1790]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Weapons of miracle 

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Basically I tried shooting this fireball projectile from ignition staff of Choup's Drakvyrn mod and the weapon itself was fine but when I shot the projectile. As soon as the custom fireball projectile hit lupus. My server crashed.

The same thing happened when I tried to shoot any other projectile which was "not vanilla" from other mod.

Crash report with mod1 -> https://mclo.gs/aFPbaAn

Crash report with mod2 ->https://mclo.gs/Wd5hQVf

### Steps to Reproduce

Please can you fix this issue...

(Idk what steps to write here)
Crash report with mod1 -> https://mclo.gs/aFPbaAn

Crash report with mod2 ->https://mclo.gs/Wd5hQVf

**Comment by guivnf** [comment]
Not our problem, report this to the wom repository

**Comment by Sidabyss** [comment]
how and where do i do report it?

**Comment by Sidabyss** [comment]
any idea how i can contact raescar

**Comment by GLMaster19** [comment]
> any idea how i can contact raescar

He has discord, you can write him report about this bug in DM. But, please, be informative. Try to include all information in one or two messages - he is very busy right now.
