### ISSUE TITLE
[Suggestion]: WoM Solar weapon heat

### ISSUE THREAD

**Issue by MAXO1111111** [Yesssssman/epicfightmod#1791]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

Really love the mod I have for a year now so keep up the good work. I think the new weapon solar is really cool but I think the heat buildup needs a little buff. Currently doing a full combo (while hitting all the timed moves) seems to fill the bar very slowly. 8 combos with all timed attacks hits fills it to 100% (this is against a dummy so mobs would die before then and you would need to find a new mob and the weapon would cool down a little). but i feel like its a little slow on heat buildup. Usually performing half of the combo string pretty much kills anything. charging it to 50% takes a lot of effort which is too much compared to the other weapon ability rates. also when you switch the weapon it fully resets the heat bar to 0% heat which does not help as using the innate abilities drain your hunger for some reason not sure if this was on purpose or a bug or mod confliction but cause your hunger drains it forces you to eat something and then it resets to 0% again and cause the bar charges slowly having it reset to 0% after needing to eat some food to regen hp is very annoying causes the weapon is basically unusable in survival cause of hunger drain and needing to swap the weapon out in general. Overall I like the concept of the weapon but the heating takes way too long to even consider using the special moves and different forms unless you are fighting a whole army of mobs which is not a common occurrence in survival and you would still need to switch the weapon to eat food, resetting the heat to 0%..

ways to possibly offset this

- tune the heat effect to build a little faster.
- make the enchantment fire aspect give Solar a buff so that maybe heat builds faster or passive heating. or have normal melee attacks with fire aspect build heat when it is enchanted.
- make the heat bar shorter, requiring less heat to activate the moves.
- Solar also does not take like any stamina to use, so maybe adding a way to give up stamina to heat the weapon faster is an option.
- Take away the hunger drain completely its dumb cause switching the weapon resets it to 0% heat and the weapon itself builds heat so slow when you're finally  at 100% after fighting you need to eat thus resetting it to 0% after doing nothing.
- give it invincibility frames when performing the quicktime attacks cause the weapon swings slow being a greatsword mobs very easily hit you in the middle causing you to stun making the timed attacks very rare to execute due to stun after swings.
- for the obcuridad form, when you kill an enemy and it dies, recover some heat back boosting the time for it to be active as long as you are killing enemies fast enough. Still have it set to red though so it  is always draining still.
- crematorio attack do more damage it's a little lacking compared to the other 2 
- another issue is when enchanted with sharpness it pretty much kills everything before you can even perform an attack to build heat making heat buildup even slower. (1 combo chain with timed attacks and sharpness kills a ravager building only 4% heat.)

Overall i think the weapons really cool but compaired to antithisis (having a similar second form) the buildup for the heat is very slow while every other wom weapon charges there special very fast. overall really cool weapon and keep up the good work!

**Comment by Yesssssman** [comment]
Here is not an wom repository bruh
