### ISSUE TITLE
[Bug|Crash]: Gun mods not working

### ISSUE THREAD

**Issue by Skylash777** [Yesssssman/epicfightmod#1792]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/timeless-and-classics-zero

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

So I noticed that the custom walking / holding animations completely break my gun mods, and I was wondering if it was possible to completely turn off the custom walking when not equipping a supported item from the other supported sword mods. Just a config fix would be enough, or perhaps it's already there and my mind skipped on it somehow. Thanks!

### Steps to Reproduce

1. Install Both custom fights and TaCZ and their dependant mods.
2. SImply equip a gun from TaCZ
3. Notice that its broken!
4. (Might be shaders, dont know)

**Comment by BoyanShen** [comment]
Go to your epicfight-client.toml config file, and set "filter_animation = true", you should be able to use the gun when out of battle mode

**Comment by guivnf** [comment]
broken how, attach some footage

**Comment by Yesssssman** [comment]
Epic Fight doesn't support vanilla animation. You can configure options to display vanilla animations for specific items.

**Comment by Skylash777** [comment]
> Go to your epicfight-client.toml config file, and set "filter_animation = true", you should be able to use the gun when out of battle mode

Thanks so much! This instantly "repaired" the broken animations.

**Comment by Skylash777** [comment]
Oh and by the way the issue was all of the animations were broken

**Comment by xXxemoul** [comment]
don't work on 1.21.1
