### ISSUE TITLE
[Bug|Crash]: Armor is displayed on FPV

### ISSUE THREAD

**Issue by 0101a1a** [Yesssssman/epicfightmod#1793]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://modrinth.com/mod/l_enders-cataclysm

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

The issue doesn't happen when using any/latest version of **L_Ender's Cataclysm** and **Epic fight** 20.8.10.

It will happen once start using newer versions of Epic Fight (introduced in 20.9.1) and exist in 20.9.2.

It makes the first person unplayable when using some of the armor or all of them (not necessarily only the Chestplate armor).

![image](https://github.com/user-attachments/assets/48fcbc79-b8f5-4d1b-b75c-3f7e957d21f7)

I also have noticed that the armor has rendering issues even in the third person, it's less noticeable and playable however it will be noticeable to other players. The same issue happens in survival inventory. The chestplate armor will be visible when only wearing one of the armors and not all of them.

![image](https://github.com/user-attachments/assets/b786c5e3-be44-48fa-ab97-debb4527d1b9)

Also when wearing other chestplate armors from other mods,  it will render the one from cataclysm when wearing some other parts from cataclysm

![image](https://github.com/user-attachments/assets/9146611e-a328-4e36-a5b7-cc7f644d194f)

This issue in the images above also doesn't occurs in 20.8.10 and older versions.

It would be great to have an option to not show the armor in first person model without disabling first person model completely (to still have the animations of attack and all features of this mod)

### Steps to Reproduce

1. Create a new instance of Minecraft 1.20.1 with Forge (47.3.0 or newer versions) and the latest version of Epic Fight
2. Install [Cataclysm](https://modrinth.com/mod/l_enders-cataclysm)
3. Create a new world, load it, and Equip Ignitium Armor from creative mode
4. Switch to First person with First person model enabled (which is true by default without the need to change config)

![image](https://github.com/user-attachments/assets/e2203eac-50b4-40b8-a8bf-d82e22d324ca)

<details><summary>Epic Fight 20.9.2</summary>
<p>

![image](https://github.com/user-attachments/assets/b786c5e3-be44-48fa-ab97-debb4527d1b9)
![image](https://github.com/user-attachments/assets/67da1088-cc4c-4438-a132-304954ff4a02)
![image](https://github.com/user-attachments/assets/b158da10-d13c-4e78-8e49-66e37ef37f6c)
![image](https://github.com/user-attachments/assets/0dcaf121-c1a9-4357-b3ef-09a8eb259ff8)
![2024-08-31_21 22 36](https://github.com/user-attachments/assets/46147bea-2b36-4d29-b1c9-0aaf1c432e12)

</p>
</details> 

<details><summary>Epic Fight 20.8.10</summary>
<p>

![image](https://github.com/user-attachments/assets/19022b62-c86e-4394-abe4-dd85aae6f7bf)
![image](https://github.com/user-attachments/assets/458fd6a5-dc8a-4f6a-b349-a80be17c19b1)
![image](https://github.com/user-attachments/assets/be593883-59e9-44b9-b8bf-660830143c50)
![image](https://github.com/user-attachments/assets/e8c59250-02b4-4a7b-82f3-26ae01b1ef5f)

</p>
</details>

**Comment by Yesssssman** [comment]
Fixed in 20.9.3
