### ISSUE TITLE
[Bug|Crash]: Mod Incompatibility with Armors from other mods (Botania, Ice and Fire, Stalwart Dungeons, Others)

### ISSUE THREAD

**Issue by Awerthur** [Yesssssman/epicfightmod#1796]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

When using Epic Fight Version: 20.9.2, i cannot use any kind of mod armor. From Botania, to Ice and Fire / Alex Caves / Others.
I get the error as if the armor is full and get the helmet in the middle of the screen. 
![image](https://github.com/user-attachments/assets/55873a25-37b0-45c3-b396-b81bc8537d94)

### Steps to Reproduce

Just equip any chest plate from other mods like:
Alex Caves
Stalwart Dungeons
Ice and Fire
Botania

**Comment by guivnf** [comment]
#1793 duplicate
