### ISSUE TITLE
[Bug|

### ISSUE THREAD

**Issue by Undeadblender** [Yesssssman/epicfightmod#1797]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [x] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [ ] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

![image](https://github.com/user-attachments/assets/b870983c-2f06-486f-ac8b-0a1c30abbb9f)
I really need to figure this out, for some reason any time I try to make any sort of modpack, even with just epic fight, is shows my shoulder on the left even if I'm holding something, running around, or anything I try. I genuinely need this fixed I don't understand and nothing has helped, I even tried contacting mod support on the official forge discord and the person that tried to help couldn't figure it out either.

### Steps to Reproduce

the only thing I can think of is just try to make a modpack with epicfight (in 1.20.1)

just trying to load it up with the epic fight mod alone 
![image](https://github.com/user-attachments/assets/79951120-887c-4b93-afd3-6c21d1b2f06a)

**Comment by guivnf** [comment]
This is not an issue. If you want to disable that, then either just use the config to completely disable our first person model or remake idle animations for the player

**Comment by Undeadblender** [comment]
sorry im not the greatest with these kind of things, can you tell me how to do that or just how to open it?

**Comment by guivnf** [comment]
> sorry im not the greatest with these kind of things, can you tell me how to do that or just how to open it?
> 
> 

In-game, click on mods in the main menu, search for epic fight and config, there you can find your answers
