### ISSUE TITLE
[Bug|Crash]: Game crashes as I hover the mouse cursor over a DivineRPG (mod) weapon

### ISSUE THREAD

**Issue by notHeiru** [Yesssssman/epicfightmod#1798]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight and DivineRPG

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

[crash-2024-09-04_13.53.23-client.txt](https://github.com/user-attachments/files/16861495/crash-2024-09-04_13.53.23-client.txt)

### Steps to Reproduce

Hovering the mouse cursor over a DivineRPG weapon (Halite Bow did it for me, and several other weapons) causes the game to crash.

**Comment by notHeiru** [comment]
Only two mods are being used: DivineRPG and Epic Fight.
The crash does not happen if I use DivineRPG alone.

Edit 1:
Additional information - the latest version of mods are used, default resource pack is used, settings are untouched

edit 2: I realised that Epic Fight is incompatible with DivineRPG

**Comment by Yesssssman** [comment]
Fixed in 20.9.3
