### ISSUE TITLE
[Bug|Crash]: Render thread causing crash and datapack error after update to version 20.9.2

### ISSUE THREAD

**Issue by 5A93** [Yesssssman/epicfightmod#1799]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Crash when trying to click generate a new world also datapack error when trying to enter a old one,whether there is datapack or not

### Steps to Reproduce

Addon list: wom，indestructible
Crash [report：
[minecraft.log](https://github.com/user-attachments/files/16882347/minecraft.log)

**Comment by 5A93** [comment]
Figured out, two addon made by Shezarrin outdated, tried to change the render option and didn't work. Is anything I can do to save them? If not, please delete this issue

**Comment by Yesssssman** [comment]
```
java.util.NoSuchElementException: No animation with registry name epic_fight_battle_styles:sword/hero_sword_auto1
```
Your datapack requires epic fight battle styles installed

**Comment by 5A93** [comment]
> ```
> java.util.NoSuchElementException: No animation with registry name epic_fight_battle_styles:sword/hero_sword_auto1
> ```
> 
> Your datapack requires epic fight battle styles installed

Do you means those packs is using some moves that isn't exist in current version?

**Comment by Yesssssman** [comment]
> > ```
> > java.util.NoSuchElementException: No animation with registry name epic_fight_battle_styles:sword/hero_sword_auto1
> > ```
> > Your datapack requires epic fight battle styles installed
> 
> Do you means those packs is using some moves that isn't exist in current version?

Idk, Maybe battle styles mod deleted that animation file as the developer updated his mod, but what I can confirm in the log is your datapack is referencing animation `epic_fight_battle_styles:sword/hero_sword_auto1` which does not exist in the resource

**Comment by 5A93** [comment]
> > > ```
> > > java.util.NoSuchElementException: No animation with registry name epic_fight_battle_styles:sword/hero_sword_auto1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 您的数据包需要安装史诗级战斗风格
> > 
> > 
> > 你的意思是这些包使用了当前版本中不存在的一些动作？
> 
> 我不知道，也许战斗风格模组在开发人员更新模组时删除了该动画文件，但我可以在日志中确认的是，你的数据包引用了`epic_fight_battle_styles:sword/hero_sword_auto1`资源中不存在的动画

Thanks for the checking. Never heard of this addon before. Found it inside modpatch file and tried to save it by deleting those moveset, sadly did not work.
