### ISSUE TITLE
Modpack, Fork, Modification Allowance

### ISSUE THREAD

**Issue by ZandercraftGames** [Yesssssman/epicfightmod#18]
Hey there. I noticed that your code does not have a license assigned to it and currently is marked as "All Rights Reserved" on Curseforge. Because of this I am wondering what your policies are on the following issues:
- Forking the project for modification
- Distribution in modpacks
- Pull Requests (as they require the project to be forked and modified)

**Comment by Yesssssman** [comment]
Hmm.. I really don't know about copyrights and it's just a basic setting by the curseforge. I'll learn about that and gonna change it. Thanks!

**Comment by Opareds** [comment]
> Hmm.. I really don't know about copyrights and it's just a basic setting by the curseforge. I'll learn about that and gonna change it. Thanks!

i would suggest you to use MIT License

**Comment by Yesssssman** [comment]
What does it mean?

**Comment by ZandercraftGames** [comment]
> > Hmm.. I really don't know about copyrights and it's just a basic setting by the curseforge. I'll learn about that and gonna change it. Thanks!
> 
> i would suggest you to use MIT License

I also would suggest MIT as it is one of the more common licenses.

It grants others the ability to use your code commercially, to distribute it, to modify it and to use it privately. It removes any liability you might have for providing the code and it states that there is no warranty on the code. This is all on the condition that the code must be accompanied by the license and have a notice giving credit to the original creator and source.

**Comment by ZandercraftGames** [comment]
You could also go for the GNU LGPL-3.0
![Screenshot_20210223-183045_DuckDuckGo.jpg](https://user-images.githubusercontent.com/28664144/108922590-56511300-7605-11eb-842a-b15e338f549e.jpg)

**Comment by Yesssssman** [comment]
Ohh... this is quite difficult content for me, but I roughly understood it.

**Comment by ZandercraftGames** [comment]
Here is a guide on adding a license:
https://docs.github.com/en/enterprise-server@2.21/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by ZandercraftGames** [comment]
If you want to add a license, here are some easy links to do so:
MIT: https://github.com/Yesssssman/epicfightmod/community/license/new?branch=main&template=mit

Lesser GPL-v3: https://github.com/Yesssssman/epicfightmod/community/license/new?branch=main&template=lgpl-3.0

**Comment by ZandercraftGames** [comment]
Any updates on the status of this?
