### ISSUE TITLE
[Bug|Crash]: game crash when try to render entity?

### ISSUE THREAD

**Issue by hoenoch** [Yesssssman/epicfightmod#1800]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Born in Chaos

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

my game crashed and can't load back in until I run the game with older version of epic fight (EpicFight-20.7.4). After that I need to reinstall the old version epic fight to load in the game. look like there an entity that makes my game crash over and over again?

the crash happened when using newest epic fight mod (EpicFight-20.9.2)

[crash-2024-09-06_01.23.40-client.txt](https://github.com/user-attachments/files/16898849/crash-2024-09-06_01.23.40-client.txt)

### Steps to Reproduce

/locate structure born_in_chaos_v1:dark_tower_plain

walk next to tower (not tp to it) and then my game crash

**Comment by guivnf** [comment]
Closed issue as user has lots of other mods aside from those mentioned.
