### ISSUE TITLE
[Bug|Crash]: game crashes due to an incompatibility between the epic fight and valkyrienskies custom block render incompatibility

### ISSUE THREAD

**Issue by therealkorvax** [Yesssssman/epicfightmod#1802]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

when doing attacks that render broken terrain like that
![image](https://github.com/user-attachments/assets/e82a1cfc-a8ca-4320-ac58-8f20d1249737)
the game crashes because it cannot render the blocks
with my friend we do believe that it is due to an incompatibility between epic fight's custom block render and valkyrien skies's
here is a crash report

### Steps to Reproduce

launch a 1.20.1 forge minecraft instance with epic fight and valkyrien skies
equip a weapon that renders broken terrain like a greatsword
(if using the greatsword) do a sprint attack to render the custom blocks

**Comment by therealkorvax** [comment]
the crash report did not upload (sorry!)
here
[crash-2024-09-07_11.30.26-fml.txt](https://github.com/user-attachments/files/16917411/crash-2024-09-07_11.30.26-fml.txt)

**Comment by Yesssssman** [comment]
Can't figure out the problem in crash report. Did you just miss valkyrienskies?
```
	Failure message: Mod vs_eureka requires valkyrienskies 2.1.3-beta.1 or above
		Currently, valkyrienskies is not installed
```
