### ISSUE TITLE
[Bug|Crash]: Some UV texture for player model are mapped wrong

### ISSUE THREAD

**Issue by JonkkuSa** [Yesssssman/epicfightmod#1803]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

The UV for the player's left arm sleeve top part is rotated 90 clockwise. (The brown line is supposed to be aligned with the head like on the right shoulder. Same issue persists on all the skins I have tried.
![image](https://github.com/user-attachments/assets/7e492a95-0b43-4384-943b-d4c0d0be4023)

Also the UV for the player's left leg top part is rotated wrong. (White pixels should be pointed forward, not to the side.)
![image](https://github.com/user-attachments/assets/6482b994-4da5-4858-9db2-9309bf35b2c8)
![image](https://github.com/user-attachments/assets/7c521678-4830-4075-b7e2-aa6c185bbb63)

### Steps to Reproduce

Use any skin that has clearly marked UV textures

**Comment by Yesssssman** [comment]
Fixed in 20.9.5

**Comment by slipwolff** [comment]
I have found another issue of similar nature in version 20.9.6, this time the foot textures are mirrored.

How the feet look with the mod:
![Mirrored Feet](https://github.com/user-attachments/assets/aa24d111-e256-4139-88b1-561a353d4013)

How they should look:
![Normal Feet](https://github.com/user-attachments/assets/2998c299-cfcf-44f1-88d7-c2759c2d4e96)
