### ISSUE TITLE
[Bug|Crash]: Enderman Collider is bugged

### ISSUE THREAD

**Issue by M6FGR** [Yesssssman/epicfightmod#1804]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic fight 20.9.2

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

i just pressed f3+b testing some weapons and then i noticed the endermans collider is bugging weirdly

https://github.com/user-attachments/assets/f065f8de-0f21-4598-819a-42bb626d808a

Thats all i could upload of videos because the storage is too big to upload more

### Steps to Reproduce

Just summon an enderman and let it hit you while seeing the collider

**Comment by M6FGR** [comment]
closed by mistake

**Comment by auikiouy** [comment]
i have the same issue but his attacks also rarely hit me, same with spider

**Comment by Yesssssman** [comment]
Fixed in 20.9.3
