### ISSUE TITLE
[Bug|Crash]: Crash when play Dawncraf newest version 

### ISSUE THREAD

**Issue by kIENNGUYN** [Yesssssman/epicfightmod#1805]
### Please check if a similar issue has already been reported.

- [x] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Dawncraft Epic Fight Blood and Madness

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

First, sorry for ask here but i was asked in DC discord but still no respon for now and i really need help the crash log show some info abt Epic Fight so im here 
I found out thats when my friend ( we play lan world ) use the skill steel whirwind with church scythe from the Blood and Madness mod will crash me but not my friend and when i play in single world test it nothing happen with me 

### Steps to Reproduce

[crash-2024-09-10_22.19.22-client.txt](https://github.com/user-attachments/files/16948468/crash-2024-09-10_22.19.22-client.txt)

**Comment by guivnf** [comment]
This is not the dawncraft repository.

**Comment by kIENNGUYN** [comment]
ok then tks for u respon and time
