### ISSUE TITLE
[Bug|Crash]: Will the epic fight x recruits mod , double layered skin glitch be fixed anytime soon???

### ISSUE THREAD

**Issue by Sidabyss** [Yesssssman/epicfightmod#1806]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Recruits mod

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Will the epic fight x recruits mod , double layered skin glitch be fixed anytime soon???

### Steps to Reproduce

I'm not sure what to say here... especially since idk how it can be fixed and just here to report the issue

**Comment by guivnf** [comment]
Issue will not be fixed as they can fix the render layer in their mod and make both compatible. Epic fight is a library.
