### ISSUE TITLE
[Bug]: Can't add minecraft:air to auto switch list

### ISSUE THREAD

**Issue by Mqony** [Yesssssman/epicfightmod#1808]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I attempted several times to add minecraft:air (holding nothing) to the auto switch to mining list. It works for a little, though it seems to randomly reset and for some reason completely remove itself from the config. It sometimes happens randomly after a while though it seems to happen after game restart.

### Steps to Reproduce

1. Restart the game or play for a indefinite amount of time

**Comment by Yesssssman** [comment]
Fixed in 20.9.5
