### ISSUE TITLE
[Bug|Crash]: Cannot invoke "yesman.epicfight.skill.SkillContainer.isActivated()" because "skillContainer" is null

### ISSUE THREAD

**Issue by longsosos** [Yesssssman/epicfightmod#1809]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Cannot invoke "yesman.epicfight.skill.SkillContainer.isActivated()" because "skillContainer" is null
[crash-2024-09-13_17.58.12-client.txt](https://github.com/user-attachments/files/16992974/crash-2024-09-13_17.58.12-client.txt)

### Steps to Reproduce

Actually, this crash occurred with my client; he tried to attack or got attacked and instantly crashed.

**Comment by guivnf** [comment]
closing issue as user has connector which's not supported.
