### ISSUE TITLE
Possible to disable the green laser pointer for ranged weapons?

### ISSUE THREAD

**Issue by ethanp919** [Yesssssman/epicfightmod#181]
Is it possible to disable the green laser pointer for ranged weapons? I love the mod, but this really ruins it for me personally. I looked through the config, but did not see an option to disable it.

**Comment by Yesssssman** [comment]
If you turn on the fabulous graphic option, it'll no more be shown. but this is not a good solution. I'd add that option later.

**Comment by ethanp919** [comment]
Awesome thank you so much.
