### ISSUE TITLE
Animations not working.

### ISSUE THREAD

**Issue by DiamondDoesGames** [Yesssssman/epicfightmod#1811]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/5159623

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I cant find anything on this issue, and i cant access the text channel of issues for some reason. But what is happening is that whenever i try to use the mod, lets say i;m using a greatsword, i still have joints like elbows and knees, but the animation of weapons still plays just like the normal animations, just with an elbow. And the two handed weapons are also only held in my main hand. I've also gone into the mod settings config in game and no settings help. I also dont stop moving when i swing my sword.

### Steps to Reproduce

I just open the game, with other mods and without other mods, in 1.20.1

**Comment by guivnf** [comment]
Press "R" to enable battle mode.
