### ISSUE TITLE
[Bug|Crash]: Crash after fall death 1.20.1

### ISSUE THREAD

**Issue by LjeDamos** [Yesssssman/epicfightmod#1812]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/corpse

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Fall with half heart - died, cant respawn and crashed. Happens not all the times, got it once from like 8 fall deaths.

Maybe related to this mod, not sure:
https://www.curseforge.com/minecraft/mc-mods/corpse

Crashlog below:
java.lang.NullPointerException: Cannot invoke "yesman.epicfight.api.animation.TransformSheet.getInterpolatedTransform(float)" because "coord" is null
[crash-2024-09-15_13.39.53-client.txt](https://github.com/user-attachments/files/17005453/crash-2024-09-15_13.39.53-client.txt)

### Steps to Reproduce

Get health to 0.5 heart, fall

**Comment by TW-Black-Cat** [comment]
I have the same situation here, but I was injured on the lava block until I died and the game popped up.

As the player above said, the game does not crash and pop up every time you die.

**Comment by Yesssssman** [comment]
Fixed in 20.9.5
