### ISSUE TITLE
[Bug|Crash]: Game crashes when i try to use the skill book

### ISSUE THREAD

**Issue by Dinguslad** [Yesssssman/epicfightmod#1813]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

When i try to use the skill book it crashes my game 

[crash-2024-09-15_03.37.21-client.txt](https://github.com/user-attachments/files/17006945/crash-2024-09-15_03.37.21-client.txt)

### Steps to Reproduce

Just using the skill book

**Comment by guivnf** [comment]
Closing the issue as user did not attempt to find culprit mod incompatibility.
