### ISSUE TITLE
[Bug|Crash]: Using skill book crashes game

### ISSUE THREAD

**Issue by Dinguslad** [Yesssssman/epicfightmod#1814]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Suspected Mod:  	Epic Fight (epicfight), Version: 20.9.2

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Game crashes when i try to use the skill book 
[crash-2024-09-15_11.52.49-client.txt](https://github.com/user-attachments/files/17007595/crash-2024-09-15_11.52.49-client.txt)

### Steps to Reproduce

Get a skill book and try to use it

**Comment by guivnf** [comment]
If you report this again, i'm blocking you from this repository. Read the support policy and try to narrow down to which mod is causing the crash (aside from epic fight obviously...)

**Comment by Dinguslad** [comment]
> If you report this again, i'm blocking you from this repository. Read the support policy and try to narrow down to which mod is causing the crash (aside from epic fight obviously...)

brother in christ the mod is literally epic fight how about you help with that
Error: java.lang.NullPointerException: Cannot invoke "yesman.epicfight.skill.Skill$Resource.ordinal()" because the return value of "yesman.epicfight.skill.Skill.getResourceType()" is null this is what its telling me so its from the epicfight mod unless you would to point out its something else or get someone else who's willing to try and help

**Comment by GLMaster19** [comment]
> > If you report this again, i'm blocking you from this repository. Read the support policy and try to narrow down to which mod is causing the crash (aside from epic fight obviously...)
> 
> brother in christ the mod is literally epic fight how about you help with that Error: java.lang.NullPointerException: Cannot invoke "yesman.epicfight.skill.Skill$Resource.ordinal()" because the return value of "yesman.epicfight.skill.Skill.getResourceType()" is null this is what its telling me so its from the epicfight mod unless you would to point out its something else or get someone else who's willing to try and help

Try to reproduce this crash without any of your mods, but only with Epic Fight. After that, you can say with a 100% that this crash is caused by Epic Fight. Even if you have an error message where, in stacktrace, Epic Fight was mentioned, it doesn't mean that this crash caused by Epic Fight. That's how Minecraft works.

**Comment by guivnf** [comment]
> brother in christ the mod is literally epic fight how about you help with that Error: java.lang.NullPointerException: Cannot invoke "yesman.epicfight.skill.Skill$Resource.ordinal()" because the return value of "yesman.epicfight.skill.Skill.getResourceType()" is null this is what its telling me so its from the epicfight mod unless you would to point out its something else or get someone else who's willing to try and help

Ok, i'm assuming you know nothing about modding, epic fight works just fine on it's own, you have other mods that are causing this crash, and it's not my job to download all the goddamn mods you have and test it on my side, so do me a favor and stop being lazy and find the culprit if you want any help here.
