### ISSUE TITLE
[Bug|Crash]: 'Function' command crash server

### ISSUE THREAD

**Issue by YWCLee** [Yesssssman/epicfightmod#1815]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

[crash-2024-09-18_16.15.19-server.txt](https://github.com/user-attachments/files/17040829/crash-2024-09-18_16.15.19-server.txt)
Using the _function_ command in the **command block** to execute `epicfight skill add @p identity epicfight:revelation` will causes the server to crash.
This is a big bug, causing my map to not work properly.

### Steps to Reproduce

1. Create a datapack
2. Add this command `epicfight skill add @p identity epicfight:revelation`
3. Place a command block and type `function test:test`
4. Activate command block
5. Server crash
![1](https://github.com/user-attachments/assets/a5fb6da8-ef94-4727-bceb-771468981355)

Won't crash if you type `function test:test` in the chat. Won't crash if you are in **Singleplayer**. Only crash when in a server using a command block to execute it.

**Comment by Yesssssman** [comment]
Fixed in 20.9.3
