### ISSUE TITLE
[Suggestion]: Support for Vanilla style movements (I.E. an option for removed joints)

### ISSUE THREAD

**Issue by TheGamerCailo** [Yesssssman/epicfightmod#1816]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### Minecraft Version

1.20.1

### What's your suggestion?

**(I wanted to clarify that I'm NOT recommending an entire overhaul of the combat system because that would take too much time for the dev team and I know they wouldn't even consider it at that point.)**

I want to give my compliments to the modding team before I start giving constructive criticism. I really like the Epic Fight mod because of the poses and combos that it adds, which is like 90% of why I'm posting this suggestion. 

But I will say, I'm not a huge fan of the joints in arms and legs. It's a bit jarring to me for Minecraft. Now, I hear you saying: just use Better Combat. I do love that mod, and I've used it a lot, the only thing is that it doesn't add the dynamic poses and combos that I mentioned above. I think some support for a more vanilla style would allow for more adaptability in the kind of modpacks that it's used in; definitely in my case, because I'd use it a lot more in combination with other mods. 

So, rather than just straight up say what I'd like to see, I think it'll raise my chances of you guys seeing and considering it if I say how you could implement these things:

A simple config will do. You could simply add a config that enabled a more Minecraft integrated style that removes the joints and bends from the player model. I don't know if that's too difficult, but that's my only suggestion. Thanks for the consideration!

**Comment by guivnf** [comment]
> **(I wanted to clarify that I'm NOT recommending an entire overhaul of the combat system because that would take too much time for the dev team and I know they wouldn't even consider it at that point.)**
> 
> I want to give my compliments to the modding team before I start giving constructive criticism. I really like the Epic Fight mod because of the poses and combos that it adds, which is like 90% of why I'm posting this suggestion.
> 
> But I will say, I'm not a huge fan of the joints in arms and legs. It's a bit jarring to me for Minecraft. Now, I hear you saying: just use Better Combat. I do love that mod, and I've used it a lot, the only thing is that it doesn't add the dynamic poses and combos that I mentioned above. I think some support for a more vanilla style would allow for more adaptability in the kind of modpacks that it's used in; definitely in my case, because I'd use it a lot more in combination with other mods.
> 
> So, rather than just straight up say what I'd like to see, I think it'll raise my chances of you guys seeing and considering it if I say how you could implement these things:
> 
> A simple config will do. You could simply add a config that enabled a more Minecraft integrated style that removes the joints and bends from the player model. I don't know if that's too difficult, but that's my only suggestion. Thanks for the consideration!

We hear you, but the thing is, there's no way to remove joints from animations without remoaking every single animation from the ground up. We've animated everything in blender with a skeleton that has bends, removing them is basically out of the map for us, as it would takes us months if not years to remake it all again.
