### ISSUE TITLE
[Bug|Crash]:  The Combat mode Makes no damage, and  dont make any animation

### ISSUE THREAD

**Issue by HyperionDeveloperSENIOR** [Yesssssman/epicfightmod#1817]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

EPIC FIGHT

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I have a aternos server with diferent mods, all works as it should be but the main problem start when i activate the combat mode  theres no animation and no damage

### Steps to Reproduce

Start the server and join

**Comment by guivnf** [comment]
Attach logs, footage, and provide more info on how to reproduce the issue

**Comment by Ghostkiller01** [comment]
> Attach logs, footage, and provide more info on how to reproduce the issue

i have the same problem but it would be with greatswords i can't provide logs but it would happen after awhile when playing a playthrough and first it would work fine then after a while the sword would fade through the enemies and do no damage

**Comment by guivnf** [comment]
> > Attach logs, footage, and provide more info on how to reproduce the issue
> 
> 
> 
> i have the same problem but it would be with greatswords i can't provide logs but it would happen after awhile when playing a playthrough and first it would work fine then after a while the sword would fade through the enemies and do no damage 
> 
> 

That's most likely related to another mod causing this issue. Never heard of this and looks completely unrelated to epic fight itself.
