### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Foxyfan3105** [Yesssssman/epicfightmod#1819]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

hello, i have a problem, When I press (R) to enter fight mode, my view doesn't change and i have check the controls , can someone help me?

### Steps to Reproduce

https://github.com/user-attachments/assets/43794631-7183-48c3-8d5c-61ce1274a63b

**Comment by guivnf** [comment]
In the mod's config you can enable/disable the first person model.
