### ISSUE TITLE
Render Thread/NOClassDefFoundError

### ISSUE THREAD

**Issue by SyrusWhite** [Yesssssman/epicfightmod#182]
Hello, I current run a Server and i have several Members who can join and some that can't. for those who can't this is the issue they are running into. 
[Crash Report.txt](https://github.com/Yesssssman/epicfightmod/files/6329362/Crash.Report.txt)
Any insight would be helpful! 

Thank you in advance!

**Comment by RayBlazar** [comment]
[crash-2021-04-17_12.37.01-client.txt](https://github.com/Yesssssman/epicfightmod/files/6329734/crash-2021-04-17_12.37.01-client.txt)
Similar thing I think

**Comment by ebmario** [comment]
I was having a very similar issue where I could not even play with the mod.  I think it may be because their forge is not fully updated, I updated mine to 36.1 (the recommended version) I believe and it works out alright.   Just make sure they have the proper forge and I think it should work out.

**Comment by Yesssssman** [comment]
You should update the forge version to the latest 1.16.5. Since it doesn't support 1.16.4 forge after the 3.0.3 version.

**Comment by SyrusWhite** [comment]
Hello guys , and thank you for the reply, I will test this out with him...
it’s just I simply copy and paste my forge and mods and give it to others
so that there transitions would be smooth and not a hassle. If that’s the
case I can only assume that if it worked for me it should work for them.
Let me confirm though.

Thank you for the reply.
