### ISSUE TITLE
[Bug|Crash]: Game crash when loading a world because i am holding an epic fight weapon

### ISSUE THREAD

**Issue by ddarkpais1999** [Yesssssman/epicfightmod#1820]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Game crash when loading a world because i am holding an epic fight weapon and it started crashing after i hold a weapon from the epic fight mod

### Steps to Reproduce

[crash-2024-09-21_23.49.47-server.txt](https://github.com/user-attachments/files/17085947/crash-2024-09-21_23.49.47-server.txt)

**Comment by guivnf** [comment]
Crash does not occur because of epic fight, ask ex capabilities developer for help instead.
