### ISSUE TITLE
[Bug|Crash]: Imported airslash animations simply stop in mid-air

### ISSUE THREAD

**Issue by qVoidreaver** [Yesssssman/epicfightmod#1822]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

 [1.20.1] Last Version
 
 

https://github.com/user-attachments/assets/3deaa5d3-601f-473f-bd82-8830482d6273

### Steps to Reproduce

I simply added an imported animation.

**Comment by qVoidreaver** [comment]
[newzwei.zip](https://github.com/user-attachments/files/17105300/newzwei.zip)

The data package and the resource package, if you need it

The name of the weapon style I think is “newzweihander”

**Comment by Yesssssman** [comment]
I added Air Slash animation on datapack in 20.9.5
![image](https://github.com/user-attachments/assets/6b10e9b2-0a6a-4966-9339-7ba0dcd91c55)

But if you change the animation type it resets the previous elements so I recommend a workaround.

You can directly modify the animation type in the resource like this

![image](https://github.com/user-attachments/assets/f625467f-b5ed-4163-b09b-1e4b3bef8dcc)

In this way, you don't have to fill the required values again in datapack editor, just switch the name of class in the resource
