### ISSUE TITLE
[Crash]: Client Crashed 

### ISSUE THREAD

**Issue by IvoryJustie** [Yesssssman/epicfightmod#1825]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/werewolves-become-a-beast

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Here's My crash log:
[crash-2024-09-28_15.26.08-client.txt](https://github.com/user-attachments/files/17176015/crash-2024-09-28_15.26.08-client.txt)
I think the issue is it doesn't has a epic fight player when the player is something else other than the player.

### Steps to Reproduce

just download werewolves with  epic and become a werewolf

**Comment by Yesssssman** [comment]
Fixed in 20.9.3
