### ISSUE TITLE
[Bug|Crash]: Forbidden Strenght Orbs cause the Servers TPS to Tank to 0

### ISSUE THREAD

**Issue by Mikaaah** [Yesssssman/epicfightmod#1826]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

When a epicfight:forbidden_strength_orb spawns it instantly drops the servers tps to 0, this issue is consistent, and happens every time.

https://observable.tas.sh/p/I6Ha/aggregated
epicfight:forbidden_strength_orb x1 | 13363947 μs (99.2%)

### Steps to Reproduce

When using the deathharvest skill, and getting the hit that spawns the orb, it instantly kills the servers tps.

**Comment by Yesssssman** [comment]
I'm not sure of the reason but I optimized the ticking code of the entity. Could you test this on the next update?

**Comment by Yesssssman** [comment]
Hi, can you test if the same issue exists in 20.9.3?
