### ISSUE TITLE
[Suggestion]: 

### ISSUE THREAD

**Issue by Alif2200** [Yesssssman/epicfightmod#1828]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

Epic fight

### Minecraft Version

1.20.1

### What's your suggestion?

Alif

**Comment by guivnf** [comment]
?
