### ISSUE TITLE
[Bug|Crash]: I followed the tutorial to create a custom trails path, but adding two or more itemskins and custom textures would cause damage to the trails texture of the first item.

### ISSUE THREAD

**Issue by MechRW** [Yesssssman/epicfightmod#1832]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I followed the tutorial to create a custom trails path, but adding two or more temskins and custom textures would cause damage to the texture of the first item.

i dont use any mods,i just use datapack to let minecraft Original weapons can use epicfight function

### Steps to Reproduce

1.draw your own texture of trails by PS
2.fllow your wiki to make a pack
3.put more than 2 itemskins and textures in pack,name like 1.png or 2.png
4 writing item skin，let one use trails texture named 1.png，one use 2.png
5.2.png is okay in your game，but 1.png become to black and puprle cursh 
6.i allready check my file path is exactly the same as your wiki.
I don't know if there can only be one texture in the path, so I can only use one custom trails texture?
![2024-10-04_20 58 12_3](https://github.com/user-attachments/assets/4a74a744-9529-4f33-9fc2-7ff208fa46ae)

**Comment by MechRW** [comment]
I'm sorry to ask you this question, but of course I'm not using the latest version of Epicfight,
Because it is not compatible with my server and the epicvision NPC has not been updated yet.
The person who taught me how to make a resource package doesn't know if someone has stolen his labor results and used them to make black money,
He deleted all of his Chinese tutorials
And I can't contact them now.
My English is not good, it may cause trouble. I'm sorry

**Comment by Yesssssman** [comment]
Could you share your resource pack?

**Comment by MechRW** [comment]
[my trails.zip](https://github.com/user-attachments/files/17275688/my.trails.zip)

ok

**Comment by Yesssssman** [comment]
First, you have an invalid value for iron_sword item skin. There are now particle type named `epicfight:katana_trail` in game. Just use `epicfight:swing_trail` for that element.

And as I tested, I didn't get missing texture issue. Do you have any graphic related mod like optifine?

![c1](https://github.com/user-attachments/assets/c7768565-2883-4e77-a7cc-ea5aa25a8a79)
![c2](https://github.com/user-attachments/assets/d86f1e40-e82b-4ffa-9cc1-4f6ea9cd631c)

**Comment by MechRW** [comment]
yeah。maybe this is all optfine‘s falut.
may i should use rubidium and oculus to instead optfine.

**Comment by MechRW** [comment]
yeah,all be okay now. FXXK OPTFINE

**Comment by Yesssssman** [comment]
rubidium is still unstable in 1.20.1. I have embeddium in my development environment and have no problem so far. If you get any troubles in using rubidium I recommend using embeddium instead

**Comment by MechRW** [comment]
thanks for your answer,but i found embeddium will let bendy-lib-forge(lib for let emotecraft's emotion can have bendy anime)
Neutralization.maybe i should report under embeddium or oculus
