### ISSUE TITLE
[Bug|Crash]: server crash when adding skill to player via command block & datapack

### ISSUE THREAD

**Issue by Lexagonn** [Yesssssman/epicfightmod#1833]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Server crash when adding skills to player via command block & Datapack

[Works when doing it manually with a command, but not with commands!]

Client Forge version: 1.20.1-forge-47.3.0
Server Forge version: 1.20.1-forge-47.3.0

Crash logs:

When adding skill with Datapack function:
[crash-2024-10-08_00.22.25-server.txt](https://github.com/user-attachments/files/17285188/crash-2024-10-08_00.22.25-server.txt)

When adding skill with com
[crash-2024-10-08_00.20.11-server.txt](https://github.com/user-attachments/files/17285195/crash-2024-10-08_00.20.11-server.txt)
mand block:

Tested with only Epic Fight installed, no other mods:
[crash-2024-10-08_00.25.59-server.txt](https://github.com/user-attachments/files/17285202/crash-2024-10-08_00.25.59-server.txt)

### Steps to Reproduce

The simplest way to reproduce this error would be to try giving yourself a skill with a command block, example: /epicfight skill add @p passive1 epicfight:berserker

And the other way would be to make a datapack with a function which gives the player a skill when executed.

**Comment by Lexagonn** [comment]
I just tested the issue on all Epic Fight versions, and found out this bug doesn't happen on versions without the **Datapack Editor** feature.

Last working version: **Epic Fight 20.7.4**

![image](https://github.com/user-attachments/assets/38cccadf-7ad3-40db-884c-e5c72dbe4377)

**Comment by Yesssssman** [comment]
Same type of crash to #1815

**Comment by Yesssssman** [comment]
Fixed in 20.9.3
