### ISSUE TITLE
[Bug|]: sword doesn't swing correctly when first person model is turned off

### ISSUE THREAD

**Issue by MeMeiki** [Yesssssman/epicfightmod#1834]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

So when i turn off first person model and spam click or click fastly, the sword stops swinging and just stays up, while the efm swing animation is still playing.
![2024-10-08_21 51 08](https://github.com/user-attachments/assets/bcc7e4f8-8a20-460a-b936-4a9dbcd2a78e)

### Steps to Reproduce

Load up efm with no other mods, turn off first person model in config, equip a weapon, turn on battle mode, click fastly.

**Comment by Yesssssman** [comment]
This is not a bug but feature to ensure the compatibility with mods having their own first person models.

**Comment by MeMeiki** [comment]
> This is not a bug but feature to ensure the compatibility with mods having their own first person models.

What mods are you talking about in particular? first person model mod doesn't work with efm anyway?
Why not fix the issue in vanilla efm and just keep it when the specific mods are installed?

**Comment by guivnf** [comment]
> What mods are you talking about in particular? first person model mod doesn't work with efm anyway? Why not fix the issue in vanilla efm and just keep it when the specific mods are installed?

Any mods that makes changes to the first person model. If you don't like this, feel free to make changes through a pull request.
