### ISSUE TITLE
[Bug|Crash]: Rendering entity in world ( animations is the reason of crash)

### ISSUE THREAD

**Issue by D00TO** [Yesssssman/epicfightmod#1837]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

when creating new world or joining existing one, game crashes.

### Steps to Reproduce

create new world wait unitl it 100% then "creating world" then poof game crashes to desktop.

I have messed with mod options a little and  the option
graphic
first person model from ON to OFF
I get to play the game, the world generates I can run around do anything, but get to third person... poof game crashes again, 
so my suggest is that it has something to deal with the animations

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-10-11 20:30:09
Description: Rendering entity in world

java.lang.NullPointerException: Cannot invoke "yesman.epicfight.api.client.model.AnimatedMesh$AnimatedModelPart.setHidden(boolean)" because "mesh.head" is null

so, how to fix?

**Comment by Yesssssman** [comment]
You have an outdated resource pack that causes this crash. Please deactivate the resource pack
