### ISSUE TITLE
[Suggestions]: 1.19.4 pls

### ISSUE THREAD

**Issue by CryoNine** [Yesssssman/epicfightmod#1838]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [ ] This is related to other mods.

### The mod

Epic Fight mod 

### Minecraft Version

1.19.2

### What's your suggestion?

I play with a lot of mods, epic fight being one of my favorites, but since my friend and I are playing 1.19.4, I can't use this mod, and many of the other mods don't have other versions available that are compatible with switching versions. 

Also I selected 1.19.2 above because that is the closest to my current version.

**Comment by Yesssssman** [comment]
Sorry we only support for 1.20 now and we don't have any plans to backport the project.

**Comment by CryoNine** [comment]
> Sorry we only support for 1.20 now and we don't have any plans to backport the project.

Understandable have a nice day
