### ISSUE TITLE
[Bug|Crash]: Epic Fight mod NullPointerException getMaxStunShield Oculus rendering crash

### ISSUE THREAD

**Issue by itsdeadfrosty** [Yesssssman/epicfightmod#1839]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Occulus

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

When attempting to join a multiplayer server with the Epic Fight mod and Oculus shader mod enabled, Minecraft crashes and returns to the launcher with an error message and the option to view the crash report. The crash is triggered by a NullPointerException in the getMaxStunShield method of the LivingEntityPatch class from the Epic Fight mod. This issue does not occur in singleplayer and seems to be related to the interaction between entity rendering and shaders in a multiplayer environment.

### Steps to Reproduce

Install Minecraft version 1.19.2 with Forge.
Install Epic Fight mod version 19.5.26 and Oculus mod version 1.6.9 (for shaders).
Join a multiplayer server with these mods enabled.
The game crashes after loading into the server, returning to the launcher with an error message.

**Comment by Yesssssman** [comment]
We do not support 1.19.2 rn but please upload the crash report so we can evaluate the affection of this crash on 1.20.1

**Comment by itsdeadfrosty** [comment]
thank you for not blowing me off and saying "not my problem" as so many devs do

heres the crash:
https://pastebin.com/k6GuSQjB

**Comment by itsdeadfrosty** [comment]
nvm then

**Comment by Yesssssman** [comment]
Found out this issue no longer exists in 1.20.1 due to the base code changes. Older versions also have potential issues with packet processing. So I highly recommend updating it to 1.20.1.

**Comment by itsdeadfrosty** [comment]
thank you. just started building my modpack on 20.1 so it works out
