### ISSUE TITLE
[Bug]: Custom animations not working on Multiplayer-Server

### ISSUE THREAD

**Issue by Lexagonn** [Yesssssman/epicfightmod#1840]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Custom added animations through the Datapack Editor don't work on Multiplayer Server. Everything worked fine on 20.9.2

Epic Fight version: 20.9.3
Forge version: 47.3.0

### Steps to Reproduce

1. Add custom animations through Datapack editor
2. Add Resourcepack and Datapack to the server

**Comment by guivnf** [comment]
How don't they work? Does it just not play the animations at all, or does it use some default animation or something else...

And are you sure clients have the resourcepack?

Also, attach your resourcepack & datapack

**Comment by Yesssssman** [comment]
No worries I solved the issue. I'll upload hotfix soon cause it's so critical

**Comment by Yesssssman** [comment]
Fixed in 20.9.4
