### ISSUE TITLE
[Bug|Crash]: 

### ISSUE THREAD

**Issue by Meidde** [Yesssssman/epicfightmod#1841]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

![2024-10-14_13 13 03](https://github.com/user-attachments/assets/34a1a74e-5d02-422c-9604-f8040adbf6bd)
![2024-10-14_12 59 24](https://github.com/user-attachments/assets/9d554fe6-c467-473d-a6f5-46a2e9fac09d)
Something in the epicfight-forge-20.8.6-1.20.1 update makes the "ModelEngine" models break, basically these models are composed of "armor supports and item frames", I imagine that in one of the updates the way that epicfight deals with these entities changed.
All versions of the Epicfight Mod from 20.8.6 onwards have been tested by me and they all break the entity

If you look at the image where I use the epicfight-forge-20.8.5-1.20.1 version, the model behaves normally, but with more recent versions it breaks.

And before you say "we do not support Hybrid servers", this makes no sense considering that nowadays, those who have professional servers that use your mod always look for hybrid options and ModelEngine is clearly one of the most important plugins for server creators. And since I reported which version has the bug and which does not, I have already helped in any way I could.

### Steps to Reproduce

ModelEngine > Epic Fight 20.8.6 and newers

**Comment by guivnf** [comment]
We still do not support hybrid servers. If you wish this is fixed then report it to that hybrid server repository instead of ours, epic fight works perfectly fine on a default forge server.
