### ISSUE TITLE
[Bug]: Required Resourcepack not loading hitboxes correctly

### ISSUE THREAD

**Issue by Lexagonn** [Yesssssman/epicfightmod#1844]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I created a datapack using the in-built Datapack Editor and tried putting it on the server. 

In server.properties I set the resource pack as required 
![image](https://github.com/user-attachments/assets/7056d572-cfa6-4ebc-90cc-42776a39f009)

The animations work, but the hitboxes don't load and only show a fist hitbox. It also breaks all the other hitboxes for weapons which have a custom moveset. 
[**Also, the hitbox works, it just doesn't display correctly**]

![image](https://github.com/user-attachments/assets/8c789235-5255-446d-8074-752e8e99290e)

However, the issue is fixed when I apply this same resourcepack in my client 
![image](https://github.com/user-attachments/assets/af923a33-f4ca-4cd4-9dba-91cfb7eb2595)

EF version: 20.9.4
Forge verison: 47.3.0

### Steps to Reproduce

1. make a custom moveset with a custom hitbox
2. upload the resourcepack to the server and make it required
3. join the server and test hitboxes

**Comment by Yesssssman** [comment]
Fixed in 20.9.5
