### ISSUE TITLE
[Suggestion]: Disable Mob animations(Compatibility issues with data packs that affects mobs)

### ISSUE THREAD

**Issue by Kyljpg** [Yesssssman/epicfightmod#1845]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

https://www.curseforge.com/minecraft/texture-packs/blues-better-monsters

### Minecraft Version

1.20.1

### What's your suggestion?

Can you add a setting to atleast disable mob animations because I really want to use data packs for mobs whilst retaining animations for the player. Or can someone make a data pack for 1.20.1 that disables mob animations(if possible) and yes i tried the "[Epic Fight] No Animations" datapack but it doesn't work for 1.20.1

**Comment by Kyljpg** [comment]
https://www.planetminecraft.com/data-pack/epic-fight-no-animations/ this is the datapack that is supposed to disable mob animations for epic fight but still doesn't work

**Comment by Yesssssman** [comment]
https://github.com/user-attachments/assets/ad9e50c7-ecf2-4830-8867-36d47817c911

I've tested the datapack, and it worked fine. (20.9.4)

**Comment by Kyljpg** [comment]
Did you  install it as is?
