### ISSUE TITLE
[Bug|Crash]: Client crashes when using Epic Fight with BMC4 (Better Minecraft Mod Pack)

### ISSUE THREAD

**Issue by OperatorReezo** [Yesssssman/epicfightmod#1848]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

BMC4 v33.5

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Client crashes when turning on Battle Mode.

### Steps to Reproduce

1. Prepare a server with BMC4 v33.5 Mod Pack and add the Epic Fight mod
2. Run the server
3. Prepare a client with BMC4 v33.5 Mod Pack and add the Epic Fight mod
4. Run the client
5. Connect to the server via MULTIPLAYER > (select the server)
6. Once joined and in the world, enter Battle Mode by pressing the assigned key bind

On my end, this causes the client to crash.

(Attached, the log from the crash)
[crash.log](https://github.com/user-attachments/files/17430829/crash.log)

UPDATE:
- Crash happens in Single Player, too
- Crash does not happen in a test world I have "rp_test_ma_1.20.4" that I use just to check resource packs. It does happen in the world I created with BMC4

**Comment by Yesssssman** [comment]
The link for crash log is invalid

**Comment by OperatorReezo** [comment]
> The link for crash log is invalid

Apologies, I updated it and now it should work.

UPDATE:
- Crash happens in Single Player, too
- Crash does not happen in a test world I have "rp_test_ma_1.20.4" that I use just to check resource packs. It does happen in the world I created with BMC4

**Comment by guivnf** [comment]
Closed issue as user is running a modpack in an undesirable environment.

**Comment by OperatorReezo** [comment]
I solved it! It works now! But thanks anyway for coming to the rescue and for the amazing mod!
