### ISSUE TITLE
[Bug|Crash]: Game sometimes crashes when it can't find a specific idle animation, but the animation is there

### ISSUE THREAD

**Issue by Lexagonn** [Yesssssman/epicfightmod#1849]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

An animation in my pack seems to be causing some issues, sometimes (not always) the game will crash when it attempts to play the animation, but when I restart my game it's fine. 

Crash log: https://mclo.gs/skmIRaF

Resource pack: 
[EFACA 1.0.0.zip](https://github.com/user-attachments/files/17416805/EFACA.1.0.0.zip)

### Steps to Reproduce

1. Download the pack and equip iron longsword, the problem seems to be the "efa:biped/efa_hold_longsword" animation. It's a simple idle animation for the longsword.

**Comment by Yesssssman** [comment]
Fixed in 20.9.5
