### ISSUE TITLE
[Bug|visual]: Epic Fight latest update breaks some of Jet and Elia's Armors

### ISSUE THREAD

**Issue by TheComradeCrusade** [Yesssssman/epicfightmod#1852]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [x] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/jet-and-elias-armors

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I was testing the new epic fight update with the Jet and Elia's Armors mod and came across the visual bug that makes the armors not appear when equiped, not all armor pieces are buged just most chestplates and helmets.
![image](https://github.com/user-attachments/assets/d44fd017-e753-4ab5-96d0-2fe41afc698d)
![2024-10-18_17 45 56](https://github.com/user-attachments/assets/4f742975-4f1e-4801-864e-5d304ac62583)

### Steps to Reproduce

Just equip the armors

**Comment by Yesssssman** [comment]
Fixed in 20.9.5
