### ISSUE TITLE
[Bug|Crash]: Epic Fight & Armouer's Workshop Incompatibility

### ISSUE THREAD

**Issue by CiciHoneyBee** [Yesssssman/epicfightmod#1856]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/armourers-workshop

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Game crashes when moving in world/equipping sword or screen turns fully black after loading in whenever including Epic Fight and Armourer's Workshop mods.

Crash Report: https://gist.github.com/CiciHoneyBee/a3bebd7b5ea873503c6ca168d6acf023

### Steps to Reproduce

1.
Operating System: Windows 11 Pro

Minecraft Version: 1.20.1 

Loader: Forge 47.3.11

Epic Fight Version: 20.9.4

Armouer's Workshop Version: 2.1.4

Other mods: Oculus 1.7.0, Embeddium 0.3.31

2.
Load into world, walk around, equip weapon.

**Comment by Yesssssman** [comment]
Armouer's Workshop is outdated.

**Comment by CiciHoneyBee** [comment]
You are right, I apologize. Curseforge labeled it in my modpacks as up to date when it wasn't. Should have looked closer
