### ISSUE TITLE
[Bug|Crash]: Wither boss vanishing effect lead to crash server. Mc 1.20.1 / Forge 47.3.10 / Epic Fight-forge 20.9.4- 1.20.1

### ISSUE THREAD

**Issue by LnX-OrioN** [Yesssssman/epicfightmod#1857]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

The server crashes when the Wither Boss enters its second phase, when it disappears and tries to no clip a surface (wither proof glass from Mob Grinding Utils in my case).

### Steps to Reproduce

Set up a farm with wither boss (closed construction), go into survival mode, open just one block for the wither to attack us, as soon as its animation starts, the game crashes.

[crash-2024-10-27_12.14.44-server.txt](https://github.com/user-attachments/files/17533675/crash-2024-10-27_12.14.44-server.txt)

**Comment by Yesssssman** [comment]
Fixed in 20.9.5
