### ISSUE TITLE
[Bug|Crash]: crash when using Satsujin in Weapons of Miracles

### ISSUE THREAD

**Issue by latiaotiao** [Yesssssman/epicfightmod#1859]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

WeaponsOfMiracles-20.1.8.5.2

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

only two mods, epicfight-20.9.5-1.20.1 and WeaponsOfMiracles-20.1.8.5.2.

[crash-2024-10-31_12.11.40-server.txt](https://github.com/user-attachments/files/17581917/crash-2024-10-31_12.11.40-server.txt)

### Steps to Reproduce

Just use Satsujin

**Comment by latiaotiao** [comment]
Just hold it in your hand for a few seconds and it will crash

**Comment by LnX-OrioN** [comment]
I can confirm,  Same issue on server multiplayer. No crash but user with weapon in hand got disconnect from server. Forced to delete this weapon in user.dat inventory for allow him to reconnect.

**Comment by GLMaster19** [comment]
It's not WoM github page. Yesman and Gui, Epic Fight developers, can't help you with this. Go to Reascer's discord with this problem.

**Comment by NaokiMasaru** [comment]
I experience the same situation just click using the setsujin it will crash the game

**Comment by LnX-OrioN** [comment]
> It's not WoM github page. Yesman and Gui, Epic Fight developers, can't help you with this. Go to Reascer's discord with this problem.

yes, I agree but this bug appeared just after the last epic fight update (10/29/2024)

**Comment by NaokiMasaru** [comment]
I found new when using combo or skill of the weapon it will freeze and crashed

**Comment by latiaotiao** [comment]
There is no issue with 20.9.4, it is caused by the 20.9.5 update

**Comment by NaokiMasaru** [comment]
> There is no issue with 20.9.4, it is caused by the 20.9.5 update

is dat the version should I Download?

**Comment by LnX-OrioN** [comment]
> > There is no issue with 20.9.4, it is caused by the 20.9.5 update
> 
> is dat the version should I Download?

Yes, but expect others bugs/crashs. Look at my latest post on closed section

**Comment by latiaotiao** [comment]
It also crashes when using antitheus's skills, and it feels like a similar issue

**Comment by Yesssssman** [comment]
Fixed in WeaponsOfMiracles-20.1.8.5.5
