### ISSUE TITLE
[Bug|Crash]: java.lang.NoSuchMethodError: 'void yesman.epicfight.world.capabilities.entitypatch.player.ServerPlayerPatch.modifyLivingMotionByCurrentItem()'

### ISSUE THREAD

**Issue by MCnifficent1** [Yesssssman/epicfightmod#1862]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Forgive me, but I'm writing this at 4 am but I always run into this crash issue after playing for a few minutes. I'm fairly certain it's not a mod conflict, but just in case, I'm using:
- Epic Fight Battle Arts
- Epic Fight EX Capabilities
- Epic Fight Impactful
- Epic Fight Indestructible
- Epic Fight Wukong Moveset
- Weapons of Miracle

I'm using many unrelated world generation, structures, etc mods that I can provide later if needed. I'm on the lastest 1.20.1 version of forge and everything is up to date.

Here is the latest crash report:
[crash-2024-11-02_03.54.35-server.txt](https://github.com/user-attachments/files/17606647/crash-2024-11-02_03.54.35-server.txt)

### Steps to Reproduce

This crash happens often when attacking with any weapons, like from WOM for example, the Antitheseus (however you spell it)'s transformation is a guaranteed crash.

**Comment by ArcaneSan** [comment]
Is WOM updated to latest? had the same issue and noticed WOM needed to update and it was fixed
