### ISSUE TITLE
[Bug|Crash]: how can i remove only death animation all entity. i want use death animation of physic mod.

### ISSUE THREAD

**Issue by PHATTHAKAN** [Yesssssman/epicfightmod#1863]
As mentioned in the title, I want to remove all the entity death animations so that I can use the Ragdoll animation in physic mod.

i create datapack for test a zombie
![image](https://github.com/user-attachments/assets/e0ee5aa3-8920-4e55-9386-a64d6bb0bf8b)
but when i kill zombie it just stay still.
![image](https://github.com/user-attachments/assets/4e1ac0bf-0a61-4113-ac43-bf41f89b8267)

**Comment by guivnf** [comment]
Closed source mod
