### ISSUE TITLE
[Bug|Crash]: Pants trims don't display with Oculus.

### ISSUE THREAD

**Issue by SoftPaw6234** [Yesssssman/epicfightmod#1864]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Oculus

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

What happened: I applied a full set of armor trims, and the pants trim didn't render on my player model in f5. Testing various combinations of the mods in my pack, I narrowed down the issue to Oculus+Epic Fight.
What should have happened: all armor trims should render as normal.

### Steps to Reproduce

Install Oculus and Epic Fight. Apply two mismatched armor trims, one on the leggings, go in f5, and observe. Specifically I use, from head to toe, silence, dune, silence, tide, all redstone on netherite, and the two silence pieces can coexist. the trim and armor material don't seem to matter.

**Comment by guivnf** [comment]
Footage missing. Please attach a video or image of the issue.

**Comment by Yesssssman** [comment]
Won't fix, I inspected the issue but there was nothing I could do about the issue, Maybe it comes from some optimization code oculus but I really can't figure out how they work.
