### ISSUE TITLE
[Bug]: Punch Modifies Damage Attribute

### ISSUE THREAD

**Issue by YumYumJudah** [Yesssssman/epicfightmod#1865]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Using Epic Fight's Punch modifies the damage attribute of itself and other weapons

### Steps to Reproduce

When I punch with EF in my modpack it causes my attack damage attribute to be increased semi permanently. The damage seems to be reset when I leave and rejoin the world, but its obviously still a problem for balancing issues. Are there any known fixes for this?
https://mclo.gs/uPYxxqP
This log is from me testing it on a server
I'm playing on ver.20.9.5-1.20.1. The problem also appeared on ver.20.7.4.

**Comment by guivnf** [comment]
User log has over 11k lines, with closed source mods & sinytra connector.
