### ISSUE TITLE
[Crash]: when opening datapack cofig

### ISSUE THREAD

**Issue by IvoryJustie** [Yesssssman/epicfightmod#1867]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

GeckoLib  and also BleachAwaken (bleachawaken)

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

when i was making m custom data pack for mob captittes it crashed
 
[crash-2024-11-09_17.00.03-client.txt](https://github.com/user-attachments/files/17689516/crash-2024-11-09_17.00.03-client.txt)

### Steps to Reproduce

1. dowload the mods i did 
2. make sword data pack
3. swich to mob capites

**Comment by Yesssssman** [comment]
#1830
