### ISSUE TITLE
[Bug|Crash]: Compatibility with Origin furs

### ISSUE THREAD

**Issue by VinceDav** [Yesssssman/epicfightmod#1868]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://modrinth.com/mod/origin-furs-unofficial-forge-port

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Crash when loading world with epic fight
[crash-2024-11-10_18.50.44-client.txt](https://github.com/user-attachments/files/17693590/crash-2024-11-10_18.50.44-client.txt)

### Steps to Reproduce

download mod with epic fight
start world

**Comment by guivnf** [comment]
We don't add compatibility for unnoficial ports.
