### ISSUE TITLE
[Bug|Crash]: Witches not throwing potions

### ISSUE THREAD

**Issue by BAP9909** [Yesssssman/epicfightmod#1869]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

Witches not throwing potions, only the throwing animations but no potions is thrown

### Steps to Reproduce

load the newest version of the mod normally with forge

**Comment by guivnf** [comment]
Footage missing, attach a video of the issue.

**Comment by HaktyGaona** [comment]
> 缺少素材，请附上该问题的视频。

I encountered the same problem, this is a video.

https://github.com/user-attachments/assets/0abfcb6d-bd5a-44a6-a8e3-c89280ed42cf

**Comment by HaktyGaona** [comment]
> Footage missing, attach a video of the issue.

I encountered the same problem, this is a video.

https://github.com/user-attachments/assets/bd2a2ccb-b55d-4eb5-99fc-d34488a23703

**Comment by Yesssssman** [comment]
Fixed in 20.9.6. Thank you
