### ISSUE TITLE
[Suggestion]: fantasy armors compat

### ISSUE THREAD

**Issue by papanatas-ef** [Yesssssman/epicfightmod#1870]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [X] This is related to other mods.

### The mod

https://www.curseforge.com/minecraft/mc-mods/fantasy-armor

### Minecraft Version

1.20.1

### What's your suggestion?

In fantasy armors when changing to combat mode some parts of the armors (like capes or extra overlays) don't display.

**Comment by Yesssssman** [comment]
I fixed the visibility of other parts but only the cape part I can't make it visible because the mod doesn't follow the standard hierarchy.
