### ISSUE TITLE
[Bug]: Weapon types customized through the editor cannot use any guard skills

### ISSUE THREAD

**Issue by HaktyGaona** [Yesssssman/epicfightmod#1871]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

EpicFight 20.9.5

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

I have created some weapon types using a packet editor, but using these weapon types does not allow me to use guard skills, and the right mouse button does not work.
I have confirmed that I have learned the skills.

No log information was thrown for this issue.

I think this is a mistake. If necessary, I can provide a JSON file for reference.

### Steps to Reproduce

As described in the problem description.

**Comment by TrollLikesPizza** [comment]
Had you added "Block" Animation in "Living Animations"?

![image](https://github.com/user-attachments/assets/453f8c75-4f9a-4dc4-92f0-2f396c0914ca)

**Comment by HaktyGaona** [comment]
![image](https://github.com/user-attachments/assets/0f42922e-c5ca-4a4f-bd2c-eb0ed290376a)

[test.json](https://github.com/user-attachments/files/17811873/test.json)

Yes, I did.

**Comment by HaktyGaona** [comment]
Oh, I see. If the default style is `two_hand`, it must be the same instead of `common`, but why can attack animations be used?
