### ISSUE TITLE
[Bug]: You cant use the bow in first person view.

### ISSUE THREAD

**Issue by Curupi18** [Yesssssman/epicfightmod#1873]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Epic Fight mod

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

When i try to use the bow in first person, the view gets obstructed by the same bow, like its in the middle of the screen.
![2024-11-15_12 29 53](https://github.com/user-attachments/assets/5b80a26c-e0c4-4898-aaef-2635b0417d5e)
Some times it changes and occupies more of the screen and other times it lets you see from up top de bow, things that i dont think are suppose to happen. 
I know someone allready talked about the crossbows having the same issue, and that got fixed, I belive. But this stops any player from using the bow and arrow. 
Thank you very much, awaiting for your response. 

### Steps to Reproduce

I dont know exactly, but setting the vanilla animation on the character while shooting with the bow might be a good idea. I dont really know of any of this stuff, but thats my best thought.

**Comment by Yesssssman** [comment]
#1824
