### ISSUE TITLE
[Suggestion]: New action animations

### ISSUE THREAD

**Issue by OneWorldStudio** [Yesssssman/epicfightmod#1874]
### Have you checked if there's any similar suggestions ?

- [X] I checked, there are no similar suggestions that have been reported.

### Are you using the latest Epic Fight ?

- [X] I checked I'm using latest Epic Fight version.

### Is this suggestion related to another mod? (i.e: add animations for X mod)

- [x] This is related to other mods.

### The mod

https://modrinth.com/mod/vintage-animations/version/ZCWqdfCU

### Minecraft Version

1.20.1

### What's your suggestion?

Add animation when collecting plants (for example, wheat and others, so that he does not break, but collects with animation and a timer), chopping wood, mining with a pickaxe, when digging with a shovel, hoes to stick into the ground when excavating it for seeds, add emotions like in EmoteCraft and I would like to still see the function and animation lying down

**Comment by guivnf** [comment]
> ### Have you checked if there's any similar suggestions ?
> 
>     * [x]  I checked, there are no similar suggestions that have been reported.
> 
> 
> ### Are you using the latest Epic Fight ?
> 
>     * [x]  I checked I'm using latest Epic Fight version.
> 
> 
> ### Is this suggestion related to another mod? (i.e: add animations for X mod)
> 
>     * [x]  This is related to other mods.
> 
> 
> ### The mod
> 
> https://modrinth.com/mod/vintage-animations/version/ZCWqdfCU
> ### Minecraft Version
> 
> 1.20.1
> ### What's your suggestion?
> 
> Add animation when collecting plants (for example, wheat and others, so that he does not break, but collects with animation and a timer), chopping wood, mining with a pickaxe, when digging with a shovel, hoes to stick into the ground when excavating it for seeds, add emotions like in EmoteCraft and I would like to still see the function and animation lying down

Never open an issue here again, or your account will be suspended from this repository. We don't care about your suggestions nor will they ever be added to the mod.

**Comment by guivnf** [comment]
Issue blocked due to uncooperation in older reply from user:
https://github.com/Yesssssman/epicfightmod/issues/1795#issuecomment-2327932022

**Comment by OneWorldStudio** [comment]
Понял, плакса вакса

**Comment by guivnf** [comment]
> Понял, плакса вакса

You'll definately be blocked from this repository & others now. I'm reporting you to github and hopefully your account will be terminated for harrasment.
