### ISSUE TITLE
Hurt event causing Ticking Entity

### ISSUE THREAD

**Issue by nokosi1736** [Yesssssman/epicfightmod#188]
when someone get hurt it sometimes causes an ticking entity
[crash-2021-04-18_19.09.25-server.txt](https://github.com/Yesssssman/epicfightmod/files/6332013/crash-2021-04-18_19.09.25-server.txt)
seems like ranged or thrown weapons from other mods will cause it to crash when hurting a mob too

**Comment by koderian** [comment]
Same issue.

**Comment by Jollyolsport** [comment]
yup
