### ISSUE TITLE
[Bug|Crash]: The Game Crashed Whilst Ticking Entity

### ISSUE THREAD

**Issue by Cronos139** [Yesssssman/epicfightmod#1881]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/modpacks/mystic-horizons-rpg

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

As I was playing Minecraft I was in a cave fighting a Creeper and using a Great axe and I let the creeper explode as I was hitting it at the same time and then my game crashed and wont let me relaunch it, I join the world But it kicks me Out right away before I can do Anything, I've made new worlds and they work its just this one when I load into it it crashes, It Gave me this message here (The game crashed whilst ticking entity
Error: java.lang.ClassCastException: class yesman.epicfight.gameasset.Animations$1 cannot be cast to class yesman.epicfight.api.animation.types.AttackAnimation (yesman.epicfight.gameasset.Animations$1 and yesman.epicfight.api.animation.types.AttackAnimation are in module epicfight@20.9.4 of loader 'TRANSFORMER' @50cf26b7) and i do not know what it means, is there anyway you can help me?

### Steps to Reproduce

1. use Great axe that has the berserk skill on it
2.hit creeper as its exploding with it
3. i think game Crashes i haven't been able to recreate it

**Comment by guivnf** [comment]
That's not a mod, but a modpack. Closing issue as user failed to find culprit.

**Comment by Cronos139** [comment]
It says that the error is coming from Epic Fights which is the culprit?

**Comment by guivnf** [comment]
> It says that the error is coming from Epic Fights which is the culprit?

That's not how crash reports work. First of all, this modpack has tons of mods and anything could be causing it. If you want to get your issue fixed, follow the support policy and find the mod that's actually causing the issue.
