### ISSUE TITLE
[Bug|Crash]: armour not working with better combat

### ISSUE THREAD

**Issue by frinzo** [Yesssssman/epicfightmod#1887]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

souls's like universe

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

every time when i try to equip any kind of armour with epic fight in combat mod game simply crashes i have tried multiple armour mods and i get the same result i can equip my armour and play in third person but as soon as i play on third erson it immediately crashes.
[tl-logger8873149000627174258.txt](https://github.com/user-attachments/files/18014113/tl-logger8873149000627174258.txt)

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/1621b060-f0bd-4d3c-a8b8-3a6f49f31985)these were the mods i was using...

**Comment by guivnf** [comment]
this is not the better combat repository.
