### ISSUE TITLE
[Bug|Crash]: Crash using Antitheus from Weapons of miracle

### ISSUE THREAD

**Issue by DarkSoul666999** [Yesssssman/epicfightmod#1888]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

Mod causes crash: https://modrinth.com/mod/weapons-of-miracles   And Valkyrien Skies 2. Downloaded from same site

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

The game crashes during weapon animation. Ticking entity
[crash-2024-12-07_08.35.58-client.txt](https://github.com/user-attachments/files/18046376/crash-2024-12-07_08.35.58-client.txt)

### Steps to Reproduce

I used the weapon "Antitheus" from the Weapons of miracles mod. Using a weapon on the left mouse button does not cause a crash, only the right one

https://github.com/user-attachments/assets/23cd4977-c653-4539-bb90-2f3a5af5d176

**Comment by BoyanShen** [comment]
Its not just an issue from antitheus, using a base EF greatsword ground shattering attack can crash your game as well. Heres a solution you can use to fix it:

Install embeddium
Delete this world and generate a new one
Try whatever you want to test again

Also just a tip: if you want to play epicfight with valkyrien skies, avoid using any mods that affects the lighting engine eg. starlight

**Comment by DarkSoul666999** [comment]
I want to first say thank you! The Embeddium really helped.

I found the reason for these crashes. The whole essence of the problem was in one mod that conflicted with the deformation of blocks around the player, a mod called "Eureka! Ships! for Valkyrien Skies (Forge/Fabric)" (Without Embeddium, the game crashed, even without Eureka)
While checking with him and without him there were different situations. Without it, the flights stopped and the blocks became deformed.
