### ISSUE TITLE
[Bug]: The raincoat model displayed wrongly with Convenient Decor mod.

### ISSUE THREAD

**Issue by Hakuyako** [Yesssssman/epicfightmod#1890]
### Please check if a similar issue has already been reported.

- [X] I checked this type of issue has never been reported.

### Please check you're using proper versions.

- [X] I checked all of them in the right version.

### Please check if this issue's from out of our area

- [X] I understood the problem.

### The name of the mod

https://www.curseforge.com/minecraft/mc-mods/convenient-decor

### After all of these, please check if you're just pressing the ok buttons to skip this process.

- [X] I read the checklist and I promise I'll provide all the information that is needed to fix the issue

### Minecraft Version

1.20.1

### The Issue

The raincoat model displayed wrongly with Convenient Decor mod.
![2024-12-12_01 38 04](https://github.com/user-attachments/assets/05073b30-8e04-408e-8507-12668b5acb81)
![2024-12-12_01 40 55](https://github.com/user-attachments/assets/0ccd344a-537d-4ca2-8ccf-69dad3790a08)

### Steps to Reproduce

1. Install both the mod.
2. Run the game.
3. Wearing any raincoat from the Conveninent Decor.

**Comment by guivnf** [comment]
Closing issue as this is a fabric mod.
