### ISSUE TITLE
Suggestion : New Weapons and Better shield

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#2]
I'm sure Maces And Sledge Hammers can be cool so much.
Can you add these weapons to the mod ?

You can add these features for maces and sledge hammers : 
Knockback enemy 
Slowdown enemy (10 or 15 Seconds)
Stun (Enemy cannot hit or move for 3 or 5 seconds when we do a head hit)

And you can make these changes for shields : 
1-Make shield blocking animation like the reaction of a soldier using a shield to an arrow rain
(When player crawls with shift button)

2-Make a shield hitting ability (Left click while blocking) and the enemy can get knockbacked or stunned by this ability.

And last suggestion : Make bow animation more realistic.
You know archers are rotating their body while pulling an arrow.
And that realistic bow animation is featuring in even mount & blade.

I recommend you to add these super things. 👍 
Thanks for reading.

**Comment by Yesssssman** [comment]
Ok, It won't much easy but I'll try it later.

**Comment by jeroen11122005** [comment]
i would love it if the damage, durability and stuff like the armor pen of weapons would be configurable as well, for example when your playing in modpacks with really strong weapons like AVA or ice and fire you could turn them up so they are still relevant but if you playing in a harder pack you could make them weaker instead

**Comment by TurkishAhmet4545** [comment]
@Yesssssman I don't know should i close this issue.
Can you help me to decide that will i close this issue or make it stay open ?

**Comment by jklw10** [comment]
hmm... i guess as long as the feature isn't implemented the "issue" still exists right? on the other hand this isn't really an issue but a todo now that it has been approved. so if you do close it make sure it's written up somewhere else or implemented maybe? that's just my 2 cents

**Comment by TurkishAhmet4545** [comment]
> hmm... i guess as long as the feature isn't implemented the "issue" still exists right? on the other hand this isn't really an issue but a todo now that it has been approved. so if you do close it make sure it's written up somewhere else or implemented maybe? that's just my 2 cents

ok

**Comment by TurkishAhmet4545** [comment]
Ok i think i can close the topic now.
I can check the mod's updates.
