### ISSUE TITLE
Custom armor configs don't seem to work.

### ISSUE THREAD

**Issue by xbomp** [Yesssssman/epicfightmod#200]
![2021-04-20_00 08 39](https://user-images.githubusercontent.com/82787283/115340729-dc548a80-a16c-11eb-8803-9c0a4a185a32.png)
![Capture6](https://user-images.githubusercontent.com/82787283/115340751-e9717980-a16c-11eb-8714-a149cc58c77c.PNG)

**Comment by StLankowski** [comment]
Yeah. I have the same problem. It just won't work.
