### ISSUE TITLE
[Suggestion] Slashblade compatibility

### ISSUE THREAD

**Issue by InteJason** [Yesssssman/epicfightmod#206]
Slashblade is an interesting katana mod that gives the player different abilities by landing combos and special attacks: https://www.curseforge.com/minecraft/mc-mods/slashblade
This would pair up amazingly with your mod, however, as of right now, the sword isn't rendered, and there's no animation despite the fact that I added the weapon into the config folder.
![2021-04-21_21 34 29](https://user-images.githubusercontent.com/74423341/115562759-6590cc00-a2e9-11eb-9abb-7fb54c67d2e4.png)

If this can be implemented, I would like to make a samurai modpack based on these two mods :)

**Comment by InviteKnight** [comment]
Ooo, I agree. This would definitely add some interesting abilities.

**Comment by TurkishAhmet4545** [comment]
I agree,too.

**Comment by Aboslut** [comment]
I mean yeah but please don't do that now because there's way more important things to add before this
