### ISSUE TITLE
Crashes When Spawners Spawn Mobs

### ISSUE THREAD

**Issue by PrussianFungus** [Yesssssman/epicfightmod#207]
Once I removed Epic Fight everything worked as normal and spawned mobs again. 
[crash-2021-04-21_14.03.26-server.txt](https://github.com/Yesssssman/epicfightmod/files/6353076/crash-2021-04-21_14.03.26-server.txt)

**Comment by MagmaBro123** [comment]
Try downgrading EpicFightMod version by
version till you find a lower version that works.

**Comment by TripConeHead** [comment]
I have the same issue, oddly enough it only seems to have applied to the spawners from when dungeons arise and not a different dungeon mod I have installed.

It's definitely the result of the spawners becoming ticking entities once they actually start spawning. Flying up to one in spectator wont result in a crash, but the moment I pop into creative or survival the game goes down.

**Comment by MagmaBro123** [comment]
> I have the same issue, oddly enough it only seems to have applied to the spawners from when dungeons arise and not a different dungeon mod I have installed.
> 
> It's definitely the result of the spawners becoming ticking entities once they actually start spawning. Flying up to one in spectator wont result in a crash, but the moment I pop into creative or survival the game goes down.

As I said, try downgrading till you find a version that works.
