### ISSUE TITLE
Big server problems

### ISSUE THREAD

**Issue by imkappa** [Yesssssman/epicfightmod#219]
I wanna make a server with this mod. But in 1.12.2 it makes really really big problems. Kicks players, sometimes combat is bugging and not working.

**Comment by imkappa** [comment]
not crashes the server but it makes it unplayable

**Comment by InviteKnight** [comment]
> not crashes the server but it makes it unplayable

How many players are we talking about here? I plan on making a small modpack for my friends and I to play with it installed

**Comment by imkappa** [comment]
2 players just me and my friend i wrote the main problem in here and showed the problem https://github.com/Yesssssman/epicfightmod/issues/224

**Comment by imkappa** [comment]
> > not crashes the server but it makes it unplayable
> 
> How many players are we talking about here? I plan on making a small modpack for my friends and I to play with it installed

it starts when you try to close the server with any weapon
