### ISSUE TITLE
crash when loading minecraft with epicfightmod.

### ISSUE THREAD

**Issue by Andermedievil** [Yesssssman/epicfightmod#22]
[crash-2021-02-24_03.26.16-client.txt](https://github.com/Yesssssman/epicfightmod/files/6034096/crash-2021-02-24_03.26.16-client.txt)

i was loading the mod from the beta version 1.12.2 and it crash when loading minecraft.i through that it was because of some mods that replaced the animations and the models of the enemies.but i remove it and is still crash.i hope this report can help you to fix it.

**Comment by Yesssssman** [comment]
Im currently focusing on 1.16.4. the 1.12.2 version will be backported when I finish fixing bugs in 1.16.4
