### ISSUE TITLE
1.12.2 ERROR MOHIST SERVER SPIGOT/FORGE CRASH

### ISSUE THREAD

**Issue by imkappa** [Yesssssman/epicfightmod#224]
https://www.youtube.com/watch?v=PVGudm-fNLg
basically the problem is this. It happens with every other weapon but in other weapons just the attack mode is giving problem and not working. This is the latest log:
[latest.log](https://github.com/Yesssssman/epicfightmod/files/6404315/latest.log)

**Comment by imkappa** [comment]
basically the problem is this. It happens with every other weapon but in other weapons just the attack mode is giving problem and not working (no errors can seen in logs or crash reports)

**Comment by imkappa** [comment]
Server Mods
![mods1](https://user-images.githubusercontent.com/82937403/116674718-abb2f300-a9ad-11eb-9d16-ec99455424c8.PNG)

Server Plugins
![plugins](https://user-images.githubusercontent.com/82937403/116674768-ba99a580-a9ad-11eb-804b-bd0322e80d09.PNG)

Client Mods
![clientside mods](https://user-images.githubusercontent.com/82937403/116674803-c4230d80-a9ad-11eb-9e59-5dea1a454ef5.PNG)

**Comment by imkappa** [comment]
if u delete player data it will change to normal but if u do it again, it happens again

**Comment by imkappa** [comment]
This is the latest log
[latest.log](https://github.com/Yesssssman/epicfightmod/files/6404296/latest.log)

**Comment by WerelWolf** [comment]
Yess, I have the same problem, the error is only in the mod is a server crash, we were unable to use the mod when we relogged many errors when attacking

**Comment by imkappa** [comment]
yes thats true, its not just with weapons it makes it with fists too, but in fists just atacking diasbles
