### ISSUE TITLE
Problem with version 1.12.2 in server of Aternos (Magma)

### ISSUE THREAD

**Issue by ImDoggy** [Yesssssman/epicfightmod#228]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
Contact their authors BEFORE contacting forge

// Don't do that.

Time: 5/2/21 11:06 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.minecraft.network.datasync.EntityDataManager.func_187225_a(EntityDataManager.java:151)
	at maninthehouse.epicfight.capabilities.entity.LivingData.getStunArmor(LivingData.java:302)
	at maninthehouse.epicfight.capabilities.entity.player.PlayerData.updateOnServer(PlayerData.java:96)
	at maninthehouse.epicfight.capabilities.entity.LivingData.update(LivingData.java:134)
	at maninthehouse.epicfight.capabilities.entity.player.PlayerData.update(PlayerData.java:118)
	at maninthehouse.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:85)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:535)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2425)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:253)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:482)
	at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:566)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:1310)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:467)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:240)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.network.datasync.EntityDataManager.func_187225_a(EntityDataManager.java:151)
	at maninthehouse.epicfight.capabilities.entity.LivingData.getStunArmor(LivingData.java:302)
	at maninthehouse.epicfight.capabilities.entity.player.PlayerData.updateOnServer(PlayerData.java:96)
	at maninthehouse.epicfight.capabilities.entity.LivingData.update(LivingData.java:134)
	at maninthehouse.epicfight.capabilities.entity.player.PlayerData.update(PlayerData.java:118)
	at maninthehouse.epicfight.events.EntityEvents.updateEvent(EntityEvents.java:85)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_94_EntityEvents_updateEvent_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:190)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:535)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2425)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:253)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 30
	Entity Name: ImDoggay
	Entity's Exact location: 743.30, 64.00, 195.24
	Entity's Block location: World: (743,64,195), Chunk: (at 7,4,3 in 46,12; contains blocks 736,0,192 to 751,255,207), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:482)
	at net.minecraft.server.management.PlayerList.playerLoggedOut(PlayerList.java:566)
	at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:1310)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:467)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:240)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1013)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:461)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:865)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:737)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Magma Version: 48ec0a1
	Operating System: Linux (amd64) version 5.4.0-52-generic
	Java Version: 1.8.0_272, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1383167280 bytes (1319 MB) / 2035286016 bytes (1941 MB) up to 2035286016 bytes (1941 MB)
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx2100M -Xms1050M
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version              | Source                                        | Signature                                |
	|:------ |:--------------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2               | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                   | 9.42                 | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                   | 8.0.99.99            | server.jar                                    | None                                     |
	| LCHIJA | forge                 | 14.23.5.2855         | server.jar                                    | None                                     |
	| LCHIJA | deconstruction        | 3.0.4                | [MC1.12.2]DeconTable-3.0.4.jar                | None                                     |
	| LCHIJA | additional_lights     | 1.12.2-1.2.1         | additional_lights-1.12.2-1.2.1.jar            | None                                     |
	| LCHIJA | appleskin             | 1.0.14               | AppleSkin-mc1.12-1.0.14.jar                   | None                                     |
	| LCHIJA | baubles               | 1.5.2                | Baubles-1.12-1.5.2.jar                        | None                                     |
	| LCHIJA | llibrary              | 1.7.20               | llibrary-1.7.20-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCHIJA | mowziesmobs           | 1.5.8                | mowziesmobs-1.5.8.jar                         | None                                     |
	| LCHIJA | patchouli             | 1.0-23.6             | Patchouli-1.0-23.6.jar                        | None                                     |
	| LCHIJA | bewitchment           | 0.22.63              | bewitchment-1.12.2-0.0.22.64.jar              | None                                     |
	| LCHIJA | biomesoplenty         | 7.0.1.2444           | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar | None                                     |
	| LCHIJA | bloodmoon             | 1.5.3                | Bloodmoon-MC1.12.2-1.5.3.jar                  | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCHIJA | bookshelf             | 2.3.590              | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | buildcraftlib         | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftcore        | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftbuilders    | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcrafttransport   | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftsilicon     | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftcompat      | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftenergy      | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftfactory     | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | buildcraftrobotics    | 7.99.24.8            | buildcraft-all-7.99.24.8.jar                  | None                                     |
	| LCHIJA | carryon               | 1.12.3               | carryon-1.12.2-1.12.4.16.jar                  | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
	| LCHIJA | chisel                | MC1.12.2-1.0.2.45    | Chisel-MC1.12.2-1.0.2.45.jar                  | None                                     |
	| LCHIJA | clumps                | 3.1.2                | Clumps-3.1.2.jar                              | None                                     |
	| LCHIJA | cosmeticarmorreworked | 1.12.2-v5a           | CosmeticArmorReworked-1.12.2-v5a.jar          | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCHIJA | craftstudioapi        | 1.0.0                | CraftStudio-1.0.0.93-mc1.12-alpha.jar         | None                                     |
	| LCHIJA | cyclopscore           | 1.6.7                | CyclopsCore-1.12.2-1.6.7.jar                  | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCHIJA | doggytalents          | 1.15.1.6             | DoggyTalents-1.12.2-1.15.1.6.jar              | None                                     |
	| LCHIJA | dungeonsmod           | 1.12.2-1.0.6         | DungeonsMod-1.12.2-1.0.6.jar                  | None                                     |
	| LCHIJA | eplus                 | 5.0.176              | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | epicfight             | 1.12.2-2.0.0         | EpicFightMod-1.12.2-2.2.0.jar                 | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                      | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.13.0.183    | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
	| LCHIJA | extrautils2           | 1.0                  | extrautils2-1.12-1.9.9.jar                    | None                                     |
	| LCHIJA | gravestone            | 1.10.3               | gravestone-1.10.3.jar                         | None                                     |
	| LCHIJA | ichunutil             | 7.2.2                | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | infernalmobs          | 1.7.6                | InfernalMobs-1.12.2.jar                       | None                                     |
	| LCHIJA | inventorytweaks       | 1.64+dev.151.822d839 | InventoryTweaks-1.64+dev.151.jar              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHIJA | ironchest             | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCHIJA | morpheus              | 1.12.2-3.5.106       | Morpheus-1.12.2-3.5.106.jar                   | None                                     |
	| LCHIJA | mutantbeasts          | 1.12.2-1.0.2         | MutantBeasts-1.12.2-1.0.2.jar                 | None                                     |
	| LCHIJA | mmm                   | 1.0.8                | mutatedmobs-1.0.8.jar                         | None                                     |
	| LCHIJA | portalgun             | 7.1.0                | PortalGun-1.12.2-7.1.0.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | xreliquary            | 1.12.2-1.3.4.796     | Reliquary-1.12.2-1.3.4.796.jar                | None                                     |
	| LCHIJA | roguelike             | 1.8.0                | RoguelikeDungeons-1.12.2-1.8.0.jar            | None                                     |
	| LCHIJA | tektopia              | 1.1.0                | tektopia-1.1.0.jar                            | None                                     |
	| LCHIJA | travelersbackpack     | 1.0.35               | TravelersBackpack-1.12.2-1.0.35.jar           | None                                     |
	| LCHIJA | treechopper           | 1.2.4                | TreeChopper-1.12.2-1.2.4.jar                  | None                                     |
	| LCHIJA | uppers                | 0.0.6                | Uppers-0.0.6.jar                              | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.151.jar)
  invtweaks.forge.asm.ContainerTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
BewitchmentFMLLoadingPlugin (bewitchment-1.12.2-0.0.22.64.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Player Count: 1 / 5; [EntityPlayerMP['ImDoggay'/30, uuid='dcda5877-44aa-33f1-b70d-ef35d1500e41', l='world', x=743.30, y=64.00, z=195.24, cx=46, cd=12, tl=179791, v=true, d=false](ImDoggay at 743.3000000119209,64.0,195.2425459505408)]
	Is Modded: Definitely; Server brand changed to 'Magma'
	Type: Dedicated Server (map_server.txt)

**Comment by ImDoggy** [comment]
Every time I try to join the server it instantly crash and this is the crash report, I don't know what to do. Pls help, this mod is too epic to left out.

**Comment by WerelWolf** [comment]
i have the same problem https://github.com/Yesssssman/epicfightmod/issues/224

**Comment by ImDoggy** [comment]
> i have the same problem #224

Were you able to solve the problem or what are you doing with the server now?

**Comment by WerelWolf** [comment]
I didn't get it I'm waiting for an answer from the owner
