### ISSUE TITLE
1.16.5 - 36.0.42 load Crash

### ISSUE THREAD

**Issue by OriginalGone** [Yesssssman/epicfightmod#23]
I just want to first start off my saying this mod looks amazing, right now its currently unclear why its happening, I'm currently using this mod to play with friends with couple other mods on our own server, but I had to remove it due to it crashing when loading the world, only one of my friends was able to join perfectly, but me and my other friend who was on at the time also tried it and it as well crashed him. I tried to take away mods to see if it where clashing and no, sadly it was the fight mod that crashed the game when loading the game. I tried to delete my Launcher and re installed it to see if it let me and  nothing changed, still crashed. I was hoping the new version released 18 hours ago would fish it but it sadly didn't, still making me and my other friend crash and letting 2 other friends load in just fine. If anyone has any idea why it would be happening and any solutions to help please share.

**Comment by Yesssssman** [comment]
Do you have crash report? I'll inspect the reason if you attach it.

**Comment by OriginalGone** [comment]
> Do you have crash report? I'll inspect the reason if you attach it.

This is the crash report, My game loaded and once I moved it crashed.
[crash-2021-01-05_13.57.08-server.txt](https://github.com/Yesssssman/epicfightmod/files/6036728/crash-2021-01-05_13.57.08-server.txt)

**Comment by Yesssssman** [comment]
You're trying to execute from minecraft 1.15.2. you should execute it in 1.16.4 version.

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2

**Comment by OriginalGone** [comment]
![image](https://user-images.githubusercontent.com/79585894/109020852-f64b8280-767f-11eb-8b15-cfd63502ed23.png)
that's weird, I'm currently using 1.16.5, also I'm using 36.0.7 of forge sorry bout that. I don't get why it would say I'm using 1.15, unless it could be the forge version or Technic it self causing the problem.

**Comment by Yesssssman** [comment]
Or maybe there is a problem with the server. you should take a look at a friend who has successfully joined the game.

**Comment by OriginalGone** [comment]
> Or maybe there is a problem with the server. you should take a look at a friend who has successfully joined the game.

well the crash log is from loading a single player game, I'd look more into it and send feedback if I find the issue

**Comment by OriginalGone** [comment]
> Or maybe there is a problem with the server. you should take a look at a friend who has successfully joined the game.

[crash-2021-02-24_08.41.14-client.txt](https://github.com/Yesssssman/epicfightmod/files/6037230/crash-2021-02-24_08.41.14-client.txt)
this is another crash report if you'd like to take a look at it, this time showing the version id of 1.16.5

**Comment by Yesssssman** [comment]
OK.. can you check if the crashing solved when you remove only my mod?

**Comment by Yesssssman** [comment]
I can't find the specific code that occurs problem in my mod from crash report. It's kinda global issues from minecraft.

**Comment by jklw10** [comment]
sometimes the logs after the crash report also reveal something.
