### ISSUE TITLE
I figured out the problem

### ISSUE THREAD

**Issue by TopD77** [Yesssssman/epicfightmod#230]
Me and a friend of mine decided to make a modded SMP with a bunch of mods in it. When we added the MCDoom mod, we figured out that it was messing with the armors when mixed with this mod. Basically the Epic Fight Mod messes with the textures of some custom armors, an issue that is known for quite a while. But when we installed the Abyss mod, the armors were working just fine. So we looked into the mods' files and we found the problem. MCDoom armors are dual layered, whereas the Abyss armors have only one layer. But then we saw that one of the Abyss armors has a hat too and is working fine as well. That led us to the conclusion that the Epic Fight Mod is made for armors with a png texture of 64x32, which is the dimensions for single layered skins/armors (with or without a hat). Double layered armors are 64x64, which causes the mod to compress the image into a 64x32 one and then use it like that. Which explains the messy texture. So what can you do? Well, you can edit the textures using Photoshop, to turn the armors into single layered ones with dimensions 64x32, either by removing the outer layer, or pasting it on top of the inner one. You can still keep the hat though. What can the developers do? Well, I think they need to remake the armor animations for double layered armors.

**Comment by ScualoYeln** [comment]
grcias uwu
