### ISSUE TITLE
Animations are not compatible

### ISSUE THREAD

**Issue by Maxion78** [Yesssssman/epicfightmod#235]
### Animations make some issue with other mods, for example : 
**Hats** : hats are invisible
**Quark (emotes)** : emotes doesn't work 
**Curios** : All mods items related to curios are not visible on the player
_That would be so good if someone can fix all of that (=_

**Comment by lesero** [comment]
I have the same problem but.. i would add 1 thing. Traveler's backpack doesn't work from it aswell. i tested it and removed the epic fight mod and everything worked fine. its probly problem from animations that exist in epic fight mod.

**Comment by Maxion78** [comment]
> I have the same problem but.. i would add 1 thing. Traveler's backpack doesn't work from it aswell. i tested it and removed the epic fight mod and everything worked fine. its probly problem from animations that exist in epic fight mod.

Yes, epic fight cause all modded player models not to work, but I just found that you can filter animation in the config options, you just lose some animation, but it works fine with other mods.

**Comment by ghiltonT** [comment]
eso me interesa como hago eso? y sabes como puedo poner los tridentes como el tridente de ice and fire?

**Comment by gabycapo** [comment]
Como dice el de arriba si activas el filtrado de animaciones te deja usar varias cosas sin errores que seria en el servidor o en el minecraft .minecraft  /config   y el archivo epicfight-client   configurar el filtrado de animacion en true y guardas
