### ISSUE TITLE
1.14.4 crash when move or left click

### ISSUE THREAD

**Issue by TronXyrzX** [Yesssssman/epicfightmod#24]
Every time i load up a world and do pretty much anything the game crashes. I play on Mac(iMac 2019) and tried using the oldest and newest 1.14.4 version of forge but nothing worked. I am only using the mod by it's self just to be clear. What version of the 1.14.4 forge should i use?

**Comment by Yesssssman** [comment]
Versions below 1.16.4-2.0.0 were made without considering the operation in the Mac environment. Please let me know if the same problem keep occurs with a latest version. If it works fine, please wait until the old versions updated!
