### ISSUE TITLE
How do I add weapons using the configuration file in 1.12.2?

### ISSUE THREAD

**Issue by Danicool09** [Yesssssman/epicfightmod#240]
I m making a server using this mod and i want to add Spartan Weaponry weapons, but the weapons dont work, the configuration file is this
![image](https://user-images.githubusercontent.com/83871340/117541306-95dba880-b013-11eb-92d2-1869cdfb38fe.png)

**Comment by IndieSN** [comment]
why is this closed without a sigle response? many of us have the same problem
