### ISSUE TITLE
[bug] Some mods are not displayed

### ISSUE THREAD

**Issue by ChihoiTse** [Yesssssman/epicfightmod#246]
- The Traveller's Backpack does not show
- Quark's rune enchantment is no longer displayed

**Comment by Aboslut** [comment]
it makes the same for every mods that add a cosmetic or animation, please fix

**Comment by downnfall** [comment]
Backtools mod doesn't work either.

**Comment by Aboslut** [comment]
> Backtools mod doesn't work either.

its doesnt work with every mods that adds cosmetic :/

**Comment by ChihoiTse** [comment]
The author does not reply to the message, and the game crashes due to the bug of the mod, so I have removed the mod and will turn off Issues
