### ISSUE TITLE
[bug] can't build iron golem

### ISSUE THREAD

**Issue by CootieDwagon** [Yesssssman/epicfightmod#247]
Using 1.16.5 and only the epic fight mod with latest forge version and I can not create an iron golem.

I can build it, but it will not "pop" into a living one. Just a normal T shape of iron blocks with a carved pumpkin head now. I don't know why.

**Comment by R-A-I-D-E-N** [comment]
The same thing happens to me bro, unfortunately the guy who created the mod has not taken the time to see the problems ..
