### ISSUE TITLE
What's causing this?

### ISSUE THREAD

**Issue by iShaday** [Yesssssman/epicfightmod#256]
Here's a pastebin of my crashlog

https://pastebin.com/ptnmPVZt

**Comment by TranquilStar** [comment]
is this on a server or is this local (singleplayer)? if so did you test to see if it was any of the plugins that caused this error, if it is singleplayer did you test to see if any mods are incompatible with one another. Now it might also be a possibility that Dynamic Surroundings can cause this crash, but I would copy over the mods from your server and create a single-player world, and test to see if it works.

if it doesn't crash check your plugins, if it does then try and removing Dynamic Surroundings from the mods.

What I usually do is add the mod, the one I want the most, and in your case EpicFightMod. Now try and add one mod at a time
to see if any of them crash, if so you may have to remove them.

now for the plugins, if they could possibly be the reason to crash, then it might take a while but you should do the same as I suggested for the mods.

**Comment by TranquilStar** [comment]
Taking a second look it is most likely a mod incompatibility with one of your other mods
