### ISSUE TITLE
Invisible character

### ISSUE THREAD

**Issue by FootLong0106** [Yesssssman/epicfightmod#26]
My character becomes invisible when i use this mod or sometimes crash i am using 1.16.4

**Comment by Yesssssman** [comment]
Which version you using now?

**Comment by FootLong0106** [comment]
> Which version you using now?

1.16.4 forge 35.1.37

**Comment by Yesssssman** [comment]
I meant the version of mod. I've heard some problems like you just before 1.6.4-2.0.0 version.

**Comment by FootLong0106** [comment]
> I meant the version of mod. I've heard some problems like you just before 1.6.4-2.0.0 version.

im using the 2.0.3 version

**Comment by Yesssssman** [comment]
ok please leave a crash report or pictures of problem.

**Comment by FootLong0106** [comment]
> ok please leave a crash report or pictures of problem.

i fixed it the problem is becuz i have n outdated version of optifine
