### ISSUE TITLE
I'm proposing to make your mod the best.

### ISSUE THREAD

**Issue by HongMint88** [Yesssssman/epicfightmod#261]
I've used all the other animation mods, but you're the best. So I really want to use it, but my server is using Armour's workshop mod. But when I install your mod, I can't see the wearing equipment made from Armour's workshop. So I'd like to make a suggestion, if I toggle from your mod to non-combat mode, can I cut off your animation itself? I want your animation to be applied only in combat mode. Then it is compatible with other mods.

**Comment by Naelim** [comment]
There's an option in config called filter animation. It does exactly that

**Comment by HongMint88** [comment]
> There's an option in config called filter animation. It does exactly that

I know what you're talking about. However, switching to the toggle currently does not show Armour's workshop fitting.

**Comment by HongMint88** [comment]
> There's an option in config called filter animation. It does exactly that

I know what you're talking about, but what I'm saying is that you should look like a toggle to someone else. Only on my screen do I look like I'm wearing Armour's workshop and still naked to others.
