### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by iShadowyz** [Yesssssman/epicfightmod#27]
Hello, I think my world crashes because of its mod, more specifically because of Husky's fighting animation, I spawned several of it to fight with a golem and that's it, when they get close to the crash server, when I removed the mod and I did the same thing again, there was no problem.

[crash-2021-02-25_14.38.51-server.txt](https://github.com/Yesssssman/epicfightmod/files/6044931/crash-2021-02-25_14.38.51-server.txt)

**Comment by Yesssssman** [comment]
Hmm.. Is there any extended husk mobs in mod? I want to know if this is a conflict between mods or just fault of my mod.

**Comment by iShadowyz** [comment]
There is nothing that changes the husky itself, but there are some mods around it, like Husky Spawn and Champions
