### ISSUE TITLE
Crash ticking entity Epicfight Hurt event at entity zombie

### ISSUE THREAD

**Issue by koad96** [Yesssssman/epicfightmod#272]
[crash-2021-05-26_00.40.28-server.txt](https://github.com/Yesssssman/epicfightmod/files/6542771/crash-2021-05-26_00.40.28-server.txt)

Pastebin: https://pastebin.com/CA9vgMrx

This results in a stackOverflow crash. Not sure if its the combination of mods used or Epicfightmod but thought maybe this could be fixed somehow here.

**Comment by VolgaLVI** [comment]
I had the same issue
