### ISSUE TITLE
Other mod's animation overwritten by Epic fight mod

### ISSUE THREAD

**Issue by th3n0mn0m2** [Yesssssman/epicfightmod#284]
This example refers to the [paragliders mod](https://www.curseforge.com/minecraft/mc-mods/paragliders?__cf_chl_jschl_tk__=0da6687b3b5314dfa11d2694a63017f738ea23c6-1622465876-0-AcjxN0DpIpjJrnT-XbFQl_F1QqIjpg6NCXT6ZF6mUq1tz9jHALmjkWdX40kSp1tZ0dD6M9QuqJj_LK1hz4AWoSvxin-U5oLQf5wArmvUJE2mrMgYee_3_61-DVwcVEwkebDVLA89fKeh25ymBRTZUBnEawIOX08s23dw04LYkLmBd9BT2DDdpiinW4ci3Gag_3ROTC0lj3m2U93gAzJkoeeeJTJ8LxPxSdyT-DtrQaopEagesz_TXq3C0nPRLChDDgYOCU_mzSMexduL2Yt_zUZiG12kajG_gCfk_uPoE5pLe6z0AOwQHFgw5durhOLzd3e1LS52QJxQ6FM96hdyESkfqrmYk6qF6yQmb8A2hYgpZiBzpThDtvwMCHZwkP-6KebCe2TmrUrItLxnympZV80iK3vVX44xm4z_7hzov873_ElEzVLkxsxixiLUUd3j2tsF1b39512TzwzxxbiSmNwQcuaD9WtJN1cYllEFK1srZzTnz6bOlUV5-a2LpTaWqQ).

When I glide with the paraglider, there is a walking animation instead of the mod's gliding animation. Is there a way that when there is a custom animation from the paraglider mod (or another mod), it chooses the paraglider mod's (or another mod's) animation.

**Comment by TotallyCooki** [comment]
https://github.com/Yesssssman/epicfightmod/issues/291#issue-917424808
Duplicate issue

**Comment by Aerhtjiz** [comment]
is there a way to fix that duplication issue
