### ISSUE TITLE
Game crashes when switching to combat mode on a server when optifine is installed and animation filtering is set to true

### ISSUE THREAD

**Issue by Acapered** [Yesssssman/epicfightmod#287]
CHECK EDIT
when I try to switch to combat mode on a server using R, the game crashes immediately. both the client and server have epic fight installed. I also have a few other mods installed. my guess is optifine is incompatible with this mod as this started happening when I installed optifine. It also could be the server.

Edit: Apparently, when optifine is installed, animation filtering is set to true, and you are playing on a server, the game will crash when you enter combat mode by pressing R. ???????

**Comment by tripleee** [comment]
Sounds similar to https://gaming.stackexchange.com/questions/386727/java-null-exception-errors-how-to-fix
