### ISSUE TITLE
Modded Mobs

### ISSUE THREAD

**Issue by CodySpirits** [Yesssssman/epicfightmod#29]
This mod doesn't appear to function well at all with modded mobs. With Dungeon Mobs, a mod that adds Minecraft Dungeon mobs to the game, several of the mobs are able to damage you while you attack them, and are not able to be stunned by your attacks, making it likely the player will die if they try to attack a non-vanilla mob.

**Comment by Yesssssman** [comment]
It's not quite easy to make compatible with mobs from other mod especially when they're custom shaped. I'll make configuration system for modded entities, but it'll only work with entity which has vanilla model.
