### ISSUE TITLE
[Request] Configs to disable/move GUI elements

### ISSUE THREAD

**Issue by aaronhowser1** [Yesssssman/epicfightmod#292]
![image](https://user-images.githubusercontent.com/15698722/121646357-da1af800-ca5a-11eb-94e4-60196e74453b.png)

I don't need to see the HP at the top, it doesn't help at all. I also don't need to see the red triangle, since afaik there's no lock-on system. And honestly, a way to get rid of the health bar would be nice as well. I don't like the way it looks, and other mods already show mob health.

**Comment by L4mbads** [comment]
the option for disabling pointer and health bar is already included in "epicfight-client.toml" config file.

**Comment by aaronhowser1** [comment]
I 100% didn't notice that there was an epicfight-client, my bad 😅
