### ISSUE TITLE
 is there a solution to fix the problem of armor texture when it come from a mod?

### ISSUE THREAD

**Issue by PetitAkihiko** [Yesssssman/epicfightmod#3]
How to fix the armor texture problem when they come from a mod

**Comment by Yesssssman** [comment]
Are you saying about custom armor?

**Comment by TurkishAhmet4545** [comment]
> How to fix the armor texture problem when they come from a mod

Are you seeing this problem on new versions of the mod ?
If yes,i dont have idea.
But if no,i recommend you to try newest versions of the mod.

**Comment by jeroen11122005** [comment]
im having the same problem and its happening with almost every armor set in my modpack except for the armor from immersive engineering for some reason and armor doesn't have a configurable weight value either heres some screenshots:
psimetal
![2021-02-22_20 47 29](https://user-images.githubusercontent.com/42644683/108765113-b1c2c880-7553-11eb-9a85-e0f9c7c05b15.png)
red dragon scale
![2021-02-22_20 47 50](https://user-images.githubusercontent.com/42644683/108765135-b9826d00-7553-11eb-88e7-fe941aa70ae3.png)
steel
![2021-02-22_20 48 14](https://user-images.githubusercontent.com/42644683/108765142-bb4c3080-7553-11eb-9cf0-69361d4150d9.png)
mekasuit
![2021-02-22_20 48 48](https://user-images.githubusercontent.com/42644683/108765145-bc7d5d80-7553-11eb-9f60-748c0331d068.png)

**Comment by Yesssssman** [comment]
the custom armors will be broken cause I only made a animated model that compatible with vanilla armor model. to solve this problem, I have to make animated model for whole custom armors but it's gonna very difficult.

**Comment by Yesssssman** [comment]
![image](https://user-images.githubusercontent.com/79469058/108893001-e9189e80-7653-11eb-8afb-db9536bfe52e.png)

This is similar issue with mo' bends mod which adds new animation for minecraft just like mine.

**Comment by PetitAkihiko** [comment]
ok 
in fact it would be limit impossible and even if you would make its compatible with certain mods but there will still be too much has developed
