### ISSUE TITLE
A visual bug in the latest alpha version

### ISSUE THREAD

**Issue by someguy324231** [Yesssssman/epicfightmod#304]
Holding a dagger in the left hand without holding anything in the right makes the model disappear or render in a wierd way.
![2021-06-17_22 38 17](https://user-images.githubusercontent.com/85259579/122472524-01c11180-cfc1-11eb-8722-45360d8c579f.png)
![2021-06-17_23 06 16](https://user-images.githubusercontent.com/85259579/122472529-04bc0200-cfc1-11eb-84d5-8c6b84ab2a03.png)
 
(p.s. I think you should talk more about your patreon. Lots of people don't know about it, and you deserve to get paid)

**Comment by Yesssssman** [comment]
Thanks for the report! but the second screenshot is what I intended because there's no animation that wielding a dagger offhand so I made it invisible to notify the player.

**Comment by someguy324231** [comment]
> Thanks for the report! but the second screenshot is what I intended because there's no animation that wielding a dagger offhand so I made it invisible to notify the player.

No problem, thank you for your amazing work <3
