### ISSUE TITLE
Error Download to Forge

### ISSUE THREAD

**Issue by TailsDoll2537** [Yesssssman/epicfightmod#311]
Well the problem is this, i download the 2.2.0/2.1.3 version of 1.12.2, but, what i join in the 1.12.2 Minecraft, the mod version it's Alpha 2.0.0 version, what i have to do?

**Comment by Yesssssman** [comment]
I forgot to change the version that appeared in the forge mod list screen. Although it says 2.0.0 that's actually the 2.1.3 version!

**Comment by TailsDoll2537** [comment]
Oh good, i scare whit that X"D
