### ISSUE TITLE
4.0.1 version causing huge Lag.

### ISSUE THREAD

**Issue by StLankowski** [Yesssssman/epicfightmod#320]
Epic Fight Mod 1.16.5 4.0.1 is causing a massive drop in fps, whilst previous versions didn't had that issue.

**Comment by StLankowski** [comment]
same problem with 4.0.2 :(

**Comment by Yesssssman** [comment]
Did you test it only install Epic Fight Mod?

**Comment by StLankowski** [comment]
yes. withnothig else installed, it still crated a huuge drop in fps.

**Comment by Yesssssman** [comment]
Can you post the video? I can't find any information about your problem.
