### ISSUE TITLE
（BUG)Climbing the ladder can only show one direction

### ISSUE THREAD

**Issue by GalaxyZEROX** [Yesssssman/epicfightmod#323]
![2021-06-25_02 10 07](https://user-images.githubusercontent.com/73332842/123312430-e8890980-d55a-11eb-900d-48a4e52d7fcb.png)

**Comment by Yesssssman** [comment]
Version?

**Comment by GalaxyZEROX** [comment]
> 版本？

1.12.2

**Comment by GalaxyZEROX** [comment]
> Version?

1.12.2

**Comment by Yesssssman** [comment]
Umm... maybe your forge-server option "fullBoundingBoxLadders" have set to true. This will be fixed in the next update!
