### ISSUE TITLE
modded weapons won't work 1.12.2 latest forge version

### ISSUE THREAD

**Issue by Sageking10** [Yesssssman/epicfightmod#325]
Modded weapons won't act like a sword in fight mode.

**Comment by Sageking10** [comment]
![2021-06-24_19 51 20](https://user-images.githubusercontent.com/48606472/123346152-a2fe1980-d525-11eb-81d3-da4c51b9dc80.png) holding modded sword
![2021-06-24_19 51 16](https://user-images.githubusercontent.com/48606472/123346184-b5785300-d525-11eb-8199-e6f5ea36bec2.png) holding vanilla sword

**Comment by Yesssssman** [comment]
Have you set up something in the .toml file?

**Comment by GalaxyZEROX** [comment]
I have also encountered this problem. In version 2.1.2, other mod weapons can be used to move swords normally (at this time, config can't be used to change the combat mode of weapons normally). . .
However, later versions can only use fist combat mode when using other mod weapons. . . . .

**Comment by Yesssssman** [comment]
> I have also encountered this problem. In version 2.1.2, other mod weapons can be used to move swords normally (at this time, config can't be used to change the combat mode of weapons normally). . .
> However, later versions can only use fist combat mode when using other mod weapons. . . . .

Could you post the config file? I checked the config file works well with spartan weaponry mod. If some mods have a problem with Constructing configuration file, I'll fix it as soon as possible.

**Comment by GalaxyZEROX** [comment]
> > I have also encountered this problem. In version 2.1.2, other mod weapons can be used to move swords normally (at this time, config can't be used to change the combat mode of weapons normally). . .
> > However, later versions can only use fist combat mode when using other mod weapons. . . . .
> 
> Could you post the config file? I checked the config file works well with spartan weaponry mod. If some mods have a problem with Constructing configuration file, I'll fix it as soon as possible.

# Configuration file

custom {

    custom_weaponry {

        sample_weapon1 {
            D:armor_negation=0.0
            D:impact=0.5
            I:max_strikes=1
            S:registry_name=modid:registryname

            # Valid values:
            # AXE
            # FIST
            # HOE
            # PICKAXE
            # SHOVEL
            # SWORD
            # SPEAR
            # GREATSWORD
            # KATANA
            S:weapon_type=SWORD
        }

        sample_weapon2 {
            S:registry_name=modid:starwars:lightsaber_blue

            # Valid values:
            # AXE
            # FIST
            # HOE
            # PICKAXE
            # SHOVEL
            # SWORD
            # SPEAR
            # GREATSWORD
            # KATANA
            S:weapon_type=SWORD

            onehand {
                D:armor_negation=0.0
                D:impact=0.5
                I:max_strikes=1
            }

            twohand {
                D:armor_negation=0.0
                D:impact=0.5
                I:max_strikes=1
            }

        }

    }

    custom_armor {

        sample_armor {
            S:registry_name=modid:registryname
            D:stun_armor=0.0
            D:weight=0.0
        }

    }

}

**Comment by GalaxyZEROX** [comment]
I don't know if my config is filled in correctly. If it is wrong, please issue a sample config (subject to "nano_saber" in Industrial Craft 2)

**Comment by Yesssssman** [comment]
> I don't know if my config is filled in correctly. If it is wrong, please issue a sample config (subject to "nano_saber" in Industrial Craft 2)

modid:starwars:lightsaber_blue 

Modify this line to

starwars:lightsaber_blue

If it still not work, Please notify me again.

**Comment by GalaxyZEROX** [comment]
> > I don't know if my config is filled in correctly. If it is wrong, please issue a sample config (subject to "nano_saber" in Industrial Craft 2)
> 
> modid:starwars:lightsaber_blue
> 
> Modify this line to
> 
> starwars:lightsaber_blue
> 
> If it still not work, Please notify me again.

Problem solved, thank you

**Comment by Yesssssman** [comment]
Np! 😄
