### ISSUE TITLE
Longsword bug in [EpicFightMod-1.16.5-4.0.2]

### ISSUE THREAD

**Issue by someguy324231** [Yesssssman/epicfightmod#327]
Using longsword's special skill disables sprinting.

https://user-images.githubusercontent.com/85259579/123412095-7ee81a00-d5b1-11eb-85b2-cfa396ff3c00.mp4

**Comment by Yesssssman** [comment]
It's actually a skill effect.

**Comment by someguy324231** [comment]
> It's actually a skill effect.

I know, but it persists even when I no longer have a longsword in my hand. The ability to sprint only returns when I reset the game or hold a weapon of a different kind

https://user-images.githubusercontent.com/85259579/123434347-ab5d5f80-d5cc-11eb-8dbd-69dfaafbe758.mp4

.

**Comment by Yesssssman** [comment]
It's because skill is still activated as you can see on GUI. Um... I'll find a proper way to solve this problem.

**Comment by someguy324231** [comment]
Thank you! :3
