### ISSUE TITLE
The animation of bow has something wrong

### ISSUE THREAD

**Issue by hsdsdddd** [Yesssssman/epicfightmod#329]
![无标题](https://user-images.githubusercontent.com/86495252/123478083-864f0800-d631-11eb-9ae5-bfb5e1676bb3.png)

**Comment by Yesssssman** [comment]
A modded bow wasn't recognized as a bow. You should manually configure it.

**Comment by hsdsdddd** [comment]
How can I manually configure it？LIke this？
![image](https://user-images.githubusercontent.com/86495252/123505763-81bb3b80-d693-11eb-87e3-b75f65ac5ac8.png)

**Comment by hsdsdddd** [comment]
But the bow in the other mod can be used with the right animation.

**Comment by hsdsdddd** [comment]
Could you please tell me how can I manually configure it.

**Comment by hsdsdddd** [comment]
Could you please teach me how can I manually configure the bows and crossbows.

**Comment by someguy324231** [comment]
> Could you please teach me how can I manually configure the bows and crossbows.

https://youtu.be/aTEDYgWZrbg

**Comment by hsdsdddd** [comment]
> > 你能教我如何手动配置弓和十字弓吗？
> 
> https://youtu.be/aTEDYgWZrbg

Thank ,but I want to know how to manually configure the bows and crossbows ,there are just the ways of configuring close-in weapons in this video.
