### ISSUE TITLE
Thanks and questions/suggestions

### ISSUE THREAD

**Issue by KamiSami** [Yesssssman/epicfightmod#33]
(Sorry beforehand for my wall of text)

Hey, just wanted to thank you for this amazing mod. Am looking forward to see how this progresses in future if you plan to continue this more further. There are couple things i'd like to ask and suggest as i see so much potential of how this mod can get even past its greatness of its current state even further, question is pretty much this: Will there be more weapon variations and possibly more skills? And the other question or rather mention is: Will the combat get aiming sometime later? As..  I find it often hard to aim small mobs even that im directly looking at them or flying mobs that im normally supposed to hit, such as ender dragon at middle of portal. Now to my suggestions: If you implement more skills, perhaps they could be assigned to keybinds, either by leveling up using experience points (not levels, the exp itself) from vanilla minecraft exp system, and weapon abilities depending how much you are accustomed to the weapons you use. Next suggestion is: More config, cooldowns for rolls, charging speed (at least for current version) of ability, stun system configs which would make me wish to be able to change config for stun when performing special attack, i find myself often getting stunned before i can perform special ability to get rid of horde of zombies even with armor.  Maybe bit more clarification how to use the current config, i don't know how to separate the newly made config from eachother for example, im not good with this uh, coding language? I don't know what to call it... Eitherway, last suggestion: Breaking/deflecting arrows with katana by holding right click for example, by spinning katana at high speed infront of you, of if you do "perfect parry" with katana, instead of breaking the arrow it deflects back to enemy that shot it.

That's all i think for now, again, thanks for doing even this much with this mod, im having much more fun with combat using this mod in Minecraft!

**Comment by Alaberti** [comment]
Awesome mod! Just want to add in for suggestion consideration (since OP started a thread) animations for flying. I love the rest of the mod as-is, I'd just like a neat flying animation. Thanks for making this mod, it has actually changed how I play the game in a real meaningful way!

**Comment by koderian** [comment]
@Alaberti A flying animation would be awesome. Here's how Mo Bends did it in 1.12.2, it's like Superman. @Yesssssman, maybe take this as inspiration?
![4984da319d28b2c8359a24009be6eab1](https://user-images.githubusercontent.com/44537031/109567409-65164a80-7a89-11eb-9fe0-c5b8c74f9462.gif)
