### ISSUE TITLE
Crafting Longsword, Knuckles, Tachi, and Dagger is not possible

### ISSUE THREAD

**Issue by ImWulf** [Yesssssman/epicfightmod#336]
I haven't read anything on this issue, however, when I go try to craft the longsword, Tachi, knuckles, or the dagger, nothing shows up as craftable. I also have the "Too Many Items" mod which shows the recipes and even with that mod the recipes don't show up as possible. Would this be something with the version of the mod. The version I am on is "EpicFightMod-1.16.5-4.0.0-alpha." 

If anyone knows how to fix this issue please let me know. 

Thank you.

![Capture](https://user-images.githubusercontent.com/86545437/123533733-d9829280-d6e5-11eb-99bd-01ab401e1f20.JPG)

**Comment by Sidorov-Arseniy** [comment]
Update mod version

**Comment by Sidorov-Arseniy** [comment]
Use the new version of the mod
