### ISSUE TITLE
Question with 1.12.2 version of the mod

### ISSUE THREAD

**Issue by TheReaper77** [Yesssssman/epicfightmod#34]
So i have minecraft 1.12.2 and i have both this mod and Spartan Weaponry, i would like to know if theres any compatibility patch out there, if not, i would like to know if theres any way to add the weapons from that mod into this mod like how the 1.16 version compatibility mod exits, i went to the config folder and i noticed that theres no config file for this mod, is it anywhere else? is the custom weapon adding only supported for newer versions? anyway, great mod, definetely one of the best mods for minecraft!

**Comment by Yesssssman** [comment]
I would like to update 1.16.4 first. I'll add some functions that people wanted to me like first person battle, custom model render, etc. Then I'll backport everything to older version. Hope you understand me.

**Comment by TheReaper77** [comment]
Oh yes, absolutely understandable, i will be patiently waiting for that momment, keep up the good work.
