### ISSUE TITLE
NullPointerException: Ticking entity at maninhouse.epicfight.events.EntityEvents.hurtEvent(EntityEvents.java:122) 

### ISSUE THREAD

**Issue by aburone** [Yesssssman/epicfightmod#342]
I see several ticking entity errors but not this particular one referring hurtEvent

I was in the end, flying. So it was from something falling to the void or something like that

https://hastebin.com/ulikiwopit.rb

**Comment by Yesssssman** [comment]
Fixed in 4.1.0
