### ISSUE TITLE
Texture compatibility problem (IE, BM, Mekanism)

### ISSUE THREAD

**Issue by Ices63** [Yesssssman/epicfightmod#343]
Hello,

few armor visual of popular mods are invisible in 3.2.2 and 4.1.0.

Mods concerned :
- Immersive Engineering
- Blood Magic
- Mekanism

Thanks for watching this and have fun for the next !

**Comment by Yesssssman** [comment]
Custom armors have visual issues but It's very hard to fix cause Epic Fight uses an indifferent model from vanilla one.
