### ISSUE TITLE
[Bug] Parrying attacks with bare hands in [EpicFightMod-1.16.5-4.0.3]

### ISSUE THREAD

**Issue by someguy324231** [Yesssssman/epicfightmod#346]
Sorry to bother you again, but I noticed another bug with longsword's special skill.
I can still parry attacks even though I don't have a sword in my inventory (because the skill is still active).

https://user-images.githubusercontent.com/85259579/123710104-707a5680-d86e-11eb-8362-4a6051ec2e81.mp4

It's a minor thing, but I decided to report it anyway :3

**Comment by Yesssssman** [comment]
Thank you for reporting!
