### ISSUE TITLE
stun_armor or stunArmor

### ISSUE THREAD

**Issue by DPurple** [Yesssssman/epicfightmod#347]
in maninhouse/epicfight/entity/ai/attribute/ModAttributes.java line 20
MAX_STUN_ARMOR registered as "stun_armor"

in maninhouse/epicfight/config/ConfigManager.java line 38
generated a default config with "stunArmor"

just nothing serious

**Comment by Yesssssman** [comment]
Many configuration files have already been created, so I will not change them to reduce the inconvenience of modifying them.

**Comment by DPurple** [comment]
ok, got it
