### ISSUE TITLE
[Suggestion] Add config to disable all Player animations so we can use modded armors

### ISSUE THREAD

**Issue by bosambinja** [Yesssssman/epicfightmod#35]
This way people who like this mod but also want to use modded armors without them glitching out can use your mod. Basically, the config will have an option to disable all player animation changes (everything from the roll to weapon attacks) so that the player character will revert back to vanilla animations but enemy AI and animation changes will still be kept.

**Comment by Alaberti** [comment]
Have you tried the Cosmetic Armor Mod? Let's you hide individual armor pieces.

**Comment by bosambinja** [comment]
I've heard of the mod but at the end of the day, the issue is wanting to use your mod in tandem with modded armors. I don't want to hide the epic looking modded armors but instead, be able to rock them with the exaggerated swagger of Freddy Mercury

**Comment by Alaberti** [comment]
Oh, I'm not the mod dev, I was just offering that mod as an interim solution

**Comment by Yesssssman** [comment]
This is applied to 3.0.2! :)
