### ISSUE TITLE
[question] Is a Fabric version planned?

### ISSUE THREAD

**Issue by Felix14-v2** [Yesssssman/epicfightmod#351]
Is there even a small hope of ever seeing the Fabric version? Or do you work exclusively with Forge? 
The performance of my laptop does not allow me to play comfortably with Forge...

**Comment by Yesssssman** [comment]
Right now, there's no plan to export to fabric cause I have to update two projects at the same time (which really burdening task for me). And in my opinion, Epic Fight has more of an impact on performance than Forge.  It requires quite high performance.
