### ISSUE TITLE
1.16.5 Crashing issues

### ISSUE THREAD

**Issue by MaliceOfRites** [Yesssssman/epicfightmod#352]
![image](https://user-images.githubusercontent.com/86718025/123944889-80408a80-d995-11eb-86f4-01a16ac9efd7.png)

EpicfightMod is incompatible with one of these mods (not sure which) but dying with EFM installed causes an instant crash to the desktop

**Comment by Yesssssman** [comment]
Please attach the crash report.

**Comment by 5ully** [comment]
Fairly certain that the incompatible with corpse. Have had issues, but it does not hard crash, only makes the client unable to answer.  Included is the latest.log and debug
[debug.log](https://github.com/Yesssssman/epicfightmod/files/6760502/debug.log)
[latest.log](https://github.com/Yesssssman/epicfightmod/files/6760503/latest.log)

Have tested the incompatibility by disabling both and testing with only one of EFM/corpse active. There is no issues when only 1 of the 2 mods are active.
