### ISSUE TITLE
How to delete spider things ?

### ISSUE THREAD

**Issue by Skyexir** [Yesssssman/epicfightmod#353]
Hello ! 
First i want to say a huge thanks for this amazing mod !

Please can you explain how to remove spider changes from your mod ?
(to make it compatible with Spider 2.0)

I searched a lot but not found :(

**Comment by Yesssssman** [comment]
For now, there's no way to remove the behavior of Epic Fight for a particular creature.

**Comment by Skyexir** [comment]
Can you please add it? 🙏🏻🙏🏻🙏🏻 This is very important for the concept of my server 🥺
