### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by LakshyaKAChauhan** [Yesssssman/epicfightmod#355]
First I want to Tell You That I don't know English Because I am From India, So Please Ignore Mistakes In My issue

1. I cannot destroy entities like armor stand in Build and Attack Mode when there is any tool or any item in hand
2. In Survival Mode When I am Holding Left Mouse Button to make (Any Weapon)'s special Attack But It Dose Not Doing Any Thing 
    But In Creative mode it do its special attack
Questions:
1. What Is The use of the book in the mod

**Comment by XanTheMann** [comment]
Hi! In order to use your special attack you need to deal damage to mobs while in attack mode. While in attack mode, on the bottom right you should see your special attack's progress. At 100% you can hold left click and use your special attack.
