### ISSUE TITLE
Crash in server:  Exception ticking world  (entity mob: Zombie)

### ISSUE THREAD

**Issue by NahG07** [Yesssssman/epicfightmod#358]
[crash-2021-06-27_00.21.39-server.txt](https://github.com/Yesssssman/epicfightmod/files/6757228/crash-2021-06-27_00.21.39-server.txt)

**Comment by Yesssssman** [comment]
This crash is caused by incompatibility with the dungeons mobs mod. I sent the mod creator crash report and he said it will be fixed in a later version.

https://github.com/Thelnfamous1/Dungeons-Mobs/issues/27

**Comment by NahG07** [comment]
Oh, Thank you so much!
