### ISSUE TITLE
Set all sounds to Mono instead of Stereo

### ISSUE THREAD

**Issue by aaronhowser1** [Yesssssman/epicfightmod#361]
Almost all the sounds in the mod are Stereo, which causes problems with minecraft's sound engine. Mainly, they don't get quieter with distance. It also somewhat inflates the file size, but they're all less than a second long, so.

**Comment by Yesssssman** [comment]
Sorry but I'm not familiar with the sound system. I'll inspect this problem and tryna fix it.

**Comment by aaronhowser1** [comment]
Open the sound .ogg in Audacity (just drag and drop it in), then click the drop down
![image](https://user-images.githubusercontent.com/15698722/124421127-6a7ced80-dd26-11eb-9d24-f5e32ec9988f.png)
Click `Split Stereo to Mono`.
![image](https://user-images.githubusercontent.com/15698722/124421193-87192580-dd26-11eb-9484-416789218074.png)
Click the X on either of the new waves.
![image](https://user-images.githubusercontent.com/15698722/124421215-95ffd800-dd26-11eb-9846-7cb0673d8214.png)

Export it as an OGG
![image](https://user-images.githubusercontent.com/15698722/124421247-a748e480-dd26-11eb-9c67-c32df3df5c19.png)

Use this new .ogg instead of the old one. Repeat this for each one (close Audacity each time so it knows you're doing a different file).

**Comment by aaronhowser1** [comment]
Closing since this was fixed
