### ISSUE TITLE
Devloper Must Fix This By Adding This !!! Very Important

### ISSUE THREAD

**Issue by LakshyaKAChauhan** [Yesssssman/epicfightmod#363]
First I wan't To Tell You I am From India So My English Is Not 100% Accurate.

Please Read Full Thing Before Doing Anything.

1. When I am On My Boat Player's Leg's are Starting From Player's Body, Passing the Boat's Body, And Stops at Under The Boat.
    As Shown In Picture :-
![Glitch](https://user-images.githubusercontent.com/86772566/124348340-0283b580-dc07-11eb-8318-d3b39afb2593.png)

2. When I am Using Gsit Plugin With This Mod In My Server [If You Ask How I Use Plugin And Mods Together in 1.16.5 My Ans. Is 
    I Use A Server Software Called -->Mohist<-- That Runs Mods And Plugins Together ] And When I Sit on solid Block, Stair, Slab
    Player's Legs goes in that block.

(To Fix This Bug)
You should Make Many Sitting Animations
And Add Sitting Options
Types of Sitting Animations:-
1. Sitting Animation for when Player Is Sit On Solid Block
         My Idea for this animation:-
![model 3](https://user-images.githubusercontent.com/86772566/124348781-a8382400-dc09-11eb-9b0d-e9692831bf85.png)
2. Sitting Animation for when Player Is Sit On Stair
         My Idea for this animation:-
![model 1](https://user-images.githubusercontent.com/86772566/124348816-df0e3a00-dc09-11eb-9c8c-b60d8e258556.png)
3. Sitting Idea for when Player Is Sit On Slab
         My Suggestion for this animation:-
              {As Same As Sitting animation on Solid Block}
(Suggestion)
1. If You Are Adding Sitting animation Please Add Riding option and riding animation to ride On Player
    My Idea for this animation:-
![model 2](https://user-images.githubusercontent.com/86772566/124349075-f6015c00-dc0a-11eb-84af-cf4e14af83f4.png)

2. If You Are Adding Sitting Options And Animations
   My Idea For How To Sit on Block:-
   First make a Key To Sit on block (Can Be Modify in Controls) (Default Should be (Page Down) Key)
   Second make a Key To dismount on block (Can Be Modify in Controls) (Default Should be (Page Up) Key)
        To Sit on block:-
              1. Point Cursor to the block we are sitting on
              2. Press the Key (Key To Sit on Block That is set in controls)
              3. Done
              4. To Dismount Press the Key (Key To dismount from the Block That is set in controls)

**Comment by LakshyaKAChauhan** [comment]
1 More Thing, If You Are Adding Player Riding option then to ride on player is same as to sit on block

**Comment by LakshyaKAChauhan** [comment]
1 More Thing, If devlopers see my Issue and suggestion Please comment To Let me know that developers have seen my issue and suggestion

**Comment by LakshyaKAChauhan** [comment]
Beacause I Hard Work On Models on Block Bench About 3 to 4 Hours

**Comment by Yesssssman** [comment]
Sorry, but I don't think this is matching with the development direction of this mod. I'd like to make more animations related to combat first. A great alternative to this is the mo'bends mod.

**Comment by LakshyaKAChauhan** [comment]
I can't understand this clearly please translate it in hindi then tell me
