### ISSUE TITLE
Recommended changes for the mod

### ISSUE THREAD

**Issue by XanTheMann** [Yesssssman/epicfightmod#367]
Hi! I'm a big fan of the mod and I wanted to recommend some changes if you're interested!

**Katana changes**
I love the Katana and honestly mechanic wise I think it's perfect! My main recommendation though is that the Katana recipe is removed, and it becomes only obtainable as loot in dessert and jungle temple chests. My train of thought is that desert and jungle temples are the tombs of ancient leaders, and the weapon used by them, (Katana) would be buried in the tomb with them. Make it like a 10% chance to find in a dessert temple chest, and 20% for jungle temples. That's 40% chance overall to find in either a dessert, or jungle temple. Also I remember awhile back you said that you wanted to add like an RPG style dungeon at some point. You could add weapons that can only be found in that dungeon.

**Longsword changes**
Firstly I noticed that Sweeping Edge is useless on a Longsword. In the mod it now increases the damage of specials, but since the Longsword's special doesn't deal any damage, it's a pointless enchantment. My recommended change is that each level increases the max amount of guard points. For example: without Sweeping Edge the Longsword can hold 4 guard points at max, with Sweeping Edge 1 the max would be 6 guard points, then level 2 would increase it to 8 guard points, and then level 3 would increase it to 10 guard points. 

**Trident changes**
The Trident is one of the most sought after items in Minecraft, but I feel like it isn't utilized enough in this mod. Firstly, in my personal opinion, the primary attack pattern of the Trident is very dull; just 1 poking attack. I feel like the Trident's attacks should feel more similar to the Spear; just a little bit faster in speed. More wide swinging attacks that can hit multiple enemies. Secondly, the Trident doesn't have a special attack. By default the Trident can have Heartpiercer just copy-pasted from the Spear, but in this case the special attack will be different depending on if the Trident has the Channeling, or Riptide enchantment. 
This one is similar to the Katana's special in that executing it while sprinting is slightly different.
**Lightning Charge**
_Unlocked if the Trident has Channeling. "Stab your Trident into the ground creating an electric charge of lightning extending 8 blocks in all directions. If cast while sprinting, it will stab the trident forward into the ground creating a lightning charge in a 3 block wide wave in front of the player extending 16 blocks." Anything hit by the lightning will take 20 damage and get stunned for one second regardless of stun armor. Though it isn't a lightning strike it can still charge Creepers, turn Villagers to Witches, turn Pigs to Piglins, and may catch some blocks such as wood on fire if hit. Fire Protection reduces the damage taken more than enchantments such as Protection and Blast Protection. Can be dodged and blocked._
This next special is similar to the Tachi's in that it hits twice._
**Energy Drain**
_Unlocked if the Trident has Riptide. "Plunge your trident forward and impale an enemy quickly followed by a kick knocking the enemy back off your Trident." Impaling deals 19 damage, stunning the enemy for one second regardless of stun armor, and the kick deals an additional 6 damage. If you impale a player, he loses all of his current special attack gauge, 50% of it will get re-added to your own special attack gauge. The draining mechanic doesn't work on mobs. Can only hit one enemy. Protection reduces the damage taken more than other enchantments such as Blast Protection and Fire Protection. Can be dodged and blocked._

**Special changes**
It would be much easier to use specials if there was a button that could be held or toggled besides the attack button, as I've been in a ton of situations where I needed to use my special quickly, or while attacking accidently using it. My recommendation is that a new control is added to the controls menu that can be set to whatever. For example: if I wanted to use my special I could press C, and it would instantly use my special. Also in the config there could be an option to hold a key rather than toggle it. For example: when I use the Longsword special I could hold C to switch to the defensive stance, letting go would switch back to the main stance.

**Dodging changes**
I love dodging, I do it allot! But the main thing that I don't like is that while dodging I can't move my camera at all. I can understand that being a thing in first person perspective, but in third person perspective I'd like to be able to move my mouse freely. Also can you please increase the speed of recovering from a roll and prevent the roll from canceling sprints? Trust me, this will make combat much more smooth.

Let me know your thoughts on all this! This took a long time to write up haha. Anyways thanks for all of the time you put into the mod so far, I've been having allot of fun with it and this mod definitely has the potential to be one of the best!

I gratefully appreciate you taking the time to read this! :)

**Comment by Yesssssman** [comment]
I love your idea about Katana, Longsword, and Trident. I originally planned various things like exclusive material for katana and adding a special attack for the trident, but I was running out of time because I was developing this mod alone.

**Comment by XanTheMann** [comment]
Epic! Also mad respect to you making this mod alone man. I've never seen anything quite like this done before and it's cool!
