### ISSUE TITLE
(Question) What is the correct "texture location" I must import?

### ISSUE THREAD

**Issue by hisatsune00** [Yesssssman/epicfightmod#373]
I want to use this mod to change with other mod( like Medieval Mod), but I can't correctly import "modid:texture_location".

I know the address is [assets/(modid)/textures/XXX.png], but I don't know the format of "texture_location".

is there any concrete example for tutorials?

**Comment by Yesssssman** [comment]
https://www.youtube.com/watch?v=vEs1SXiLDVI

Here I uploaded how to set up entity config.
