### ISSUE TITLE
How to identify random skin textures? 

### ISSUE THREAD

**Issue by hsdsdddd** [Yesssssman/epicfightmod#375]
How to identify random skin textures?

**Comment by Yesssssman** [comment]
Sorry, but that's beyond the scope of what the config file can fix.

**Comment by hsdsdddd** [comment]
So what can I do to dentify random skin textures

**Comment by hsdsdddd** [comment]
Are there any other ways to identify random skin textures?I want to make this mods  compatible with another mod。
