### ISSUE TITLE
Paraglider mod animation issue

### ISSUE THREAD

**Issue by HylianNotebook** [Yesssssman/epicfightmod#377]
When using this mod with the paraglider mod you walk on the paraglider.

**Comment by XplodinNdr08** [comment]
ik it happened to me to

**Comment by XplodinNdr08** [comment]
to fix it click on mods

**Comment by XplodinNdr08** [comment]
![Screenshot (26)](https://user-images.githubusercontent.com/66173981/126573253-7946b43a-b2c2-47ad-ae2a-f8c5816af239.png)

**Comment by XplodinNdr08** [comment]
then click on epic fight mod and config

**Comment by XplodinNdr08** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/66173981/126573364-13e3be0d-adcd-4256-8bd8-f5d78c605d98.png)

**Comment by XplodinNdr08** [comment]
![Screenshot (27)](https://user-images.githubusercontent.com/66173981/126573410-6cb0c161-e374-460a-b9e1-7b056101f829.png)

**Comment by XplodinNdr08** [comment]
and turn on filter animation

**Comment by XplodinNdr08** [comment]
![Screenshot (28)](https://user-images.githubusercontent.com/66173981/126573498-7f4d56ea-cb30-45b0-8d2b-e98a324e554d.png)

**Comment by XplodinNdr08** [comment]
and when you exit battle mode and by default to toggle battle mode its "r"

**Comment by XplodinNdr08** [comment]
and i know i wish there was compatibility with animations from other mods

**Comment by XplodinNdr08** [comment]
there probably are going add compatibility with animations from other mods
