### ISSUE TITLE
(A suggestion) Compatibility with non-original biological models

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#378]
Hey there! Brother, I have an idea about the module, which is whether the module can be made into a framework, such as the interface for creatures to be attacked. Because I discovered that there are actually many modular creatures that actually have animations, including animations when they are attacked. But none of these creatures will be interrupted from attacking the player because they are attacked. For example, the snow monster in mowziesmobs actually has an animation when he is attacked, and also jumps to avoid the player by himself. I'm thinking if you can make your attack into an open interface, it's like your module is a framework. Then other module authors use this interface to call the animation of his own module creature, which will be very cool.

**Comment by Yesssssman** [comment]
I plan to divide the Epic Fight mod into two, the core mode and the epic fight original, in order to provide APIs to the mod developers. But, first I have to complete making the basic system to avoid confusion by changing the API after it was released.

**Comment by wushen233** [comment]
It seems that the author has a plan, so I look forward to that day
