### ISSUE TITLE
No animation for boating

### ISSUE THREAD

**Issue by asanginxst** [Yesssssman/epicfightmod#379]
· No animation for boating
![QQ图片20210706155824](https://user-images.githubusercontent.com/48101330/124563849-03208400-de73-11eb-8680-6c66b245b1ae.png)
The boating uses horse riding animation
· Can you add stamina points as the cost of using skills? (Like Dark Soul)
please！！！！！
thanks

**Comment by plantyourcrop** [comment]
Also for minecart too 
I think entities that are rideble only has one 
Animation

**Comment by plantyourcrop** [comment]
Also for minecart too 
I think entities that are rideble only has one 
Animation

**Comment by plantyourcrop** [comment]
Oof just doubled what I said.

**Comment by asanginxst** [comment]
XD
