### ISSUE TITLE
Mod not loading the stats correctly

### ISSUE THREAD

**Issue by HERNANDIITO** [Yesssssman/epicfightmod#380]
I edited the stats of the custom weapons but the mod doesn't loads it correctly.
[config.txt](https://github.com/Yesssssman/epicfightmod/files/6769968/config.txt)
![Example](https://user-images.githubusercontent.com/59618470/124599472-fe090800-de65-11eb-9d18-74a44449143e.png)

**Comment by Yesssssman** [comment]
You have to correct armor negation value 8 to 8.0.

**Comment by HERNANDIITO** [comment]
I see... Thanks anf sorry for being such a dumbass

**Comment by HERNANDIITO** [comment]
I tried it, and still not working
[config.txt](https://github.com/Yesssssman/epicfightmod/files/6776315/config.txt)
