### ISSUE TITLE
Tetra Weapons Dont Work

### ISSUE THREAD

**Issue by Firezone87** [Yesssssman/epicfightmod#381]
[Tetra](https://www.curseforge.com/minecraft/mc-mods/tetra) weapons dont work with epic fight mod

https://user-images.githubusercontent.com/69213979/124612855-f69c2b80-de72-11eb-80a7-72b193bdd322.mp4

**Comment by Yesssssman** [comment]
Tetra weapons normally use the NBT format to decide the weapon type. For now, Epic Fight doesn't support NBT based configuration.

**Comment by wushen233** [comment]
You can add item id by yourself, I can use it here.

**Comment by RealMerlin23** [comment]
how did u do it? cause i'm trying to config that but it only recognizes tetra itens as bare hands.
