### ISSUE TITLE
Back weapon setting (recommended)

### ISSUE THREAD

**Issue by GalaxyZEROX** [Yesssssman/epicfightmod#382]
Excuse me. . . . Is there any way to prevent some weapons from being displayed on the back when riding?
![2021-07-07_02 50 56](https://user-images.githubusercontent.com/73332842/124652669-f598e780-dece-11eb-91a3-4b9d33788d72.png)

**Comment by GalaxyZEROX** [comment]
For some reasons, I use the lightsaber as "TACHI", but at this time, riding on a horse or other riding objects makes the lightsaber feel strange on the back (what is the material of this back? . . . Not afraid of lightsabers. . . . )

**Comment by Yesssssman** [comment]
I can't handle the details of compatibility with other mods. It is recommended to use the "Filter Animation" option in the mod container screen. It will prevent rendering the animated model when you're not in battle mode.
