### ISSUE TITLE
doVanillaAttack doesnt work

### ISSUE THREAD

**Issue by tjwhang** [Yesssssman/epicfightmod#388]
I want to use the epic fight mod in servers, only getting the animation, so I tried /gamerule doVanillaAttack in Singleplayer, but it does not seem to allow me attacking in vanilla mode. 

Please fix it

**Comment by Yesssssman** [comment]
Thanks for reporting!

**Comment by tjwhang** [comment]
> Thanks for reporting!

Thanks, the new 4.1.4 version fixed it!
Thank You

Now I will close the feed.
