### ISSUE TITLE
Issue with rolling

### ISSUE THREAD

**Issue by AmburLoaf** [Yesssssman/epicfightmod#399]
Whenever I try to run with combat mode disabled, I still end up rolling. Can you fix this so that players only roll when using the combat mode?

**Comment by Yesssssman** [comment]
Which version have you used?

**Comment by AmburLoaf** [comment]
I'm using EpicFightMod- 1.16.5-4.1.4

**Comment by Yesssssman** [comment]
Well, Are you saying about disabling rolling if the player is in building mode? If it's true, I thought it's already applied.
