### ISSUE TITLE
Mark as compatible with 1.16.5 on CurseForge

### ISSUE THREAD

**Issue by koderian** [Yesssssman/epicfightmod#40]
Hi @Yesssssman. Could you mark Epic Fight Mod as compatible with 1.16.5 on CurseForge? Reason being, 1.16.4 mods work on 1.16.5. Also, it makes updating the mod when using the CurseForge desktop app easier as I don't need to finker with the Manifest files.

**Comment by Yesssssman** [comment]
I made this on mdk 1.16.4 environment so I can't assure that there's no side effect on 1.16.5.

**Comment by koderian** [comment]
It's working fine for me, I tried comparing both 1.16.4 running the mod and 1.16.5 and I didn't see a difference.

**Comment by Yesssssman** [comment]
Yeah, but still there can be a crash or something when you install another mod in 1.16.5.

**Comment by koderian** [comment]
thanks
