### ISSUE TITLE
Animations from other mods do not work.

### ISSUE THREAD

**Issue by LordKiriYT** [Yesssssman/epicfightmod#400]
I tried using this mod together with spider 2.0, mowzies mobs and wizard staff and no animation from those other mods work.

**Comment by Yesssssman** [comment]
It's inevitable because I made an independent model for animations in Epic Fight. You can turn on the "filter animation" option and it'll disable the animated model for Epic Fight and render vanilla model if you're in building mod.

**Comment by LordKiriYT** [comment]
> It's inevitable because I made an independent model for animations in Epic Fight. You can turn on the "filter animation" option and it'll disable the animated model for Epic Fight and render vanilla model if you're in building mod.

thank you for the response. Your solution works fine. Is there any downside to enabling the filter animation?

**Comment by Yesssssman** [comment]
For now, there's no way to apply the filter animation option or similar thing to monsters. I'll find a proper way to solve this.
