### ISSUE TITLE
How do I destory boats?

### ISSUE THREAD

**Issue by Nequczek** [Yesssssman/epicfightmod#401]
So i cant destoroy boats either on creative or survival is there any solution?

**Comment by Yesssssman** [comment]
Oh, I forgot to apply it in 1.12.2. Sorry.

**Comment by Nequczek** [comment]
but im playing on 1.16.5

**Comment by Nequczek** [comment]
EpicFightMod-1.16.5-4.1.3.

**Comment by Yesssssman** [comment]
You can destroy them in building mod. Battle mode doesn't support destroying any non-living entity like armor stand and boat.

**Comment by Nequczek** [comment]
not really https://youtu.be/vBayvjTQTQk

**Comment by Yesssssman** [comment]
Oh, I forgot it. the 4.1.3 version has a bug. when the special attack key is set to default, the vanilla attack doesn't execute. Use the latest version.

**Comment by Nequczek** [comment]
oh okay thanks very much
