### ISSUE TITLE
Can I import version 1.12.2 of "bow" and "crossbow" to modify the action of long-range weapon?

### ISSUE THREAD

**Issue by GalaxyZEROX** [Yesssssman/epicfightmod#403]
In many other MODS, bows and the like are displayed on the right hand, and the position of the bow is on the arm joint when pulling the bow. . . Can you import "bow" and "crossbow" into version 1.12.2 to modify the action of long-range weapon?

**Comment by Yesssssman** [comment]
Like the case of guns, Since there are no crossbows in vanilla Minecraft, it's very hard to make items from other mods being recognized as a crossbow.

**Comment by GalaxyZEROX** [comment]
Can you try to support TechgunsMOD as an extended option and add bow and crossbow options in "config"?

**Comment by GalaxyZEROX** [comment]
> Like the case of guns, Since there are no crossbows in vanilla Minecraft, it's very hard to make items from other mods being recognized as a crossbow.

Can you try to support TechgunsMOD as an extended option and add bow and crossbow options in "config"?
