### ISSUE TITLE
First person render shows "Slim" skins with the classic model

### ISSUE THREAD

**Issue by SomeRandomPetey** [Yesssssman/epicfightmod#407]
Basically title, the first person player model uses the classic model regardless if the user has a slim or classic skin. This causes issues with the skin in first player, with the arms having black bars at places.
![2021-07-16_12 26 36](https://user-images.githubusercontent.com/42192920/125979543-b7233153-bc46-4f6a-bec3-1340f09ce7e3.png)
Look at the arm. 4 pixels wide = classic skin, however I am using a slim skin, as illustrated below.
![2021-07-16_12 26 50](https://user-images.githubusercontent.com/42192920/125979564-e294ef82-a144-4396-b8b9-775183711c32.png)

**Comment by Yesssssman** [comment]
Oh, I didn't consider that detail. I will fix this as soon as possible.
