### ISSUE TITLE
[Suggestion] Smoother first-person/third-person camera switching

### ISSUE THREAD

**Issue by diodelass** [Yesssssman/epicfightmod#408]
First off, I just want to say that this mod is outstanding. I'm a longtime Bloodborne fan, and seeing Minecraft turned into a playable third-person hack & slash just makes me very happy. The animations are fantastic, too! After playing the game with such well-constructed mob combat, it's kind of hard to go back to the awkward, stilted vanilla combat animations.

One small thing that keeps bugging me is that switching the camera from third-person to first-person and back by the usual F5 method is really not very ergonomic. I've been finding that third-person mode is really a lot more fun for combat, but that it's really difficult to use for pretty much anything else, and since dungeon exploration in minecraft involves about the same amount of digging and building as it does actual fighting, I've been switching back and forth very frequently. Since the F5 key is far away from the home row and also requires a double-press to return from third-person to first-person - and has to be done in addition to the combat/mining mode switch that the mod uses - I've found this process to be pretty clunky. 

What would you say to the idea of having combat mode automatically put the camera in third-person, and then return it to first-person when deactivated/returned to mining mode? I don't know if most people prefer third-person view when fighting, but given that most hack & slash games I know of are third-person and also that it just seems to work very well, I would be surprised if it weren't popular. At any rate, maybe it could be a config option?

Either way, great mod!

**Comment by Yesssssman** [comment]
Thank for your opinion. Actually, I made such system when there's no support for first person battle mode. (early 1.12.2 version) but it was discarded after Epic Fight doesn't seperate the building/battle mode by First/Third person view. Anyway, I think it would be better to leave this issue to user's choice.

**Comment by maximogta** [comment]
Also try nimble, it creates a smooth transition between 3rd and 1st person view an removes the need to double-press F5
https://www.curseforge.com/minecraft/mc-mods/nimble

**Comment by diodelass** [comment]
Nimble is perfect for this. I was a bit worried that binding the same key to camera shifts and mode switching would risk having the two come unsynced from each other, but in practice, I haven't seen that happen once. This does exactly what I was looking for, with the only caveat being that it makes front-view third-person camera mode inaccessible. But I don't really have any plans to do Youtube videos, so I can live with that.
