### ISSUE TITLE
Server crashing for a ticking entity

### ISSUE THREAD

**Issue by NooberPlays** [Yesssssman/epicfightmod#409]
Anyone else is having problems with ticking entities? I am not sure how to explain what is happening so I'll rpovide my client logs and my server logs and hope anyone knows why 
 My log:
[latest (1).log](https://github.com/Yesssssman/epicfightmod/files/6834043/latest.1.log)
My crash report:
[crash-2021-07-16_20.46.19-client.txt](https://github.com/Yesssssman/epicfightmod/files/6834045/crash-2021-07-16_20.46.19-client.txt)
Server logs (idk which is the correct so I just uploaded all the files I thought were relevant): 
[2021-07-15-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/6834046/2021-07-15-1.log.gz)
[debug-1.log.gz](https://github.com/Yesssssman/epicfightmod/files/6834047/debug-1.log.gz)
[latest (2).log](https://github.com/Yesssssman/epicfightmod/files/6834048/latest.2.log)
Server crash report:
[crash-2021-07-15_20.52.11-server.txt](https://github.com/Yesssssman/epicfightmod/files/6834050/crash-2021-07-15_20.52.11-server.txt)
I will also provide a picture of the mods I have:
![image](https://user-images.githubusercontent.com/62673966/126023446-8e6eaf7e-abd8-47e1-9e57-0f4f04a4658b.png)

Yes, I have seen the ticket #345 although the problem is said to be the mod "Dungeon Mobs" mod with husk and I do not have this mod

**Comment by Yesssssman** [comment]
Does this issue keep occurring in the 4.1.5? Then, I'll inspect this problem again.

**Comment by NooberPlays** [comment]
> Does this issue keep occurring in the 4.1.5? Then, I'll inspect this problem again.

sadly yes it does, I am using 4.1.5 and all the other mods in the screenshot

**Comment by HERNANDIITO** [comment]
Still happening

**Comment by NooberPlays** [comment]
> Still happening

yeah I've been testing it and it does crash

**Comment by Yesssssman** [comment]
Your crash reports were made by various reason and I only can fix the crash that caused by

java.lang.NullPointerException: Ticking entity
at maninhouse.epicfight.client.animation.BaseLayer.playAnimation(BaseLayer.java:29) ~[?:1.0 {re:classloading,pl:runtimedistcleaner:A}

because it's caused by my sector.

And the issue #410 is different problem of this. Can you check that the crash I wrote above still happens?

**Comment by NooberPlays** [comment]
> Your crash reports were made by various reason and I only can fix the crash that caused by
> 
> java.lang.NullPointerException: Ticking entity
> at maninhouse.epicfight.client.animation.BaseLayer.playAnimation(BaseLayer.java:29) ~[?:1.0 {re:classloading,pl:runtimedistcleaner:A}
> 
> because it's caused by my sector.
> 
> And the issue #410 is different problem of this. Can you check that the crash I wrote above still happens?

not anymore
