### ISSUE TITLE
Weird player animations with projectile weapons in first person & third person

### ISSUE THREAD

**Issue by koderian** [Yesssssman/epicfightmod#41]
Using Epic Fight 3.0.0 on Forge 36.0.43 on 1.16.5

Mods I am using that may modify camera movement are Better Third Person and CameraOverhaul [Forge], but I believe this is a issue of Epic Fight Mod. 

Here is a video of the problem I am describing: [https://streamable.com/f1yxow](https://streamable.com/f1yxow). As you can see, when turning my view in battlemode with a crossbow/bow it glitches and starts bobbing left/right weirdly. 

Also, in third person, when moving my view left/right and aiming with a projectile weapon it makes it really hard to aim. Also, there is no crosshair in third person.

**Comment by Yesssssman** [comment]
Ok. check this on 3.0.1

**Comment by koderian** [comment]
Ok thanks. Also do you mind marking 3.0.1 as 1.16.4 AND 1.16.5?

**Comment by koderian** [comment]
Fixed.
