### ISSUE TITLE
Crash: "Attempted to load class maninhouse/epicfight/client/capabilites/entity/ClientPlayerData for invalid dist DEDICATED_SERVER"

### ISSUE THREAD

**Issue by aaronhowser1** [Yesssssman/epicfightmod#414]
Crash report: https://pastebin.com/kTGbD2Bv

Got this crash on my server, I wasn't on when it happened so idk what caused it.

This is using `EpicFightMod-1.16.5-4.1.4`

**Comment by Yesssssman** [comment]
Same problem as #404. Try this again in the next update.

**Comment by aaronhowser1** [comment]
Will do, though I don't know how to test if it's fixed since I don't know what caused it in the first place.

**Comment by Yesssssman** [comment]
Well, If you leave no comments here, I'll think there's no more same issue in the latest version.
