### ISSUE TITLE
epic fight mod incompatible with artifacts mod

### ISSUE THREAD

**Issue by XplodinNdr08** [Yesssssman/epicfightmod#415]
i love the artifacts ( https://www.curseforge.com/minecraft/mc-mods/artifacts ) mod but i love this mod too but when i have this mod with artifacts mod its kinda broken because when i use for example the umbrella artifact with this mod the falling animation is weird im not even holding the umbrella up to glide.

**Comment by XplodinNdr08** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/66173981/126229738-565750d2-3a08-4ad1-98d3-1815e5afdc5f.png)

**Comment by XplodinNdr08** [comment]
i just want an rpg game experience in minecraft

**Comment by XplodinNdr08** [comment]
also the same animation is bugged with the paragliders mod

**Comment by Yesssssman** [comment]
It's a similar problem with #400. Use the "Filter Animation" option in the mod configuration screen.

**Comment by XplodinNdr08** [comment]
not really what i wanted i just wanted for the animations to work together because when i fall im supposed to hold the umbrella up not down to my legs
