### ISSUE TITLE
Controllable mod compatibility

### ISSUE THREAD

**Issue by maximogta** [Yesssssman/epicfightmod#417]
Could be added compatibility between epicfightmod and [Controllable mod by MrCrayfish](https://www.curseforge.com/minecraft/mc-mods/controllable)?
It needs controllable [support to be added](https://github.com/MrCrayfish/Controllable#developers) in epicfight to work properly, at the moment the combat mode animations and mechanics dont work while using controllable.

Controllable version Controllable 0.13.3
EpicFightMod version 1.16.5-4.1.6

Epicfight is really a awesome mod, I cant go back to normal minecraft combat anymore, thank you for this masterpiece :)

**Comment by KOSKing09** [comment]
is it fixed or no... i still can't use this mod and i can't go back to vanilla either.... really sad about this its a really good mod....

**Comment by KOSKing09** [comment]
Found a way around it!!... so i was messing around inside of the mouse menu with controllable installed, and to my surprise when you click on it with mouse you CAN USE YOUR CONTROLLER AND SET THE BUTTON TO THE CONTROLLER BUTTON! it fixed the glitch im going to remove my attack key in controllable and use it like that.

**Comment by 911653534** [comment]
is it fixed or no? i still can't attack

**Comment by MetalKnight56** [comment]
This issue is not fixed yet, next update should have compatbility between the two mods.

**Comment by MetalKnight56** [comment]
Issue has been fixed as of the latest commits
https://github.com/Yesssssman/epicfightmod/compare/e963d283e2ec...35e8aa9ea4ba

**Comment by ToppyTopology** [comment]
would like to know if this commit will also be included for the 1.20.1 version aswell? thanks

**Comment by EchoEllet** [comment]
If you're on:

* **1.20.1:** use [Epic Fight: Controlify](https://www.curseforge.com/minecraft/mc-mods/epic-fight-controlify) with [Controlify: Forgified](https://www.curseforge.com/minecraft/mc-mods/controlify-forgified-unofficial).
* **1.21.1:** use the latest Epic Fight with the official Controlify mod; no need to install `Epic Fight: Controlify`
