### ISSUE TITLE
Support custom moded armors in combat mode (Dungeons gear)

### ISSUE THREAD

**Issue by SkullDiamond** [Yesssssman/epicfightmod#418]
Dont get me wrong the mod is awesome like this but it will be AWESOME to see Dungeons gear mod in combat mode or a config that could make that hapend

**Comment by SkullDiamond** [comment]
:(

**Comment by MetalKnight56** [comment]
Patched Dungeon Gear mod here: https://www.planetminecraft.com/data-pack/epic-fight-dungeon-gear-patch/
