### ISSUE TITLE
Epic Fight crash server with apotheosis

### ISSUE THREAD

**Issue by RedneTwo** [Yesssssman/epicfightmod#42]
Epic Fight Mod 3.0.1
Minecraft 1.16.4
Forge 35.1.36
Apotheosis 4.4.1

Crash Server: https://pastebin.com/m5pbGTt1
Explication: I only know that to reproduce the error, my friend encountered a spawner, then the server was closed
I wasn't on the server at the time so I can't give a video of the problem

**Comment by Yesssssman** [comment]
This is same issue. Every crashes you sent me was occured from

maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84)

**Comment by RedneTwo** [comment]
Could you fix it?

**Comment by Yesssssman** [comment]
Guess I need kinda rough way.
