### ISSUE TITLE
[Request] Config to disable custom player model when out of fight mode

### ISSUE THREAD

**Issue by aaronhowser1** [Yesssssman/epicfightmod#430]
The custom model *is* very cool, but it breaks rendering for basically anything more complex than vanilla armor. 

![image](https://user-images.githubusercontent.com/15698722/126796716-61e5e3af-f97e-47e3-bc7f-28531b2a59ea.png)
This is what I should look like, but this is what I actually look like: 
![image](https://user-images.githubusercontent.com/15698722/126796765-442b5839-bafe-4714-addd-e6be924d0586.png)

It also breaks Mekanism jetpacks etc.

**Comment by ColaLiao** [comment]
in config file "epicfight-client.toml"
set filter_animation = true.

**Comment by aaronhowser1** [comment]
Oh thank you, I hadn't realized that was already an option!
