### ISSUE TITLE
Incompatible with Quark emotes (1.16.5)

### ISSUE THREAD

**Issue by VolgaLVI** [Yesssssman/epicfightmod#435]
Hi! Just as a heads up, I have no clue how replacing player models/animating works, but it seems the emotes are incompatible with the emotes from the Quark mod, as the animations for the emotes don't seem to play when I use them. I don't know which mod needs to make a change to fix this, if possible, but I will also write this report to the Quark authors in case this issue is not yours to fix. Thank you! 
(Also, I cannot seem to break boats with melee attacks. Same version)

**Comment by Yesssssman** [comment]
Turn on the "Filter Animation" option. It'll stop the animated model by Epic Fight in mining mode. And the unbreakable entity bug is fixed after 4.1.6.
