### ISSUE TITLE
Incompatible with Mowzies mob's (sort of)

### ISSUE THREAD

**Issue by manmanguy** [Yesssssman/epicfightmod#44]
I've been using the two mods to create a soft of high risk, high reward gameplay style. I was fine with the weapons just acting as swords or blocks. Until I beat the Knight. I used his axe, no animations for special moves. I was totally fine with it. Tried placing on the helmet, then went into the third person mode epic fight mod has. And the game crashes, I'm pretty sure it's how the armor and helmet is rendered by the multi-limb body. As various other mods have similar issues, where some stuff is displaced, or a visor is missing, but don't generally crash when i try wearing an armor piece. (i've also tried the sun mask, it crashes too), It isn't game breaking or anything. Just slightly annoying that I can't use any armor pieces.

**Comment by Yesssssman** [comment]
Which version did you use?

**Comment by manmanguy** [comment]
1.12.2

**Comment by Yesssssman** [comment]
Well, I'm fixing bugs and crashes in 1.16.4 first then I'll backport everything to 1.12.2. Hope you can wait till then.
