### ISSUE TITLE
Custom weapons don't work well

### ISSUE THREAD

**Issue by TheTechPny** [Yesssssman/epicfightmod#447]
I went through my modpack and added a lot of the custom weaponry to be compatible with epic fight mod but they are goofy and I had to remove it

Config
https://pastebin.com/raw/nM6hevTu

What it looks like
https://www.youtube.com/watch?v=4mOi7Yecg58

**Comment by dreckz** [comment]
The same is happening to me when attempting to make new compatibilities for weapons.

**Comment by Yesssssman** [comment]
Hello there, What's the version?

**Comment by TheTechPny** [comment]
It looks like it has been fixed now, thanks!
