### ISSUE TITLE
Resurrect after being killed, the attacking creature will report an error and cannot cause damage

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#448]
Now resurrected after being killed cannot cause damage to any creatures and an error occurs, but monsters can cause damage to the player and will also report an error. And the monster's attack animation disappeared and became the original animation. It would be fine if you exit the server and re-enter, but the situation will repeat after death. And can not roll over on the server. Except for the inability to roll, no other problems appeared before. It can roll after death. Now it doesn’t work. I doubt it’s caused by the update of the server core forge version.
The following is an error：https://paste.ubuntu.com/p/K2xrVTXDgC/

**Comment by Yesssssman** [comment]
Will be fixed after 5.0.2

**Comment by wushen233** [comment]
> 将在 5.0.2 后修复

Thanks to the author! Can the player quit the server and re-enter and cannot attack in combat mode and must die once, can it be fixed?
