### ISSUE TITLE
Two Bugs: Missing & Visual when using this and a mod

### ISSUE THREAD

**Issue by urnoobx19** [Yesssssman/epicfightmod#45]
Bug 1:

*Missing visual item [travelers backpack mod] when wear in 3RD person view; 
First image:[MISSING] ![2021-03-05_14 09 52](https://user-images.githubusercontent.com/80088559/110074631-8003fa00-7dbc-11eb-82cf-a384e99e3f90.png)

When EPICFIGHTMOD was remove from the mod folder, The Backpack is shown.
Second Image: [SHOWN] 
![2021-03-05_14 15 17](https://user-images.githubusercontent.com/80088559/110075106-4384ce00-7dbd-11eb-8c5f-ed0c8dff23fe.png)

Bug 2:

*Visual Bug. [ISSUE]When the MC tries and sleep using Vanilla Bed or Comfort mod Bed/ Travelers Backpack Bed, the MC stands up In the bed and jerk-like movement while standing up at the bed. see the image below.
First Image: [VISUAL BUG] using Vanilla Bed;
![2021-03-05_14 28 56](https://user-images.githubusercontent.com/80088559/110076342-4c769f00-7dbf-11eb-9c5e-185f3e40fc50.png)
Second Image [VISUAL BUG] using travelers Backpack Bed
![2021-03-05_14 29 11](https://user-images.githubusercontent.com/80088559/110077062-7d0b0880-7dc0-11eb-80c7-1706174875d2.png)

Last Image: [VISUAL BUG] using comfort mod
![2021-03-05_14 29 38](https://user-images.githubusercontent.com/80088559/110076627-c575f680-7dbf-11eb-8d5a-261b1b8b0371.png)

BTW thank you for creating this marvelous EPICFIGHT MOD.
[Sorry for my bad English.]
Version 1.16.4 Forge

**Comment by Yesssssman** [comment]
Oops, I didn't add sleeping animation, but I'm focusing on other stuff now. Hope you understand.

**Comment by Jollyolsport** [comment]
Bump for possible travelers backpack compat.
