### ISSUE TITLE
[Help] Off and On

### ISSUE THREAD

**Issue by RafWasTaken** [Yesssssman/epicfightmod#451]
I cannot find the config file

**Comment by FurryApocalypse** [comment]
what do you want turn off or on?
If you just want to change battle mode to dig mode or so you should just go in minecraft - options and search for the propper key.

**Comment by RafWasTaken** [comment]
i want to turn off anims outside combat mode

**Comment by Yesssssman** [comment]
Turn on the "Filter Animation" option in the mod configurations.
