### ISSUE TITLE
epic fight can get better

### ISSUE THREAD

**Issue by HaaDT** [Yesssssman/epicfightmod#455]
I was playing with mod and well saw some mistakes in planning the mod and thought of some ideas that can make it look better...

the mod has a system to be able to switch to combat mode and for the construction to have to be pressed a button is bad, a system could be made that the moment you pick up a weapon that is configured in the mod it switches to battle mode, and so in construction mode the player would only deal 1.0 damage which would be the punch no matter what item you are holding if not configured it will not deal damage, this would make the way to enter combat faster and simpler and also prevent you from using the Original combat system since the mode is redoing all combat you can use the old and bad one and break a few things.

**Comment by Yesssssman** [comment]
First, the items having functionality as a tool and weapon, the system. Can't judge which mode the player wants to behave. If you hold the axe, the player starts the vanilla swings even if you want to use Epic Fight combo.

Second, there is an option to disable the mod animation when you're not in battle mode. Epic Fight uses a different model from vanilla so there's a lot of visual incompatibility with other mods. To solve this problem, the separation between battle-mining mod is necessary.

I wish you understand these issues and there's a command to disable the vanilla attacks by the player. Type the /gamerule doVanillaAttacks false and it will block all kinds of vanilla attacks.

**Comment by HaaDT** [comment]
I understand, thanks, I didn't even remember this command
