### ISSUE TITLE
How many weapons can be put in the custom configs?

### ISSUE THREAD

**Issue by Shikomi36** [Yesssssman/epicfightmod#456]
I don't know when the error starts (there's 123 weapons) but when i add some it works, and when i get to a certain point it causes an error. So can the mod only config a certain amount of weapons or?
Here is the most recent crash I've had: [crash-2021-08-13_09.03.11-fml.txt](https://github.com/Yesssssman/epicfightmod/files/6983008/crash-2021-08-13_09.03.11-fml.txt)
Here is a config file with all of what I want to add:  [KK config.txt](https://github.com/Yesssssman/epicfightmod/files/6983017/KK.config.txt)
Here is what is placed in when the errors start: [epicfight.txt](https://github.com/Yesssssman/epicfightmod/files/6983056/epicfight.txt)

**Comment by Shikomi36** [comment]
Update: it errors after 14 custom weapons are put in, is 14 the max?

**Comment by Yesssssman** [comment]
> Details:
> 	Mod File: EpicFightMod-1.16.5-4.1.6.jar
> 	Failure message: Epic Fight Mod (epicfight) encountered an error during the common_setup event phase
> 		net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: kingdomkeys:Darkgnaw
> 	Mod Version: 4.1.6
> 	Mod Issue URL: NOT PROVIDED
> 	Exception message: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: kingdomkeys:Darkgnaw

You've used uppercase in the registryname. They don't allow using that.
