### ISSUE TITLE
[Bug] Game Freese And Crash With The Gravestone/Corpse Mod Installed

### ISSUE THREAD

**Issue by sclozes** [Yesssssman/epicfightmod#457]
**Bug description:**
Game freezes and crashes when the [Gravestone](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod)/[Corpse](https://www.curseforge.com/minecraft/mc-mods/corpse) Mod is installed.

**Versions**

- Minecraft version: 1.16.5
- Forge version: 1.16.5-forge-36.2.2
- Mod version: EpicFightMod-1.16.5-4.1.6

**Other Mods**
gravestone-1.16.5-1.0.6 / corpse-1.16.5-1.0.5

**This issue is related to these two issues:**
[henkelmax/corpse#52](https://github.com/henkelmax/corpse/issues/52)
[henkelmax/gravestone#68](https://github.com/henkelmax/gravestone/issues/68)

**Comment by Yesssssman** [comment]
Can you give me a crash report?
