### ISSUE TITLE
[Mod conflict]Conflict with corpse Mod

### ISSUE THREAD

**Issue by T-422** [Yesssssman/epicfightmod#459]
Install epicfight and corpse mod at the same time
The game will get stuck after you die

**Comment by T-422** [comment]
corpse mod'slink:
curseforge
https://www.curseforge.com/minecraft/mc-mods/corpse/?__cf_chl_captcha_tk__=pmd_9fe98295a56d5835b4e453e362d34e9fbaadc63a-1628995497-0-gqNtZGzNAw2jcnBszRI6
github
https://github.com/henkelmax/corpse

**Comment by Yesssssman** [comment]
Crash report?

**Comment by T-422** [comment]
I didn't see the crash report     not in the folder
At the moment of death, the game will not respond, and then I can only restart the game
If you don't remove epicfight or corpse mod, this save will not be able to enter again (it will not respond every time you enter)

**Comment by Yesssssman** [comment]
[henkelmax/corpse#52](https://github.com/henkelmax/corpse/issues/52)

I've sent him a message to solve this problem. It will be fixed after we get an agreement on how to fix this problem.

**Comment by T-422** [comment]
i see  that
thz to solve it
