### ISSUE TITLE
Crashes with When Dungeons Arise mod (Possible Confliction?) (java.lang.NullPointerException: Exception while ticking)

### ISSUE THREAD

**Issue by Coraline77447** [Yesssssman/epicfightmod#46]
Hi, my game would crash whenever I try to make a new world with Epic Fight Mod and When Dungeons Arise mod. Here's the log and crash report for the last time the game crashed with both of these mods installed:

Log: [2021-03-02-4.log](https://github.com/Yesssssman/epicfightmod/files/6089001/2021-03-02-4.log)
Crash Report: [crash-2021-03-03_03.33.06-server.txt](https://github.com/Yesssssman/epicfightmod/files/6089024/crash-2021-03-03_03.33.06-server.txt)

(Sorry for it not being from pastebin but I've tried to put it in there and it always opened a new tab instead of the crash report actually going onto pastbin so I don't know what I'm doing wrong but here is the crash report anyways...)

Btw the problem began when I installed Epic Fight Mod to one of my previous modded worlds (Coraline World 3 1.16.5 (Modded) and both mods were working just fine till I came too close to one of the dungeons from When Dungeons Arise mod and then the game crashed and now when I try to make a new world with them both the game instantly crashes when entering a new world. As I said in the comments of Epic Fight Mod on curseforge that it might be the big airship that's causing this to happen.
But I really I don't know if its Epic Fight Mod's problem or When Dungeons Arise's problem for this to occur...
Even tho I've sent the crash report on here already but when I was looking through it I saw a couple things in there that has both of the mods names in there.

The game version, forge version, and the mods versions that this reoccurring issue started in is:
Minecraft: 1.16.5
Forge: 36.0.42 (I'm at 36.0.46 now but at the time I was at 36.0.42 when it all started)
Epic Fight Mod: 3.0.1
When Dungeons Arise: 1.2.63a

**Comment by Yesssssman** [comment]
This is exactly the same issue from
https://github.com/Yesssssman/epicfightmod/issues/42

I'm finding a solution to this.

**Comment by Coraline77447** [comment]
"maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84)"

There must be something wrong with that piece of code that's not working properly since it keeps reoccurring periodically to everyone but with different mods that was played with Epic Fight Mod as well as different game modes as of singleplayer and multiplayer with different mods that were paired with Epic Fight Mod. 
I had thought that the big airship from When Dungeons Arise mod was one of the causes of this but maybe it isn't which is why I'm confused about it.
It doesn't make any since to me cause I don't see how a dungeon from a dungeon mod could cause an error like this to occur.
Anyways, all I can say is good luck to ya on finding a fix or work around for this issue.

**Comment by Yesssssman** [comment]
Can you try this version and tell me if the same problem still occurs? 
https://drive.google.com/file/d/140ZpXSJCUqnUa8Nj2okMWVLBGCU1yJ1m/view?usp=sharing
I recommend making a backup world file or test it in a world that doesn't matter to crash.
