### ISSUE TITLE
[Bug] Armor nagation doesn't work properly

### ISSUE THREAD

**Issue by Zarrylon** [Yesssssman/epicfightmod#461]
1.16.5-forge-36.1.0
EpicFightMod-1.16.5-4.1.6

1) If I punch a dummy(without armor) with stone axe(10% armor nagation):
![Screenshot_4](https://user-images.githubusercontent.com/63860918/129486378-82dde269-3e71-4974-804c-b4f78a1e43d2.png)

2) If I punch a dummy(without armor) with netherite axe(40% armor nagation):
![Screenshot_3](https://user-images.githubusercontent.com/63860918/129486363-c36ff583-78a8-4bed-90f0-965c84dca273.png)

3) If I punch a dummy(full leather set - 7 armor) with stone axe(10% armor nagation):
![Screenshot_5](https://user-images.githubusercontent.com/63860918/129486458-aae7b946-4f5d-462f-b371-80b4a957cde7.png)

4) If I punch a dummy(full leather set - 7 armor) with netherite axe(40% armor nagation):
![Screenshot_6](https://user-images.githubusercontent.com/63860918/129486489-928f0732-5b12-45dc-8dca-38da329c272e.png)

So it seems that this ability doesn't sum this non decreased damage by armor to a total damage. For now, stone axe is the most OP axe in this game.

**Comment by Yesssssman** [comment]
Seems like the indicator doesn't contain the extra damage. The extra damage deals first as much as (original damage * (negation percent)). And then, the damage as much as (original damage * (1 - negation percent)) deals which decreased by defense points.

The indicator only shows the second damage so you can misunderstand it only deals second damage. Can you check the actual damage on the entities having HP?

**Comment by Zarrylon** [comment]
Yes, you're right. Damage on the entities work correctly. Sorry for this misunderstand.
