### ISSUE TITLE
[Bugs n Compatibility] Epic Fight Is Littered With Issues And bugs And Compatibility Errors Sadly 

### ISSUE THREAD

**Issue by ReshawnStar** [Yesssssman/epicfightmod#462]
So epic fight mod has 3 issues I care about right now 
1. Skin layers are incorrect for the head bottom they are facing the models left (annoying to look at especially when you have a mod for 3rd person and Shaders on)
![2021-08-16_04 41 42](https://user-images.githubusercontent.com/78557905/129555317-bfc60ea6-e37d-4d3c-840a-9ae22d2cc33c.png)

2. It is incompatible with many mods from Backpacks, Artifacts and anything that revolves around making the character model do something (carry-on, artifacts, relics, more animations mod, animation collection, personalize, the dang female mod. ) 

3. The mod crashes sometimes on death, rare but since I was running it with ice and fire and a dragon was nearby I may count this on the dragon mod, crashed when I died in a dungeon running away from a giant (boss mob)

4. extra one since I am not sure this is epic fight's fault but sleeping causes glitches sometimes body slapping all over the place 
(bad since I can't see when I run Somina mod)

It is hard to put this in a mod-pack without something breaking, I really really want to use this mod in my mod-pack  since it adds the dodge and has the Mo's Bends, If this is fixed I would be amazed and greatful 

If you are seeing this know it is looking great so far

**Comment by aaronhowser1** [comment]
For 2, set filter_animations to false in the epicfight-client config. That will make it only change the model when youre in battle mode.

**Comment by Yesssssman** [comment]
Can I know the version? Also, do you have a crash report for 3?

**Comment by ReshawnStar** [comment]
Not sure which one it is but yeah I have a few still around.
some I see are from ice and fire then some are from other things.

At one point (and this was after I made this comment) I couldn't hit anything without crashing I think it was a conflict between this mod and another mod that I removed. 
Would need to look for the mod to find if the problem still persists. 

[crash-2021-08-17_18.42.23-client.txt](https://github.com/Yesssssman/epicfightmod/files/7024939/crash-2021-08-17_18.42.23-client.txt)
[crash-2021-08-17_18.51.51-client.txt](https://github.com/Yesssssman/epicfightmod/files/7024940/crash-2021-08-17_18.51.51-client.txt)
[crash-2021-08-17_19.02.36-client.txt](https://github.com/Yesssssman/epicfightmod/files/7024941/crash-2021-08-17_19.02.36-client.txt)
[crash-2021-08-17_19.19.00-client.txt](https://github.com/Yesssssman/epicfightmod/files/7024942/crash-2021-08-17_19.19.00-client.txt)
[crash-2021-08-14_19.15.18-server.txt](https://github.com/Yesssssman/epicfightmod/files/7024943/crash-2021-08-14_19.15.18-server.txt)
[crash-2021-08-17_18.13.14-client.txt](https://github.com/Yesssssman/epicfightmod/files/7024944/crash-2021-08-17_18.13.14-client.txt)

**Comment by Yesssssman** [comment]
The crash report says it occured from Ambience and Citadel mod. I don't know what is it exactly, so please send this crash report to mod maker.

java.lang.NullPointerException: Ticking entity
	at com.github.alexthe666.citadel.server.entity.datatracker.EntityProperties.getEntity(EntityProperties.java:63) ~[?:1.7.3-1.16.5] {re:classloading}

java.lang.NullPointerException: Unexpected error
	at vazkii.ambience.Util.Handlers.EventHandlers.playInstant(EventHandlers.java:194) ~[?:1.16.5-1.0.0] {re:classloading}
