### ISSUE TITLE
Compatibility issues with other mods.

### ISSUE THREAD

**Issue by asanginxst** [Yesssssman/epicfightmod#466]
It has poor compatibility with “Dungeons Gear" mod armor, which is manifested by incorrect textures.
![image](https://user-images.githubusercontent.com/48101330/129858761-54a93759-3097-4567-8142-610b991497c3.png)

**Comment by MetalKnight56** [comment]
Patched Dungeon Gear mod here: https://www.planetminecraft.com/data-pack/epic-fight-dungeon-gear-patch/
