### ISSUE TITLE
java.lang.NullPointerException: Ticking entity 	at maninhouse.epicfight.client.animation.AnimatorClient.playAnimation(AnimatorClient.java:53) 

### ISSUE THREAD

**Issue by aburone** [Yesssssman/epicfightmod#467]
https://hastebin.com/bululilicu.properties

**Comment by Yesssssman** [comment]
Hello, can I get the information about when this happens?

**Comment by aburone** [comment]
I was at a computercraft computer writing a program. No movement or anything. Happened 3 times in a row and had to remove the mod to be able to continue
