### ISSUE TITLE
New crash problem, old version does not exist

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#471]
When using Spartan weapons such as boomerangs and daggers that can be fired by right-clicking, the client will immediately crash. The following is the log
https://paste.ubuntu.com/p/27gsBRKmPC/
In addition, in the past, when players entered the server, they could not roll but could attack, and they had to die once to solve it. But this time in the test version, players cannot perform any operations such as dodge and attack animations in combat mode. But it can still be solved by the previous method. I don’t know if it’s because of the separation of the dodge skills this time.

**Comment by Yesssssman** [comment]
#467
