### ISSUE TITLE
when i throw spartan weaponry throwables, the game crashes

### ISSUE THREAD

**Issue by lordi-erez** [Yesssssman/epicfightmod#474]

**Comment by Yesssssman** [comment]
Crash report?

**Comment by wushen233** [comment]
> 崩溃报告？

Sorry, I should have given feedback yesterday, and I only found out that I have given feedback on other issues. The link is the log of the crash of throwing the Spartan weapon
https://paste.ubuntu.com/p/Np43WgqGnX/

**Comment by Yesssssman** [comment]
#467
