### ISSUE TITLE
Right click using items crashes the game

### ISSUE THREAD

**Issue by DarkScorn** [Yesssssman/epicfightmod#475]
[crash-2021-08-20_18.10.00-client.txt](https://github.com/Yesssssman/epicfightmod/files/7025150/crash-2021-08-20_18.10.00-client.txt)
Right-click using an enchanted key, ankh of pray, and tablets from Corail tombstone mod always crashes the game at the end of the animation.
It probably happens with almost any right-click pulling items, that's probably why the guy who opened the issue on spartan weaponry ranged weapons.

**Comment by Yesssssman** [comment]
#473
