### ISSUE TITLE
[question] How many custom weapons/armor we can put?

### ISSUE THREAD

**Issue by Houllp** [Yesssssman/epicfightmod#476]
My game crashed when I put some Cyclic weapons(nether weapons, especifically).
I already put some weapons (from Cyclic and others mods too) and no problems until now...
[crash-2021-08-21_16.58.06-client.txt](https://github.com/Yesssssman/epicfightmod/files/7026136/crash-2021-08-21_16.58.06-client.txt)

**Comment by Yesssssman** [comment]
![image](https://user-images.githubusercontent.com/79469058/130342629-65af980d-83e9-4257-93b2-4b905c0c878e.png)

Is there any misspell in the configuration file? Parser failed to find the "impact" value.

**Comment by Houllp** [comment]
Hum... Configs i'm using
[cyclic-epic-fight.txt](https://github.com/Yesssssman/epicfightmod/files/7026628/cyclic-epic-fight.txt)

**Comment by Houllp** [comment]
I found it xD. My bad
