### ISSUE TITLE
Suggestion to implement skills and possible new weapon

### ISSUE THREAD

**Issue by hitmanssilent** [Yesssssman/epicfightmod#479]
I have an idea to implement the different skills that is now incorporated into the mod, instead of making the skills appear in chests and we have to learn them, what if you make a skill tree in which we have to invest the experience of the game to "buy" those skills ?, and so each one is separated to buy, for example, blocking attacks individually for tachi, swords, axes, etc.

It would also serve to invest in the effectiveness of those skills, in the case of blocking, a duration could be implemented in the blocking of attacks or that less resistance is reduced with each impact, there could also be a section to improve the resistance of the player investing In that with experience, it could also be divided into several sections to improve, for example the attack while the player jumps could be divided into speed, resistance consumption and damage, thus it becomes a more customizable, immersive experience and gives it a touch of RPG.

It could also serve to, for example, we can use increasingly heavy armor with fewer penalties, or that for example we can improve the speed at which we can move with the great sword.

Also in the skill tree, experience could be spent so that special attacks charge faster, damage more or consume less resistance.

Or even some other things such as that we can unlock certain abilities that save us having to enchant an object, such as the loyalty of the tridents or the fast reload of the crossbows (At the end of the day, we still use the same experience that we would use to enchant those weapons with the same enchantment).

Also another suggestion that I make is that you implement a potion that allows the player to regenerate more quickly the resistance or another that accelerates the attack speed

As a last suggestion, I've been playing a game called kingdoms of amalur, which has a very cool type of weapon called "chakrams" is a semi-ranged type of weapon that returns to the player with each attack, maybe you can consider adding it to the mod, here is an example video: 
https://www.youtube.com/watch?v=aVOhs4uSy0A

If you need me to make a diagram to explain it better, let me know, and I will do my best to make it clearer.

**Comment by Yesssssman** [comment]
This is not a bad idea, but It'll take a huge time to implement. I'll take a look at this later after solving the present problems.
