### ISSUE TITLE
bug in 5.0.1

### ISSUE THREAD

**Issue by kny6548** [Yesssssman/epicfightmod#483]
Unable to attack after leaving and entering the server.
and I don't know if it's a bug or intended, but after death, the skills you learn are lost.

**Comment by Joadv21** [comment]
i also got this bug, in book skills it said Applied but i cant use it 
before 5.0.0 version i never got this bug

**Comment by Yesssssman** [comment]
You can prevent the removal of skills when you die by /gamerule keepSkills true.
By the way, can you attach a video or screenshot of the bug you mentioned?

**Comment by Joadv21** [comment]
> You can prevent the removal of skills when you die by /gamerule keepSkills true.
> By the way, can you attach a video or screenshot of the bug you mentioned?

opps i didnt know that because in previous version i never lost skills
