### ISSUE TITLE
Exception in server tick loop 5.01 when learning a skill book

### ISSUE THREAD

**Issue by Nihilooo** [Yesssssman/epicfightmod#484]
Instantly crashes the server and disconnects all clients.

how to recreate:
cheat in a skill book
open the ui
click learn

[crash-2021-08-23_14.54.35-server.txt](https://github.com/Yesssssman/epicfightmod/files/7032093/crash-2021-08-23_14.54.35-server.txt)

**Comment by Yesssssman** [comment]
Can you try this again after update the forge version to 36.2.0?

**Comment by VolgaLVI** [comment]
I ran a test with Forge 36.2.0 on my server and it did not crash. So a forge update is probably needed

**Comment by VolgaLVI** [comment]
I had this same issue prior to updating

**Comment by asanginxst** [comment]
Me too, this problem was resolved after the forge version was updated.
