### ISSUE TITLE
[1.16.5 Mod Conflict] Player Revive mod

### ISSUE THREAD

**Issue by MapleSiryup** [Yesssssman/epicfightmod#485]
There's a compatibility issue with the Player revive mod where when you get revived you are still laying on the ground
[](https://www.curseforge.com/minecraft/mc-mods/playerrevive)

**Comment by MapleSiryup** [comment]
In advance: There was no crash report, it doesn't crash the game it just makes you unmovable and stuck in place even after being revived by another player.

**Comment by VanilaBOI** [comment]
Fixed in pre03.
https://www.curseforge.com/minecraft/mc-mods/playerrevive/files/3364213
