### ISSUE TITLE
Some sort of entity Crash 

### ISSUE THREAD

**Issue by simplemath64** [Yesssssman/epicfightmod#49]
I'm not sure why but my world keeps crashing, I think my crash log says it's do to zombies spawning.

[crash-2021-03-06_20.54.33-server.txt](https://github.com/Yesssssman/epicfightmod/files/6096412/crash-2021-03-06_20.54.33-server.txt)

[2021-03-02-4.log.gz](https://github.com/Yesssssman/epicfightmod/files/6096413/2021-03-02-4.log.gz)

Love the mod and i don't want to get take it out, is there another mod causing this?

Was using forge 36.0.43 for 1.16.5

**Comment by Yesssssman** [comment]
Hey, can you try this version? I've made a modified version for such bugs, but I don't know if it works fine.

https://drive.google.com/file/d/140ZpXSJCUqnUa8Nj2okMWVLBGCU1yJ1m/view?usp=sharing

Please reply to me whether it works or not!

**Comment by simplemath64** [comment]
Thank you, it works, though I can't seem to find any zombies anymore, just in dungeons.

Either way thank you for the amazing mod.

**Comment by Yesssssman** [comment]
Hmm... What means did you say about "I can't seem to find any zombies anymore"? Is it another bug?

**Comment by simplemath64** [comment]
Oh snap i thought that was your fix for the crashes

Well i don't know to be honest, I've been playing for couple hours walking at night, on normal difficulty, and the amount of zombies found this entire time is about 2, but that may just be the regular spawning amount, or my other mods tweaked the spawning, IDK to be honest.

**Comment by Yesssssman** [comment]
That's actually an irrational amount. You can find log files that recording everything that happened during you're playing in the Minecraft folder. What about taking a look at them? Maybe there're error logs for spawning zombies.
