### ISSUE TITLE
a few bugs

### ISSUE THREAD

**Issue by EddyHz** [Yesssssman/epicfightmod#496]
Hi again! Just thought i'd let you know of a few bugs i've come across in the new 5.0.2 update

the first issue is likely a compatibilty error caused by the other mods, but previously the mods "spartan shields" and "wizard staff" had animations that worked with the epic fight mod, now both dont show any animation when being used

secondly, the trident has three main issues i noticed, two of which may be intended? the issues are:
1, there is no jump attack
2, there is no 'special' attack for holding down left click
3, the icon for the weapon is still the default grey sword icon

and finally, blocking with a shield makes the character do a guard block, as if they were using the guard skill and no shield, as opposed to using the shield to block. this doesn't seem to affect daggers and mainhand only weapons from what i've found

**Comment by Yesssssman** [comment]
Trident has no special attack for now. I originally planned there are different types of special attacks decided by the trident's special enchantment. But it's not started yet. Grey icon means you're holding an incompatible weapon for the current special attack. Also, it has jump attacks as I know, which is same as the one-handed style of a spear.
