### ISSUE TITLE
When will you update 1.12.2 ?

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#50]
I'm patiently waiting for you to update the mod for 1.12.2 because there is so much cool updates in new versions 
and i like 1.12.2 only. :)

**Comment by Yesssssman** [comment]
Maybe after I finish the custom armor render problem.

**Comment by TurkishAhmet4545** [comment]
> Maybe after I finish the custom armor render problem.

Ok,thx.
