### ISSUE TITLE
All Entity dose not get damage when attacked in my server.

### ISSUE THREAD

**Issue by LakshyaKAChauhan** [Yesssssman/epicfightmod#501]
When I am Attacking any entity in my server, monster or animal, it dose not get any damage and animation is perfect.
It Happens build mode and in attack mode.
also when I use Filter Animation: ON

Also I cannot Dodge, and cannot do special attack when it is fully charged.
Please fix this soon as possible.
THx For reading.
Best Mod ever.
This Mod needs Frequent updates because this is the best, super minecraft and has many bugs.
good work for mod owner.
Good By Take Care In Covid 19.

**Comment by Lakshyacode123** [comment]
This is my 2nd account.

Yes I use mohist server software which runs both forge based mods and spigot based plugins but I created a another server with same mods and plugins and it work, entities gets damage when attacked.
Is it that server problem or world problem or I am joining with mismatch forge virsion or server have another mod virsion and I am joining with another mod virsion.
Please tell.

**Comment by Yesssssman** [comment]
I don't know well about how another API works so I can't tell you the solution to this problem. Maybe you can tell it to the maker of API.
