### ISSUE TITLE
Please add an mod option screen

### ISSUE THREAD

**Issue by Petslime** [Yesssssman/epicfightmod#502]
1.12.2 There is no mod option screen.
I want to disable animation in non-combat mode because I use the SlashBlade mod in my mod package. 
His weapon will also change the animation so that SlashBlade cannot be displayed in the third person.

**Comment by Yesssssman** [comment]
![2021-08-28_16 37 07](https://user-images.githubusercontent.com/79469058/131210451-0dd13dca-d945-4b26-811e-cf5084547ae5.png)

This is the config screen for 1.12.2. Go to the "epicfight_client"
