### ISSUE TITLE
Crashes a lot and I'm not sure what is causing it

### ISSUE THREAD

**Issue by TheEvilEye05** [Yesssssman/epicfightmod#507]
I love this mod but it just crashes a lot, for example everytime I die it crashes, this has happened to me a lot of time before in more older versions. But now it crashes without me doing something specific, it just crashes from nowhere. I'm sure it is this mod and no other im using it with, or maybe it is some uncompatibility.

Let me just find a way to share the crash report

**Comment by Yesssssman** [comment]
This is not a crash report... please attach the whole file.

**Comment by TheEvilEye05** [comment]
Ok I'm sorry, give me just a minute. Thank you

**Comment by FlameyFaucet** [comment]
Uh...i'd like to notify you that Tlauncher is a piracy launcher, it lets people create free accounts to play MC. Not sure you'd want those kind of people here.

**Comment by TheEvilEye05** [comment]
> Uh...i'd like to notify you that Tlauncher is a piracy launcher, it lets people create free accounts to play MC. Not sure you'd want those kind of people here.

fari enough

**Comment by TheEvilEye05** [comment]
> Uh...i'd like to notify you that Tlauncher is a piracy launcher, it lets people create free accounts to play MC. Not sure you'd want those kind of people here.

fair enough
