### ISSUE TITLE
Kantana move animations dont work

### ISSUE THREAD

**Issue by kriticalvinho** [Yesssssman/epicfightmod#508]
Hi, i set in .config one mod weapon like a katana, still animation works but the issue is when i attack, uses the sword animations and skill, down right weapon icon still in sword

Thanks you, Really nice work whit this mod

**Comment by Yesssssman** [comment]
1.12.2?

**Comment by Yesssssman** [comment]
It can't be supported on 1.12.2 cause it has a different system from 1.16.5, which is unable to change motions for katana's passive.

**Comment by kriticalvinho** [comment]
Yes 1.12.2
Oh this is so sad... thanks you again
