### ISSUE TITLE
Can you Make a new mod ?

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#51]
Can you make a second mod which fully like mount & blade warband ?
It can be an alternative to current mod.

**Comment by TurkishAhmet4545** [comment]
Btw i mean player controls only.

**Comment by ArturAlexandre32** [comment]
The Mod is already perfect like that, there is no need to create another one

**Comment by TurkishAhmet4545** [comment]
> The Mod is already perfect like that, there is no need to create another one

Mount and blade is different better.

**Comment by TurkishAhmet4545** [comment]
> The Mod is already perfect like that, there is no need to create another one

After i checked the mod,i think you are right,im gonna close topic because available mod is good.
