### ISSUE TITLE
Sword & Axe dont work with shield/ no roll mechanic

### ISSUE THREAD

**Issue by Jollyolsport** [Yesssssman/epicfightmod#512]
Forge: 1.16.5-36.2.2
Epic Fight: 5.0.0 through 5.0.2

Whilst holding the shield in your offhand and sword/axe in your main, you will proceed to block with the weapon instead of the shield.
![2021-08-28_00 57 18](https://user-images.githubusercontent.com/64448764/131206776-b9dad005-e478-4715-9561-f4486f330160.png)
![2021-08-28_00 57 21](https://user-images.githubusercontent.com/64448764/131206779-cc8542e3-92f6-4a87-84e0-89c89b0427e9.png)

Roll Mechanic not working despite being in creative and in fight mode.
https://user-images.githubusercontent.com/64448764/131206798-6f1182d5-6d22-4067-a924-f49fd6fd8ee2.mp4

**Comment by Yesssssman** [comment]
Fixed in 5.0.3.

And the roll is not a default skill for the initial spawn. You have to learn it by skill book.
