### ISSUE TITLE
Custom NPC's compatibility/support

### ISSUE THREAD

**Issue by ShadowWolf90** [Yesssssman/epicfightmod#515]
Epic Fight mod could have a very nice synergy with Custom NPCS by Noppes.
NPCS would be more "alive" in combat meaning, plus can be added a special tab to Custom NPCS to choose actions, types of behaviors or something like that, or at least NPCS could have animations.
With something like that making maps like RPG-Fantasy would be very interesting and would expand combat system etc.

**Comment by kappagaren58** [comment]
that would be really cool but it has to be so hard to make this

**Comment by ShadowWolf90** [comment]
I know it's hard, but i think adding at least some sort of animations for selected NPC, for ex. u make NPC and u call him "Swordsman", then u give him a normal iron sword, and u choose animations for him that he have katana, bcuz in your map universe he is one of the best fighters
or others

Currently there's a config with adding a custom entity, but this have already 5 AI to choose, also u have to choose texture for this entity, so you can't do anything more with changing apparel of your NPC.
Also, NPC should have some sort of options like chance to make roll, dodge etc. or use power attack or some sort of "skill" unique for this class of your NPC.
for example:
NPC A
Health: 15
Base Damage: 4 
Melee Resistance: 10% | Arrow resistance: 5% | Knockback resistance: 0%
Chance to dodge/roll: 15%
Power Attack?: Yes (Chance: 10%, multiplier 1,5x)

**Comment by Yesssssman** [comment]
I'll make the Datapack system process more complicate custom settings.
