### ISSUE TITLE
I uploaded a simplified Chinese language file. Can I add it in the next update? grateful!

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#516]
[zh_cn.json.txt](https://github.com/Yesssssman/epicfightmod/files/7071569/zh_cn.json.txt)
Please delete the suffix.txt

**Comment by Yesssssman** [comment]
As with #374, I won't include language files more than English. I think it's good to have multiple people discussing appropriate translations in each language-speaking community.
