### ISSUE TITLE
The Shield still working with a TwoHanded weapon 

### ISSUE THREAD

**Issue by Dargorix** [Yesssssman/epicfightmod#519]
There is a screenshot with a Greatsword and a Shield in the second hand.
When I want to block, it is the shield that will be used while I have learned guard.
![2021-08-29_12 30 03](https://user-images.githubusercontent.com/89711165/131247394-3a0fa1d4-8c51-47a1-8438-7f4d95fa6a16.png)

**Comment by Yesssssman** [comment]
Damn, sorry for my poor works. It will be fixed in the next update.

**Comment by Dargorix** [comment]
thank a lot
