### ISSUE TITLE
[Problem with another mod]

### ISSUE THREAD

**Issue by Ecderebi** [Yesssssman/epicfightmod#52]
We are using epic fight mod with hardcore revival mod. After someone revives my character it doesnt stand up.
Just lays down on the ground. Maybe you can fix it?

**Comment by Yesssssman** [comment]
Do you have a screenshot?

**Comment by Ecderebi** [comment]
> Do you have a screenshot?

![Issue](https://user-images.githubusercontent.com/80206351/110250296-a4fa9780-7f8b-11eb-8989-74924cc9ca1e.png)

**Comment by Yesssssman** [comment]
Ok, I'll fix this problem next version. Before I release that, you should reconnect to the server when you revive.

**Comment by Ecderebi** [comment]
Understood

8 Mar 2021 Pzt 9:57 AM tarihinde Yesssssman <notifications@github.com> şunu
yazdı:
