### ISSUE TITLE
Server environment, a NBT makes players should die once before they can use Epicfight.

### ISSUE THREAD

**Issue by Acerie** [Yesssssman/epicfightmod#526]
Minecraft 1.16.5| Epicfightmod Versions 4.1.6 and 5.0.3
ServerCore: Arclight 1.0.21 (or any other one based on Spigot? I haven't tested it)
Issue NBT: Spigot.tickLived  (Find it in *\world\playerdata\ [UUID].dat)

If Spigot.tickLived>0, survival mode players will not be able to attack in battle mode (specifically, attack-key has no response). 
They must die first and update Spigot.tickLived to 0 in order to use Epicfight.

By the way, creative mode players can't use basic attack but infinite special attacks.

**Comment by JerryNPDev** [comment]
hmm is this fixed

**Comment by Acerie** [comment]
> hmm is this fixed

excuse...？
