### ISSUE TITLE
KEYBINDS

### ISSUE THREAD

**Issue by HighCatFrame** [Yesssssman/epicfightmod#529]
not a real issue but can you make a key bind for the guard skill

**Comment by DarkScorn** [comment]
Isn't right-clicking enough? it also makes sense for other rpg games.

**Comment by HighCatFrame** [comment]
Do you think people play with one mod, there are other mods that use right
clicks to do things. Eg the demon slayer mod

**Comment by DarkScorn** [comment]
Do you think only these two mods conflict? There are many more conflicting with each other, eg. mowzies mobs axe with epic fights guard. There isn't much to do.

**Comment by HighCatFrame** [comment]
That why add a configure option would be best, you are providing my points
for me
