### ISSUE TITLE
Can't dodge

### ISSUE THREAD

**Issue by FlameyFaucet** [Yesssssman/epicfightmod#530]
Oops, i left this empty?
Anyway, i can't dodge. The default shift keybind just crouches me and there is no dodge icon. Is this a skill or something?

**Comment by Jhoczi** [comment]
I also have this problem on 1.16.5 version

**Comment by wushen233** [comment]
Didn’t you watch the author’s demo video? After 5.0, dodge skills need to learn skill books.

**Comment by FlameyFaucet** [comment]
Finally found out. It is, in fact, a skill. But i did not find any sort of demo video in the mod page, only two videos regarding the config of the mod and one showcase. The controls section did not point this out either. It should really be made clearer that dodging is a skill and _not_ a default ability.
