### ISSUE TITLE
Suggestions for further optimization of the combat part

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#534]
After experiencing the combat part today, I suddenly thought of an idea. I didn’t say that the spurs would lock the perspective and cause a sense of fragmentation, so I suddenly thought today, why not change the spur attack triggered by the player's attack while running and press the attack button? Just like the old version of the special skills, I found that the new version allows the special skills to change the keys, and I will set a separate skill trigger key, and long press the attack will be useless. And the long press time setting of the module configuration will also become useless because I changed the special skill button to other. So I have a suggestion. Simply change the spur attack that can be triggered by the player's running attack to grow and press the attack button to trigger. This mechanism is also used in other games. And the long press time setting in the module configuration becomes the setting for triggering the spur attack. I think it is enough for the player to set the key trigger for the special skill attack, because it can only be used when it is full of energy. On the contrary, the ordinary spur attack can be used at any time without energy at all. Then, if I changed the stab to grow by attacking, I used to have two thoughts about attacking when running. First: the attack is the same as the normal attack, and the second: the attack is a little higher than the attack power when walking normally. Then on the part about dodge skills, don’t there currently have two dodge skills? I think the current two dodge skills are similar except for the animation. I mean the gap is not big, I have a suggestion: Rolling skills can eliminate or be immune to part of the fall damage. Then I think the stepping skill can be added to give the player a short sprint effect at the moment of triggering. And because this skill is not like a tumbling skill. After it is triggered, the player is actually in a standing state. Because of this, I think the player does not need to press the arrow keys again after sprinting. In this way, with the short sprint effect in front, it will be very smooth.

**Comment by DarkScorn** [comment]
I think a charged attack with long-press left-click is a good idea. The question is how should weapon special abilities activate if left click is charged attack.
