### ISSUE TITLE
startup keeps saying "EntityTeleportEvent$EnderEntity"

### ISSUE THREAD

**Issue by SaidaiFinn** [Yesssssman/epicfightmod#539]
This has been happening since 5.0.0 but 5.0.0 alpha still works for me and I don't know how to fix this issue. This is the crash file.
[crash-2021-09-07_15.57.48-fml.txt](https://github.com/Yesssssman/epicfightmod/files/7124759/crash-2021-09-07_15.57.48-fml.txt)

**Comment by Yesssssman** [comment]
Update your forge version above 36.2.0.
