### ISSUE TITLE
Suggestion/Question Do weapons have Critical Chance and Damage?

### ISSUE THREAD

**Issue by Cryoraven** [Yesssssman/epicfightmod#540]
Love the work you've put into this mod and all of the compatibility files to allow for modpack creation but i tried giving my weapon critical chance and critical damage but, it doesn't apply in combat mode but applies in building mode. The mod i used to grant those stats is Apotheosis.

**Comment by Yesssssman** [comment]
Most properties of other mods don't apply to EpicFight now. Someday I'll try to fix it but I don't know when I will finish my current work. Keep looking changelog!
