### ISSUE TITLE
Illagers Crossbow Animation?

### ISSUE THREAD

**Issue by KitsuTheFloof** [Yesssssman/epicfightmod#543]
I noticed whenever I have the EpicFights mod installed, Illagers crossbows aren't shown in their hand. What I mean is like there crossbow will look like it's not equipped but they will aim with their hands. I'll show a picture for reference if necessary, and how I know it's epicfights is because when I uninstalled it, I could see the illagers crossbow animation. Their animation is basically them holding it in their hand and aiming it. But with epic fights installed, the crossbow will not be shown in their hand.

**Comment by Yesssssman** [comment]
It has been fixed in 5.0.6.
