### ISSUE TITLE
Battle Mode does not work properly

### ISSUE THREAD

**Issue by SushiRay** [Yesssssman/epicfightmod#544]
In Battle Mode, weapons still strike using vanilla attacks and not the Epic Fight combat attacks.
https://imgur.com/a/dr5zyNr

notes: I added this mod to RLCraft, and I'm running this on an RLCraft server on my PC.

**Comment by Yesssssman** [comment]
Is /gamerule doVanillaAttack false not working?

**Comment by SushiRay** [comment]
tried that gamerule, resulted in all vanilla attacks doing 0 damage

**Comment by luxias56** [comment]
Do you have BetterCombat installed? I had the same problem with BetterCombat installed and when I unistalled it, it worked just fine

**Comment by SushiRay** [comment]
No I don't, but perhaps this means there is a combat mod in RLCraft that is affecting this mod

**Comment by SushiRay** [comment]
Ah, yes I do! It's part of the RLCraft modpack. Should I remove this mod, or can the author work around this?

**Comment by luxias56** [comment]
I think you can delete BetterCombat, because even if epicfightmod became compatible with BetterCombat, the only advantage will be the random crit. All of the other feature is either useless, or already in epic fight mod (Or at least I think)

**Comment by SushiRay** [comment]
Thanks for the help! Will remove BetterCombat and test later.
