### ISSUE TITLE
[1.16.5] [5.0.6] Accessory rendering

### ISSUE THREAD

**Issue by DarkScorn** [Yesssssman/epicfightmod#545]
Accessories stay the way they were just before going into attack mode. They move with the whole character, making it look weird.
Accessories should move with their corresponding body parts. 
I never expected accessories to appear in battle mode tho, this mod is getting much better than it already is.

Here's the video about it.
https://youtu.be/Evm-5N7MYQA

**Comment by Yesssssman** [comment]
This is unfixable since I can't access the code of Accessories mod. Instead, I will add an option to disable layers.
