### ISSUE TITLE
[Feature] I know this is a frequently asked question, but...

### ISSUE THREAD

**Issue by Swilllow** [Yesssssman/epicfightmod#553]
Spartan weaponry & spartan shields compat? Please? :) (Oh and, while you're at it... perhaps some compat for some of Alex's mobs? Of course, dont rush anything. and im completely fine if this doesn't get added. (though i'd be really keen on some spartan weaponry and shields compat 😏))

**Comment by Drakoflame** [comment]
https://www.curseforge.com/minecraft/customization/epic-fight-spartan-weaponry
