### ISSUE TITLE
Epic Fight Mod Makes Capes Look Positioned Weird

### ISSUE THREAD

**Issue by KitsuTheFloof** [Yesssssman/epicfightmod#559]
It seems like the epicfights mod causes capes to be positioned incorrectly.

**How capes look with the Epic Fight Mod**
![image](https://user-images.githubusercontent.com/90358192/133481906-06903286-3567-445e-bff1-e3097d54937c.png)

**How capes look without the Epic Fight Mod**
![image](https://user-images.githubusercontent.com/90358192/133480752-308f5880-d134-48fd-98e3-47733e10fbfd.png)

**Comment by Coach-mdl** [comment]
Even tho it's a bug, it does look kinda cool.
