### ISSUE TITLE
[Suggestion] New weapon type: Bo-staff

### ISSUE THREAD

**Issue by ProjectAleph** [Yesssssman/epicfightmod#56]
I was playing around with your excellent mod when I thought to myself, "This one-handed spear combat feels slightly like a bo-staff." and just like that I came up with this concept. 

Base description:
The bo-staff is a very fast and stylish two-handed weapon that deals low amounts of damage to enemies at blazing speeds. With a fast and varied combo, the bo-staff can easily stun-lock a single opponent. When fighting a large number of enemies, the bo-staff allows you to quickly change targets in the heat of combat. However, the bo-staff can only hit a single target at a time, meaning effective use of the bo-staff will require careful positioning in order to avoid being overwhelmed. The best use of the bo-staff is to quickly lower the defenses of stronger enemies such as the enderman or the wither skeleton. Use of the bo-staff against heavily armored enemies is ill-advised, as the armor will prevent you from dealing sufficient damage to your enemy. 

The bo-staff would provide a varied and useful weapon that could be easily acquired in the early game and would serve a useful purpose in the late game. There are several craftable variants: 

- The Bo-staff is crafted with three pieces of bamboo arranged diagonally, it is the base weapon as described above. 
Stats:
Damage: 1 heart
Speed: Extremely fast
Durability: Extremely High (on par with Netherite)
Hits one enemy at a time.
Weak to armor.
Stylish combo. (inspired by Minecraft dungeons)

- The makeshift staff is crafted with three sticks arranged diagonally. The makeshift staff is the slower and weaker variant. On top of being fragile, the poor quality gives it a slower attack speed and a weak attack.
Stats:
Damage: 1/2 heart
Speed: Fast
Durability: Extremely Low (worse than gold)
Hits one enemy at a time.
Extremely Weak to armor.
Stylish combo.

- The wooden staff is crafted with three wooden planks. A solid staff that will get the job done.
Stats
Damage: 1 heart
Speed: Very fast
Durability: Low (Wooden tool)
Hits one enemy at a time.
Weak to armor.
Stylish combo.

- The Iron staff is crafted with Iron bars. being made of iron deals more damage than the bo-staff at a slower speed. its weight makes the iron staff more effective against armor. 
Stats:
Damage: 2 hearts
Speed: Fast
Durability: Medium (Iron tool)
Hits one enemy at a time.
Normal against armor.
Stylish combo.

- The Golden staff is crafted with golden ingots. What it lacks in durability, damage, and speed it makes up for in effectiveness against armor. 
Stats:
Damage: 2 hearts
Speed: Normal
Durability: Very low (Gold tool)
Hits one enemy at a time.
Strong against armor.
Stylish combo.

What do you think? Any tweaks that you would make? Would this work as a weapon at all? All the stats are up for tweaking, this is just what I came up with on the spot. I also thought about giving the bo-staff a step assist feature, kinda like a walking stick.

**Comment by Yesssssman** [comment]
Adding a new weapon is not what I am currently developing as a flagship, But I'll take note of your idea and do something like vote later.
