### ISSUE TITLE
mod incompatibility with any non vanilla attributes

### ISSUE THREAD

**Issue by DeRp-MaSte5** [Yesssssman/epicfightmod#562]
any mod that adds attributes wont do anything when you turn on fight mode on
off:
![2021-09-17_16 10 47](https://user-images.githubusercontent.com/78517263/133848096-7c0c777b-d586-4762-bbce-d46eb43a5c72.png)
on:
![2021-09-17_16 09 53](https://user-images.githubusercontent.com/78517263/133848183-f8b961fe-9ef5-4260-a755-8c9572c2c837.png)
tested on maka from lycanites mobs.
weapon has affixes from apotheosis

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
