### ISSUE TITLE
wont swing

### ISSUE THREAD

**Issue by KrysisUchiha** [Yesssssman/epicfightmod#573]
5.0.0 wont let me swing my sword at all in combat mode ive tried differnt versions but everything 5.0.0 and up dont let me swing in combat but im trying to make a mmo rpg kinda pack with epic fight in it but we cant even hit each other

**Comment by KrysisUchiha** [comment]
so i found out that it works fine in singleplayer but it doesnt work in the server

**Comment by Yesssssman** [comment]
Are the server and client have the different versions?

**Comment by KrysisUchiha** [comment]
> 
> 
> Are the server and client have the different versions?

no same version it works for like 10 mins then stops

**Comment by Yesssssman** [comment]
Have you installed any other mods?

**Comment by KrysisUchiha** [comment]
yes i installed a couple of mods but nothing that should break the mod

**Comment by idisaj93** [comment]
In my opinion, It is also a bucket problem like mohist.

**Comment by KrysisUchiha** [comment]
works fine alone  but  idk what mod  would be colliding

**Comment by KrysisUchiha** [comment]
and reminder it works fine in singleplayer with the pack of mods as well
just not on the server

**Comment by Yesssssman** [comment]
Dedicated server + No other mods: does this works fine?

**Comment by KrysisUchiha** [comment]
yes

**Comment by Yesssssman** [comment]
I can't test each mod since it takes time too long. If you have time to test them, Could you find which mod causes this problem?

**Comment by Yesssssman** [comment]
Then I'll postpone this problem. I'll mention this issue again when someone reports me the same problem.
