### ISSUE TITLE
Config is drunk

### ISSUE THREAD

**Issue by Coach-mdl** [Yesssssman/epicfightmod#575]
The config like to reset the main TOML file and put all the updates in multiple BAK files. This typically happens when I load up the pack with the updated config. I don't know if this is a notepad++ thing or if the config file has amnesia.

If it helps, here is how I'm structuring the lines:
```
[custom_weaponry.spartan_glaive_lead]
		armor_ignorance = 0.0
		hit_at_once = 3
		impact = 1
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT
		weapon_type = "SPEAR"
		registry_name = "spartanweaponry:glaive_lead"
```

**Comment by Coach-mdl** [comment]
It seems this is an issue to do with forge. A lot of TOML files do this.

**Comment by Yesssssman** [comment]
You should turn off Minecraft when you edit the .toml file. Since the file stream is occupied by Minecraft, it won't be saved normally.
