### ISSUE TITLE
Game crash when swinging Tetra hammer

### ISSUE THREAD

**Issue by EigentlicherVogel** [Yesssssman/epicfightmod#576]
--  Versions: --

Minecraft 1.16.5
Forge 36.2.5
Epic Fight 5.0.6
(Details in log)

-- Step to reproduce: --

(1) Install Tetra and EFM, both newest version
(2) Create new world
(3) Spawn a hammer from Tetra's creative menu
(4) Switch to battle mode, swing the hammer in main hand
(5) Hammer swings very slowly, then game crashes with java.lang.NullPointerException: Ticking player

-- Detailed Crash Report: --

https://pastebin.com/WxPQ4vGr

**Comment by Yesssssman** [comment]
Fixed in 5.1.0.
