### ISSUE TITLE
Katana generation issue

### ISSUE THREAD

**Issue by knighto14** [Yesssssman/epicfightmod#577]
Me and my friend were having issues with finding a katana in dungeon chests in our game so i went to a testing world and made 99 chests that called for the dungeon loot table and 0 katanas generated, in the image is all of the chests i generated and none of them had a katana
![image](https://user-images.githubusercontent.com/91307474/134625588-77d023eb-481e-4712-90e4-ea88213fc271.png)

**Comment by XanTheMann** [comment]
You find them in desert and jungle temples.
