### ISSUE TITLE
Sprinting issue

### ISSUE THREAD

**Issue by InviteKnight** [Yesssssman/epicfightmod#578]
When you bring out a longsword, it tends to lock in that sword pose that makes the sword point away from you, (kinda like you’re about to duel someone) it’s a bit weird attempting to get out of that animation, I myself don’t know how to cancel it. Whilst that animation is active, I can’t sprint at all, not even if I unequip the weapon. It isn’t a permanent thing, but it happens often enough when I use the longsword

**Comment by knighto14** [comment]
to get out of that animation you need to press the special attack button AGAIN as that defensive stance that prevents you from sprinting is the longsword's special attack and the upside is supposed to be that you auto block any attack if you aren't attacking at that moment
