### ISSUE TITLE
Not Loading

### ISSUE THREAD

**Issue by Subzero90909** [Yesssssman/epicfightmod#579]
When I try to load any of the versions I get this:
Mod File: EpicFightMod-1.16.5-5.0.6.jar
	Failure message: Epic Fight Mod (epicfight) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/living/EntityTeleportEvent$EnderEntity
I think it has to be the problem with entities like Ender man, and Ender mites and I play with only one mod which is optifine.

**Comment by FlameyFaucet** [comment]
Remove it. Optifine is very unfriendly to mods.

**Comment by Yesssssman** [comment]
You should update the forge version to avoid this issue. The latest Epic Fight mod's matching forge version is 36.2.0
