### ISSUE TITLE
Crash Nef's Medieval Decorations

### ISSUE THREAD

**Issue by Jollyolsport** [Yesssssman/epicfightmod#583]
Forge Version: 1.16.5
Epic Fight Version: 5.0.6
Nef's Medieval Decorations Version: NefsMedievalPub+v0.9(1.16.5).jar

Upon starting the attack animation while using the "Blacksmith Hammer" from Nef's Medieval Decorations the game will crash.
[crash-2021-09-27_13.19.29-server.txt](https://github.com/Yesssssman/epicfightmod/files/7238186/crash-2021-09-27_13.19.29-server.txt)

**Comment by Yesssssman** [comment]
Fixed in 5.1.0.
