### ISSUE TITLE
A few buggy shields

### ISSUE THREAD

**Issue by Cheeky0wl** [Yesssssman/epicfightmod#588]
I noticed that some spartan shields are still held in the wrong orientation. Rectangular shields that are similar in shape to vanilla are fine.
![image](https://user-images.githubusercontent.com/47038331/135790893-35a38d43-4cc0-42b0-a951-8de183f0f306.png)
But "round" shields are the ones that have issues
Shield with guard down:
![image](https://user-images.githubusercontent.com/47038331/135790771-e8461e62-dc29-4853-93bd-a094cb38a674.png)
Shield with guard up:
![image](https://user-images.githubusercontent.com/47038331/135791121-c8fc00aa-f95c-4acb-8958-7b192bf092fc.png)

Alex's mobs shield of the deep also suffers from this
![image](https://user-images.githubusercontent.com/47038331/135791293-d4d08033-2caa-4e0f-9f50-1496b856ba7c.png)

And lastly Immersive engineering's heavy plated shield 
![image](https://user-images.githubusercontent.com/47038331/135791776-c88a32bd-feb1-4d76-af2f-c0ddcc9b9ced.png)

Which is a shame since IE's shield is one of the best looking ones out there.

**Comment by Yesssssman** [comment]
I can't correct each item's visual position from other mods. I guess the author of the mod used a different way from vanilla to render the shield. It can't be fixed unless the mod creator decides to modify it.
