### ISSUE TITLE
[bug] Unexpected crash in game 

### ISSUE THREAD

**Issue by hitmanssilent** [Yesssssman/epicfightmod#59]
Hey bro, I'm the one who crashes the game when we fight against a dragon or a cyclops, I was experimenting more with the different modes of fighting with weapons and came to the conclusion that the game only crashes when you have selected a two-handed weapon and your character is mounted on something (including when an enemy of some mod grabs you), in fact, it not only happens when you are in a fight with a dragon but it also happens when you are mounted on a horse, a donkey or a boat. By the way, this only happens when we are in 3rd person, when we are in first person there is no problem.

**Comment by Yesssssman** [comment]
You're right. I check the same problem when I received #54. This will be solved later version.

**Comment by hitmanssilent** [comment]
Thanks man 😃
