### ISSUE TITLE
1.12.2 configurations

### ISSUE THREAD

**Issue by Red-TF2-Sniper** [Yesssssman/epicfightmod#591]
Does 1.12.2 config support multiple configurations, if yes then how does it work since  your video on 1.16.5 doesn't work

**Comment by Red-TF2-Sniper** [comment]
if I modify the config in-game it works just fine, but when I try to modify the config via notepad and load with said changes, the mod shits its self and refuse to load Minecraft until I reset the config file [deleting config]

**Comment by Yesssssman** [comment]
You should turn off Minecraft when you change the config file. And 1.12.2 is using an outdated method for configuration so I recommend using 1.16.5.

**Comment by Red-TF2-Sniper** [comment]
you mean 1.12.2 has an outdated method or your 1.12.2 mod config?

**Comment by Yesssssman** [comment]
Yes, the latest version uses data packs which is more convenient than a configuration file. 1.12.2's configuration format is messy and inefficient.

**Comment by Red-TF2-Sniper** [comment]
well alright, but do you plan to update the 1.12.2 config/continuing support for 1.12.2? or giving support for other mods, such has Chocolate Quest Repoured, Aether Legacy, or maybe medieval craft?

**Comment by Red-TF2-Sniper** [comment]
alright then, Ill close this then

**Comment by kiankashiro** [comment]
how to make a new system for this 1.12.2 ? can tell me ? , i want to try
