### ISSUE TITLE
5.1.0 The shield animation cannot be displayed normally, and the two-handed weapon display overlaps

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#594]
![image](https://user-images.githubusercontent.com/46721555/136005793-6f5faa6d-9bea-453d-b3c9-b9b6f28ea218.png)
![image](https://user-images.githubusercontent.com/46721555/136005814-c0b2252c-9341-4357-9377-04a8e5644904.png)
![image](https://user-images.githubusercontent.com/46721555/136005855-68b3d8ad-02da-475f-9b1a-edcc9d47b596.png)

**Comment by Yesssssman** [comment]
How did you put the katana in offhand? It's not supposed to be there.

**Comment by wushen233** [comment]
> 你是怎么把武士刀放在手边的？它不应该在那里。

I am also very curious. I switched over by directly pressing the f key, but the old version is also available. Put the mouse on the backpack interface and press f to switch to the deputy.

**Comment by Yesssssman** [comment]
Have you installed any other mods?

**Comment by wushen233** [comment]
> 有没有安装其他的mod？

Yes, but it’s okay in 5.0.6

**Comment by Yesssssman** [comment]
Many internal codes are changed in 5.1.0 so there can be a potential problem. Could you let me know the mod's name?

**Comment by wushen233** [comment]
> 许多内部代码在 5.1.0 中发生了变化，因此可能存在潜在问题。你能告诉我这个mod的名字吗？

curios，CosmeticArmorReworked，ophisticatedbackpacks，NyfsQuive，Paraglider，PassableFoliage，backslot，InvMove，ItemPhysic
