### ISSUE TITLE
rendering issue

### ISSUE THREAD

**Issue by ClockworkzAI** [Yesssssman/epicfightmod#603]
When the  minecraft runs it crash on start up, using EpicFightMod-1.16.5-5.1.0.jar.

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/6/21 3:30 PM
Description: Rendering overlay

java.lang.NullPointerException: Rendering overlay
	at software.bernie.geckolib3.util.json.JsonAnimationUtils.getObjectListAsArray(JsonAnimationUtils.java:187) ~[?:3.0.46] {re:classloading}
	at software.bernie.geckolib3.util.json.JsonAnimationUtils.getAnimations(JsonAnimationUtils.java:36) ~[?:3.0.46] {re:classloading}
	at software.bernie.geckolib3.file.AnimationFileLoader.loadAllAnimations(AnimationFileLoader.java:26) ~[?:3.0.46] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$reload$0(GeckoLibCache.java:70) ~[?:3.0.46] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache$$Lambda$14014/142113813.apply(Unknown Source) ~[?:?] {}
	at software.bernie.geckolib3.resource.GeckoLibCache.lambda$null$5(GeckoLibCache.java:88) ~[?:3.0.46] {re:classloading}
	at software.bernie.geckolib3.resource.GeckoLibCache$$Lambda$14106/175800161.get(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1582) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:807) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,xf:fml:fairylights:GameRendererTransformer,pl:mixin:APP:shouldersurfing.mixins.json:MixinGameRenderer,pl:mixin:APP:flywheel.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:client.MinecraftMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:fancymenu.general.mixin.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.4.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$481/1916224178.call(Unknown Source) [forge-1.16.5-36.2.4.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1409552856 bytes (1344 MB) / 2332033024 bytes (2224 MB) up to 4265607168 bytes (4068 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4576m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.5_HD_U_G8.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.4.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.4
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		Wyrmroost-1.16.3-1.2.11.jar                       |Wyrmroost                     |wyrmroost                     |1.16.3-1.2.11       |VALIDATE  |Manifest: NOSIGNATURE
		incontrol-1.16-5.2.1.jar                          |InControl                     |incontrol                     |1.16-5.2.1          |PROCESS_IM|Manifest: NOSIGNATURE
		DoggyTalents-1.16.5-2.1.0.1.jar                   |Doggy Talents 2               |doggytalents                  |2.1.0.1             |VALIDATE  |Manifest: NOSIGNATURE
		rsgauges-1.16.4-1.2.11.jar                        |Gauges and Switches           |rsgauges                      |1.2.11              |VALIDATE  |Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		BetterCaves-Forge-1.16.4-1.1.2.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |PROCESS_IM|Manifest: NOSIGNATURE
		ForgeEndertech-1.16.5-7.2.1.0-build.0180.jar      |Forge Endertech               |forgeendertech                |7.2.1.0             |PROCESS_IM|Manifest: NOSIGNATURE
		TerraForged-1.16.5-0.2.15.jar                     |TerraForged                   |terraforged                   |0.2.15              |VALIDATE  |Manifest: 7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |VALIDATE  |Manifest: NOSIGNATURE
		alexsmobs-1.12.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.1              |VALIDATE  |Manifest: NOSIGNATURE
		farmersdelightintegrations-1.16.5-1.2.jar         |Farmer's Delight Compats      |farmersdelightintegrations    |1.16.5-1.2          |PROCESS_IM|Manifest: NOSIGNATURE
		YungsApi-1.16.4-Forge-12.jar                      |YUNG's API                    |yungsapi                      |1.16.4-Forge-12     |PROCESS_IM|Manifest: NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |PROCESS_IM|Manifest: d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		itemzoom-1.16.4-2.3.0.jar                         |Item Zoom                     |itemzoom                      |2.3.0               |PROCESS_IM|Manifest: NOSIGNATURE
		wyrmroostspawncontrol-0.1.2.jar                   |Wyrmroost Spawn Control       |wyrmroostspawncontrol         |0.1.2               |PROCESS_IM|Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.5.15.jar                      |Carry On                      |carryon                       |1.15.5.15           |VALIDATE  |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		Paraglider-1.16.5-1.3.2.2.jar                     |Paraglider                    |paraglider                    |1.3.2.2             |PROCESS_IM|Manifest: NOSIGNATURE
		MmmMmmMmmMmm-1.16.5-1.3.1.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.3.0               |VALIDATE  |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.17.3.jar                 |Supplementaries               |supplementaries               |1.16.5-0.17.2       |PROCESS_IM|Manifest: NOSIGNATURE
		konkrete_1.3.0_MC_1.16.2-1.16.5.jar               |Konkrete                      |konkrete                      |1.3.0               |PROCESS_IM|Manifest: NOSIGNATURE
		OreTweaker-1.16.5-2.5.1.jar                       |Ore Tweaker                   |oretweaker                    |2.5.1               |PROCESS_IM|Manifest: NOSIGNATURE
		chocolate-1.3.0-1.16.4.jar                        |Chocolate                     |chocolate                     |1.3.0-1.16.4        |PROCESS_IM|Manifest: NOSIGNATURE
		mcw-bridges-1.0.6-mc1.16.5.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.6               |PROCESS_IM|Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.4.6.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.6        |VALIDATE  |Manifest: NOSIGNATURE
		fd_cookbook-2.0.jar                               |Farmers Delight Cookbook      |fd_cookbook                   |2.0                 |PROCESS_IM|Manifest: NOSIGNATURE
		divedeeper-0.1.1.jar                              |Dive Deeper                   |divedeeper                    |0.1.1               |PROCESS_IM|Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |PROCESS_IM|Manifest: NOSIGNATURE
		projectvibrantjourneys-1.16.5-3.2.10.jar          |Project: Vibrant Journeys     |projectvibrantjourneys        |1.16.5-3.2.10       |PROCESS_IM|Manifest: NOSIGNATURE
		fairylights-4.0.5-1.16.5.jar                      |Fairy Lights                  |fairylights                   |4.0.5               |VALIDATE  |Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |VALIDATE  |Manifest: NOSIGNATURE
		relics-0.2.11.1.jar                               |Relics                        |relics                        |0.2.11.1            |VALIDATE  |Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |PROCESS_IM|Manifest: NOSIGNATURE
		collective-1.16.5-2.64.jar                        |Collective                    |collective                    |2.64                |PROCESS_IM|Manifest: NOSIGNATURE
		BetterStrongholds-1.16.4-1.2.1.jar                |YUNG's Better Strongholds     |betterstrongholds             |1.16.4-1.2.1        |PROCESS_IM|Manifest: NOSIGNATURE
		antiquewaystones-1.3.jar                          |Antique Waystones             |antiquewaystones              |1.3                 |PROCESS_IM|Manifest: NOSIGNATURE
		TheAbyss2 1.9.7 1.16.5.jar                        |TheAbyss                      |theabyss                      |1.9.7               |VALIDATE  |Manifest: NOSIGNATURE
		architectury-1.23.33-forge.jar                    |Architectury                  |architectury                  |1.23.33             |PROCESS_IM|Manifest: NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |PROCESS_IM|Manifest: NOSIGNATURE
		cloth-config-4.11.26-forge.jar                    |Cloth Config v4 API           |cloth-config                  |4.11.26             |PROCESS_IM|Manifest: NOSIGNATURE
		The_Undergarden-1.16.5-0.5.5.jar                  |The Undergarden               |undergarden                   |0.5.5               |PROCESS_IM|Manifest: NOSIGNATURE
		smallships-1.16.5-1.10.1.jar                      |Small Ships Mod               |smallships                    |1.10.1              |VALIDATE  |Manifest: NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.4.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.4        |PROCESS_IM|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.46.jar                  |GeckoLib                      |geckolib3                     |3.0.46              |PROCESS_IM|Manifest: NOSIGNATURE
		mowziesmobs-1.5.19.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.19              |VALIDATE  |Manifest: NOSIGNATURE
		handoveryouritems_1.16.5-1.3.jar                  |Hand Over Your Items          |handoveryouritems             |1.3                 |PROCESS_IM|Manifest: NOSIGNATURE
		ftb-library-forge-1605.3.3-build.74.jar           |FTB Library                   |ftblibrary                    |1605.3.3-build.74   |PROCESS_IM|Manifest: NOSIGNATURE
		[1.16.5] ComicsBubblesChat-1.2.1.jar              |Comics Bubbles Chat           |comicsbubbleschat             |version             |PROCESS_IM|Manifest: NOSIGNATURE
		spiders-2.0-1.16.4-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |PROCESS_IM|Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.122.jar                          |Just Enough Items             |jei                           |7.7.1.122           |PROCESS_IM|Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.0.jar                   |Abnormals Core                |abnormals_core                |3.3.0               |VALIDATE  |Manifest: NOSIGNATURE
		copperpot-1.16.5-1.1.2.jar                        |Copper Pot                    |copperpot                     |1.16.5-1.1.2        |PROCESS_IM|Manifest: NOSIGNATURE
		createchunkloading-0.2.0.jar                      |Create Chunkloading           |createchunkloading            |0.2.0               |PROCESS_IM|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.3.jar                        |Waystones                     |waystones                     |7.6.3               |PROCESS_IM|Manifest: NOSIGNATURE
		BetterPortals-1.16.4-0.3.8.jar                    |YUNG's Better Portals         |betterportals                 |1.16.4-0.3.8        |VALIDATE  |Manifest: NOSIGNATURE
		EpicFightMod-1.16.5-5.1.0.jar                     |Epic Fight Mod                |epicfight                     |5.1.0               |VALIDATE  |Manifest: NOSIGNATURE
		Clumps-6.0.0.27.jar                               |Clumps                        |clumps                        |6.0.0.27            |PROCESS_IM|Manifest: NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.3.jar                |Traveler's Backpack           |travelersbackpack             |5.4.3               |VALIDATE  |Manifest: NOSIGNATURE
		Artifacts-1.16.5-2.10.2.jar                       |Artifacts                     |artifacts                     |1.16.5-2.10.2       |VALIDATE  |Manifest: NOSIGNATURE
		smarterfarmers-1.16.5-1.2.1.jar                   |Smarter Farmers               |smarterfarmers                |1.16.5-1.2          |PROCESS_IM|Manifest: NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.121-universal.jar      |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.121    |PROCESS_IM|Manifest: NOSIGNATURE
		ColtCosmeticArmorMod-1.2.5.jar                    |Colt's Cosmetic Armour Mod    |ccam                          |1.0.1               |PROCESS_IM|Manifest: NOSIGNATURE
		AdHooks-1.16.5-6.1.7.0-build.0179.jar             |Advanced Hook Launchers       |adhooks                       |6.1.7.0             |PROCESS_IM|Manifest: NOSIGNATURE
		betteranimalsplus-1.16.5-10.2.0.jar               |Better Animals Plus           |betteranimalsplus             |10.2.0              |PROCESS_IM|Manifest: NOSIGNATURE
		walljump-forge-1.16.4-1.3.7.jar                   |Wall-Jump!                    |walljump                      |1.16.4-1.3.7        |VALIDATE  |Manifest: NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.35.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.35            |PROCESS_IM|Manifest: NOSIGNATURE
		iChunUtil-1.16.5-10.4.1.jar                       |iChunUtil                     |ichunutil                     |10.4.1              |PROCESS_IM|Manifest: NOSIGNATURE
		CraftTweaker-1.16.5-7.1.2.451.jar                 |CraftTweaker                  |crafttweaker                  |7.1.2.451           |VALIDATE  |Manifest: NOSIGNATURE
		ImmersivePetroleum-1.16.5-3.3.0-6.jar             |Immersive Petroleum           |immersivepetroleum            |3.3.0-6             |PROCESS_IM|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.4-universal.jar                 |Forge                         |forge                         |36.2.4              |VALIDATE  |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		goprone-1.16.4-1.3.5.jar                          |GoProne                       |goprone                       |1.16.4-1.3.5        |PROCESS_IM|Manifest: NOSIGNATURE
		dotcoinmod-1.16_V10.jar                           |Dot Coin Mod                  |dotcoinmod                    |1.16 v10            |PROCESS_IM|Manifest: NOSIGNATURE
		immersiveposts-1.16.5-4.2.2.jar                   |Immersive Posts               |immersiveposts                |4.2.0               |PROCESS_IM|Manifest: d5:aa:49:67:b7:dd:64:8a:a4:7d:3e:57:12:6b:f9:3f:e8:5e:6b:24:d9:f9:c5:fb:c5:e7:a0:cf:98:64:dc:d0
		DynamicSurroundings-1.16.4-4.0.4.2.jar            |§3Dynamic Surroundings        |dsurround                     |1.16.4-4.0.4.2      |PROCESS_IM|Manifest: b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		selene-1.16.5-1.8.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |PROCESS_IM|Manifest: NOSIGNATURE
		antiqueatlas-6.0.1-forge-mc1.16.5.jar             |Antique Atlas                 |antiqueatlas                  |6.0.1-forge-mc1.16.5|PROCESS_IM|Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.47-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.47              |PROCESS_IM|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.4-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |PROCESS_IM|Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.3.1.jar                        |CoFH Core                     |cofh_core                     |1.3.1               |VALIDATE  |Manifest: NOSIGNATURE
		TConstruct-1.16.5-3.1.3.271.jar                   |Tinkers' Construct            |tconstruct                    |3.1.3.271           |VALIDATE  |Manifest: NOSIGNATURE
		voicechat-forge-1.16.5-1.7.8.jar                  |Simple Voice Chat             |voicechat                     |1.16.5-1.7.8        |VALIDATE  |Manifest: NOSIGNATURE
		pandoras_creatures-1.16.3-2.0.1.jar               |Pandoras Creatures            |pandoras_creatures            |1.16.3-2.0.1        |PROCESS_IM|Manifest: NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |VALIDATE  |Manifest: NOSIGNATURE
		mana-and-artifice-1.4.0.8.jar                     |Mana and Artifice             |mana-and-artifice             |1.4.0.8             |VALIDATE  |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.16.5-5.0.3-138.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.0.3-138    |VALIDATE  |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		ShoulderSurfing-1.16.5-2.2.1.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.5-2.2.1        |PROCESS_IM|Manifest: NOSIGNATURE
		archers_paradox-1.16.5-1.3.1.jar                  |Archer's Paradox              |archers_paradox               |1.3.1               |PROCESS_IM|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		towers_of_the_wild-1.16.4-2.0.1.jar               |Towers Of The Wild            |towers_of_the_wild            |1.16.4-2.0.1        |VALIDATE  |Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |VALIDATE  |Manifest: NOSIGNATURE
		extragolems-16.5.2.jar                            |Extra Golems                  |golems                        |16.5.2              |PROCESS_IM|Manifest: NOSIGNATURE
		Craftable Saddles [1.16 All]-1.3.jar              |Craftable Saddles             |craftable_saddles             |1.3                 |PROCESS_IM|Manifest: NOSIGNATURE
		flywheel-1.16-0.2.4.jar                           |Flywheel                      |flywheel                      |1.16-0.2.4          |VALIDATE  |Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2d.jar                       |Create                        |create                        |v0.3.2d             |ERROR     |Manifest: NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |PROCESS_IM|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.127.jar                         |Mantle                        |mantle                        |1.6.127             |VALIDATE  |Manifest: NOSIGNATURE
		Inspirations-1.16.5-1.2.3.38.jar                  |Inspirations                  |inspirations                  |1.2.3.38            |VALIDATE  |Manifest: NOSIGNATURE
		twoplayersonehorse-1.16.4-2.0.2.jar               |2 players 1 horse             |twoplayersonehorse            |1.16.4-2.0.2        |PROCESS_IM|Manifest: NOSIGNATURE
		fancymenu_2.3.3_MC_1.16.2-1.16.5.jar              |FancyMenu                     |fancymenu                     |2.3.3               |PROCESS_IM|Manifest: NOSIGNATURE
		ferritecore-2.0.7-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.7               |PROCESS_IM|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Aquaculture-1.16.5-2.1.21.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.21       |PROCESS_IM|Manifest: NOSIGNATURE
		farmerstea-1.16.5-1.3.jar                         |Farmer's Tea - A Compat Mod   |farmerstea                    |1.16.5-1.3          |PROCESS_IM|Manifest: NOSIGNATURE
		TA2 beginning 1.0.9 1.16.5.jar                    |[Add-on] The Abyss: The Beginn|thebeginning                  |1.0.9               |VALIDATE  |Manifest: NOSIGNATURE
		expandability-2.0.2-forge.jar                     |ExpandAbility                 |expandability                 |2.0.2               |PROCESS_IM|Manifest: NOSIGNATURE
		createaddition-1.16.5-20210930a.jar               |Create Crafts & Additions     |createaddition                |1.16.5-20210930a    |PROCESS_IM|Manifest: NOSIGNATURE
	Crash Report UUID: 7c1011c4-1d6f-4368-a9ea-518e9ee70750
	Patchouli open book context: n/a
	Launched Version: forge-36.2.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 472.12, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8
	OptiFine Build: 20210515-161946
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v8.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 472.12
	OpenGlRenderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Yesssssman** [comment]
I checked it. It'll be fixed in next update.
