### ISSUE TITLE
Fight Mode stops working after rejoin

### ISSUE THREAD

**Issue by CleverWind77** [Yesssssman/epicfightmod#609]
Fight Mode stops working(nothing happens when pressing LMB) after rejoining the server, killing player fix this problem but only until the next rejoin.
Mohist 1.16.5(or Magma 1.16.5)
Epic Fight 1.16.5-5.1.1

**Comment by Yesssssman** [comment]
Normally, It was turned out that the server with a different API (Mohist in your case) has a lot of problems. I recommend you to use the pure Forge server.
