### ISSUE TITLE
Incorrect captions

### ISSUE THREAD

**Issue by Coach-mdl** [Yesssssman/epicfightmod#611]
I will now provide a low quality image. This is the same with all sounds from the mod.

![image](https://user-images.githubusercontent.com/59576000/136446805-dccc80f3-a5f7-4847-bea4-b121e9e30675.jpeg)

https://user-images.githubusercontent.com/59576000/136446888-888ddc6b-d115-4718-992f-d913fb3f67ca.MOV

**Comment by Yesssssman** [comment]
This gonna be a huge challenge for me because I'm not a native English. Well, It'll be fixed in the next update.
