### ISSUE TITLE
Future Plans for the mod

### ISSUE THREAD

**Issue by XanTheMann** [Yesssssman/epicfightmod#62]
Hi! Big fan of the mod so far. Just wanted to know what plans you have for the mod in the near future. What features do you want to add most? When in your mind will it be complete?

Thanks!

-XanTheMann

**Comment by Yesssssman** [comment]
I don't have a detailed plan for the future, but I want to add more weapon types with attacking motions and an RPG-style dungeon with new mobs. but first of all, I'd like to make more compatibility with other mods since there're already awesome mods adding epic weapons and monsters.
