### ISSUE TITLE
5.1.1 The issue with shield animation not playing and katana overlay remains

### ISSUE THREAD

**Issue by redtardis12** [Yesssssman/epicfightmod#625]
I installed a new version of the mod and i still have the same issues as it was described [here](https://github.com/Yesssssman/epicfightmod/issues/594)

Two-handed weapon display overlaps issue still remains
![2021-10-10_22 56 44](https://user-images.githubusercontent.com/33347417/136711410-1b8e2032-4fcc-4bef-b76b-2f25b61be830.png)

Apparently, you still can hold a katana in off-hand. I managed to do this by opening inventory menu, pick up the katana item, put it back and press F still being in the menu.
![2021-10-10_22 56 56](https://user-images.githubusercontent.com/33347417/136711513-8927bd68-e9e4-41ff-bb21-7e42c82c3b76.png)

And the shield animation still doesn't displays, even though it's mentioned in changelog
(on this screenshot i hold right click and it seems that shield is working, as the player moves slower, but visually nothing changes)
![2021-10-10_22 57 50](https://user-images.githubusercontent.com/33347417/136711584-3420b88f-ea30-4806-b17e-dcadd2a54526.png)

I don't use any mods except  OptiFine HD_U_G7

**Comment by Yesssssman** [comment]
Plus, I found the shield animation is not played when the shield is held by offhand. It will be fixed in next update.
