### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by notkidgamer23** [Yesssssman/epicfightmod#638]
Crashes with Epic Fight, no crashes without epic fight installed. 
Here's the log
PS keep up the great work

https://pastebin.com/X51RY8zW

**Comment by Yesssssman** [comment]
I guess this problem was caused by the incompatibility of Botania. I'll check what's the problem. Could you check it?

**Comment by notkidgamer23** [comment]
Did some testing today and was able to get it down to a conflict between epic fight and special ai, here's the updated log 
https://pastebin.com/1E1hXaHB

Not sure who would need to fix it in this case
