### ISSUE TITLE
Ticking Player Crash(s)

### ISSUE THREAD

**Issue by Coraline77447** [Yesssssman/epicfightmod#64]
It's me again but this time with another issue that whenever I tried to put any "weapon" (except for the bow) in my offhand slot that the game crashes. I think it has somethin to do with another mod called Tons Of Enchants which what that mod does is it adds enchantments and one in particular seems to not play well with Epic Fight Mod that the game crashes. Anyways here's the crash report and log:

Crash Report:  [crash-2021-03-10_05.09.42-server.txt](https://github.com/Yesssssman/epicfightmod/files/6115729/crash-2021-03-10_05.09.42-server.txt)

Log:  [latest.log](https://github.com/Yesssssman/epicfightmod/files/6115746/latest.log)

Btw I've just looked into this log that I've provided to you and I see the mod Tons Of Enchantments in there with one of it's enchants that applies an attribute when an attribute that's possibly similar was already applied to the player somehow without me even having the enchantment on my items. So I'll go report this same issue to them but it would be about one of their enchantments conflicting with another mod. I originally thought that this issue was caused from a mod called Attribute Fix+ but the game crashed without it as the same error from before so it ain't Attribute Fix+ that's causing this.
Also;
Minecraft: 1.16.5
Forge: 36.0.46
Epic Fight Mod: 3.0.2
Tons of Enchants: 0.4 SERVER-FIX

**Comment by Yesssssman** [comment]
I guess I have to update the developing environment to 1.16.5 forge. All crashes are occurred from registering Attributes. I'll notify you then.

**Comment by Yesssssman** [comment]
Hey, could you try it in the 3.0.4 version? I updated the development environment, so I hope it would fix the problem.

**Comment by Coraline77447** [comment]
I had downloaded version 3.0.3 but not 3.0.4 yet but after I'm finished with a different game called Block City Wars (later on today) before I start my modded minecraft play session then I'll grab 3.0.4 and see if it's fixed also the owner of Tons of Enchants wanted discord so that both him and I could discuss about the problem which may not be one of his enchantments (heart healthy).

**Comment by Coraline77447** [comment]
I think I may know the main cause of the issue is. I have a mod called OffHandCombat which allows me to use anything that can deal entity damage (i.g. I can dual wield two netherite swords or axes with OffHandCombat) and Epic Fight Mod may be hard-coded to only allow us to use both vanilla and/or modded weapons in our main hand, especially when we're in combat mode. In the comments on Epic Fight Mod's curseforge page I had asked if this mod was compatible with Epic Fight Mod. 
Well now we may know the answer now that both of these mods aren't compatible since I just did the same thing again but this time with Project Rankine's Invar Hammer and yes the game did crash again from the same crash as before. Again... 
Tons Of Enchants has nothing to do with all of this mess and neither does Attribute Fix and Tiered. 
So there really is a confliction between two mods, OffHandCombat and Epic FIght Mod.
Now that I may have discovered the main cause of this now I have three options; 
1) I continue to play with both mods but I can no longer dual wield but there won't be any more crashes if I avoid putting any tool or weapon (except for the bow since I can't put the bow in the off-hand slot anyways since Epic Fight Mod prevents this) both vanilla or modded. 
2) I remove Epic Fight Mod to allow dual wielding but I won't have Epic Fight Mod's custom combat system and the animations form the mod... 
3) I remove OffHandCombat to have Epic Fight Mod's custom combat system and its awesome animations but there won't be any more dual wielding...
Which one shall I do while I wait for a compatibility with both of these mods if possible?

**Comment by koderian** [comment]
Might this be related to issue #72? I am also having server issues and the latest version that works with my server right now is 3.0.2. Something past that versions must have been changed to cause such issues

**Comment by Coraline77447** [comment]
Yes this issue may relate to yours and my recent world may have just died from this piece of code (maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84) from Epic Fight Mod while playing with Nugget's Dungeons II mod.
Apparently Epic Fight Mod doesn't like playing with certain dungeon mods and mods like Project Rankine. 
There's something definitely wrong with at piece of code and what does it do? 
What is it responsible for and why doesn't it like other mods and certain dungeon mods. 
I feel like I'm going to stop playing with Epic Fight Mod till this issue gets fixed cause it's starting to annoy me now and losing my most recent world to this problem is the last straw to be playing with this mod since a few pieces of it are clearly broken in some way. 
Sure some people may manage to find a fix for this issue but I just don't have the time and patience to figure out how to fix this issue myself and it's not my responsibility to find a fix for this problem since it ain't my mod to do that in the first place. 
So until this issue is fixed/removed I'm gonna either backport the mod version to a time when the mod was working properly (3.0.2 or prior to 3.0.2) or I completely stop playing with Epic Fight Mod...

**Comment by Coraline77447** [comment]
Hi, does the latest version (3.1.1) finally fixes (maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84)? 
Or do I and many other people who has experienced issues with (maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84) still has to wait till you find the solution to it?

**Comment by koderian** [comment]
Same issue on 3.1.3. Still getting maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:82) ~[epicfight:1.0] {re:classloading}. The latest version that works for me is 3.0.2 @Yesssssman

**Comment by Coraline77447** [comment]
I'm no longer playing with Epic Fight Mod cause I ran inti another crash which was a weird one that I have Not Enough Crashes installed and instead of being put back to the title screen I was brought to the multiplayer server screen. btw "maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:82) ~[epicfight:1.0] {re:classloading" thats what was my last crash which is the very last straw for playing with this mod till @Yesssssman or the owner of this mod fixes this mod cause as I see it Epic Fight Mod is in a poor state cause of some of it's capabilities not functioning properly!!!

**Comment by Yargenshmoler** [comment]
same problem as #171 #72 and #288

**Comment by Coraline77447** [comment]
Hey, Just checking in if these problems have been addressed and fixed already. 
Still not gonna play with Epic Fight Mod till those issues are resolved but I do miss playing with EFM...
Also just looked through the issues tap on here and I see that there's a butt ton of problems with EFM which makes me not want to play with EFM even tho I don't play on *multiplayer....

*(Since I don't have any friends who plays java edition, also if the multiplayer server itself is located on the other side of the world that I'll get too far behind the server itself since my internet is garbage....)
