### ISSUE TITLE
When empty handend in creative mode change automatically to fighting stands

### ISSUE THREAD

**Issue by ClockworkzAI** [Yesssssman/epicfightmod#646]
When scrolling thru the invontory of the game the you change to the fighting stand automatic. This makes it hard to for builiding in minecraft.

Minecraft:1.16.5
Mod version:5.1.3
Forge:36.2.4

**Comment by Yesssssman** [comment]
Please read the update log.

https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod/files/3481293

**Comment by Yesssssman** [comment]
Why don't you register blocks to the mining list?
