### ISSUE TITLE
Crashing when trying to join server

### ISSUE THREAD

**Issue by Yellowracecar77** [Yesssssman/epicfightmod#647]
When loading into my server it says "saving World" then I crash soon after I am going to paste the crash report below
[crash-2021-10-15_06.46.40-client.txt](https://github.com/Yesssssman/epicfightmod/files/7352897/crash-2021-10-15_06.46.40-client.txt)
.

**Comment by Yesssssman** [comment]
Crash with Performant mod. Share this report with the author of that mod.
