### ISSUE TITLE
[Suggestion] Blocking with two-handed or dual-weapon weapons or spear

### ISSUE THREAD

**Issue by hitmanssilent** [Yesssssman/epicfightmod#65]
Blocking could be added with those three combat options as it happens in Skyrim, of course, it would not cover all the melee damage like the shield does, but it could reduce the damage received, perhaps adding during the block an absorption buff or resistance, and it wouldn't cover the arrows damage at all.

**Comment by Yesssssman** [comment]
My goal is to add some skill like this
https://www.youtube.com/watch?v=GzL0mtZVybw
Is it satisfy you?

**Comment by hitmanssilent** [comment]
Hmm, I like it when it blocks with the sword, it could be a system where all damage is blocked only if it blocks at the right moment when the enemy attacks and only partial damage if it blocks all the time, like a kind of parry (thus rewarding the timing of the combat if you don't have a shield equipped), and as for the arrows, I also like it but only if it blocks at the right moment when the arrow is going to hit and only if you look directly Who shoots the arrow, because it would be more difficult to defend yourself from an arrow shot if you were surrounded by two or more enemies, or that, or only have a small dash available if you do not have a shield equipped which recharges slightly more faster than the dodge thus having two ways to evade the attack of an enemy if you do not have a shield, the dash and the dodge (I know that in this last suggestion I would not be including the block if you do not have a shield, maybe you could do a mixture of the two ideas being able to block with parry system only with two-handed weapons and dual-wield weapons, block normally if you have a shield and only be able to do a dash and a dodge if you have selected an axe, a hoe, a shovel, a single sword, a spear, a bow or a katana) -

PS: sorry if something is not understood, English is not my native language and I am better at reading it and listening it than writing it, so I help myself with the google translator and try to correct what does not translate well.
