### ISSUE TITLE
Classy Hats Support

### ISSUE THREAD

**Issue by HaaDT** [Yesssssman/epicfightmod#650]
it would be interesting for the mod to have support for Classy Hats, you can currently use it along with the mod, but when it enters combat mode the hat disappears, so I think it's necessary to support the mod, well, there's the recommendation for support

here the mod that i commented: https://www.curseforge.com/minecraft/mc-mods/classy-hats

**Comment by Yesssssman** [comment]
1.12.2 is no longer supported.
