### ISSUE TITLE
Dodge not working in server 1.12.2

### ISSUE THREAD

**Issue by Danissemo** [Yesssssman/epicfightmod#654]
Hello, on server 1.12.2, with mod version 2.2.7 on the magma core, when you first enter the world on a clean account, the dodge works, but after you re-enter the same world, the dodges simply stop working. How can this be fixed?
All this was tested without other mods, only forge and optfine.
There is no such problem in single player mode.

**Comment by dan1654** [comment]
update: Also, the server crashes if the player re-logs into the world and puts on armor on the body

**Comment by dan1654** [comment]
[crash.txt](https://github.com/Yesssssman/epicfightmod/files/7357435/crash.txt)

**Comment by Yesssssman** [comment]
Have you installed any other mods? I'm assuming that particular mod causes this crash but I can't find it 'cause most of people uses too many mods that I can't test it.

**Comment by dan1654** [comment]
> Have you installed any other mods? I assume that particular mod causes this crash but I can't find it 'cause most of people uses too many mods that I can't test it.

Everything was tested on one, this particular fashion.

**Comment by dan1654** [comment]
[world.zip](https://github.com/Yesssssman/epicfightmod/files/7357459/world.zip)

**Comment by dan1654** [comment]
Can I get into the files somehow and do something about it? I just want to play with my friends today and not delete this mod.

**Comment by Yesssssman** [comment]
I think this problem occurs in Magma. Your world works fine both in Integrated and Dedicated servers. What you and #634 Guy have in common is both using a server that consists of other API(Magma, Mohist) rather than a normal Forge server. If it works fine in the normal Forge server, I can't fix this problem.

**Comment by Yesssssman** [comment]
Since I only can refer to the Forge code, I don't have much acknowledge about other APIs. If Magma's development team can help me, maybe it could be fixed.

**Comment by WerelWolf** [comment]
here is their discord https://discord.gg/Nvd3PjmJNx, do you need the source code?

**Comment by Tirimar** [comment]
Can u please update 1.12.2 files on github?<3

**Comment by Tirimar** [comment]
I'm trying to rewrite your mod, can you please tell me what to change to fix the U-turns and putting armor on the Mohist?
