### ISSUE TITLE
Configuration file : weapon_type don't have BOW Animation yet?  If yes I want to name Valid values ​​for bow animation.

### ISSUE THREAD

**Issue by BungPeerapat** [Yesssssman/epicfightmod#655]

**Comment by BungPeerapat** [comment]
Configuration file : weapon_type don't have BOW Animation yet? If yes I want to name Valid values ​​for bow animation.

**Comment by BungPeerapat** [comment]
# Configuration file

custom {

    custom_weaponry {

        mw_m17 {
            D:armor_negation=0.0
            D:impact=0.5
            I:max_strikes=1
            S:registry_name=mw:m17
            S:weapon_type=FIST

            
        }

        sample_weapon1 {
            D:armor_negation=0.0
            D:impact=0.5
            I:max_strikes=1
            S:registry_name=modid:registryname

            # Valid values:
            # AXE
            # FIST
            # HOE
            # PICKAXE
            # SHOVEL
            # SWORD
            # SPEAR
            # GREATSWORD
            # KATANA
            S:weapon_type=PICKAXE
        }

        sample_weapon2 {
            S:registry_name=modid:registryname

            # Valid values:
            # AXE
            # FIST
            # HOE
            # PICKAXE
            # SHOVEL
            # SWORD
            # SPEAR
            # GREATSWORD
            # KATANA
            S:weapon_type=SWORD

            onehand {
                D:armor_negation=0.0
                D:impact=0.5
                I:max_strikes=1
            }

            twohand {
                D:armor_negation=0.0
                D:impact=0.5
                I:max_strikes=1
            }

        }

    }

    custom_armor {

        sample_armor {
            S:registry_name=modid:registryname
            D:stun_armor=0.0
            D:weight=0.0
        }

    }

}

**Comment by BungPeerapat** [comment]
this is my Configuration file

**Comment by Yesssssman** [comment]
1.12.2 not supports the bow type weapon. It's a problem with the old system and wouldn't be added.

**Comment by kiankashiro** [comment]
so , no any update for 1.12.2 ?
