### ISSUE TITLE
epicfight.toml config not saving/changing to default every time I open the game.

### ISSUE THREAD

**Issue by LoSilopante** [Yesssssman/epicfightmod#659]
My custom [config](https://pastebin.com/TS4AJVCT) keeps getting overwritten to the default file every time I open the game, thus making it impossible for me to add weapons from other mods.

Setting the file to 'read only' crashes the game.

This is what happens i the [log](https://pastebin.com/89mLr7eU)

**Comment by r4ven1245** [comment]
I'm having the same issue, and prefixing it with "custom_entity" doesn't work:

`[custom_entity]

    [custom_entity.dungeonsmod_guard]
        type_name = "dungeonsmod:guard"
        impact = 0.5
        max_strikes = 1
        armor_negation = 0.0
        #Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
        ai_type = "VINDICATOR"
        texture_location = "dungeonsmod:assets/dungeonsmod/textures/entity/guard.png"`
        
it just wipes the config file and the log says
`...epicfight.toml is not correct. Correcting`
`...Incorrect key custom_entity was corrected from SimpleCommentedConfig:{dungeonsmod_guard=SimpleCommentedConfig:{type_name=dungeonsmod:guard, impact=0.5, max_strikes=1, armor_negation=0.0, ai_type=VINDICATOR, texture_location=dungeonsmod:assets/dungeonsmod/textures/entity/guard.png}} to its default, null. `

**Comment by LoSilopante** [comment]
I tried seeing the mod in 1.17 and the entire configs gets wiped clean every time, well, you should open a new issue about that.
