### ISSUE TITLE
[Bugs]

### ISSUE THREAD

**Issue by Ecderebi** [Yesssssman/epicfightmod#66]
1) Hardcore revival mod.
We are still cant be revived if we use epic fight and hardcore revival mod together.
If we try reconnecting server after revival. Game crashes.
2) The player doesnt lay down on the bed. 
![Issue 2](https://user-images.githubusercontent.com/80206351/110677285-0cac1f00-81e6-11eb-964f-043f9c7f7aa6.png)

**Comment by Yesssssman** [comment]
Could you post the crash report?

**Comment by Ecderebi** [comment]
I tested it again. But this time it didnt crash. The only problems left:
Cant stand up after revival. You can add a config option to disable death animation. Or you can add  reviving animations.
(Revive animations **will** make it more epic)
Here is the mod page. https://www.curseforge.com/minecraft/mc-mods/hardcore-revival
And the only old thing... There is no sleeping animation.
