### ISSUE TITLE
Death screen Freeze

### ISSUE THREAD

**Issue by EkutoruSama** [Yesssssman/epicfightmod#663]
When I die, the death screen freezing and I need to restart
A clear and concise description of what the bug is

    1. I fight a random mob
    2. The random mob kill me
    3. Screen of Death turns my game into "No Answer"
    4 .I have to restart my game

Versions 

    Minecraft version : 1.16.5
    Forge version : 36.2.0
    Mod version : 5.1.3

Other mods
The mod that causes the Freeze is Corpse Mod

Probably because of the death animation and the body creation appear at the same time

I have contact the creator of Corpset Mod for answer
Thanks :3

![crash report](https://user-images.githubusercontent.com/77534573/137701542-1937e58d-0abf-42a0-8794-663e409b641a.PNG)

**Comment by X-Madjakk-X** [comment]
same here
