### ISSUE TITLE
Named armor texturepack issue

### ISSUE THREAD

**Issue by redtardis12** [Yesssssman/epicfightmod#665]
I tried to use the [texturepack](https://www.curseforge.com/minecraft/texture-packs/name-it-get-it-v1), that allows to name an armor and change it texture. The texurepack clearly works, but when you put on a named armor, it doesn't display. Even though regular armor texurpacks work fine. It's not the problem of this particular texturpack, as I tested other 2 familiar ones and all of them don't display. 

![2021-10-19_00 49 21](https://user-images.githubusercontent.com/33347417/137812557-856fc8ff-300d-401d-8040-ce7ae0cca23e.png)
![2021-10-19_00 49 33](https://user-images.githubusercontent.com/33347417/137812589-c1f8cd87-39c1-4599-9d67-b4b7ee0235b7.png)

I also tried to turn on smart animations, and noticed that named armor doesn't work only with fighting animations.
(here i use two texurepacks, the described one and regular texturpack that changes netherite armor texture)

https://user-images.githubusercontent.com/33347417/137813372-585ac42b-79d0-48bb-b86e-49dd697d1d2b.mp4

Important note: the texturpack i described requires Optifine to work. I have custom items setting on though. If a problem concludes in different model type, than it used in the mod, how can i convert the texture to a necessary format?

**Comment by Yesssssman** [comment]
Hello! and sorry for late reply. All optifine texturepack bugs are figured out as unfixable since I don't have a right to access to optifine code. Thanks for wait and sorry again.

**Comment by MetalKnight56** [comment]
Could you try remaking that texturepack but with CEM from JEMs ? 
https://www.curseforge.com/minecraft/mc-mods/json-entity-models-jems

**Comment by MetalKnight56** [comment]
ACTUALLY, you can do that with Custom Model Data, please try it and show me the results xD
