### ISSUE TITLE
How can i make npcs fight with this mod's features ?

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#675]
I want some guards protecting me but i have to learn how to make them fight like this mod.
Im using CustomNPCS and GuardsCraft.They are fighting like vanilla so can you teach me how to make them use this mod ?

**Comment by WerelWolf** [comment]
> You have to create an addon using the code I posted in github.

CustomNpc was released for the new version 1.16.5 I tried to integrate npc's for the animated entities but npc bugs and doesn't appear
