### ISSUE TITLE
Curios and Mekanism

### ISSUE THREAD

**Issue by RustBandit** [Yesssssman/epicfightmod#68]
First off, I'd like to say amazing job on getting modded armors working, I can confirm that ice and fire as well as various other armor mods work perfectly fine, however Mekanism and Curios are the only two I find that don't render at all, It actually appears as though I have no armor on but still this is amazing progress, as someone who see's this mod as an absolute essential for my modpack, I don't wanna list off evcery single little error, but mekanism and curios are also essentials and I feel like if more major mods like these two had compatibility that more and more people will find this as an essential too. Keep up the good work!

**Comment by Yesssssman** [comment]
I've been made an automatic model generating system based on ice and fire mod which most people mentioned to me. So it seems like that it wouldn't work well with another mod's custom armors. Hmm.. I would develop this step by step.

**Comment by RustBandit** [comment]
I'm no coder, so I won't try to simplify your work process, just though I would mention it to ya. Thank you so much for the work you've done!
