### ISSUE TITLE
Optifine glowing texture Glitch

### ISSUE THREAD

**Issue by Marentum** [Yesssssman/epicfightmod#685]
I made a custom shield with a glowing texture that makes the whole character glow.
This applies to some entities
![1](https://user-images.githubusercontent.com/93139398/138709299-69effc49-c450-4eb2-ac21-23cb575f5f59.jpg)
![2](https://user-images.githubusercontent.com/93139398/138709312-f3fef542-51d9-42f3-989f-b62d4cb51ece.jpg)
.

**Comment by Yesssssman** [comment]
Optifine issues are unable to fix for now because it's not an open source.
