### ISSUE TITLE
[bug] condition stats for tools conficts wtih general keybinds

### ISSUE THREAD

**Issue by Shibva** [Yesssssman/epicfightmod#689]
idk how to explain tihs, but I will try

in the instance and setup I have, I have an action keybind set to be Shift + F, I found that if in holding an item wtih the tag "Two-handed" and "mainhand only" and press the keybind that the keybind will NOT be set off for whatever reason, but when im not holding those items wtih those tags, the keybinds work

furthermore I found that I cant shift+click items with these tags into other slots, same goes for hovering over tiems and pressing a hotbar slot keybind

if you can fix this that would be nice

**Comment by SteamDoge9000** [comment]
I would like to re-open this issue on the terms that the bug still prexsist

**Comment by SteamDoge9000** [comment]
and by presist I mean some of the key fuctions when setting keybinds are not working

in the case I have it, I have something that enables NV when I press SHIFT + F while in game (not inventory GUI) and it works, but when I hold an item that cannot be shifted into the offhand menu by whatever you did, it seems to be also affecting the functionality of that keybind as well
