### ISSUE TITLE
Bug Resume

### ISSUE THREAD

**Issue by Allomere** [Yesssssman/epicfightmod#69]
### **Visual Bugs**
**The Texture for the left shoulder of the player's skin is rotated 90° clockwise:**
![Shoulder](https://user-images.githubusercontent.com/71918599/110733946-a0411800-8205-11eb-8388-1161929291c0.png)

**The Texutre for the left shoulder of the armors  are rotated 180°** _[doesn't happen on custom models]_:
![Shoulder Armor 1](https://user-images.githubusercontent.com/71918599/110734128-f2823900-8205-11eb-9903-d96001492ec7.png)
> Should be like this:
> ![Shoulder Armor 2](https://user-images.githubusercontent.com/71918599/110734170-0168eb80-8206-11eb-9ea2-821bf799db76.png)

**The left leg of the armors uses the same texture as the right leg** _[doesn't happen on custom models]_:
![Legs - 1](https://user-images.githubusercontent.com/71918599/110734388-7d633380-8206-11eb-9b3c-01ce326c0388.png)
> Should be like this:
> ![Legs - 2](https://user-images.githubusercontent.com/71918599/110734402-83f1ab00-8206-11eb-8177-5420465b0415.png)

**The bottom part of the armor's feet doesn't render** _[doesn't happen on custom models]_:
![Feet](https://user-images.githubusercontent.com/71918599/110734814-58bb8b80-8207-11eb-8bfa-3691839f5776.png)

Engineer's Goggles from [Create](https://www.curseforge.com/minecraft/mc-mods/create) Render too big:
![image](https://user-images.githubusercontent.com/71918599/110735198-0dee4380-8208-11eb-9d0f-cacc5c559c72.png)

### **Crash Report**
Game [crashes](https://gist.github.com/Allomere/05dd6fd6d9d5f7edef120ae1e923dcb5) when you equip a [Elytra](https://www.curseforge.com/minecraft/mc-mods/curious-elytra) on a [Curio](https://www.curseforge.com/minecraft/mc-mods/curios) item slot _[doesn't happen with other curio items]_

### **Question**
Do you pretend adding support for Curio Items like you did for custom armor models ?

### **Message**
Thank you for developing this amasing mod!
It enhances minecraft's combat better then any thing else available, its only down side _(imo)_ was that it used to not support custom armor models (wich was understandable) and now you even got around clearing that issue out, you are the man!
Keep the great work!

**Comment by Yesssssman** [comment]
The visual problem of the vanilla model will be fixed in a short time. Thanks for reporting.
