### ISSUE TITLE
[1.16.5] two bugs

### ISSUE THREAD

**Issue by SteamDoge9000** [Yesssssman/epicfightmod#690]
Bug 1: Laser pointer rendering issues when shaders are present

The issue for this is relatively simple, the line still renders, but it's not bright enough for it to be seen

Bug 2: Specials will not "refresh" when you die with weapon with a special when keepskills= true 

This issue is self explanatory for this issue only happens when you die with a weapon with a special skill (let say the katana) while keep skills is enabled 

When you select the weapon again, it's special charge indicator will not show, furthermore even when you believe it reaches the point where it can be used, it will not _execute_. From some testing I found that this issue resolved itself if you select a weapon while in this mode that you did not die within your hand; this seems to "update" the special system and from then the special for that weapon you died with in you selected hotbar slot will work again. However it was noted that if you die with this "secondary" weapon equipped and in hand it will too become affected and will no longer work in refreshing the system

I noticed this issue does not exist if you die and keepskills is set to false

**Comment by Yesssssman** [comment]
Bug 2 will be solved in next version while But 1 won't be fixed as it is blocked by the shader.

**Comment by SteamDoge9000** [comment]
thanks, but the thing is, it still renders, its just that it can only be seen at night

**Comment by SteamDoge9000** [comment]
![image](https://user-images.githubusercontent.com/38770780/140318106-b8d1bde5-c3b0-46c7-a3c0-78fda8e8fb11.png)

**Comment by SteamDoge9000** [comment]
I would like to confirm that this bug has been corrected, thanks
