### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by RJHG56** [Yesssssman/epicfightmod#696]
[crash-2021-10-27_19.43.07-client.txt](https://github.com/Yesssssman/epicfightmod/files/7430122/crash-2021-10-27_19.43.07-client.txt)

**Comment by Yesssssman** [comment]
Could you attach the new crash report?

**Comment by RJHG56** [comment]
[crash-2021-11-04_13.26.02-client.txt](https://github.com/Yesssssman/epicfightmod/files/7477771/crash-2021-11-04_13.26.02-client.txt)
sorryyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy, :c

**Comment by Yesssssman** [comment]
It crashed with Techgun. Could you share this report to author of mod?

**Comment by RJHG56** [comment]
okey let me do it :3
