### ISSUE TITLE
World Creation stuck at 0%

### ISSUE THREAD

**Issue by IMinedThat** [Yesssssman/epicfightmod#7]
I am on a Macbook Pro 2017 model and when i create a new world with just this mod installed it is stuck at 0%.

**Comment by Yesssssman** [comment]
Hi, can you attach a crash report just like other issues tap?

**Comment by IMinedThat** [comment]
> Hi, can you attach a crash report just like other issues tap?

Yes will do sorry i didnt reply earlier i cant play on weekdays, i dont think it is the right log but i think it is aswell, sorry latest log was way too big to upload

https://pastebin.com/2fit2NdH

**Comment by IMinedThat** [comment]
> Hi, can you attach a crash report just like other issues tap?

also not mod confliction cuz its the only mod in the modpack, do i need optifine?

**Comment by IMinedThat** [comment]
> Hi, can you attach a crash report just like other issues tap?

and 1.16.4 works just not 1.12.2
