### ISSUE TITLE
Katana weapon type bug

### ISSUE THREAD

**Issue by crafting-Aaron** [Yesssssman/epicfightmod#70]
When adding a weapon as a katana, the normal attack animation works properly but will have the special attack of the normal sword. I tried this with the Spartanweaponry katana and other people also seem to have this problem.

**Comment by Yesssssman** [comment]
That's what I intended. Since katanas from another mod don't have a sheath, I replaced it to a normal sword attack.

**Comment by monsterjj00** [comment]
> 
> 
> That's what I intended. Since katanas from another mod don't have a sheath, I replaced it to a normal sword attack.

Do you have any plans on updating it? I was planning on making a mod pack and having multiple katanas would be very nice. Thanks for your work on the mod as well, its truly great!
