### ISSUE TITLE
Enderman Crashing Game (i think?)

### ISSUE THREAD

**Issue by Caesar299** [Yesssssman/epicfightmod#709]
So, I don't understand code at all. But from my limited understanding of the hell hole that is the American English Language, I believe something having to do with the Epic Fight enderman is crashing my game. Please help, for this has been tripping me up for awhile now.
[crash-2021-10-30_08.19.40-server - Copy.txt](https://github.com/Yesssssman/epicfightmod/files/7446488/crash-2021-10-30_08.19.40-server.-.Copy.txt)

**Comment by Yesssssman** [comment]
Use the latest version.

**Comment by Caesar299** [comment]
So I just tested it both with and without mods and have figured out that it's probably compatibility with one of the other mods I had in my folder. Any suggestions for a quick way to find out which one?

**Comment by Yesssssman** [comment]
There's no clear way to find it but I suggest you a workaround. Remove the bigger one first because the probability of crash will increase as the mod size gets bigger.

**Comment by Caesar299** [comment]
So turns out it was the mod called Well Behaved Mobs. It does mess with endermen a little, but it doesn't really do more than decrease their player detection range and their movement speed while in attack mode. I don't really understand how either of these affect Epic Fight endermen, but I'm just happy it works now.
