### ISSUE TITLE
Can't hit anything/damage anything after pressing R

### ISSUE THREAD

**Issue by AdnanuReeves** [Yesssssman/epicfightmod#71]
https://gyazo.com/6cbe4583e2b05c2cd5b450ec3490e8ce

**Comment by Allomere** [comment]
That only happens with small animals (on my experience)
The hit box must be so low on the ground that the hitbox from the attack doesnt reach it

**Comment by AdnanuReeves** [comment]
It happens with all mobs/animals for me

**Comment by MisuNaviel** [comment]
@Yesssssman It doesn't happen in single player games. This can happen in multiplayer games, When I removed [Quark]mod, the problem was solved .
