### ISSUE TITLE
Using the skill Guard does not work on the server

### ISSUE THREAD

**Issue by SilverHatTrick** [Yesssssman/epicfightmod#716]
The Guard Skill works perfectly fine in Singleplayer, but does not work in Multiplayer. Also, is there by any chance any incompatibility issues with Offhand Combat?

**Comment by Yesssssman** [comment]
Guard works fine in the dedicated server when I tested. Could you attach more information?

**Comment by SilverHatTrick** [comment]
Essentially, you cannot block in the server, unless you're equipped with a shield, which is confusing because normally offhand equips don't even render with two handed weapons. Said lack of blocking w/out shield applies to all weapons in the server. Additionally, armor does not render while in combat mode (vanilla). 

![image](https://user-images.githubusercontent.com/59756411/139856345-de2d0652-4641-4eb3-a277-53c5e5770460.png)

**Comment by Yesssssman** [comment]
Version? the shield shouldn't visible when you hold a two-handed weapon. Also, are you using server API like Mohist?

**Comment by SilverHatTrick** [comment]
I am not using Mohist, just Forge. 

I am using EpicFightMod-1.16.5-5.1.6.jar, which should be the latest version on Curseforge. Again, it does appear to work in Singleplayer, but I'm having difficulty rendering armor and using the guard skill. 

I'd be happy to let you experience it yourself on the server modpack?

https://www.curseforge.com/minecraft/modpacks/rise-and-fall-kingdoms

**Comment by Yesssssman** [comment]
I've figured out that this issue is related to #711. Please test in the latest version and let me know how far the problem was solved.
