### ISSUE TITLE
Multiple Issues on multiplayer servers

### ISSUE THREAD

**Issue by TheKaratCake** [Yesssssman/epicfightmod#717]
Armor isn't showing up in multiplayer and weapon blocking has no animation unless for some reason you load a singleplayer world before joining the server, this happens with all armor, vanilla or modded and we are using no custom armor

**Comment by Yesssssman** [comment]
#711 

Refer to the comment I've posted.

**Comment by Yesssssman** [comment]
As I mentioned in the above link, Could you test then let me know how far the problem has been solved?
