### ISSUE TITLE
Epic Fight Mod seems to conflict with the Paraglider mod

### ISSUE THREAD

**Issue by RamiK12** [Yesssssman/epicfightmod#719]
I have been using your mod for quite some time now and I have noticed a constant issue every time I have both the Epic Fight Mod and the Paraglider up at the same time. It seems to be that the animations conflict with each other. So I was wondering if it was possible to address and fix this issue.

**Comment by megagnarxd** [comment]
+1

**Comment by megagnarxd** [comment]
found the fix. Go to config client > filter_animation = true
