### ISSUE TITLE
 java.lang.NullPointerException: Exception ticking world at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84) ~[epicfight:1.0] {re:classloading}

### ISSUE THREAD

**Issue by koderian** [Yesssssman/epicfightmod#72]
Crashing when making a new world and loading in. 
Crash report snippet:
`
java.lang.NullPointerException: Exception ticking world
	at maninhouse.epicfight.capabilities.entity.LivingData.initAttributes(LivingData.java:84) ~[epicfight:1.0] {re:classloading}`

Full crashreport:
[https://gist.github.com/koderian/8ffbb3607dbe292f7f71ef3075261b29](https://gist.github.com/koderian/8ffbb3607dbe292f7f71ef3075261b29
)

**Comment by koderian** [comment]
Running latest version of EPM on Forge 36.0.48

**Comment by minerman52** [comment]
yeah i had a pretty similar issue, because i had Optifine G6, which wasnt compatable, if you're using g6 upgrade to g7 (this is the 1.16.4 version of the mod btw) if you're not using optifine then idk man sorry.

**Comment by koderian** [comment]
I was using latest version of Optifine G7 iirc

**Comment by Yesssssman** [comment]
Is it crashes if you only use the Epic Fight without any other mods?

**Comment by koderian** [comment]
I didnt have this issue with 3.0.2

**Comment by koderian** [comment]
Heres the serverside crash report https://gist.github.com/koderian/f70e6e919c424d265a64e0090e05f93a

**Comment by Yesssssman** [comment]
This looks like a mod conflict. Idk what causes this, but I've never got this crash when I executed epicfight without any mods.
