### ISSUE TITLE
Question on all config options for Client

### ISSUE THREAD

**Issue by SilverHatTrick** [Yesssssman/epicfightmod#720]
[ingame]
	#Range: 0.0 ~ 1.0
	laser_pointer_color = 0.328125
	show_health_indicator = true
	#Range: 1 ~ 10
	long_press_count = 2
	enable_laser_pointer = true
	auto_preparation = false
	mining_autoswitch_items = []
	camera_auto_switch = false
	filter_animation = false
	off_gore = false
	show_target_indicator = true
	battle_autoswitch_items = []

~ ~ ~

Hello, I had a question regarding all the config options, and what exactly changes for the Client? 
What is autopreparation? 
Is gore the blood involved during combat?

If I had to guess, filtering animations disables Epic Fight animations outside of "combat mode"?

~ ~ ~

Also, how do I find the modid as well as its respective texture for mobs in order to add a series of custom animations/AI to them?

Lastly, is there a Discord available, or some form of documentation regarding Epic Fight Mod?

**Comment by Yesssssman** [comment]
In the mod options screen, you can see the tooltip for each options.

![image](https://user-images.githubusercontent.com/79469058/139923248-2967a026-366c-4c0a-baf9-5c108c57cc5f.png)

You can see the guideline of how you set custom entities in the video I've uploaded.

https://www.youtube.com/watch?v=vEs1SXiLDVI&t=2s

Note that there are restrictions when you set custom entities.
