### ISSUE TITLE
Incompatibility with Wings Mod and Mermaid Tail Mod

### ISSUE THREAD

**Issue by Reavez5** [Yesssssman/epicfightmod#721]
https://www.curseforge.com/minecraft/mc-mods/mermaid-tail-mod
https://www.curseforge.com/minecraft/mc-mods/wings
![image](https://user-images.githubusercontent.com/93596875/139860101-d2e6ddc5-ba38-4c5e-938d-3c20b9252c16.png)
![image](https://user-images.githubusercontent.com/93596875/139860212-08d1fde4-af69-468c-ab14-ca9b957fc321.png)
Сould you please fix incompatibility with this two mods? Wings looks broken cuz there is no correct animation for flying and character just walks in the air. Mermaid tail is broken too cuz legs are not hiden while in the water and so player can have both legs and mermaid tail.

**Comment by Aronforester** [comment]
Just use filter animation you can watch Kulitin that's what he does

**Comment by Reavez5** [comment]
> Just use filter animation you can watch Kulitin that's what he does

It cant be fixed this way cuz using his methode u get this situation: u have 2 options
1) battle more grounded
2) mining mode flying
but what if i need to mine somethig on the ground? I should turn on/off wings and battle more separately. This looks and feels bad. There is also too much incompartablities with mods like artifacts and relics. Especially with hands equipement as different gloves etc.

**Comment by n0itLT** [comment]
Is there any way to add or fix the creative mode fly animation, I believe you could add something like that to fix this. Once flying activates it works like creative mode flying. I just don't understand why Wings mod animation isn't overlapping the standard walking animation for EFM.

**Comment by LordGriefington** [comment]
I know that one, with filter animation true and mining mode you can fly normal. I like this wings behavior since the speed is adjusted it looks very cool, I like to fight phantoms with. just the first persion view should be adjusted. the camera is off. I work around by using auto camera sawitch. that way you can only do it on purpose. and I made a function that puts me in mining mode when activating the wings. (its just using the same key and exectutes a command). if I went into fight now it does third person as well. works great.
the mermaid is done.

**Comment by Yesssssman** [comment]
Fixed in 20.8.2. Enjoy it!

**Comment by richardsymeoncarey-art** [comment]
Hi Yesman, I was told this was fixed but it's not working for me on 1.20.1 forge. When usin epic fight mode both legs and mermod tail disapear. Any fixes?

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/ce443a1b-c164-4d3a-9594-d7ae24e6db43" />
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/27d073b1-6c8b-4c4b-8649-17e1a83719b6" />
