### ISSUE TITLE
Quark Emotes Compatibility

### ISSUE THREAD

**Issue by OfficialLahusa** [Yesssssman/epicfightmod#725]
The Quark mod provides the player with some emotes that animate the player model at the press of a button. When using the epic fights mod, those emotes no longer work, instead the epic fights animations override the emote animation. I don't know if this is a change epic fights needs to make or one of quark, however I would just wish both mods were compatible for the optimal medieval roleplaying experience.

**Comment by Yesssssman** [comment]
Set "fIlter animation : on"
