### ISSUE TITLE
Personality Mod Sitting Compatibility

### ISSUE THREAD

**Issue by OfficialLahusa** [Yesssssman/epicfightmod#726]
The Personality Mod adds the ability for the player to sit and crawl anywhere when holding down a key. The crawling mechanic uses vanilla's swimming animations and is therefore compatible with the epic fight mod animations, the sitting animation, which also uses vanilla's sitting pose, doesn't work when using your mod, instead the player just stands still while the camera shifts slightly down. Ideally, both animations should be supported.

**Comment by Yesssssman** [comment]
Set "fIlter animation : on"
