### ISSUE TITLE
[Enhancement] Add stances that change attack patterns.

### ISSUE THREAD

**Issue by Daderic** [Yesssssman/epicfightmod#727]
The idea is to add a new tab in the skills menu called "Stance". Within this tab would be abilities similar to passive skills that modify the way you attack with certain weapons.

For example, the Lichtenauer ability on long-swords puts the player into a specific position that modifies how they fight. Similarly, you might have a stance for daggers that makes you hold the knife upside-down (more like a karambit) which makes you do a different set of stab and slash animations. For a spear, you might hold the spear the same as normal, but do more spinning moves when it comes time to attack. Or maybe a katana stance with attacks that mimic the fighting style of kendo.

Stances could modify the damage you deal with certain attacks, the speed of the attacks, whether or not you are vulnerable to damage when attacking with a certain move, how many attacks you do, and whether or not some attacks consume stamina. Stances would allow players to choose their own style of attack with a specific weapon, potentially based on different scenarios.

(also random feature: make the hit-box on weapon attacks (when active/damaging) deflect/stop arrows)

**Comment by Aronforester** [comment]
Those are some pretty good ideas but check the ''labels'' on ''issues'' and go to future plans
