### ISSUE TITLE
Another bug

### ISSUE THREAD

**Issue by megagnarxd** [Yesssssman/epicfightmod#728]
Welp, shield animation bug. Note that i have filter animation to be on true.

![image](https://user-images.githubusercontent.com/92188308/140385132-fe2d4f82-6ef5-4710-ba21-b8b44b1dff85.png)

**Comment by megagnarxd** [comment]
only could replicate once.

**Comment by Yesssssman** [comment]
Version 1.17.1?

**Comment by megagnarxd** [comment]
1.16

**Comment by Yesssssman** [comment]
It's the latest version?

**Comment by megagnarxd** [comment]
Yes

**Comment by Yesssssman** [comment]
Could you give me more detail? In my environment, I didn't get any visual glitches with shield animations. Does this happen even when you install only EpicFight?
