### ISSUE TITLE
Patching other mods.

### ISSUE THREAD

**Issue by thedeerirty** [Yesssssman/epicfightmod#737]
So, my guess when it comes to thinks like Werewolf, that one vampirism addon, is it can't render the models properly because they aren't animated in the system as a player, right?

Would there be anyway for me to patch it, with not too much coding experiencing? Albeit blockbench + geckolib, I have more than enough modelling and animating experience to create the kinds of animations needed (I'm an artist on a mod atm)

Or is the coding to bind animations like that simply too complex for a simplton like me to understand quickly?

**Comment by Yesssssman** [comment]
Epic Fight uses Blender to animate the skeletal model. All model and animation data are saved in .dae format.

Also, even if you create animations for the mod, you will need to code it so that those animations play at the right time. This would be very difficult without the knowledge of Java.

**Comment by thedeerirty** [comment]
Ah, that makes sense; I'll have to pick up blender.

Tell me, any particular references I could use for your mod? Once I learn blender I should be able to create the animations smoothly, or I hope so at least.
I discovered that someone made a resource pack that changed some animations; would that be able to add animations to mobs that don't have them as well? 

Also, and this is just out of curiousity as I don't know Java, but how do you actually implement your animations? As far as I knew Java wasn't the best for that, which is why libraries like Geckolib and such exist. Did you essentially build your own sort of system within your mod akin to those kind of mods? If so, very cool i gotta say.

**Comment by Yesssssman** [comment]
Resource pack just can override the animations that already exist. If you want to add a new animation for the mob, you should add it by coding.

And there's an example code that implements importing blender animations to Java.

https://www.youtube.com/watch?v=f3Cr8Yx3GGA
https://www.youtube.com/watch?v=F-kcaonjHf8&t=690s
https://www.youtube.com/watch?v=cieheqt7eqc&t=288s
https://www.youtube.com/watch?v=z0jb1OBw45I&t=550s

I've tweaked the code a little as I needed, but the basic principle is not quite different. Take a look if you're interested.
