### ISSUE TITLE
Suggestion: Add a second phase to mobs: similar to Endermen + Ender Dragon Boss Fight

### ISSUE THREAD

**Issue by XanTheMann** [Yesssssman/epicfightmod#738]
Hi!
I was recently playing the new update and I just realized that Endermen are the only mobs that have a "second phase." When you get an Endermen to low health, it stops teleporting and just straight up charges you. It gave me an interesting idea for second phases for other mobs.

**Zombies**
There's a 20% chance that when you hit a zombie, it will get enraged and become a sprinter. Sprinting zombies can sprint just slightly under the player's sprint speed. They also attack slightly faster than normal zombies. Some zombies might spawn enraged. The % can be changed in the config.

**Skeletons**
There's a 20% chance that when a skeleton is at lower than three hearts, it becomes enraged and uses a melee attack; knocking the player back before quickly shooting three arrows. The enraged % can be changed in the config.

**Spiders**
There's a 20% chance that when a spider is lower than four hearts, it becomes enraged and retreats from the player, getting distance and shooting a web attack that temporarily snares the player. This web can be blocked or dodged. If the web connects the spider will run back to the player and deal a poison attack that lasts the same as a normal cave spider attack. Cave spiders deal an attack that gives the player a strong hunger effect instead. The % can be changed in the config.

**Vindicators**
Vindicators are capable of dodging and blocking melee attacks just like players.

**Ender Dragon FULL BOSS FIGHT: VERY HARD**

**Stage 1**
In this stage, The Ender Dragon is completely immune to damage until all the end crystals have been destroyed. The dragon flies around and shoots purple fireballs at a low frequency. Once all crystals are destroyed, the dragon will let out a loud roar and then stage 2 begins.

**Stage 2**
The Ender Dragon lets out a loud scream signifying that stage 2 has begun. 
The dragon flies around more aggressively and quickly, shooting purple fireballs and flying into players, dealing high damage and destroying anything that isn't the Portal, Bedrock End Stone or Obsidian. After a few attacks, the ender dragon will stop in the air above the portal, open it's mouth and start charging up a powerful purple laser attack from it's mouth. The charge up lasts 10 seconds, and a player either needs to hide behind an obsidian pillar, or shoot the dragon in the mouth with an arrow. If the dragon finishes charging the attack, it will shoot whichever player it's focusing on and deal 40 damage, most likely killing. If the dragon get's shot in the mouth during charge up, there will be an explosion and the dragon will fall onto the ground near the portal for 8 seconds for the players to deal melee damage; then quickly jumping back into the air and dealing high knockback to all players within a few blocks when the 8 seconds are up. Repeat the damage phase until the dragon's health gets to 30%, then stage 3 begins.

**Stage 3**
The dragon lets out another high pitched scream, signifying that stage 3 has begun. The dragon is now vulnerable to arrows to the head as well as melee attacks

The dragon lands on the ground, stomping around and following players at a little faster than walking speed; shooting purple fireballs and unleashing slow melee wing swipe attacks that can hit multiple players at once, dealing 15 damage with each wing attack. The recovery time after a wing attack is long enough for the player/s to land a few quick melee attacks. Once the dragon reaches 0% health, it faints near the portal. The portal is now glowing purple. Player/s have 10 seconds to hit the dragon into the portal with their melee weapons. The dragon will automatically go up blocks like a horse because if it couldn't this step would be impossible. When the dragon is close enough to the portal, it will absorb the dragon into the portal. As the portal absorbs the dragon, it creates an increasingly glowing ball of white light. Once the dragon is fully absorbed, the light explodes, leaving the screen nearly completely white for a split second. Experience explodes all around the portal for the player/s to collect, and the dragon egg is there as well. You beat the Ender Dragon. If the players fail to hit the dragon into the portal before the time runs out, the dragon will regain 10% of it's health and they'll have to redo the step until completion.

**Comment by Aronforester** [comment]
I like this but vindicators are pretty hard already without using iron equipment the enraged skeletons I don't really agree with but maybe if you said that they got pulled underground by other skeleton arms and then spat out ten block away from the player and it would be random with the skeleton getting out of harms way but still that's too much to implement I think ''so skeletons me no like''  but zombies and spiders those sound good also the dragon sounds good too
