### ISSUE TITLE
[Suggestion] Add client config to go F5 mode on activating combat mode and vice versa.

### ISSUE THREAD

**Issue by KamiSami** [Yesssssman/epicfightmod#74]
Title pretty much. This was a thing before the new updates, i find it bit inconvenient to go in battle mode then having to also toggle F5 mode every time. ^^;

**Comment by hitmanssilent** [comment]
I recommend you download a mod called "shoulder surfing" that adds an option in controls that allows you to go directly to a camera in 3rd person, configure the button of that mod with the combat mode button of this mod and when you press f5 both things will happen at the same time.
