### ISSUE TITLE
Game crash when type @ symbol in JEI searchbox

### ISSUE THREAD

**Issue by RisingInIris2017** [Yesssssman/epicfightmod#740]
### Forge Version
forge-1.16.5-36.2.9
### Epic Fight Mod Version
EpicFightMod-1.16.5-5.1.8
### Related Mods Version
Just Enough Items: jei-1.16.5-7.7.1.134
### Crash Report
https://paste.ubuntu.com/p/KTmZNmgjyQ/
### How to reproduce
1. Open the Inventory.
2. Type @ symbol in JEI's searchbox. It usually is at the bottom right corner of the game window.
3. Game crashes.

Thanks in advance for your help.
Looking forward to your reply.

**Comment by Yesssssman** [comment]
Use the latest version. 16.5.9.
