### ISSUE TITLE
java.lang.NoClassDefFoundError:[BUG]

### ISSUE THREAD

**Issue by Zombotron04** [Yesssssman/epicfightmod#742]
When i open minecraft with your mod the game says this thing in the loading error section. I'm on the latest version of the mod in 1.16.5

**Comment by Yesssssman** [comment]
It usually happens when Forge is not updated. Make sure the version listed in the changelog matches the version of Forge currently installed.

**Comment by Zombotron04** [comment]
Ok so i checked and i have the 36.1.0 version of forge (a really old version). The latest version is the 36.2.9 but the recommended one is 36.2.0 (that also is newer than mine). Should i download the latest (36.2.9) or the recommended (36.2.0)?

**Comment by Zombotron04** [comment]
ok i downloaded the recommended one and it worked. Thank you!
