### ISSUE TITLE
【BUG】Strange behavior while sleeping...

### ISSUE THREAD

**Issue by GalaxyZEROX** [Yesssssman/epicfightmod#743]
![2021-11-10_04 00 59](https://user-images.githubusercontent.com/73332842/140996829-119ec03a-f872-43a0-91a7-d64b271c1fd5.png)
When you sleep, you will sit down, and your right hand will wave constantly.

**Comment by GalaxyZEROX** [comment]
Version 1.16.5

**Comment by SaltOnigiri** [comment]
I am also having this issue! I tried removing every mod except epic fight and It is still doing it.....

**Comment by DrizzyBo1** [comment]
im having that issues as well as a issues with mobs gliching out on there death (many enemy mobs)

**Comment by Yesssssman** [comment]
Fixed in 1.18.2
