### ISSUE TITLE
[Suggestions] New combat features

### ISSUE THREAD

**Issue by EddyHz** [Yesssssman/epicfightmod#746]
Hey! Loving this mod!

I have a few suggestions though, and would appreciate your consideration of them.

Firstly, there is the (guard skill) Parry: As an enemy attacks, the player has a short window of time in which they can parry and stun the enemy, this costs stamina, but can also be followed up by...

The (passive skill) Riposte: While an enemy is stunned from a parry, the next attack could do more damage than normal

And finally, (passive skill) Guard Break: while an enemy is blocking, sprint-attacking could break their guard

Thanks for reading! Would love to hear about the possibility/probability of these being implemented!

**Comment by Aronforester** [comment]
check the label for future plans and tell this to others who keep spamming

**Comment by marcusurdaddy** [comment]
Eddy the issue with the guard break is that you cant see other peoples blocks in servers,  idk if yesman will every fix it....
