### ISSUE TITLE
Atum 2 3D Armor Compatability

### ISSUE THREAD

**Issue by TakoDile** [Yesssssman/epicfightmod#748]
This isn't really an issue, but I wanted to get Yesman's input on something and I didn't know a better way of contacting them. Im looking to modify the two god armor sets from the Atum 2 mod, so that they work with EFM. I'm aware of the pinned post on compatibility issues but I don't even know how to modify Atum 2's source code and then recompile it into a working mod. Should Yesman see this post, please note that I do NOT intend to redistribute the mod after making any changes to it, I'm looking to do this solely for my own personal gameplay. Any guidance would be greatly appreciated.

**Comment by Yesssssman** [comment]
How to add a mod as a library: https://www.cursemaven.com/

Download source code of Atum2: https://github.com/TeamMetallurgy/Atum2

I recommend you build your own Forge project. But I don't know about the license of Atum2 so it's better to ask him first.

**Comment by Aronforester** [comment]
Also you could watch Kulitin because he did a tutorial about it
