### ISSUE TITLE
[suggestion] Better shield intigration wtih other mods

### ISSUE THREAD

**Issue by SteamDoge9000** [Yesssssman/epicfightmod#749]
what I mean by add better shield intigration is to make it to where anything that can be considered a shield in some shape or form can be detected by the mod

the reason: ive noticed that some shields (Tetra and Immersive Engineerings Heavy Shield_ dont properly render the shield being used as it should when in combat mode

I expected them to be acting like the
![image](https://user-images.githubusercontent.com/38770780/141270945-b289a0dd-b555-418b-bcb1-bee7652b80ff.png)

 original one as in this shot 

but instead it acts more like this 
![image](https://user-images.githubusercontent.com/38770780/141270958-d0baadcb-30d1-4967-a57a-78ac2081ef79.png)
(using Tetra Shield while in Combat mode, it not rendering as such for some reason)

![image](https://user-images.githubusercontent.com/38770780/141271445-68f3a279-ae45-4eed-ae0a-91d94510ab2f.png)
(using the heavy shield from IE)

if you can fix this then that would be swell, I really like the work you put into this mod ^w^

**Comment by ColaLiao** [comment]
you can set it in mod config

**Comment by Yesssssman** [comment]
Tetra uses NBT value to define the type of item. So without the special config, the blocking animation won't be played. There is an  
addon that makes it possible.

https://www.curseforge.com/minecraft/mc-mods/epic-fight-nbt-integration

**Comment by SteamDoge9000** [comment]
I have that mod present in that shot. I guess they need to fix that. is their any info that can help in impimenting it?

**Comment by SteamDoge9000** [comment]
ok I intigrated it into the custom config option, only problem

![image](https://user-images.githubusercontent.com/38770780/141936703-3883cff0-ec2a-4c46-81f9-f1aa07ff773f.png)

it dosent disable the slight shield bend offset when used (the old bend thing)

is this something to fix on your end or another?
