### ISSUE TITLE
5.1.0+ World Load Error

### ISSUE THREAD

**Issue by BwastWoff** [Yesssssman/epicfightmod#751]
(Repost btw i accidentally deleted it) Whenever i use 5.1.0+ versions of the mod,worlds won't load.
I've searched for a solution but there was nothing about this.
![world error](https://user-images.githubusercontent.com/94068822/141317231-6f597601-4890-4bc4-baa2-04212b78a516.png)
Game says that the problem is about datapacks but i don't even have datapacks.

**Comment by Aronforester** [comment]
no the mod are considered data packs

**Comment by BwastWoff** [comment]
> no the mod are considered data packs

then whats wrong with the mod? (it still happens when i only use efm)

**Comment by Aronforester** [comment]
Also the not being able to enter the world might be a some sort of problem with minecraft trying to read the mod so get a higher version of the mod and make a new world but if you backed up the world then use the back up

**Comment by BwastWoff** [comment]
> Also the not being able to enter the world might be a some sort of problem with minecraft trying to read the mod so get a higher version of the mod and make a new world but if you backed up the world then use the back up

well the problem is im already trying to use it with a new world and i tried all the verions of the mod

**Comment by Aronforester** [comment]
Alright try deleting other mods and leave epic fight on then add one mod after you start up minecraft load a world then you work from there and if that doesn't work Then try making a new modpack and download only epic fight and slowly add a mod after starting up minecraft to see if it works. :)

Sorry if this is confusing

**Comment by BwastWoff** [comment]
> Alright try deleting other mods and leave epic fight on then add one mod after you start up minecraft load a world then you work from there and if that doesn't work Then try making a new modpack and download only epic fight and slowly add a mod after starting up minecraft to see if it works. :)
> 
> Sorry if this is confusing

i forgot to tell you it still happens even if i use only epic fight mod

**Comment by Yesssssman** [comment]
Check if there's a message from Minecraft in debug.log file after your game crashed. It's in /.minecraft/logs/ folder.

**Comment by Aronforester** [comment]
hey yesssssman could u give an idea of when the next update is coming out pllllzzzzz

**Comment by Yesssssman** [comment]
@Aronforester Working on the Ender dragon animation but not sure how long it would take. Because I'm quite busy with tasks irl.

**Comment by Aronforester** [comment]
I understand but you could give me like a time frame like the month

**Comment by BwastWoff** [comment]
> Check if there's a message from Minecraft in debug.log file after your game crashed. It's in /.minecraft/logs/ folder.

there is one,do you want me to send a photo of it?

**Comment by Aronforester** [comment]
Yeah he'll see it sometime soon

**Comment by BwastWoff** [comment]
![world crash1](https://user-images.githubusercontent.com/94068822/141346871-8deb6a6f-9992-4453-a39a-f67714ae0921.png)
![world crash2](https://user-images.githubusercontent.com/94068822/141346879-c7c625ec-aa4e-4a33-a2d5-5b8f4aa7577d.png)
![world crash3](https://user-images.githubusercontent.com/94068822/141346884-4cbc0553-c041-4a4c-9ee9-d5346f2c9af9.png)
![world crash4](https://user-images.githubusercontent.com/94068822/141346893-191bb9f9-02e8-4560-bb07-3884639bf964.png)

![world crash5](https://user-images.githubusercontent.com/94068822/141346902-0e768c06-185e-46f8-b886-7a4dd882e268.png)

**Comment by Yesssssman** [comment]
You can just put this file like:
[latest.log](https://github.com/Yesssssman/epicfightmod/files/7523938/latest.log)

Anyway, Have you downgraded Epic Fight version? I guess the junk datapack files remain in your world.

**Comment by Yesssssman** [comment]
@Aronforester Everything is uncertain so I can't give you a specific date.

**Comment by BwastWoff** [comment]
> You can just put that file like:
> 
> [text.txt](https://github.com/Yesssssman/epicfightmod/files/7523947/text.txt)
> 
> Anyway, Have you downgraded Epic Fight version? I guess the junk datapack files remain in your world.

I don't think you get it.The problem isn't about just a world it happens even if i create a new world and wdym by downgraded the version?

**Comment by Yesssssman** [comment]
Which Epic Fight version are you using now? And could you check the data pack setting screen in creating a world?

![image](https://user-images.githubusercontent.com/79469058/141512599-6c57320a-6b88-4135-9075-be5191a5cde5.png)

**Comment by BwastWoff** [comment]
The version im using and data pack setting selected are same (5.1.8)

**Comment by Yesssssman** [comment]
Does this still happen in the latest version? and can I get the full log file?

**Comment by BwastWoff** [comment]
If you mean 17.0.1 by latest verison yes it does and here is the log
[text.txt](https://github.com/Yesssssman/epicfightmod/files/7530072/text.txt)

**Comment by Yesssssman** [comment]
I found that your computer parses "LIECHTENAUER" to "LİECHTENAUER". I'll fix this in next update.

**Comment by BwastWoff** [comment]
> I found that your computer parses "LIECHTENAUER" to "LİECHTENAUER". I'll fix this in next update.

ok,thanks for helping

**Comment by Yesssssman** [comment]
https://drive.google.com/file/d/17pTHgb4eKkOHuvji831QjFU2DSjNAJO8/view?usp=sharing

@BwastWoff Please test this version works normally on your desktop.

**Comment by BwastWoff** [comment]
> https://drive.google.com/file/d/17pTHgb4eKkOHuvji831QjFU2DSjNAJO8/view?usp=sharing
> 
> @BwastWoff Please test this version works normally on your desktop.
it works

**Comment by Yesssssman** [comment]
Ok, thank you for your reply. It'll be uploaded both 1.16.5 and 1.17.1.
