### ISSUE TITLE
[FEATURE] Increased compat so other mods can view DefinedWeaponTypes.TYPES

### ISSUE THREAD

**Issue by pitbox46** [Yesssssman/epicfightmod#752]
I would have made a pull request, but it seems like the code hasn't been pushed for 1.17 yet. 

I am the dev of Epic Fight NBT Integration, so I am asking for slightly more compat for the 1.17 version. Currently DefinedWeaponTypes.TYPES is private. I would appreciate if either the constant were public or perhaps if there was a method that returned an immutable copy of TYPES. 
If you add weapons in the future, currently I have to manually add each one so my mod can use it. If I could access TYPES however, this process would be automatic for me.

**Comment by Yesssssman** [comment]
Is DefinedWeaponTypes#get method can't solve this problem?

**Comment by pitbox46** [comment]
It doesn't solve the issue since it requires the string to begin with.

**Comment by Yesssssman** [comment]
I see. Can this kind of method solve your problem?

>	public static Collection<Function<Item, CapabilityItem>> getAllTypes() {
>            return TYPES.values();
>	}

**Comment by pitbox46** [comment]
Something like this would be best since I would also need access to the keys. 
```java
public static ImmutableMap<String, Function<Item, CapabilityItem>> getTypes() {
    return ImmutableMap.copyOf(TYPES);
}
```

**Comment by Yesssssman** [comment]
Ok, I'll add this method in the next 1.17.1.

**Comment by pitbox46** [comment]
Thanks!
