### ISSUE TITLE
how would i go about making a glove-like item that is compatible with epic fight?

### ISSUE THREAD

**Issue by ScavengingSquid** [Yesssssman/epicfightmod#755]
So basically I want to make a fighting glove to give more uses to the knuckles class but whenever I make the model in blockbench is place is just right to fit the hand, but when I load in the game with epic fight, it's all misplaced.

**Comment by Reshirou** [comment]
have you tried starting with the knuckles model itself and editing that as a base? just take the knuckles model out of the .jar, import it to blockbench, delete the texture and go from there

**Comment by ScavengingSquid** [comment]
hmm, ill try that tnx
