### ISSUE TITLE
[1.16.5] Skill system bug; setting skill in the menu while holding an item will delete it

### ISSUE THREAD

**Issue by SteamDoge9000** [Yesssssman/epicfightmod#757]
if your using keepskils and are alternating between different skils then when you do switch via the menu, any item that is in your main hand will be cleared upon switching it, I think that this was a possable oversight to the book removal system and it doing the same for any held item when a skill gets changed

this can result into issue, such as my good tetra pickaxe being erased from existence for no reason when swiching between Step to Roll

this issue can be reproduced easaly and is simply done by changing your set skills in the skill menu while holding any item in your main hand

can you please fix this, I am going to a backup to get my poor pick back

**Comment by Yesssssman** [comment]
Fixed in next both 1.16.5 and 1.17.1
