### ISSUE TITLE
error java.lang.bootstrapmethoderror: java.lang.noclassdeffounderror:

### ISSUE THREAD

**Issue by YoshiKuroshi** [Yesssssman/epicfightmod#76]
![image](https://user-images.githubusercontent.com/80627876/111068322-4e4d0a80-8503-11eb-905d-74aaf82a7f61.png)

**Comment by Yesssssman** [comment]
Which forge version are you using now? I recommend to use the latest.

**Comment by ezey20** [comment]
> 
> 
> Which forge version are you using now? I recommend to use the latest.

im using the latest version myself but i cant find the issue
