### ISSUE TITLE
Possible issue with Lichtenauer skill.

### ISSUE THREAD

**Issue by Daderic** [Yesssssman/epicfightmod#765]
I'm not sure if this is intentional, but currently the Lichtenauer skill still activates while you are blocking. If you have the Lichtenauer skill active, and you choose to block an attack on your own (by pressing the block keybind), it will still use a charge from the Lichtenauer skill, and also penalize my stamina for that blocked attack.

If this isn't intentional, I feel it should either:
a) Only use the Lichtenauer skill to block the attack, or
b) Use the player's block skill, ignoring Lichtenauer for that attack

**Comment by Yesssssman** [comment]
Will be fixed to plan b.
