### ISSUE TITLE
[Suggestion] Add the possibility to hit up and down 

### ISSUE THREAD

**Issue by hitmanssilent** [Yesssssman/epicfightmod#77]
Could you add the possibility of being able to hit up and down? is a bit difficult to fight with this mod when we fight with small enemies (such as baby zombies or silverfish) and it is directly impossible to fight against the ender dragon with the fight mode activated, is much more notable especially when you fight with a shield and spear because when looking up the character only hits in front of him so he does not hit up or down when you look in those directions .

**Comment by Yesssssman** [comment]
Ok, I'll add it after a few experiments.

**Comment by hitmanssilent** [comment]
Thank you, really, thank you, I like the style of combat with the great sword, but I had so many problems with small enemies that I have chose to use only two-handed spear when i fight against small enemies, creepers or zombie hordes and relegate the great sword only when it comes a fight against archers. 

I will wait impatiently for that update, again, thanks 😃

**Comment by hitmanssilent** [comment]
Thanks bro, I really appreciate it.
