### ISSUE TITLE
Skin Rotation Glitch [1.16.5]

### ISSUE THREAD

**Issue by BiggiestBoy** [Yesssssman/epicfightmod#770]
The shoulder on the skin rotates whenever I use this mod (EpicFightMod-16.5.10)

![image](https://user-images.githubusercontent.com/41413575/141710613-a8fb64e3-aaf4-4502-89ae-9e6b1b09e68b.png)

**Comment by BiggiestBoy** [comment]
![image](https://user-images.githubusercontent.com/41413575/141710659-cd1abc4c-9297-4dd0-95e4-f44f5736123d.png)

**Comment by Yesssssman** [comment]
Fixed in 18.1.15
