### ISSUE TITLE
dodge is broken

### ISSUE THREAD

**Issue by MiyazakiTakumi11** [Yesssssman/epicfightmod#773]
dodge in EpicFightMod-17.0.3 is literally broken, i've try binding different key, it wont do anything
im using ForgeOptifine 1.17.1 Tlaunder btw

edit: dodge in EpicFightMod-17.0.4 is also broken

**Comment by Yesssssman** [comment]
Have you learned the skill?

**Comment by MiyazakiTakumi11** [comment]
> Have you learned the skill?

wait you have to learn it???
and how??

**Comment by MiyazakiTakumi11** [comment]
also is there any way to earn all skills in creative?
it's kinda confusing since i can't find any tutorial/guidebook or something like that

**Comment by Yesssssman** [comment]
https://www.youtube.com/watch?v=xO58-4RPhdw&t=60s

**Comment by Yesssssman** [comment]
![image](https://user-images.githubusercontent.com/79469058/141840145-6206f8a7-1061-4b33-a62b-65fde4e945f6.png)

Skillbooks in the creative tab.

**Comment by MiyazakiTakumi11** [comment]
> https://www.youtube.com/watch?v=xO58-4RPhdw&t=60s

ohhhhhh
thanks mate
