### ISSUE TITLE
Dual daggers skill almost useless- possible tweak?

### ISSUE THREAD

**Issue by Himynameissomeone** [Yesssssman/epicfightmod#775]
The dual daggers' skill is one of the worst of all the weapons right now and it would be nice to see a change. Other than its fancy graphics, its use is almost pathetic compared to the basic attack of dual daggers. 
Currently, it consists of 3 strikes with normal attacks and a last attack with 250% of normal attack. This archetype is obsolete/problematic for several reasons:

1.  It does too low damage: The first strikes are just equivalent to a normal melee attack. However, it's even worse than the basic melee because 1) it's slower and doesn't "combo" 2) it only hits 1 enemy at a time, while melee can hit several in the same time because of high attack speed. Furthermore, 3) it's easy to miss the dashes so aiming is required. Essentially the only benefit of using the first strike is because of the small dash. However, even that's done by the standard dash attack. Ultimately, I end up just avoiding the skill because straight up meleeing is stronger. In addition, it's impossible to spam click like melee because it will end up missing most hits.
2. It's impossible to properly "aim" the last strike: now the only remainding benefit is the 250% last strike. However, it's near impossible to reliably intentionally use this. 1) it only hits 1 enemy so having just one chicken or mini slime in the middle will dillute damage. 2) there is no indicator of when the last strike is used on gui- you have to count the 4th strike manually. Especially with the adding stack effect, it ends up just spamming the first skill until the last strike hopefully comes out.
3. It takes too long to charge: For such an inefficiency, the skill takes too long to charge. For something worse than the basic melee attacks, it is the longest skill to charge. Of course, some may bring up the "adding stacks with a kill" function. However, because the damage is so low (9dmg per strikes with max netherite), it barely adds 1-2 stacks against vanilla skeletons/zombies/creepers. The only justified use is against say slimes which max netherite can finish.
4. "adding stacks on kill" is gimmicky and does not provide value. Adding stacks is actually worse- it forces the user to use more of the slow, aim-needed normal strikes, sacrificing standard melee. With the skill being unreliable with actually killing things, it ends up just adding 1-2 stacks of normal strikes, which again are worse than melee. Then it's charging for a long time until 4 stacks to repeat this....

Ultimately, the dual dagger skill becomes a horribily inefficient skill that pales to even basic melee attacks. It's hard to aim; does lower dps than melee; hard to utilize in a meaningful way. Especially against stronger mobs/bosses/mobs from other mods, the skill is essentially useless. Credits to @Daedric's suggestion, there may be an easy fix:

Make it so that the skill can "lock" onto a target or redirect the camera to face towards whatever the player just hit. This will make aiming so much easier, allowing users to click faster, therefore not sacrificing dps. In addition, it would be great to make the skill unsuable until all 4 stacks are charged. This would decrease the chance of accidentally using a strike before all 4 stacks, wasting the skill before using the last strong attack. The "adding stacks on kill" passive will synergize especially well, decreasing the cooldown of the skill by adding stacks for a kill without the aforementioned flaws of accidentally using the skill.

**Comment by Daderic** [comment]
To add to this, potentially redirect the camera to face towards whatever you just hit, or where you just came from, to make chaining the attack viable.

**Comment by Himynameissomeone** [comment]
@Daderic Sounds like the solution to me. The purpose of the skill (probably to chain attacks) is not possible right now and it's really hard to aim. In addition to your idea, I think it would be best to lock the skill until all 4 stacks are charged. This way, it would be so much easier to control the skill without accidently using it in the middle and losing the last strong attack. Then, "adding stacks on kill" passive will help with charging the long cooldown skill without creating useless stacks that accidentally set up. 

I'll edit my suggestion accordingly.

**Comment by Yesssssman** [comment]
I originally planned the "Interaction animation" between attacker and target for both two dagger skills but due to the lack of my programming skill, it has poor ability as you mentioned. Epic Fight development is not ended, so I'll refresh the skills on a big scale someday.

**Comment by Himynameissomeone** [comment]
I mean I don't want a big scale change- the current animations are really nice. It's just mechanics would be so much easier if somehow 1) the skill locked unto a target or kept its camera to face where I originally was. 2) Make the skill usable only at full 4 stacks. The extra stacks on kill can help reduce the cooldown rather than being hard to use. These to changes would be fix most problems. 

Again, your mod is awesome, and the animations for dual daggers is fantastic. Few tweaks would be more than enough. Thx for making the mod!
