### ISSUE TITLE
Lichtenauer UI bug

### ISSUE THREAD

**Issue by Daderic** [Yesssssman/epicfightmod#777]
After dying when using the Lichtenauer skill on an item that has sweeping edge (which grants Lichtenauer more charges), the visual cap seems to stay at 4 charges. Dying again does not fix this issue. Watch how it goes from its normal 7 charges on a sweeping edge 3 sword, then stays at 4 afterwards: [The video was too big to put on github; had to upload to Youtube](https://youtu.be/0xHBRzpm5uE)

**Comment by Yesssssman** [comment]
It will be fixed in the next update.
