### ISSUE TITLE
[Forge 1.17.1 - v17.0.3] epicfight.toml gets wiped every time the game initializes the mod

### ISSUE THREAD

**Issue by r4ven1245** [Yesssssman/epicfightmod#778]
Using version 17.0.3 on Forge 1.17.1-37.0.82
I'm having the same issue as described in #659, however it couldn't be fixed the way that one was. As everything is already prefixed correctly.
No matter what I write in the config, it gets wiped completely.

Config:

    [custom_entity]

        [custom_entity.dungeonsmod_guard]
            type_name = "dungeonsmod:guard"
            impact = 0.5
            max_strikes = 1
            armor_negation = 0.0
            #Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
            ai_type = "VINDICATOR"
            texture_location = "dungeonsmod:assets/dungeonsmod/textures/entity/guard.png"
            

And the logs say:

`...epicfight.toml is not correct. Correcting`
`...Incorrect key custom_entity was corrected from SimpleCommentedConfig:{dungeonsmod_guard=SimpleCommentedConfig:{type_name=dungeonsmod:guard, impact=0.5, max_strikes=1, armor_negation=0.0, ai_type=VINDICATOR, texture_location=dungeonsmod:assets/dungeonsmod/textures/entity/guard.png}} to its default, null.`

**Comment by Yesssssman** [comment]
17 version doesn't support config file system because it's too buggy and inefficient. I'll post how to use datapack to replace the config file.

**Comment by r4ven1245** [comment]
Is it possible to config other things or just the weapons, armor and entities?
Like initial skills for example, I'd want the active guard skill to be always enabled

**Comment by Yesssssman** [comment]
Well, If you set the "keepSkills" game rule to true, your won't lose your skills after you die, but there's no way to learn a particular skill in initial.

**Comment by Yesssssman** [comment]
In 1.17.1, Datapack replaces what config files have done. I'm testing NBT separative functions and I'll post a description of how to set them.

**Comment by r4ven1245** [comment]
> Well, If you set the "keepSkills" game rule to true, your won't lose your skills after you die, but there's no way to learn a particular skill in initial.

keepSkills doesn't work btw, I've tested it.
At least not for `online-mode=false`

**Comment by Yesssssman** [comment]
1.17.1?

**Comment by r4ven1245** [comment]
Yes, the version stated in the description
I'm running a server

**Comment by Yesssssman** [comment]
Solved in 17.0.5.

**Comment by DistantDig** [comment]
I'm having this exact issue in 17.0.6. If configs are still disabled, could I get a link to the datapack option?
