### ISSUE TITLE
`deferredProviders` cause huge memory usage

### ISSUE THREAD

**Issue by Wireless4024** [Yesssssman/epicfightmod#780]
[heap dump](https://imgur.com/a/jR84bUy) 
when joining world I have to allocate memory to game more than version 1.16.5-5.1.6 over 2.5GiB.

that list seem referenced a lot of object after downgrade memory usage when joining world reduced from 4.8GiB (full gc) to 2.5GiB (full gc)

**Comment by Yesssssman** [comment]
Sorry, It will be fixed in the next update.

**Comment by Yesssssman** [comment]
A question, Were you using multiplay? (either Dedicated or LAN)

**Comment by Wireless4024** [comment]
> A question, Were you using multiplay? (either dedicated or LAN)

dedicated server

**Comment by Yesssssman** [comment]
Are you using another API server like Mohist or Magma? I've tested several times, but it doesn't happen in my environment. I need more information about yours.

**Comment by Wireless4024** [comment]
can you please add my discord Wireless#4024
