### ISSUE TITLE
I found a mod similar to your mod, including animation.

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#782]
Hey! Brother, I found that a mod now has a combat system similar to your mod after the update! And the action and the health bar are the same. I would like to ask, are you clear about this?
https://www.curseforge.com/minecraft/mc-mods/minecraft-dark-souls

**Comment by Yesssssman** [comment]
I haven't heard anything from him, but the usage of code is free if he wrote the original copy.
Anyway, thanks for notifying me.

**Comment by wushen233** [comment]
> 我没有听到他的任何消息，但如果他写了原件，代码的使用是免费的。 无论如何，谢谢你通知我。

I just looked at the mod, and I feel that the code should be the code of the version before 5.0.0, and many mechanisms are before this.

**Comment by wushen233** [comment]
> 我没有他的任何消息，但如果他写了原件，代码的使用是免费的。 三周，谢谢你通知我。

So, his mod is actually themed by Dark Souls, and now he uses your code as the combat part, what are your plans? Is the fighting style still the soul of darkness? My idea is if you make some values that can be changed by the player, so that everyone can adjust some details according to their needs. It can be a hard-core battle like the Soul of Darkness, or it can be similar to Searle. Up to the kind of faster-paced battle.

**Comment by wushen233** [comment]
> 我没有他的任何消息，但如果他写了原件，代码的使用是免费的。 三周，谢谢你通知我。

In this way, your mod becomes a mod of the battle system framework, and players can freely match other mods to achieve different gameplay.

**Comment by Yesssssman** [comment]
I'm planning to make a library mod to provide the developers who are interested in developing the mod that has fighting styles like Epic Fight. So I'm working on optimizing model and animation files and adding various events so that Epic Fight can be used as an API.

**Comment by wushen233** [comment]
> 我计划制作一个图书馆模组，以提供有兴趣开发具有 Epic Fight 等战斗风格的模组的开发人员。所以我正在优化模型和动画文件并添加各种事件，以便 Epic Fight 可以用作 API。

For the moment, I think the player part has a good experience. But for the monster part, the original monster is actually a bit monotonous for now. So will there be plans to develop a framework that can customize creatures in the future? For example, other people can use this framework to model and animate themselves and then use the api to implement it in the game. So everyone can design some very interesting bosses

**Comment by Yesssssman** [comment]
Yes, that's what the library mod will work. Like people use Geckolib and Citadel to make more fine animations.

**Comment by wushen233** [comment]
> 是的，这就是图书馆模组的作用。就像人们在使用壁虎和城堡来制作更精美的动画一样。

The main reason is that Geckolib can use Blockbench, a model-making software dedicated to minecraft, to make creatures and animations. After all, many people use it, including the Bukkit and Spigot plug-ins. There is a model engine that also uses the format of this software.

**Comment by Yesssssman** [comment]
First, I didn't know the existence of Geckolib when I start developing. It's kinda hilarious.

Second, Geckolib couldn't express the bending part of the model. It's limited to transforming square models. I'm so affected by many cinematic Minecraft videos (e.g. Black Plasma Stuiod and NinjaCharlieT) so I dreamed of a mod that has more fancy animations.

I don't know I'm doing well, but after I make library mod, Maybe many skilled developers can create more cinematic mobs and bosses. I'm just building a bridge to them. :)

**Comment by wushen233** [comment]
> 首先，我在开始开发时并不知道 Geckolib 的存在。有点搞笑啊
> 
> 其次，Geckolib 无法表达模型的弯曲部分。它仅限于转换方形模型。我深受许多电影 Minecraft 视频（例如 Black Plasma Stuiod 和 NinjaCharlieT）的影响，所以我梦想有一个具有更多花哨动画的 mod。
> 
> 我不知道我做得好不好，但是在我制作了库 mod 之后，也许许多熟练的开发人员可以创建更多的电影小怪和 Boss。我只是给他们垫脚石。:)

Hahaha, this is embarrassing, but what you said is true. Geckolib actually uses the official bedrock model of mojng. It does not have any bending parts compared to the model you use. However, the model used by Geckolib should be a little lower in entry, but each has its own advantages. After that, have you considered compatibility with the bedrock model used by Geckolib? After you finish making the frame

**Comment by wushen233** [comment]
> 首先，我在开始开发时并不知道 Geckolib 的存在。有点资源啊
> 
> 即将，Glib 表达模型的弯曲部分。它无法抵达所以转换模型。
> 
> 我不知道我成功了好不好，但是在我制作了库模型之后，可能会很多次开发人员可以创建更多的电影小怪和老板。我只是给垫脚石。:)

But as you said, your animation is made in the same way as a movie, which is indeed a new direction. Just wait for you to build the platform for everyone, just before I had the idea to learn the model and animation production you use. I hope to make some different creatures by then

**Comment by Yesssssman** [comment]
Since the animating tool is totally different (Blender and Blockbench), I think it's hard to make these ones compatible. Anyway, please look forward to the progression!
