### ISSUE TITLE
After switching to the third person, the frame rate becomes lower. The original version does not have this problem

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#783]
![image](https://user-images.githubusercontent.com/46721555/142273210-75f650be-18a3-4fb6-8064-17a69a3be401.png)
![image](https://user-images.githubusercontent.com/46721555/142273250-05a00b0f-c869-4e22-8244-b33dc1f28f0e.png)

**Comment by fkyah3** [comment]
因为人物的模型变了 还加了动画渲染
