### ISSUE TITLE
vanilla "full charge" conditions causes incompatibility with other mods

### ISSUE THREAD

**Issue by Himynameissomeone** [Yesssssman/epicfightmod#784]
I'm not sure how the Epic Fight Mod deals with the original vanilla attack charge meter, but there are several compatibility issues. Any enchant/effect from a mod that requires a "fully charged" attack meter will not proc when using the fight mode. Would there be a way to solve this?
What I'm thinking is something like getting the mod to consider every "attack" as a fully charged vanilla attack, but I'm not sure how that would work. Would be great if this could get fixed

**Comment by Yesssssman** [comment]
I don't know what's a fully charged attack. But if this is a mod incompatibility issue, I think it's hard to be fixed.
