### ISSUE TITLE
Game crashes when rendering an armored skeleton with Pupil mod installed

### ISSUE THREAD

**Issue by RisingInIris2017** [Yesssssman/epicfightmod#786]
### Minecraft Version
1.16.5
### Forge Version
1.16.5-36.2.9
### Epic Fight Mod Version
EpicFightMod-16.5.9
### Related Mod & Version
pupil-0.1-pt
### Crash Report
https://paste.ubuntu.com/p/bnPBc7S9z6/
### How to reproduce
1. Summon a skeleton with EpicFight mod's armor.
2. Turn on the shaders of Pupil.
3. Game crashes.
4. Remove Pupil mod, then restart the game and enter the same world.
5. Game will not crash.

I think this is a compatability issue, so I will post the same issue to Pupil's issue tracker.
https://github.com/Someone-Else-Was-Taken/Periodic-Table-Reforged/issues/113

Thanks in advance for your help!
Looking forward to your reply.

**Comment by Yesssssman** [comment]
Crash report?

**Comment by RisingInIris2017** [comment]
> Crash report?

Sorry for forgetting upload that. I have added the [pastebin link](https://paste.ubuntu.com/p/bnPBc7S9z6/) of the crash report to the issue.

**Comment by Yesssssman** [comment]
Where can I get the mod file?

**Comment by RisingInIris2017** [comment]
Sorry for my late reply.
You may get the exact version of Magnesium and Pupil in my test environment via these two links https://drive.google.com/file/d/1xz0e6hF17GF46lPYk-Z5o_9HwMchCaw2/view?usp=sharing
https://drive.google.com/file/d/1mWXVDr9vG89xejgInrtahRYNwAYJrJEt/view?usp=sharing
