### ISSUE TITLE
EFA Resource Pack Katana Animation

### ISSUE THREAD

**Issue by BwastWoff** [Yesssssman/epicfightmod#788]
The katana animation from EFA resource pack won't work
![animation erorr](https://user-images.githubusercontent.com/94068822/142480710-b21a6b83-5c90-4e4c-91f8-2132b435f8ac.png)
![animation error2](https://user-images.githubusercontent.com/94068822/142480736-3758b2e0-6b19-4658-a673-d1f295709acb.png)
![animation error3](https://user-images.githubusercontent.com/94068822/142480759-90010b89-c59f-45f2-b8e4-7681fc998d27.png)

**Comment by Yesssssman** [comment]
Version?

**Comment by BwastWoff** [comment]
> Version?

the new 1.16 version you uploaded

**Comment by Yesssssman** [comment]
What about resourcepack version?

**Comment by BwastWoff** [comment]
> What about resourcepack version?

1.3

**Comment by Yesssssman** [comment]
Seems like the 1.3 has no override animation for katana. Wait for the update.

**Comment by BwastWoff** [comment]
> Seems like the 1.3 has no override animation for katana. Wait for the update.

Wdym  its the max verison of the resource pack

**Comment by BwastWoff** [comment]
> The maker of this resource pack removed katana animation in the latest version. I don't know why. Maybe he's making new animations.

okie
