### ISSUE TITLE
[Enhancement] I found that the Dark Souls mod using your code implements some functions that epic fight should have. So I gave some suggestions, please check

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#790]
I just saw that the Dark Souls mod using your code was updated, and then I took a closer look at his mod, and I found that he also added an animation to the player’s food, including an animation of drinking water. This feature was previously I just want to give you advice, but I have been running out of time. I didn’t expect the Dark Souls mod next door to be installed. Then there is the third-person issue. In fact, epic fight can be used with the better third-person 360 rotation camera function. Realize most of the rpg games, including the camera function of dark souls. But I tested it before, and his mod can’t recognize epic fight’s dodge skills well. The dodge direction is based on the direction of the game character, but the better third person is that the camera and the player’s direction are separated. It stands to reason that I would hold down the s button when I was chased by a monster. The character of the game will move towards you in front of the screen, but your camera can look at the back of the character. At this time, if you press Under dodge, the character in the game should dodge forward based on the camera, but it was not when I tested it before. He will dodge based on the game character, which will cause you to dodge backwards. Thereby walking towards the monster. But I watched the Dark Souls mod, he is compatible with this problem, and he has built-in better third-person functions in it. I think, can you solve this problem here? Or you can find the author of Dark Souls to see how to achieve it

**Comment by Yesssssman** [comment]
Applied in the 1.18.2

**Comment by wushen233** [comment]
> 应用在 1.18.2

What feature is applied in 1.18.2?

**Comment by MetalKnight56** [comment]
"The dodge direction is based on the direction of the game character"

**Comment by MetalKnight56** [comment]
other features will be re thinked and maybe added in future versions, i'll update this report once another feature from it is applied

**Comment by wushen233** [comment]
> other features will be re thinked and maybe added in future versions, i'll update this report once another feature from it is applied

Eating animations and drinking potion animations?

**Comment by wushen233** [comment]
> other features will be re thinked and maybe added in future versions, i'll update this report once another feature from it is applied

Then there is the function of automatically locking monsters. I remember that it was provided to yesman before, and he said at the time that he did not know how to implement this function. But now there is https://github.com/alRex-U/AutoLook

**Comment by Yesssssman** [comment]
Actually, some other developers already implemented the eating and drinking animation. But they're waiting for the library mod. So this will be the feature after the library.

**Comment by wushen233** [comment]
> 实际上，其他一些开发者已经实现了吃喝动画。但他们正在等待图书馆模式。所以这将是图书馆之后的功能。

Wow, that would be a very nice update!
