### ISSUE TITLE
Can you backport the new config files (.toml) to 1.12.2 please ?

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#791]
I know you are not able to backport other new things to 1.12.2,but i want you to do it on new config files.
If you do that,we can add weapons easily to 1.12.2 like how it is in new versions.

**Comment by Yesssssman** [comment]
The configuration file is built in Forge. I don't have such ability to make it. Sorry.

**Comment by TurkishAhmet4545** [comment]
> The configuration file is built in Forge. I don't have such ability to make it. Sorry.

As last,can i ask for backporting other things ?
Whats are unable to be backported ?

**Comment by Yesssssman** [comment]
I'll not backport to 1.12.2 'cause people will ask me about backporting every time I update in the latest version. It's too hard to support multiple versions at the same time.

**Comment by TurkishAhmet4545** [comment]
> I'll not backport to 1.12.2 'cause people will ask me about backporting every time I update in the latest version. It's too hard to support multiple versions at the same time.

Can your latest backporting be the guard mechanic ?

**Comment by WerelWolf** [comment]
i believe in a latest version for 1.12.2

**Comment by TurkishAhmet4545** [comment]
> I'll not backport to 1.12.2 'cause people will ask me about backporting every time I update in the latest version. It's too hard to support multiple versions at the same time.

Please at least the blocking system.
It is just a very important thing.
Please that can be your latest backport to 1.12.2.
