### ISSUE TITLE
Mod Support Request: Mana and Artifice

### ISSUE THREAD

**Issue by SerNurp** [Yesssssman/epicfightmod#797]
Playing around with these two mods, the newest update of Mana and Artifice causes issues with Mana and Artifices factional armors to break, the textures stretching across the body and removing the animations attached to them.

I spent about 12 hours trying to fix the error myself only to realize the error is tied to this mod, and I could not simply change the texture.

Using the "Filtered Animations" config option I have attached screenshots of what it should look like, and what's happening to the armor
![2021-11-20_18 45 08](https://user-images.githubusercontent.com/55299287/142746141-0334ac61-615d-467c-aeeb-bf0614d60c4e.png)
![2021-11-20_18 45 11](https://user-images.githubusercontent.com/55299287/142746144-fd9e77c1-aacd-42c9-97bb-3065070e3340.png)
.
The armors sets that actively break when in combat mode from Mana and Artifice would be the: Witherbone armor set, Druidic armor set, Infernal armor set, and the Spellweaver armor set.

**Comment by Yesssssman** [comment]
#536
