### ISSUE TITLE
Crash with Bountiful Baubles

### ISSUE THREAD

**Issue by GenericDwarf** [Yesssssman/epicfightmod#8]
The game,being in singleplayer or in a server, crashes everytime you hold/equip an obsidian/ankh shield from Bountiful Baubles. Crash report below.

[crash-2021-02-22_18.24.52-server.txt](https://github.com/Yesssssman/epicfightmod/files/6025236/crash-2021-02-22_18.24.52-server.txt)

**Comment by Yesssssman** [comment]
This is same issues with #6 . Will be fixed in new version.
