### ISSUE TITLE
Epic Fight Issues with server hosting

### ISSUE THREAD

**Issue by LordIsopod** [Yesssssman/epicfightmod#801]
When I run my mod pack on just my pc, the mods work just fine. As soon as I upload them to my server, the server crashes as soon as anyone joins. This is even after the most recent update to "16.5.12" where join lag was fixed. Please update me if this issue gets fixed or you find a work around

**Comment by Gigarus** [comment]
i had similar issues on #799 as well.

**Comment by Yesssssman** [comment]
Please attach a crash report.

**Comment by LordIsopod** [comment]
here is the report my server gave me after running the mod by itself, to me it looks like lag, because its a "ticking entity" crash. Here is a link to the file in my google drive: https://drive.google.com/file/d/1QDRgmacWFTrSpIjBuoIx3xyFbhs6YIg_/view?usp=sharing

**Comment by Gigarus** [comment]
I just solved this issue by switching to 36.2.0 for 1.16.5 forge, make sure to get the latest 1.16.5 version of the mod too.

It doesn't seem to work with the latest version of forge strangely.

**Comment by LordIsopod** [comment]
ill try that right now

**Comment by LordIsopod** [comment]
@Gigarus that does seem to work! I was running the most recent version of forge 1.16.5 . I still wonder why the mod causes crashes on other versions?

**Comment by Yesssssman** [comment]
I found some codes are not working in latest Forge version. It will be fixed as soon as possible.
