### ISSUE TITLE
<suggestion> knuckles buff or rework

### ISSUE THREAD

**Issue by Lermonix** [Yesssssman/epicfightmod#804]
I think that the knuckles need a buff or a rework where their strength is a more defensive strategy than offensive, like a kick that pushes at the end of the combo and / or a kick when sprinting that pushes (just like the endeman), and they need more durability since as they require more hits to defeat an enemy and that makes them break quickly and it specials attack may changed for  2 - 3 hits to end with a powerful blow that pushes a great distance since the current special attack spends a lot of durability .

Keep it up, your mod is amazing!

**Comment by Yesssssman** [comment]
Balancing needs more discussion with more people but anyway thanks for providing your opinion.
