### ISSUE TITLE
Epic Fight Mod Causing Ticking Errors For My Aternos Server?

### ISSUE THREAD

**Issue by Sir-Lycan** [Yesssssman/epicfightmod#806]
I havent been able to run my minecraft server due to ticking errors occuring, ive tried doing many things such as using cofh core, /kill @e, /cofh killall but it still hasnt fixed, the only reason why i talk about it here is because epic fight mod is the cause as just removing it fixes it, but we want the mod installed, we dont know what mods clashing with epic fight mod but we still cannot even start the server up.
The ticking entity is usually a rail, leather, so far, heres the latest log.
https://mclo.gs/XPHzk48
The mods i am using are,
![image](https://user-images.githubusercontent.com/94950610/143181466-6e10f166-6108-4811-860e-0fbcb0d0d264.png)
Forge Version - 1.16.5-2.18
Edit - It also causes a player ticking in my single player, crashing my game.

**Comment by Sir-Lycan** [comment]
Its also causing ticking player inside singleplayer.

**Comment by Yesssssman** [comment]
The latest forge version has issues with EpicFight below 16.5.12. Update the Epic Fight version to 16.5.13 or Downgrade your forge version.

**Comment by Yesssssman** [comment]
@Sir-Lycan Could you also post the repo for the ticking crash?

**Comment by Sir-Lycan** [comment]
heya sorry for the late reply @Yesssssman thankyou, it worked me and my friend were just reconfiguring as we then had a problem with forge and t-construct
