### ISSUE TITLE
Make Dodge be based on camera direction instead of model (suggestion)

### ISSUE THREAD

**Issue by lyeochan** [Yesssssman/epicfightmod#807]
So basically, i noticed that the dodge / step buttons make u dodge based on the current model's direction, usually that doesn't matter since the MC character is always looking forward. BUT if u pair it with other mods like Better Third person the results might be unsatisfying.

https://user-images.githubusercontent.com/94973750/143250377-979375d8-7f39-43d5-859c-3955fd349613.mp4

Like on this vid, when i am running left but with my camera pointed forwards, id like to roll left too. Well, tis not the end of the world, but would be very cool for this amazing mod!

**Comment by megagnarxd** [comment]
+1, also what is the compass mod (not journey map)

**Comment by lyeochan** [comment]
it be RPG hud

**Comment by megagnarxd** [comment]
thanks! also hoping he'll fix it since it's pretty crucial to have better third person with epic fight

**Comment by Bitgedon** [comment]
I think the dodge direction is based on direction of movement.

**Comment by lyeochan** [comment]
i really don't know how it works, but if it were to be based on camera + which of the movement keys ur pressing, that would be awesome since that would be pretty much Dark Souls Rolling on MC! This already awesome mod would become even more awesome in my opinion.

**Comment by ElTioYisus** [comment]
Its direction based on movement while shifted. I use shouder surfing mod and i havent seen any problem.

**Comment by Yesssssman** [comment]
Applied in 1.18.2
