### ISSUE TITLE
Epic Fight Mod  1.16.5 error reporting

### ISSUE THREAD

**Issue by 915594695** [Yesssssman/epicfightmod#808]
I like this mod very much, but I have a crash problem when playing. It seems that there is a problem in the selection of epic fight mod. Because the technology is limited, I submitted an error log and hope it can be repaired

[error-2021-11-24_23.12.53.zip](https://github.com/Yesssssman/epicfightmod/files/7599514/error-2021-11-24_23.12.53.zip)

**Comment by fkyah3** [comment]
大概情况就是 有个实体出现问题了   18.47, 61.00, -180.19在这个坐标的僵尸卡住了 你只需要开个和平就行了 或者把这个区块的先删了之类的

**Comment by fkyah3** [comment]
而且我注意到你的版本是11版本 我建议你升级到最新的forge和最新的版本来尝试修复他

**Comment by 915594695** [comment]
[错误报告-2021-11-26_23.32.56.zip](https://github.com/Yesssssman/epicfightmod/files/7609653/-2021-11-26_23.32.56.zip)
looklook this is 1.3

**Comment by fkyah3** [comment]
-38.50, 70.00, -298.50 一个僵尸being ticked 区块文件-1,-1 老样子 僵尸ticked了 没啥办法 我不知道服务器和客户端分开会不会有啥大帮助 我水平有限只能帮到这里了

**Comment by Yesssssman** [comment]
Fixed in the recent update.
