### ISSUE TITLE
compatibility with eidolon mos

### ISSUE THREAD

**Issue by StaticFaid** [Yesssssman/epicfightmod#81]
the new armor model looked great for ice and fire mod but the armor is a bit wrong for the edoilon mod :/

**Comment by Yesssssman** [comment]
https://youtu.be/icL5Hqe86Qg
Try the instruction that I fixed in comments. If it still look weird, it's so sad to say, but it's out of my strength for now :(

**Comment by Yesssssman** [comment]
I accidently misclicked close tab. sorry!

**Comment by StaticFaid** [comment]
> https://youtu.be/icL5Hqe86Qg
> Try the instruction that I fixed in comments. If it still look weird, it's so sad to say, but it's out of my strength for now :(

np its fine if nothing can be done its great
