### ISSUE TITLE
Special attack in survival mode is not working and it is having strange animation on sleeping. 

### ISSUE THREAD

**Issue by InsaneKart** [Yesssssman/epicfightmod#812]
I am using 1.16.5 version
And special attacks are not working in survival mode please help
The special attacks are only working in creative mode
And the when I click on bed the player do strange animation it just siting on the bed and rotating its hands

**Comment by Bitgedon** [comment]
Did you charge you special ability bar before trying to use it in survival?

**Comment by fkyah3** [comment]
![1](https://user-images.githubusercontent.com/87884337/143590273-0c8b72e4-02bd-4e75-8efc-2d22bc0e796d.gif)
Same as me lol
Hope fix in next undate

**Comment by fkyah3** [comment]
Infact you just in mod option open filter animation,when you in dig mode its all be normal

**Comment by InsaneKart** [comment]
> Did you charge you special ability bar before trying to use it in survival?

How to do it pls
I first time installed this mod
