### ISSUE TITLE
Detached 3rd party character enhancments

### ISSUE THREAD

**Issue by ph4tcat** [Yesssssman/epicfightmod#816]
When using EARS (https://www.curseforge.com/minecraft/mc-mods/ears/) or Skin Layers 3D (https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)

The ears and 3D voxel elements are not attached to me

I'm running:
EpicFightMod-16.5.13
Forge 36.2

Image of error: 
https://imgur.com/GrtTuDl

**Comment by DearFox** [comment]
To make compatibility with Ears Mod better - I think that you should not create a new player’s head, but use his current head, then the ears on the head should follow the head.
 As an example: https://modrinth.com/mod/emotecraft
 In any case, there will be problems with bends, but I think that technically the head can be fixed.

**Comment by guivnf** [comment]
Fixed in 20.8.2. We weren't able to fix all the changes to the older versions. Thank you for your consideration.
