### ISSUE TITLE
(suggestion) Add which values for AI type are avaliable in the Toml files. 

### ISSUE THREAD

**Issue by lyeochan** [Yesssssman/epicfightmod#819]
This:

		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, LONGSWORD, DAGGER, BOW, CROSSBOW, TRIDENT, SHIELD
		weapon_type = "SWORD"
		
But for entities.
Something like this, would be interesting:
               #Allowed Values:ZOMBIE, SKELETON, VINDICATOR, SPIDER, WITCH, PIGLIN, HOGLIN, ZOGLIN, etc
               ai_type = "ZOMBIE"
               
               
               
               now some extras, that could be nice: A little explanation of what each AI type is capable.
               
               Zombies: run towards the player and hit them
               Skeletons: If with sword will run to player and hit them, if with bow will try to shoot the player
               
               give all AI some basic Ranged /  rightclick capability, what if a zombie spawns with a ranged weapon/tridend (which had to be rightclicked to use on ranged atack). 
               
               
               This would help a lot, thanks for the awesome mod !!!!

**Comment by ElTioYisus** [comment]
And golem! dont forget golem!

**Comment by Yesssssman** [comment]
I'd like to say I'm gonna make massive changes regarding custom AI and it would use the datapack. Also, this function is deprecated.
