### ISSUE TITLE
Crash upon joining Multiplayer server

### ISSUE THREAD

**Issue by archonxgames** [Yesssssman/epicfightmod#82]
Forge version: 36.1.0
Epic Fight version: 3.0.4

Works fine in singleplayer, but in Multiplayer server crashes every time a player attempts to join.

Full crash report: [crash-2021-03-19_10.04.13-server.txt](https://github.com/Yesssssman/epicfightmod/files/6170309/crash-2021-03-19_10.04.13-server.txt)

**Comment by Yesssssman** [comment]
Are the server and client are the same versions?

**Comment by Fucaa** [comment]
When my friend join in my server, he gets stucked and cant move. Sometimes his game crashes.

The server and client are the same versions.

**Comment by archonxgames** [comment]
Yes, server and client have the same versions of Epic Fight mod, 3.0.4

**Comment by archonxgames** [comment]
The other mods I have that I think might affect Epic Fight is Create, Psi, and Mining helmet mod. It could be Mining Helmet that is causing the crashes since its always zombies that cause the crash, and zombies can spawn with Mining Helmets. Though this is unlikely because singleplayer works fine.
