### ISSUE TITLE
Issues with the skills book.

### ISSUE THREAD

**Issue by Milenos** [Yesssssman/epicfightmod#820]
Hi. The problem I currently have is that there is only 1 skill book for Dodge roll and it can't be opened, and no other book show up in the JEI. Im not sure what is causing that, since I downloaded a Modpack directly because it was fully configurated for Epic
![2021-11-28_01 49 53](https://user-images.githubusercontent.com/95160662/143732602-ec3923e7-741c-49fa-b8f2-38491f06caca.png)
. 

I added some mod, but even a clean install doesnt show the book.

**Comment by lyeochan** [comment]
why would this be a issue with the mod? have u checked if the modpakc dev decided to remove the other skills?

**Comment by Milenos** [comment]
Im not sure why he would do that, since its a mod pack centered around it.

**Comment by lyeochan** [comment]
well, at least check it,  i guess. Modpack makers do have a wild mind.

**Comment by DistantDig** [comment]
Actually, I have this same issue. The difference is that its not apart of a modpack for me and I see a different skill. If it helps, I do have other mods installed

**Comment by Yesssssman** [comment]
It looks like the modpack maker doesn't update Epic Fight. Contact him.
