### ISSUE TITLE
Can this be your latest backport ?

### ISSUE THREAD

**Issue by TurkishAhmet4545** [Yesssssman/epicfightmod#826]
Can you make the latest backport to 1.12.2 please ?
These newest updates are very important.

Especially,the blocking/defense ability.
Can you make atleast the blocking system ?

These new updates are worthy for any version.
This can be the last time i ask for a backporting to 1.12.2 if you do and if new or big bugs doesn't appear.

**Comment by WerelWolf** [comment]
dude please stop it, it won't do the backport, but if you want to share the backport value with me, i'm budgeting with some programmers to do this service, call me on dscord Werelwolf#5280

**Comment by TurkishAhmet4545** [comment]
> dude please stop it, it won't do the backport, but if you want to share the backport value with me, i'm budgeting with some programmers to do this service, call me on dscord Werelwolf#5280

Thank you for changing some ideas in my mind.
