### ISSUE TITLE
(Suggestion) Could you add these in the next major update

### ISSUE THREAD

**Issue by Ghidorah4** [Yesssssman/epicfightmod#827]
This suggestion is  only to make the mod more Rpg like

Leveling
You would start as a level one that cant use any skills like dodging or the special attack and as you level up you can use the points given to you and increase your base defense to unlock blocking or upgrading your speed to unlock dodging, wall running, or increasing your stamina

Skills
Just adding more skills like an air slash  that eats up at your stamina or a skill where just slam your sword to the ground that does a big aoe(This would be used for the greatsword users).

Weapons
Sythe- this would be resting on your shoulder swinging it around
Flintlock pistol- high damage, low reloading, range is about 5 to 10
Musket- higher damage, lower reloading, range is about 12 to 17 bolcks
Longbows-high damage, low drawing speed, much more accurate, range is much more higher

Classes
You would start of as an adventurer and when reaching a certain threshold you can become a Warrior ( Anything that has a handle), a Fighter ( Fists, Knuckles), and a Hunter( Dagger, Bows, Longbows, Crossbows these would be the main classes that branch out to other classes. they would boost your weapon for percent so you could use other weapons from other classes with no draw backs.

Class Tree
A warrior would branch out to be a tier 1 Defender ( Axe, Greatsword), a Knight ( Sword, Longsword), , Ronin ( Tachi, Katana), Spearmen (Trident, Spear). Then these would branch out to a tier 2 that would focus on only one weapon

**Comment by ElTioYisus** [comment]
This mod focus on fight mechanics not rpg system. Would be great if cross support with other mods are implemented like player ex or mine and slash. Personal thought.
Other mods that adds gun weapons uses the normal bow animation, so longbows only need a longer animation to fit.
I feel that guns like musket and flintlock needs their own animation to fit well.
