### ISSUE TITLE
Server Crash - Ticking entity (Spider)

### ISSUE THREAD

**Issue by Tennik** [Yesssssman/epicfightmod#83]
Hello! I got a server crash when playing in multiplayer on my own server. It was called by Ticking entity - Spider, and it can repeat from time to time, at different intervals.

**I use a 1.12.2 version of client, server and mod version is EpicFightMod-1.12.2-1.1.0.jar**

There are latest crash reports:
[crash-2021-03-19_12.07.56-server.txt](https://github.com/Yesssssman/epicfightmod/files/6170687/crash-2021-03-19_12.07.56-server.txt)
[crash-2021-03-19_12.53.55-server.txt](https://github.com/Yesssssman/epicfightmod/files/6170684/crash-2021-03-19_12.53.55-server.txt)

**Comment by Yesssssman** [comment]
1.12.2 version is outdated now. please wait until I finish updating it.

**Comment by Tennik** [comment]
Ok, I will wait for it!
Btw, can you also add config file for 1.12.2? I want to add weight and stun for other weapons and armor
Thank you!

**Comment by Yesssssman** [comment]
I'm backporting everything featured in 1.16. but there could be missed one because 1.12's code is quite different from 1.16.

**Comment by Tennik** [comment]
Yeah, I know, I have some skills with 1.12 modding, I made some portings from 1.7.10 to 1.12.2. I can help you with that
And one more thing. Can you also add an animation for standart player model from Custom NPC`s mod? It looks very strange when player is animated but Custom NPC`s are not
