### ISSUE TITLE
Custom Armor

### ISSUE THREAD

**Issue by Rydjinn** [Yesssssman/epicfightmod#830]
I know that it's possible to make armor from other mods compatible with Epic Fight, but I can't figure out how to do it. I wanted to make the armor models from Mana and Artifice not look like a jumbled mess. Can anyone help/do that?

Without Epic Fight

![2021-12-08_01 04 53](https://user-images.githubusercontent.com/88597604/145130447-2b9179a0-c58e-4204-895b-11c5e0a1dcab.png)

With Epic Fight

![2021-12-08_00 50 44](https://user-images.githubusercontent.com/88597604/145130480-755eeeee-e799-420a-94c1-54ce6aa373ed.png)

**Comment by ClockworkzAI** [comment]
https://www.youtube.com/watch?v=aTEDYgWZrbg

its on the page its the same method for the sword you do with the armour

**Comment by Rydjinn** [comment]
I looked into that, but it's not the same thing. I'm fine with the stats, I just want it to look right.

**Comment by Yesssssman** [comment]
#536
