### ISSUE TITLE
The weapon animation is still the same. (1.16.5)

### ISSUE THREAD

**Issue by Rademon74** [Yesssssman/epicfightmod#832]
Hello Everyone,
Sorry to annoy you with that but I tried to fix this bug that makes it so the weapons animation is still the vanilly slashing vanilla one and couldn't do it by myself. I read that you had to disable the vanilly weapon animation in game rules before creating the world and tried that, it didn't fix it. I also tried to hit a zombie but I somehow I'm unable to hit them.

I'm using Epic Fight Mod with some other mods as I'm trying to create a rather large private modpack for me and my friends. I've been installing the mods 10 by 10 and troubleshooting the problems each time if I spotted some but I can't fix this one by myself, here is the list of the other mods:

- Advanced rocketry
- Atmospheric
- Awesome Dungeons plus
- Better animals plus
- Better biome blend
- Yungs Better Dungeons
- Yungs Better Stronghold
- Yungs Better Mineshaft
- Yungs Bridges
- Yungs Extra forge
- Better End forge
- Better Nether reforged
- Better third person
- Biomes O Plenty
- Buzzier Bees
- Caves and Cliffs backport
- Create
- Desolation
- Dungeons Plus
- Dungeons Arise
- Dynamic Trees
- DT B.O'Plenty patch
- DT plus
- Elenai Dodge 2
- Endergetic expansion
- Enironmentl
- Infernal expansion
- Just enough items
- Repurposed structures forge
- Sky villages
- Sodium forge
- Stoneholm
- Towers of the wild
- Twilight Forest
- Upgrade aquatic
- Valhelsia structures

Is there a known reason why the animation would stay the vanilla ones (the "battle stances" when you hold a weapon like the longswords are working correctly but when you attack the animation is still vanilly, I can see other animations like climbing and sneaking working correctly though!) is there a known incompatibility between a mot that I mentioned and Epic Fight? I would really like to make this mod work as it's a great part of my attempt to make the fighting gameplay really interesting in that modpack for me and my friends.

Thanks for your time and help.

**Comment by Rademon74** [comment]
Little update: The unability to hit something seemed to have been fixed by removing the other mods so I should be able to find which mod causes this when working with Epic Fight, but even when Epic Fight is my only mod with Forge, the attack animation stays the vanilla one even when I set Vanilla attacks off in game rules when creating the world.

**Comment by TripConeHead** [comment]
Did you manage to find out which mod was causing it? I'm having the same issue.

**Comment by Rademon74** [comment]
For some reason the unability to hit something just vanished and I don't have that bug anymore while I didn't remove any mods. For the vanilla animation it's really dumb from me but you don't need to change the game rules by putting vanilla attacks to off, if you have vanilla attacks just press R and it should be the key to change between mining and fighting mode and during fighting mode you should see a new blue icon on the right of your hud that show the loading of a special attack and in that fighting mode the animations should work.
