### ISSUE TITLE
Visual issue: enderman dont have a proper block holding animation

### ISSUE THREAD

**Issue by Shibva** [Yesssssman/epicfightmod#833]
for 1.16.5 (and others maybe) when the enderman that is animated holds a block, it dosent show that its holding it, instead it shows that its "using its mind to have it be suspended in front of their face"

while this is amusing it gives off a buggy look, can you investiage

to reproduce, just have an enderman holding a block

**Comment by SteamDoge9000** [comment]
heres an image to show what im talking about 
![2021-12-11_21 11 11](https://user-images.githubusercontent.com/38770780/145739995-607e55c5-e934-479f-bb65-2044286bab94.png)
