### ISSUE TITLE
[may or may not be issue] Losing skills

### ISSUE THREAD

**Issue by Ianoneshot** [Yesssssman/epicfightmod#835]
Good morning, afternoon, or night,

Me and my friend are making an adventure map inspired by Dark Souls, but this one has it's own unique story and identity. We decided your mod was perfect, however the only issue that I can see right now is that when you die you lose your skills. Being a souls-like, that means players will be dying a lot. 
Is there some way we can manipulate the mod so that the players always have a skill after they learn it even after death? It could be going into the mod file and manipulating it, or it could be a setting in the game itself?
Currently our map is stuck at 1.16.5 at the moment, if that helps at all. 
Thank you so much for your time.

Sincerely,
I.S.

**Comment by ClockworkzAI** [comment]
It always help to read the mod page:
/gamerule keepSkills true/false (default false)

Determines if the skills player learns will be maintained when the player dies.

**Comment by Ianoneshot** [comment]
Sorry! I'm very unobservant apparently.
Have a nice holiday season (if you celebrate that)!
