### ISSUE TITLE
Confirmed feature Incompatably issue: non-player animations are Frozen when certain performant setting is enabled

### ISSUE THREAD

**Issue by Shibva** [Yesssssman/epicfightmod#838]
im currently investingating this issue based on it not happenig before, for some uknown reason the visuals that are created from hostiles appear to be frozen and not moving correctly as a result. Im trying to currently track down what might be the possable cause for this sudden and unpresidented shift

**Comment by SteamDoge9000** [comment]
Investigation is complete, I found the issue, 

This only happens and can be reproduced if Perfromant and if this setting is set to true

it seems to mess wtih the fuctions that animates the mobs movment animations
![image](https://user-images.githubusercontent.com/38770780/145763459-f43829eb-71dd-44ca-abbb-b019304b1dc9.png)

**Comment by RichieGael** [comment]
uh so i had this issue but im not sure how to disable it, when i try to look for performant in the mods tab it doesnt have a config file so i need help on how to disable it please

**Comment by RichieGael** [comment]
ok but how do i do that? you said in a txt file but where?

**Comment by SteamDoge9000** [comment]
Like I said you could also do it using the Configured mod but if you do it that way you need to restart the game after you make that change

**Comment by SteamDoge9000** [comment]
As for the config in the config folder search the name performant and select the one that you believe is the right one it's either as a plain tax document or it's in a file name performant
