### ISSUE TITLE
Missing Skill Books

### ISSUE THREAD

**Issue by DistantDig** [Yesssssman/epicfightmod#839]
I have the exact same issue as the one from #820 
Even with the mod installed all by itself I can only find one skill book in the creative menu. This is the case in 1.16 and 1.17, and I have not configured it to remove the skill books. The book is stamina pillager if that makes any difference.

**Comment by CynderR** [comment]
+1
Only mods are:
EpicFightMod-16.5.13
jei-1.16.5-7.7.1.139

Using forge: 36.2.20

Only skill book via give command or jre is

**Skill Book**
Stamaina Pillager
epicfight:skillbook
NBT: 1 tag(s)
Epic Fight Mod


![Screenshot (10)](https://user-images.githubusercontent.com/3331762/148593069-a7e5a3ef-3f28-439d-bc68-fb212a8a4b4a.png)
![Screenshot (14)](https://user-images.githubusercontent.com/3331762/148593072-90faddf9-8d3a-4c6b-b4a3-96b729b0cfd0.png)
ands and jei is

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
