### ISSUE TITLE
Animation Issues With Some Other Mod

### ISSUE THREAD

**Issue by Ecderebi** [Yesssssman/epicfightmod#84]
We are using MrCrayfish's Gun mod. But looks like Epic Fight Mod animations doesnt allow it. 
![tp2 (1)](https://user-images.githubusercontent.com/80206351/111778444-b619a180-88c5-11eb-9184-d431f02f7ca7.png)
![tp2 (2)](https://user-images.githubusercontent.com/80206351/111778448-b74ace80-88c5-11eb-8af9-124aad2f1cf9.png)

**Comment by Yesssssman** [comment]
There is an option that allows the turning off animation of epicfight. Go to the config tab on the main screen of Minecraft > epicfight > config and turn on the "filter animation" option then the animation will be turned off when you're none battle mod.
