### ISSUE TITLE
Do not install create onto a server with this mod

### ISSUE THREAD

**Issue by Bitgedon** [Yesssssman/epicfightmod#840]
Attempted to install create (the automation mod) onto a server which had this mod on it. This caused a ticking entity error so widespread and so horrendous that all backups became corrupted as soon as they started, even after removing create, all attempts to remove the ticking entity caused more ticking entities, joining cause my character to corrupt. Something with flywheel is likely the issue but I can't even begin to understand why. I attempted to enable forge's nuclear option 

removeErroringEntities: true

The server started, the server lagged so bad that a single tick did not pass for 60 seconds. There we're so many ticking errors the server could not run. This is just one of many crash reports the server produced while I attempted to fix this issue. Idk if this is even an issue 

[crash-2021-12-15_19.23.38-server.txt](https://github.com/Yesssssman/epicfightmod/files/7723696/crash-2021-12-15_19.23.38-server.txt)

I am at a loss for words.

I understand that there likely isnt anything the dev's can do but I just wanted to post this as a warning to all who may fair into the same seas as me.

**Comment by ClockworkzAI** [comment]
Have you install the newest version of epic fight mod you seemed to be running 16.5.11 while there is 16.5.13

**Comment by Bitgedon** [comment]
> Have you install the newest version of epic fight mod you seemed to be running 16.5.11 while there is 16.5.13

No I had the older version when the crash happened but upon reviewing the change log it shouldnt have affected anything. I think I diagnosed the issue to being flywheels rendering engine updates completely corrupting all entities that are affected by epic fight. The only thing that still confuses me is that even after removing create and restoring a backup of the world it still corrupted all the entities on load in.
