### ISSUE TITLE
Problem with add entity to Epic Fight configs.

### ISSUE THREAD

**Issue by ZEkA10000** [Yesssssman/epicfightmod#843]
I have template 
```
[custom_entity.custom_enitiy]
		type_name = "mod_id:custom_enitiy"
		impact = 0.5
		max_strikes = 1
		armor_negation = 0.0
		#Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
		ai_type = "ZOMBIE"
		texture_location = "texture_path"
```
---
I tried to add new enitiy from installed mod ZombieArmy: ZombieBrute 

```
[custom_entity.zombievrute_1]
		type_name = "zombiearmy:zombievrute_1"
		impact = 0.5
		max_strikes = 1
		armor_negation = 0.0
		#Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
		ai_type = "VINDICATOR"
		texture_location = "minecraft:textures/entity/zombie/zombie.png"
```
Result: Game crashes

---

Tried to add new enitiy from installed mod ZombieArmy: Zombie Ranger
```
[custom_entity.zombieranger_1]
		type_name = "zombiearmy:zombieranger_1"
		impact = 0.5
		max_strikes = 1
		armor_negation = 0.0
		#Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
		ai_type = "SKELETON"
		texture_location = "minecraft:textures/entity/zombie/zombie.png"
```
Result: Zombie don't count me as enemy

---

Tried to add new enitiy from installed mod ZombieArmy: Zombie Mage
```
[custom_entity.zombiemage]
		type_name = "zombiearmy:zombiemage"
		impact = 0.5
		max_strikes = 1
		armor_negation = 0.0
		#Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
		ai_type = "ZOMBIE"
		texture_location = "minecraft:textures/entity/zombie/zombie.png"
```
Result: Zombie don't shot by custom projectiles + Zombie have wrong texture on model 
All zombies are same in models and all zombies have vanilla textures

**Comment by DarkScorn** [comment]
texture_location: you should change this to the expected mobs' model location in the mod file.
Not all mobs are compatible with ai or textures.
This doesn't mean all mods cannot be used, atum forsakens and mummies do the job perfectly.

**Comment by Yesssssman** [comment]
Config by toml file is completely deleted. Use data pack instead.
