### ISSUE TITLE
Compatibility and Customization

### ISSUE THREAD

**Issue by SubkingExtinct** [Yesssssman/epicfightmod#848]
Hello, i have  few questions about this mod's **compatibility**, i haven't tried it yet but it would be better to ask before doing so.

Is this mod compatible with **Customizable Players**? and what about the **Resourcepack** _Fresh Animations_? they're both great mods however they do not improve anything in the **combat system** like this mod does, i would like to know if compatibility is possible between these, since _i as many others wish to combine these for an even better experience_.

I apologize in advance if this troubles you in any way.
I'll be waiting for a reply, thank you!

**Comment by Yesssssman** [comment]
Epic Fight uses an entirely different model from vanilla. They're designed based on vanilla models so it's technically incompatible.
