### ISSUE TITLE
Dodge is not working - EpicFightMod- 16.5.13

### ISSUE THREAD

**Issue by Sebaspc97** [Yesssssman/epicfightmod#849]
Dodge key is not working, tried using different keys and restarting the world.

Mod that I am using:
-Biomes o plenty - 13.1.0.484
-CustomNPCs 21dec19snapshot
-IceandFire - 2.1.9
-Citadel - 1.8.1
-Jei - 7.7.1.138
-JourneyMap - 5.8.0 Beta 4
-Optifine - HD U G8

**Comment by InsaneKart** [comment]
Step 1- go in inventory 
Step 2- search roll
Step 3- a skill book will come
Step 4- this book in inventory and right click
Step 5- learn
U can now roll

For more details Check epic fight mod on youtube on youtube

**Comment by Sebaspc97** [comment]
Sorry, didn´t used since 1.12.2. Im glad that the mod has improved :)
