### ISSUE TITLE
Posible error de renderización con barra de salud activa 

### ISSUE THREAD

**Issue by DragonAstemirN** [Yesssssman/epicfightmod#851]
Encontré un problema con la renderización el los cascos de entidades, esqueleto wither, zombie, esqueleto. El problema se genera cuando la entidad o parte de la armadura (casco) posee el encantamiento de fuerza. 

![2021-12-24_00 09 39](https://user-images.githubusercontent.com/94336869/147324621-c72cabfe-4570-423a-aae3-88ae80e1d5fa.png)

El problema solo se genera cuando la barra de salud esta presente únicamente 
![2021-12-24_00 09 43](https://user-images.githubusercontent.com/94336869/147324780-2b4174a6-9f21-499e-a099-94e325c4e155.png)

**Comment by Yesssssman** [comment]
So what's the problem
