### ISSUE TITLE
pls set optifine custom armor texture pack😭😭

### ISSUE THREAD

**Issue by LILPRINCES** [Yesssssman/epicfightmod#852]
😭😭Please make the mod compatible with some optifine custom armor texture packs. Some texture packs have the function of custom naming and changing the armor texture, but the custom armor texture cannot be displayed in the mod. 
without epic fight mod😋
![Thumb 64099161894-64e0ec8a-2f80-3f8f-bf53-09e4dea94dcb](https://user-images.githubusercontent.com/60571513/147342271-7139d286-be71-4604-92f3-45aadcddf858.jpg)
with epic fight mod😭
![Thumb 64099161894-3fb8f7ac-4102-339a-bdf0-d07c4f443db0](https://user-images.githubusercontent.com/60571513/147342340-dde4aa8c-ede7-4ae6-8f9f-acc2504fb995.jpg)

**Comment by Aronforester** [comment]
He pinned the message he won't deal with 3d armor glitches

**Comment by LILPRINCES** [comment]
> He pinned the message he won't deal with 3d armor glitches

But he is not caused by other mod, but a texture pack based on vanilla textures. His model is the same as vanilla armor.

**Comment by Yesssssman** [comment]
I can't handle the optifine issues because it's not an open source.
