### ISSUE TITLE
Shaders incompatibility

### ISSUE THREAD

**Issue by Sebaspc97** [Yesssssman/epicfightmod#854]
Im using the last 1.16.5 version and I´ve tried several shaders. None of them work propertly. Katanas, Spears and other items show purple/black blocks instead of the texture.

Shaders work on EFM for 1.12.2 btw.

**Comment by SimulatorSia** [comment]
I have the same issues, it's made worse with the Inspirations mod. I don't think this is something that could be fixed without hard coding in optifine's rendering. (personal opinion, I don't represent epicfightmod)

**Comment by Yesssssman** [comment]
Try F3+T.
