### ISSUE TITLE
Death Freeze

### ISSUE THREAD

**Issue by Storkclips** [Yesssssman/epicfightmod#859]
### I have encountered an issue, whereupon the death of the player the game freezes.

> `
> 06.01 00:20:28 [Server] Server thread/INFO Smerkll was slain by Zombie
> 06.01 00:20:29 [Server] Server thread/ERROR Exception caught during firing event: Duplicate id value for 252!
> 06.01 00:20:29 [Server] INFO Index: 2
> 06.01 00:20:29 [Server] INFO Listeners:
> 06.01 00:20:29 [Server] Startup0: NORMAL
> 06.01 00:20:29 [Server] Startup1: ASM: com.minecraftabnormals.abnormals_core.common.capability.chunkloading.ChunkLoaderEvents@1801d8a3 attachChunkLoaderCap(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
> 06.01 00:20:29 [Server] Startup2: ASM: class yesman.epicfight.events.CapabilityEvent attachEntityCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
> 06.01 00:20:29 [Server] Startup3: ASM: class yesman.epicfight.events.CapabilityEvent attachItemCapability(Lnet/minecraftforge/event/AttachCapabilitiesEvent;)V
> 06.01 00:20:29 [Server] INFO java.lang.IllegalArgumentException: Duplicate id value for 252!
> 06.01 00:20:29 [Server] INFO at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:86)
> 06.01 00:20:29 [Server] INFO at yesman.epicfight.capabilities.entity.LivingData.onEntityConstructed(LivingData.java:78)
> 06.01 00:20:29 [Server] INFO at yesman.epicfight.capabilities.entity.player.PlayerData.onEntityConstructed(PlayerData.java:51)
> 06.01 00:20:29 [Server] INFO at yesman.epicfight.capabilities.entity.player.PlayerData.onEntityConstructed(PlayerData.java:38)
> 06.01 00:20:29 [Server] INFO at yesman.epicfight.events.CapabilityEvent.attachEntityCapability(CapabilityEvent.java:35)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler_53_CapabilityEvent_attachEntityCapability_AttachCapabilitiesEvent.invoke(.dynamic)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:601)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:595)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:90)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:85)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:64)
> 06.01 00:20:29 [Server] INFO at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapsAndRevive(CapabilityProvider.java:68)
> 06.01 00:20:29 [Server] INFO at net.minecraft.server.management.PlayerList.respawn(PlayerList.java:640)
> 06.01 00:20:29 [Server] INFO at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:535)
> 06.01 00:20:29 [Server] INFO at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2054)
> 06.01 00:20:29 [Server] INFO at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30)
> 06.01 00:20:29 [Server] INFO at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8)
> 06.01 00:20:29 [Server] INFO at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
> 06.01 00:20:29 [Server] INFO at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
> 06.01 00:20:29 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
> 06.01 00:20:29 [Server] INFO at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
> 06.01 00:20:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942)
> 06.01 00:20:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
> 06.01 00:20:29 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
> 06.01 00:20:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925)
> 06.01 00:20:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919)
> 06.01 00:20:29 [Server] INFO at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
> 06.01 00:20:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905)
> 06.01 00:20:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825)
> 06.01 00:20:29 [Server] INFO at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
> 06.01 00:20:29 [Server] INFO at java.base/java.lang.Thread.run(Thread.java:829)
> 06.01 00:20:29 [Server] Server thread/FATAL Error executing task on Server
> 06.01 00:20:29 [Server] Server thread/ java.lang.IllegalArgumentException: Duplicate id value for 252!
> 06.01 00:20:29 [Server] Server thread/ at net.minecraft.network.datasync.EntityDataManager.func_187214_a(EntityDataManager.java:86)
> 06.01 00:20:29 [Server] Server thread/ at yesman.epicfight.capabilities.entity.LivingData.onEntityConstructed(LivingData.java:78)
> 06.01 00:20:29 [Server] Server thread/ at yesman.epicfight.capabilities.entity.player.PlayerData.onEntityConstructed(PlayerData.java:51)
> 06.01 00:20:29 [Server] Server thread/ at yesman.epicfight.capabilities.entity.player.PlayerData.onEntityConstructed(PlayerData.java:38)
> 06.01 00:20:29 [Server] Server thread/ at yesman.epicfight.events.CapabilityEvent.attachEntityCapability(CapabilityEvent.java:35)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.eventbus.ASMEventHandler_53_CapabilityEvent_attachEntityCapability_AttachCapabilitiesEvent.invoke(.dynamic)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:601)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:595)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.common.capabilities.CapabilityProvider.doGatherCapabilities(CapabilityProvider.java:90)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:85)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapabilities(CapabilityProvider.java:64)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraftforge.common.capabilities.CapabilityProvider.gatherCapsAndRevive(CapabilityProvider.java:68)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraft.server.management.PlayerList.respawn(PlayerList.java:640)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraft.server.management.PlayerList.func_232644_a_(PlayerList.java:535)
> 06.01 00:20:29 [Server] Server thread/ at net.minecraft.network.play.ServerPlayNetHandler.func_147342_a(ServerPlayNetHandler.java:2054)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:30)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.network.play.client.CClientStatusPacket.func_148833_a(SourceFile:8)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:176)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:136)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:905)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:825)
> 06.01 00:20:33 [Server] Server thread/ at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
> 06.01 00:20:33 [Server] Server thread/ at java.base/java.lang.Thread.run(Thread.java:829)
> 06.01 00:20:34 [Disconnect] User Smerkll has disconnected, reason: Disconnected
> 06.01 00:20:34 [Server] Server thread/INFO Smerkll left the game`

**Comment by Yesssssman** [comment]
Please check all mods. This is definitely a mod incompatibility.
