### ISSUE TITLE
Epic fight mod shows the top of my arms when wearing armor, makes chestplate arms too into my character

### ISSUE THREAD

**Issue by H3xadecim4l** [Yesssssman/epicfightmod#860]
![2022-01-07_17 46 42](https://user-images.githubusercontent.com/97284639/148525520-d9b1aec4-65be-48a9-8f71-6e7d530450d4.png)

**Comment by Coach-mdl** [comment]
When you wear a shirt that's too small for you.

Have you got any mods that might change the player model in any way excluding epic fight?

**Comment by Yesssssman** [comment]
Normally it would render the new rigged model for vanilla armor. Check what mod causes this problem.
