### ISSUE TITLE
Mixin `MixinPacketBuffer` Breaks any Mod that uses ItemStack Capabilities 

### ISSUE THREAD

**Issue by Nyfaria** [Yesssssman/epicfightmod#863]
Mixin `MixinPacketBuffer` Breaks any Mod that uses ItemStack Capabilities 
because `readShareTag` is never being called so the Capabilities aren't being synched.

**Comment by SteamDoge9000** [comment]
can confirm, the mod nyf's quivers uses this method for UI and epic fight is breaking it, any time when it does render, if a bow fires or one of its keybinds to switch arrows breaks the UI indicators ability to grab stack info by the looks of it

a fix to this was attempted but failed to work, so could you please fix this on your (epic fights) end?

**Comment by Yesssssman** [comment]
I have to test more cause I can't expect what this change can bring other issues. Anyway, thanks.

**Comment by SteamDoge9000** [comment]
My God… The radio silence has ended

Thank you for finally responding

and please make sure that this can be done in the 1.16.5 version

Thanks

**Comment by Yesssssman** [comment]
I've worked on Ender dragon and Wither animation so I don't have time to look here. I'm so sorry.

**Comment by SteamDoge9000** [comment]
I see… It makes sense

I would also like to note that charge up of tetra items that are war forged do not work when you have a blocking system in place


I have someone that works with an add-on and they said that it might have to be something that you would have to change. just thought I should let you know

**Comment by SteamDoge9000** [comment]
Also you're good it's just we weren't expecting for radio silence I guess

**Comment by Yesssssman** [comment]
I'm not sure it can be fixed but I'll take a look at it. This mod changes numerous things so there's a flooding incompatibility.

**Comment by SteamDoge9000** [comment]
Also it seems that epic fight also has a very rare crash that occurs sometimes with the entities and causes the world to lock up? Idk

lastly epic fight NBT has features that allow for certain things such as NBT data in tetra tools to be modular to represent what sort of tool stat they have

It may be possible to just have any sort of blocking functionality to be disabled if it's a Tetris item; or add some sort of hook that could be used to disable blocking all together and allow for the right click button (use) to still have functionality

**Comment by SteamDoge9000** [comment]
*tetra

**Comment by SteamDoge9000** [comment]
This would allow for other mods to add some sort of ability to preserve right click functionality if for some reason epic fight causes a break in such

**Comment by SteamDoge9000** [comment]
To be completely honest the items in tetra use bows correctly probably because there is no sort of whitelist or ability to block with a bow so that might be something that could work? I'm not exactly sure to be honest

You can go ahead and make a separate issue on this if you want to keep things straight and I'll be willing to test for a fix when it comes available

(Some of the items in tetra also break render like holding the bow and crossbow during charge up, Yet another adon manages to fix that)

**Comment by Yesssssman** [comment]
Hm, ok. After a few tests, It was figured out that this mixin doesn't need anymore above the 1.17.1 version. It will be removed.

**Comment by SteamDoge9000** [comment]
Ment to send this here

Will it also be fixed for 16.5?

**Comment by Yesssssman** [comment]
I have to test but since 1.16.5 and 1.17.1 has different JDK version, I'd test it later.
