### ISSUE TITLE
The compatibilitie with other mod problem AoA, Spartan Weaponry

### ISSUE THREAD

**Issue by Keselka** [Yesssssman/epicfightmod#866]
In the spartan weaponry, and AoA3 the weapon type's like :
AoA3: Greatblade, and Hammer
Spartan Weaponry: Greatsword Hammer Warhammer Spear Halberd Pike Lance Glaive

Have an issue, that is all this weapon types after adding them into Epic Fight Mod config, dealse vanilla sweep attack even in "combat" mode, on the video it's clearly seen (especially on a greatsword) that the attacking happens earlier than the real hit by the sword. All of the weapon that have theese problem have a "Reach l" enchantment (in case of sword weaponry), or the reach atribute modifier (in case of aoa3)

That problem seems to be a bug that is connected to the "reach modifier", that is calculated above the base reach attack distance value, but it's may be a more worse problem (i am newbie in java).

So please fix that little problem, all other weapon works just fine, but these bug really make the game expirience much worse.

-Thanks for your respond

https://user-images.githubusercontent.com/31411975/149529805-1ba93c2c-f419-4c42-b0d9-1bd8b6c3f44c.mp4

d

**Comment by Keselka** [comment]
Minecraft 1.16.5
Forge 36.2.2
Epic Fight Mod 16.5.13

**Comment by Yesssssman** [comment]
For the first aid, use /gamerule doVanillaAttack false
