### ISSUE TITLE
Weapons not moving with the animation

### ISSUE THREAD

**Issue by SKoMonster** [Yesssssman/epicfightmod#867]
Weapons arent moving along with the animations, they're stuck to my character's side, and sometimes are small, I'm using the latest 1.16.5 version of the mod
My modlist:
![image](https://user-images.githubusercontent.com/98066289/150243342-ac63ca0f-2a48-4346-876c-8ef52a7a7fe9.png)
![image](https://user-images.githubusercontent.com/98066289/150243382-7855bf1d-363a-41b2-93d8-4808fb7a3031.png)

**Comment by Ripticor** [comment]
same here :(

**Comment by Yesssssman** [comment]
It's caused by the Wizard staff. Remove it or remove Epic FIght.
