### ISSUE TITLE
Items are not in hand

### ISSUE THREAD

**Issue by F3nDyss** [Yesssssman/epicfightmod#876]
Things aren't in hand, whenever I take whatever vanilla or mod thing is next to me and the animation is like I have that thing in hand
![2022-01-29_12 07 41](https://user-images.githubusercontent.com/98644289/151658668-2cb6fa5c-3f90-45ab-9ee8-6172f33a1f06.png)
-

Epic Fight mod16.5.1
Forge 1.16.5 36.2.23

**Comment by Humidsquirrel** [comment]
I'm having the same gltich

**Comment by The-Shadow986** [comment]
apparently other people have had this problem and it is caused by the wizard staff mod

**Comment by Yesssssman** [comment]
Sorry but Epic Fight and Wizard Staff is incompatible now. You have to remove one.
