### ISSUE TITLE
Skill books deletes wrong items

### ISSUE THREAD

**Issue by ZEkA10000** [Yesssssman/epicfightmod#877]
When I learn skill from book with secondary hand it deletes item in main hand

https://user-images.githubusercontent.com/25690631/151676404-3df7392d-f6fd-4cb1-8217-c10697593b79.mp4

EpicFight v16.5.13
Minecraft 1.16.5
Forge v36.2.22

**Comment by Yesssssman** [comment]
Fixed in 17.1.12
