### ISSUE TITLE
weapon_type:KATANA applied the SWORD skill but not katana

### ISSUE THREAD

**Issue by yi-lan** [Yesssssman/epicfightmod#878]
my dear creater，i come from China，So I'm not sure my English can be understood
I use the mod with Minecraft 1.12.2 and version 2.2.8，I modified the config file ，Want more weapons get Epic Fight，but the weapon_type:KATANA applied the SWORD skill （power and rotate cut）without katana（Draw a knife and cut）

**Comment by Yesssssman** [comment]
Sorry but 1.12.2 is not supported anymore.
