### ISSUE TITLE
[Suggestion] Weapon suggestions

### ISSUE THREAD

**Issue by gbhosl** [Yesssssman/epicfightmod#88]
Hey, first of all this mod is amazing so I would like to give my thoughts on what to add.

The few weapons I can think of that moves in a different style compared to other weapons will be the following:

Rapier (more thrusting, less slicing)

Warhammer/sledgehammer (Greatsword animation feels too fluid for it)

Scythe (spear animation feels off when using it)

Claws (like fist but more overhead arcing swings)

Oodachi (less 1 hand style katana, but more 2 hand style swordplay)

**Comment by Ecderebi** [comment]
Cool ideas...

**Comment by Yesssssman** [comment]
Ooook... I would make a major weapon update later.

**Comment by Aboslut** [comment]
The scythe is a really great idea
