### ISSUE TITLE
Am I the Only One Who has this glitch

### ISSUE THREAD

**Issue by Urmomgaybruh** [Yesssssman/epicfightmod#882]
Weapons arent swinging like in the videos its swinging like regulary minecraft

**Comment by Urmomgaybruh** [comment]
and its all weapons
the ones from the mod and the ones from vanilla

**Comment by DarkScorn** [comment]
You have to go into battle mode with a button, change it in controls.

**Comment by Yesssssman** [comment]
What mods did you install?
