### ISSUE TITLE
Katana sheath independent of weapon held | 1.16.5

### ISSUE THREAD

**Issue by nikorue** [Yesssssman/epicfightmod#887]
is there a way to make the Katana stay on body when it's in the hotbar/inventory instead of when it is held in the main slot?

**Comment by Yesssssman** [comment]
You may can use backtools mod

**Comment by nikorue** [comment]
as in on the side and not on the back?

**Comment by Yesssssman** [comment]
Oh, it's only located in your back. What you want is not implemented yet.
