### ISSUE TITLE
weapon compatibility for TiC & in general | 1.16.5

### ISSUE THREAD

**Issue by nikorue** [Yesssssman/epicfightmod#888]
Sadly the video for "adopting" the compatibility wasn't informative enough for my low iq brain, how exactly can you/I make (for example)Tinker's construct weaponry compatible? How can I make (short/long/vanilla)bows compatible?

**Comment by Yesssssman** [comment]
Everything is described in the video. Please watch it multiple times and I'm sure you can understand it.
