### ISSUE TITLE
Replay Mod

### ISSUE THREAD

**Issue by Keonhaplayz** [Yesssssman/epicfightmod#89]
Hey so I really wanted to make a cinematic fight scene using Replay mod but I ran into a bit of a problem. The attack animation for each weapon doesn't show up when you go back to the recorded clip however for some reason the movement animation like walking, running, and rolling seems to be captured just fine. Is there any way I could fix this or if not can you add a patch to the 1.12.2 version? I see a lot of potential for cinematic videos with this mod and I know you were suggested to use replay mod during your 1.14.4 mod showcase (though the forge version of replay mod can only go up to 1.12.2 but I know that you're planning to eventually backport everything once you're finish with the current version anyway).

**Comment by Yesssssman** [comment]
What an incredible timing. I uploaded the backported version 1.12.2 now, would you like to experiment?

**Comment by Tennik** [comment]
The same troubles there with 1.12.2, but I have some other troubles too, I described them here:
https://github.com/Yesssssman/epicfightmod/issues/91

**Comment by Keonhaplayz** [comment]
Hello, I tried the backported version for 1.12.2 and the problem still
remains the same. I believe that a patch might have to be made or some kind
of change in the config file on how replay mod captures animations. It
seems that movement animations and weapon animations seem to be captured
differently for some reason. If you want, here is my
discord: Keonhaplayz#9247 and I can help you test out a few patches or
changes in the config file as I want this to be fixed as soon as possible.
Since this would be only for the 1.12.2 version of Epic Fight Mod, I hope
we can find a solution fairly quickly. I believe that the Epic Fight Mod
could bring a new perspective in cinematics to the community and it would
be of great use in your future showcases of the mod. Anyway message me on
discord and I'll try to get back to you as soon as I can since my time zone
is EST. If you have a more preferable way of communication than that is
also fine with me.
