### ISSUE TITLE
[Urgent Issue] This needs to be fixed

### ISSUE THREAD

**Issue by Aronforester** [Yesssssman/epicfightmod#893]
Update to 1.18 plzzzzzz , sorry for the clickbait by the way 😅

**Comment by Augusto2103** [comment]
Ngl, clickbait ain't cool.

**Comment by Aronforester** [comment]
> Ngl, clickbait ain't cool.

True but 1.18 update is cool

**Comment by Yesssssman** [comment]
Refer to FAQs in mod description
