### ISSUE TITLE
[Feature/Request]

### ISSUE THREAD

**Issue by Aronforester** [Yesssssman/epicfightmod#895]
Could it be possible to add animations outside of battle mode where the player punches to break blocks and holds the axe the right way to chop down a tree instead of flailing his arms and swings the pickaxe like he's trying to mine and using the shovel how people shovel dirt and using the hoes by swinging it into the ground and pulling it back to himself and could u add a drinking and eating animation plzzzz I know this alot to ask but I hope you'll consider putting it on your list of future plans.

**Comment by Yesssssman** [comment]
I think this is not fit with my development direction.
