### ISSUE TITLE
Compatability issue with Optifine and immersive portals

### ISSUE THREAD

**Issue by naxmaardur** [Yesssssman/epicfightmod#9]
whenever I use this mod with both OptiFine_1.16.4_HD_U_G5 and immersive portals it crahses giving a null pointer exception for this mod on the attack key bind "at maninhouse.epicfight.client.events.engine.ControllEngine.attackKeyPressed(ControllEngine.java:151) ~[?:1.0] {re:classloading,pl:runtimedistcleaner:A}" 
and some times a ticking entity error

epicfight + optifine works
optifine + immersive portals works
epicfight + immersive portals also works but all 3 together crashes the game

**Comment by Yesssssman** [comment]
Forge version?

**Comment by naxmaardur** [comment]
I knew I forgot something
1.16.4 - 35.1.37
I also saw that you updated the mod after I made the post so I downloaded that one.
still crashes with the same error

**Comment by naxmaardur** [comment]
downgraded forge and it works now but only with V2.0.2 of the mod
your mods amazing and I appreciate the frequent patches keep up the good work mate
