### ISSUE TITLE
Option to disable the new animation of certain mobs?

### ISSUE THREAD

**Issue by jonylentzmc** [Yesssssman/epicfightmod#90]
Hi, first of all, thank you for making this mod, it's really well made and gives a new life to the old Minecraft combat system!
Is there an option to disable the new animation of certain mobs? I have checked the config file and could not find it...
I would like to use this mod combined with spiders 2.0, it works fine, no crashes but since this mod and the other replace the animation for spiders, what happen is the animations from this mod overrides the spider 2.0 animation. This make upside-down spiders render as right side up which is visually weird... 
I am not sure if it is something hard to implement but if you could add this option to the config file, I would be grateful

![2021-03-23_03 51 57](https://user-images.githubusercontent.com/76884929/112106176-18a3c380-8b8c-11eb-8389-3f53d6d7905c.jpg)
![2021-03-23_03 39 09](https://user-images.githubusercontent.com/76884929/112106290-41c45400-8b8c-11eb-9b2b-2e32c6777c98.jpg)

**Comment by n3kyl3** [comment]
Yes this is exactly what i want also because i have 2 texture packs that redesign villagers, pillagers, and zombies but the epic fight mod over rules them which sucks.
