### ISSUE TITLE
Does guard not work on magma?

### ISSUE THREAD

**Issue by marcusurdaddy** [Yesssssman/epicfightmod#901]

**Comment by marcusurdaddy** [comment]
https://streamable.com/jdtm00

**Comment by marcusurdaddy** [comment]
1.16.5 magma idk if it works or not guard is acting weird and also im not getting any ultimate when hitting enitys someone pls help

**Comment by Yesssssman** [comment]
I recommend using the pure Forge server. I have received a similar issue but it took almost 3 weeks to find a reason.
