### ISSUE TITLE
Remove Mob Anim

### ISSUE THREAD

**Issue by danrney** [Yesssssman/epicfightmod#903]
How do I remove combat from mods and leave only the Player with Epic Fight?

**Comment by JackPunk701** [comment]
I really need it too. I use the Fresh Animations mod and with the EpicFight mod I have problems with mob models. Please drop the jar file without animation, textures and everything else that is directly related to mobs.

**Comment by Yesssssman** [comment]
There's no way to disable a specific mob's animation for now but it will be the feature of the library mod.
