### ISSUE TITLE
.jem parts in resource packs don't work with changed mobs.

### ISSUE THREAD

**Issue by UDP-14N** [Yesssssman/epicfightmod#906]
.jem parts in optifine resource packs don't apply to hostile mobs, rendering a lot of modern packs broken.
as you can see in the images below, the textures work, assumedly because EFM models draw from the vanilla mobs' textures, but the resource pack models don't transfer over. I have no idea if it's even possible to integrate these systems because EFM seems pretty custom model/animation heavy, but I'd definitely like to be able to use resource packs with the mod.
*Fresh Animation Pack*
![image](https://user-images.githubusercontent.com/101961605/159204625-6bc4ec43-68bb-4474-aa8a-1e3b4336df81.png)
*Cute Mob Models Pack*
![image](https://user-images.githubusercontent.com/101961605/159204699-2a69b6af-3938-4bdc-a2a9-c63bebde0053.png)
*Journey Pack*
![image](https://user-images.githubusercontent.com/101961605/159204934-0e2563a6-a999-40cd-846a-2a8dac1c5afe.png)

**Comment by Yesssssman** [comment]
It is impossible to fix if those resourcepacks use custom models like you can't use them simultaneously. Only texturepack/resourcepack that uses the same model format as vanilla would be compatible with Epic Fight.
