### ISSUE TITLE
Attack Animations Not Working with Sodium/Rubidium/Magnesium

### ISSUE THREAD

**Issue by GonKiIlua** [Yesssssman/epicfightmod#908]
Attack animations with any kind of weapons aren't working with Rubidium (sodium forge port) installed.  

This also goes for roll and guard animations. Replacing Rubidium with Optifine fixes the issue and animations work fine again. Is there an incompatibility with sodium, or a dependency on Optifine? 

Using latest version of 1.16.5 of Epic Fight, Forge version 36.2.20.

**Comment by un-hunt** [comment]
There is a dependency on OpifFine, which is not only an optimization mod, but also has a very nice configuration of custom animations, which is used in Epic Fight. Also, Sodium is a Fabric mod, so it won't be compatible with any Forge mod, including Epic Fight.

**Comment by FlameyFaucet** [comment]
sodium has a forge port
that being said this dependency on optifine may not have been accounted for sodium too. you could try asking the sodium devs instead and see how they handle it, otherwise it may just not work with epic fight

**Comment by MetalKnight56** [comment]
Denied issue, 1.16.5 no longer will be supported.
