### ISSUE TITLE
New Issues with updated 1.12.2 version

### ISSUE THREAD

**Issue by Tennik** [Yesssssman/epicfightmod#91]
I have installed the latest version of mod, but got new issues.
1. Spamming errors in my server console on the start (from line 429 to 2174):
[latest.log](https://github.com/Yesssssman/epicfightmod/files/6187535/latest.log)
2. Battle animations with all weapons looks weird
3. No more battle GUI, animations and functionality for Basic Attack, Dash Attack, Rolling, Weapon Special Attack
4. Stray Pants are shown as Hat slot, not an Legs and I can`t wear it

**Comment by Yesssssman** [comment]
Can you post a picture or video for 2 and 3?

**Comment by Tennik** [comment]
Yeah, sure. Also, Skill book doesn`t work and there are some troubles with localisations of tabs and items:
https://dropmefiles.com/zHlHY

**Comment by Yesssssman** [comment]
Hey! you have to press 'R' and goes to the battle mod!

**Comment by Tennik** [comment]
Oh, sorry, it's really my bad! I forgot that this key is already taken by another mod. I changed it and now it's ok! But fight with two-handed sword without battle mod looks really funny, but in battle mod it's awesome!
What about those weird spam errors in server console, Stray Pants and Skill Book?

**Comment by Tennik** [comment]
That's so cool you fixed issue with Stray armor and armor from Ice&Fire mod looks almost correct, just some particles are not shown when you wear an armor, but that is much better when it is displayed weird at all (like in Mo'Bends mod)
There are no more crashes of client and server, at least for now. Thanks!
But can you also check my errors in server console? There are still there...
