### ISSUE TITLE
Epic Fight not working with Spartan Weaponry

### ISSUE THREAD

**Issue by bluvuuu** [Yesssssman/epicfightmod#911]
So i watched a video on how to configure Spartan Weaponry with Epic Fight, but it's just straight up not working. whenever i put in what i typed into the config, this is the error i get. any solutions?

<img width="960" alt="image" src="https://user-images.githubusercontent.com/102454523/160267783-bc238513-f368-4558-b62e-163802978b57.png">

**Comment by un-hunt** [comment]
If you are playing on 1.16.5, try [this](https://www.curseforge.com/minecraft/customization/epic-fight-spartan-weaponry/files) config.

**Comment by Yesssssman** [comment]
Do you have a crash repo?

**Comment by bluvuuu** [comment]
No not anymore, I managed to fix it with the config that the other user sent me. Though, I still do have a problem where if I create my own my config then it says "epic fight has failed to load correctly" or something like that.

**Comment by Yesssssman** [comment]
It would leave a message in a log file if Minecraft failed to load.

**Comment by TotallyCooki** [comment]
I've gotten this error in the past when I had a double entry, could be the cause.
