### ISSUE TITLE
Skills lost on death

### ISSUE THREAD

**Issue by Brown-bricks** [Yesssssman/epicfightmod#915]
I used the roll skill, died shortly after, and found roll no longer worked until reapplying it with the book.

Version 16.5.13 was in use at the time, with several other mods available on request.

**Comment by Thedarkcat12** [comment]
I'm having the same issue, it's leading me to not using them until this gets patched.

**Comment by un-hunt** [comment]
Is KeepSkills set on true? There is a /gamerule KeepSkills , which is false by default. Just change it. Also I wouldn't recommend to write about things like that right on GitHub, as solves of most issues you might have are already on CurseForge.
