### ISSUE TITLE
Wings mod + EFM Compatibility  1.16.5

### ISSUE THREAD

**Issue by n0itLT** [Yesssssman/epicfightmod#918]
Is there any way you can change the flying animation to creative mode? The animation for flying won't work and shows the default EFM creative flying ( walking ).

**Comment by n0itLT** [comment]
Trying to get flying animation for EFM for wings mod. I don't like the idea of switching to mining mode (having default Minecraft animation) for flying. The animation looks horrible while in mining mode. Are we able to add or change the default flying mode for Epic Fight Mod? Or do something for Wings mod to have its flying animation activate when in flying mode?

**Comment by Yesssssman** [comment]
I won't support any direct compatibility patch with other mods. Instead, I'll port the library mod that is useable to other developers can access the Epic Fight source code. There are too many kinds of mods and I can't handle all of them.
