### ISSUE TITLE
[1.16.5, v16.5.13] World stuck at 100% generation whenever this mod is installed

### ISSUE THREAD

**Issue by Catomax262** [Yesssssman/epicfightmod#923]
It just gets stuck, and idk what does it have to do with worldgen. Perhaps it's player and mob rendering? This happens EVERY time i install the mod. It does not get stuck when i don't install it. Even restarting Minecraft doesn't help. It just stays in this same screen for like 20 minutes with no change.

**Comment by Catomax262** [comment]
Also, here's my almost 300 mods modlist: https://pastebin.com/83dik5b1

**Comment by Yesssssman** [comment]
I need a crash repo

**Comment by Catomax262** [comment]
How do I get those?

**Comment by Catomax262** [comment]
Also, I have seen and there's no new crash reports on the folder, let me check

**Comment by Yesssssman** [comment]
.minecraft>logs>debug.log or latest.log

**Comment by Catomax262** [comment]
Ok. Finally got it. Here's the log: https://www.mediafire.com/file/ujwge59bw5sk0ab/latest.log/file
Pastebin had a size limit so i had to upload it this way

**Comment by MetalKnight56** [comment]
> Ok. Finally got it. Here's the log: https://www.mediafire.com/file/ujwge59bw5sk0ab/latest.log/file Pastebin had a size limit so i had to upload it this way

https://mclo.gs/MLyUlWU - I've uploaded it to mclo.gs so it's permanent an easier for the author to see it :)

**Comment by Catomax262** [comment]
So... Anything new?

**Comment by Yesssssman** [comment]
It says the game can't look up your profile.

```
Couldn't look up profile properties for com.mojang.authlib.GameProfile@42e61229[id=428b3709-43b4-11ea-9ed6-b42e996a7d7a,name=MaxiCato62,properties={},legacy=false]
```

Do you sure that the crash occurred by Epic Fight? or have you attached the wrong repo?

**Comment by Catomax262** [comment]
Yeah. It plays normally until I install Epic Fight. I have been installing my mods one by one in conjunction with Epic Fight, and it seems to be that one of my mods is causing it to crash. Wdym by repos?

**Comment by Yesssssman** [comment]
I mean, I can't find any clues In the crash report you posted that Epic Fight caused a crash. Could you check if this crash repo was made when checking the mods one by one?

**Comment by Catomax262** [comment]
If I remember, it was just before checking all of the mods. I'm still testing the mods this way, so I will notify you when I am done with this testing.

Oh and also for now it runs normally. But that means there's plenty of mods to go. Remember, I'll notify you when I end the testing.

**Comment by Catomax262** [comment]
And also, the comment I made before this one was before I started testing the mods.

**Comment by Catomax262** [comment]
Yeah. It is more likely to be a mod that is causing this. I came back to test and it's still running normally.

**Comment by Catomax262** [comment]
If it doesn't load, then i'm done.

**Comment by Catomax262** [comment]
I ended testing the mods. In the end, it was the Custom NPCs mod which made this crash.
