### ISSUE TITLE
When i go to sleep, the model of my character is completly f*ed up

### ISSUE THREAD

**Issue by EmanPower** [Yesssssman/epicfightmod#926]
![Immagine 2022-04-10 051735](https://user-images.githubusercontent.com/74879830/162599873-6d1a54cd-df6c-4b33-b80d-e84dde3d21b8.png)
This is what i see everytime i go to sleep, this happens only when EFM is installed

**Comment by Yesssssman** [comment]
Fixed in 17.1.13, 18.0.1
