### ISSUE TITLE
Epic Fight ignores pet invulnerability

### ISSUE THREAD

**Issue by LocoPineapples** [Yesssssman/epicfightmod#930]
With Domestication Innovation, there's a feature where your pets can not longer be hurt by you unless you shift click them, making fighting with them much easier and more viable. If you attack them in Fight Mode though, it goes right through that and hurts them anyway, making it easy to kill them by accident. If in mining mode, pets are unable to be hurt by their owners as usual. Thanks!

**Comment by MetalKnight56** [comment]
Closing issue as fixed on 18.5.0.1 - available only for Closed Beta Access users
