### ISSUE TITLE
epic fight config dissapearing epicfight.toml

### ISSUE THREAD

**Issue by MetalKnight56** [Yesssssman/epicfightmod#932]
So when creating a config on epicfight.toml, not only does the file is empty but everytime i start my minecraft the config is deleted and nothing happens. 

Here's an image showing it before i load my world 
![image](https://user-images.githubusercontent.com/77132244/163067070-189a8dc0-7e38-4e70-8667-641544cbc410.png)

and Here's an image showing it after
![image](https://user-images.githubusercontent.com/77132244/163067174-6f1e453d-2bf7-4496-bd59-12c9bf2a7765.png)

**Comment by Yesssssman** [comment]
The config file is deprecated. It is too buggy and hard to figure out what the problem is. Instead, use Datapack to avoid the problems
