### ISSUE TITLE
Compatibility Issue with Mowzie's Mobs

### ISSUE THREAD

**Issue by ErikVandervelde** [Yesssssman/epicfightmod#933]
![IMG20220412211026](https://user-images.githubusercontent.com/98760465/163091913-c794b4f5-2fc7-44c9-967a-8e825743a53d.jpg)

Rendering issue when placing the gauntlet on the player's off hand

**Comment by BobMowzie** [comment]
To shed more insight on this, I flip the gauntlet model by hiding/showing either the left hand or right hand models. I do this in this function:
`@Override
    public void func_239207_a_(ItemStack itemStack, ItemCameraTransforms.TransformType transformType, MatrixStack matrixStack, IRenderTypeBuffer bufferIn, int combinedLightIn, int combinedOverlayIn) {
        if (!modelProvider.getAnimationProcessor().getModelRendererList().isEmpty()) {
            if (transformType == ItemCameraTransforms.TransformType.THIRD_PERSON_LEFT_HAND ||
                transformType == ItemCameraTransforms.TransformType.FIRST_PERSON_LEFT_HAND) {
                modelProvider.getBone("root").setHidden(true);
                modelProvider.getBone("rootFlipped").setHidden(false);
            }
            else {
                modelProvider.getBone("root").setHidden(false);
                modelProvider.getBone("rootFlipped").setHidden(true);
            }
        }
        super.func_239207_a_(itemStack, transformType, matrixStack, bufferIn, combinedLightIn, combinedOverlayIn);
    }`
    
    which is overridden from the original method in Geckolib's GeoItemRenderer. I suspect that when rendered on the Epic Fight Mod player model, the item renderer isn't calling this specific function.

**Comment by Yesssssman** [comment]
Could you let me know the version?

**Comment by BobMowzie** [comment]
1.16.5
Mowzie’s Mobs 1.5.23
Unsure what Epic Fight Mod version

**Comment by Yesssssman** [comment]
Sorry for the late reply, I found that I only gave the transform type "THIRD_PERSON_RIGHT_HAND" even tho the item is being held in offhand. I'll fix this 1.18.2 first then fix 1.16.5

**Comment by Yesssssman** [comment]
Fixed in 16.6.0
