### ISSUE TITLE
The game crashes by pressing esc

### ISSUE THREAD

**Issue by wushen233** [Yesssssman/epicfightmod#934]
[debug.log](https://github.com/Yesssssman/epicfightmod/files/8481072/debug.log)
[latest.log](https://github.com/Yesssssman/epicfightmod/files/8481074/latest.log)
[游戏崩溃前的输出.txt](https://github.com/Yesssssman/epicfightmod/files/8481075/default.txt)

**Comment by Yesssssman** [comment]
hey, when does this problem occurs?
