### ISSUE TITLE
[ Enhancement ] Create a discord server or forum

### ISSUE THREAD

**Issue by MetalKnight56** [Yesssssman/epicfightmod#936]
I know this is not an issue related to the mod itself, but i really would appreciate if there would have an easier way to talk with the community and share stuff, epic fight is becomming a bigger mod every day, and i think a discord server or something like that would boost up your mod.

**Comment by wushen233** [comment]
> 我知道这不是与模组本身有关的问题，但如果有更简单的方式与社区交谈和分享东西，我真的很感激，史诗般的战斗每天都在成为一个更大的模组，我认为不和谐的服务器或类似的东西会提升你的模组。

https://discord.com/channels/955784714264932362/960306389497053337

**Comment by MetalKnight56** [comment]
i did not understand, like there's nothing at this discord link

**Comment by MetalKnight56** [comment]
was this supposed to be the discord invite ?

**Comment by wushen233** [comment]
> 这应该是不和谐的邀请吗？

Then you go to the mod post there is a link below

**Comment by MetalKnight56** [comment]
found
thanks !
