### ISSUE TITLE
Documents for creating datapack

### ISSUE THREAD

**Issue by truemogician** [Yesssssman/epicfightmod#941]
I'm trying to use the config file to modify Epic Fight's attributes of weapons from other mods in my own modpack (Minecraft 1.18.2+Forge 40) today and face the same problem as #932   
You recommend using datapack, but I cannot find any document or wiki that explains how to make one that plays the same role as the deprecated config file.  
May you add some documents for modpack makers like me to build a datapack that works like the config file?

**Comment by VanilaBOI** [comment]
Yesman is working on a library mod to make it more easier to modify it but in the mean time, did you look at this video he made. I'm guessing yes because you know that you should use datapacks and not the config anymore. https://youtu.be/JNpahwjriac

**Comment by Yesssssman** [comment]
https://www.youtube.com/watch?v=JNpahwjriac&t=60s

**Comment by truemogician** [comment]
Thanks! This video is a great tutorial and I've made my datapack that works perfectly. Maybe you could add this link to curseforge to let more people know 😁

**Comment by Yesssssman** [comment]
well it's already linked in the FAQ tab in curseforge description I guess
