### ISSUE TITLE
Suggestion for gamerules

### ISSUE THREAD

**Issue by xblackshadow26x** [Yesssssman/epicfightmod#943]
Hi, I'm a massive fan of your mod. I just want to give a suggestion of making the gamerules a config option instead, like do vanilla attack and keep skills. This is because its a lot easier for modpack developers to change them because gamerules are a lot harder to access in general as they need to be applied in worlds.

Also I wanted to ask am I allowed to create an addon for this mod?

**Comment by Yesssssman** [comment]
Idk, why it's needed since it could prevent all players using the modpack from keeping their skills after the death or using the vanilla attacks.

Btw you're free to use the code of Epic Fight but I recommend you wait until I release the library mod. It would help make an addon a lot easier.

**Comment by xblackshadow26x** [comment]
Tbh that’s exactly what I want. I’m going for a dark souls themed combat with a few twists and I just don’t want vanilla attacks at all, so it would be a lot easier for me to just have a config option to enable or disable it.

**Comment by Yesssssman** [comment]
I think we have to leave those options to the players. I also don't like spamming the vanilla attacks when Epic Fight is installed but there are still many people who want to use a vanilla attack. So you can still control the server on your own or you're having an op but don't try controlling all users using your modpack.

**Comment by Overlooks** [comment]
Its tedious to make a new world and switch it to creative mode with cheats on just to type two of the following commands that i think should be mandatory anyways,. /gamerule doVanillaAttack false and /gamerule keepSkills true

**Comment by Yesssssman** [comment]
you can set the gamerules when making a new world. you don't have to change to creative mode.

**Comment by Overlooks** [comment]
game rules dont save from world to world sadly and mods that i found that do save gamerules from world to world tend to not support epic fight mod or destroy the existing gamerules set in the modpacks games. +  using vanilla attacks is cheating since epic fight mobs actually has a set distance to attack making it just click and walk back ultimately destroying the purpose of this amazing mod. if its not clear enough i want my friends to suffer ;). cant play with them ping issues so i decided to make a modpack for them.

**Comment by xblackshadow26x** [comment]
I agree with Overlooks. Vanilla attacks don’t really work in specific modpacks built to work with epic fight and having a config option is just easy for us to change rules globally. Besides if players don’t want it then they can easily access config and disable. But ultimately it should be initially up to the creator of the modpack as it’s their modpack and they should have the ability to globally change things like vanilla attack and keepskills. If certain players don’t like it they can simply just change in config or just play a different modpack.

**Comment by Yesssssman** [comment]
Hm, okay, but I think the config value shouldn't take precedence over the gamerule. In other words, players can still use vanilla attack when the gamerule doVanillaAttack is set to true even tho you set the doVanillaAttack false in the config file. It would be just the default value for the gamerules. How about this middle ground?

**Comment by VanilaBOI** [comment]
That would be great.

**Comment by xblackshadow26x** [comment]
Yes that's honestly perfect
