### ISSUE TITLE
Client / Server crash when compile the code from Github

### ISSUE THREAD

**Issue by Flashback083** [Yesssssman/epicfightmod#944]
Hello ! First to all thanks again for creating this mod, the feedback is very impressive!

Version : 
1.16.5

Explanation : 
I wanted to test the Dodge fix commit so i compiled the code from Github, and when i try to load the compiled jar to my mods folder i got theses crash report : 
Client side : https://gist.github.com/Flashback083/10031018da1019a4ab66dc7f1852aeae

Server side : https://gist.github.com/Flashback083/b0dcde57e190751ecada8f3c2c0521d3

How reproduce : 
Client side : Just create a new world
Server side : Just start the server

Modpack : i use the Shattered Ring modpack available on CurseForge -> https://www.curseforge.com/minecraft/modpacks/shattered-ring

Edit : Got the crash even with only EpicFight mod installed (still the builded on from Github)

**Comment by Yesssssman** [comment]
Why you're using an old version of epic fight?

**Comment by Flashback083** [comment]
Its not an old version its just the name i got when i compiled, provided by the build.gradle

**Comment by Flashback083** [comment]
I have this build.gradle if it can help : 
https://gist.github.com/Flashback083/9438098e20a4b4f483c0da4c6fcef160

**Comment by Yesssssman** [comment]
I guess you're using an old code since I haven't updated the latest project on Github.

**Comment by Flashback083** [comment]
I use a code that have been push from 21 days ago, but it might be old indeed haha

**Comment by Flashback083** [comment]
So i guess my issue is solved, i just need to wait a runnable build to be push on github ^^

**Comment by Yesssssman** [comment]
Do you need only the 1.16.5 code? since it's still a relatively old code because I'm working on 1.18.2 now

**Comment by Flashback083** [comment]
Yep, only 1.16.5 for now ! Thats fair 1.18.2 is the new target, 1.16.5 seems to be enough stable for now, just wanna mess with the 1.16.5 code and also the dodge fix which seems cool !

**Comment by Flashback083** [comment]
Seems good with latest push, thanks ! <3
