### ISSUE TITLE
[Request] [1.16.5]Compatible with different mods and equipment models

### ISSUE THREAD

**Issue by XiFengXF** [Yesssssman/epicfightmod#946]
serious problem:
Armor: Full body (especially dungeon gear), head and some breastplates
Accessories: Necklace First Person Model Clash, Hands, Shoes, Head Model Clash
Weapons: Hand-worn class and shield
![2022-04-19_20 11 09](https://user-images.githubusercontent.com/97110012/164011216-6375310c-c5b2-4274-8690-3feac2844f3a.png)
![2022-04-19_20 34 37](https://user-images.githubusercontent.com/97110012/164011242-a8c1c2c0-ff92-4428-aa98-3ec0139e4f1f.png)
![2022-04-19_20 34 54](https://user-images.githubusercontent.com/97110012/164011250-998d09cf-c110-414d-8a2e-5a4f90f7ca42.png)
![2022-04-19_20 35 18](https://user-images.githubusercontent.com/97110012/164011264-31967840-a065-4ec0-9bde-6e9a49639838.png)
![2022-04-19_20 09 21](https://user-images.githubusercontent.com/97110012/164118428-f50ba6d7-5a6e-4784-82aa-f67995c4d87c.png)
![2022-04-19_20 06 09](https://user-images.githubusercontent.com/97110012/164118440-d0e1a1df-684b-4696-89fb-6b4008a31bfa.png)
![2022-04-19_20 07 05](https://user-images.githubusercontent.com/97110012/164118445-e28a96c4-0694-4f0a-b9b8-4af22006a3db.png)
![2022-04-19_20 08 53](https://user-images.githubusercontent.com/97110012/164118456-4f0c0bce-7eee-44f1-b1c6-6f7fedf2d0be.png)
![2022-04-19_20 08 35](https://user-images.githubusercontent.com/97110012/164119049-1947d0e2-6cbf-45c0-90c2-e2654adec379.png)
![2022-04-19_20 10 26](https://user-images.githubusercontent.com/97110012/164119071-6645bda9-7470-494f-a3fa-2c473b507ae5.png)
![2022-04-19_19 37 43](https://user-images.githubusercontent.com/97110012/164119077-722e8405-ec74-4f39-8ad7-06cf5ac08180.png)
![2022-04-20_07 47 19](https://user-images.githubusercontent.com/97110012/164119125-6d3579ad-dc97-4269-b219-9210d5d7c504.png)
![2022-04-19_21 08 24](https://user-images.githubusercontent.com/97110012/164119145-61296875-8400-4529-9ec5-bcf5baff58e4.png)
![2022-04-20_07 44 22](https://user-images.githubusercontent.com/97110012/164119146-9c4e92e9-a3a1-4da4-835f-1efa85040281.png)
![2022-04-20_07 44 25](https://user-images.githubusercontent.com/97110012/164119150-6950a7bc-8969-4f09-afe1-c5b95e894bd6.png)
Mod link: 
https://www.curseforge.com/minecraft/mc-mods/omnis
https://www.curseforge.com/minecraft/mc-mods/atum
https://www.curseforge.com/minecraft/mc-mods/savage-and-ravage
https://www.curseforge.com/minecraft/mc-mods/environmental
https://www.curseforge.com/minecraft/mc-mods/scuba-gear
https://www.curseforge.com/minecraft/mc-mods/dungeons-mobs
https://www.curseforge.com/minecraft/mc-mods/dungeons-gear
https://www.curseforge.com/minecraft/mc-mods/the-conjurer
https://www.curseforge.com/minecraft/mc-mods/pyromancer
https://www.curseforge.com/minecraft/mc-mods/artifacts
https://www.curseforge.com/minecraft/mc-mods/relics-mod
https://www.curseforge.com/minecraft/mc-mods/alexs-mobs
https://www.curseforge.com/minecraft/mc-mods/stalwart-dungeons
https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm
ps：This mod is very handsome, I also hope that the equipment in the mod pack is also compatible with epic figh
![2022-04-19_20 58 41](https://user-images.githubusercontent.com/97110012/164119323-cf6ff010-573b-4de0-b482-811f6cbddb91.png)
![2022-04-19_21 03 41](https://user-images.githubusercontent.com/97110012/164119337-9e50ac4c-9167-4b00-be7f-a5a91eb12422.png)

t

**Comment by MetalKnight56** [comment]
That is already beein worked on, with the library update, making mods compatible with efm should be easier. And this has already been reported.

**Comment by MetalKnight56** [comment]
Fixed dungeon gear here: https://www.planetminecraft.com/data-pack/epic-fight-dungeon-gear-patch/
