### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by TacocaTYT** [Yesssssman/epicfightmod#949]
https://pastebin.com/Lq8mqsJY

game crashed while i was tryong out the attack speed on my new modular knife

**Comment by MetalKnight56** [comment]
This is a dupe report. You've already reported this issue on the dc server, there's no need to post on both places.
![image](https://user-images.githubusercontent.com/77132244/164359049-ea16e6c8-612f-498c-8eac-fd78e3677014.png)

**Comment by TacocaTYT** [comment]
my apologies, figured it was better to report on github so it could be tracked
