### ISSUE TITLE
Can't display the second layer of the multi-layer armor resourcepacks

### ISSUE THREAD

**Issue by D0704Wong** [Yesssssman/epicfightmod#950]
Before epic fight mod
![image](https://user-images.githubusercontent.com/104116101/164361358-77e36420-d26f-4574-a00b-18c26eb3ed51.png)
After epic fight mod
![image](https://user-images.githubusercontent.com/104116101/164361645-9b973e76-df73-49f8-9902-add633823582.png)

Epic fight mod : EpicFight-18.0.3-beta
Resourcepacks : 1.18.2-Dokucraft-Light
Forge : 1.18.2-forge-40.1.0

**Comment by Yesssssman** [comment]
Have you read #536?

**Comment by D0704Wong** [comment]
> Have you read #536?

because that is not a mod 3d armor that just is the resourcepacks armor has two-layer so I don't know is the same bug of 3d armor or just other thing

**Comment by Yesssssman** [comment]
![image](https://user-images.githubusercontent.com/79469058/164456612-f1a0f285-dcbf-44a6-952b-c7e17c2b4a76.png)

epicfight armor doesn't have a second layer. I'll fix this if vanilla Minecraft supports the second layer.

**Comment by D0704Wong** [comment]
> ![image](https://user-images.githubusercontent.com/79469058/164456612-f1a0f285-dcbf-44a6-952b-c7e17c2b4a76.png)
> 
> epicfight armor doesn't have a second layer. I'll fix this if vanilla Minecraft supports the second layer.

get it

**Comment by Yesssssman** [comment]
Fixed in 18.1.5
