### ISSUE TITLE
Little Logistics crash with locomotive engines

### ISSUE THREAD

**Issue by cleannrooster** [Yesssssman/epicfightmod#952]
Little Logistics crashes with Epic Fight because locomotive engines are being cast as living entities when they're not in line 79 of LocalPlayerPatch.java, I fixed it by adding a conditional that checks if the parent of "hit" is a living entity. 
![image](https://user-images.githubusercontent.com/95945095/164878722-d2372de9-95dd-4f4f-9eb5-55a39d48976a.png)

**Comment by cleannrooster** [comment]
Now there seems to be a problem with monsters wearing armor, ill keep looking

**Comment by Yesssssman** [comment]
Oh.. I made the code without expecting compatibility with other mods. thanks

**Comment by Yesssssman** [comment]
Fixed in 18.1.5
