### ISSUE TITLE
Customization datapacks not working

### ISSUE THREAD

**Issue by Catomax262** [Yesssssman/epicfightmod#953]
I recently wanted to tweak a knife from the Create: Alloyed Farmer's Delight mod.
I have done everything from the tutorial you made, literally i did everything exactly like you did (by this i mean i literally typed the same things you typed but i replaced the "spear" to "dagger"), but somehow i couldn't manage to change the weapon's attributes and animation. The datapack was successfully installed but it made absolutely no changes. Why? It still has the same attributes and the default fist animation.

**Comment by MetalKnight56** [comment]
This is probably an issue in your datapack structure, make sure you organize all files exacly as he showed in his video. for example:
[datapackname]/data/[modid]/capabilities/weaponds/[registryname].json, if this issue persists after making those changes to your folders, please provide the code in the json file.

**Comment by Catomax262** [comment]
I already have it like so. https://pastebin.com/5CFxM9p6 here's the json i introduced.

**Comment by Yesssssman** [comment]
"armor_negation": 10.0 -> "armor_negation": 10.0,

you missed comma
