### ISSUE TITLE
Cannot dodge no matter what key i have it set to

### ISSUE THREAD

**Issue by jodieLMAO** [Yesssssman/epicfightmod#957]
and yes, I'm in fight mode

**Comment by MetalKnight56** [comment]
Please provide mod version, forge version, and if you are using any other mods. **Please be aware that to use the dodge skill, you need to use the skill book for it, this can be found on the creative tab of the mod.**

**Comment by jodieLMAO** [comment]
oh I wasn't aware of that feature, my bad.
