### ISSUE TITLE
Do you take commissions? 

### ISSUE THREAD

**Issue by Spynathan** [Yesssssman/epicfightmod#96]
I didn't see anywhere else to contact you, hope you don't mind me using github. Just wanted to know if you take commissions and if so what all do you take commissions for? I was interested in commissioning a new weapon type or two, but I'm not sure what all you're open to do. If you wanna contact me on discord you can hit me up at spynathan#6245 or we can just talk here. Thanks for your time and keep up the good work

**Comment by Yesssssman** [comment]
It's MIT license. you're free to do anything if you leave the copyright.

**Comment by Spynathan** [comment]
roger that thanks m8
