### ISSUE TITLE
Client Crash on 1.16.5

### ISSUE THREAD

**Issue by n0itLT** [Yesssssman/epicfightmod#964]
I was fighting and it instantly crashes when swinging a sword. 
The client crashes; however, server does not.
https://pastebin.com/aUCkG8HQ

**Comment by Yesssssman** [comment]
Crash with ice and fire

**Comment by drguest** [comment]
i'm having this exact issue but even now, after i've gotten rid of every mod but epic fight, it still crashes.

https://pastebin.com/yxEr2dDs

**Comment by MetalKnight56** [comment]
> i'm having this exact issue but even now, after i've gotten rid of every mod but epic fight, it still crashes.
> 
> https://pastebin.com/yxEr2dDs

Wrong forge version, use latest.

**Comment by drguest** [comment]
Ah, didn't notice I wasn't on the latest. Many thanks!
