### ISSUE TITLE
[1.16.5] Datapack not working

### ISSUE THREAD

**Issue by Moses24713** [Yesssssman/epicfightmod#965]
Hello, I am struggling to get my datapack working, please let me know why this isn't working or if you have a template I could use that would be great, thanks 👍 

**File structure**
(datapack)/data/iceandfire/capabilities/weapons/tide_trident.JSON

**JSON contents**
{
	"type":"spear",
	"attributes": {
			"common": {
				"armor_negation":10.0,
				"impact":2.0
				"max_strikes":3
			}
		}
}

**Datapack**
[efm.zip](https://github.com/Yesssssman/epicfightmod/files/8596380/efm.zip)

**Comment by Yesssssman** [comment]
you missed comma end of the line of impact value.

**Comment by Moses24713** [comment]
I fixed that but I still doesn't work :|

**Comment by Yesssssman** [comment]
Please open a new tab with the new crash repo
