### ISSUE TITLE
Adds more weapons [1.16.5]

### ISSUE THREAD

**Issue by Edystn** [Yesssssman/epicfightmod#966]
I tri to add weapons from Spartan Weaponary mod and Epic Knight, when i add both mod weapons minecraft give me an error
[latest.log](https://github.com/Yesssssman/epicfightmod/files/8597673/latest.log)
[crash-2022-04-30_21.55.36-fml.txt](https://github.com/Yesssssman/epicfightmod/files/8597676/crash-2022-04-30_21.55.36-fml.txt)
[epicfight.txt](https://github.com/Yesssssman/epicfightmod/files/8597679/epicfight.txt)
I made the config .txt because .toml don't let me upload.

**Comment by Yesssssman** [comment]
> Table with path [custom_weaponry, spartan_flanged_mace_netherite] has been declared twice.

Well, it looks like you declared the same name of the item twice.

**Comment by Edystn** [comment]
When i try to use one at a time, it's work
[epicfight (2).txt](https://github.com/Yesssssman/epicfightmod/files/8597708/epicfight.2.txt)
[knightly-armory_epicfight.txt](https://github.com/Yesssssman/epicfightmod/files/8597709/knightly-armory_epicfight.txt)

**Comment by Yesssssman** [comment]
yeah you have to remove duplicated "spartan_flanged_mace_netherite" item. there's no "spartan_flanged_mace_netherite" in the config file you've posted

**Comment by Edystn** [comment]
Thank you so much, i tried to solve this problem for some weeks!
