### ISSUE TITLE
bow target line hidden with fabulous graphics settings.

### ISSUE THREAD

**Issue by xblackshadow26x** [Yesssssman/epicfightmod#967]
Bow target line (green laser) hidden with fabulous video graphics settings enabled. Also applies for when chocapic shaders are used.

game version: 1.16.5
mod version: 16.5.13
optifine: OptiFine_1.16.5_HD_U_G8

**Comment by Yesssssman** [comment]
It's inevitable incompatibility with MInecraft engine. For now, I can't handle this issue.
