### ISSUE TITLE
Drowned issue on latest build [18.1.5]

### ISSUE THREAD

**Issue by MetalKnight56** [Yesssssman/epicfightmod#968]
Drowneds are bugged a lot. They're inside texture is messed up, i can mostly see through their second texture
![image](https://user-images.githubusercontent.com/77132244/166165201-7456aaac-09d5-4faa-806b-6d2d02470e4a.png)
![image](https://user-images.githubusercontent.com/77132244/166165210-4fae3dfd-7201-4647-b298-a379b181b240.png)
And when a drowned is holding a trident they are able to throw a giant laser of tridents resulting in this madness
![image](https://user-images.githubusercontent.com/77132244/166165235-2e8649c3-7463-407f-b166-4225ec54afaa.png)
![image](https://user-images.githubusercontent.com/77132244/166165238-16e70aef-c701-463d-96d9-4c782c4ff461.png)

**Comment by Yesssssman** [comment]
Is this the last version I uploaded?

**Comment by MetalKnight56** [comment]
yes

> Is this the last version I uploaded?

**Comment by Yesssssman** [comment]
ah sorry, it was written in the title.
btw, are you using a texture or other mod? I still can see the drowned's inner layer

![image](https://user-images.githubusercontent.com/79469058/166165684-b1914b8b-5332-471e-808b-041f902e929e.png)

**Comment by MetalKnight56** [comment]
> 

Yeah i think that was my fault :p i was using a texturepack that glitched it

**Comment by MetalKnight56** [comment]
The trident laser issue also happens with witches when throwing bottles at player 
![image](https://user-images.githubusercontent.com/77132244/166166577-95b59ba3-62a5-48c8-a166-cd013b4600bd.png)

**Comment by Yesssssman** [comment]
Fixed in the 18.1.6
