### ISSUE TITLE
Strange crash that renders the world unusable, seems to be related to entities spawning with armor cause of one of my mods but saw someone else also getting a render issue to, so might as well post a few logs here of it

### ISSUE THREAD

**Issue by MQHP** [Yesssssman/epicfightmod#979]
[crash-2022-05-03_10.43.10-client.txt](https://github.com/Yesssssman/epicfightmod/files/8613040/crash-2022-05-03_10.43.10-client.txt)
[crash-2022-05-03_10.07.38-client.txt](https://github.com/Yesssssman/epicfightmod/files/8613042/crash-2022-05-03_10.07.38-client.txt)
[crash-2022-05-03_10.00.45-client.txt](https://github.com/Yesssssman/epicfightmod/files/8613043/crash-2022-05-03_10.00.45-client.txt)

**Comment by Yesssssman** [comment]
duplicated #976

**Comment by Yesssssman** [comment]
Fixed in 18.1.11
