### ISSUE TITLE
No skill books in the 1.16.5 version and no skills either 

### ISSUE THREAD

**Issue by DemiZombie1** [Yesssssman/epicfightmod#980]
For some reason there are no skill books to learn dodge or block, and i've tried installing previous versions (im using Minecraft 1.16.5, Epic Fighting Mod 16.5.13, and Forge 36.2.20) and it didnt even load the world, please help.

**Comment by Yesssssman** [comment]
Have you checked the creative tab?

![image](https://user-images.githubusercontent.com/79469058/167615125-360c2386-5007-4bb6-a805-742d9efc1632.png)

**Comment by VanilaBOI** [comment]
Have you tried checking if this still happens without any other mods?

**Comment by SanctusStreams** [comment]
Found the issue! It was me LOL there were pages to the creative menu! the books work... my bad X
![Screenshot 2022-05-26 123332](https://user-images.githubusercontent.com/105398391/170532805-447af99c-a1c0-4590-8fd1-52501a21189a.png)
D
