### ISSUE TITLE
Bosses Do not call for loot tables

### ISSUE THREAD

**Issue by LordOzey** [Yesssssman/epicfightmod#982]
I've discovered that with mythical Agriculture, that bosses do not call for Loot tables, when using Epic fight. 
IE: Wither only drops Nether star, and no Essences, no soul, or any other moded loot tables that call for wither death.

I'm sure there is a way to code on death to either drop directly out of the bosses death zone, or from the Amazing Animations of where the other loot drops.

**Comment by Yesssssman** [comment]
Fixed in 18.1.12
