### ISSUE TITLE
Witches doesn't throw potions

### ISSUE THREAD

**Issue by noxyaberry** [Yesssssman/epicfightmod#983]
In the latest version of Epic Fight (18.1.11), witches don't throw potion at the player. They drinking potions though. (Tested with only Epic Fight installed)

**Comment by Yesssssman** [comment]
Fixed in 18.1.12

**Comment by KatakuriDeadpool2300** [comment]
Witches don't throw potions in epic fight version 20.9.2. They only drink potions
