### ISSUE TITLE
Even more incompatibility crashes with Antique Shotgun

### ISSUE THREAD

**Issue by Catomax262** [Yesssssman/epicfightmod#985]
I know. These are annoying to you. This mod is allergic to mods that use a custom item holding animation, or an item that uses the bow's animation. I'm pretty much annoyed too.

**Comment by VanilaBOI** [comment]
Well what's the problem with it. We need an actual crashlog or something to go off of.

**Comment by Catomax262** [comment]
How can I generate one? Even the log doesn't say anything about this

**Comment by Catomax262** [comment]
Also, there were like 2 more of these, that consist on the world never finish loading, I mean it gets stuck at 100%

**Comment by Yesssssman** [comment]
You don't have to generate it, it is automatically created when you launch Minecraft. Go to the folder /.minecraft/logs/debug.log or /.minecraft/logs/latest.log

**Comment by Catomax262** [comment]
I know there's logs, but if you see a "Couldn't look profile options blah blah" thing, ignore it, it's just a little launcher inconvenience. Also, with some modded guns that actually made it to the game, how do I make them stop having the bow animation? They seem to have the bow animation and it kinda makes them look like they just go through the player and not aiming in front. They look awkward.

**Comment by Yesssssman** [comment]
Well, it depends on how the guns in other mods work, but try setting the datapack. You can set the weapon type to "crossbow" which has the most natural animation for the guns.
