### ISSUE TITLE
Katana rendering issue - Latest build [18.1.12]

### ISSUE THREAD

**Issue by MetalKnight56** [Yesssssman/epicfightmod#987]
Katana has misplacement issue on rendering, its holster is not aligned with its blade 
![image](https://user-images.githubusercontent.com/77132244/167221954-94f36e7b-0b40-442c-a7f0-0070cc8577ee.png)

**Comment by soulerwastaken** [comment]
for me its not only with the katana, but with all weapons

**Comment by Yesssssman** [comment]
Fixed in 18.1.13
