### ISSUE TITLE
Weapons don't properly align with animation

### ISSUE THREAD

**Issue by soulerwastaken** [Yesssssman/epicfightmod#988]
I have no idea what could be causing this

![Bild_2022-05-07_232628479](https://user-images.githubusercontent.com/98284436/167272194-e8272425-6ba6-490a-9af1-c0d3006af171.png)

**Comment by MetalKnight56** [comment]
Provide your mod list please

**Comment by soulerwastaken** [comment]
AI-Improvements-1.16.5-0.4.0.jar
backpacked-2.1.6-1.16.5.jar
BetterThirdPerson-Forge-1.16.4-1.7.2.jar
biomeidfixer-1.16.5-1.0.1.s5.jar
Blur-1.1.0-1.jar
chocolate-1.3.0-1.16.4.jar
cleancut-mc1.16-2.2-forge.jar
cloth-config-4.14.64-forge.jar
ColdSweat-r2.1.8.jar
ColdsGrappler(Forge1.16.4)vrs1.0.2.jar
Controlling-7.0.0.28.jar
curios-forge-1.16.5-4.0.5.3.jar
diet-forge-1.16.5-1.0.4.0.jar
DynamicTrees-1.16.5-0.10.0-Beta33.jar
DynamicTreesTerraForged-1.16.5-1.0.0.jar
EpicFightMod-16.5.13.jar
fightnbtintegration-1.16.5-1.4.1.jar
[1.16.5]-Epic-Knights-Armor-and-Weapons-5.11v.jar
Fallingleaves-1.16.3-1.2.4.jar
geckolib-forge-1.16.5-3.0.68.jar
Iceberg-1.16.5-1.0.38.jar
ImmersiveFX 1.0.2 1.16.5.jar
inventorio-1.16-forge-1.6.1.jar
itemstitchingfix-1.16.5-0.2.jar
Kiwi-1.16.5-3.6.1.jar
kotlinforforge-1.17.0-obf.jar
lazydfu-0.1.3.jar
LegendaryTooltips-1.16.5-1.1.6.jar
magnesium-1.5.jar
dynamiclightsreforged-mc1.16.5_v1.0.1.jar
magnesium_extras-mc1.16.5_v1.3.1.jar
mowziesmobs-1.5.24.jar
NyfsQuiver-1.16.5-0.6.3.jar
ostOverhaul-0.1-1.16-Forge.jar
PassableFoliage-1.16.5-2.4.0.jar
Patchouli-1.16.4-53.2.jar
physics-mod-1.0.6_forge.jar
presencefootsteps-r29-1.16.4.jar
Psi 1.16-97.jar
RapidLeafDecay-1.16.5-2.0.0.jar
ReachFix-1.16.5-1.0.1.jar
ShoulderSurfing-1.16.5-2.2.1.jar
ShoulderSurfing-1.16.5-2.2.1.jar
sons-of-sins-1.16.5-1.0.9.jar
SoundFilters-0.14_for_1.16.2.jar
SpartanShields-1.16.5-2.1.2.jar
SpartanWeaponry-1.16.5-2.2.0-rc-2.jar
TerraForged-1.16.5-0.2.15.jar
WaterSource-1.1.40-release-1.16.5.jar
WaveyCapes-forge-1.2.0-mc1.16.5.jar
wizardstaff-1.16.5-1.8.1.jar
mobhealthbar-1-16-5-2.jar
weaponmaster-1-16-5-multi.jar
YungsApi-1.16.4-Forge-13.jar
BetterCaves-Forge-1.16.4-1.1.2.jar
BetterDungeons-1.16.4-1.2.1.jar
BetterMineshafts-Forge-1.16.4-2.0.4.jar
YungsBridges-Forge-1.16.4-1.0.1.jar
YungsExtras-Forge-1.16.4-1.0.jar

**Comment by Yesssssman** [comment]
You have to choose to remove either the Wizard Staff or Epic Fight. Both are incompatible now.

**Comment by soulerwastaken** [comment]
Works now. Thanks.
