### ISSUE TITLE
Config problem again

### ISSUE THREAD

**Issue by bluvuuu** [Yesssssman/epicfightmod#989]
So, for some reason everytime i put in a new config for another mod into the epic fight config, it deletes whatever i put in immediately after booting up the game. i have a feeling that i'm probably just doing something wrong, but i have no idea how to fix it.

**Comment by MetalKnight56** [comment]
1.18+ doens't support the config folder since they are deprecate. If you want to add custom weapondry, create a datapack. If you need help, feel free to ask in the discord server *https://discord.gg/ReqrdPMpBv*
