### ISSUE TITLE
crash with minecolonie

### ISSUE THREAD

**Issue by kyruyuji** [Yesssssman/epicfightmod#990]
Hello;
Having installed your mod (epic fight 1.18.2) in our mod pack, we had crash while using an other mod, MineColonie.
On the preview off the town hall of some city types like asia, true dwarven... on lvl 5, the game crash.
Despite our researches, we couldn't find any solutions to this problem.
Here is attached the crash log
[latest.log](https://github.com/Yesssssman/epicfightmod/files/8647420/latest.log)
.

**Comment by kyruyuji** [comment]
Problem found, i think, but i cannot solve it. In every building which make the game crash we can find armor stand which are not in the other.

**Comment by Yesssssman** [comment]
I'll open a new tab in minecolonies issues tab because this kind of crash is something I can't understand.

**Comment by Yesssssman** [comment]
One thing, which is the version of minecolonies? Since they requires to check if you're using the latest version of minecolonies

**Comment by Hyratrion** [comment]
The version is minecolonies-1.18.2-1.0.673-ALPHA

**Comment by Yesssssman** [comment]
He said it will be fixed in the next update.
