### ISSUE TITLE
Right arm (hand texture part rotates when in combat mode)/ left arm (shoulder texture part rotates when in combat mode)

### ISSUE THREAD

**Issue by MetalKnight56** [Yesssssman/epicfightmod#991]
Red is how it should be, blue is the rotated version(issue)
![Inked2022-05-08_17 26 36_LI](https://user-images.githubusercontent.com/77132244/167314867-9dc8db23-1823-4f6b-a094-ca597cda4688.jpg)
![Inked2022-05-08_17 26 44_LI](https://user-images.githubusercontent.com/77132244/167314882-6897e61f-063b-4bc5-be05-b7001d3122bf.jpg)
![Inked2022-05-08_17 31 26_LI](https://user-images.githubusercontent.com/77132244/167314901-91a2fb63-833b-4ffa-8a23-467a87a3a9d2.jpg)
![Inked2022-05-08_17 31 24_LI](https://user-images.githubusercontent.com/77132244/167314920-94cc251c-c36e-46f9-a205-db3787949c3e.jpg)

As you can see by comparing the marks in the images it strangely rotates around creating some issue when remapping textures for armors

**Comment by MetalKnight56** [comment]
actual duplicate of #770

**Comment by Yesssssman** [comment]
Fixed in 18.1.15
