### ISSUE TITLE
Doesn't work on server but works in single player

### ISSUE THREAD

**Issue by JediM4ster** [Yesssssman/epicfightmod#993]
I have double checked to make sure it's loaded into the client and server side, yet for some reason the animations don't work when on the server. Other things work such as the boss bar and you can still activate battle mode, but the animations don't show up.

**Comment by Yesssssman** [comment]
Have you installed another server API rather than Forge?

**Comment by JediM4ster** [comment]
No, I just installed the forge client into the normal minecraft launcher if that's what you mean. But I can also send a screenshot of all the lists of mods that I'm trying to run with it; if it happens to be a mod incompatibility issue.

![image](https://user-images.githubusercontent.com/72643339/167752081-3a45218c-507b-4fa5-b521-f271ccdf7f4b.png)
![image](https://user-images.githubusercontent.com/72643339/167752121-810d3a9c-d52a-4610-9404-8d4bddb1d2d8.png)

**Comment by JediM4ster** [comment]
But if you're talking about the server jar itself, its just the forge server jar that comes when I go to install forge, and instead of installing the client, I install the server. It's that jar.

**Comment by JediM4ster** [comment]
I actually did go through the list of mods. The thing is that it works on single player just fine, yet when I go on to my forge server that has the same exact mods, then the animations don't work. The ping is under 50 most of the time

**Comment by Yesssssman** [comment]
>I actually did go through the list of mods. The thing is that it works on single player just fine, yet when I go on to my forge server >that has the same exact mods, then the animations don't work. The ping is under 50 most of the time

Did you test all mods?

**Comment by JediM4ster** [comment]
Yes, I individually removed all of them and tried each of them in. The fighting mod works just normally in single player no matter the mods that are or aren't active.

**Comment by MetalKnight56** [comment]
> I actually did go through the list of mods. The thing is that it works on single player just fine, yet when I go on to my forge server that has the same exact mods, then the animations don't work. The ping is under 50 most of the time

Try installing spark and leave the profiler here
https://www.curseforge.com/minecraft/mc-mods/spark - Here's the mod on CF

**Comment by TheOgDiego97** [comment]
I actually have the same problem. I removed all my mods (which are admittedly a lot) and Epic Fight Mod still won't load on the server on it's own. It works no problem even with all my mods on client, it just won't load on the server. Any idea what else I could try?

Minecraft 1.16.5
Forge 36.2.8
Epic Fight Mod 1.16.13 (also tried down to version 1.16.10)

**Comment by JediM4ster** [comment]
Alright I'll just try deleting all the other mods once again and see if I missed anything. If not I'll try the spark thing.

**Comment by JediM4ster** [comment]
> > I actually did go through the list of mods. The thing is that it works on single player just fine, yet when I go on to my forge server that has the same exact mods, then the animations don't work. The ping is under 50 most of the time
> 
> Try installing spark and leave the profiler here https://www.curseforge.com/minecraft/mc-mods/spark - Here's the mod on CF

I tried using the spark mod, it kept crashing every time I went to upload the profile.. any other ways to do this? I have no problems with ram or my pc in terms of performance.

**Comment by JediM4ster** [comment]
Here's the video of proof that it's working in single player. And then as you can see on the server it doesn't. There's no server console errors. https://youtu.be/96gDbhlCmAA

**Comment by Yesssssman** [comment]
Could you check if the dedicated server also has installed the epicfight? Both epicfight versions must be the same.

**Comment by JediM4ster** [comment]
> Could you check if the dedicated server also has installed the epicfight? Both epicfight versions must be the same.

![image](https://user-images.githubusercontent.com/72643339/169714027-7ba14d8e-6f7b-457e-87b9-ade8bd306b4f.png)
![image](https://user-images.githubusercontent.com/72643339/169714035-08727289-8ff0-4493-b673-9ffd814fdda3.png)

It seems to have installed correctly unless I'm missing some files?

**Comment by Yesssssman** [comment]
well, this is not enough information. And I found the incompatibility mark on your server list.

![image](https://user-images.githubusercontent.com/79469058/169724264-6a742ee4-51c4-4127-a2a6-b56a8bb98916.png)

Are you using another mod server? Like magma, mohist server. They sometimes break down the server.

**Comment by JediM4ster** [comment]
> well, this is not enough information. And I found the incompatibility mark on your server list.
> 
> ![image](https://user-images.githubusercontent.com/79469058/169724264-6a742ee4-51c4-4127-a2a6-b56a8bb98916.png)
> 
> Are you using another mod server? Like magma, mohist server. They sometimes break down the server.

No, I just have the jar that came from the forge installer and then I uploaded it into the server files. I’ll try to install it again. I can show you all the server files if you like. Does it being on a public host also make a difference? I have it whitelisted for just my friend and I. It’s strange because I took it out and literally the only mod I have is epic fighting one.

**Comment by Yesssssman** [comment]
If you don't mind, please send me the all server files.

**Comment by JediM4ster** [comment]
> If you don't mind, please send me the all server files.

This is configured to run as a local host, but it's the same files from the server other than the start.bat I made. https://www.mediafire.com/file/e0g4ddq2d5a2mrx/Forge_1.16.5.zip/file

**Comment by Yesssssman** [comment]
.... your server targeted the vanilla .jar file. I guess somebody changed the name of `minecraft_server.1.16.5` to `forge-1.16.5`, which is causing confusion when setting up the bat file. Tweak your bat file as below.

```
@echo off
java -Xmx5G -Xms5G -jar forge-1.16.5.jar nogui
PAUSE
```
to
```
@echo off
java -Xmx5G -Xms5G -jar forge-1.16.5-36.2.35.jar nogui
PAUSE
```
