### ISSUE TITLE
Combat system and animation polish

### ISSUE THREAD

**Issue by rtx2090ti** [Yesssssman/epicfightmod#996]
I love this mod, it's quite unique and probably the only one of it's kind. However, I have two large complaints about it

- The combat mechanic doesnt seem very integrated into the game, pressing a button to switch between two entirely different combat modes kinda ruins the immersion to be honest

A way of solving this could be to have two stances, and disabling the vanilla combat (At least the "combat" part of it) entirely. Like a basic stance for blocks, food items and tools which only gives you access to a fairly simple moveset but enables actions like mining and placing blocks, and a combat stance that automatically toggles on when you're holding a valid item in your main hand (Configurable in a config file), giving you the combos and special moves associated with the weapon classes. This could be toggled off (Or on) with, again, the press of a button, switching you to the basic stance

- The animations

Most of the movement animations are quite rough and seem to be lagging behind, things like sprint-jumping and just running around look very awkward and not fluid at all. The attack animations look fine although, they could use some smoothing aswell. Taking your finger off the movement keys will stop your movement, but your character will continue to walk/run for about a whole second even after you've completely stopped, which makes them look like a professional moonwalker

This is about it, thank you for reading through my little suggestion

**Comment by rtx2090ti** [comment]
I just realised I forgot to add a label... Oh well

**Comment by TotallyCooki** [comment]
https://www.curseforge.com/minecraft/texture-packs/epic-fight-animations you may like this for some smoother animations! :) doesn't change any of the mechanics tho so that's up to yesman :)

**Comment by rtx2090ti** [comment]
Oh wow, I didnt even know there were animation packs for this, thanks!
