### ISSUE TITLE
Mod Causing issues in multiplayer.

### ISSUE THREAD

**Issue by ItsCohe** [Yesssssman/epicfightmod#997]
Im not sure why it does this but for some reason whenever my friend joins for him all of the world textures disappear. The mod works just fine in single player.

**Comment by MetalKnight56** [comment]
Please provide minecraft version and mod verison, if possible also provide forge's version

**Comment by ItsCohe** [comment]
everything is 1.8.2

**Comment by ItsCohe** [comment]
Okay after some testing we found that optfine is what is conflicting with epic fight

**Comment by Yesssssman** [comment]
Optifine issues are hard to fix for now.
