### ISSUE TITLE
Crash with Ender Dragon

### ISSUE THREAD

**Issue by SeanChengN** [Yesssssman/epicfightmod#999]
Crash on encounter with the ender dragon.
Forge 40.1.19
Epic Fight 18.1.13-beta
https://pastebin.com/M4mWfTsM

**Comment by Yesssssman** [comment]
Try downgrading the forge version to 41.1.0

**Comment by SeanChengN** [comment]
> Try downgrading the forge version to 41.1.0

40.1.0 crash again.
https://pastebin.com/f2NGYS8w

**Comment by Yesssssman** [comment]
Can you see if this crash keeps happening when you removed all your installed mods?

**Comment by SeanChengN** [comment]
> Can you see if this crash keeps happening when you removed all your installed mods?

It runs well without any mods. In addition, I also found that there will be no crash in the creative mode, It may be because the ender dragon will not land in the creative mode. Only in the survival mode, game crash when the ender dragon wants to land.

In addition, I may need to test the compatibility of each mod.

**Comment by Yesssssman** [comment]
Yes, it would be very helpful if you could pinpoint the specific mod causing the crash.

**Comment by Yesssssman** [comment]
Hello, Did you summon the dragon on overworld?

**Comment by SeanChengN** [comment]
> Hello, Did you summon the dragon on overworld?

No, in the end, a naturally occurring ender dragon.

**Comment by Yesssssman** [comment]
Could you try removing Progressive Bosses?

**Comment by SeanChengN** [comment]
> Could you try removing Progressive Bosses?

Still crash

**Comment by SeanChengN** [comment]
> Could you try removing Progressive Bosses?

Finally I found the reason, a datapack: [nullscape-v1-1-1.zip](https://www.planetminecraft.com/data-pack/nullscape/)

And I use [openloader](https://www.curseforge.com/minecraft/mc-mods/open-loader) to load it

**Comment by Yesssssman** [comment]
Fixed in 18.1.18
